### ISSUE TITLE
[STORM-10] Exception when tick tuples are enabled on a trident topology

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3852]
<p><a href="https://github.com/nathanmarz/storm/issues/637" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/637</a></p>

<p>When tick tuples are enabled for a trident topology, the following exception is produced:</p>

<p>java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Long cannot be cast to    storm.trident.topology.TransactionAttempt<br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:87)<br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:58)<br/>
at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62)<br/>
at backtype.storm.daemon.executor$fn_<em>4050$fn</em><em>4059$fn</em>_4106.invoke(executor.clj:658)<br/>
at backtype.storm.util$async_loop$fn__465.invoke(util.clj:377)<br/>
at clojure.lang.AFn.run(AFn.java:24)<br/>
at java.lang.Thread.run(Thread.java:724)<br/>
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to storm.trident.topology.TransactionAttempt<br/>
at storm.trident.spout.TridentSpoutCoordinator.execute(TridentSpoutCoordinator.java:46)<br/>
at backtype.storm.topology.BasicBoltExecutor.execute(BasicBoltExecutor.java:32)<br/>
at backtype.storm.daemon.executor$fn_<em>4050$tuple_action_fn</em>_4052.invoke(executor.clj:566)<br/>
at backtype.storm.daemon.executor$mk_task_receiver$fn__3976.invoke(executor.clj:348)<br/>
at backtype.storm.disruptor$clojure_handler$reify__1606.onEvent(disruptor.clj:43)<br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:84)<br/>
... 6 more</p>

<p>Ideally there would be an exception thrown at deploy time saying tick tuples aren't supported for trident topologies.</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-10" target="_blank">Exception when tick tuples are enabled on a trident topology</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:05+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
