### ISSUE TITLE
[STORM-80] NPE caused by TridentBoltExecutor reusing TrackedBatches between batch groups

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3922]
<p><a href="https://github.com/nathanmarz/storm/issues/421" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/421</a></p>

<p>I'm seeing intermittent errors caused by SubtopologyBolt.execute being called with a BatchInfo whose ProcessorContext is set up for a different Batch Group. In particular I'm seeing null pointer exceptions from PartitionPersistProcessor because its state fields were never set up correctly.</p>

<p>The best I can tell the id key (IBatchID) being used for the _batches map in TridentBoltExecutor is not unique between batch groups. As a result the tracked batch will have been initialized for a different Batch Group and set of processors.</p>

<p>I hoped to be able to track down the source of this issue but can't determine where the BatchIDs are being added to the tuples.</p>

<p>If it matters, my topology has two streams each reading from their own OpaqueTransactionalKafka spout w/different topics.</p>

<p>Backtrace:</p>

<p>65108 <span class="error">&#91;Thread-25&#93;</span> ERROR backtype.storm.daemon.executor - <br/>
java.lang.RuntimeException: java.lang.NullPointerException<br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:87) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:58) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>3551$fn</em><em>3563$fn</em>_3610.invoke(executor.clj:712) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at backtype.storm.util$async_loop$fn__436.invoke(util.clj:377) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:722) <span class="error">&#91;na:1.7.0_09&#93;</span><br/>
Caused by: java.lang.NullPointerException: null<br/>
at storm.trident.planner.processor.PartitionPersistProcessor.execute(PartitionPersistProcessor.java:59) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at storm.trident.planner.SubtopologyBolt$InitialReceiver.receive(SubtopologyBolt.java:189) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at storm.trident.planner.SubtopologyBolt.execute(SubtopologyBolt.java:129) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:352) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>3551$tuple_action_fn</em>_3553.invoke(executor.clj:607) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at backtype.storm.daemon.executor$mk_task_receiver$fn__3474.invoke(executor.clj:379) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at backtype.storm.disruptor$clojure_handler$reify__3011.onEvent(disruptor.clj:43) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:84) ~<span class="error">&#91;storm-0.9.0-wip4.jar:na&#93;</span><br/>
... 6 common frames omitted</p>

<p>Also, I'm only seeing this in LocalCluster mode, not in production.</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-80" target="_blank">NPE caused by TridentBoltExecutor reusing TrackedBatches between batch groups</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:58+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
