### ISSUE TITLE
[STORM-85] IsolationScheduler fails due to NoSuchElementException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3927]
<p><a href="https://github.com/nathanmarz/storm/issues/738" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/738</a></p>

<p>Repro step:<br/>
1. update Nimbus config, add following lines, and re-start Nimbus</p>

<p>storm.scheduler: backtype.storm.scheduler.IsolationScheduler</p>

<p>isolation.scheduler.machines: <br/>
    "WordCountIso": 5<br/>
Nimbus failed to re-start and "NullPointerException" found in log files:<br/>
2013-10-28 00:46:32 TNonblockingServer <span class="error">&#91;ERROR&#93;</span> Unexpected exception while invoking!<br/>
java.util.NoSuchElementException<br/>
at java.util.HashMap$HashIterator.nextEntry(Unknown Source)<br/>
at java.util.HashMap$KeyIterator.next(Unknown Source)<br/>
at backtype.storm.scheduler.IsolationScheduler$remove_elem_from_set_BANG_.invoke(IsolationScheduler.clj:140)<br/>
at backtype.storm.scheduler.IsolationScheduler$schedule.invoke(IsolationScheduler.clj:190)<br/>
at backtype.storm.scheduler.IsolationScheduler.schedule(Unknown Source)<br/>
at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)<br/>
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
at java.lang.reflect.Method.invoke(Unknown Source)<br/>
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)<br/>
at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)<br/>
at backtype.storm.daemon.nimbus$computenew_topology_<em>GT_executor</em>_GT_node_PLUS_port.invoke(nimbus.clj:587)<br/>
at backtype.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:674)<br/>
at clojure.lang.RestFn.invoke(RestFn.java:410)<br/>
at backtype.storm.daemon.nimbus$fn_<em>3812$exec_fn</em><em>1239</em><em>auto</em><em>$reify</em>_3827.submitTopologyWithOpts(nimbus.clj:965)<br/>
at backtype.storm.daemon.nimbus$fn_<em>3812$exec_fn</em><em>1239</em><em>auto</em><em>$reify</em>_3827.submitTopology(nimbus.clj:973)<br/>
at backtype.storm.generated.Nimbus$Processor$submitTopology.getResult(Nimbus.java:1223)<br/>
at backtype.storm.generated.Nimbus$Processor$submitTopology.getResult(Nimbus.java:1211)<br/>
at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:32)<br/>
at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:34)<br/>
at org.apache.thrift7.server.TNonblockingServer$FrameBuffer.invoke(TNonblockingServer.java:632)<br/>
at org.apache.thrift7.server.THsHaServer$Invocation.run(THsHaServer.java:201)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
at java.lang.Thread.run(Unknown Source)</p>

<p>Possible root cause:<br/>
missing null checking in IsolationScheduler.remove-elem-from-set!() and IsolationScheduler.-schedule()</p>

<p>fixing:<br/>
/src/clj/backtype/storm/scheduler/IsolationScheduler.clj</p>

<p>line 140-142:</p>

<p>   (if (-> aset .iterator .hasNext) // add hasNext() checking here<br/>
    (let <span class="error">&#91;elem (-> aset .iterator .next)&#93;</span><br/>
      (.remove aset elem)<br/>
      elem<br/>
      )))</p>

<p>line 191:</p>

<p>  (if (not-nil? executors-set)// add null checking here. if missing this line, there will be NullPointerException when call cluster.assign()<br/>
    (.assign cluster slot top-id executors-set)))</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-85" target="_blank">IsolationScheduler fails due to NoSuchElementException</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:48+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
