### ISSUE TITLE
[STORM-91] Registering already registered serializations causes strange runtime errors

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3933]
<p><a href="https://github.com/nathanmarz/storm/issues/279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/279</a></p>

<p>e.g. if registering String:</p>

<p>java.lang.RuntimeException: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: char[]<br/>
Note: To register this class use: kryo.register(char[].class);<br/>
Serialization trace:<br/>
value (java.lang.String)<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:82)<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:55)<br/>
    at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:56)<br/>
    at backtype.storm.disruptor$consume_loop_STAR_$fn__1596.invoke(disruptor.clj:67)<br/>
    at backtype.storm.util$async_loop$fn__465.invoke(util.clj:377)<br/>
    at clojure.lang.AFn.run(AFn.java:24)<br/>
    at java.lang.Thread.run(Thread.java:662)<br/>
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: char[]<br/>
Note: To register this class use: kryo.register(char[].class);<br/>
Serialization trace:<br/>
value (java.lang.String)<br/>
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:495)<br/>
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)<br/>
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:554)<br/>
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:77)<br/>
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:18)<br/>
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:472)<br/>
    at backtype.storm.serialization.KryoValuesSerializer.serializeInto(KryoValuesSerializer.java:27)<br/>
    at backtype.storm.serialization.KryoTupleSerializer.serialize(KryoTupleSerializer.java:27)<br/>
    at backtype.storm.daemon.worker$mk_transfer_fn$fn_<em>4120$fn</em>_4124.invoke(worker.clj:99)<br/>
    at backtype.storm.util$fast_list_map.invoke(util.clj:770)<br/>
    at backtype.storm.daemon.worker$mk_transfer_fn$fn__4120.invoke(worker.clj:99)<br/>
    at backtype.storm.daemon.executor$start_batch_transfer_<em>GT_worker_handler_BANG</em>$fn__3898.invoke(executor.clj:205)<br/>
    at backtype.storm.disruptor$clojure_handler$reify__1584.onEvent(disruptor.clj:43)<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:79)<br/>
    ... 6 more<br/>
Caused by: java.lang.IllegalArgumentException: Class is not registered: char[]<br/>
Note: To register this class use: kryo.register(char[].class);<br/>
    at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:426)<br/>
    at com.esotericsoftware.kryo.Kryo.getSerializer(Kryo.java:446)<br/>
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:477)<br/>
    ... 19 more<br/>
This error catching should happen at registration time (ideally in Kryo itself). Or, even better, Storm should allow duplicate registrations and skip any duplicates when initializing Kryo. This is consistent with how serialization registration works w.r.t. component configs.</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-91" target="_blank">Registering already registered serializations causes strange runtime errors</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:19+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
