### ISSUE TITLE
[STORM-99] Multitple topologies assigned to one port

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3941]
<p><a href="https://github.com/nathanmarz/storm/issues/586" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/586</a></p>

<p>When I submitted a lot of topologies(about 15) to the storm cluster, one supervisor throw a runtime exception. I believe that the exception should not be thrown in the normal. The version of the storm is 0.8.1</p>

<p>I tried to reproduce this exception, but failed and after review the nimbus.clj & supervisor.clj, I found nothing. Is it a known bug?</p>

<p>Stack Info:<br/>
2013-06-06 14:55:00 supervisor <span class="error">&#91;INFO&#93;</span> Shut down 212aa36c-81a0-4d4d-8104-759d9f128669:f66a0118-7267-4460-9f35-58435c92dc10<br/>
2013-06-06 14:55:00 supervisor <span class="error">&#91;INFO&#93;</span> Shutting down and clearing state for id 8db35c17-9e69-49db-86c3-f7dc90fa42be. Current supervisor time: 1370501700. State: :disallowed, Heartbeat: #backtype.storm.daemon.common.WorkerHeartbeat{:time-secs 1370501699, :storm-id "case_10-537-1370488327", :executors #</p>
{[7 7] [14 14]}
<p>, :port 6708}<br/>
2013-06-06 14:55:00 supervisor <span class="error">&#91;INFO&#93;</span> Shutting down 212aa36c-81a0-4d4d-8104-759d9f128669:8db35c17-9e69-49db-86c3-f7dc90fa42be<br/>
2013-06-06 14:55:00 supervisor <span class="error">&#91;INFO&#93;</span> Shut down 212aa36c-81a0-4d4d-8104-759d9f128669:8db35c17-9e69-49db-86c3-f7dc90fa42be<br/>
2013-06-06 14:55:03 event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.lang.RuntimeException: Should not have multiple topologies assigned to one port<br/>
at backtype.storm.daemon.supervisor$read_assignments$fn__4510.doInvoke(supervisor.clj:45)<br/>
at clojure.lang.RestFn.invoke(RestFn.java:421)<br/>
at clojure.core$merge_with$merge_entry__4159.invoke(core.clj:2645)<br/>
at clojure.core$reduce1.invoke(core.clj:880)<br/>
at clojure.core$merge_with$merge2__4161.invoke(core.clj:2648)<br/>
at clojure.core$reduce1.invoke(core.clj:880)<br/>
at clojure.core$reduce1.invoke(core.clj:871)<br/>
at clojure.core$merge_with.doInvoke(core.clj:2649)<br/>
at clojure.lang.RestFn.applyTo(RestFn.java:139)<br/>
at clojure.core$apply.invoke(core.clj:603)<br/>
at backtype.storm.daemon.supervisor$read_assignments.invoke(supervisor.clj:48)<br/>
at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__4692.invoke(supervisor.clj:270)<br/>
at backtype.storm.event$event_manager$fn__2484.invoke(event.clj:24)<br/>
at clojure.lang.AFn.run(AFn.java:24)<br/>
at java.lang.Thread.run(Thread.java:679)<br/>
2013-06-06 14:55:03 util <span class="error">&#91;INFO&#93;</span> Halting process: ("Error when processing an event")</p>

<p>nimbus log within the crash time<br/>
2013-06-06 14:54:44 nimbus <span class="error">&#91;INFO&#93;</span> Delaying event :remove for 0 secs for case_9-536-1370488243<br/>
2013-06-06 14:54:44 nimbus <span class="error">&#91;INFO&#93;</span> Updated case_9-536-1370488243 with status {:type :killed, :kill-time-secs 0}<br/>
2013-06-06 14:54:45 nimbus <span class="error">&#91;INFO&#93;</span> Killing topology: case_9-536-1370488243<br/>
2013-06-06 14:54:52 EvenScheduler <span class="error">&#91;INFO&#93;</span> Available slots: (<span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6705&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6706&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6709&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6710&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6711&#93;</span>)<br/>
2013-06-06 14:54:52 nimbus <span class="error">&#91;INFO&#93;</span> Setting new assignment for topology id case_23-527-1370478607: #backtype.storm.daemon.common.Assignment{:master-code-dir "/home/admin/install/storm-local/nimbus/stormdist/case_23-527-1370478607", :node->host </p>
{"212aa36c-81a0-4d4d-8104-759d9f128669" "dev163015.sqa.cm6"}
<p>, :executor->node+port </p>
{[2 2] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6706], [3 3] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6709], [4 4] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6710], [5 5] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6711], [6 6] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6705], [7 7] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6706], [8 8] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6709], [9 9] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6710], [10 10] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6711], [11 11] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6705], [12 12] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6706], [13 13] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6709], [1 1] ["212aa36c-81a0-4d4d-8104-759d9f128669" 6705]}
<p>, :executor->start-time-secs {<span class="error">&#91;2 2&#93;</span> 1370501692, <span class="error">&#91;3 3&#93;</span> 1370501692, <span class="error">&#91;4 4&#93;</span> 1370501692, <span class="error">&#91;5 5&#93;</span> 1370501692, <span class="error">&#91;6 6&#93;</span> 1370501692, <span class="error">&#91;7 7&#93;</span> 1370501692, <span class="error">&#91;8 8&#93;</span> 1370501692, <span class="error">&#91;9 9&#93;</span> 1370501692, <span class="error">&#91;10 10&#93;</span> 1370501692, <span class="error">&#91;11 11&#93;</span> 1370501692, <span class="error">&#91;12 12&#93;</span> 1370501692, <span class="error">&#91;13 13&#93;</span> 1370501692, <span class="error">&#91;1 1&#93;</span> 1370501692}}<br/>
2013-06-06 14:54:52 nimbus <span class="error">&#91;INFO&#93;</span> Cleaning up case_2-486-1370440841<br/>
2013-06-06 14:54:52 nimbus <span class="error">&#91;INFO&#93;</span> Cleaning up case_9-536-1370488243<br/>
2013-06-06 14:54:52 nimbus <span class="error">&#91;INFO&#93;</span> Cleaning up case_7-490-1370441170<br/>
2013-06-06 14:54:53 nimbus <span class="error">&#91;INFO&#93;</span> Delaying event :remove for 0 secs for case_10-537-1370488327<br/>
2013-06-06 14:54:53 nimbus <span class="error">&#91;INFO&#93;</span> Updated case_10-537-1370488327 with status {:type :killed, :kill-time-secs 0}<br/>
2013-06-06 14:54:53 nimbus <span class="error">&#91;INFO&#93;</span> Killing topology: case_10-537-1370488327<br/>
2013-06-06 14:55:03 EvenScheduler <span class="error">&#91;INFO&#93;</span> Available slots: (<span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6700&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6701&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6702&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6703&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6704&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6705&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6706&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6707&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6708&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6709&#93;</span>)<br/>
2013-06-06 14:55:03 EvenScheduler <span class="error">&#91;INFO&#93;</span> Available slots: (<span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6705&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6706&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6707&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6708&#93;</span> <span class="error">&#91;"212aa36c-81a0-4d4d-8104-759d9f128669" 6709&#93;</span>)</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-99" target="_blank">Multitple topologies assigned to one port</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2015-01-22T16:12:02+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=egoslin">egoslin</a>:</i>
<p>Was this issue fixed by <a href="https://issues.apache.org/jira/browse/STORM-155" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-155</a> ?<br/>
We receive this error in 0.9.2</p>

<p>2015-01-22 06:25:45.138 b.s.event []<span class="error">&#91;Thread-1&#93;</span><span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.lang.RuntimeException: Should not have multiple topologies assigned to one port<br/>
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~<span class="error">&#91;na:1.8.0_11&#93;</span><br/>
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~<span class="error">&#91;na:1.8.0_11&#93;</span><br/>
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~<span class="error">&#91;na:1.8.0_11&#93;</span><br/>
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~<span class="error">&#91;na:1.8.0_11&#93;</span><br/>
at clojure.lang.Reflector.invokeConstructor(Reflector.java:180) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.util$throw_runtime.doInvoke(util.clj:753) ~<span class="error">&#91;storm-core-0.9.2-incubating.jar:0.9.2-incubating&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:408) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.supervisor$read_assignments$fn__6143.doInvoke(supervisor.clj:65) ~<span class="error">&#91;storm-core-0.9.2-incubating.jar:0.9.2-incubating&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:421) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$merge_with$merge_entry__4279.invoke(core.clj:2698) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$reduce1.invoke(core.clj:896) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$merge_with$merge2__4281.invoke(core.clj:2701) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$reduce1.invoke(core.clj:896) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$reduce1.invoke(core.clj:887) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$merge_with.doInvoke(core.clj:2702) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RestFn.applyTo(RestFn.java:139) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.supervisor$read_assignments.invoke(supervisor.clj:64) ~<span class="error">&#91;storm-core-0.9.2-incubating.jar:0.9.2-incubating&#93;</span><br/>
at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__6330.invoke(supervisor.clj:303) ~<span class="error">&#91;storm-core-0.9.2-incubating.jar:0.9.2-incubating&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2378.invoke(event.clj:39) ~<span class="error">&#91;storm-core-0.9.2-incubating.jar:0.9.2-incubating&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Unknown Source) <span class="error">&#91;na:1.8.0_11&#93;</span></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/browse/STORM-155" title="Storm rebalancing code causes multiple topologies assigned to a single port" class="issue-link" data-issue-key="STORM-155"><del>STORM-155</del></a> was fixed as a part of 0.9.3, so 0.9.2 still has the issue in it.  <a href="https://issues.apache.org/jira/browse/STORM-155" title="Storm rebalancing code causes multiple topologies assigned to a single port" class="issue-link" data-issue-key="STORM-155"><del>STORM-155</del></a> also only reduced the window in which the race condition causes the supervisor to crash because it is in the middle of downloading scheduling changes while nimbus is in the middle of uploading them.  There is still the possibility that if nimbus crashes in the middle of uploading the changes, or for some other reason nimbus takes a really long time to upload all the changes the supervisor will still crash after the retries are exhausted.</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-155">STORM-155</a>]</i>
