### ISSUE TITLE
[STORM-113] TridentUtils.thriftDeserialize() is used unsafely when running in local mode.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3955]
<p><a href="https://github.com/nathanmarz/storm/issues/500" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/500</a></p>

<p>When running a trident topology with multiple workers in local mode, each worker runs as a thread in a single jvm. These worker threads call TridentUtils.thriftDeserialize() concurrently when loading the (serialized) topology. However, this method is not threadsafe. In particular, it uses a static reference to a TDeserializer, which in turn uses an instance of TMemoryInputTransport, which is stateful. The end result is sporadic and nondeterministic Thrift exceptions when starting the workers.</p>

<p>This is not difficult to fix, but I'm not sure which approach the committers want to take. I made the deserializer (and serializer) ThreadLocal vars.</p>

<p>----------<br/>
juhoautio: Thanks for explaining the problem! This issue made my test fail* occasionally when trying to submit a topology to a local cluster.</p>

<p>For now I set number of workers & max parallelism to 1, but eventually I'd like to be able to enable some parallelism. I'm not sure if both parameters are significant, but here's a code extract for rerefence:</p>

<p>conf = new Config();<br/>
conf.setNumWorkers(1);<br/>
conf.setMaxTaskParallelism(1);<br/>
// ...<br/>
cluster = new LocalCluster();<br/>
cluster.submitTopology(.., conf, ..);<br/>
With this configuration the problem hasn't happened any more.</p>

<p>*) Stacktrace for the error (happens occasionally when number of workers is set to 2) :</p>

<p>2629 <span class="error">&#91;Thread-9&#93;</span> ERROR backtype.storm.daemon.worker  - Error on initialization of server mk-worker<br/>
java.lang.RuntimeException: org.apache.thrift7.TException: Negative length: -72553216<br/>
    at storm.trident.util.TridentUtils.thriftDeserialize(TridentUtils.java:111)<br/>
    at storm.trident.planner.PartitionNode.readObject(PartitionNode.java:33)<br/>
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/>
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
    at java.lang.reflect.Method.invoke(Method.java:606)<br/>
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)<br/>
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1891)<br/>
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1796)<br/>
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1348)<br/>
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)<br/>
    at java.util.HashMap.readObject(HashMap.java:1183)<br/>
    at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)<br/>
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
    at java.lang.reflect.Method.invoke(Method.java:606)<br/>
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)<br/>
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1891)<br/>
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1796)<br/>
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1348)<br/>
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1989)<br/>
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1913)<br/>
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1796)<br/>
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1348)<br/>
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1989)<br/>
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1913)<br/>
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1796)<br/>
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1348)<br/>
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)<br/>
    at backtype.storm.utils.Utils.deserialize(Utils.java:64)<br/>
    at backtype.storm.utils.Utils.getSetComponentObject(Utils.java:199)<br/>
    at backtype.storm.daemon.task$get_task_object.invoke(task.clj:56)<br/>
    at backtype.storm.daemon.task$mk_task_data$fn__3766.invoke(task.clj:158)<br/>
    at backtype.storm.util$assoc_apply_self.invoke(util.clj:731)<br/>
    at backtype.storm.daemon.task$mk_task_data.invoke(task.clj:152)<br/>
    at backtype.storm.daemon.task$mk_task.invoke(task.clj:163)<br/>
    at backtype.storm.daemon.executor$mk_executor$fn__3922.invoke(executor.clj:267)<br/>
    at clojure.core$map$fn__4087.invoke(core.clj:2432)<br/>
    at clojure.lang.LazySeq.sval(LazySeq.java:42)<br/>
    at clojure.lang.LazySeq.seq(LazySeq.java:60)<br/>
    at clojure.lang.RT.seq(RT.java:473)<br/>
    at clojure.core$seq.invoke(core.clj:133)<br/>
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)<br/>
    at clojure.core.protocols$fn__5875.invoke(protocols.clj:54)<br/>
    at clojure.core.protocols$fn_<em>5828$G</em><em>5823</em>_5841.invoke(protocols.clj:13)<br/>
    at clojure.core$reduce.invoke(core.clj:6030)<br/>
    at clojure.core$into.invoke(core.clj:6077)<br/>
    at backtype.storm.daemon.executor$mk_executor.invoke(executor.clj:267)<br/>
    at backtype.storm.daemon.worker$fn_<em>4348$exec_fn</em><em>1228</em><em>auto</em>__<em>4349$iter</em><em>4354</em><em>4358$fn</em>_4359.invoke(worker.clj:354)<br/>
    at clojure.lang.LazySeq.sval(LazySeq.java:42)<br/>
    at clojure.lang.LazySeq.seq(LazySeq.java:60)<br/>
    at clojure.lang.Cons.next(Cons.java:39)<br/>
    at clojure.lang.LazySeq.next(LazySeq.java:92)<br/>
    at clojure.lang.RT.next(RT.java:587)<br/>
    at clojure.core$next.invoke(core.clj:64)<br/>
    at clojure.core$dorun.invoke(core.clj:2726)<br/>
    at clojure.core$doall.invoke(core.clj:2741)<br/>
    at backtype.storm.daemon.worker$fn_<em>4348$exec_fn</em><em>1228</em><em>auto</em>___4349.invoke(worker.clj:354)<br/>
    at clojure.lang.AFn.applyToHelper(AFn.java:185)<br/>
    at clojure.lang.AFn.applyTo(AFn.java:151)<br/>
    at clojure.core$apply.invoke(core.clj:601)<br/>
    at backtype.storm.daemon.worker$fn_<em>4348$mk_worker</em>_4404.doInvoke(worker.clj:323)<br/>
    at clojure.lang.RestFn.invoke(RestFn.java:512)<br/>
    at backtype.storm.daemon.supervisor$fn__4807.invoke(supervisor.clj:467)<br/>
    at clojure.lang.MultiFn.invoke(MultiFn.java:177)<br/>
    at backtype.storm.daemon.supervisor$sync_processes$iter_<em>4684</em><em>4688$fn</em>_4689.invoke(supervisor.clj:249)<br/>
    at clojure.lang.LazySeq.sval(LazySeq.java:42)<br/>
    at clojure.lang.LazySeq.seq(LazySeq.java:60)<br/>
    at clojure.lang.RT.seq(RT.java:473)<br/>
    at clojure.core$seq.invoke(core.clj:133)<br/>
    at clojure.core$dorun.invoke(core.clj:2725)<br/>
    at clojure.core$doall.invoke(core.clj:2741)<br/>
    at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:237)<br/>
    at clojure.lang.AFn.applyToHelper(AFn.java:161)<br/>
    at clojure.lang.AFn.applyTo(AFn.java:151)<br/>
    at clojure.core$apply.invoke(core.clj:603)<br/>
    at clojure.core$partial$fn__4070.doInvoke(core.clj:2343)<br/>
    at clojure.lang.RestFn.invoke(RestFn.java:397)<br/>
    at backtype.storm.event$event_manager$fn__2507.invoke(event.clj:24)<br/>
    at clojure.lang.AFn.run(AFn.java:24)<br/>
    at java.lang.Thread.run(Thread.java:724)<br/>
Caused by: org.apache.thrift7.TException: Negative length: -72553216<br/>
    at org.apache.thrift7.protocol.TBinaryProtocol.checkReadLength(TBinaryProtocol.java:388)<br/>
    at org.apache.thrift7.protocol.TBinaryProtocol.readBinary(TBinaryProtocol.java:363)<br/>
    at org.apache.thrift7.protocol.TProtocolUtil.skip(TProtocolUtil.java:102)<br/>
    at org.apache.thrift7.protocol.TProtocolUtil.skip(TProtocolUtil.java:60)<br/>
    at backtype.storm.generated.Grouping.readValue(Grouping.java:353)<br/>
    at org.apache.thrift7.TUnion.read(TUnion.java:135)<br/>
    at org.apache.thrift7.TDeserializer.deserialize(TDeserializer.java:69)<br/>
    at storm.trident.util.TridentUtils.thriftDeserialize(TridentUtils.java:108)<br/>
    ... 79 more<br/>
2653 <span class="error">&#91;Thread-9&#93;</span> INFO  backtype.storm.util  - Halting process: ("Error on initialization")</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-113" target="_blank">TridentUtils.thriftDeserialize() is used unsafely when running in local mode.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Adam Lewis" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=supercargo">supercargo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-05-02T20:14:46+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=supercargo">supercargo</a>:</i>
<p>Are github pull requests still acceptable since the move to Apache?  I submitted PR #26 for this issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/26#issuecomment-42048346" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/26#issuecomment-42048346</a></p>

<p>    +1 the code changes look good to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/26#issuecomment-42049580" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/26#issuecomment-42049580</a></p>

<p>    +1 Looks good.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/26#issuecomment-42050174" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/26#issuecomment-42050174</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=supercargo" class="user-hover" rel="supercargo">Adam Lewis</a> Sorry this took so long to get pulled in.  Thanks for the contribution and keep up the good work.  I pulled this into master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=supercargo">supercargo</a>:</i>
<p>No worries, I know it hit right during the apache transition. Thanks for catching up and for all the great effort growing the Storm community to be so inclusive and welcoming. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/26" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/26</a></p>
