### ISSUE TITLE
[STORM-114] Runtime ClassCastException while attempting to log problems with file deletion while cleaning inbox.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3956]
<p>I noticed this while starting nimbus with a user that didn't have privileges to cleanup the inbox (also see this <a href="https://groups.google.com/forum/#!msg/storm-user/I8gTBg8-qy8/U7Q41AiJYkUJ" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!msg/storm-user/I8gTBg8-qy8/U7Q41AiJYkUJ</a>)</p>

<p>nimbus clean-inbox calls log-error incorrectly (first argument should be a Throwable) generating a runtime exception.</p>

<p>(log-message "Cleaning inbox ... deleted: " (.getName f))<br/>
;; This should never happen<br/>
(log-error "Cleaning inbox ... error deleting: " (.getName f))<br/>
))))<br/>
I guess a "this should never happen" should be instead be replaced with a RuntimeException.</p>

<p>2013-06-26 04:45:59,999 nimbus <span class="error">&#91;Thread-1&#93;</span> <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Throwable<br/>
    at clojure.tools.logging$eval1$fn__7.invoke(NO_SOURCE_FILE:0)<br/>
    at clojure.tools.logging.impl$fn_<em>56$G</em><em>49</em>_67.invoke(impl.clj:16)<br/>
    at clojure.tools.logging$log_STAR_.invoke(logging.clj:59)<br/>
    at backtype.storm.daemon.nimbus$clean_inbox.invoke(nimbus.clj:832)<br/>
    at backtype.storm.daemon.nimbus$fn_<em>3596$exec_fn</em><em>1231</em><em>auto</em>__<em>3597$fn</em>_3607.invoke(nimbus.clj:880)<br/>
    at backtype.storm.timer$schedule_recurring$this__1779.invoke(timer.clj:77)<br/>
    at backtype.storm.timer$mk_timer$fn_<em>1762$fn</em>_1763.invoke(timer.clj:33)<br/>
    at backtype.storm.timer$mk_timer$fn__1762.invoke(timer.clj:26)<br/>
    at clojure.lang.AFn.run(AFn.java:24)<br/>
    at java.lang.Thread.run(Thread.java:662)<br/>
2013-06-26 04:46:00,022 util <span class="error">&#91;Thread-1&#93;</span> <span class="error">&#91;INFO&#93;</span> Halting process: ("Error when processing an event")</p>

<p>both #611 and #756 are trying to solve this issue</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-114" target="_blank">Runtime ClassCastException while attempting to log problems with file deletion while cleaning inbox.</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:37+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
