### ISSUE TITLE
[STORM-119] Nimbus and Supervisor process crash with error.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3961]
<p>Hi,<br/>
We are getting the below exception while running storm and zookeper on the same box.</p>

<p>2013-11-26 16:42:48 CuratorFrameworkImpl <span class="error">&#91;ERROR&#93;</span> Background operation retry gave up<br/>
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss<br/>
at org.apache.zookeeper.KeeperException.create(KeeperException.java:90)<br/>
at com.netflix.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:380)<br/>
at com.netflix.curator.framework.imps.BackgroundSyncImpl$1.processResult(BackgroundSyncImpl.java:49)<br/>
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:617)<br/>
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:506)<br/>
2013-11-26 16:42:52 nimbus <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /storms<br/>
at org.apache.zookeeper.KeeperException.create(KeeperException.java:90)<br/>
at org.apache.zookeeper.KeeperException.create(KeeperException.java:42)<br/>
at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1363)<br/>
at com.netflix.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:184)<br/>
at com.netflix.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:173)<br/>
at com.netflix.curator.RetryLoop.callWithRetry(RetryLoop.java:85)<br/>
at com.netflix.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:169)<br/>
at com.netflix.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:161)<br/>
at com.netflix.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:36)<br/>
at backtype.storm.zookeeper$get_children.invoke(zookeeper.clj:111)<br/>
at backtype.storm.cluster$mk_distributed_cluster_state$reify__1996.get_children(cluster.clj:86)<br/>
at backtype.storm.cluster$mk_storm_cluster_state$reify__2415.active_storms(cluster.clj:237)<br/>
at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)<br/>
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
at java.lang.reflect.Method.invoke(Method.java:606)<br/>
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)<br/>
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:298)<br/>
at backtype.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:634)<br/>
at clojure.lang.RestFn.invoke(RestFn.java:410)<br/>
at backtype.storm.daemon.nimbus$fn_<em>3592$exec_fn</em><em>1228</em><em>auto</em>__<em>3593$fn</em><em>3598$fn</em>_3599.invoke(nimbus.clj:872)<br/>
at backtype.storm.daemon.nimbus$fn_<em>3592$exec_fn</em><em>1228</em><em>auto</em>__<em>3593$fn</em>_3598.invoke(nimbus.clj:871)<br/>
at backtype.storm.timer$schedule_recurring$this__1776.invoke(timer.clj:69)<br/>
at backtype.storm.timer$mk_timer$fn_<em>1759$fn</em>_1760.invoke(timer.clj:33)<br/>
at backtype.storm.timer$mk_timer$fn__1759.invoke(timer.clj:26)<br/>
at clojure.lang.AFn.run(AFn.java:24)<br/>
at java.lang.Thread.run(Thread.java:724)</p>

<p>The exception is stopping nimbus and supervisor processes. We are using storm-0.8.2 and zookeeper-3.4.5.</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-119" target="_blank">Nimbus and Supervisor process crash with error.</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2015-10-09T02:39:02+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rkellogg">rkellogg</a>:</i>
<p>Please provide additional details like environment details (Zookeeper, Storm, JDK, OS), connection information, steps to duplicate, etc.  Without this no one will be able to help on this item.</p>

<p>Have you confirmed Zookeeper is functioning normally outside of Storm?  If not please close this item for insufficient details.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rkellogg">rkellogg</a>:</i>
<p>Insufficient detail to address issue.</p>
