### ISSUE TITLE
[STORM-128] Topology fails to start if a configured DRPC server is down

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3970]
<p><a href="https://github.com/nathanmarz/storm/issues/696" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/696</a></p>

<p>In our environment we have 3 DRPC servers running. This was done mainly for availability and capacity. However, we noticed that when even one of these servers is down, topologies fail to start with the following exception:</p>

<p>java.lang.RuntimeException: org.apache.thrift7.transport.TTransportException: java.net.NoRouteToHostException: No route to host<br/>
at backtype.storm.drpc.DRPCInvocationsClient.(DRPCInvocationsClient.java:23)<br/>
at backtype.storm.drpc.DRPCSpout.open(DRPCSpout.java:65)<br/>
at storm.trident.spout.RichSpoutBatchTriggerer.open(RichSpoutBatchTriggerer.java:41)<br/>
at backtype.storm.daemon.executor$fn_<em>3985$fn</em>_3997.invoke(executor.clj:460)<br/>
at backtype.storm.util$async_loop$fn__465.invoke(util.clj:375)<br/>
at clojure.lang.AFn.run(AFn.java:24)<br/>
at java.lang.Thread.run(Thread.java:722)<br/>
Caused by: org.apache.thrift7.transport.TTransportException: java.net.NoRouteToHostException: No route to host<br/>
at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)<br/>
at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)<br/>
at backtype.storm.drpc.DRPCInvocationsClient.connect(DRPCInvocationsClient.java:30)<br/>
at backtype.storm.drpc.DRPCInvocationsClient.(DRPCInvocationsClient.java:21)<br/>
... 6 more<br/>
Caused by: java.net.NoRouteToHostException: No route to host<br/>
at java.net.PlainSocketImpl.socketConnect(Native Method)<br/>
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)<br/>
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)<br/>
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)<br/>
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)<br/>
at java.net.Socket.connect(Socket.java:579)<br/>
at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)<br/>
... 9 more</p>

<p>I was wondering if it makes sense to make Storm handle this gracefully instead of failing fast. Otherwise, the DRPC servers become a SPOF.</p>

<p>If the topologies are already running the topology usually just logs an error message and continues.</p>

<p>----------<br/>
dkador: +1 on figuring out how to make the DRPC stuff not a SOP. I'd be happy to look into it myself but not sure where to start. Any guidance?</p>

<p>----------<br/>
rijuk: For reference, the stack trace I see when a DRPC server goes down while a topology is running is the following. In this case, the topology continues to function normally.</p>

<p><span class="error">&#91;backtype.storm.drpc.DRPCSpout Thread-65&#93;</span>: Failed to fetch DRPC result from DRPC server<br/>
org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused<br/>
at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)<br/>
at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)<br/>
at backtype.storm.drpc.DRPCInvocationsClient.connect(DRPCInvocationsClient.java:30)<br/>
at backtype.storm.drpc.DRPCInvocationsClient.fetchRequest(DRPCInvocationsClient.java:53)<br/>
at backtype.storm.drpc.DRPCSpout.nextTuple(DRPCSpout.java:89)<br/>
at storm.trident.spout.RichSpoutBatchTriggerer.nextTuple(RichSpoutBatchTriggerer.java:68)<br/>
at backtype.storm.daemon.executor$fn_<em>3985$fn</em><em>3997$fn</em>_4026.invoke(executor.clj:502)<br/>
at backtype.storm.util$async_loop$fn__465.invoke(util.clj:377)<br/>
at clojure.lang.AFn.run(AFn.java:24)<br/>
at java.lang.Thread.run(Thread.java:722)<br/>
Caused by: java.net.ConnectException: Connection refused<br/>
at java.net.PlainSocketImpl.socketConnect(Native Method)<br/>
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)<br/>
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)<br/>
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)<br/>
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)<br/>
at java.net.Socket.connect(Socket.java:579)<br/>
at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)<br/>
... 9 more</p>

<p>In this case I'd the host up, but the DRPC server process was down. Hence the ConnectException. But, the behavior is the same even when the host is unreachable, except for the Exception type.</p>

<p>@dkador, I'm not sure what the right solution is. One naive solution I can think of is to make DRPCInvocationsClient constructor rethrow TException instead of throwing a RuntimeException. Obviously, you'll have to make sure that all callers of this higher up in the stack handle this exception properly.</p>

<p>Actually, on second thoughts that's not a good idea. You probably still want the DRPCInvocationsClient object to be constructed. So, maybe you can log an error and just eat that exception. All other methods in that class call "connect" if necessary anyway.</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-128" target="_blank">Topology fails to start if a configured DRPC server is down</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:08+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
