### ISSUE TITLE
[STORM-131] Intermittent Zookeper errors when shutting down local Topology

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3973]
<p><a href="https://github.com/nathanmarz/storm/issues/259" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/259</a></p>

<p>We have a great deal of Storm integration tests in our project (Storm version 0.7.3) using local topology. We have only one topology operational at any moment in time. As tests run they are organized in groups. Each group works within the boundaries of a topology. When the tests finish executing they shutdown their local cluster, then the new group of tests launches its own cluster.</p>

<p>We see with some remarkable regularity failures related to, what looks like, incorrect Zookeeper shutdown, which leads to a JVM exit (which is a disaster as no test information is recorded at the end). Here is what we see in the main error log (log level: WARN and higher):</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2012-07-07 00:22:58,420 WARN [ConnectionStateManager-0|]@jenkins com.netflix.curator.framework.state.ConnectionStateManager
=> There are no ConnectionStateListeners registered.

2012-07-07 00:22:58,534 WARN [<span class="code-object">Thread</span>-23-EventThread|]@jenkins backtype.storm.cluster
=> Received event :disconnected::none: with disconnected Zookeeper.

2012-07-07 00:23:00,013 WARN [<span class="code-object">Thread</span>-23-SendThread(localhost:2000)|]@jenkins org.apache.zookeeper.ClientCnxn
=> Session 0x1385ece8f1b0017 <span class="code-keyword">for</span> server <span class="code-keyword">null</span>, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.$$YJP$$checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)
2012-07-07 00:23:01,527 WARN [<span class="code-object">Thread</span>-23-SendThread(localhost:2000)|]@jenkins org.apache.zookeeper.ClientCnxn
=> Session 0x1385ece8f1b0017 <span class="code-keyword">for</span> server <span class="code-keyword">null</span>, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.$$YJP$$checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)
2012-07-07 00:23:03,510 WARN [<span class="code-object">Thread</span>-23-SendThread(localhost:2000)|]@jenkins org.apache.zookeeper.ClientCnxn
=> Session 0x1385ece8f1b0017 <span class="code-keyword">for</span> server <span class="code-keyword">null</span>, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.$$YJP$$checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)
2012-07-07 00:23:04,687 WARN [<span class="code-object">Thread</span>-23-SendThread(localhost:2000)|]@jenkins org.apache.zookeeper.ClientCnxn
=> Session 0x1385ece8f1b0017 <span class="code-keyword">for</span> server <span class="code-keyword">null</span>, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.$$YJP$$checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)
2012-07-07 00:23:05,961 WARN [<span class="code-object">Thread</span>-23-SendThread(localhost:2000)|]@jenkins org.apache.zookeeper.ClientCnxn
=> Session 0x1385ece8f1b0017 <span class="code-keyword">for</span> server <span class="code-keyword">null</span>, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.$$YJP$$checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)
2012-07-07 00:23:07,588 WARN [<span class="code-object">Thread</span>-23-SendThread(localhost:2000)|]@jenkins org.apache.zookeeper.ClientCnxn
=> Session 0x1385ece8f1b0017 <span class="code-keyword">for</span> server <span class="code-keyword">null</span>, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.$$YJP$$checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)
2012-07-07 00:23:07,691 ERROR [<span class="code-object">Thread</span>-23-EventThread|]@jenkins com.netflix.curator.framework.imps.CuratorFrameworkImpl
=> Background operation retry gave up

org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:90)
at com.netflix.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:380)
at com.netflix.curator.framework.imps.BackgroundSyncImpl$1.processResult(BackgroundSyncImpl.java:49)
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:617)
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:506)
2012-07-07 00:23:07,697 WARN [ConnectionStateManager-0|]@jenkins com.netflix.curator.framework.state.ConnectionStateManager
=> There are no ConnectionStateListeners registered.

2012-07-07 00:23:07,699 ERROR [<span class="code-object">Thread</span>-23-EventThread|]@jenkins backtype.storm.zookeeper
=> Unrecoverable Zookeeper error Background operation retry gave up

org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:90)
at com.netflix.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:380)
at com.netflix.curator.framework.imps.BackgroundSyncImpl$1.processResult(BackgroundSyncImpl.java:49)
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:617)

at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:506)
And here is what we see in Storm dedicated log file (log level: DEBUG):

2012-07-07 00:22:58,306 INFO [main|]@jenkins backtype.storm.daemon.task
=> Shut down task TLTopology-1-1341620393:31

2012-07-07 00:22:58,306 INFO [main|]@jenkins backtype.storm.messaging.loader
=> Shutting down receiving-thread: [TLTopology-1-1341620393, 5]

2012-07-07 00:22:58,307 INFO [main|]@jenkins backtype.storm.messaging.loader
=> Waiting <span class="code-keyword">for</span> receiving-thread:[TLTopology-1-1341620393, 5] to die

2012-07-07 00:22:58,307 INFO [<span class="code-object">Thread</span>-319|]@jenkins backtype.storm.messaging.loader
=> Receiving-thread:[TLTopology-1-1341620393, 5] received shutdown notice

2012-07-07 00:22:58,307 INFO [main|]@jenkins backtype.storm.messaging.loader
=> Shutdown receiving-thread: [TLTopology-1-1341620393, 5]

2012-07-07 00:22:58,307 INFO [main|]@jenkins backtype.storm.daemon.worker
=> Terminating zmq context

2012-07-07 00:22:58,307 INFO [main|]@jenkins backtype.storm.daemon.worker
=> Waiting <span class="code-keyword">for</span> threads to die

2012-07-07 00:22:58,307 INFO [<span class="code-object">Thread</span>-318|]@jenkins backtype.storm.util
=> Async loop interrupted!

2012-07-07 00:22:58,309 INFO [main|]@jenkins backtype.storm.daemon.worker
=> Disconnecting from storm cluster state context

2012-07-07 00:22:58,311 INFO [main|]@jenkins backtype.storm.daemon.worker
=> Shut down worker TLTopology-1-1341620393 96e12303-4c22-4821-9f3b-3bce2230bf08 5

2012-07-07 00:22:58,311 DEBUG [main|]@jenkins backtype.storm.util
=> Rmr path /tmp/f308eb0e-2e72-4221-9620-43e15a9c1bdc/workers/16966f32-d0d4-4ee1-a0fe-1d85fc4a478e/heartbeats

2012-07-07 00:22:58,313 DEBUG [main|]@jenkins backtype.storm.util
=> Removing path /tmp/f308eb0e-2e72-4221-9620-43e15a9c1bdc/workers/16966f32-d0d4-4ee1-a0fe-1d85fc4a478e/pids

2012-07-07 00:22:58,313 DEBUG [main|]@jenkins backtype.storm.util
=> Removing path /tmp/f308eb0e-2e72-4221-9620-43e15a9c1bdc/workers/16966f32-d0d4-4ee1-a0fe-1d85fc4a478e

2012-07-07 00:22:58,313 INFO [main|]@jenkins backtype.storm.daemon.supervisor
=> Shut down 96e12303-4c22-4821-9f3b-3bce2230bf08:16966f32-d0d4-4ee1-a0fe-1d85fc4a478e

2012-07-07 00:22:58,314 INFO [main|]@jenkins backtype.storm.daemon.supervisor
=> Shutting down supervisor 96e12303-4c22-4821-9f3b-3bce2230bf08

2012-07-07 00:22:58,314 INFO [<span class="code-object">Thread</span>-25|]@jenkins backtype.storm.event
=> Event manager interrupted

2012-07-07 00:22:58,315 INFO [<span class="code-object">Thread</span>-26|]@jenkins backtype.storm.event
=> Event manager interrupted

2012-07-07 00:22:58,318 INFO [main|]@jenkins backtype.storm.testing
=> Shutting down in process zookeeper

2012-07-07 00:22:58,321 INFO [main|]@jenkins backtype.storm.testing
=> Done shutting down in process zookeeper

2012-07-07 00:22:58,321 INFO [main|]@jenkins backtype.storm.testing
=> Deleting temporary path /tmp/0202cf11-6ad7-4dda-94d6-622a63c9f6b6

2012-07-07 00:22:58,321 DEBUG [main|]@jenkins backtype.storm.util
=> Rmr path /tmp/0202cf11-6ad7-4dda-94d6-622a63c9f6b6

2012-07-07 00:22:58,322 INFO [main|]@jenkins backtype.storm.testing
=> Deleting temporary path /tmp/ee47e3e3-752f-40a8-b6a9-a197a9dda3de

2012-07-07 00:22:58,323 DEBUG [main|]@jenkins backtype.storm.util
=> Rmr path /tmp/ee47e3e3-752f-40a8-b6a9-a197a9dda3de

2012-07-07 00:22:58,323 INFO [main|]@jenkins backtype.storm.testing
=> Deleting temporary path /tmp/ece72b84-357e-4183-aeb5-e0d2dc5d6eca

2012-07-07 00:22:58,323 DEBUG [main|]@jenkins backtype.storm.util
=> Rmr path /tmp/ece72b84-357e-4183-aeb5-e0d2dc5d6eca

2012-07-07 00:22:58,326 INFO [main|]@jenkins backtype.storm.testing
=> Deleting temporary path /tmp/f308eb0e-2e72-4221-9620-43e15a9c1bdc

2012-07-07 00:22:58,326 DEBUG [main|]@jenkins backtype.storm.util
=> Rmr path /tmp/f308eb0e-2e72-4221-9620-43e15a9c1bdc

2012-07-07 00:22:58,534 WARN [<span class="code-object">Thread</span>-23-EventThread|]@jenkins backtype.storm.cluster
=> Received event :disconnected::none: with disconnected Zookeeper.

2012-07-07 00:23:07,699 ERROR [<span class="code-object">Thread</span>-23-EventThread|]@jenkins backtype.storm.zookeeper
=> Unrecoverable Zookeeper error Background operation retry gave up

org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:90)
at com.netflix.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:380)
at com.netflix.curator.framework.imps.BackgroundSyncImpl$1.processResult(BackgroundSyncImpl.java:49)
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:617)
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:506)
2012-07-07 00:23:07,702 INFO [<span class="code-object">Thread</span>-23-EventThread|]@jenkins backtype.storm.util

=> Halting process: (<span class="code-quote">"Unrecoverable Zookeeper error"</span>)

</pre>
</div></div>
<p>It seems like a threading issue to me personally. I wonder if there is some form of workaround. I also understand that since this is a "local" topology issue, this might not receive due attention... However, fundamentally this is what new users would start with when they begin to play with Storm, and, I think, it is important to make this experience positive.</p>

<p>Nathan, thank you very much for everything that you're doing.</p>

<p>-Kyrill</p>

<p>----------<br/>
dkincaid: Looking through the shutdown code for local clusters I noticed a comment in the code about a possible race condition. I'm wondering if we could be running into this on our Jenkins server (which we know runs pretty slowly). Is a worker getting restarted before the supervisor can be shutdown?</p>

<p>Here is the function with the comment:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">(defn kill-local-storm-cluster [cluster-map]
  (.shutdown (:nimbus cluster-map))
  (.close (:state cluster-map))
  (.disconnect (:storm-cluster-state cluster-map))
  (doseq [s @(:supervisors cluster-map)]
    (.shutdown-all-workers s)
    ;; race condition here? will it launch the workers again?
    (supervisor/kill-supervisor s))
  (psim/kill-all-processes)
  (log-message <span class="code-quote">"Shutting down in process zookeeper"</span>)
  (zk/shutdown-inprocess-zookeeper (:zookeeper cluster-map))
  (log-message <span class="code-quote">"Done shutting down in process zookeeper"</span>)
  (doseq [t @(:tmp-dirs cluster-map)]
    (log-message <span class="code-quote">"Deleting temporary path "</span> t)
    (rmr t)
    ))
</pre>
</div></div>

<p>--------<br/>
kyrill007: Fantastic catch, Dave!!! This exactly what is happening: supervisor begins launching new workers when the other ones are still being shut down. Here is the proof from the logs:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Shut down process is initiated at 04:37:05,136.

2012-07-11 04:37:05,136 INFO [main|]@jenkins backtype.storm.daemon.nimbus
  => Shutting down master

2012-07-11 04:37:05,145 INFO [main|]@jenkins backtype.storm.daemon.nimbus
  => Shut down master

2012-07-11 04:37:05,151 INFO [main|]@jenkins backtype.storm.daemon.supervisor
  => Shutting down 5c48d4fc-769f-41ef-abd6-f92df60fa543:12eba15d-fb17-4a3c-8e25-1c0266eed04d

2012-07-11 04:37:05,152 INFO [main|]@jenkins backtype.storm.process-simulator
  => Killing process ea132b37-dc6a-447c-b1de-ac6727c82cef

2012-07-11 04:37:05,152 INFO [main|]@jenkins backtype.storm.daemon.worker
  => Shutting down worker TLTopology-1-1341981237 5c48d4fc-769f-41ef-abd6-f92df60fa543 1

2012-07-11 04:37:05,152 INFO [main|]@jenkins backtype.storm.daemon.task
  => Shutting down task TLTopology-1-1341981237:64

2012-07-11 04:37:05,153 INFO [<span class="code-object">Thread</span>-129|]@jenkins backtype.storm.util
  => Async loop interrupted!

2012-07-11 04:37:05,180 INFO [main|]@jenkins backtype.storm.daemon.task
  => Shut down task TLTopology-1-1341981237:64

2012-07-11 04:37:05,180 INFO [main|]@jenkins backtype.storm.daemon.task
  => Shutting down task TLTopology-1-1341981237:34
It continues <span class="code-keyword">for</span> a <span class="code-keyword">while</span> (we have a lot of workers). Then at 04:37:05,665 we start seeing <span class="code-keyword">this</span>:

012-07-11 04:37:05,665 DEBUG [<span class="code-object">Thread</span>-19|]@jenkins backtype.storm.daemon.supervisor
  => Assigned tasks: {2 #backtype.storm.daemon.supervisor.LocalAssignment{:storm-id <span class="code-quote">"TLTopology-1-1341981237"</span>, :task-ids (96 66 36 6 102 72 42 12 108 78 48 18 114 84 54 24 120 90 60 30 126)}, 1 #backtype.storm.daemon.supervisor.LocalAssignment{:storm-id <span class="code-quote">"TLTopology-1-1341981237"</span>, :task-ids (64 34 4 100 70 40 10 106 76 46 16 112 82 52 22 118 88 58 28 124 94)}, 3 #backtype.storm.daemon.supervisor.LocalAssignment{:storm-id <span class="code-quote">"TLTopology-1-1341981237"</span>, :task-ids (32 2 98 68 38 8 104 74 44 14 110 80 50 20 116 86 56 26 122 92 62)}}

2012-07-11 04:37:05,665 DEBUG [<span class="code-object">Thread</span>-19|]@jenkins backtype.storm.daemon.supervisor
  => Allocated: {<span class="code-quote">"a724dc19-84ec-46dc-9768-afb73df94237"</span> [:valid #backtype.storm.daemon.common.WorkerHeartbeat{:time-secs 1341981425, :storm-id <span class="code-quote">"TLTopology-1-1341981237"</span>, :task-ids #{96 66 36 6 102 72 42 12 108 78 48 18 114 84 54 24 120 90 60 30 126}, :port 2}]}

2012-07-11 04:37:05,665 DEBUG [<span class="code-object">Thread</span>-19|]@jenkins backtype.storm.util
  => Making dirs at /tmp/4884ffb5-c6c7-43a9-ac72-e0a5426eea3c/workers/a7f81ea0-a5f6-47de-9a89-47998b1e1639/pids

2012-07-11 04:37:05,666 DEBUG [<span class="code-object">Thread</span>-19|]@jenkins backtype.storm.util
  => Making dirs at /tmp/4884ffb5-c6c7-43a9-ac72-e0a5426eea3c/workers/1b5c4c87-4e05-4cab-a580-ae1dabb3fd2e/pids

2012-07-11 04:37:05,666 INFO [main|]@jenkins backtype.storm.daemon.worker
  => Shut down worker TLTopology-1-1341981237 5c48d4fc-769f-41ef-abd6-f92df60fa543 2

2012-07-11 04:37:05,667 DEBUG [main|]@jenkins backtype.storm.util
  => Rmr path /tmp/4884ffb5-c6c7-43a9-ac72-e0a5426eea3c/workers/a724dc19-84ec-46dc-9768-afb73df94237/heartbeats

2012-07-11 04:37:05,669 DEBUG [main|]@jenkins backtype.storm.util
  => Removing path /tmp/4884ffb5-c6c7-43a9-ac72-e0a5426eea3c/workers/a724dc19-84ec-46dc-9768-afb73df94237/pids

2012-07-11 04:37:05,669 DEBUG [main|]@jenkins backtype.storm.util
  => Removing path /tmp/4884ffb5-c6c7-43a9-ac72-e0a5426eea3c/workers/a724dc19-84ec-46dc-9768-afb73df94237

2012-07-11 04:37:05,669 INFO [main|]@jenkins backtype.storm.daemon.supervisor
  => Shut down 5c48d4fc-769f-41ef-abd6-f92df60fa543:a724dc19-84ec-46dc-9768-afb73df94237

2012-07-11 04:37:05,669 INFO [main|]@jenkins backtype.storm.daemon.supervisor
  => Shutting down supervisor 5c48d4fc-769f-41ef-abd6-f92df60fa543

2012-07-11 04:37:05,670 INFO [<span class="code-object">Thread</span>-18|]@jenkins backtype.storm.event
  => Event manager interrupted

2012-07-11 04:37:05,670 INFO [<span class="code-object">Thread</span>-19|]@jenkins backtype.storm.daemon.supervisor
  => Launching worker with assignment #backtype.storm.daemon.supervisor.LocalAssignment{:storm-id <span class="code-quote">"TLTopology-1-1341981237"</span>, :task-ids (64 34 4 100 70 40 10 106 76 46 16 112 82 52 22 118 88 58 28 124 94)} <span class="code-keyword">for</span> <span class="code-keyword">this</span> supervisor 5c48d4fc-769f-41ef-abd6-f92df60fa543 on port 1 with id a7f81ea0-a5f6-47de-9a89-47998b1e1639

2012-07-11 04:37:05,672 INFO [<span class="code-object">Thread</span>-19|]@jenkins backtype.storm.daemon.worker
  => Launching worker <span class="code-keyword">for</span> TLTopology-1-1341981237 on 5c48d4fc-769f-41ef-abd6-f92df60fa543:1 with id a7f81ea0-a5f6-47de-9a89-47998b1e1639 and conf {<span class="code-quote">"dev.zookeeper.path"</span> <span class="code-quote">"/tmp/dev-storm-zookeeper"</span>, <span class="code-quote">"topology.fall.back.on.java.serialization"</span> <span class="code-keyword">true</span>, <span class="code-quote">"zmq.linger.millis"</span> 0, <span class="code-quote">"topology.skip.missing.kryo.registrations"</span> <span class="code-keyword">true</span>, <span class="code-quote">"ui.childopts"</span> <span class="code-quote">"-Xmx768m"</span>, <span class="code-quote">"storm.zookeeper.session.timeout"</span> 20000, <span class="code-quote">"nimbus.reassign"</span> <span class="code-keyword">true</span>, <span class="code-quote">"nimbus.monitor.freq.secs"</span> 10, <span class="code-quote">"java.library.path"</span> <span class="code-quote">"/usr/local/lib:/opt/local/lib:/usr/lib"</span>, <span class="code-quote">"storm.local.dir"</span> <span class="code-quote">"/tmp/4884ffb5-c6c7-43a9-ac72-e0a5426eea3c"</span>, <span class="code-quote">"supervisor.worker.start.timeout.secs"</span> 120, <span class="code-quote">"nimbus.cleanup.inbox.freq.secs"</span> 600, <span class="code-quote">"nimbus.inbox.jar.expiration.secs"</span> 3600, <span class="code-quote">"nimbus.host"</span> <span class="code-quote">"localhost"</span>, <span class="code-quote">"storm.zookeeper.port"</span> 2000, <span class="code-quote">"transactional.zookeeper.port"</span> nil, <span class="code-quote">"transactional.zookeeper.servers"</span> nil, <span class="code-quote">"storm.zookeeper.root"</span> <span class="code-quote">"/storm"</span>, <span class="code-quote">"supervisor.enable"</span> <span class="code-keyword">true</span>, <span class="code-quote">"storm.zookeeper.servers"</span> [<span class="code-quote">"localhost"</span>], <span class="code-quote">"transactional.zookeeper.root"</span> <span class="code-quote">"/transactional"</span>, <span class="code-quote">"topology.worker.childopts"</span> nil, <span class="code-quote">"worker.childopts"</span> <span class="code-quote">"-Xmx768m"</span>, <span class="code-quote">"supervisor.heartbeat.frequency.secs"</span> 5, <span class="code-quote">"drpc.port"</span> 3772, <span class="code-quote">"supervisor.monitor.frequency.secs"</span> 3, <span class="code-quote">"task.heartbeat.frequency.secs"</span> 3, <span class="code-quote">"topology.max.spout.pending"</span> nil, <span class="code-quote">"storm.zookeeper.retry.interval"</span> 1000, <span class="code-quote">"supervisor.slots.ports"</span> (1 2 3), <span class="code-quote">"topology.debug"</span> <span class="code-keyword">false</span>, <span class="code-quote">"nimbus.task.launch.secs"</span> 120, <span class="code-quote">"nimbus.supervisor.timeout.secs"</span> 60, <span class="code-quote">"topology.message.timeout.secs"</span> 30, <span class="code-quote">"task.refresh.poll.secs"</span> 10, <span class="code-quote">"topology.workers"</span> 1, <span class="code-quote">"supervisor.childopts"</span> <span class="code-quote">"-Xmx1024m"</span>, <span class="code-quote">"nimbus.thrift.port"</span> 6627, <span class="code-quote">"topology.stats.sample.rate"</span> 0.05, <span class="code-quote">"worker.heartbeat.frequency.secs"</span> 1, <span class="code-quote">"nimbus.task.timeout.secs"</span> 30, <span class="code-quote">"drpc.invocations.port"</span> 3773, <span class="code-quote">"zmq.threads"</span> 1, <span class="code-quote">"storm.zookeeper.retry.times"</span> 5, <span class="code-quote">"topology.state.synchronization.timeout.secs"</span> 60, <span class="code-quote">"supervisor.worker.timeout.secs"</span> 30, <span class="code-quote">"nimbus.file.copy.expiration.secs"</span> 600, <span class="code-quote">"drpc.request.timeout.secs"</span> 600, <span class="code-quote">"storm.local.mode.zmq"</span> <span class="code-keyword">false</span>, <span class="code-quote">"ui.port"</span> 8080, <span class="code-quote">"nimbus.childopts"</span> <span class="code-quote">"-Xmx1024m"</span>, <span class="code-quote">"topology.ackers"</span> 1, <span class="code-quote">"storm.cluster.mode"</span> <span class="code-quote">"local"</span>, <span class="code-quote">"topology.optimize"</span> <span class="code-keyword">true</span>, <span class="code-quote">"topology.max.task.parallelism"</span> nil}

2012-07-11 04:37:05,675 INFO [<span class="code-object">Thread</span>-19|]@jenkins backtype.storm.event
  => Event manager interrupted

2012-07-11 04:37:05,677 INFO [<span class="code-object">Thread</span>-19-EventThread|]@jenkins backtype.storm.zookeeper
  => Zookeeper state update: :connected:none
which at the end result in <span class="code-keyword">this</span>:

2012-07-11 04:37:06,175 INFO [<span class="code-object">Thread</span>-19-EventThread|]@jenkins backtype.storm.zookeeper
  => Zookeeper state update: :disconnected:none

2012-07-11 04:37:06,175 WARN [<span class="code-object">Thread</span>-22-EventThread|]@jenkins backtype.storm.cluster
  => Received event :disconnected::none: with disconnected Zookeeper.

2012-07-11 04:37:15,923 ERROR [<span class="code-object">Thread</span>-22-EventThread|]@jenkins backtype.storm.zookeeper
  => Unrecoverable Zookeeper error Background operation retry gave up

org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:90)
    at com.netflix.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:380)
    at com.netflix.curator.framework.imps.BackgroundSyncImpl$1.processResult(BackgroundSyncImpl.java:49)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:613)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:502)
2012-07-11 04:37:15,926 INFO [<span class="code-object">Thread</span>-22-EventThread|]@jenkins backtype.storm.util
  => Halting process: (<span class="code-quote">"Unrecoverable Zookeeper error"</span>)
</pre>
</div></div>

<p>Dear Nathan,</p>

<p>If this race condition could somehow be fixed (presumably it is not that hard since we know what the problem is), it would so much appreciated!!!</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-131" target="_blank">Intermittent Zookeper errors when shutting down local Topology</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:55:01+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
