### ISSUE TITLE
[STORM-134] FileNotFoundException during supervisor cleanup due to non-existant file

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3976]
<p><a href="https://github.com/nathanmarz/storm/issues/356" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/356</a></p>

<p>During development runs with local clusters I've sometimes managed to encounter FileNotFoundException thrown from FileUtils.forceDelete during cleanup.</p>

<p>Without knowing the internals of Storm it feels a bit strange that clean up...<br/>
a) ...fails when trying to delete a non existing file/folder<br/>
b) ...tries to delete a non-existant file</p>

<p>Would suppressing FileNotFoundException from FileUtils.forceDelete or switching to FileUtils.deleteQuietly be reasonable?</p>

<p>Sample stack trace:</p>

<p>ERROR <span class="error">&#91;2012-10-09 22:08:51,255&#93;</span> org.apache.zookeeper.server.NIOServerCnxn: Thread Thread<span class="error">&#91;main,5,main&#93;</span> died<br/>
! java.io.FileNotFoundException: File does not exist: /var/folders/30/4f0z00f56sqfh512yr1l61ym0000gn/T/5844d75c-3801-4757-b7ea-f20ca76e4e52/workers/08a06e4f-4cbc-4e10-b013-ff4fcb4cbf51/heartbeats/1349813330619.version<br/>
! at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1386)<br/>
! at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1044)<br/>
! at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:977)<br/>
! at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1381)<br/>
! at backtype.storm.util$rmr.invoke(util.clj:413)<br/>
! at backtype.storm.daemon.supervisor$try_cleanup_worker.invoke(supervisor.clj:146)<br/>
! at backtype.storm.daemon.supervisor$shutdown_worker.invoke(supervisor.clj:165)</p>

<p>----------<br/>
MichaelBlume: Getting the same error while trying to test with complete-topology</p>

<p>Note: I'm using storm 0.8.1. Have reproduced on my mac and my ubuntu netbook. Can try with development version if desired.</p>

<p>Reproduced with development version. It's a really weird bug, because the code is actually checking for the existence of the path before attempting to delete it.</p>

<p>OK, I think I partially understand. I put some logging into rmr to log out a listing of the tree it's attempting to remove. I get this:</p>

<p><span class="error">&#91;clojure-test&#93;</span> 3501 <span class="error">&#91;Thread-10&#93;</span> INFO backtype.storm.util - <span class="error">&#91;"/private/var/folders/qz/qs47vb4938bbk3djt74vrxwr0000gn/T/dadf34c4-ad02-4728-9d91-8b3300bcc926/workers/94008c8d-593e-463d-8665-d58fbb682f0e/heartbeats" "/private/var/folders/qz/qs47vb4938bbk3djt74vrxwr0000gn/T/dadf34c4-ad02-4728-9d91-8b3300bcc926/workers/94008c8d-593e-463d-8665-d58fbb682f0e/heartbeats/1349990601844" "/private/var/folders/qz/qs47vb4938bbk3djt74vrxwr0000gn/T/dadf34c4-ad02-4728-9d91-8b3300bcc926/workers/94008c8d-593e-463d-8665-d58fbb682f0e/heartbeats/1349990601844.version" "/private/var/folders/qz/qs47vb4938bbk3djt74vrxwr0000gn/T/dadf34c4-ad02-4728-9d91-8b3300bcc926/workers/94008c8d-593e-463d-8665-d58fbb682f0e/heartbeats/1349990602801" "/private/var/folders/qz/qs47vb4938bbk3djt74vrxwr0000gn/T/dadf34c4-ad02-4728-9d91-8b3300bcc926/workers/94008c8d-593e-463d-8665-d58fbb682f0e/heartbeats/1349990602801.version"&#93;</span><br/>
<span class="error">&#91;clojure-test&#93;</span> 3518 <span class="error">&#91;main&#93;</span> INFO backtype.storm.util - <span class="error">&#91;"/private/var/folders/qz/qs47vb4938bbk3djt74vrxwr0000gn/T/dadf34c4-ad02-4728-9d91-8b3300bcc926/workers/94008c8d-593e-463d-8665-d58fbb682f0e/heartbeats"&#93;</span></p>

<p>Looks like backtype.storm.util.rmr's being called on the same dir from two threads. The second call happens when the directory's just about empty, but not quite gone, but by the time rmr calls forceDelete, the directory's gone entirely and an exception gets raised. I've thrown a band-aid on this on my fork, but the proper solution would be to figure out why two threads are deleting the same directory.</p>

<p>----------<br/>
nathanmarz: Please attach a reproducible test case that I can run so I can look into what's going on. I run local cluster's all the time (Storm's unit tests bring clusters up and down dozens of times) and have never seen this.</p>

<p>----------<br/>
chids: I've not been able to create a reliable test case but the condition does occur "regularly". Right now I'm running the testBasicTopology code and got bitten by this a couple of times in a row. Then it stops happening.</p>

<p>@MichaelBlume's have you tried to identify what Thread-10 is?</p>

<p>----------<br/>
travis: yea, I'm seeing this regularly as well, not quite sure what the pattern is yet</p>

<p>I got stack traces of the two threads trying to rmr:</p>

<p>11073 <span class="error">&#91;main&#93;</span> ERROR backtype.storm.util  - Rmr path /var/folders/ll/0csh8smd025d9mgh2nf842400000gn/T//88915881-f92a-44be-93c1-434d9be6ac28/workers/bf2411b5-830a-4549-85e8-76637dcf352b/heartbeats<br/>
java.lang.Exception<br/>
    at backtype.storm.util$rmr$fn__4117.invoke(util.clj:411)<br/>
    at backtype.storm.util$rmr.invoke(util.clj:411)<br/>
    at backtype.storm.daemon.supervisor$try_cleanup_worker.invoke(supervisor.clj:146)<br/>
    at backtype.storm.daemon.supervisor$shutdown_worker.invoke(supervisor.clj:165)<br/>
    at backtype.storm.daemon.supervisor$fn_<em>4733$exec_fn</em><em>1207</em><em>auto</em><em>$reify</em>_4742.shutdown_all_workers(supervisor.clj:368)<br/>
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br/>
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br/>
    at java.lang.reflect.Method.invoke(Method.java:597)<br/>
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)<br/>
    at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:298)<br/>
    at backtype.storm.testing$kill_local_storm_cluster.invoke(testing.clj:154)<br/>
... (application specific stacktrack - let me know if it would be useful)<br/>
11073 <span class="error">&#91;Thread-19&#93;</span> ERROR backtype.storm.util  - Rmr path /var/folders/ll/0csh8smd025d9mgh2nf842400000gn/T//88915881-f92a-44be-93c1-434d9be6ac28/workers/bf2411b5-830a-4549-85e8-76637dcf352b/heartbeats<br/>
java.lang.Exception<br/>
    at backtype.storm.util$rmr$fn__4117.invoke(util.clj:411)<br/>
    at backtype.storm.util$rmr.invoke(util.clj:411)<br/>
    at backtype.storm.daemon.supervisor$try_cleanup_worker.invoke(supervisor.clj:146)<br/>
    at backtype.storm.daemon.supervisor$shutdown_worker.invoke(supervisor.clj:165)<br/>
    at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:223)<br/>
    at clojure.lang.AFn.applyToHelper(AFn.java:161)<br/>
    at clojure.lang.AFn.applyTo(AFn.java:151)<br/>
    at clojure.core$apply.invoke(core.clj:603)<br/>
    at clojure.core$partial$fn__4070.doInvoke(core.clj:2343)<br/>
    at clojure.lang.RestFn.invoke(RestFn.java:397)<br/>
    at backtype.storm.event$event_manager$fn__2484.invoke(event.clj:24)<br/>
    at clojure.lang.AFn.run(AFn.java:24)<br/>
at java.lang.Thread.run(Thread.java:680)<br/>
Still not quite sure what this all means, but getting closer. This happens pretty much every time I run tests on my mac and on our CI box.</p>

<p>Still no test case, but I did find a workaround. I was running the topology like:</p>

<p>(with-local-cluster <span class="error">&#91;cluster&#93;</span><br/>
    (complete-topology cluster<br/>
       (my-topology drpc)<br/>
       :mock-sources </p>
{"actions" (map vector actions)
      "drpc-requests" requests}
<p>))<br/>
Sleeping for 5 seconds before shutting down the cluster seems to fix it (shorter periods just made the error sporadic rather than constant:</p>

<p>(with-local-cluster <span class="error">&#91;cluster&#93;</span><br/>
  (let [results<br/>
(complete-topology cluster<br/>
   (my-topology drpc)<br/>
   :mock-sources </p>
{"actions" (map vector actions)
  "drpc-requests" requests}
<p>)]<br/>
    (Thread/sleep 5000)<br/>
    results))</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-134" target="_blank">FileNotFoundException during supervisor cleanup due to non-existant file</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-10-09T02:21:22+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-133">STORM-133</a>]</i>
