### ISSUE TITLE
[STORM-136] [Trident] Bug when working with two spouts with stateful operator

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3978]
<p><a href="https://github.com/nathanmarz/storm/issues/711" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/711</a></p>

<p>Hi,</p>

<p>I'm working with Trident and basically what i am trying to do is a windowed join across batches using partitionPersist and stateQuery on two different stream that come from TWO DIFFERENT SPOUTS.</p>

<p>Both the spouts implement the IBatchSpout interface.</p>

<p>The error i get is a NPE on StateQueryProcessor or on PartitionPersistProcessor depending on which one of the two spouts starts early.</p>

<p>I try to debug this and what i have understand is that Trident use the same BatchID(txid) for the two different spouts and this take to a wrong initialization of state in the core processing nodes.</p>

<p>If i use the same throughput for the two spout and i make one spout starts with a delay the problem doesn't occur (we don't have an overlap between the BachID(txid) of the different spouts).</p>

<p>----------<br/>
liesrock: Sorry for the delay.<br/>
I send to you the source code.</p>

<p><a href="https://dl.dropboxusercontent.com/u/49470846/TridentBug.tar.gz" class="external-link" target="_blank" rel="nofollow noopener">https://dl.dropboxusercontent.com/u/49470846/TridentBug.tar.gz</a></p>

<p>In this example i am using two spout:<br/>
1) the first one starts emitting tuples at a certain rate.<br/>
2) the second one is delayed by 5 seconds and emits at an higher rate than the first one.</p>

<p>I print on the sterr some debug info, the most important is the Batch ID (txid).<br/>
I print on the stdout info about the state window.</p>

<p>You can see that this is exactly the case that i was explain in my first message.</p>

<p>Thank you for your attention, i can't figure out on this, so i left Trident and i start working with Storm(i didn't have problem in implementing this on Storm).</p>

<p>Let me know what is your opinion about it.</p>

<p>Luca Muratore</p>

<p>----------<br/>
xumingming: @liesrock try to minimize your test case so it can reproduce the issue but contains the least source files(preferably only one source file), the least lines of source code &#8212; that makes us more easier to see whether the issue is in your app code or in storm core.</p>

<p>----------<br/>
liesrock: As you requested, in the following link you can find the test case in one source file and with the minimum lines of code:</p>

<p><a href="https://dl.dropboxusercontent.com/u/49470846/SimpleTridentBug.zip" class="external-link" target="_blank" rel="nofollow noopener">https://dl.dropboxusercontent.com/u/49470846/SimpleTridentBug.zip</a></p>

<p>Thanks for your patience.</p>

<p>----------<br/>
xumingming: paste the case source code here to make it easier for others to follow:</p>

<p>package storm.starter.trident;</p>

<p>import java.io.IOException;<br/>
import java.util.ArrayList;<br/>
import java.util.List;<br/>
import java.util.Map;</p>

<p>import storm.trident.Stream;<br/>
import storm.trident.TridentState;<br/>
import storm.trident.TridentTopology;<br/>
import storm.trident.operation.TridentCollector;<br/>
import storm.trident.spout.IBatchSpout;<br/>
import storm.trident.state.BaseQueryFunction;<br/>
import storm.trident.state.BaseStateUpdater;<br/>
import storm.trident.state.State;<br/>
import storm.trident.state.StateFactory;<br/>
import storm.trident.tuple.TridentTuple;<br/>
import backtype.storm.Config;<br/>
import backtype.storm.LocalCluster;<br/>
import backtype.storm.task.IMetricsContext;<br/>
import backtype.storm.task.TopologyContext;<br/>
import backtype.storm.tuple.Fields;<br/>
import backtype.storm.tuple.Values;</p>

<p>public class BugTest {</p>

<p>    //Spout that simulates an ATM<br/>
    @SuppressWarnings("serial")<br/>
    public static class ATMSpout implements IBatchSpout {   <br/>
private int batchSize;<br/>
private int initialSleepMilliTime;<br/>
private int rate;<br/>
private String name;<br/>
private List<String> currentCCIDList;<br/>
private long withdrawalID = 0;<br/>
private final static String[] LOCATIONS = </p>
{ "Madrid", "Barcelona", "Siviglia", "Granada", "Toledo", "Ibiza", "Valladolid", "Valencia" }
<p>;</p>

<p>public ATMSpout(int batchSize, int initialSleepMilliTime, int rate, String name) throws IOException </p>
{
    this.batchSize = batchSize;
    this.initialSleepMilliTime = initialSleepMilliTime;
    this.rate = rate;
    this.name = name;
}

<p>//generate a list of "size" CCID<br/>
private List<String> generateCCID(int size){<br/>
    //check the input parameter<br/>
    if(size < 0)</p>
{
System.err.println("Negative CCID list size");
return null;
    }
<p>    //initialize some variables<br/>
    List<String> aux = new ArrayList<String>();<br/>
    Integer randDigit = 0;<br/>
    String currentCCID = "";<br/>
    //create a random CCID<br/>
    for(int i = 0; i < size; i++){<br/>
for(int j = 0; j < 16; j++)</p>
{
    randDigit = (int)(Math.random() * 10);
    currentCCID +=  randDigit;
}
<p>aux.add(currentCCID);<br/>
currentCCID = "";<br/>
    }<br/>
    return aux;<br/>
}</p>

<p>@SuppressWarnings("rawtypes")<br/>
@Override<br/>
public void open(Map conf, TopologyContext context) {<br/>
    System.err.println("Open Spout instance");<br/>
    this.currentCCIDList = generateCCID(10000);<br/>
    //initial delay<br/>
    try </p>
{
Thread.sleep(initialSleepMilliTime);
    }
<p> catch (InterruptedException e) </p>
{
e.printStackTrace();
    }

<p>}</p>

<p>@Override<br/>
public void emitBatch(long batchId, TridentCollector collector) {<br/>
    System.err.println(name + " ---> Starting emitting Batch number : " + batchId);<br/>
    for(int i = 0; i < batchSize; i++) {<br/>
try </p>
{
    Thread.sleep(rate);
}
<p> catch (InterruptedException e) </p>
{
    e.printStackTrace();
}
<p>collector.emit(getNextWithdrawal());<br/>
    }<br/>
}</p>

<p>@Override<br/>
public void ack(long batchId) {<br/>
}</p>

<p>@Override<br/>
public void close() {<br/>
}</p>

<p>@SuppressWarnings("rawtypes")<br/>
@Override<br/>
public Map getComponentConfiguration() </p>
{
    return new Config();
}

<p>@Override<br/>
public Fields getOutputFields() </p>
{
    return new Fields("withdrawalID", "ccID", "location", "amount", "timestamp");
}

<p>private Values getNextWithdrawal()</p>
{
    int randIndexCCID = (int) ((Math.random()) * this.currentCCIDList.size());
    int randAmmount = (int) ((Math.random()) * 1000);
    int randIndexLocation = (int) ((Math.random()) * LOCATIONS.length);
    return new Values(++withdrawalID, 
      this.currentCCIDList.get(randIndexCCID), 
      LOCATIONS[randIndexLocation],
      randAmmount,
      System.currentTimeMillis());
}

<p>    }</p>

<p>    //state updater<br/>
    @SuppressWarnings("serial")<br/>
    private static class Updater extends BaseStateUpdater<DB>  {<br/>
private String streamName;</p>

<p>public Updater(String streamName) </p>
{
    this.streamName = streamName;
}<br/>
<br/>
@Override<br/>
public void updateState(DB state, List<TridentTuple> tuples, TridentCollector collector) {
    System.err.println(streamName + " Update State");
    }<br/>
    }<br/>
<br/>
    //query<br/>
    @SuppressWarnings("serial")<br/>
    public static class Query extends BaseQueryFunction<DB, TridentTuple> {<br/>
private String streamName;<br/>
<br/>
public Query(String streamName) {    this.streamName = streamName;}

<p>@Override<br/>
public List<TridentTuple> batchRetrieve(DB state, List<TridentTuple> inputs) {<br/>
    System.err.println(streamName + " Query");</p>

<p>    List<TridentTuple> retList = new ArrayList<TridentTuple>(); //return list<br/>
    for(int i = 0; i < 5; i++)</p>
{
retList.add(null);
    }
<p>    return retList;<br/>
}</p>

<p>@Override<br/>
public void execute(TridentTuple tuple, TridentTuple result, TridentCollector collector) {</p>

<p>}</p>

<p>    }</p>

<p>    //state<br/>
    public static class DB implements State {</p>

<p>@Override<br/>
public void beginCommit(Long txid) {</p>

<p>}</p>

<p>@Override<br/>
public void commit(Long txid) {</p>

<p>}</p>

<p>    }</p>

<p>    //factory<br/>
    @SuppressWarnings("serial")<br/>
    public static class Factory implements StateFactory {</p>

<p>@SuppressWarnings("rawtypes")<br/>
@Override<br/>
public State makeState(Map conf, IMetricsContext metrics, int partitionIndex, int numPartitions) </p>
{
    return new DB();
}
<p>       <br/>
    }</p>

<p>    public static void main(String[] args) throws Exception </p>
{
Config conf = new Config();
LocalCluster cluster = new LocalCluster();

final int BATCH_SIZE = 5;
final int DELAY_1 = 100;
final int RATE_1 = 300;
final int DELAY_2 = 5000;
final int RATE_2 = 100;

ATMSpout spout1 = new ATMSpout(BATCH_SIZE, DELAY_1, RATE_1, "SpoutLowRate");
ATMSpout spout2 = new ATMSpout(BATCH_SIZE, DELAY_2, RATE_2, "SpoutHighRate");   
TridentTopology topology = new TridentTopology();

Stream s1 = topology.newStream("stream1", spout1);
Stream s2 = topology.newStream("stream2", spout2);

TridentState leftState = s1.partitionPersist(new Factory(), 
     s1.getOutputFields(),
     new Updater("left"));
s2.stateQuery(leftState,
      s1.getOutputFields(),
      new Query("right"),
      new Fields("out"));

cluster.submitTopology("BugTest", conf, topology.build());

Thread.sleep(20000);

cluster.shutdown();
    }
<p>}</p>

<p>----------<br/>
xumingming: stacktrace:</p>

<p>5320 <span class="error">&#91;Thread-27-b-0&#93;</span> ERROR backtype.storm.util - Async loop died!<br/>
java.lang.RuntimeException: java.lang.NullPointerException<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:90) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:61) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>3496$fn</em><em>3508$fn</em>_3555.invoke(executor.clj:730) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.util$async_loop$fn__442.invoke(util.clj:403) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at java.lang.Thread.run(Thread.java:680) <span class="error">&#91;na:1.6.0_29&#93;</span><br/>
Caused by: java.lang.NullPointerException: null<br/>
    at storm.trident.planner.processor.StateQueryProcessor.execute(StateQueryProcessor.java:69) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at storm.trident.planner.SubtopologyBolt$InitialReceiver.receive(SubtopologyBolt.java:194) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at storm.trident.planner.SubtopologyBolt.execute(SubtopologyBolt.java:130) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:355) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>3496$tuple_action_fn</em>_3498.invoke(executor.clj:615) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.daemon.executor$mk_task_receiver$fn__3419.invoke(executor.clj:383) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.disruptor$clojure_handler$reify__2960.onEvent(disruptor.clj:43) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:87) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    ... 6 common frames omitted<br/>
5320 <span class="error">&#91;Thread-27-b-0&#93;</span> ERROR backtype.storm.daemon.executor -<br/>
java.lang.RuntimeException: java.lang.NullPointerException<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:90) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:61) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>3496$fn</em><em>3508$fn</em>_3555.invoke(executor.clj:730) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.util$async_loop$fn__442.invoke(util.clj:403) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at java.lang.Thread.run(Thread.java:680) <span class="error">&#91;na:1.6.0_29&#93;</span><br/>
Caused by: java.lang.NullPointerException: null<br/>
    at storm.trident.planner.processor.StateQueryProcessor.execute(StateQueryProcessor.java:69) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at storm.trident.planner.SubtopologyBolt$InitialReceiver.receive(SubtopologyBolt.java:194) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at storm.trident.planner.SubtopologyBolt.execute(SubtopologyBolt.java:130) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:355) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>3496$tuple_action_fn</em>_3498.invoke(executor.clj:615) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.daemon.executor$mk_task_receiver$fn__3419.invoke(executor.clj:383) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.disruptor$clojure_handler$reify__2960.onEvent(disruptor.clj:43) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:87) ~<span class="error">&#91;storm-core-0.9.0-rc3.jar:na&#93;</span><br/>
    ... 6 common frames omitted<br/>
5334 <span class="error">&#91;Thread-27-b-0&#93;</span> INFO  backtype.storm.util - Halting process: ("Worker died")</p>

<p>The NullPointerException is thrown because state is null:</p>

<p><a href="https://github.com/nathanmarz/storm/blob/master/storm-core/src/jvm/storm/trident/planner/processor/StateQueryProcessor.java?source=cc#L57-L61" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/blob/master/storm-core/src/jvm/storm/trident/planner/processor/StateQueryProcessor.java?source=cc#L57-L61</a></p>

<p>    @Override<br/>
    public void execute(ProcessorContext processorContext, String streamId, TridentTuple tuple) </p>
{
BatchState state = (BatchState) processorContext.state[_context.getStateIndex()];
state.tuples.add(tuple);
state.args.add(_projection.create(tuple));
    }
<p>Why state is null? state is initialized in startBatch method:<br/>
<a href="https://github.com/nathanmarz/storm/blob/master/storm-core/src/jvm/storm/trident/planner/processor/StateQueryProcessor.java?source=cc#L52-L54" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/blob/master/storm-core/src/jvm/storm/trident/planner/processor/StateQueryProcessor.java?source=cc#L52-L54</a></p>

<p>    public void startBatch(ProcessorContext processorContext) </p>
{
processorContext.state[_context.getStateIndex()] =  new BatchState();
    }
<p>In this case, startBatch is not called before execute is called.</p>

<p>Why startBatch is not called? startBatch is called by initBatchState, initBatchState should be called by TridentBoltExecutor.execute:</p>

<p>if(tracked==null) </p>
{
    tracked = new TrackedBatch(new BatchInfo(batchGroup, id, _bolt.initBatchState(batchGroup, id)), _coordConditions.get(batchGroup), id.getAttemptId());
    _batches.put(id.getId(), tracked);
}
<p>In the code above, initBatchState is called with a batchGroup arg, when there are multiple batchGroups in one batch, the TrackedBatch will only be created once, then the initBatchState will only be called for the first batchGroup, then startBatch method of processors in the rest batchGroups will not be called, then the NullPointerException, @nathanmarz, is this a bug or just not using Trident in the correct way?</p>

<p>----------<br/>
nathanmarz: Looks like a bug.</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-136" target="_blank">[Trident] Bug when working with two spouts with stateful operator</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:57+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hanjia">hanjia</a>:</i>
<p>Hi guys,</p>

<p>Is there any updates on this issue? I have a similar use case and get the same exception.</p>

<p>Thanks,<br/>
Han</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agomez">agomez</a>:</i>
<p>I have the same issue, Is there any update?</p>

<p>Thanks, <br/>
Andres</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
