### ISSUE TITLE
[STORM-156] Compiling Storm 0.9.0 results in java.lang.ClassNotFoundException: backtype.storm.LocalDRPC

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#3998]
<p><a href="https://github.com/nathanmarz/storm/issues/495" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/495</a></p>

<p>In reference to pull request #460 I was able to reproduce the error<br/>
and gather log files. I am using the bin/build_release.sh to compile<br/>
Storm. Storm compiles on Mac OS X 10.8.2 using Lein 2.0.0 and Java JDK<br/>
1.7. On Ubuntu 12.04 using Lein 2.0.0 and Java JDK 1.7 it fails with<br/>
the following error:</p>

<p>Compiling storm.trident.testing Exception in thread "main"<br/>
java.lang.ClassNotFoundException: backtype.storm.LocalDRPC,<br/>
compiling:(testing.clj:1) at<br/>
clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3387) at<br/>
clojure.lang.Compiler.compile1(Compiler.java:7035) at<br/>
clojure.lang.Compiler.compile1(Compiler.java:7025) at<br/>
clojure.lang.Compiler.compile(Compiler.java:7097) at<br/>
clojure.lang.RT.compile(RT.java:387) at<br/>
clojure.lang.RT.load(RT.java:427) at clojure.lang.RT.load(RT.java:400)<br/>
at clojure.core$load$fn__4890.invoke(core.clj:5415) at<br/>
clojure.core$load.doInvoke(core.clj:5414) at<br/>
clojure.lang.RestFn.invoke(RestFn.java:408) at<br/>
clojure.core$load_one.invoke(core.clj:5227) at<br/>
clojure.core$compile$fn__4895.invoke(core.clj:5426) at<br/>
clojure.core$compile.invoke(core.clj:5425) at<br/>
user$eval7.invoke(NO_SOURCE_FILE:1) at<br/>
clojure.lang.Compiler.eval(Compiler.java:6511) at<br/>
clojure.lang.Compiler.eval(Compiler.java:6501) at<br/>
clojure.lang.Compiler.eval(Compiler.java:6477) at<br/>
clojure.core$eval.invoke(core.clj:2797) at<br/>
clojure.main$eval_opt.invoke(main.clj:297) at<br/>
clojure.main$initialize.invoke(main.clj:316) at<br/>
clojure.main$null_opt.invoke(main.clj:349) at<br/>
clojure.main$main.doInvoke(main.clj:427) at<br/>
clojure.lang.RestFn.invoke(RestFn.java:421) at<br/>
clojure.lang.Var.invoke(Var.java:419) at<br/>
clojure.lang.AFn.applyToHelper(AFn.java:163) at<br/>
clojure.lang.Var.applyTo(Var.java:532) at<br/>
clojure.main.main(main.java:37)</p>

<p>I have contacted leiningen on IRC and they suggested that it might be<br/>
Storm. I am attaching the logs that I generated with: export<br/>
DEBUG=true lein with-profile release jar > system_jar.txt 2>&1</p>

<p>Mac OS X Log: <a href="http://pastebin.com/YvBRisSH" class="external-link" target="_blank" rel="nofollow noopener">http://pastebin.com/YvBRisSH</a> Ubuntu 12.04 Log:<br/>
<a href="http://pastebin.com/6KMKF63e" class="external-link" target="_blank" rel="nofollow noopener">http://pastebin.com/6KMKF63e</a></p>

<p>---------- d2r: I had to add :require LocalDRPC before the :import.</p>

<p>The cause might have to do with build order...</p>

<p>--------- alexcpsec: I had the same issue and fixed it the same<br/>
way. Is there a pull request for this yet</p>

<p>---------- alchemist0: I am running into this error too. I am not very<br/>
strong with the clojure syntax. Could someone either give me the code<br/>
which needs to be inserted verbatim, or share their working<br/>
testing4j.clj file with me?</p>

<p>---------- d2r: I have the following:</p>

<p>  1 (ns backtype.storm.testing4j <br/>
  2 (:import <span class="error">&#91;java.util Map List Collection ArrayList&#93;</span>) <br/>
  3 (:require <span class="error">&#91;backtype.storm LocalCluster&#93;</span>) <br/>
  4 (:import <span class="error">&#91;backtype.storm Config ILocalCluster LocalCluster&#93;</span>)</p>

<p>---------- ypf412: In my environment, I have the following: 1 (ns<br/>
backtype.storm.testing4j 2 (:import [java.util Map List Collection<br/>
ArrayList]) 3 (:require [backtype.storm.LocalCluster :as<br/>
LocalCluster]) and 1 (ns storm.trident.testing 2 (:require<br/>
<span class="error">&#91;backtype.storm.LocalDRPC :as LocalDRPC&#93;</span>)</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-156" target="_blank">Compiling Storm 0.9.0 results in java.lang.ClassNotFoundException: backtype.storm.LocalDRPC</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-10-09T02:20:34+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>This issue is highly environment-specific. I have two systems: A (which does not have the issue) and B (which does).</p>

<p><b>----<del>A</del>----</b></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">$ cat /proc/version
Linux version 2.6.32-358.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) ) #1 SMP Fri Feb 22 00:31:26 UTC 2013

$ java -version
java version <span class="code-quote">"1.6.0_31"</span>
Java(TM) SE <span class="code-object">Runtime</span> Environment (build 1.6.0_31-b04)
Java HotSpot(TM) 64-Bit Server VM (build 20.6-b01, mixed mode)

$ lein -version
Leiningen 2.3.4 on Java 1.6.0_31 Java HotSpot(TM) 64-Bit Server VM
</pre>
</div></div>


<p><b>----<del>B</del>----</b></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">$ cat /proc/version
Linux version 2.6.32-358.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) ) #1 SMP Fri Feb 22 00:31:26 UTC 2013

$ java -version
java version <span class="code-quote">"1.6.0_31"</span>
Java(TM) SE <span class="code-object">Runtime</span> Environment (build 1.6.0_31-b04)
Java HotSpot(TM) 64-Bit Server VM (build 20.6-b01, mixed mode)

$ lein -version
Leiningen 2.3.4 on Java 1.6.0_31 Java HotSpot(TM) 64-Bit Server VM
</pre>
</div></div>

<p>For all intents and purposes (at least from an OS/Java/Leiningen perspective), the systems should behave the same way, but when compiling storm's clojure code they don't:</p>

<p><b>----<del>A</del>----</b><br/>
<tt>$lein sub install</tt><br/>
<em>snip</em></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked <span class="code-keyword">for</span> details.
Compiling backtype.storm.bootstrap
Compiling backtype.storm.timer
Compiling backtype.storm.thrift
Compiling backtype.storm.disruptor
Compiling backtype.storm.stats
Compiling backtype.storm.event
Compiling backtype.storm.scheduler.IsolationScheduler
Compiling backtype.storm.scheduler.EvenScheduler
Compiling backtype.storm.scheduler.DefaultScheduler
Compiling backtype.storm.command.deactivate
Compiling backtype.storm.command.shell-submission
Compiling backtype.storm.command.rebalance
Compiling backtype.storm.command.list
Compiling backtype.storm.command.activate
Compiling backtype.storm.command.dev-zookeeper
Compiling backtype.storm.command.config-value
Compiling backtype.storm.command.kill-topology
Compiling backtype.storm.process-simulator
Compiling backtype.storm.LocalCluster
Compiling backtype.storm.config
Compiling backtype.storm.messaging.local
Compiling backtype.storm.messaging.loader
Compiling backtype.storm.zookeeper
Compiling backtype.storm.testing
Compiling backtype.storm.clojure
Compiling backtype.storm.metric.testing
Compiling backtype.storm.log
Compiling backtype.storm.testing4j
Compiling backtype.storm.LocalDRPC
Compiling backtype.storm.util
Compiling backtype.storm.ui.helpers
Compiling backtype.storm.ui.core
Compiling backtype.storm.tuple
Compiling backtype.storm.daemon.common
Compiling backtype.storm.daemon.nimbus
Compiling backtype.storm.daemon.drpc
Compiling backtype.storm.daemon.supervisor
Compiling backtype.storm.daemon.logviewer
Compiling backtype.storm.daemon.acker
Compiling backtype.storm.daemon.task
Compiling backtype.storm.daemon.builtin-metrics
Compiling backtype.storm.daemon.executor
Compiling backtype.storm.daemon.worker
Compiling backtype.storm.cluster
Compiling storm.trident.testing
</pre>
</div></div>
<p><em>successfull compilation</em></p>

<p><b>----<del>B</del>----</b><br/>
<tt>$lien sub install</tt><br/>
<em>snip</em></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked <span class="code-keyword">for</span> details.
Compiling storm.trident.testing
Exception in thread <span class="code-quote">"main"</span> java.lang.ClassNotFoundException: backtype.storm.LocalDRPC, compiling:(testing.clj:16)
	at clojure.lang.<span class="code-object">Compiler</span>$InvokeExpr.eval(<span class="code-object">Compiler</span>.java:3387)
	at clojure.lang.<span class="code-object">Compiler</span>.compile1(<span class="code-object">Compiler</span>.java:7035)
	at clojure.lang.<span class="code-object">Compiler</span>.compile1(<span class="code-object">Compiler</span>.java:7025)
	at clojure.lang.<span class="code-object">Compiler</span>.compile(<span class="code-object">Compiler</span>.java:7097)
	at clojure.lang.RT.compile(RT.java:387)
	at clojure.lang.RT.load(RT.java:427)
	at clojure.lang.RT.load(RT.java:400)
	at clojure.core$load$fn__4890.invoke(core.clj:5415)
	at clojure.core$load.doInvoke(core.clj:5414)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5227)
	at clojure.core$compile$fn__4895.invoke(core.clj:5426)
	at clojure.core$compile.invoke(core.clj:5425)
	at user$eval9.invoke(form-init4988551896295848674.clj:1)
	at clojure.lang.<span class="code-object">Compiler</span>.eval(<span class="code-object">Compiler</span>.java:6511)
	at clojure.lang.<span class="code-object">Compiler</span>.eval(<span class="code-object">Compiler</span>.java:6501)
	at clojure.lang.<span class="code-object">Compiler</span>.load(<span class="code-object">Compiler</span>.java:6952)
	at clojure.lang.<span class="code-object">Compiler</span>.loadFile(<span class="code-object">Compiler</span>.java:6912)
	at clojure.main$load_script.invoke(main.clj:283)
	at clojure.main$init_opt.invoke(main.clj:288)
	at clojure.main$initialize.invoke(main.clj:316)
	at clojure.main$null_opt.invoke(main.clj:349)
	at clojure.main$main.doInvoke(main.clj:427)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: backtype.storm.LocalDRPC
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:306)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:247)
	at java.lang.<span class="code-object">Class</span>.forName0(Native Method)
	at java.lang.<span class="code-object">Class</span>.forName(<span class="code-object">Class</span>.java:169)
	at storm.trident.testing$loading__4784__auto__.invoke(testing.clj:16)
	at clojure.lang.AFn.applyToHelper(AFn.java:159)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.lang.<span class="code-object">Compiler</span>$InvokeExpr.eval(<span class="code-object">Compiler</span>.java:3382)
	... 27 more
Compilation failed: Subprocess failed
</pre>
</div></div>

<p>The difference is that <b>A</b> attempts to compile the clojure packages in a different order than <b>B</b>. <b>A</b> starts with <tt>backtype.storm.bootstrap</tt>, while <b>B</b> starts with <tt>storm.trident.testing</tt>.</p>

<p>The solution is to add an explicit <tt>require</tt>  (see patch).</p>

<p>Since the patch does not affect any functionality, I think it is safe to apply to avoid the issue on systems that behave like <b>B</b>.</p>
