### ISSUE TITLE
[STORM-173] use "-c " command to define Number config value will generate ClassCastException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4015]
<p>storm -c topology.workers=3 -c storm.zookeeper.root=/storm/cluster001 jar ./storm-starter-0.0.1-SNAPSHOT.jar storm.starter.WordCountTopology2 WordCountTopology2</p>

<p>Will generate SerConf like this :<br/>
Submitting topology WordCountTopology2 in distributed mode with conf </p>
{"storm.zookeeper.root":"\/storm\/cluster001","topology.workers":"3","topology.debug":true}

<p>but "topology.workers":"3" is wrong and should be "topology.workers":3</p>

<p>And can find errors in $STOMR_HOME/logs/nimbus.log as following:<br/>
2013-12-10 11:18:44 o.a.t.s.TNonblockingServer <span class="error">&#91;ERROR&#93;</span> Unexpected exception while invoking!<br/>
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number<br/>
at backtype.storm.thrift$mk_plain_component_common.doInvoke(thrift.clj:93) ~<span class="error">&#91;storm-core-0.9.0-rc2.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:494) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at backtype.storm.thrift$mk_bolt_spec_STAR_.doInvoke(thrift.clj:158) ~<span class="error">&#91;storm-core-0.9.0-rc2.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:573) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at backtype.storm.daemon.common$add_acker_BANG_.invoke(common.clj:183) ~<span class="error">&#91;storm-core-0.9.0-rc2.jar:na&#93;</span><br/>
at backtype.storm.daemon.common$system_topology_BANG_.invoke(common.clj:280) ~<span class="error">&#91;storm-core-0.9.0-rc2.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$fn_<em>5822$exec_fn</em><em>1273</em><em>auto</em><em>$reify</em>_5835.submitTopologyWithOpts(nimbus.clj:931) ~<span class="error">&#91;storm-core-0.9.0-rc2.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$fn_<em>5822$exec_fn</em><em>1273</em><em>auto</em><em>$reify</em>_5835.submitTopology(nimbus.clj:949) ~<span class="error">&#91;storm-core-0.9.0-rc2.jar:na&#93;</span><br/>
at backtype.storm.generated.Nimbus$Processor$submitTopology.getResult(Nimbus.java:1223) ~<span class="error">&#91;storm-core-0.9.0-rc2.jar:na&#93;</span><br/>
at backtype.storm.generated.Nimbus$Processor$submitTopology.getResult(Nimbus.java:1211) ~<span class="error">&#91;storm-core-0.9.0-rc2.jar:na&#93;</span><br/>
at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:32) ~<span class="error">&#91;libthrift7-0.7.0-2.jar:0.7.0-2&#93;</span><br/>
at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:34) ~<span class="error">&#91;libthrift7-0.7.0-2.jar:0.7.0-2&#93;</span><br/>
at org.apache.thrift7.server.TNonblockingServer$FrameBuffer.invoke(TNonblockingServer.java:632) ~<span class="error">&#91;libthrift7-0.7.0-2.jar:0.7.0-2&#93;</span><br/>
at org.apache.thrift7.server.THsHaServer$Invocation.run(THsHaServer.java:201) <span class="error">&#91;libthrift7-0.7.0-2.jar:0.7.0-2&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) <span class="error">&#91;na:1.6.0_37&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) <span class="error">&#91;na:1.6.0_37&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;na:1.6.0_37&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="caofangkun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-173" target="_blank">use "-c " command to define Number config value will generate ClassCastException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Danijel Schiavuzzi" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dschiavu">dschiavu</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-04-22T17:45:06+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>:</i>
<p>Duplicated with <a href="https://issues.apache.org/jira/browse/STORM-72" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-72</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Resolved by <a href="https://issues.apache.org/jira/browse/STORM-181" title="Wrong config types submitted with topologies can bring nimbus down" class="issue-link" data-issue-key="STORM-181"><del>STORM-181</del></a> fix.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jethrobakker">jethrobakker</a>:</i>
<p>This issue is not resolved by the <a href="https://issues.apache.org/jira/browse/STORM-181" title="Wrong config types submitted with topologies can bring nimbus down" class="issue-link" data-issue-key="STORM-181"><del>STORM-181</del></a> fix, Storm will give an error but should convert the property values to the right type.</p>

<p>/opt/storm/bin/storm -c topology.workers=1 jar anotherJarFile.jar com.storm.Main</p>

<p>Info:<br/>
Submitting topology aTopology in distributed mode with conf </p>
{"topology.workers":"1","topology.name":"aTopology"}

<p>Error:<br/>
Topology submission exception: field topology.workers '1' must be a 'java.lang.Number'<br/>
InvalidTopologyException(msg:field topology.workers '1' must be a 'java.lang.Number')</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>The issue is that command line arguments are always written as strings.  Not numbers, not lists, not maps.  I remember a pull request or issue on github to try and fix this, but I cannot find it now.  Essentially in the code that parsed the command line options it looked to see if the value looked like a number, and if it did, it converted it to a number and stored it in the config.  There was also some code for lists and things too.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jethrobakker">jethrobakker</a>:</i>
<p>Robert, check the first comment of <a href="https://issues.apache.org/jira/browse/STORM-72" title="Storm Conf convert value to int fail" class="issue-link" data-issue-key="STORM-72"><del>STORM-72</del></a> it contains a simple check for numbers.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xiaokang">xiaokang</a>:</i>
<p>We encountered the same problem and added support for int and list args for "-c" command in StormSubmitter. For example:</p>
<ol>
	<li>"-c topology.workers=(int)10": set topology.workers to Integer 10</li>
	<li>"-c drpc.servers=(list)host1;host2;host3": set drpc.servers to List [host1, host2, host3]</li>
</ol>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=quies_net">quies_net</a>:</i>
<p>Thanks for the update Kang. If the user can specify a type there should be choice. Wouldn't it be better if the respective component using a setting takes responsibility for the details?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dschiavu">dschiavu</a>:</i>
<p>This is still happening on 0.9.1-incubating even though the Release notes seem to indicate it's fixed.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming" class="user-hover" rel="xumingming">James Xu</a>, <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a> or <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a>, please reopen this task if possible. Thanks!</p>

<p>Example:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>$ storm jar my-topology-jar-with-dependencies.jar org.storm.topologies.MyTopology -c topology.trident.batch.emit.interval.millis=1000

Exception in thread "main" java.lang.IllegalArgumentException: field topology.trident.batch.emit.interval.millis '1000' must be a 'java.lang.Number'
at backtype.storm.config$eval716$fn$reify__718.validateField(config.clj:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
at backtype.storm.config$validate_configs_with_schemas.invoke(config.clj:112)
at backtype.storm.config$read_storm_config.invoke(config.clj:117)
at backtype.storm.command.config_value$_main.invoke(config_value.clj:22)
at clojure.lang.AFn.applyToHelper(AFn.java:161)
at clojure.lang.AFn.applyTo(AFn.java:151)
at backtype.storm.command.config_value.main(Unknown Source)
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I think there was some confusion when this was resolved.  What was fixed was validating the config before it was passed to nimbus, but not the ability to add numbers on the command line.  All configs added to the command line are treated as strings.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dschiavu">dschiavu</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> exactly. I believe the patch in the first comment of <a href="https://issues.apache.org/jira/browse/STORM-72" title="Storm Conf convert value to int fail" class="issue-link" data-issue-key="STORM-72"><del>STORM-72</del></a> (by caofangkun) would be the way to go.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user dschiavu opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73</a></p>

<p>    Treat command line "-c" option number config values as such (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>    This fixes the `ClassCastException` when submitting numeric config values using the `storm` utility's `-c` option.<br/>
    It works by first checking if the `-c` configuration value is numeric (via Apache Commons' `NumberUtils#isNumber`) and, if positive, converting it to a numeric type. See <a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/dschiavu/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/dschiavu/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>-storm-number-config-value</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #73</p>

<hr />
<p>commit c4ff804c30b331be0af032f01d1b2819d62c7dc2<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-11T16:11:55Z</p>

<p>    Treat command line "-c" option number config values as such (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73#issuecomment-40422105" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73#issuecomment-40422105</a></p>

<p>    I would prefer it if we made the change inside Utils.readCommandLineOpts instead.  Just because it reduces the configs that could be changed to just those on the command line.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dschiavu closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user dschiavu reopened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73</a></p>

<p>    Treat command line "-c" option number config values as such (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>    This fixes the `ClassCastException` when submitting numeric config values using the `storm` utility's `-c` option.<br/>
    It works by first checking if the `-c` configuration value is numeric (via Apache Commons' `NumberUtils#isNumber`) and, if positive, converting it to a numeric type. See <a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/dschiavu/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/dschiavu/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>-storm-number-config-value</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #73</p>

<hr />
<p>commit c4ff804c30b331be0af032f01d1b2819d62c7dc2<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-11T16:11:55Z</p>

<p>    Treat command line "-c" option number config values as such (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>commit 442d8e75103f425d211a022184621072326925f0<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-16T16:01:34Z</p>

<p>    Move command line options values introspection logic to<br/>
    Utils#readCommandLineOpts (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dschiavu commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73#issuecomment-40619267" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73#issuecomment-40619267</a></p>

<p>    @revans2 Moved the change to Utils#readCommandLineOpts as requested.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dschiavu commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73#issuecomment-40627080" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73#issuecomment-40627080</a></p>

<p>    Any suggestions on how to parse lists, booleans etc on the command line? Should we recognize the config value type simply by parsing a prefix such as `(list)` or `(boolean)`, or do some guessing on the type?</p>

<p>    Also, what about `backtype.storm.Config`-included properties? Should we introspect (via reflection) the corresponding property value type in `backtype.storm.Config` and then convert it to that type? See Pascal's comment and code <span class="error">&#91;here&#93;</span>(<a href="https://issues.apache.org/jira/browse/STORM-173?focusedCommentId=13900881&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13900881" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-173?focusedCommentId=13900881&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13900881</a>). I do like his approach and have already modified and included his code into Storm's `Utils.java`.</p>

<p>    Let me know if I can include these changes in this pull request.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73#issuecomment-40658465" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73#issuecomment-40658465</a></p>

<p>    I am fine with trying to do reflection to get the types, but that does not fit with lists and maps like you said.  Why don't we just use JSON, like we do on other parts of the config?  It is not strictly backwards compatible, but it allows for fairly arbitrary complexity, and the null check allows for things that JSON cannot parse to still be treated as a string.</p>

<p>    ```<br/>
    diff --git a/storm-core/src/jvm/backtype/storm/utils/Utils.java b/storm-core/src/jvm/backtype/storm/utils/Utils.java<br/>
    index 7979e4b..6c8d2cf 100644<br/>
    &#8212; a/storm-core/src/jvm/backtype/storm/utils/Utils.java<br/>
    +++ b/storm-core/src/jvm/backtype/storm/utils/Utils.java<br/>
    @@ -168,9 +168,13 @@ public class Utils {<br/>
 commandOptions = commandOptions.replaceAll("%%%%", " ");<br/>
 String[] configs = commandOptions.split(",");<br/>
 for (String config : configs) {</p>
<ul class="alternate" type="square">
	<li>String[] options = config.split("=");<br/>
    +String[] options = config.split("=", 2);<br/>
     if (options.length == 2) {</li>
	<li>ret.put(options<span class="error">&#91;0&#93;</span>, options<span class="error">&#91;1&#93;</span>);<br/>
    +    Object val = JSONValue.parse(options<span class="error">&#91;1&#93;</span>);<br/>
    +    if (val == null) 
{
    +      val = options[1];
    +    }
<p>    +    ret.put(options<span class="error">&#91;0&#93;</span>, val);<br/>
     }<br/>
 }<br/>
     }<br/>
    ``` </p></li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dschiavu commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73#issuecomment-40692528" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73#issuecomment-40692528</a></p>

<p>    Looks great! Parsing command line options as JSON values simplifies things a lot, it is flexible enough for various Storm config types and, most importantly, we can avoid the `Config` reflection logic and ugly hacks like type prefixes ("(list)").</p>

<p>    I've merged your patch into the pull request.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dschiavu closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user dschiavu reopened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73</a></p>

<p>    Treat command line "-c" option number config values as such (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>    This fixes the `ClassCastException` when submitting numeric config values using the `storm` utility's `-c` option.<br/>
    It works by first checking if the `-c` configuration value is numeric (via Apache Commons' `NumberUtils#isNumber`) and, if positive, converting it to a numeric type. See <a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/dschiavu/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/dschiavu/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>-storm-number-config-value</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #73</p>

<hr />
<p>commit c4ff804c30b331be0af032f01d1b2819d62c7dc2<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-11T16:11:55Z</p>

<p>    Treat command line "-c" option number config values as such (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>commit 442d8e75103f425d211a022184621072326925f0<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-16T16:01:34Z</p>

<p>    Move command line options values introspection logic to<br/>
    Utils#readCommandLineOpts (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>commit a0e2aa6e37ddfd1174c3430499de2b18b34052c5<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-17T08:25:54Z</p>

<p>    Parse command line options as JSON values (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user dschiavu reopened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73</a></p>

<p>    Treat command line "-c" option number config values as such (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>    This fixes the `ClassCastException` when submitting numeric config values using the `storm` utility's `-c` option.<br/>
    It works by first checking if the `-c` configuration value is numeric (via Apache Commons' `NumberUtils#isNumber`) and, if positive, converting it to a numeric type. See <a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/dschiavu/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/dschiavu/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>-storm-number-config-value</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/73.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/73.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #73</p>

<hr />
<p>commit c4ff804c30b331be0af032f01d1b2819d62c7dc2<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-11T16:11:55Z</p>

<p>    Treat command line "-c" option number config values as such (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>commit 442d8e75103f425d211a022184621072326925f0<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-16T16:01:34Z</p>

<p>    Move command line options values introspection logic to<br/>
    Utils#readCommandLineOpts (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>commit a0e2aa6e37ddfd1174c3430499de2b18b34052c5<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-17T08:25:54Z</p>

<p>    Parse command line options as JSON values (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<p>commit b81ba5ee75627312719c713b6c3030b237b342d2<br/>
Author: Danijel Schiavuzzi <danijel.schiavuzzi@infobip.com><br/>
Date:   2014-04-17T13:42:20Z</p>

<p>    Clean up imports (<a href="https://issues.apache.org/jira/browse/STORM-173" title="use "-c " command to define Number config value will generate ClassCastException" class="issue-link" data-issue-key="STORM-173"><del>STORM-173</del></a>)</p>

<hr />
