### ISSUE TITLE
[STORM-180] Nimbus fails to start In case of non-worked zookeeper server specifed in config

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4022]
<p>For example, If I specify three servers in config for zookeeper, and any of them not working during <br/>
`storm nimbus`<br/>
then nimbus fails to start at all - </p>

<p>Can this be avoided somehow?<br/>
If one of zookeeper servers failed, then I had to reconfigure all storm instances to simply start it and connect to working zk servers.</p>

<p>Backtrace:</p>

<p>2013-12-20 14:08:08 b.s.d.nimbus <span class="error">&#91;ERROR&#93;</span> Error on initialization of server service-handler<br/>
java.lang.RuntimeException: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss<br/>
at backtype.storm.util$wrap_in_runtime.invoke(util.clj:28) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.zookeeper$exists_node_QMARK_$fn__991.invoke(zookeeper.clj:82) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.zookeeper$exists_node_QMARK_.invoke(zookeeper.clj:78) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.zookeeper$mkdirs.invoke(zookeeper.clj:92) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.cluster$mk_distributed_cluster_state.invoke(cluster.clj:26) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.cluster$mk_storm_cluster_state.invoke(cluster.clj:201) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$nimbus_data.invoke(nimbus.clj:51) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$fn_<em>5528$exec_fn</em><em>1229</em><em>auto</em>___5529.invoke(nimbus.clj:884) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:163) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:151) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:601) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$fn_<em>5528$service_handler</em>_5616.doInvoke(nimbus.clj:881) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:421) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1136) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1167) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$_main.invoke(nimbus.clj:1189) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:159) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:151) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus.main(Unknown Source) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss<br/>
at com.netflix.curator.ConnectionState.getZooKeeper(ConnectionState.java:72) ~<span class="error">&#91;curator-client-1.0.1.jar:na&#93;</span><br/>
at com.netflix.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:74) ~<span class="error">&#91;curator-client-1.0.1.jar:na&#93;</span><br/>
at com.netflix.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:353) ~<span class="error">&#91;curator-framework-1.0.1.jar:na&#93;</span><br/>
at com.netflix.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:149) ~<span class="error">&#91;curator-framework-1.0.1.jar:na&#93;</span><br/>
at com.netflix.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:138) ~<span class="error">&#91;curator-framework-1.0.1.jar:na&#93;</span><br/>
at com.netflix.curator.RetryLoop.callWithRetry(RetryLoop.java:85) ~<span class="error">&#91;curator-client-1.0.1.jar:na&#93;</span><br/>
at com.netflix.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:134) ~<span class="error">&#91;curator-framework-1.0.1.jar:na&#93;</span><br/>
at com.netflix.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:125) ~<span class="error">&#91;curator-framework-1.0.1.jar:na&#93;</span><br/>
at com.netflix.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:34) ~<span class="error">&#91;curator-framework-1.0.1.jar:na&#93;</span><br/>
at backtype.storm.zookeeper$exists_node_QMARK_$fn__991.invoke(zookeeper.clj:81) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
... 17 common frames omitted<br/>
2013-12-20 14:08:08 b.s.util <span class="error">&#91;INFO&#93;</span> Halting process: ("Error on initialization")</p>

---
<details><summary><i>Originally reported by <a title="Alexander Yerenkow" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yerenkow">yerenkow</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-180" target="_blank">Nimbus fails to start In case of non-worked zookeeper server specifed in config</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2013-12-23T15:59:55+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>How many zookeeper nodes did you have down out of how many total? Looking at the stack trace it is caused by curator saying it took too long for zookeeper to connect to the ensemble and it timed out.  In this case it is waiting for Zookeeper to call back into the watcher to say that it has syncConnected.  So this may be an issue with zookeeper, or curator has missed some other connection mode, or it could be that you actually don't have a full quorum and zk is doing the correct thing and not connecting.  Say you have 2 zk nodes and one of them is down.</p>
