### ISSUE TITLE
[STORM-187] From ZMQ to Netty "java.lang.IllegalArgumentException: timeout value is negative"

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4029]
<p>Hi,</p>

<p>I am trying to use Netty as the transport layer in storm 0.9.0.1 but I am getting the following error trace:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.IllegalArgumentException: timeout value is negative
    at java.lang.<span class="code-object">Thread</span>.sleep(Native Method)
    at backtype.storm.messaging.netty.Client.reconnect(Client.java:78)
    at backtype.storm.messaging.netty.StormClientHandler.exceptionCaught(StormClientHandler.java:108)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:377)
    at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:78)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:744)
</pre>
</div></div>

<p>I am using the following supervisor config:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">storm.zookeeper.servers:
    - <span class="code-quote">"son-rtl-dev-zook1"</span>
storm.zookeeper.port: 9000
storm.local.dir: <span class="code-quote">"/mnt/storm"</span>
storm.local.hostname: <span class="code-quote">"son-rtl-dev-superv1"</span>

java.library.path: <span class="code-quote">"/usr/local/lib"</span>

nimbus.host: <span class="code-quote">"son-rtl-dev-nimbus"</span>
nimbus.task.launch.secs: 240

supervisor.worker.start.timeout.secs: 240
supervisor.worker.timeout.secs: 240
supervisor.childopts: <span class="code-quote">"-Xmx512m -Djava.net.preferIPv4Stack=<span class="code-keyword">true</span>"</span>
supervisor.slots.ports:
    - 6700
    - 6701
    - 6702
    - 6703
    - 6704
    - 6705
    - 6706
    - 6707

worker.childopts: <span class="code-quote">"-Xmx512m -Djava.net.preferIPv4Stack=<span class="code-keyword">true</span>"</span>
nimbus.childopts: <span class="code-quote">"-Xmx512m -Djava.net.preferIPv4Stack=<span class="code-keyword">true</span>"</span>
topology.message.timeout.secs: 1

storm.messaging.transport: <span class="code-quote">"backtype.storm.messaging.netty.Context"</span>
storm.messaging.netty.server_worker_threads: 1
storm.messaging.netty.client_worker_threads: 1
storm.messaging.netty.buffer_size: 5242880
storm.messaging.netty.max_retries: 30
storm.messaging.netty.max_wait_ms: 1000
storm.messaging.netty.min_wait_ms: 100
</pre>
</div></div>

<p>Without these last config lines, topologies are working fine using ZMQ.</p>

<p>Any idea?</p>

<p>Thanks</p>

---
<details><summary><i>Originally reported by <a title="Jose Ignacio Honrado" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jihonrado">jihonrado</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-187" target="_blank">From ZMQ to Netty "java.lang.IllegalArgumentException: timeout value is negative"</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-03-05T19:33:26+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mauzhang">mauzhang</a>:</i>
<p>try to set "storm.messaging.netty.max_retries" to a smaller number (e.g. 10). The current setting will cause sleep_time to exceed the maximum integer and evaluate to a negative value.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jihonrado">jihonrado</a>:</i>
<p>Hi,</p>

<p>Thanks for the response. Now I am not getting the mentioned error but the topology is not working. I see to much traces like this:</p>

<p>2014-01-02 16:29:40 b.s.m.n.Client <span class="error">&#91;INFO&#93;</span> Reconnect ... <span class="error">&#91;10&#93;</span><br/>
2014-01-02 16:29:40 b.s.m.n.Client <span class="error">&#91;WARN&#93;</span> Remote address is not reachable. We will close this client.</p>

<p>Any idea?</p>

<p>Thanks</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mauzhang">mauzhang</a>:</i>
<p>Have you verified any network problems ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jihonrado">jihonrado</a>:</i>
<p>Yes, it is all fine. As I mentioned the topologies work fine with ZMQ but when I put those lines in the storm.yaml they don't work.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jihonrado">jihonrado</a>:</i>
<p>More log traces:</p>

<p>2014-01-03 12:38:08 b.s.m.n.Client <span class="error">&#91;WARN&#93;</span> Remote address is not reachable. We will close this client.<br/>
2014-01-03 12:38:09 b.s.util <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
java.lang.RuntimeException: java.lang.RuntimeException: Client is being closed, and does not take requests any more<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:90) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:61) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    at backtype.storm.disruptor$consume_loop_STAR_$fn__2975.invoke(disruptor.clj:74) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    at backtype.storm.util$async_loop$fn__444.invoke(util.clj:403) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at java.lang.Thread.run(Thread.java:744) <span class="error">&#91;na:1.7.0_45&#93;</span><br/>
Caused by: java.lang.RuntimeException: Client is being closed, and does not take requests any more<br/>
    at backtype.storm.messaging.netty.Client.send(Client.java:109) ~<span class="error">&#91;storm-netty-0.9.0.1.jar:na&#93;</span><br/>
    at backtype.storm.daemon.worker$mk_transfer_tuples_handler$fn_<em>5867$fn</em>_5868.invoke(worker.clj:304) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    at backtype.storm.daemon.worker$mk_transfer_tuples_handler$fn__5867.invoke(worker.clj:293) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    at backtype.storm.disruptor$clojure_handler$reify__2962.onEvent(disruptor.clj:43) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:87) ~<span class="error">&#91;storm-core-0.9.0.1.jar:na&#93;</span><br/>
    ... 6 common frames omitted</p>

<p>I tried to map the hostnames of the different components of the storm architecture (nimbus, zookepers and workers) to their IPs in /etc/hosts just in case, but the result is the same.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=piyushrai">piyushrai</a>:</i>
<p>I was running a storm topology and found the same issue:<br/>
WARNING: An exception was thrown by a user handler while handling an exception event (<span class="error">&#91;id: 0x655862ff&#93;</span> EXCEPTION: java.net.ConnectException: Connection refused)<br/>
java.lang.IllegalArgumentException: timeout value is negative<br/>
at java.lang.Thread.sleep(Native Method)<br/>
at backtype.storm.messaging.netty.Client.reconnect(Client.java:78)<br/>
at backtype.storm.messaging.netty.StormClientHandler.exceptionCaught(StormClientHandler.java:108)<br/>
at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:377)<br/>
at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525)<br/>
at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)<br/>
at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:78)<br/>
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)<br/>
at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
at java.lang.Thread.run(Thread.java:701)</p>

<p>Is netty production ready?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=piyushrai">piyushrai</a>:</i>
<p>Just found out that this issue happens when I directly kill supervisor and nimbus without killing the topology from the storm ui. Also when I start the topology with the same name the error persists, but if I change the topology name the topology starts to work again.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jnioche">jnioche</a>:</i>
<p>Am getting the same error Jose posted on 3/01. Here is how I configured storm :</p>

<blockquote>
<p>storm.messaging.transport: "backtype.storm.messaging.netty.Context"<br/>
storm.messaging.netty.server_worker_threads: 1<br/>
storm.messaging.netty.client_worker_threads: 1<br/>
storm.messaging.netty.buffer_size: 5242880<br/>
storm.messaging.netty.max_retries: 10<br/>
storm.messaging.netty.max_wait_ms: 1000<br/>
storm.messaging.netty.min_wait_ms: 100</p></blockquote>

<p>Any idea?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=priya ganesan">priya ganesan</a>:</i>
<p>Can anyone please guide me to run storm in remote mode? what are all the changes that I must do in yaml file to run in remote mode. should I want to add any changes in Netty folder interms of IP address. </p>

<p>Thank you,<br/>
Priya</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=piyushrai">piyushrai</a>:</i>
<p>Go through the following links and I think that should get you started<br/>
<a href="https://github.com/nathanmarz/storm/wiki/Running-topologies-on-a-production-cluster" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/wiki/Running-topologies-on-a-production-cluster</a><br/>
<a href="http://www.michael-noll.com/tutorials/running-multi-node-storm-cluster/" class="external-link" target="_blank" rel="nofollow noopener">http://www.michael-noll.com/tutorials/running-multi-node-storm-cluster/</a></p>







<p>&#8211; <br/>
Regards,<br/>
Piyush Rai</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p><a href="https://github.com/apache/incubator-storm/pull/41" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/41</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dschiavu">dschiavu</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=SoAG" class="user-hover" rel="SoAG">Roland Jungnickel</a> a temporary workaround is to merge <a href="https://github.com/apache/incubator-storm/pull/41" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/41</a> into 0.9.1-incubating and build your own Storm release. See <a href="https://github.com/apache/incubator-storm/blob/master/DEVELOPER.md" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/blob/master/DEVELOPER.md</a> for build instructions.</p>
