### ISSUE TITLE
[STORM-197] registering metrics in an IRichSpout used in Trident Topology throws an Exception

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4039]
<p>Because of how the RichSpoutBatchExecutor initializes and calls open() of the IRichSpout, any metric registrations cause an exception to be thrown.  See stacktrace below.</p>

<p>java.lang.RuntimeException: java.lang.RuntimeException: TopologyContext.registerMetric can only be called from within overridden IBolt::prepare() or ISpout::open() method.<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:90)<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:61)<br/>
    at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62)<br/>
    at backtype.storm.daemon.executor$fn_<em>3498$fn</em><em>3510$fn</em>_3557.invoke(executor.clj:730)<br/>
    at backtype.storm.util$async_loop$fn__444.invoke(util.clj:403)<br/>
    at clojure.lang.AFn.run(AFn.java:24)<br/>
    at java.lang.Thread.run(Thread.java:722)<br/>
Caused by: java.lang.RuntimeException: TopologyContext.registerMetric can only be called from within overridden IBolt::prepare() or ISpout::open() method.<br/>
    at backtype.storm.task.TopologyContext.registerMetric(TopologyContext.java:213)<br/>
    at com.XXXXXXX.spouts.amqp.AMQPSpout.open(AMQPSpout.java:232)<br/>
    at storm.trident.spout.$RichSpoutEmitter.emitBatch(RichSpoutBatchExecutor.java:88)<br/>
    at storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:65)<br/>
    at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:352)<br/>
    at backtype.storm.daemon.executor$fn_<em>3498$tuple_action_fn</em>_3500.invoke(executor.clj:615)<br/>
    at backtype.storm.daemon.executor$mk_task_receiver$fn__3421.invoke(executor.clj:383)<br/>
    at backtype.storm.disruptor$clojure_handler$reify__2962.onEvent(disruptor.clj:43)<br/>
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:87)<br/>
    ... 6 more</p>

---
<details><summary><i>Originally reported by <a title="Jason Trost" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jasontrost">jasontrost</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-197" target="_blank">registering metrics in an IRichSpout used in Trident Topology throws an Exception</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:47+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jasontrost" class="user-hover" rel="jasontrost">Jason Trost</a>,</p>

<p>Do you happen to have, or can you provide, a minimal project that can reproduce this? It would help get this resolved.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jasontrost">jasontrost</a>:</i>
<p>yes, I modified storm-starter's TridentWordCount to use the RandomSentenceSpout (with metrics collection added).</p>

<p><a href="https://github.com/jt6211/storm-starter/tree/STORM-197_demo" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jt6211/storm-starter/tree/STORM-197_demo</a></p>

<p>It should error out immediate when running with this error:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.RuntimeException: java.lang.RuntimeException: TopologyContext.registerMetric can only be called from within overridden IBolt::prepare() or ISpout::open() method.
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:90) ~[storm-core-0.9.0.1.jar:na]
	at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:61) ~[storm-core-0.9.0.1.jar:na]
	at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62) ~[storm-core-0.9.0.1.jar:na]
	at backtype.storm.daemon.executor$fn__3498$fn__3510$fn__3557.invoke(executor.clj:730) ~[storm-core-0.9.0.1.jar:na]
	at backtype.storm.util$async_loop$fn__444.invoke(util.clj:403) ~[storm-core-0.9.0.1.jar:na]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.4.0.jar:na]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_17]
Caused by: java.lang.RuntimeException: TopologyContext.registerMetric can only be called from within overridden IBolt::prepare() or ISpout::open() method.
	at backtype.storm.task.TopologyContext.registerMetric(TopologyContext.java:213) ~[storm-core-0.9.0.1.jar:na]
	at storm.starter.spout.RandomSentenceSpout.open(RandomSentenceSpout.java:26) ~[classes/:na]
	at storm.trident.spout.RichSpoutBatchExecutor$RichSpoutEmitter.emitBatch(RichSpoutBatchExecutor.java:88) ~[storm-core-0.9.0.1.jar:na]
	at storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:65) ~[storm-core-0.9.0.1.jar:na]
	at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:352) ~[storm-core-0.9.0.1.jar:na]
	at backtype.storm.daemon.executor$fn__3498$tuple_action_fn__3500.invoke(executor.clj:615) ~[storm-core-0.9.0.1.jar:na]
	at backtype.storm.daemon.executor$mk_task_receiver$fn__3421.invoke(executor.clj:383) ~[storm-core-0.9.0.1.jar:na]
	at backtype.storm.disruptor$clojure_handler$reify__2962.onEvent(disruptor.clj:43) ~[storm-core-0.9.0.1.jar:na]
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:87) ~[storm-core-0.9.0.1.jar:na]
	... 6 common frames omitted
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=andrewneilson">andrewneilson</a>:</i>
<p>This issue becomes more visible when using Trident with the 0.5.0-SNAPSHOT version of <a href="https://github.com/wurstmeister/storm-kafka-0.8-plus" class="external-link" target="_blank" rel="nofollow noopener">storm-kafka-0.8-plus</a>. It seems to work fine from the 0.3.0 release but otherwise the workaround is to build a version of storm-kafka with all calls to registerMetric commented out or removed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
