### ISSUE TITLE
[STORM-214] Windows: storm.cmd does not properly handle multiple -e arguments

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4056]
<p>As reported to user@:</p>

<p>Begin forwarded message:</p>

<p>From: Spico Florin <spicoflorin@gmail.com><br/>
Subject: Fwd: Rebalance topology throws java.lang.StringIndexOutOfBoundsException: String index out of range: -1<br/>
Date: February 5, 2014 at 4:30:43 AM EST<br/>
To: "user@storm.incubator.apache.org" <user@storm.incubator.apache.org><br/>
Reply-To: user@storm.incubator.apache.org</p>

<p>Hello!<br/>
In the mentioned version for Windows, the  rebalance command arguments should not be passed as indicated in </p>

<p><a href="https://github.com/nathanmarz/storm/wiki/Understanding-the-parallelism-of-a-Storm-topology" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/wiki/Understanding-the-parallelism-of-a-Storm-topology</a><br/>
storm rebalance mytopology -n 5 -e blue-spout=3 -e yellow-bolt=10</p>

<p>In order to get rid of the mentioned exception(java.lang.StringIndexOutOfBoundsException<img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/> you should use the command</p>

<p>storm rebalance WordCount -e "spout=3"</p>

<p>However, trying to rebalance more components (either spouts or bolts) will rebalance only the latest component mentioned in the list. So, for example for example:</p>

<p>storm rebalance WordCount -e "spout=3" -e "count=5"<br/>
 the rebalance will be applied only for the "count" component not for the "spout".</p>

<p>So, in my opinion either the documentation should be updated or the rebalance.clj should be changed in order to support rebalancing for multiple components.</p>

<p>I look forward for your opinions.<br/>
  Regards,<br/>
  Florin</p>

<p>---------- Forwarded message ----------<br/>
From: Spico Florin <spicoflorin@gmail.com><br/>
Date: Tue, Feb 4, 2014 at 11:10 AM<br/>
Subject: Rebalance topology throws java.lang.StringIndexOutOfBoundsException: String index out of range: -1<br/>
To: "user@storm.incubator.apache.org" <user@storm.incubator.apache.org></p>

<p>Hello!<br/>
I'm using the Taylor Goetz's storm version pointed out by article </p>

<p><a href="http://ptgoetz.github.io/blog/2013/12/18/running-apache-storm-on-windows/" class="external-link" target="_blank" rel="nofollow noopener">http://ptgoetz.github.io/blog/2013/12/18/running-apache-storm-on-windows/</a></p>

<p>and located at:<br/>
<a href="https://github.com/ptgoetz/incubator-storm/tree/windows-test" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/ptgoetz/incubator-storm/tree/windows-test</a></p>

<p>I have succeeded to install everything on my computer (running windows 7, 64 bit). I have also ran fine the indicated topology and my topology too. But when I'm trying to do a rebalancing of my topology by re-configuring the number of spouts or bolt with the command  <br/>
  storm rebalance WordCount -e spout=3<br/>
I'm getting the exception:<br/>
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1<br/>
at java.lang.String.substring(String.java:1911)<br/>
at backtype.storm.command.rebalance$parse_executor.invoke(rebalance.clj:24)<br/>
at clojure.tools.cli$apply_specs.invoke(cli.clj:80)<br/>
at clojure.tools.cli$cli.doInvoke(cli.clj:130)<br/>
at clojure.lang.RestFn.invoke(RestFn.java:460)<br/>
at backtype.storm.command.rebalance$_main.doInvoke(rebalance.clj:31)<br/>
at clojure.lang.RestFn.applyTo(RestFn.java:137)<br/>
at backtype.storm.command.rebalance.main(Unknown Source)</p>

<p>If I'm changing only the number of workers it works without any exceptions.</p>

<p>If someone of you have tested this version, can you please help me to get rid of it?<br/>
I'll look forward for your answers.</p>

<p>Thanks in advance.<br/>
  Regards,<br/>
  Florin </p>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-214" target="_blank">Windows: storm.cmd does not properly handle multiple -e arguments</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Harsha" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-03-22T22:13:32+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user harshach opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/77" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/77</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-214" title="Windows: storm.cmd does not properly handle multiple -e arguments" class="issue-link" data-issue-key="STORM-214"><del>STORM-214</del></a>. Windows: storm.cmd does not properly handle multiple -c arguments</p>

<p>    :combine-fn merge doesn't have any affect on multiple args. New version of cli provides a  :assoc-fn capability which can be used  to merge multiple params for same arg. <br/>
    Tested on linux and windows.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/harshach/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/harshach/incubator-storm</a> rebalance-cmd</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/77.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/77.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #77</p>

<hr />
<p>commit bd4ee0e7c606654624c698328b53633489429b37<br/>
Author: Sriharsha Chintalapani <schintalapani@hw10843.local><br/>
Date:   2014-04-16T21:11:14Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-214" title="Windows: storm.cmd does not properly handle multiple -e arguments" class="issue-link" data-issue-key="STORM-214"><del>STORM-214</del></a>. Windows: storm.cmd does not properly handle multiple -c arguments.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/77#issuecomment-41407121" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/77#issuecomment-41407121</a></p>

<p>    I got confused by my own mistake (typo in the original JIRA). The "-c" in the title should be a "-e".</p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/77#issuecomment-42324509" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/77#issuecomment-42324509</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/77" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/77</a></p>
