### ISSUE TITLE
[STORM-239] Supervisor fails in working directories whose paths have spaces in them

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4081]
<p>This is incredibly minor, but when running the unit tests from a path that has a space somewhere, you get a failure of the form:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">7378 [<span class="code-object">Thread</span>-5] INFO  backtype.storm.daemon.supervisor - Copying resources at file:/<span class="code-keyword">var</span>/lib/jenkins/jobs/Apache%20Storm/workspace/storm-core/target/test-classes/resources to /tmp/265ce1e8-8a68-475a-9d59-ccb599add284/supervisor/stormdist/test-1-0/resources
7383 [<span class="code-object">Thread</span>-5] ERROR backtype.storm.event - Error when processing event
java.io.FileNotFoundException: Source <span class="code-quote">'/<span class="code-keyword">var</span>/lib/jenkins/jobs/Apache%20Storm/workspace/storm-core/target/test-classes/resources'</span> does not exist
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:866) ~[commons-io-1.4.jar:1.4]
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:770) ~[commons-io-1.4.jar:1.4]
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:745) ~[commons-io-1.4.jar:1.4]
	at backtype.storm.daemon.supervisor$fn__4995.invoke(supervisor.clj:493) ~[classes/:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:172) ~[clojure-1.4.0.jar:na]
	at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__4902.invoke(supervisor.clj:325) ~[classes/:na]
	at backtype.storm.event$event_manager$fn__2530.invoke(event.clj:39) ~[classes/:na]
	at clojure.lang.AFn.run(AFn.java:24) ~[clojure-1.4.0.jar:na]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:724) ~[na:1.7.0_25]
7405 [<span class="code-object">Thread</span>-5] INFO  backtype.storm.util - Halting process: (<span class="code-quote">"Error when processing an event"</span>)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Storm ............................................. SUCCESS [22.941s]
[INFO] maven-shade-clojure-transformer ................... SUCCESS [23.513s]
[INFO] Storm Core ........................................ FAILURE [2:54.488s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:52.857s
[INFO] Finished at: Mon Feb 10 16:16:28 EST 2014
[INFO] Final Memory: 29M/262M
[INFO] ------------------------------------------------------------------------
</pre>
</div></div>

<p>This can be kind of annoying when (as in my example) a continuous integration system is running tests, since you often don't have full control of the path it chooses to check the source tree out at.</p>

---
<details><summary><i>Originally reported by <a title="Adrian Petrescu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetresc">apetresc</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-239" target="_blank">Supervisor fails in working directories whose paths have spaces in them</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Adrian Petrescu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetresc">apetresc</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-07-31T01:37:16+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user apetresc opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-239" title="Supervisor fails in working directories whose paths have spaces in them" class="issue-link" data-issue-key="STORM-239"><del>STORM-239</del></a> Allow supervisor to operate in paths with spaces in them</p>

<p>    Works around a bug in path-escaping for Resources, described here:<br/>
    <a href="http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485" class="external-link" target="_blank" rel="nofollow noopener">http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485</a></p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apetresc/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apetresc/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-239" title="Supervisor fails in working directories whose paths have spaces in them" class="issue-link" data-issue-key="STORM-239"><del>STORM-239</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #188</p>

<hr />
<p>commit ebfc0d3de05dbef0479c81ce4274360d1e3c483c<br/>
Author: Adrian Petrescu <apetresc@gmail.com><br/>
Date:   2014-07-11T17:18:30Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-239" title="Supervisor fails in working directories whose paths have spaces in them" class="issue-link" data-issue-key="STORM-239"><del>STORM-239</del></a> Allow supervisor to operate in paths with spaces in them</p>

<p>    Works around a bug in path-escaping for Resources, described here:<br/>
    <a href="http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485" class="external-link" target="_blank" rel="nofollow noopener">http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485</a></p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetresc">apetresc</a>:</i>
<p>Okay, I diagnosed this and it is caused by a bug in the JDK when calling `getFile()` on a Resource with spaces in the path (described here: <a href="http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485" class="external-link" target="_blank" rel="nofollow noopener">http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485</a>).</p>

<p>I applied the recommended workaround, which is to create a `java.net.URI` object for the resource instead.</p>

<p>Tested locally (in a directory with a space in the path) and all tests pass (whereas they did NOT before).</p>

<p>Pull Request is here: <a href="https://github.com/apache/incubator-storm/pull/188" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#discussion_r14839191" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#discussion_r14839191</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/daemon/supervisor.clj &#8212;<br/>
    @@ -522,6 +523,7 @@<br/>
   (FileUtils/copyDirectory (File. master-code-dir) (File. stormroot))<br/>
   (let [classloader (.getContextClassLoader (Thread/currentThread))<br/>
 resources-jar (resources-jar)<br/>
    +    uri (URI. (str (.getResource classloader RESOURCES-SUBDIR)))<br/>
    &#8212; End diff &#8211;</p>

<p>    Could do:<br/>
    ```Clojure<br/>
    ;; Work-around for JDK-4466485<br/>
    uri (if-let <span class="error">&#91;url-str (str (.getResource classloader RESOURCES-DIR))&#93;</span><br/>
  (URI. url-str))<br/>
    ```</p>

<p>    Then replace all `url` with `uri` below.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-48772740" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-48772740</a></p>

<p>    Good find.  I made one comment about how we can re-use code better, and also since it looks strange, we can put a comment in the code to the effect that this is a work-around for that JDK bug.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user apetresc commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-48779351" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-48779351</a></p>

<p>    Hey @d2r,</p>

<p>    Thanks, I've made your recommended changes (although there was no `else` clause in your `if-let`, and I'm not sure what we could possibly do to recover if `(.getResource classloader RESOURCES-SUBDIR)` was `nil` anyway, so I just kept the `let`).</p>

<p>    Commit amended!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#discussion_r14843674" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#discussion_r14843674</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/daemon/supervisor.clj &#8212;<br/>
    @@ -522,17 +523,18 @@<br/>
   (FileUtils/copyDirectory (File. master-code-dir) (File. stormroot))<br/>
   (let [classloader (.getContextClassLoader (Thread/currentThread))<br/>
 resources-jar (resources-jar)</p>
<ul class="alternate" type="square">
	<li>url (.getResource classloader RESOURCES-SUBDIR)<br/>
    +    ;; Work-around for JDK-4466485<br/>
    +    uri (URI. (str (.getResource classloader RESOURCES-SUBDIR)))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    I wanted to avoid trying to copy when no resource was found.  Now that we are making a string out of what is returned by .getResource, `uri` won't be `nil` when no resource is found—it will be a URI with an empty path.  And we do not want to try and do a dir copy from a File with an empty path, since it will likely bring down the supervisor with an exception.</p>

<p>    We really want something like:<br/>
    ```Clojure<br/>
    uri (if-let <span class="error">&#91;url (.getResource classloader RESOURCES-DIR)&#93;</span><br/>
  (URI. (str url)))<br/>
    ```</p>

<p>    This is slightly corrected from my earlier comment, and with this change:</p>

<ul>
	<li>If `.getResource` returns `nil`, then `uri` becomes `nil` (no else is needed within `if-let`), and the `cond` does not evaluate the `do` expression paired to `uri` with the `copyDirectory` below.</li>
</ul>


<ul>
	<li>If `.getResource` returns a URL, then `uri` becomes a URI of the string of `url`, and `cond` evaluates the `do` expression with the `copyDirectory`.</li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user apetresc commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-48784372" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-48784372</a></p>

<p>    @d2r, thanks for the detail, that makes a lot of sense <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/> Commit amended with all your comments.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-49932845" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-49932845</a></p>

<p>    This need an upmerge, but other than that I'm +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user apetresc commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-50076920" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-50076920</a></p>

<p>    Upmerged. There were some conflicts and I reworked it a bit to deal with the new logic, but it still works (and allows tests to run in paths with spaces in them)</p>

<p>    Let me know if you want these commits squashed before merging!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user apetresc closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user apetresc commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-50649340" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-50649340</a></p>

<p>    Anything else I need to do for this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user apetresc reopened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-239" title="Supervisor fails in working directories whose paths have spaces in them" class="issue-link" data-issue-key="STORM-239"><del>STORM-239</del></a> Allow supervisor to operate in paths with spaces in them</p>

<p>    Works around a bug in path-escaping for Resources, described here:<br/>
    <a href="http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485" class="external-link" target="_blank" rel="nofollow noopener">http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485</a></p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apetresc/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apetresc/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-239" title="Supervisor fails in working directories whose paths have spaces in them" class="issue-link" data-issue-key="STORM-239"><del>STORM-239</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #188</p>

<hr />
<p>commit dcd4bf7c33c799fca8ea67ba22f1bee7c6b40f4b<br/>
Author: Adrian Petrescu <apetresc@gmail.com><br/>
Date:   2014-07-11T17:18:30Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-239" title="Supervisor fails in working directories whose paths have spaces in them" class="issue-link" data-issue-key="STORM-239"><del>STORM-239</del></a> Allow supervisor to operate in paths with spaces in them</p>

<p>    Works around a bug in path-escaping for Resources, described here:<br/>
    <a href="http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485" class="external-link" target="_blank" rel="nofollow noopener">http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485</a></p>

<p>commit 8c89d188a910a57a4e10bc956206c0f16e5d827d<br/>
Author: Adrian Petrescu <apetresc@gmail.com><br/>
Date:   2014-07-24T20:53:59Z</p>

<p>    Upmerging with master and fixing merge conflicts</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-50649984" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-50649984</a></p>

<p>    @apetresc Nope. Just need more committer +1 in order to merge.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-50654810" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-50654810</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188#issuecomment-50699284" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188#issuecomment-50699284</a></p>

<p>    +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks Adrian,</p>

<p>I merged this into master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/188" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/188</a></p>
