### ISSUE TITLE
[STORM-270] Why ahead-of-time compiled clojure "classes" are not used in storm-core

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4112]
<p>Hi</p>

<p>I do see that storm-core.jar contains both *.clj sources and clojure compiler generated  *.class files. But in my observation in storm UI daemon, every request triggers some clj compilation on the-flight.</p>

<p>This leads to:</p>
<ul class="alternate" type="square">
	<li>high latency. (it takes about 5 seconds to fully load storm UI index page)</li>
	<li>under very modest load (10 concurrent requests) index page rendering fails with exceptions for some requests:</li>
</ul>

<p>java.lang.RuntimeException: Unable to resolve symbol: nimbus in this context, compiling:(backtype/storm/ui/core.clj:1038)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6281)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6223)<br/>
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3548)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6457)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6223)<br/>
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)<br/>
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5919)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6223)<br/>
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)<br/>
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5054)<br/>
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3674)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6453)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6223)<br/>
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3548)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6457)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6223)<br/>
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3548)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6457)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.access$100(Compiler.java:37)<br/>
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:518)<br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6262)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6223)<br/>
	at clojure.lang.Compiler.eval(Compiler.java:6515)<br/>
	at clojure.lang.Compiler.load(Compiler.java:6952)<br/>
	at clojure.lang.RT.loadResourceScript(RT.java:359)<br/>
	at clojure.lang.RT.loadResourceScript(RT.java:350)<br/>
	at clojure.lang.RT.load(RT.java:429)<br/>
	at clojure.lang.RT.load(RT.java:400)<br/>
	at clojure.core$load$fn__4890.invoke(core.clj:5415)<br/>
	at clojure.core$load.doInvoke(core.clj:5414)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:408)<br/>
	at clojure.core$load_one.invoke(core.clj:5227)<br/>
	at clojure.core$load_lib.doInvoke(core.clj:5264)<br/>
	at clojure.lang.RestFn.applyTo(RestFn.java:142)<br/>
	at clojure.core$apply.invoke(core.clj:603)<br/>
	at clojure.core$load_libs.doInvoke(core.clj:5298)<br/>
	at clojure.lang.RestFn.applyTo(RestFn.java:137)<br/>
	at clojure.core$apply.invoke(core.clj:603)<br/>
	at clojure.core$require.doInvoke(core.clj:5381)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:421)<br/>
	at ring.middleware.reload$wrap_reload$fn__7318.invoke(reload.clj:13)<br/>
	at backtype.storm.ui.core$catch_errors$fn__2082.invoke(core.clj:1075)<br/>
	at ring.middleware.keyword_params$wrap_keyword_params$fn__6327.invoke(keyword_params.clj:27)<br/>
	at ring.middleware.nested_params$wrap_nested_params$fn__6364.invoke(nested_params.clj:65)<br/>
	at ring.middleware.params$wrap_params$fn__6301.invoke(params.clj:55)<br/>
	at ring.middleware.multipart_params$wrap_multipart_params$fn__6390.invoke(multipart_params.clj:103)<br/>
	at ring.middleware.flash$wrap_flash$fn__6561.invoke(flash.clj:14)<br/>
	at ring.middleware.session$wrap_session$fn__6552.invoke(session.clj:43)<br/>
	at ring.middleware.cookies$wrap_cookies$fn__6489.invoke(cookies.clj:160)<br/>
	at ring.adapter.jetty$proxy_handler$fn__7252.invoke(jetty.clj:16)<br/>
	at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)<br/>
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)<br/>
	at org.mortbay.jetty.Server.handle(Server.java:326)<br/>
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)<br/>
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)<br/>
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)<br/>
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)<br/>
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)<br/>
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)<br/>
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)<br/>
Caused by: java.lang.RuntimeException: Unable to resolve symbol: nimbus in this context<br/>
	at clojure.lang.Util.runtimeException(Util.java:170)<br/>
	at clojure.lang.Compiler.resolveIn(Compiler.java:6766)<br/>
	at clojure.lang.Compiler.resolve(Compiler.java:6710)<br/>
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6671)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6244)<br/>
	... 74 more</p>

<p>I'm not sure whether same compilation processes happen in other storm daemons.</p>

<p>I've done experiments: after removing all clj files from the storm-core.jar, all issues described above disappeared: latency decreased to 800 ms, UI become able to handle 50 concurrent requests on the same machine.</p>

---
<details><summary><i>Originally reported by <a title="Rafael Bagmanov" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bugzmanov">bugzmanov</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-270" target="_blank">Why ahead-of-time compiled clojure "classes" are not used in storm-core</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-04-09T15:31:53+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I have seen similar issues on startup of nimbus and the workers, but I never had time to trace it down.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user revans2 opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/58" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/58</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-270" title="Why ahead-of-time compiled clojure "classes" are not used in storm-core" class="issue-link" data-issue-key="STORM-270"><del>STORM-270</del></a> don't package .clj files in release jars.</p>

<p>    This makes it so that .clj files are no longer packaged in the storm-core jar.  I left storm-starter untouched.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/revans2/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/revans2/incubator-storm</a> no-clj-in-jar</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/58.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/58.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #58</p>

<hr />
<p>commit ae71186acdeb5a7efc19393d10cdde997f587773<br/>
Author: Robert (Bobby) Evans <evans@yahoo-inc.com><br/>
Date:   2014-04-03T17:29:32Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-270" title="Why ahead-of-time compiled clojure "classes" are not used in storm-core" class="issue-link" data-issue-key="STORM-270"><del>STORM-270</del></a> don't package .clj files in release jars.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/58#issuecomment-39859841" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/58#issuecomment-39859841</a></p>

<p>    +1</p>

<p>    Tested on a multi-node cluster. UI is much snappier with this patch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/58#issuecomment-39876516" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/58#issuecomment-39876516</a></p>

<p>    +1<br/>
    Tested on a multi-node cluster.  Logviewer seems a bit faster too.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user jasonjckn commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/58#issuecomment-39919694" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/58#issuecomment-39919694</a></p>

<p>    +1<br/>
    no testing done on my end. </p>
