### ISSUE TITLE
[STORM-273] Error while running storm topologies on Windows using "storm jar"

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4115]
<p>While running some example topologies from storm-starter on Windows, I noticed the following error during file copy:</p>

<p>D:\storm\bin\storm.cmd jar D:\storm\contrib\storm-starter\storm-starter.jar storm.starter.BasicDRPCTopology</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">23402 [<span class="code-object">Thread</span>-6] INFO  backtype.storm.daemon.supervisor - Downloading code <span class="code-keyword">for</span> storm id drpc-demo-1-1396297060 from C:\Users\hadoopqa\AppData\Local\Temp\60b71f41-e4b4-4f76-843a-7cb4d1aadcb3\nimbus\stormdist\drpc-demo-1-1396297060
24485 [<span class="code-object">Thread</span>-6] INFO  backtype.storm.daemon.supervisor - Copying resources at jar:file:/D:\storm\contrib\storm-starter\storm-starter.jar!/resources to C:\Users\hadoopqa\AppData\Local\Temp\220d4bc5-7833-40f1-ad61-73ba62d6035a\supervisor\stormdist\drpc-demo-1-1396297060\resources
24488 [<span class="code-object">Thread</span>-6] ERROR backtype.storm.event - Error when processing event
java.io.FileNotFoundException: Source <span class="code-quote">'file:\D:\storm\contrib\storm-starter\storm-starter.jar!\resources'</span> does not exist
at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368) ~[commons-io-2.4.jar:2.4]
at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261) ~[commons-io-2.4.jar:2.4]
at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230) ~[commons-io-2.4.jar:2.4]
at backtype.storm.daemon.supervisor$eval6588$fn__6589.invoke(supervisor.clj:493) ~[na:na]
at clojure.lang.MultiFn.invoke(MultiFn.java:172) ~[clojure-1.4.0.jar:na]
at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__6491.invoke(supervisor.clj:325) ~[na:na]
at backtype.storm.event$event_manager$fn__2583.invoke(event.clj:39) ~[na:na]
at clojure.lang.AFn.run(AFn.java:24) [clojure-1.4.0.jar:na]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:722) [na:1.7.0_21]
24507 [<span class="code-object">Thread</span>-6] INFO  backtype.storm.util - Halting process: (<span class="code-quote">"Error when processing an event"</span>)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Ramya Sunil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rramya">rramya</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-273" target="_blank">Error while running storm topologies on Windows using "storm jar"</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Suresh Srinivas" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sureshms">sureshms</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-04-08T17:11:00+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sureshms">sureshms</a>:</i>
<p>The problem is in the following in util.clj:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">(defn zip-contains-dir? [zipfile target]
  (let [entries (->> zipfile (ZipFile.) .entries enumeration-seq (map (memfn getName)))]
    (some? #(.startsWith % (str target file-path-separator)) entries)
    ))
</pre>
</div></div>

<p>In the jar file, the file-path-separator is trying to find target + file-path-separator. In this case, file-path-separator on windows is "\" and hence it is searching for "resource\". However jar file always uses "/" as separator. Hence it cannot find "resources/" and instead it should actually be looking for "resources/"</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a>, can you please review the attached patch?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user sureshms opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/59" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/59</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-273" title="Error while running storm topologies on Windows using "storm jar"" class="issue-link" data-issue-key="STORM-273"><del>STORM-273</del></a>. Error while running storm topologies on Windows using "storm ...</p>

<p>    Patch changes the path separator to the separator used by the jar file.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/sureshms/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/sureshms/incubator-storm</a> master</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/59.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/59.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #59</p>

<hr />
<p>commit 0d3b833d86687857ec8cbfb1e01041ffc8120798<br/>
Author: Suresh Srinivas <sureshms@yahoo-inc.com><br/>
Date:   2014-04-03T21:17:14Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-273" title="Error while running storm topologies on Windows using "storm jar"" class="issue-link" data-issue-key="STORM-273"><del>STORM-273</del></a>. Error while running storm topologies on Windows using "storm jar"</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/59#issuecomment-39785988" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/59#issuecomment-39785988</a></p>

<p>    Looks fine to me +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/59#issuecomment-39855487" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/59#issuecomment-39855487</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks for the fix Suresh.  I merged this into master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/59" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/59</a></p>
