### ISSUE TITLE
[STORM-292] emit blocks the publishing bolt if disrupter queue is full   

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4134]
<p>During testing, i notice once the disruptor queue is full, it blocks (timed_wait ) the publishing bolt essentially creating slowdown live-lock. Should the outputCollector.emit be a non-blocking call?</p>

<p>Also, configs for better control on the disruptor queue/buffer size seem to not have any impact.</p>

<p>"topology.executor.receive.buffer.size"<br/>
"topology.receiver.buffer.size"<br/>
"topology.executor.send.buffer.size"<br/>
"topology.transfer.buffer.size"</p>

<p>Below is example of topology that re-creates live lock scenario	 with disruptor queue.</p>

<p><a href="https://github.com/kishorvpatil/incubator-storm/blob/dqueue-full/examples/storm-starter/src/jvm/storm/starter/SplitJoinTopology.java" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm/blob/dqueue-full/examples/storm-starter/src/jvm/storm/starter/SplitJoinTopology.java</a></p>

<p>"Thread-9-splitjoinbolt" prio=10 tid=0x00007fe518a9f000 nid=0x64b5 waiting on condition <span class="error">&#91;0x00007fe5144f2000&#93;</span><br/>
   java.lang.Thread.State: TIMED_WAITING (parking)<br/>
at sun.misc.Unsafe.park(Native Method)<br/>
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:349)<br/>
at com.lmax.disruptor.SingleThreadedClaimStrategy.waitForFreeSlotAt(SingleThreadedClaimStrategy.java:129)<br/>
at com.lmax.disruptor.SingleThreadedClaimStrategy.incrementAndGet(SingleThreadedClaimStrategy.java:81)<br/>
at com.lmax.disruptor.Sequencer.next(Sequencer.java:127)<br/>
at backtype.storm.utils.DisruptorQueue.publish(DisruptorQueue.java:113)<br/>
at backtype.storm.disruptor$publish.invoke(disruptor.clj:51)<br/>
at backtype.storm.daemon.executor$mk_executor_transfer_fn$this__4913.invoke(executor.clj:176)<br/>
at backtype.storm.daemon.executor$mk_executor_transfer_fn$this__4913.invoke(executor.clj:183)<br/>
at backtype.storm.daemon.executor$mk_executor_transfer_fn$this__4913.invoke(executor.clj:185)<br/>
at backtype.storm.daemon.executor$fn_<em>5141$fn</em><em>5155$bolt_emit</em>_5184.invoke(executor.clj:683)<br/>
at backtype.storm.daemon.executor$fn_<em>5141$fn$reify</em>_5190.emit(executor.clj:693)<br/>
at backtype.storm.task.OutputCollector.emit(OutputCollector.java:186)<br/>
at backtype.storm.task.OutputCollector.emit(OutputCollector.java:32)<br/>
at backtype.storm.topology.BasicOutputCollector.emit(BasicOutputCollector.java:19)<br/>
at storm.starter.bolt.SplitAndCountBolt.execute(SplitAndCountBolt.java:24)<br/>
at backtype.storm.topology.BasicBoltExecutor.execute(BasicBoltExecutor.java:33)<br/>
at backtype.storm.daemon.executor$fn_<em>5141$tuple_action_fn</em>_5143.invoke(executor.clj:634)</p>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-292" target="_blank">emit blocks the publishing bolt if disrupter queue is full   </a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-09-08T21:47:04+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>:</i>
<p>Since SplitAndJoinTopology is cyclic. I was looking at  Nathan's previous commits to "fix deadlock bug due to variant of dining philosophers problem" using overflow-buffer for spouts. </p>

<p><a href="https://github.com/nathanmarz/storm/commit/1a9dca46abe4c937e6b5874a9d1b178163a95af4" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/commit/1a9dca46abe4c937e6b5874a9d1b178163a95af4</a><br/>
<a href="https://groups.google.com/forum/#!msg/storm-user/c1g_s5L8yuI/JV5q94SCnWQJ" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!msg/storm-user/c1g_s5L8yuI/JV5q94SCnWQJ</a></p>

<p>I think storm should extend the use of overflow-buffer to bolts as well to avoid deadlock on bolt while publishing to queue with no free slots. Any thoughts?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>That sounds good to me.  I would rather have a topology use more memory then dead/live lock.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It is already fixed by <a href="https://issues.apache.org/jira/browse/STORM-216" title="Secure Multi-tenant Storm" class="issue-link" data-issue-key="STORM-216"><del>STORM-216</del></a>.<br/>
Please refer <a href="https://github.com/apache/storm/commit/fe5f41aa8332700d3f98422cb7d986fc47289bcd" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/commit/fe5f41aa8332700d3f98422cb7d986fc47289bcd</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ujfjhz" class="user-hover" rel="ujfjhz">Shan Hongjie</a>,</p>

<p>You are right overflow has been on for all spouts and bolts for quite a while.  Since security went in as a part of 0.10.  If you are running into it please upgrade to at least 0.10 and preferable 1.0. </p>
