### ISSUE TITLE
[STORM-299] tick tuples stop in a long running topology

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4141]
<p>We are running a topology that processes about 10K tuples a second on a single worker. There are about 80 executor threads across 3 different Bolt types, each receiving a tick tuple at a frequency of 1 second. We observe that the tick tuples stop coming in after few hours or sometime even after a day. The nimbus UI also shows that the tick tuples count has frozen whereas the same set of bolts continue to process tuples from other spouts. I have taken a stack trace and it shows following:</p>

<p>"Thread-8" daemon prio=10 tid=0x00007f1a0fed2000 nid=0x4438 runnable <span class="error">&#91;0x00007f19a5e01000&#93;</span><br/>
   java.lang.Thread.State: TIMED_WAITING (parking)<br/>
at sun.misc.Unsafe.park(Native Method)<br/>
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:349)<br/>
at com.lmax.disruptor.AbstractMultithreadedClaimStrategy.waitForFreeSlotAt(AbstractMultithreadedClaimStrategy.java:99)<br/>
at com.lmax.disruptor.AbstractMultithreadedClaimStrategy.incrementAndGet(AbstractMultithreadedClaimStrategy.java:49)<br/>
at com.lmax.disruptor.Sequencer.next(Sequencer.java:127)<br/>
at backtype.storm.utils.DisruptorQueue.publish(DisruptorQueue.java:113)<br/>
at backtype.storm.disruptor$publish.invoke(disruptor.clj:51)<br/>
at backtype.storm.disruptor$publish.invoke(disruptor.clj:53)<br/>
at backtype.storm.daemon.executor$setup_ticks_BANG_$fn__3885.invoke(executor.clj:299)<br/>
at backtype.storm.timer$schedule_recurring$this__1839.invoke(timer.clj:79)<br/>
at backtype.storm.timer$mk_timer$thread_fn_<em>1822$fn</em>_1823.invoke(timer.clj:32)<br/>
at backtype.storm.timer$mk_timer$thread_fn__1822.invoke(timer.clj:25)<br/>
at clojure.lang.AFn.run(AFn.java:24)<br/>
at java.lang.Thread.run(Thread.java:744)</p>

<p>   Locked ownable synchronizers:</p>
<ul class="alternate" type="square">
	<li>None</li>
</ul>

<p>"Thread-268-__system" prio=10 tid=0x00007f1a0ef45000 nid=0x46b5 runnable <span class="error">&#91;0x00007f17ef574000&#93;</span><br/>
   java.lang.Thread.State: TIMED_WAITING (parking)<br/>
at sun.misc.Unsafe.park(Native Method)</p>
<ul class="alternate" type="square">
	<li>parking to wait for  <0x000000073d9a2060> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)<br/>
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)<br/>
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2176)<br/>
at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:87)<br/>
at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:54)<br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:56)<br/>
at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62)<br/>
at backtype.storm.daemon.executor$eval4023$fn_<em>4024$fn</em><em>4038$fn</em>_4089.invoke(executor.clj:749)<br/>
at backtype.storm.util$async_loop$fn__364.invoke(util.clj:400)<br/>
at clojure.lang.AFn.run(AFn.java:24)<br/>
at java.lang.Thread.run(Thread.java:744)</li>
</ul>

<p>   Locked ownable synchronizers:</p>
<ul class="alternate" type="square">
	<li>None</li>
</ul>

<p>We are running storm-0.9.0_wip21 and I would be glad to provide any other information.</p>

<p>Also see <a href="https://issues.apache.org/jira/browse/STORM-106" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-106</a>.</p>

<p>Thanks,<br/>
Sushant</p>

---
<details><summary><i>Originally reported by <a title="Sushant Kumar" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sushantk">sushantk</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-299" target="_blank">tick tuples stop in a long running topology</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2014-04-29T23:24:53+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>This seems to indicate that a tick tuple was trying to publish to the receive queue of an executor, but could not because the queue was full.  While at the same time an executor, possibly a different one, was waiting for data to be available on its queue.  I'm not sure that there is any way to tie the two together, in fact if the two are for the same queue it probably means that you have found a bug in disruptor.  If this is reproducible, we should be able to get to the bottom of it, so long as you are OK with sharing stack traces, and possibly a heap dump of a worker experiencing this issue.  If this is something you are not going to be able to share it will be much more difficult to track down what is happening.</p>
