### ISSUE TITLE
[STORM-307] After host crash, supervisor is unable to restart itself

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4149]
<p>Hi,</p>

<p>I've observed <a href="#links" target="_blank" rel="noopener">multiple times</a> that supervisor state de-serialisation after host crash or reboot can fail. Supervisor is then unable to come up without manual intervention. AFAICT, it seems that serialized supervisor state if invalid and coun't be read at next start.</p>

<p>Observed error in supervisor log :</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2014-04-29 19:38:35 c.n.c.f.i.CuratorFrameworkImpl [INFO] Starting
2014-04-29 19:38:35 o.a.z.ZooKeeper [INFO] Initiating client connection, connectString=127.0.0.1:2181/storm sessionTimeout=20000 watcher=com.netflix.curator.ConnectionState@18d055e0
2014-04-29 19:38:35 o.a.z.ClientCnxn [INFO] Opening socket connection to server /127.0.0.1:2181
2014-04-29 19:38:35 o.a.z.ClientCnxn [INFO] Socket connection established to localhost/127.0.0.1:2181, initiating session
2014-04-29 19:38:35 o.a.z.ClientCnxn [INFO] Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x145a7cc1c7e48b1, negotiated timeout = 20000
2014-04-29 19:38:35 b.s.d.supervisor [INFO] Starting supervisor with id 71b01216-9d00-4fb6-8538-6673058ab5ef at host storm
2014-04-29 19:38:36 b.s.event [ERROR] Error when processing event
java.lang.RuntimeException: java.io.EOFException
at backtype.storm.utils.Utils.deserialize(Utils.java:86) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
at backtype.storm.utils.LocalState.snapshot(LocalState.java:45) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
at backtype.storm.utils.LocalState.get(LocalState.java:56) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:207) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
at clojure.lang.AFn.applyToHelper(AFn.java:161) ~[clojure-1.4.0.jar:na]
at clojure.lang.AFn.applyTo(AFn.java:151) ~[clojure-1.4.0.jar:na]
at clojure.core$apply.invoke(core.clj:603) ~[clojure-1.4.0.jar:na]
at clojure.core$partial$fn__4070.doInvoke(core.clj:2343) ~[clojure-1.4.0.jar:na]
at clojure.lang.RestFn.invoke(RestFn.java:397) ~[clojure-1.4.0.jar:na]
at backtype.storm.event$event_manager$fn__2593.invoke(event.clj:39) ~[na:na]
at clojure.lang.AFn.run(AFn.java:24) ~[clojure-1.4.0.jar:na]
at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
Caused by: java.io.EOFException: null
at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2323) ~[na:1.7.0_25]
at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2792) ~[na:1.7.0_25]
at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:799) ~[na:1.7.0_25]
at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299) ~[na:1.7.0_25]
at backtype.storm.utils.Utils.deserialize(Utils.java:81) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
... 11 common frames omitted
2014-04-29 19:38:36 b.s.util [INFO] Halting process: ("Error when processing an event")
</pre>
</div></div>

<p>Current workaround : full stop supervisor daemon and delete all Storm's data/supervisor directory helped, and after restarting Supervisor is now running smoothly. </p>

<p><a name="links"></a> Here is some references of very similar issues :</p>
<ul>
	<li><a href="http://mail-archives.apache.org/mod_mbox/storm-user/201402.mbox/%3C23100d14e7ac4cef947f7236ef8963e1@BY2PR08MB144.namprd08.prod.outlook.com%3E" class="external-link" target="_blank" rel="nofollow noopener">http://mail-archives.apache.org/mod_mbox/storm-user/201402.mbox/%3C23100d14e7ac4cef947f7236ef8963e1@BY2PR08MB144.namprd08.prod.outlook.com%3E</a></li>
	<li><a href="https://groups.google.com/forum/#!topic/storm-user/SL9FK9XeoI8" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!topic/storm-user/SL9FK9XeoI8</a></li>
	<li><a href="https://groups.google.com/forum/#!topic/storm-user/2gapTYTRrX8" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!topic/storm-user/2gapTYTRrX8</a></li>
</ul>

<p>Regards,</p>

---
<details><summary><i>Originally reported by <a title="Damien Raude-Morvan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=drazzib">drazzib</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-307" target="_blank">After host crash, supervisor is unable to restart itself</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Thomas Becker" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wurstmeister">wurstmeister</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-11-04T13:10:56+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>Deleting the supervisor and worker state directories and unzipping this tar into storm.home will reproduce this bug.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>For some strange reason all of the local state files are empty, but not the isupervisor ones.  This either means that Utils.serialize returned an empty array, or that FileUtils.writeByteArrayToFile did not fully write out what it was supposed to.  Either way this seems very odd. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>For those coming across this, a workaround is to delete the <tt>storm/supervisor</tt> and <tt>storm/workers</tt> directories before the supervisor is started in your storm supervisor init script, if you've got one. Then the state is re-created anew every time the supervisor is started, and this bug is never hit.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/282#issuecomment-60423299" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/282#issuecomment-60423299</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/282#issuecomment-60429586" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/282#issuecomment-60429586</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user clockfly commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/282#issuecomment-61636291" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/282#issuecomment-61636291</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/282" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/282</a></p>
