### ISSUE TITLE
[STORM-319] mvn build storm failed for that "../../multilang/rb/storm.rb" have syntax error.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4161]
<p>I download latest storm code from master branch,use "mvn clean install" to build.It reports that "../../multilang/rb/storm.rb" in resources/storm.rb have syntax error.I am not ruby expert.Who can help me ? thanks.</p>

<p>The error information are below:<br/>
145772 <span class="error">&#91;Thread-402&#93;</span> INFO  org.apache.curator.framework.imps.CuratorFrameworkImpl - Starting<br/>
145804 <span class="error">&#91;Thread-402-EventThread&#93;</span> INFO  org.apache.curator.framework.state.ConnectionStateManager - State change: CONNECTED<br/>
145805 <span class="error">&#91;ConnectionStateManager-0&#93;</span> WARN  org.apache.curator.framework.state.ConnectionStateManager - There are no ConnectionStateListeners registered.<br/>
145819 <span class="error">&#91;Thread-402-EventThread&#93;</span> INFO  backtype.storm.zookeeper - Zookeeper state update: :connected:none<br/>
146000 <span class="error">&#91;Thread-413-1&#93;</span> ERROR backtype.storm.util - Async loop died!<br/>
java.lang.RuntimeException: Pipe to subprocess seems to be broken! No output read.<br/>
Shell Process Exception:<br/>
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /tmp/7233be77-e821-4ad1-8421-cbbc14c43281/supervisor/stormdist/test-1-1400079903/resources/storm.rb:1: syntax error, unexpected .. (SyntaxError)<br/>
../../multilang/rb/storm.rb<br/>
  ^<br/>
/tmp/7233be77-e821-4ad1-8421-cbbc14c43281/supervisor/stormdist/test-1-1400079903/resources/storm.rb:1: unknown regexp options - ltlag<br/>
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'<br/>
from tester_spout.rb:19:in `<main>'</p>

<p>at backtype.storm.utils.ShellProcess.readString(ShellProcess.java:135) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.utils.ShellProcess.readMessage(ShellProcess.java:81) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:62) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.spout.ShellSpout.open(ShellSpout.java:53) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>3570$fn</em>_3585.invoke(executor.clj:519) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.util$async_loop$fn__442.invoke(util.clj:432) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_05&#93;</span><br/>
146002 <span class="error">&#91;Thread-413-1&#93;</span> ERROR backtype.storm.daemon.executor - <br/>
java.lang.RuntimeException: Pipe to subprocess seems to be broken! No output read.<br/>
Shell Process Exception:<br/>
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /tmp/7233be77-e821-4ad1-8421-cbbc14c43281/supervisor/stormdist/test-1-1400079903/resources/storm.rb:1: syntax error, unexpected .. (SyntaxError)<br/>
../../multilang/rb/storm.rb<br/>
  ^<br/>
/tmp/7233be77-e821-4ad1-8421-cbbc14c43281/supervisor/stormdist/test-1-1400079903/resources/storm.rb:1: unknown regexp options - ltlag<br/>
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'<br/>
from tester_spout.rb:19:in `<main>'</p>

<p>at backtype.storm.utils.ShellProcess.readString(ShellProcess.java:135) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.utils.ShellProcess.readMessage(ShellProcess.java:81) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:62) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.spout.ShellSpout.open(ShellSpout.java:53) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>3570$fn</em>_3585.invoke(executor.clj:519) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.util$async_loop$fn__442.invoke(util.clj:432) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_05&#93;</span><br/>
146052 <span class="error">&#91;Thread-413-1&#93;</span> INFO  backtype.storm.util - Halting process: ("Worker died")<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> Reactor Summary:<br/>
<span class="error">&#91;INFO&#93;</span> <br/>
<span class="error">&#91;INFO&#93;</span> Storm ............................................. SUCCESS [  9.727 s]<br/>
<span class="error">&#91;INFO&#93;</span> maven-shade-clojure-transformer ................... SUCCESS [ 11.872 s]<br/>
<span class="error">&#91;INFO&#93;</span> Storm Core ........................................ FAILURE <span class="error">&#91;04:07 min&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> storm-starter ..................................... SKIPPED<br/>
<span class="error">&#91;INFO&#93;</span> storm-kafka ....................................... SKIPPED<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> BUILD FAILURE<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> Total time: 04:32 min<br/>
<span class="error">&#91;INFO&#93;</span> Finished at: 2014-05-14T08:05:05-08:00<br/>
<span class="error">&#91;INFO&#93;</span> Final Memory: 26M/148M<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;ERROR&#93;</span> Failed to execute goal com.theoryinpractise:clojure-maven-plugin:1.3.18:test-with-junit (test-clojure) on project storm-core: Clojure failed. -> <span class="error">&#91;Help 1&#93;</span><br/>
<span class="error">&#91;ERROR&#93;</span> <br/>
<span class="error">&#91;ERROR&#93;</span> To see the full stack trace of the errors, re-run Maven with the -e switch.<br/>
<span class="error">&#91;ERROR&#93;</span> Re-run Maven using the -X switch to enable full debug logging.<br/>
<span class="error">&#91;ERROR&#93;</span> <br/>
<span class="error">&#91;ERROR&#93;</span> For more information about the errors and possible solutions, please read the following articles:<br/>
<span class="error">&#91;ERROR&#93;</span> <span class="error">&#91;Help 1&#93;</span> <a href="http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException" class="external-link" target="_blank" rel="nofollow noopener">http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException</a><br/>
<span class="error">&#91;ERROR&#93;</span> <br/>
<span class="error">&#91;ERROR&#93;</span> After correcting the problems, you can resume the build with the command<br/>
<span class="error">&#91;ERROR&#93;</span>   mvn <goals> -rf :storm-core</p>

---
<details><summary><i>Originally reported by <a title="MoonGod" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=MoonGod">MoonGod</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-319" target="_blank">mvn build storm failed for that "../../multilang/rb/storm.rb" have syntax error.</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-10-09T02:19:25+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clockfly">clockfly</a>:</i>
<p>This may happen when you are on Windows or copy source code from Windows.<br/>
To verify this, please make sure file "storm-core/src/dev/resources/storm.rb"(another file is storm.py) is a symbol link. If it is not, you need to use git to download fresh code on Linux.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=moongod">moongod</a>:</i>
<p>thanks a lot.I follow your suggestions,and use git to download code and compile,the above error has disappeared. But the below errors are born,is it normal? and what's the problem? thanks in advance.</p>

<p>869128 <span class="error">&#91;CuratorFramework-0-EventThread&#93;</span> INFO  org.apache.curator.framework.state.ConnectionStateManager - State change: SUSPENDED<br/>
869129 <span class="error">&#91;ConnectionStateManager-0&#93;</span> WARN  org.apache.curator.framework.state.ConnectionStateManager - There are no ConnectionStateListeners registered.<br/>
869129 <span class="error">&#91;CuratorFramework-0-EventThread&#93;</span> INFO  org.apache.curator.framework.state.ConnectionStateManager - State change: SUSPENDED<br/>
869129 <span class="error">&#91;ConnectionStateManager-0&#93;</span> WARN  org.apache.curator.framework.state.ConnectionStateManager - There are no ConnectionStateListeners registered.<br/>
Tests run: 156, Assertions: 101459, Failures: 3, Errors: 0<br/>
There are test failures.<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> Reactor Summary:<br/>
<span class="error">&#91;INFO&#93;</span> <br/>
<span class="error">&#91;INFO&#93;</span> Storm ............................................. SUCCESS [  4.120 s]<br/>
<span class="error">&#91;INFO&#93;</span> maven-shade-clojure-transformer ................... SUCCESS [  5.800 s]<br/>
<span class="error">&#91;INFO&#93;</span> Storm Core ........................................ FAILURE <span class="error">&#91;16:11 min&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> storm-starter ..................................... SKIPPED<br/>
<span class="error">&#91;INFO&#93;</span> storm-kafka ....................................... SKIPPED<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> BUILD FAILURE<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> Total time: 16:23 min<br/>
<span class="error">&#91;INFO&#93;</span> Finished at: 2014-05-15T08:22:16-08:00<br/>
<span class="error">&#91;INFO&#93;</span> Final Memory: 27M/147M<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;ERROR&#93;</span> Failed to execute goal com.theoryinpractise:clojure-maven-plugin:1.3.18:test-with-junit (test-clojure) on project storm-core: Clojure failed. -> <span class="error">&#91;Help 1&#93;</span><br/>
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.theoryinpractise:clojure-maven-plugin:1.3.18:test-with-junit (test-clojure) on project storm-core: Clojure failed.<br/>
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)<br/>
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)<br/>
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)<br/>
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)<br/>
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)<br/>
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)<br/>
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)<br/>
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)<br/>
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)<br/>
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)<br/>
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)<br/>
at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)<br/>
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
at java.lang.reflect.Method.invoke(Method.java:483)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)<br/>
Caused by: org.apache.maven.plugin.MojoExecutionException: Clojure failed.<br/>
at com.theoryinpractise.clojure.AbstractClojureCompilerMojo.callClojureWith(AbstractClojureCompilerMojo.java:451)<br/>
at com.theoryinpractise.clojure.AbstractClojureCompilerMojo.callClojureWith(AbstractClojureCompilerMojo.java:353)<br/>
at com.theoryinpractise.clojure.ClojureRunTestWithJUnitMojo.execute(ClojureRunTestWithJUnitMojo.java:153)<br/>
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)<br/>
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)<br/>
... 19 more<br/>
<span class="error">&#91;ERROR&#93;</span> <br/>
<span class="error">&#91;ERROR&#93;</span> <br/>
<span class="error">&#91;ERROR&#93;</span> For more information about the errors and possible solutions, please read the following articles:<br/>
<span class="error">&#91;ERROR&#93;</span> <span class="error">&#91;Help 1&#93;</span> <a href="http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException" class="external-link" target="_blank" rel="nofollow noopener">http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException</a><br/>
<span class="error">&#91;ERROR&#93;</span> <br/>
<span class="error">&#91;ERROR&#93;</span> After correcting the problems, you can resume the build with the command<br/>
<span class="error">&#91;ERROR&#93;</span>   mvn <goals> -rf :storm-core<br/>
<span class="error">&#91;root@localhost incubator-storm&#93;</span># </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clockfly">clockfly</a>:</i>
<p>You need to check test report to find out which test case failed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=moongod">moongod</a>:</i>
<p>thanks,I'll check myself!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=moongod">moongod</a>:</i>
<p>The build problem have been resolved,so close it.</p>
