### ISSUE TITLE
[STORM-334] Unable to compile storm code

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4176]
<p>I have trying to compile the storm code using mvn clean install -X but it keeps failing with the following error,</p>
<div class="code panel" style="border-style: solid;border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">[DEBUG] Command line: [java, -Dclojure.compile.path=/Users/gkhare/git/incubator-storm/storm-core/target/classes, -jar, /<span class="code-keyword">var</span>/folders/x9/gsh9kn3x5wjch7jfnwh_mf4dn5z616/T/clojuremavenplugin9203516485011075775jar, backtype.storm.command.deactivate, backtype.storm.tuple, backtype.storm.command.shell-submission, backtype.storm.bootstrap, backtype.storm.daemon.acker, backtype.storm.log, backtype.storm.ui.helpers, backtype.storm.testing4j, backtype.storm.config, backtype.storm.zookeeper, backtype.storm.daemon.nimbus, backtype.storm.daemon.builtin-metrics, backtype.storm.ui.core, backtype.storm.event, backtype.storm.command.rebalance, backtype.storm.metric.testing, backtype.storm.command.dev-zookeeper, backtype.storm.daemon.common, backtype.storm.daemon.executor, backtype.storm.daemon.worker, backtype.storm.command.config-value, backtype.storm.process-simulator, backtype.storm.testing, backtype.storm.daemon.supervisor, backtype.storm.disruptor, backtype.storm.thrift, backtype.storm.util, backtype.storm.daemon.logviewer, backtype.storm.messaging.loader, backtype.storm.scheduler.IsolationScheduler, backtype.storm.clojure, backtype.storm.stats, backtype.storm.messaging.local, backtype.storm.timer, backtype.storm.LocalDRPC, backtype.storm.scheduler.DefaultScheduler, backtype.storm.command.list, backtype.storm.cluster, backtype.storm.scheduler.EvenScheduler, backtype.storm.daemon.task, backtype.storm.daemon.drpc, storm.trident.testing, backtype.storm.command.activate, backtype.storm.command.kill-topology, backtype.storm.LocalCluster]
Compiling backtype.storm.command.deactivate to /Users/gkhare/git/incubator-storm/storm-core/target/classes
Compiling backtype.storm.tuple to /Users/gkhare/git/incubator-storm/storm-core/target/classes
Compiling backtype.storm.command.shell-submission to /Users/gkhare/git/incubator-storm/storm-core/target/classes
Compiling backtype.storm.bootstrap to /Users/gkhare/git/incubator-storm/storm-core/target/classes
Compiling backtype.storm.daemon.acker to /Users/gkhare/git/incubator-storm/storm-core/target/classes
Compiling backtype.storm.log to /Users/gkhare/git/incubator-storm/storm-core/target/classes
Compiling backtype.storm.ui.helpers to /Users/gkhare/git/incubator-storm/storm-core/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.097s
[INFO] Finished at: Thu May 29 16:00:32 IST 2014
[INFO] Final Memory: 25M/278M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.theoryinpractise:clojure-maven-plugin:1.3.20:compile (compile-clojure) on project storm-core: Clojure failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.theoryinpractise:clojure-maven-plugin:1.3.20:compile (compile-clojure) on project storm-core: Clojure failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Clojure failed.
	at com.theoryinpractise.clojure.AbstractClojureCompilerMojo.callClojureWith(AbstractClojureCompilerMojo.java:463)
	at com.theoryinpractise.clojure.AbstractClojureCompilerMojo.callClojureWith(AbstractClojureCompilerMojo.java:379)
	at com.theoryinpractise.clojure.AbstractClojureCompilerMojo.callClojureWith(AbstractClojureCompilerMojo.java:356)
	at com.theoryinpractise.clojure.ClojureCompilerMojo.execute(ClojureCompilerMojo.java:40)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
</pre>
</div></div>

<p>This is possibly failing for following namespace<br/>
<em>backtype.storm.ui.helpers</em></p>

---
<details><summary><i>Originally reported by <a title="Gaurav Khare" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gkhare">gkhare</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-334" target="_blank">Unable to compile storm code</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2015-10-09T02:32:22+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gkhare" class="user-hover" rel="gkhare">Gaurav Khare</a> Can you please update jira with java ,maven versions.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gkhare">gkhare</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a> Updated the environment info.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gkhare" class="user-hover" rel="gkhare">Gaurav Khare</a> <br/>
I tried on OS X 10.9.2 with maven-3.2.1 with java 1.7.0_55 and 1.6.0_65 <br/>
on Windows 7 with maven-3.2.1 and java 1.7.0_55 my build went through fine for the <br/>
latest from git.<br/>
I would try deleting ~/.m2 dir and run mvn clean package.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Is this still an issue?  If it is you can try compiling with clojure version 0.6.0-alpha2 it has a fix in it that allows the error to be output.  If not please close this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Closing this ticket because no response on it, in a long time.  If it is still an issue, reopen.</p>
