### ISSUE TITLE
[STORM-345] (Security) AutoTGT renewal is not working

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4187]
<p>AutoTGT will call tgt.refresh(); to try and renew a token, but ever time we try to make this work the java code blows up with some very odd errors.</p>

<p>Either we need to find some configurations and document them on how to make this work.</p>

<p>Rip out the renewal code and update the documentation to explain that the renewal is not supported.</p>

<p>Find another way to renew the TGT (Some other library)</p>

---
<details><summary><i>Originally reported by <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-345" target="_blank">(Security) AutoTGT renewal is not working</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Raghavendra Nandagopal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=speaktoraghav">speaktoraghav</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2014-07-09T17:23:18+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=speaktoraghav">speaktoraghav</a>:</i>
<p>This is Raghav.  Assign it to me, I will take look at it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=speaktoraghav">speaktoraghav</a>:</i>
<p>After going through most of the configuration parameters (JAAS) and running through AutoTGT, the client configuration requires "useTicketCache=true" to be set.  With this config parameter client has to initially call kinit and have the user obtain ticket.  Next, once AutoTGT is called then it is renewing the ticket obtained through the ticket cache.  In this situation, the tgt.refresh() method doesn't fail and correctly does the renewal.</p>

<p>Without setting the parameter useTicketCache=true it is not possible to renew the ticket because the ticket obtained directly doesn't set the renewable flag due to which tgt.refresh() method is failing.</p>

<p>For example, below is the sample configuration.<br/>
Client {<br/>
       com.sun.security.auth.module.Krb5LoginModule required<br/>
       useKeyTab=true<br/>
       keyTab="/home/user/client.keytab<br/>
       useTicketCache=true<br/>
       principal="user/domain";<br/>
};</p>

<p>Please let me know if this correct or we need to take different approach.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I am getting an error when I try to actually renew the ticket.</p>

<p>I modified AutoTGT in the following way.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">diff --git a/storm-core/src/jvm/backtype/storm/security/auth/kerberos/AutoTGT.java b/storm-core/src/jvm/backtype/storm/security/auth/kerberos/AutoTGT.java
index 52bf540..a474e5d 100644
--- a/storm-core/src/jvm/backtype/storm/security/auth/kerberos/AutoTGT.java
+++ b/storm-core/src/jvm/backtype/storm/security/auth/kerberos/AutoTGT.java
@@ -241,7 +241,7 @@ <span class="code-keyword">public</span> <span class="code-keyword">class </span>AutoTGT <span class="code-keyword">implements</span> IAutoCredentials, ICredentialsRenewer {
 <span class="code-keyword">if</span> (tgt != <span class="code-keyword">null</span>) {
     <span class="code-object">long</span> refreshTime = getRefreshTime(tgt);
     <span class="code-object">long</span> now = <span class="code-object">System</span>.currentTimeMillis();
-    <span class="code-keyword">if</span> (now >= refreshTime) {
+    <span class="code-comment">//<span class="code-keyword">if</span> (now >= refreshTime) {
</span> <span class="code-keyword">try</span> {
     LOG.info(<span class="code-quote">"Renewing TGT <span class="code-keyword">for</span> "</span>+tgt.getClient());
     tgt.refresh();
@@ -249,19 +249,21 @@ <span class="code-keyword">public</span> <span class="code-keyword">class </span>AutoTGT <span class="code-keyword">implements</span> IAutoCredentials, ICredentialsRenewer {
 } <span class="code-keyword">catch</span> (RefreshFailedException e) {
     LOG.warn(<span class="code-quote">"Failed to refresh TGT"</span>, e);
 }
-    }
+    <span class="code-comment">//}
</span> }
     }
 
     <span class="code-keyword">public</span> <span class="code-keyword">static</span> void main(<span class="code-object">String</span>[] args) <span class="code-keyword">throws</span> Exception {
+
 AutoTGT at = <span class="code-keyword">new</span> AutoTGT();
 Map conf = <span class="code-keyword">new</span> java.util.HashMap();
 conf.put(<span class="code-quote">"java.security.auth.login.config"</span>, args[0]);
 at.prepare(conf);
 Map<<span class="code-object">String</span>,<span class="code-object">String</span>> creds = <span class="code-keyword">new</span> java.util.HashMap<<span class="code-object">String</span>,<span class="code-object">String</span>>();
 at.populateCredentials(creds);
-Subject s = <span class="code-keyword">new</span> Subject();
-at.populateSubject(s, creds);
-LOG.info(<span class="code-quote">"Got a Subject "</span>+s);
+at.renew(creds);
+<span class="code-comment">//Subject s = <span class="code-keyword">new</span> Subject();
</span>+<span class="code-comment">//at.populateSubject(s, creds);
</span>+<span class="code-comment">//LOG.info(<span class="code-quote">"Got a Subject "</span>+s);
</span>     }
 }
</pre>
</div></div>

<p>I then called it.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java -cp ./storm-core-0.9.2-incubating-security.jar:./storm/lib/\* backtype.storm.security.auth.kerberos.AutoTGT  jaas.conf
</pre>
</div></div>

<p>The contents of jaas.conf are</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">StormClient {
   com.sun.security.auth.module.Krb5LoginModule required
   doNotPrompt=<span class="code-keyword">false</span>
   useTicketCache=<span class="code-keyword">true</span>
   serviceName=<span class="code-quote">"storm"</span>;
};
</pre>
</div></div>

<p>I end up with the following error as part of the output.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">294  [main] INFO  backtype.storm.security.auth.kerberos.AutoTGT - Pushing TGT <span class="code-keyword">for</span> me@TEST.COM to topology.
313  [main] INFO  backtype.storm.security.auth.kerberos.AutoTGT - Renewing TGT <span class="code-keyword">for</span> me@TEST.COM
452  [main] WARN  backtype.storm.security.auth.kerberos.AutoTGT - Failed to refresh TGT
javax.security.auth.RefreshFailedException: Failed to renew Kerberos Ticket <span class="code-keyword">for</span> client me@TEST.COM and server krbtgt/TEST.COM@TEST.COM - Message stream modified (41)
at javax.security.auth.kerberos.KerberosTicket.refresh(KerberosTicket.java:575) ~[na:1.7.0_17]
at backtype.storm.security.auth.kerberos.AutoTGT.renew(AutoTGT.java:247) [storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
at backtype.storm.security.auth.kerberos.AutoTGT.main(AutoTGT.java:264) [storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
Caused by: sun.security.krb5.internal.KrbApErrException: Message stream modified (41)
at sun.security.krb5.KrbKdcRep.check(KrbKdcRep.java:80) ~[na:1.7.0_17]
at sun.security.krb5.KrbTgsRep.<init>(KrbTgsRep.java:88) ~[na:1.7.0_17]
at sun.security.krb5.KrbTgsReq.getReply(KrbTgsReq.java:192) ~[na:1.7.0_17]
at sun.security.krb5.KrbTgsReq.sendAndGetCreds(KrbTgsReq.java:203) ~[na:1.7.0_17]
at sun.security.krb5.Credentials.renew(Credentials.java:259) ~[na:1.7.0_17]
at javax.security.auth.kerberos.KerberosTicket.refresh(KerberosTicket.java:567) ~[na:1.7.0_17]
... 2 common frames omitted
</pre>
</div></div>

<p>Turning on debug with -Dsun.security.krb5.debug=true is not that much better</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">>>>KinitOptions cache name is /tmp/krb5cc_38795
>>>DEBUG <CCacheInputStream>  client principal is me@TEST.COM
>>>DEBUG <CCacheInputStream> server principal is krbtgt/TEST.COM@TEST.COM
>>>DEBUG <CCacheInputStream> key type: 18
>>>DEBUG <CCacheInputStream> auth time: Wed Jul 02 16:19:06 UTC 2014
>>>DEBUG <CCacheInputStream> start time: Wed Jul 02 16:19:02 UTC 2014
>>>DEBUG <CCacheInputStream> end time: Thu Jul 03 02:19:06 UTC 2014
>>>DEBUG <CCacheInputStream> renew_till time: Wed Jul 09 16:19:02 UTC 2014
>>> CCacheInputStream: readFlags()  FORWARDABLE; RENEWABLE; INITIAL; PRE_AUTH;
Config name: /etc/krb5.conf
297  [main] INFO  backtype.storm.security.auth.kerberos.AutoTGT - Pushing TGT <span class="code-keyword">for</span> me@TEST.COM to topology.
316  [main] INFO  backtype.storm.security.auth.kerberos.AutoTGT - Renewing TGT <span class="code-keyword">for</span> me@TEST.COM
<span class="code-keyword">default</span> etypes <span class="code-keyword">for</span> default_tgs_enctypes: 23 16 17 18.
>>> CksumType: sun.security.krb5.internal.crypto.RsaMd5CksumType
>>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
>>> KdcAccessibility: reset
>>> KrbKdcReq send: kdc=kdc1.test.com. TCP:88, timeout=30000, number of retries =3, #bytes=1798
>>> KDCCommunication: kdc=kdc1.test.com. TCP:88, timeout=30000,Attempt =1, #bytes=1798
>>>DEBUG: TCPClient reading 1804 bytes
>>> KrbKdcReq send: #bytes read=1804
>>> KdcAccessibility: remove kdc1.test.com.:88
>>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
453  [main] WARN  backtype.storm.security.auth.kerberos.AutoTGT - Failed to refresh TGT
javax.security.auth.RefreshFailedException: Failed to renew Kerberos Ticket <span class="code-keyword">for</span> client me@TEST.COM and server krbtgt/TEST.COM@TEST.COM - Message stream modified (41)
at javax.security.auth.kerberos.KerberosTicket.refresh(KerberosTicket.java:575) ~[na:1.7.0_17]
at backtype.storm.security.auth.kerberos.AutoTGT.renew(AutoTGT.java:247) [storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
at backtype.storm.security.auth.kerberos.AutoTGT.main(AutoTGT.java:264) [storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
Caused by: sun.security.krb5.internal.KrbApErrException: Message stream modified (41)
at sun.security.krb5.KrbKdcRep.check(KrbKdcRep.java:80) ~[na:1.7.0_17]
at sun.security.krb5.KrbTgsRep.<init>(KrbTgsRep.java:88) ~[na:1.7.0_17]
at sun.security.krb5.KrbTgsReq.getReply(KrbTgsReq.java:192) ~[na:1.7.0_17]
at sun.security.krb5.KrbTgsReq.sendAndGetCreds(KrbTgsReq.java:203) ~[na:1.7.0_17]
at sun.security.krb5.Credentials.renew(Credentials.java:259) ~[na:1.7.0_17]
at javax.security.auth.kerberos.KerberosTicket.refresh(KerberosTicket.java:567) ~[na:1.7.0_17]
... 2 common frames omitted
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> can you try adding renewTGT=true in jaas.conf</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I get the same error as before.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> I was able to test it by using the following conf in kerberos</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">   ccache_type = 4
   forwardable = <span class="code-keyword">true</span>
   proxiable = <span class="code-keyword">true</span>
   udp_preference_limit = 1
   ticket_lifetime = 5m
   renew_lifetime = 10m
</pre>
</div></div>
<p>and changing AutoTGT main to</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> <span class="code-keyword">public</span> <span class="code-keyword">static</span> void main(<span class="code-object">String</span>[] args) <span class="code-keyword">throws</span> Exception {
AutoTGT at = <span class="code-keyword">new</span> AutoTGT();
Map conf = <span class="code-keyword">new</span> java.util.HashMap();
conf.put(<span class="code-quote">"java.security.auth.login.config"</span>, args[0]);
at.prepare(conf);
Map<<span class="code-object">String</span>,<span class="code-object">String</span>> creds = <span class="code-keyword">new</span> java.util.HashMap<<span class="code-object">String</span>,<span class="code-object">String</span>>();
at.populateCredentials(creds);
Subject s = <span class="code-keyword">new</span> Subject();
at.populateSubject(s, creds);
<span class="code-object">System</span>.out.println(<span class="code-quote">"Got a Subject "</span>+s);
<span class="code-object">Thread</span>.sleep(360000);
at.renew(creds);
<span class="code-object">System</span>.out.println(<span class="code-quote">"Got a Subject "</span>+s);
    }
</pre>
</div></div>
<p>and my jaas.conf</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">StormClient {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=<span class="code-keyword">true</span>
   keyTab=<span class="code-quote">"/vagrant/keytabs/harsha.keytab"</span>
   useTicketCache=<span class="code-keyword">true</span>
   renewTicket=<span class="code-keyword">true</span>
   serviceName=<span class="code-quote">"nimbus"</span>
   debug=<span class="code-keyword">true</span>
   principal=<span class="code-quote">"harsha/zookeeper.witzend.com@WITZEND.COM"</span>;
};
</pre>
</div></div>
<p>I did kinit -k -t /vagrant/keytabs/harsha.keytab harsha/zookeeper.witzend.com@WITZEND.COM<br/>
before running AutoTGT . I am able to renew ticket before and after ticket_lifetime .</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I hate the java implementation of kerberos.  Turns out that our krb5.conf had a setting in it that was forwardable = yes, not forwardable = true.  This was fine for the rest of kerberos, but mad java think it was not supposed to ask for a forwardable ticket.  So when it got back the renewed ticket from the KDC something didn't match and it got very angry.</p>

<p>Thanks for all of your help resolving this.</p>
