### ISSUE TITLE
[STORM-358] Multitenant scheduler fails to free a slot in bad-state

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4200]
<p>Nimbus crashes, as it fails to free  up the slot in bad state. </p>

<p> b.s.d.nimbus <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.lang.IllegalArgumentException: Tried to free a slot that was not part of this node 2a697d77-e16d-4586-a460-f7630244b68f<br/>
at backtype.storm.scheduler.multitenant.Node.free(Node.java:160) ~<span class="error">&#91;storm-core-0.9.0-wip21.jar:na&#93;</span><br/>
at backtype.storm.scheduler.multitenant.Node.getAllNodesFrom(Node.java:286) ~<span class="error">&#91;storm-core-0.9.0-wip21.jar:na&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-358" target="_blank">Multitenant scheduler fails to free a slot in bad-state</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-06-17T18:59:53+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/145" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/145</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-358" title="Multitenant scheduler fails to free a slot in bad-state" class="issue-link" data-issue-key="STORM-358"><del>STORM-358</del></a> - Multitenant scheduler fix to free a slot in bad-state</p>

<p>    Force free the slot that's in bad state during reassignments in multi tenant scheduler.<br/>
    Includes are unit test to validate the fix works for a slot in bad state.</p>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> slot-free-fix</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/145.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/145.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #145</p>

<hr />
<p>commit ab7784e49d251ca4da967c6ec6bc340cc7f940aa<br/>
Author: Kishor Patil <patik523@yahoo.com><br/>
Date:   2014-06-17T15:19:00Z</p>

<p>    Force free a slot in bad-state</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/145#issuecomment-46341662" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/145#issuecomment-46341662</a></p>

<p>    looks good.  +1 I'll pull this into security.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/145" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/145</a></p>
