### ISSUE TITLE
[STORM-374] storm0.9.1&kafka0.8.1 with storm-kafka-0.8-plus-0.5.0 can not run

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4216]
<p>ERROR backtype.storm.util - Async loop died!<br/>
java.lang.NoSuchMethodError: com.netflix.curator.framework.api.CreateBuilder.creatingParentsIfNeeded()Lcom/netflix/curator/framework/api/ProtectACLCreateModePathAndBytesable;<br/>
at storm.kafka.ZkState.writeBytes(ZkState.java:59) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at storm.kafka.ZkState.writeJSON(ZkState.java:53) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at storm.kafka.PartitionManager.commit(PartitionManager.java:188) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at storm.kafka.KafkaSpout.commit(KafkaSpout.java:169) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:134) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at backtype.storm.daemon.executor$eval5100$fn_<em>5101$fn</em><em>5116$fn</em>_5145.invoke(executor.clj:562) ~<span class="error">&#91;na:na&#93;</span><br/>
at backtype.storm.util$async_loop$fn__390.invoke(util.clj:433) ~<span class="error">&#91;na:na&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;na:1.6.0_45&#93;</span><br/>
12949 <span class="error">&#91;Thread-27-words&#93;</span> ERROR backtype.storm.daemon.executor - <br/>
java.lang.NoSuchMethodError: com.netflix.curator.framework.api.CreateBuilder.creatingParentsIfNeeded()Lcom/netflix/curator/framework/api/ProtectACLCreateModePathAndBytesable;<br/>
at storm.kafka.ZkState.writeBytes(ZkState.java:59) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at storm.kafka.ZkState.writeJSON(ZkState.java:53) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at storm.kafka.PartitionManager.commit(PartitionManager.java:188) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at storm.kafka.KafkaSpout.commit(KafkaSpout.java:169) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:134) ~<span class="error">&#91;storm-kafka-0.8-plus-0.5.0-SNAPSHOT.jar:na&#93;</span><br/>
at backtype.storm.daemon.executor$eval5100$fn_<em>5101$fn</em><em>5116$fn</em>_5145.invoke(executor.clj:562) ~<span class="error">&#91;na:na&#93;</span><br/>
at backtype.storm.util$async_loop$fn__390.invoke(util.clj:433) ~<span class="error">&#91;na:na&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;na:1.6.0_45&#93;</span><br/>
12971 <span class="error">&#91;Thread-27-words&#93;</span> INFO  backtype.storm.util - Halting process: ("Worker died")</p>

---
<details><summary><i>Originally reported by <a title="cha369" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cha369">cha369</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-374" target="_blank">storm0.9.1&kafka0.8.1 with storm-kafka-0.8-plus-0.5.0 can not run</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:01+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
