### ISSUE TITLE
[STORM-395] Using SaslTransportPlugin, fails to submit topology for jar file large than 3K

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4237]
<p>669  <span class="error">&#91;main&#93;</span> INFO  backtype.storm.security.auth.AuthUtils - Got AutoCreds []<br/>
847  <span class="error">&#91;main&#93;</span> INFO  backtype.storm.StormSubmitter - Uploading topology jar /home/kpatil/storm-starter-0.0.1-SNAPSHOT-jar-with-dependencies.jar to assigned location: storm-local/nimbus/inbox/stormjar-3bf4f7e5-3f9d-487f-9daa-12d8f4202440.jar<br/>
Exception in thread "main" java.lang.RuntimeException: org.apache.thrift7.transport.TTransportException<br/>
	at backtype.storm.StormSubmitter.submitJar(StormSubmitter.java:371)<br/>
	at backtype.storm.StormSubmitter.submitJar(StormSubmitter.java:315)<br/>
	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:215)<br/>
	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:157)<br/>
	at storm.starter.WordCountTopology.main(WordCountTopology.java:78)<br/>
Caused by: org.apache.thrift7.transport.TTransportException<br/>
	at org.apache.thrift7.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)<br/>
	at org.apache.thrift7.transport.TTransport.readAll(TTransport.java:84)<br/>
	at org.apache.thrift7.transport.TSaslTransport.readLength(TSaslTransport.java:345)<br/>
	at org.apache.thrift7.transport.TSaslTransport.readFrame(TSaslTransport.java:422)<br/>
	at org.apache.thrift7.transport.TSaslTransport.read(TSaslTransport.java:404)<br/>
	at org.apache.thrift7.transport.TSaslClientTransport.read(TSaslClientTransport.java:37)<br/>
	at org.apache.thrift7.transport.TTransport.readAll(TTransport.java:84)<br/>
	at org.apache.thrift7.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)<br/>
	at org.apache.thrift7.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297)<br/>
	at org.apache.thrift7.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204)<br/>
	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:69)<br/>
	at backtype.storm.generated.Nimbus$Client.recv_uploadChunk(Nimbus.java:419)<br/>
	at backtype.storm.generated.Nimbus$Client.uploadChunk(Nimbus.java:405)<br/>
	at backtype.storm.StormSubmitter.submitJar(StormSubmitter.java:360)<br/>
	... 4 more</p>

<p>And on nimbus side:<br/>
2014-07-08 17:54:08 o.a.t.s.TThreadPoolServer <span class="error">&#91;ERROR&#93;</span> Thrift error occurred during processing of message.<br/>
org.apache.thrift7.TException: Message length exceeded: 307200<br/>
	at org.apache.thrift7.protocol.TBinaryProtocol.checkReadLength(TBinaryProtocol.java:393) ~<span class="error">&#91;storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security&#93;</span><br/>
	at org.apache.thrift7.protocol.TBinaryProtocol.readBinary(TBinaryProtocol.java:363) ~<span class="error">&#91;storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security&#93;</span><br/>
	at backtype.storm.generated.Nimbus$uploadChunk_args.read(Nimbus.java:9555) ~<span class="error">&#91;storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security&#93;</span><br/>
	at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:21) ~<span class="error">&#91;storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security&#93;</span><br/>
	at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:34) ~<span class="error">&#91;storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security&#93;</span><br/>
	at backtype.storm.security.auth.SaslTransportPlugin$TUGIWrapProcessor.process(SaslTransportPlugin.java:134) ~<span class="error">&#91;storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security&#93;</span><br/>
	at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:176) ~<span class="error">&#91;storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;na:1.7.0_60&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;na:1.7.0_60&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_60&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-395" target="_blank">Using SaslTransportPlugin, fails to submit topology for jar file large than 3K</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-07-09T18:46:31+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/180" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/180</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-395" title="Using SaslTransportPlugin, fails to submit topology for jar file large than 3K" class="issue-link" data-issue-key="STORM-395"><del>STORM-395</del></a> Use TBinaryProtocol without max buffer</p>

<p>    For storm jar larger than 3K, the SaslTransportPlugin causes <a href="https://issues.apache.org/jira/browse/THRIFT-1665" title="TBinaryProtocol: exceeded message length raises generic TException" class="issue-link" data-issue-key="THRIFT-1665"><del>THRIFT-1665</del></a>( <a href="https://issues.apache.org/jira/browse/THRIFT-1665" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/THRIFT-1665</a>) TBinaryProtocol: exceeded message length raises generic TException. This is fixed in thirft 0.9 version. Since we are using 0.7.0 Here is using TBinaryProtocol without max buffer size.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> thrift-buffersize-patch-security</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/180.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/180.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #180</p>

<hr />
<p>commit ae5d0c312d170c883e9758767808e1c8d33f58c8<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-07-08T22:08:33Z</p>

<p>    Use TBinaryProtocol without max buffer</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/180#issuecomment-48507857" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/180#issuecomment-48507857</a></p>

<p>    +1 looks good to me.  I'll merge this into security.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks Kishor for finding and fixing this issue.</p>
