### ISSUE TITLE
[STORM-400] Thrift upgrade to 0.9.1

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4242]
<p>Upgrade Thrift to 0.9.1</p>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-400" target="_blank">Thrift upgrade to 0.9.1</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-10T19:51:07+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/184" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/184</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-400" title="Thrift upgrade to 0.9.1" class="issue-link" data-issue-key="STORM-400"><del>STORM-400</del></a> Thrift upgrade to 0.9.1</p>

<p>    Upgrade thrift to 0.9.1.</p>
<ul class="alternate" type="square">
	<li>Tested including trident topologies.</li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> thrift-upgrade</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/184.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/184.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #184</p>

<hr />
<p>commit da6ac7a75894ba4b94bcc45a8d7752b62dee848f<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-07-10T03:18:02Z</p>

<p>    thrift upgrade to 0.9.1</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/185" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/185</a></p>

<p>      <a href="https://issues.apache.org/jira/browse/STORM-400" title="Thrift upgrade to 0.9.1" class="issue-link" data-issue-key="STORM-400"><del>STORM-400</del></a> Thrift upgrade to 0.9.1 on security</p>

<p>    Upgrade thrift to 0.9.1.</p>
<ul class="alternate" type="square">
	<li>Tested including trident topologies.</li>
	<li>Used <a href="https://github.com/kishorvpatil/thrift/tree/storm_thrift9" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/thrift/tree/storm_thrift9</a> branch to generate code using thrift9 with python hash function.</li>
	<li>Created <a href="https://github.com/apache/thrift/pull/156" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/thrift/pull/156</a> for thrift project.</li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> thrift-upgrade-security</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/185.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/185.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #185</p>

<hr />
<p>commit 1b323412c9e60fb4ca6aeadc48659a8f703ad81f<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-07-10T20:54:27Z</p>

<p>    Upgrade thrift to 0.9.1</p>

<p>commit f8d8e180f93ebdac907183136303984139fd7136<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-07-10T21:48:05Z</p>

<p>    Merge branch 'security' of github.com:apache/incubator-storm into thrift-upgrade-security</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/184#issuecomment-48832134" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/184#issuecomment-48832134</a></p>

<p>    Really important things from this PR is, what Storm get advantages when we move thrift version to 0.9.1?<br/>
    I think you need to explain it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/184#issuecomment-48864343" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/184#issuecomment-48864343</a></p>

<p>    @kishorvpatil Thank you for kind explanation. <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/184#issuecomment-48945869" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/184#issuecomment-48945869</a></p>

<p>    Closing this pull request for now, as I am waiting for <a href="https://issues.apache.org/jira/browse/THRIFT-2621" title="Add basic default hash code method to python" class="issue-link" data-issue-key="THRIFT-2621"><del>THRIFT-2621</del></a>( <a href="https://issues.apache.org/jira/browse/THRIFT-2621" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/THRIFT-2621</a>) to resolve. I will update and reopen this pull request after that.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/185#issuecomment-48945896" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/185#issuecomment-48945896</a></p>

<p>    Closing this pull request for now, as I am waiting for <a href="https://issues.apache.org/jira/browse/THRIFT-2621" title="Add basic default hash code method to python" class="issue-link" data-issue-key="THRIFT-2621"><del>THRIFT-2621</del></a>( <a href="https://issues.apache.org/jira/browse/THRIFT-2621" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/THRIFT-2621</a>) to resolve. I will update and reopen this pull request after that.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/410" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-400" title="Thrift upgrade to 0.9.1" class="issue-link" data-issue-key="STORM-400"><del>STORM-400</del></a> Thrift upgrade to thrift-0.9.2</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> thrift092</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/410.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #410</p>

<hr />
<p>commit ef51dbeeb1a5a748deb7ee4f399ef430df443525<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-02-02T23:44:30Z</p>

<p>    Upgrade to thrift-0.9.2</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/410#issuecomment-73174063" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410#issuecomment-73174063</a></p>

<p>    @ptgoetz, Thanks for reviewing this. I have up merged the changes. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/410#issuecomment-73267260" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410#issuecomment-73267260</a></p>

<p>    The changes look good for the most part, but I am seeing a hang that comes up rather frequently.</p>

<p>    ```<br/>
    "main" #1 prio=5 os_prio=31 tid=0x00007fc339801000 nid=0x1303 waiting on condition <span class="error">&#91;0x000000010357a000&#93;</span><br/>
       java.lang.Thread.State: WAITING (parking)<br/>
    	at sun.misc.Unsafe.park(Native Method)</p>
<ul class="alternate" type="square">
	<li>parking to wait for  <0x0000000776c693f0> (a java.util.concurrent.Semaphore$NonfairSync)<br/>
    	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)<br/>
    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)<br/>
    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)<br/>
    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)<br/>
    	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)<br/>
    	at backtype.storm.daemon.drpc$service_handler$reify__7034.execute(drpc.clj:104)<br/>
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
    	at java.lang.reflect.Method.invoke(Method.java:483)<br/>
    	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)<br/>
    	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)<br/>
    	at backtype.storm.LocalDRPC$_execute.invoke(LocalDRPC.clj:35)<br/>
    	at backtype.storm.LocalDRPC.execute(Unknown Source)<br/>
    	at backtype.storm.drpc_test$fn_<em>1523$fn</em>_1526.invoke(drpc_test.clj:189)<br/>
    	at backtype.storm.drpc_test$fn__1523.invoke(drpc_test.clj:189)<br/>
    	at clojure.test$test_var$fn__7187.invoke(test.clj:704)<br/>
    	at clojure.test$test_var.invoke(test.clj:704)<br/>
    	at clojure.test$test_vars$fn_<em>7209$fn</em>_7214.invoke(test.clj:722)<br/>
    	at clojure.test$default_fixture.invoke(test.clj:674)<br/>
    	at clojure.test$test_vars$fn__7209.invoke(test.clj:722)<br/>
    	at clojure.test$default_fixture.invoke(test.clj:674)<br/>
    	at clojure.test$test_vars.invoke(test.clj:718)<br/>
    	at clojure.test$test_all_vars.invoke(test.clj:728)<br/>
    	at clojure.test$test_ns.invoke(test.clj:747)<br/>
    	at clojure.core$map$fn__4245.invoke(core.clj:2559)<br/>
    	at clojure.lang.LazySeq.sval(LazySeq.java:40)</li>
	<li>eliminated <0x00000007757dec88> (a clojure.lang.LazySeq)<br/>
    	at clojure.lang.LazySeq.seq(LazySeq.java:49)</li>
	<li>locked <0x00000007757dec88> (a clojure.lang.LazySeq)<br/>
    	at clojure.lang.Cons.next(Cons.java:39)<br/>
    	at clojure.lang.RT.boundedLength(RT.java:1654)<br/>
    	at clojure.lang.RestFn.applyTo(RestFn.java:130)<br/>
    	at clojure.core$apply.invoke(core.clj:626)<br/>
    	at clojure.test$run_tests.doInvoke(test.clj:762)<br/>
    	at clojure.lang.RestFn.invoke(RestFn.java:408)<br/>
    	at com.theoryinpractise.clojure.testrunner$eval12750$fn_<em>12755$fn</em>_12812.invoke(run-test1041168096946393675.clj:123)<br/>
    	at com.theoryinpractise.clojure.testrunner$eval12750$fn__12755.invoke(run-test1041168096946393675.clj:120)<br/>
    	at com.theoryinpractise.clojure.testrunner$eval12750.invoke(run-test1041168096946393675.clj:81)<br/>
    	at clojure.lang.Compiler.eval(Compiler.java:6703)<br/>
    	at clojure.lang.Compiler.load(Compiler.java:7130)<br/>
    	at clojure.lang.Compiler.loadFile(Compiler.java:7086)<br/>
    	at clojure.main$load_script.invoke(main.clj:274)<br/>
    	at clojure.main$script_opt.invoke(main.clj:336)<br/>
    	at clojure.main$main.doInvoke(main.clj:420)<br/>
    	at clojure.lang.RestFn.invoke(RestFn.java:408)<br/>
    	at clojure.lang.Var.invoke(Var.java:379)<br/>
    	at clojure.lang.AFn.applyToHelper(AFn.java:154)<br/>
    	at clojure.lang.Var.applyTo(Var.java:700)<br/>
    	at clojure.main.main(main.java:37)<br/>
    ```</li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/410#issuecomment-73552653" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410#issuecomment-73552653</a></p>

<p>    +1</p>

<p>    I was having the same issues as @revans2  until I ran `mvn install -DskipTests` After that, `mvn test` has succeeded consistently.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/410#issuecomment-73601819" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410#issuecomment-73601819</a></p>

<p>    the workaround from @knusbaum didn't work for me, but I also hit the same issue without this patch in, so I think it is a race condition that was not modified by this patch.  I am OK with merging this in as is, but I will keep trying to track down the root cause.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user darionyaphet commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/410#issuecomment-73672570" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410#issuecomment-73672570</a></p>

<p>    what is difference between thrift 0.9.0 and 0.9.2 ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/410#issuecomment-74700449" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410#issuecomment-74700449</a></p>

<p>    @darionyaphet, Thrift 0.9.2 includes python hash function. <a href="https://issues.apache.org/jira/browse/THRIFT-2621" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/THRIFT-2621</a>. Without this change, we were using @nathanmarz 's storm specific thrift branch. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/410" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/410</a></p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20THRIFT-2621">THRIFT-2621</a>]</i>
