### ISSUE TITLE
[STORM-401] supervisor-test sometimes crashes due to InterruptedIOException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4243]
<p>supervisor-test sometimes crashes due to InterruptedIOException. It seems to depend on the timing of shutting down local cluster.</p>

---
<details><summary><i>Originally reported by <a title="Masatake Iwasaki" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iwasakims">iwasakims</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-401" target="_blank">supervisor-test sometimes crashes due to InterruptedIOException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Masatake Iwasaki" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iwasakims">iwasakims</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-08-26T22:40:18+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iwasakims">iwasakims</a>:</i>
<p>I saw the crash in event-manager and mk-worker.</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>17062 [Thread-14] ERROR backtype.storm.event - Error when processing event
java.io.InterruptedIOException: null
	at reply.hacks.printing$print_sequential.invoke(printing.clj:31) ~[na:na]
	at clojure.core$print_map.invoke(core_print.clj:203) ~[clojure-1.5.1.jar:na]
	at clojure.core$fn__5449.invoke(core_print.clj:260) ~[clojure-1.5.1.jar:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:231) ~[clojure-1.5.1.jar:na]
	at clojure.core$pr_on.invoke(core.clj:3322) ~[clojure-1.5.1.jar:na]
	at clojure.core$pr.invoke(core.clj:3334) ~[clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:161) [clojure-1.5.1.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at clojure.core$pr_str.doInvoke(core.clj:4297) ~[clojure-1.5.1.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$sync_processes$iter__4359__4363$fn__4364.invoke(supervisor.clj:268) ~[na:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.5.1.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:60) ~[clojure-1.5.1.jar:na]
	at clojure.lang.RT.seq(RT.java:484) ~[clojure-1.5.1.jar:na]
	at clojure.core$seq.invoke(core.clj:133) ~[clojure-1.5.1.jar:na]
	at clojure.core$dorun.invoke(core.clj:2780) ~[clojure-1.5.1.jar:na]
	at clojure.core$doall.invoke(core.clj:2796) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:265) ~[classes/:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:161) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:619) ~[clojure-1.5.1.jar:na]
	at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) ~[clojure-1.5.1.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:397) ~[clojure-1.5.1.jar:na]
	at backtype.storm.event$event_manager$fn__4814.invoke(event.clj:39) ~[classes/:na]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
</pre>
</div></div>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>11275 [Thread-13] ERROR backtype.storm.daemon.worker - Error on initialization of server mk-worker
java.io.InterruptedIOException: null
at reply.hacks.printing$print_sequential.invoke(printing.clj:31) ~[na:na]
at clojure.core$print_map.invoke(core_print.clj:203) ~[clojure-1.5.1.jar:na]
at clojure.core$fn__5431.invoke(core_print.clj:207) ~[clojure-1.5.1.jar:na]
at clojure.lang.MultiFn.invoke(MultiFn.java:231) [clojure-1.5.1.jar:na]
at clojure.core$pr_on.invoke(core.clj:3322) ~[clojure-1.5.1.jar:na]
at clojure.lang.Var.invoke(Var.java:419) ~[clojure-1.5.1.jar:na]
at clojure.lang.RT.print(RT.java:1748) [clojure-1.5.1.jar:na]
at clojure.lang.RT.printString(RT.java:1727) [clojure-1.5.1.jar:na]
at clojure.lang.APersistentMap.toString(APersistentMap.java:21) ~[clojure-1.5.1.jar:na]
at clojure.core$str.invoke(core.clj:513) ~[clojure-1.5.1.jar:na]
at clojure.core$str$fn__3896.invoke(core.clj:517) ~[clojure-1.5.1.jar:na]
at clojure.core$str.doInvoke(core.clj:519) ~[clojure-1.5.1.jar:na]
at clojure.lang.RestFn.invoke(RestFn.java:816) [clojure-1.5.1.jar:na]
at backtype.storm.daemon.worker$fn__6855$exec_fn__2478__auto____6856.invoke(worker.clj:356) ~[classes/:na]
at clojure.lang.AFn.applyToHelper(AFn.java:185) [clojure-1.5.1.jar:na]
at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
at clojure.core$apply.invoke(core.clj:617) [clojure-1.5.1.jar:na]
at backtype.storm.daemon.worker$fn__6855$mk_worker__6911.doInvoke(worker.clj:355) [classes/:na]
at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
at backtype.storm.daemon.supervisor$fn__7382.invoke(supervisor.clj:561) [classes/:na]
at clojure.lang.MultiFn.invoke(MultiFn.java:241) [clojure-1.5.1.jar:na]
at backtype.storm.daemon.supervisor$sync_processes$iter__7226__7230$fn__7231.invoke(supervisor.clj:277) [classes/:na]
at clojure.lang.LazySeq.sval(LazySeq.java:42) [clojure-1.5.1.jar:na]
at clojure.lang.LazySeq.seq(LazySeq.java:60) [clojure-1.5.1.jar:na]
at clojure.lang.RT.seq(RT.java:484) [clojure-1.5.1.jar:na]
at clojure.core$seq.invoke(core.clj:133) [clojure-1.5.1.jar:na]
at clojure.core$dorun.invoke(core.clj:2780) [clojure-1.5.1.jar:na]
at clojure.core$doall.invoke(core.clj:2796) [clojure-1.5.1.jar:na]
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:265) [classes/:na]
at clojure.lang.AFn.applyToHelper(AFn.java:161) [clojure-1.5.1.jar:na]
at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
at clojure.core$apply.invoke(core.clj:619) [clojure-1.5.1.jar:na]
at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) [clojure-1.5.1.jar:na]
at clojure.lang.RestFn.invoke(RestFn.java:397) [clojure-1.5.1.jar:na]
at backtype.storm.event$event_manager$fn__4814.invoke(event.clj:39) [classes/:na]
at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
at java.lang.Thread.run(Thread.java:744) [na:1.7.0_55]
11300 [Thread-13] INFO  backtype.storm.util - Halting process: ("Error on initialization")
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user iwasakims opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/191" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/191</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-401" title="supervisor-test sometimes crashes due to InterruptedIOException" class="issue-link" data-issue-key="STORM-401"><del>STORM-401</del></a>: supervisor-test sometimes crashes due to InterruptedIOException</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/iwasakims/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/iwasakims/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-401" title="supervisor-test sometimes crashes due to InterruptedIOException" class="issue-link" data-issue-key="STORM-401"><del>STORM-401</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/191.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/191.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #191</p>

<hr />
<p>commit 492dfb9b4a2953c562099740113eccb70a65bf2a<br/>
Author: iwasakims <iwasakims@example.com><br/>
Date:   2014-07-14T13:12:43Z</p>

<p>    added handling of InterruptedIOException.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user xiaokang commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/191#issuecomment-49539641" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/191#issuecomment-49539641</a></p>

<p>    @iwasakims , is there more information about why InterruptedIOException occurs in supervisor-test?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/191#issuecomment-53494292" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/191#issuecomment-53494292</a></p>

<p>    @xiaokang </p>

<p>    InterruptedIOException shows up when a thread is interrupted while doing an IO operation.  It is a pain that it is not a subclass of InterruptedException but it serves essentially the same purpose.  The code looks fine to me.</p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks Masatake Iwasaki,</p>

<p>I merged this into master.  Sorry it took so long to get a review.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/191" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/191</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user iwasakims commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/191#issuecomment-53504833" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/191#issuecomment-53504833</a></p>

<p>    Sorry for not responding this. I saw the error when I run the tests in supervisor_test or nimbus_test. Not every time but occasionally in my env.</p>
