### ISSUE TITLE
[STORM-403] heartbeats-to-nimbus in supervisor-test failed due to unintentional worker launch

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4245]
<p>heartbeats-to-nimbus in supervisor-test failed due to unintentional worker launch. Moving the call of advance-cluster-time to inside capture-changed-workers fixed this.</p>

---
<details><summary><i>Originally reported by <a title="Masatake Iwasaki" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iwasakims">iwasakims</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-403" target="_blank">heartbeats-to-nimbus in supervisor-test failed due to unintentional worker launch</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Masatake Iwasaki" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iwasakims">iwasakims</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-07-21T17:36:11+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user iwasakims opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/193" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/193</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-403" title="heartbeats-to-nimbus in supervisor-test failed due to unintentional worker launch" class="issue-link" data-issue-key="STORM-403"><del>STORM-403</del></a>: heartbeats-to-nimbus in supervisor-test failed due to uninten...</p>

<p>    ...tional worker launch</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/iwasakims/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/iwasakims/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-403" title="heartbeats-to-nimbus in supervisor-test failed due to unintentional worker launch" class="issue-link" data-issue-key="STORM-403"><del>STORM-403</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/193.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/193.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #193</p>

<hr />
<p>commit e6d138e1935ad77099ea8513a1ea3d6141beec82<br/>
Author: iwasakims <iwasakims@example.com><br/>
Date:   2014-07-16T13:26:15Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-403" title="heartbeats-to-nimbus in supervisor-test failed due to unintentional worker launch" class="issue-link" data-issue-key="STORM-403"><del>STORM-403</del></a>: heartbeats-to-nimbus in supervisor-test failed due to unintentional worker launch</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/193#issuecomment-49321437" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/193#issuecomment-49321437</a></p>

<p>    The code change looks fine to me, and all of the tests still pass.  I am +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/193#issuecomment-49321526" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/193#issuecomment-49321526</a></p>

<p>    I forgot to mention that I'll give others some time to comment before merging this in.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user iwasakims commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/193#issuecomment-49348655" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/193#issuecomment-49348655</a></p>

<p>    @d2r, launch-worker and shutdown-worker are called from sync-processes which called every 3 seconds by even-manager thread in supervisor.<br/>
    If you submit-local-topology inside capture-changed-workers, advance-cluster-time also should be called inside the capture-changed-worker because launch-worker and shutdown-worker are mocked only inside it.  If you advance-cluster-time outside capture-changed-worker, actual launch-worker (:local) is called and the test process halt because of interrupt at end of the test.<br/>
    ```<br/>
    25524 <span class="error">&#91;Thread-14&#93;</span> ERROR backtype.storm.daemon.worker - Error on initialization of server mk-worker<br/>
    java.io.InterruptedIOException: null<br/>
    	at reply.hacks.printing$print_sequential.invoke(printing.clj:31) ~<span class="error">&#91;na:na&#93;</span><br/>
    	at clojure.core$print_map.invoke(core_print.clj:203) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$fn__5431.invoke(core_print.clj:207) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.MultiFn.invoke(MultiFn.java:231) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$pr_on.invoke(core.clj:3322) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.Var.invoke(Var.java:419) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.RT.print(RT.java:1748) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.RT.printString(RT.java:1727) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.APersistentMap.toString(APersistentMap.java:21) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$str.invoke(core.clj:513) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$str$fn__3896.invoke(core.clj:517) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$str.doInvoke(core.clj:519) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.RestFn.invoke(RestFn.java:816) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at backtype.storm.daemon.worker$fn_<em>6855$exec_fn</em><em>2478</em><em>auto</em>___6856.invoke(worker.clj:356) ~<span class="error">&#91;classes/:na&#93;</span><br/>
    	at clojure.lang.AFn.applyToHelper(AFn.java:185) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$apply.invoke(core.clj:617) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at backtype.storm.daemon.worker$fn_<em>6855$mk_worker</em>_6911.doInvoke(worker.clj:355) <span class="error">&#91;classes/:na&#93;</span><br/>
    	at clojure.lang.RestFn.invoke(RestFn.java:512) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at backtype.storm.daemon.supervisor$fn__7382.invoke(supervisor.clj:561) <span class="error">&#91;classes/:na&#93;</span><br/>
    	at clojure.lang.MultiFn.invoke(MultiFn.java:241) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at backtype.storm.daemon.supervisor$sync_processes$iter_<em>7226</em><em>7230$fn</em>_7231.invoke(supervisor.clj:277) <span class="error">&#91;classes/:na&#93;</span><br/>
    	at clojure.lang.LazySeq.sval(LazySeq.java:42) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.LazySeq.seq(LazySeq.java:60) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.RT.seq(RT.java:484) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$seq.invoke(core.clj:133) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$dorun.invoke(core.clj:2780) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$doall.invoke(core.clj:2796) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:265) <span class="error">&#91;classes/:na&#93;</span><br/>
    	at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$apply.invoke(core.clj:619) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at clojure.lang.RestFn.invoke(RestFn.java:397) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at backtype.storm.event$event_manager$fn__4814.invoke(event.clj:39) <span class="error">&#91;classes/:na&#93;</span><br/>
    	at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
    	at java.lang.Thread.run(Thread.java:744) <span class="error">&#91;na:1.7.0_45&#93;</span><br/>
    25525 <span class="error">&#91;Thread-14&#93;</span> INFO  backtype.storm.util - Halting process: ("Error on initialization")</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/193" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/193</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks Masatake, I merged this into master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iwasakims">iwasakims</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a>!</p>
