### ISSUE TITLE
[STORM-404] Worker on one machine crashes due to a failure of another worker on another machine

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4246]
<p>I have two workers (one on each machine). The first worker(10.30.206.125) had a problem starting (could not find Nimbus host), however the second worker crashed too since it could not connect to the first worker.</p>

<p>This looks like a cascading failure, which seems like a bug.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2014-07-15 17:43:32 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [17]
2014-07-15 17:43:33 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [18]
2014-07-15 17:43:34 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [19]
2014-07-15 17:43:35 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [20]
2014-07-15 17:43:36 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [21]
2014-07-15 17:43:37 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [22]
2014-07-15 17:43:38 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [23]
2014-07-15 17:43:39 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [24]
2014-07-15 17:43:40 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [25]
2014-07-15 17:43:41 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [26]
2014-07-15 17:43:42 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [27]
2014-07-15 17:43:43 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [28]
2014-07-15 17:43:44 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [29]
2014-07-15 17:43:45 b.s.m.n.Client [INFO] Reconnect started <span class="code-keyword">for</span> Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700... [30]
2014-07-15 17:43:46 b.s.m.n.Client [INFO] Closing Netty Client Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700
2014-07-15 17:43:46 b.s.m.n.Client [INFO] Waiting <span class="code-keyword">for</span> pending batchs to be sent with Netty-Client-ip-10-30-206-125.ec2.internal/10.30.206.125:6700..., timeout: 600000ms, pendings: 0
2014-07-15 17:43:46 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: java.lang.RuntimeException: Client is being closed, and does not take requests any more
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:128) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:99) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.disruptor$consume_loop_STAR_$fn__758.invoke(disruptor.clj:94) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.util$async_loop$fn__457.invoke(util.clj:431) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [na:1.7.0_60]
Caused by: java.lang.RuntimeException: Client is being closed, and does not take requests any more
at backtype.storm.messaging.netty.Client.send(Client.java:194) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.utils.TransferDrainer.send(TransferDrainer.java:54) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.daemon.worker$mk_transfer_tuples_handler$fn__5927$fn__5928.invoke(worker.clj:322) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.daemon.worker$mk_transfer_tuples_handler$fn__5927.invoke(worker.clj:320) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.disruptor$clojure_handler$reify__745.onEvent(disruptor.clj:58) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:125) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
... 6 common frames omitted
2014-07-15 17:43:46 b.s.util [INFO] Halting process: (<span class="code-quote">"Async loop died!"</span>)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Itai Frenkel" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=itaifrenkel">itaifrenkel</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-404" target="_blank">Worker on one machine crashes due to a failure of another worker on another machine</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Michael G. Noll" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=miguno">miguno</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-04-30T08:38:13+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtask of parent task STORM-329

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>I've tried to reproduce your situation with storm-starter, and it doesn't reproduced.</p>

<p>I've modified your situation to use 3 machines(A, B, C - A has nimbus, too.), which has 4 ports. (total 12 ports) And I've modified storm-starter to use 6 workers. <br/>
After submitting jar, 2 workers are created for each machine. 6 ports are remained.</p>

<p>I had shutdown B's supervisor to restrict resurrection and kill all workers belong to B.<br/>
Then all remaining workers was trying to reconnect killed workers. (as we expected)</p>

<p>But Nimbus recognized failed workers and reallocate workers to other ports.<br/>
Alive workers recognized new workers (with clean up connection with killed workers) and continue their tasks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>So you can review some checkpoints.</p>

<p>1. Did Nimbus recognized failure of first worker? If then, did Nimbus try to reassign new worker?<br/>
2. Was there free slots to reassign?<br/>
3. Can you check these options?<br/>
(Please try to see your version of defaults.yml or your custom setting, since it's current master's value.)</p>
<blockquote>
<p>nimbus.task.timeout.secs: 30<br/>
nimbus.supervisor.timeout.secs: 60<br/>
nimbus.task.launch.secs: 120<br/>
nimbus.reassign: true<br/>
&#35;how long supervisor will wait to ensure that a worker process is started<br/>
supervisor.worker.start.timeout.secs: 120<br/>
&#35;how long between heartbeats until supervisor considers that worker dead and tries to restart it<br/>
supervisor.worker.timeout.secs: 30<br/>
&#35;how frequently the supervisor checks on the status of the processes it's monitoring and restarts if necessary<br/>
supervisor.monitor.frequency.secs: 3<br/>
&#35;how frequently the supervisor heartbeats to the cluster state (for nimbus)<br/>
supervisor.heartbeat.frequency.secs: 5<br/>
supervisor.enable: true<br/>
worker.heartbeat.frequency.secs: 1<br/>
task.heartbeat.frequency.secs: 3<br/>
&#35; Since nimbus.task.launch.secs and supervisor.worker.start.timeout.secs are 120, other workers should also wait at least that long before giving up on connecting to the other worker.<br/>
storm.messaging.netty.max_retries: 300<br/>
storm.messaging.netty.max_wait_ms: 1000<br/>
storm.messaging.netty.min_wait_ms: 100</p></blockquote>

<p>Btw, if first machine cannot find nimbus host, did first machine's supervisor work properly?<br/>
Did supervisor send heartbeat to Nimbus?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Btw, we can fix it to not crash while accessing closed netty client.<br/>
If Nimbus or supervisor eventually assigned new worker, closed client may be cleaned up (as I think).</p>

<p>If it makes sense, I'll try to make a PR.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I just duped <a href="https://issues.apache.org/jira/browse/STORM-450" title="Netty can cause error on clean shutdown of worker" class="issue-link" data-issue-key="STORM-450"><del>STORM-450</del></a> to this one, because this was filed first.  The exception is thrown when the client is shutting down.  The client is shutting down in one of two cases.  Either the client is shutting down, or it gets a message with a task id of -1. If it were shut down because it got the -1 message then it would log "Receiving-thread:<span class="error">&#91;" storm-id ", " port "&#93;</span> received shutdown notice".  I didn't see that in your logs, so I have to assume that the process itself was already going to shut down.  But I don't know for sure.</p>

<p>Is this a reproducible use case for you?  It only showed up once for me.  If it is then I would be happy to help debug this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>If you just don't want to throw I think that is OK, but I am a bit nervous that we might end up eating a lot of messages waiting for another client to come up.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>:</i>
<p>I found this error just now. In my situation, supervisor is alive, bug some worker on this supervisor just died for some reason,  then worker on some other supervisor will exit because the " java.lang.RuntimeException" at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:128), anyone have some suggestions, thanks a lot.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> I reproduce this situation everytime in the case below：<br/>
In my case,there are 5 machines,4 machines for supervisor with 6 port and 1 for nimbus; my topology use 24 worker（this means all the ports in the supervisors); But there is a little trick, the prepare method in my bolt just throw exception and do nothing else, this will cause the worker exit immediately. Then other worker will exit with log that <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=itaifrenkel" class="user-hover" rel="itaifrenkel">Itai Frenkel</a> mentioned before.</p>

<p>I read the code and found that in my situation, when the  first worker(we named it as A) exit, other worker has not connect to worker A, so they retried for many times and closing this Client, note that connect logic is async and called from Client Constructor; Because connect and send method are synchronized, send must wait until connect returned, but when send run, close had been called by connect and mark closing as true, so connect will throw that Exception;</p>

<p>But i am still confused if this can happen: just remove the Exception in Bolt::prepare, and worker A exit for some unknown reason, and worker B connect to worker A will fail after retry, and then worker B can send tuple to worker A, this will end up with call send again, this will cause worker B exit by that Exception. You may say that nimbus will find worker A exit and tell worker B not send tuple to worker A any more, but worker and nimbus connected by zookeeper, and worker read nimbus's command Periodically, this is done by mk-refresh-connections. mk-refresh-connections and send share the same RWlock, when the machine load is heavy, there is a chance that mk-refresh-connections not called between the sends, where the first send has close the connection in Client;</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clockfly">clockfly</a>:</i>
<p>I got a chance to talk with XIajun offline.</p>

<p>Suppose we have a topology of two tasks, spout -> bolt. spout lies in worker A, bolt task lies in worker B. spout task (worker A) is <br/>
sending data to bolt task(worker B).</p>

<p>spout(on worker A) -->bolt (on worker B) </p>

<p>The reproduction sequence can looks like this:<br/>
1. worker B crash.<br/>
2. nimbus find worker B crashes, and scheduled a new worker C, relocate blot task to worker C. And then it tries to heartbeat this change to worker A.<br/>
3. Worker A has not received the heartbeat from nimbus yet. It still believe bolt task lies on worker B. And tries to send current message tuple to worker B.<br/>
4. worker A get heartbeat from nimbus, it now knows bolt task lies on worker C. For new messages to bolt, worker A will directly send them to worker C.<br/>
5. As the same time of step 4, however, the sending for message at step 3 continues. In this context, worker A will still tries to send message to worker B, retries, and eventually aborted. When it abort, there will a RuntimeException thrown, which cannot be catched. worker A also crashes.<br/>
6. Worker B crash cause worker A to crash also.<br/>
7. Reproduced</p>

<p>This issue will happen when worker A tries to send message to crashed worker B in a small time window, in which worker B crash but worker A still not getting the new worker assignment update from nimbus yet.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>:</i>
<p>Thank to <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clockfly" class="user-hover" rel="clockfly">Sean Zhong</a>, this is exactly the situation that I had encountered, but there's one thing I want to say: Even when worker reconnect time is greatly longer than worker timeout, this case can happen. This is because send logic and worker heartbeat logic in different threads and protected by the same RWLock, there are competition between these threads.</p>

<p>Thanks again.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clockfly">clockfly</a>:</i>
<p>Would you want to submit a patch for this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>:</i>
<p>ok, I will try later.</p>


<p>tedxia01@gmail.com</p>

<p>From: Sean Zhong (JIRA)<br/>
Date: 2014-09-10 16:45<br/>
To: tedxia01<br/>
Subject: <span class="error">&#91;jira&#93;</span> <span class="error">&#91;Commented&#93;</span> (<a href="https://issues.apache.org/jira/browse/STORM-404" title="Worker on one machine crashes due to a failure of another worker on another machine" class="issue-link" data-issue-key="STORM-404"><del>STORM-404</del></a>) Worker on one machine crashes due to a failure of another worker on another machine</p>

<p>    [ <a href="https://issues.apache.org/jira/browse/STORM-404?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=14128225#comment-14128225" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-404?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=14128225#comment-14128225</a> ] </p>

<p>Sean Zhong commented on <a href="https://issues.apache.org/jira/browse/STORM-404" title="Worker on one machine crashes due to a failure of another worker on another machine" class="issue-link" data-issue-key="STORM-404"><del>STORM-404</del></a>:<br/>
----------------------------------</p>

<p>Would you want to submit a patch for this?</p>




<p>&#8211;<br/>
This message was sent by Atlassian JIRA<br/>
(v6.3.4#6332)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clockfly">clockfly</a>:</i>
<p>I will work with Ted to make a patch for this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=riteshadval">riteshadval</a>:</i>
<p>Hi guys,</p>

<p>We are having this exact same issue on one of our production zone cluster with 9 storm supervisors. In one of our topology which has high load, we are reading messages via Kafka and this topology workers are crashing with the exceptions reported in the ticket. Another topology with lighter load does not exhibit this error. </p>

<p>Moreover the exact same two topologies are running in a different zone cluster with same number of supervisors and they are working without crashing the worker.</p>

<p>Is there any work around for this issue, or patch available? We are kind of stuck and might need to roll back to 0.8.2 storm version which was working for us.</p>

<p>Thanks<br/>
Ritesh</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marz">marz</a>:</i>
<p>Do you see this problem with the ZeroMQ transport or just with Netty? The big change from 0.8.* to 0.9.* was making Netty the default. The behavior of the transport is supposed to be to just drop messages if it can't connect to the other worker (or buffer and drop once the reassignment is received). It sounds like the Netty transport might not be doing this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marz">marz</a>:</i>
<p>Yes, switching to ZeroMQ transport may fix the problem. Please try it out and let us know.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=riteshadval">riteshadval</a>:</i>
<p>Thanks so looks like ZeroMQ is not going to work in 0.9.2, could <a href="https://issues.apache.org/jira/browse/STORM-355" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-355</a> duplicate netty jar in 0.9.2 cause this issue:</p>

<p>riteshadval@storm1 ~ $ ls -l /usr/share/storm/lib/ | grep netty<br/>
<del>rw-r</del><del>r</del>- 1 root root  785556 Aug 16 01:20 netty-3.2.2.Final.jar<br/>
<del>rw-r</del><del>r</del>- 1 root root 1202373 Aug 16 01:20 netty-3.6.3.Final.jar</p>

<p>we are only seeing this issue in one cluster and not another.?</p>

<p>Thanks<br/>
Ritesh</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> I have a pull request for this in <a href="https://issues.apache.org/jira/browse/STORM-329" title="Fix cascading Storm failure by improving reconnection strategy and buffering messages" class="issue-link" data-issue-key="STORM-329"><del>STORM-329</del></a>, which fix the same problem as <a href="https://issues.apache.org/jira/browse/STORM-510" title="Netty messaging client blocks transfer thread on reconnect" class="issue-link" data-issue-key="STORM-510"><del>STORM-510</del></a>. The pull request is <a href="https://github.com/apache/storm/pull/268" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/268</a>, the main change are:<br/>
1. When worker is disconnected, reconnect it async, so that reconnect will not block other worker.<br/>
2. In order to limit the memory limit, Client will buffer message as many as possible, if there are too many message we will block until there are enough space for the new arrival message. There also a timer for the buffered message, if the messages has cached for more than "topology.message.timeout.secs", we will drop the cached message.</p>

<p>Thank a lot for you if you can have a look at this pull request, and I am very happy to work on this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>:</i>
<p>I have run this patch on our product cluster for nearly two weeks, and the topology run very well with no failed tuple. This patch can also fix <a href="https://issues.apache.org/jira/browse/STORM-404" title="Worker on one machine crashes due to a failure of another worker on another machine" class="issue-link" data-issue-key="STORM-404"><del>STORM-404</del></a> because I changed the reconnect logic and remove the throw Exception logic. For verify <a href="https://issues.apache.org/jira/browse/STORM-404" title="Worker on one machine crashes due to a failure of another worker on another machine" class="issue-link" data-issue-key="STORM-404"><del>STORM-404</del></a>, I killed some worker a few times and no other worker exited. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=miguno">miguno</a>:</i>
<p>Since <a href="https://issues.apache.org/jira/browse/STORM-329" title="Fix cascading Storm failure by improving reconnection strategy and buffering messages" class="issue-link" data-issue-key="STORM-329"><del>STORM-329</del></a> apparently addresses the issue in this ticket I'll close it.  If there is evidence to the contrary in the future we can reopen this ticket.</p>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-450">STORM-450</a>]</i>
