### ISSUE TITLE
[STORM-434] Supervisor dies with "[ERROR] Error when processing even"

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4276]
<p>I have a one topology running on my production cluster. This topology has run for some weeks without fails, but few days ago my supervisor died with this error:</p>

<p>tail /var/log/storm/supervisor.log<br/>
2014-07-27 23:15:26 b.s.event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.lang.RuntimeException: java.io.EOFException<br/>
    at backtype.storm.utils.Utils.deserialize(Utils.java:86) ~<span class="error">&#91;storm-core-0.9.1-incubating-mmx2.jar:0.9.1-incubating-mmx2&#93;</span><br/>
    at backtype.storm.utils.LocalState.snapshot(LocalState.java:45) ~<span class="error">&#91;storm-core-0.9.1-incubating-mmx2.jar:0.9.1-incubating-mmx2&#93;</span><br/>
    at backtype.storm.utils.LocalState.get(LocalState.java:56) ~<span class="error">&#91;storm-core-0.9.1-incubating-mmx2.jar:0.9.1-incubating-mmx2&#93;</span><br/>
    at backtype.storm.daemon.supervisor$read_worker_heartbeat.invoke(supervisor.clj:77) ~<span class="error">&#91;storm-core-0.9.1-incubating-mmx2.jar:0.9.1-incubating-mmx2&#93;</span><br/>
    at backtype.storm.daemon.supervisor$read_worker_heartbeats$iter_<em>4842</em><em>4846$fn</em>_4847.invoke(supervisor.clj:90) ~<span class="error">&#91;na:na&#93;</span><br/>
    at clojure.lang.LazySeq.sval(LazySeq.java:42) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.lang.LazySeq.seq(LazySeq.java:60) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.lang.RT.seq(RT.java:473) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.core$seq.invoke(core.clj:133) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.core$dorun.invoke(core.clj:2725) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.core$doall.invoke(core.clj:2741) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at backtype.storm.daemon.supervisor$read_worker_heartbeats.invoke(supervisor.clj:89) ~<span class="error">&#91;storm-core-0.9.1-incubating-mmx2.jar:0.9.1-incubating-mmx2&#93;</span><br/>
    at backtype.storm.daemon.supervisor$read_allocated_workers.invoke(supervisor.clj:106) ~<span class="error">&#91;storm-core-0.9.1-incubating-mmx2.jar:0.9.1-incubating-mmx2&#93;</span><br/>
    at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:209) ~<span class="error">&#91;storm-core-0.9.1-incubating-mmx2.jar:0.9.1-incubating-mmx2&#93;</span><br/>
    at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.core$apply.invoke(core.clj:603) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.core$partial$fn__4070.doInvoke(core.clj:2343) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at clojure.lang.RestFn.invoke(RestFn.java:397) ~<span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at backtype.storm.event$event_manager$fn__2593.invoke(event.clj:39) ~<span class="error">&#91;na:na&#93;</span><br/>
    at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.4.0.jar:na&#93;</span><br/>
    at java.lang.Thread.run(Unknown Source) <span class="error">&#91;na:1.7.0_03&#93;</span><br/>
Caused by: java.io.EOFException: null<br/>
    at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source) ~<span class="error">&#91;na:1.7.0_03&#93;</span><br/>
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source) ~<span class="error">&#91;na:1.7.0_03&#93;</span><br/>
    at java.io.ObjectInputStream.readStreamHeader(Unknown Source) ~<span class="error">&#91;na:1.7.0_03&#93;</span><br/>
    at java.io.ObjectInputStream.<init>(Unknown Source) ~<span class="error">&#91;na:1.7.0_03&#93;</span><br/>
    at backtype.storm.utils.Utils.deserialize(Utils.java:81) ~<span class="error">&#91;storm-core-0.9.1-incubating-mmx2.jar:0.9.1-incubating-mmx2&#93;</span><br/>
    ... 21 common frames omitted<br/>
2014-07-27 23:15:26 b.s.util <span class="error">&#91;INFO&#93;</span> Halting process: ("Error when processing an event")</p>

<p>He tried wake up but I died with the same error all time. </p>

<p>I have fixed the problem when I delete my temporally storm directory "/tmp/storm" But the next day, I found the same problem again. I deleted the directory again and now the topology runs fine but I think the error "<span class="error">&#91;ERROR&#93;</span> Error when processing even" isn't normal and I have decided report it.</p>

---
<details><summary><i>Originally reported by <a title="Andres Gomez Ferrer" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agomez">agomez</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-434" target="_blank">Supervisor dies with "[ERROR] Error when processing even"</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2014-10-21T20:38:26+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>This is a duplicate of <a href="https://issues.apache.org/jira/browse/STORM-307" title="After host crash, supervisor is unable to restart itself" class="issue-link" data-issue-key="STORM-307"><del>STORM-307</del></a></p>
