### ISSUE TITLE
[STORM-439] UI unable to view topologies with percent encoded values in id

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4281]
<p>We recently upgraded to 0.9.2 from 0.8.2 or so. One of our topologies had a percent encoded value in the id 'destination%F5backfill' (or interpreted 'destination_backfill'). The UI is unable to view this topology giving us the error,</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">NotAliveException(msg:destination_backfill-2-1407261676)
at backtype.storm.generated.Nimbus$getTopologyInfo_result.read(Nimbus.java:11347)
	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78)
	at backtype.storm.generated.Nimbus$Client.recv_getTopologyInfo(Nimbus.java:491)
	at backtype.storm.generated.Nimbus$Client.getTopologyInfo(Nimbus.java:478)
	at backtype.storm.ui.core$topology_page.invoke(core.clj:587)
	at backtype.storm.ui.core$fn__8229.invoke(core.clj:796)
	at compojure.core$make_route$fn__3365.invoke(core.clj:93)
	at compojure.core$if_route$fn__3353.invoke(core.clj:39)
	at compojure.core$if_method$fn__3346.invoke(core.clj:24)
	at compojure.core$routing$fn__3371.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2443)
	at compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:619)
	at compojure.core$routes$fn__3375.invoke(core.clj:111)
	at ring.middleware.reload$wrap_reload$fn__7540.invoke(reload.clj:14)
	at backtype.storm.ui.core$catch_errors$fn__8268.invoke(core.clj:858)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__4029.invoke(keyword_params.clj:27)
	at ring.middleware.nested_params$wrap_nested_params$fn__4068.invoke(nested_params.clj:65)
	at ring.middleware.params$wrap_params$fn__4001.invoke(params.clj:55)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__4096.invoke(multipart_params.clj:103)
	at ring.middleware.flash$wrap_flash$fn__4277.invoke(flash.clj:14)
	at ring.middleware.session$wrap_session$fn__4266.invoke(session.clj:43)
	at ring.middleware.cookies$wrap_cookies$fn__4197.invoke(cookies.clj:160)
	at ring.adapter.jetty$proxy_handler$fn__7179.invoke(jetty.clj:16)
	at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
</pre>
</div></div>

<p>So it seems the UI is translating the percent encoded value which causes this issue. We shouldn't be putting these values in our topologies id in the first place but thought I would log this to see if you wanted to try to limit what characters are allowed in a topology id.</p>

---
<details><summary><i>Originally reported by <a title="Bryan Baugher" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bbaugher">bbaugher</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-439" target="_blank">UI unable to view topologies with percent encoded values in id</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Parth Brahmbhatt" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-10-07T20:28:10+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bbaugher" class="user-hover" rel="bbaugher">Bryan Baugher</a> are you able to see the above topology name "destination_backfill" in UI main page(/index.html) as part of topology summary section. NotAliveException thrown if it can't find the topology name for a given topology id .</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bbaugher">bbaugher</a>:</i>
<p>Yes I see the topology as part of the main page but its id is 'destination%F5backfill'. Following the link gives me that error because it changes the id.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bbaugher" class="user-hover" rel="bbaugher">Bryan Baugher</a> Thanks.  I am able to reproduce this. We should encode these at the nimbus level. I'll send a patch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>:</i>
<p>1) For me, the string "destination%5Fbackfill" breaks on master now because the back-end is looking for the decoded '_'.</p>

<p>2) Interestingly, the string "destination%F5backfill" breaks on master, but not because the encoding did not happen; it breaks on the client side because %F5 (not %5F as perhaps you meant) does not actually decode.  The error comes from purl.js, where it tries to parse the URI to get the topology ID, but the string is not able to parse the %F5.</p>

<p>You can see it happen when you call decodeURI('%F5').  When you decodeURI('%5F'), you just get the underscore.</p>

<p>It seems we 1) are decoding when we shouldn't and 2) neglecting to encode when we should.</p>

<p>I agree that using either string in a topology name are valid use cases.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>:</i>
<p>For me the destination_backfill works just fine. </p>

<p>As Derek pointed out destination%5Fbackfill fails, but that is not really a nimbus issue. The client is sending a get request with already decoded url so client sends denstination_backfill which is what master looks for and fails. The decoding happens as part of topology.html which tries to construct a new url by decoding the windows own url using purl.js</p>

<p>destination%F5backfill fails because purl.js is trying to decode a non encoded string. </p>

<p>Even if we encode the url on server side , purl.js decodes it twice once during the data: phase and then during the param: extraction phase. So for a string like Even if we encode the url on server side , purl.js decodes it twice so destination%5Fbackfill is encoded to destination%255Fbackfill on server side. This gets decoded twice on client side converting to original destination%5Fbackfill in the first data phase and then to destination_backfill which is the string sent to nimbus.</p>

<p>We either need to fix purl.js library or move to ajax.url. I haven't yet had success with ajax.url but not sure what the root cause is in that library.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>:</i>
<p>I have opened up an issue <a href="https://github.com/allmarkedup/purl/issues/86" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/allmarkedup/purl/issues/86</a> for fixing the purl.js bug in the purl.js repo.  </p>

<p>In the mean time I have started using an alternative library, jquery's url plugin <a href="http://plugins.jquery.com/url/" class="external-link" target="_blank" rel="nofollow noopener">http://plugins.jquery.com/url/</a>.</p>

<p>I found a bug on the server side code due to which we were double decoding the url params. Once during clout.core's CompiledRoute method and then in our ui/core.clj in all the Get and Post methods. This bug again results in the same effect as the bug in purl.js. I have removed the decoding from core.clj. Please let me know if you want me to open a separate issue for the bug.</p>

<p>As we are using mustache templates with anchor tags there is no way to encode topologyids on client side without either moving away from mustache or replacing all anchor tags with some jquery onclick binding. If we just send the encoded id's back to client then both, the anchor tag and the user's display text, appears encoded. To overcome this I had to update the response on the server side to include both the encoded and normal ids. </p>

<p>I have tested the ui locally with topology name = destination%@#$^*-_=+backfill. I will send a pull request shortly. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Parth-Brahmbhatt opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/242" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/242</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-439" title="UI unable to view topologies with percent encoded values in id" class="issue-link" data-issue-key="STORM-439"><del>STORM-439</del></a>: Replace purl.js with jquery url plugin to support special cha...</p>

<p>    ...racters in topology names.</p>

<p>    BugFix: Remove double decoding from the ui server, currently the decoding happens as part of clout.core.clj and ui.core.clj. Removed the decoding from ui.core.clj.<br/>
    Encode all url components on server side. Added the encodedId as response param to ensure the url from client side uses encoded component but the user still sees unencoded value.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/Parth-Brahmbhatt/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/Parth-Brahmbhatt/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-439" title="UI unable to view topologies with percent encoded values in id" class="issue-link" data-issue-key="STORM-439"><del>STORM-439</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/242.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/242.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #242</p>

<hr />
<p>commit c0eec64c74a97ff8a1ba28488a5c2775f4f81bfd<br/>
Author: Parth Brahmbhatt <brahmbhatt.parth@gmail.com><br/>
Date:   2014-08-26T04:12:50Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-439" title="UI unable to view topologies with percent encoded values in id" class="issue-link" data-issue-key="STORM-439"><del>STORM-439</del></a>: Replace purl.js with jquery url plugin to support special characters in topology names.<br/>
    BugFix: Remove double decoding from the ui server, currently the decoding happens as part of clout.core.clj and ui.core.clj. Removed the decoding from ui.core.clj.<br/>
    Encode all url components on server side. Added the encodedId as response param to ensure the url from client side uses encoded component but the user still sees unencoded value.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/242#discussion_r16714479" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/242#discussion_r16714479</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/ui/core.clj &#8212;<br/>
    @@ -424,7 +424,7 @@<br/>
      (if bolt-summs<br/>
(mapfn bolt-summs)<br/>
(mapfn spout-summs)))</p>
<ul class="alternate" type="square">
	<li>:link (url-format "/component.html?id=%s&topology_id=%s" id storm-id)<br/>
    +:link (url-format "/component.html?id=%s&topology_id=%s" (url-encode id) (url-encode storm-id))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Why do we need to double encode the id and storm-id?  url-format already encodes them once.</p>

<p>    ```<br/>
    (defn url-format <span class="error">&#91;fmt & args&#93;</span><br/>
      (String/format fmt<br/>
(to-array (map #(url-encode (str %)) args))))<br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/242#issuecomment-53427732" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/242#issuecomment-53427732</a></p>

<p>    OK so mustache will do HTML escaping with the ```<tt>var</tt>``` like syntax, but it will not do URL encoding. So we have added in URL encoded ids to the result of the REST APIs to allow us to not bother with doing the URL encoding in the browser.  That seems OK I guess.  But why are we not url decoding the url parameters in the REST API any more?  Is it because the ring framework already decodes them for us?  And I am really confused why in the visualization-data function we need to double url encode the ids in the link? From the look of it, it is because we take those parameters and place them in a new URL for the rest call.  I would much rather have the browser encode them again when making them a part of the URL.  encodeURIComponent should be what we want and is a standard part of javascript.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/242#issuecomment-53428003" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/242#issuecomment-53428003</a></p>

<p>    Oh and if we don't need/use purl any more we should remove it and the license section for it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/242#discussion_r16726994" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/242#discussion_r16726994</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/ui/core.clj &#8212;<br/>
    @@ -424,7 +424,7 @@<br/>
      (if bolt-summs<br/>
(mapfn bolt-summs)<br/>
(mapfn spout-summs)))</p>
<ul class="alternate" type="square">
	<li>:link (url-format "/component.html?id=%s&topology_id=%s" id storm-id)<br/>
    +:link (url-format "/component.html?id=%s&topology_id=%s" (url-encode id) (url-encode storm-id))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    I missed this , I just blindly went through all the urls and encoded the components. Not sure why in my testing I was not able to catch this though. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/242#issuecomment-53454343" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/242#issuecomment-53454343</a></p>

<p>    Our mustache templates have anchor tags where we just do the following </p>

<p>    <a href="/topology.html?id=<tt>id</tt>"><tt>name</tt></a></p>

<p>    As you already mentioned mustache does the escaping but not encoding. So the above results in unencoded url which results in the bug that we are trying to fix.  I have tried reading through mustache docs and googling around to see if there is any way to invoke javascript functions like encodeURIComponent as part of mustache template and I haven't had much luck. The only suggestion was to send lambda constructs as response from server side which is no different then just sending encoded components. There are 3 other alternatives that I could think of:</p>

<p>    1) Encode and server side, which is what we are doing right now.<br/>
    2)  Process the json on browser side before rendering using mustache. Pretty much the same thing as above but the client will have to loop through json response twice once to encode and once to render using mustache.<br/>
    3) Use a more powerful library than mustache or replace all anchor tags with some div's with onclick being handled by jquery. </p>

<p>    The easiest of 3 was the 1st option so I went with it. That said, I am not sure what are the general best practices so I don't mind changing it to option 2 or 3 or any other idea that someone else can propose.</p>

<p>    The URL decoding happens as part of <a href="https://github.com/weavejester/clout/blob/master/src/clout/core.clj#L96" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/weavejester/clout/blob/master/src/clout/core.clj#L96</a><br/>
    So the decoding on our side results in a bug. </p>

<p>    test%5Ftest -> browser sends encoded test%255Ftest -> clout decodes to test%5Ftest -> our code decodes again and tries to look for test_test topology which is not alive. </p>

<p>    I can remove the purl.js but I am not sure which library is actually better so if anyone has any comparison points please let me know. I am planning to fix the purl.js bug so if the change request gets approved we can always revert back to it. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/242#issuecomment-56726151" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/242#issuecomment-56726151</a></p>

<p>    I am really sorry that it took me so long to look at this again since you made the last commit.  It looks great. But now it needs to be upmerged because some of the templates were reformatted.  Again looks great +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/242#issuecomment-56735833" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/242#issuecomment-56735833</a></p>

<p>    upmerged.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/242#issuecomment-56985857" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/242#issuecomment-56985857</a></p>

<p>    +1 looks great.  Give a few more days for others to comment on the upmerge.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/242#issuecomment-57407000" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/242#issuecomment-57407000</a></p>

<p>    +1 looks good. Tested this on a cluster.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/242#issuecomment-57415388" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/242#issuecomment-57415388</a></p>

<p>    +1 If no one minds, I'd like to merge this one so I can verify the licensing is correct (no code changed).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/242" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/242</a></p>
