### ISSUE TITLE
[STORM-448] Apache Storm Nimbus getting dead

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4290]
<p>Apache storm nimbus getting dead due to serialVersionUID mismatch issue.</p>

<p>Caused by: java.io.InvalidClassException: backtype.storm.daemon.common.SupervisorInfo; local class incompatible: stream classdesc serialVersionUID = -292327522856879<br/>
2176, local class serialVersionUID = -6599159272110777305<br/>
at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:617)<br/>
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622)<br/>
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)<br/>
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)<br/>
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)<br/>
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)<br/>
at backtype.storm.utils.Utils.deserialize(Utils.java:55)<br/>
... 29 more</p>

---
<details><summary><i>Originally reported by <a title="PaVan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pDonS">pDonS</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-448" target="_blank">Apache Storm Nimbus getting dead</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2014-08-11T16:37:42+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pDonS" class="user-hover" rel="pDonS">PaVan</a> Did you try cleaning up storm-local and zookeeper data.dir.  This case happens when you have existing storm cluster and you upgrading it to a newer version. <br/>
bring down your storm cluster and zookeeper delete storm-local dir contents and restart the zookeeper and storm cluster.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pdons">pdons</a>:</i>
<p>HI Sriharsha ,</p>

<p>It works fine when i do the clean up manually .Can you please suggest the right version or compatible version of Apache Storm and Apache Zookeeper. Currently i am running on Apache Storm 0.8.1 and Apache Zookeeper 3.4.6 .  Can you suggest me how should it be fixed on code level while writing spout or bolt  ? . I expect Storm to clean up on its own but not working .  <br/>
Thanks a lot  in advance SriHarsha.. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>There are a few cases where an upgrade changes internal classes that storm uses, and are serialized out into zookeeper, or onto the local file system.  In general if you kill all of the running topologies before upgrading you will not run into this situation.  There is nothing that your Bolt/Spout code can do to work around this issue.  It is completely internal to storm.  Ideally in the future we would switch to a different serialization system like Thrift, Protocol Buffers, or some kryo schemes, that would allow us to maintain binary compatibility of these data structures between upgrades.</p>

<p><a href="https://issues.apache.org/jira/browse/STORM-170" title="serialize all storm zk state as EDN" class="issue-link" data-issue-key="STORM-170"><del>STORM-170</del></a>  <a href="https://issues.apache.org/jira/browse/STORM-79" title="Don&#39;t use Java serialization for storing state on disk or in Zookeeper" class="issue-link" data-issue-key="STORM-79"><del>STORM-79</del></a> and <a href="https://issues.apache.org/jira/browse/STORM-432" title="Enable version-agnostic serialization of storm&#39;s metadata" class="issue-link" data-issue-key="STORM-432"><del>STORM-432</del></a> all seem to want to cover this same thing in some way. I am going to close this as a dupe of those, but if you disagree feel free to reopen this issue.</p>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-170">STORM-170</a>]</i>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-432">STORM-432</a>]</i>
