### ISSUE TITLE
[STORM-456] Storm UI: cannot navigate to topology page when name contains spaces

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4298]
<p>1. Create a Java class that makes your topology<br/>
2. Submit the topology with a name that contains spaces: StormSubmitter.submitTopology("I Dont Want to Use Underscores", conf, builder.createTopology());<br/>
3. Submit the jar to storm: storm jar yourUberJar your.topology.class.name<br/>
4. Open Storm UI in your browser<br/>
5. Click the link for the submitted topology under "Topology Summary"</p>

<p>Result: Page refreshes but does not show the topology page</p>

<p>Expected Result: clicking the link should take you to the topology screen like it does for topologies whose names do not contain spaces OR an error should be returned if a user submits a topology whose names contains spaces and this is not supported.</p>

---
<details><summary><i>Originally reported by <a title="Steven Magana-Zook" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevenmz">stevenmz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-456" target="_blank">Storm UI: cannot navigate to topology page when name contains spaces</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Trivial
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-06-01T20:17:04+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user NareshKosgi opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/303" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/303</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-456" title="Storm UI: cannot navigate to topology page when name contains spaces" class="issue-link" data-issue-key="STORM-456"><del>STORM-456</del></a>:Storm UI cannot navigate to topology page when name contains spaces</p>

<p>    1. The issue is due to space being replaced by "+" by the framework<br/>
    2. In the routes function for core.clj I added a check for search and replace for "+" for the id being passed<br/>
    3. I tested by changing the word count example and is working as I can click on the "word count" topology and get to the next page but the next page errors out with the following exception:<br/>
    NotAliveException(msg:word+count-1-1414427540)<br/>
    	at backtype.storm.generated.Nimbus$getTopologyInfo_result.read(Nimbus.java:11347)<br/>
    	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78)<br/>
    	at backtype.storm.generated.Nimbus$Client.recv_getTopologyInfo(Nimbus.java:491)<br/>
    	at backtype.storm.generated.Nimbus$Client.getTopologyInfo(Nimbus.java:478)<br/>
    	at backtype.storm.ui.core$topology_page.invoke(core.clj:628)<br/>
    	at backtype.storm.ui.core$fn__8177.invoke(core.clj:853)<br/>
    	at compojure.core$make_route$fn__6356.invoke(core.clj:93)<br/>
    	at compojure.core$if_route$fn__6344.invoke(core.clj:39)<br/>
    	at compojure.core$if_method$fn__6337.invoke(core.clj:24)<br/>
    	at compojure.core$routing$fn__6362.invoke(core.clj:106)<br/>
    	at clojure.core$some.invoke(core.clj:2443)<br/>
    	at compojure.core$routing.doInvoke(core.clj:106)<br/>
    	at clojure.lang.RestFn.applyTo(RestFn.java:139)<br/>
    	at clojure.core$apply.invoke(core.clj:619)<br/>
    	at compojure.core$routes$fn__6366.invoke(core.clj:111)<br/>
    	at ring.middleware.reload$wrap_reload$fn__6391.invoke(reload.clj:14)<br/>
    	at backtype.storm.ui.core$catch_errors$fn__8216.invoke(core.clj:909)<br/>
    	at ring.middleware.keyword_params$wrap_keyword_params$fn__7033.invoke(keyword_params.clj:27)<br/>
    	at ring.middleware.nested_params$wrap_nested_params$fn__7072.invoke(nested_params.clj:65)<br/>
    	at ring.middleware.params$wrap_params$fn__7005.invoke(params.clj:55)<br/>
    	at ring.middleware.multipart_params$wrap_multipart_params$fn__7100.invoke(multipart_params.clj:103)<br/>
    	at ring.middleware.flash$wrap_flash$fn__7281.invoke(flash.clj:14)<br/>
    	at ring.middleware.session$wrap_session$fn__7270.invoke(session.clj:43)<br/>
    	at ring.middleware.cookies$wrap_cookies$fn__7201.invoke(cookies.clj:160)<br/>
    	at ring.adapter.jetty$proxy_handler$fn__7481.invoke(jetty.clj:16)<br/>
    	at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)<br/>
    	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)<br/>
    	at org.mortbay.jetty.Server.handle(Server.java:326)<br/>
    	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)<br/>
    	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)<br/>
    	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)<br/>
    	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)<br/>
    	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)<br/>
    	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)<br/>
    	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)</p>

<p>    I'm guessing I need to do a search and replace for the m as well and not just id?  I know this pull request is not complete, I wanted to create a pull request and make sure I'm taking the correct approach to resolving this ticket.</p>

<p>    P.S <br/>
    I changed word count topology just for testing purpose, I will revert it back once I complete the testing.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/NareshKosgi/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/NareshKosgi/incubator-storm</a> storm-456</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/303.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/303.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #303</p>

<hr />
<p>commit e72a94c1de7dd4fa7744c9dd914439bcd59a634b<br/>
Author: Naresh Kosgi <nareshkosgi@gmail.com><br/>
Date:   2014-10-18T02:57:52Z</p>

<p>    routes look for the plus sign</p>

<p>commit ccbfad1fec3f99531a8160dae51419abc3e5bb87<br/>
Author: Naresh Kosgi <nareshkosgi@gmail.com><br/>
Date:   2014-10-27T16:12:18Z</p>

<p>    using word count to test</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/303#issuecomment-60635672" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/303#issuecomment-60635672</a></p>

<p>    search and replace is not a good solution, this seems to be another encoding decoding issue. I tested locally and from the initial investigation it feels like we have out of sync encoding and decoding schemes. </p>

<p>    word count -> encoded by -> <a href="https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/util.clj#L808" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/util.clj#L808</a> -> results in word+count.</p>

<p>    however the ring gives us decoded id at <a href="https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/ui/core.clj#L852" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/ui/core.clj#L852</a> which does not transalte "word+count" to "word count". </p>

<p>    We need to ensure our encoding and decoding is done with the same scheme.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user clockfly commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/303#issuecomment-61631456" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/303#issuecomment-61631456</a></p>

<p>    @NareshKosgi,</p>

<p>    Have you considered other special character that may used as topology name?<br/>
    Like the table, #, &, (, and etc..</p>

<p>    Is it possble that this fix only works for "space", but fails for "table"?</p>

<p>    Another approach is to add strict name checking when submitting topology. This may make life easier?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/303#issuecomment-61668317" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/303#issuecomment-61668317</a></p>

<p>    @NareshKosgi  I am -1 on current PR. Please look at the @Parth-Brahmbhatt  suggested approach.<br/>
    Also lets not modify the existing examples to test it. It will be great if you can add unit tests to check if the different topology names are valid or not. Thanks.</p>

<p>    @clockfly special characters seems to have no issue. Please check the attached image. I was able to submit ./bin/storm jar examples/storm-starter/storm-starter-topologies-0.9.3-rc2-SNAPSHOT.jar storm.starter.WordCountTopology "word#&count)(" <br/>
    !<span class="error">&#91;image&#93;</span>(<a href="https://cloud.githubusercontent.com/assets/38649/4903389/0a1d1cfa-6440-11e4-972b-1618dc1d1193.png" class="external-link" target="_blank" rel="nofollow noopener">https://cloud.githubusercontent.com/assets/38649/4903389/0a1d1cfa-6440-11e4-972b-1618dc1d1193.png</a>)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user NareshKosgi closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/303" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/303</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user NareshKosgi reopened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/303" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/303</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-456" title="Storm UI: cannot navigate to topology page when name contains spaces" class="issue-link" data-issue-key="STORM-456"><del>STORM-456</del></a>:Storm UI cannot navigate to topology page when name contains spaces</p>

<p>    1. The issue is due to space being replaced by "+" by the framework<br/>
    2. In the routes function for core.clj I added a check for search and replace for "+" for the id being passed<br/>
    3. I tested by changing the word count example and is working as I can click on the "word count" topology and get to the next page but the next page errors out with the following exception:<br/>
    NotAliveException(msg:word+count-1-1414427540)<br/>
    	at backtype.storm.generated.Nimbus$getTopologyInfo_result.read(Nimbus.java:11347)<br/>
    	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78)<br/>
    	at backtype.storm.generated.Nimbus$Client.recv_getTopologyInfo(Nimbus.java:491)<br/>
    	at backtype.storm.generated.Nimbus$Client.getTopologyInfo(Nimbus.java:478)<br/>
    	at backtype.storm.ui.core$topology_page.invoke(core.clj:628)<br/>
    	at backtype.storm.ui.core$fn__8177.invoke(core.clj:853)<br/>
    	at compojure.core$make_route$fn__6356.invoke(core.clj:93)<br/>
    	at compojure.core$if_route$fn__6344.invoke(core.clj:39)<br/>
    	at compojure.core$if_method$fn__6337.invoke(core.clj:24)<br/>
    	at compojure.core$routing$fn__6362.invoke(core.clj:106)<br/>
    	at clojure.core$some.invoke(core.clj:2443)<br/>
    	at compojure.core$routing.doInvoke(core.clj:106)<br/>
    	at clojure.lang.RestFn.applyTo(RestFn.java:139)<br/>
    	at clojure.core$apply.invoke(core.clj:619)<br/>
    	at compojure.core$routes$fn__6366.invoke(core.clj:111)<br/>
    	at ring.middleware.reload$wrap_reload$fn__6391.invoke(reload.clj:14)<br/>
    	at backtype.storm.ui.core$catch_errors$fn__8216.invoke(core.clj:909)<br/>
    	at ring.middleware.keyword_params$wrap_keyword_params$fn__7033.invoke(keyword_params.clj:27)<br/>
    	at ring.middleware.nested_params$wrap_nested_params$fn__7072.invoke(nested_params.clj:65)<br/>
    	at ring.middleware.params$wrap_params$fn__7005.invoke(params.clj:55)<br/>
    	at ring.middleware.multipart_params$wrap_multipart_params$fn__7100.invoke(multipart_params.clj:103)<br/>
    	at ring.middleware.flash$wrap_flash$fn__7281.invoke(flash.clj:14)<br/>
    	at ring.middleware.session$wrap_session$fn__7270.invoke(session.clj:43)<br/>
    	at ring.middleware.cookies$wrap_cookies$fn__7201.invoke(cookies.clj:160)<br/>
    	at ring.adapter.jetty$proxy_handler$fn__7481.invoke(jetty.clj:16)<br/>
    	at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)<br/>
    	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)<br/>
    	at org.mortbay.jetty.Server.handle(Server.java:326)<br/>
    	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)<br/>
    	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)<br/>
    	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)<br/>
    	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)<br/>
    	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)<br/>
    	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)<br/>
    	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)</p>

<p>    I'm guessing I need to do a search and replace for the m as well and not just id?  I know this pull request is not complete, I wanted to create a pull request and make sure I'm taking the correct approach to resolving this ticket.</p>

<p>    P.S <br/>
    I changed word count topology just for testing purpose, I will revert it back once I complete the testing.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/NareshKosgi/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/NareshKosgi/incubator-storm</a> storm-456</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/303.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/303.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #303</p>

<hr />
<p>commit fe5f41aa8332700d3f98422cb7d986fc47289bcd<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-05-21T16:03:11Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-216" title="Secure Multi-tenant Storm" class="issue-link" data-issue-key="STORM-216"><del>STORM-216</del></a>: Added Authentication and Authorization.</p>

<p>    This is an upmerged version of <a href="https://github.com/yahoo/incubator-storm/tree/security" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/yahoo/incubator-storm/tree/security</a></p>

<p>commit ce6e5d26384d7f5d831b35e4eff126fe214981d1<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2014-05-22T18:34:23Z</p>

<p>    rename test for consistent capitalization</p>

<p>commit 698bb9c9788b82d4127d861fb3ecf06a06b683c2<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-05-28T13:45:22Z</p>

<p>    Merge branch 'master' into security</p>

<p>commit 6592b8209c49a98db15b3d6d228f488aa6c2e623<br/>
Author: Kishor Patil <patik523@yahoo.com><br/>
Date:   2014-06-09T15:42:39Z</p>

<p>    Add missing ACLs to error znodes and remove auto vivification of error znodes</p>

<p>commit cf2e8b7ee06b455a90bd4b3bfd53facef1369612<br/>
Author: Sriharsha Chintalapani <mail@harsha.io><br/>
Date:   2014-06-10T22:01:33Z</p>

<p>    Storm 344. (Security) nimbus renew-credentials not calling ICredentialsRenewer.renew</p>

<p>commit 0a98bee214b46ed20b566a9b49c3eca2895f9fd5<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-11T16:07:59Z</p>

<p>    Merge branch 'master' into security-upmerge</p>

<p>    Conflicts:<br/>
    	.gitignore<br/>
    	storm-core/src/clj/backtype/storm/daemon/drpc.clj<br/>
    	storm-core/src/clj/backtype/storm/daemon/executor.clj<br/>
    	storm-core/src/clj/backtype/storm/daemon/logviewer.clj<br/>
    	storm-core/src/clj/backtype/storm/daemon/worker.clj<br/>
    	storm-core/src/clj/backtype/storm/timer.clj<br/>
    	storm-core/src/clj/backtype/storm/ui/core.clj<br/>
    	storm-core/src/clj/backtype/storm/ui/helpers.clj<br/>
    	storm-core/src/clj/backtype/storm/util.clj<br/>
    	storm-core/src/jvm/backtype/storm/Config.java<br/>
    	storm-core/src/jvm/backtype/storm/utils/Utils.java</p>

<p>commit 118b9221b492ed8b91e6633c3cfb748bc1b82790<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-11T16:10:04Z</p>

<p>    Merge branch 'master' into security</p>

<p>commit 2131a0aeb9074b2c83a09d7515ff8e8ae86f6eaf<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-12T15:58:13Z</p>

<p>    Added back in the user to the web ui.</p>

<p>commit 41615b3c4b174077ac1c729af4aef32e5b79d3c5<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-12T15:59:46Z</p>

<p>    Merge branch 'master' into security</p>

<p>commit bc91ed88d77e392f38c406d143e7ac37bc634564<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-12T16:01:35Z</p>

<p>    Added license to UI template.</p>

<p>commit a762f1c5f99a7a9e77038399f0f14ae03b1414c7<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-12T17:48:51Z</p>

<p>    Merge branch '<a href="https://issues.apache.org/jira/browse/STORM-344" title="(Security) nimbus renew-credentials not calling ICredentialsRenewer.renew" class="issue-link" data-issue-key="STORM-344"><del>STORM-344</del></a>' of <a href="https://github.com/harshach/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/harshach/incubator-storm</a> into <a href="https://issues.apache.org/jira/browse/STORM-344" title="(Security) nimbus renew-credentials not calling ICredentialsRenewer.renew" class="issue-link" data-issue-key="STORM-344"><del>STORM-344</del></a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-344" title="(Security) nimbus renew-credentials not calling ICredentialsRenewer.renew" class="issue-link" data-issue-key="STORM-344"><del>STORM-344</del></a>: (Security) nimbus renew-credentials not calling ICredentialsRenewer.renew</p>

<p>commit 92e3a5742374a3a7c3aae20cbeda32ce7b033526<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-12T21:09:57Z</p>

<p>    Merge branch 'master' into security-upmerge</p>

<p>    Conflicts:<br/>
    	storm-core/src/clj/backtype/storm/LocalCluster.clj<br/>
    	storm-core/src/clj/backtype/storm/cluster.clj<br/>
    	storm-core/src/clj/backtype/storm/config.clj<br/>
    	storm-core/src/clj/backtype/storm/daemon/drpc.clj<br/>
    	storm-core/src/clj/backtype/storm/testing.clj<br/>
    	storm-core/src/clj/backtype/storm/testing4j.clj<br/>
    	storm-core/src/clj/backtype/storm/thrift.clj<br/>
    	storm-core/src/clj/backtype/storm/ui/core.clj<br/>
    	storm-core/src/clj/backtype/storm/util.clj<br/>
    	storm-core/src/clj/backtype/storm/zookeeper.clj</p>

<p>commit ab7784e49d251ca4da967c6ec6bc340cc7f940aa<br/>
Author: Kishor Patil <patik523@yahoo.com><br/>
Date:   2014-06-17T15:19:00Z</p>

<p>    Force free a slot in bad-state</p>

<p>commit d1ba4fc4acdadd5e5e138395bdc5892dfdb88bff<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2014-06-17T15:56:51Z</p>

<p>    Do not clean up user file when rmr is unsuccessful</p>

<p>commit 87cdbf5fdf5bfb49b983604542283f05123d0d51<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-17T18:32:18Z</p>

<p>    Merge branch '<a href="https://issues.apache.org/jira/browse/STORM-357" title="[security] Supervisors can fail to clean up worker files properly" class="issue-link" data-issue-key="STORM-357"><del>STORM-357</del></a>' of <a href="https://github.com/d2r/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/d2r/incubator-storm</a> into <a href="https://issues.apache.org/jira/browse/STORM-357" title="[security] Supervisors can fail to clean up worker files properly" class="issue-link" data-issue-key="STORM-357"><del>STORM-357</del></a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-357" title="[security] Supervisors can fail to clean up worker files properly" class="issue-link" data-issue-key="STORM-357"><del>STORM-357</del></a>: Cleans workers-users file only when rmr is successful</p>

<p>commit ea946d04dcb6df8e65dbf16500a361eaaba13432<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-06-18T23:58:33Z</p>

<p>    Show node details on errors for <a href="https://issues.apache.org/jira/browse/STORM-360" title="Add woker-id/host info/port info to the error for easy tracking on UI" class="issue-link" data-issue-key="STORM-360"><del>STORM-360</del></a> on security</p>

<p>commit 79089ad0da80e38eb36b7ea91be8b43795dc4efb<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-19T21:04:02Z</p>

<p>    Merge tag 'v0.9.2-incubating' into security</p>

<p>    <span class="error">&#91;maven-release-plugin&#93;</span>  copy for tag v0.9.2-incubating</p>

<p>    Conflicts:<br/>
    	storm-core/pom.xml</p>

<p>commit f20df7d52d52abc9bc03a0cf45388241927cff5a<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-06-20T20:35:16Z</p>

<p>    Fixing coding style and component template</p>

<p>commit c545b9d638067c0ae4528e16f14e67c56e0dd47e<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-06-20T23:01:00Z</p>

<p>    Fix nimbus use of doto</p>

<p>commit d7c1d1d0a909079a370ed35aaac91668eef33a22<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-23T14:31:41Z</p>

<p>    Merge branch 'node-on-error-security' of <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> into <a href="https://issues.apache.org/jira/browse/STORM-360" title="Add woker-id/host info/port info to the error for easy tracking on UI" class="issue-link" data-issue-key="STORM-360"><del>STORM-360</del></a>-security</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-360" title="Add woker-id/host info/port info to the error for easy tracking on UI" class="issue-link" data-issue-key="STORM-360"><del>STORM-360</del></a>: Add node details for Error Topology and Component pages on security</p>

<p>commit 65aee65af54dd29434af8f5ee403233b597561b6<br/>
Author: Robert (Bobby) Evans <bobby@apache.org><br/>
Date:   2014-06-23T15:18:38Z</p>

<p>    Merge branch 'master' into security</p>

<p>    Conflicts:<br/>
    	storm-core/src/clj/backtype/storm/cluster.clj<br/>
    	storm-core/src/clj/backtype/storm/ui/core.clj<br/>
    	storm-core/test/clj/backtype/storm/cluster_test.clj</p>

<p>commit 357fd09dff8eec1f224d7f00f5344931ec2b64df<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-06-23T16:13:34Z</p>

<p>    Add color span to most recent error and fix ui templates for security.</p>

<p>commit 28c168fd7d0272f88d586f6f572eab937b874f22<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-06-24T19:12:56Z</p>

<p>    Add check for empty table before sorting on security</p>

<p>commit 8325186b731259c17d4b06aa2c288ffc4f6dc59b<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-06-25T15:32:17Z</p>

<p>    revert tablesorter fix</p>

<p>commit 7bb8ec6d8068fe2eeec65085bfa0140aca0fb0a9<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-06-26T00:13:03Z</p>

<p>    Use javascript to color-code recent errors</p>

<p>commit f3112fa76e98038da83170513a476499dde0bb41<br/>
Author: Sriharsha Chintalapani <mail@harsha.io><br/>
Date:   2014-06-26T22:05:21Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-347" title="(Security) authentication should allow for groups not just users" class="issue-link" data-issue-key="STORM-347"><del>STORM-347</del></a>. (Security) authentication should allow for groups not just users.</p>

<p>commit 3c6930dfe4447b6077916b9f9a07b062141b5305<br/>
Author: Parth Brahmbhatt <brahmbhatt.parth@gmail.com><br/>
Date:   2014-07-07T18:36:49Z</p>

<p>    AutoHDFS for getting HDFS delegation token and auto renew.</p>

<p>commit 00e80e9a132764d4b73737d2f7a52282e5247856<br/>
Author: Parth Brahmbhatt <brahmbhatt.parth@gmail.com><br/>
Date:   2014-07-07T18:43:59Z</p>

<p>    Merge remote-tracking branch 'upstream/security' into security</p>

<p>commit e04c37356c96d9851c00542c739d053e4bf36481<br/>
Author: Parth Brahmbhatt <brahmbhatt.parth@gmail.com><br/>
Date:   2014-07-07T18:49:42Z</p>

<p>    Revert "AutoHDFS for getting HDFS delegation token and auto renew."</p>

<p>    This reverts commit 3c6930dfe4447b6077916b9f9a07b062141b5305.</p>

<p>commit ae5d0c312d170c883e9758767808e1c8d33f58c8<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2014-07-08T22:08:33Z</p>

<p>    Use TBinaryProtocol without max buffer</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/318#issuecomment-73545196" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/318#issuecomment-73545196</a></p>

<p>    @Parth-Brahmbhatt, @NareshKosgi , Does #360 sufficiently resolve <a href="https://issues.apache.org/jira/browse/STORM-456" title="Storm UI: cannot navigate to topology page when name contains spaces" class="issue-link" data-issue-key="STORM-456"><del>STORM-456</del></a>?  If so, we should close this pull request and resolve <a href="https://issues.apache.org/jira/browse/STORM-456" title="Storm UI: cannot navigate to topology page when name contains spaces" class="issue-link" data-issue-key="STORM-456"><del>STORM-456</del></a>.</p>
