### ISSUE TITLE
[STORM-466] Storm build failures due to metrics_test.clj

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4308]
<p>As reported by Rick Kilgore on mailing list<br/>
I need to make a couple modifications to KafkaSpout for our needs and I’m planning to submit back a PR to the main repo.  But I can’t build.  I’ve installed the latest git, java 7, and mvn 3 via apt-get onto Ubuntu 14.04 LTS.  Then I run:</p>

<p>git clone 'https://github.com/apache/incubator-storm' storm<br/>
cd storm<br/>
mvn clean install</p>

<p>I get lots of exceptions, but I think most are expected as part of the tests.   Below is the output at the end that I’m guessing is not good.  I’ve also tried this on a Mac running Mavericks and on an Amazon Linux installation.  I’ve tried in my usual shell setup, and with a stripped down bash setup with a minimal PATH.  The results are mostly the same, but regardless always fails in some way.  This is with what’s in master now, without any changes by me.  Here is the tail end of my output from mvn install:</p>

<p>187855 <span class="error">&#91;Thread-287&#93;</span> INFO  backtype.storm.daemon.worker - Worker 6b378fbc-cbcd-4ba4-aed8-9d8ad247eb2f for storm shell-metrics-tester-1-3 on 2e862cd2-ccaf-48ac-820e-6c5a714e9bc8:1024 has finished loading<br/>
187857 <span class="error">&#91;Thread-291-2&#93;</span> INFO  backtype.storm.task.ShellBolt - Launched subprocess with pid 16985<br/>
187858 <span class="error">&#91;Thread-291-2&#93;</span> INFO  backtype.storm.daemon.executor - Prepared bolt 2:(2)<br/>
187873 <span class="error">&#91;Thread-302&#93;</span> INFO  backtype.storm.task.ShellBolt - ShellLog pid:16985, name:2 bolt initializing<br/>
188651 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.nimbus - Shutting down master<br/>
188653 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.nimbus - Shut down master<br/>
188653 <span class="error">&#91;NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000&#93;</span> WARN  org.apache.zookeeper.server.NIOServerCnxn - caught end of stream exception<br/>
org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x14801d52e3d0001, likely client has<br/>
 closed socket<br/>
at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) <span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_65&#93;</span><br/>
188658 <span class="error">&#91;NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000&#93;</span> WARN  org.apache.zookeeper.server.NIOServerCnxn - caught end of stream exception<br/>
org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x14801d52e3d0003, likely client has<br/>
 closed socket<br/>
at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) <span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_65&#93;</span><br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.supervisor - Shutting down 2e862cd2-ccaf-48ac-820e-6c5a714e9bc8:6b378fbc-cbcd-4ba4-aed8-9d8ad247eb2f<br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.process-simulator - Killing process d2a10e11-adbd-49cd-889c-5137777fdc56<br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.worker - Shutting down worker shell-metrics-tester-1-3 2e862cd2-ccaf-48ac-820e-6c5a714e9bc8 1024<br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.worker - Shutting down receive thread<br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.messaging.loader - Shutting down receiving-thread: <span class="error">&#91;shell-metrics-tester-1-3, 1024&#93;</span><br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.messaging.loader - Waiting for receiving-thread:<span class="error">&#91;shell-metrics-tester-1-3, 1024&#93;</span> to die<br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.messaging.loader - Shutdown receiving-thread: <span class="error">&#91;shell-metrics-tester-1-3, 1024&#93;</span><br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.worker - Shut down receive thread<br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.worker - Terminating messaging context<br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.worker - Shutting down executors<br/>
188660 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.executor - Shutting down executor 2:<span class="error">&#91;2 2&#93;</span><br/>
188661 <span class="error">&#91;Thread-300-worker-receiver-thread-0&#93;</span> INFO  backtype.storm.messaging.loader - Receiving-thread:<span class="error">&#91;shell-metrics-tester-1-3, 1024&#93;</span> received shutdown notice<br/>
188661 <span class="error">&#91;Thread-291-2&#93;</span> INFO  backtype.storm.util - Async loop interrupted!<br/>
188661 [Thread-290-disruptor-executor<span class="error">&#91;2 2&#93;</span>-send-queue] INFO  backtype.storm.util - Async loop interrupted!<br/>
188662 <span class="error">&#91;NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000&#93;</span> WARN  org.apache.zookeeper.server.NIOServerCnxn - caught end of stream exception<br/>
org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x14801d52e3d0005, likely client has closed socket<br/>
at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) <span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_65&#93;</span><br/>
188663 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.executor - Shut down executor 2:<span class="error">&#91;2 2&#93;</span><br/>
188663 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.executor - Shutting down executor __acker:<span class="error">&#91;3 3&#93;</span><br/>
188673 <span class="error">&#91;Thread-293-__acker&#93;</span> INFO  backtype.storm.util - Async loop interrupted!<br/>
188674 <span class="error">&#91;Thread-302&#93;</span> ERROR backtype.storm.task.ShellBolt - Halting process: ShellBolt died.<br/>
java.lang.RuntimeException: backtype.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.<br/>
Serializer Exception:<br/>
(Unable to capture error stream)</p>

<p>at backtype.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:101) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.task.ShellBolt$1.run(ShellBolt.java:116) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_65&#93;</span><br/>
188674 <span class="error">&#91;Thread-302&#93;</span> ERROR backtype.storm.daemon.executor -<br/>
java.lang.RuntimeException: backtype.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.<br/>
Serializer Exception:<br/>
(Unable to capture error stream)</p>

<p>at backtype.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:101) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at backtype.storm.task.ShellBolt$1.run(ShellBolt.java:116) ~<span class="error">&#91;classes/:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_65&#93;</span><br/>
188677 [Thread-292-disruptor-executor<span class="error">&#91;3 3&#93;</span>-send-queue] INFO  backtype.storm.util - Async loop interrupted!<br/>
188677 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.executor - Shut down executor __acker:<span class="error">&#91;3 3&#93;</span><br/>
188678 <span class="error">&#91;main&#93;</span> INFO  backtype.storm.daemon.executor - Shutting down executor __metricsclojure.storm.metric.testing.FakeMetricConsumer:<span class="error">&#91;4 4&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Harsha" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-466" target="_blank">Storm build failures due to metrics_test.clj</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2014-08-25T16:27:09+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit" class="user-hover" rel="dagit">Derek Dagit</a>  <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xiaokang" class="user-hover" rel="xiaokang">Kang Xiao</a> This issue is caused by non-zero exit in ShellBolt.die<br/>
<a href="https://github.com/apache/incubator-storm/blob/master/storm-core/src/jvm/backtype/storm/task/ShellBolt.java#L302" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/blob/master/storm-core/src/jvm/backtype/storm/task/ShellBolt.java#L302</a><br/>
easiest fix is to make System.exit(0) although it indicates the process exited without any error. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user harshach opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/240" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/240</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-466" title="Storm build failures due to metrics_test.clj" class="issue-link" data-issue-key="STORM-466"><del>STORM-466</del></a>. Strom build failures due to metrics_test.clj.</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/harshach/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/harshach/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-466" title="Storm build failures due to metrics_test.clj" class="issue-link" data-issue-key="STORM-466"><del>STORM-466</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/240.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/240.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #240</p>

<hr />
<p>commit 6970fef0fe17998804bb87263ab765e0400a2596<br/>
Author: Sriharsha Chintalapani <mail@harsha.io><br/>
Date:   2014-08-23T21:13:24Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-466" title="Storm build failures due to metrics_test.clj" class="issue-link" data-issue-key="STORM-466"><del>STORM-466</del></a>. Strom build failures due to metrics_test.clj.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user xiaokang commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/240#issuecomment-53178864" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/240#issuecomment-53178864</a></p>

<p>    hi @harshach , this problem is related to #223 . Chould you have a look at it whether it fix this problem?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/240#issuecomment-53278146" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/240#issuecomment-53278146</a></p>

<p>    @harshach I just merged in #223.  I think we can close this pull and resolve <a href="https://issues.apache.org/jira/browse/STORM-466" title="Storm build failures due to metrics_test.clj" class="issue-link" data-issue-key="STORM-466"><del>STORM-466</del></a> as a dupe of <a href="https://issues.apache.org/jira/browse/STORM-449" title="ShellBolt can cause periodic test failures" class="issue-link" data-issue-key="STORM-449"><del>STORM-449</del></a>.  Please let me know if you don't have permissions in JIRA for that and I will grant them to you.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/240#issuecomment-53523494" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/240#issuecomment-53523494</a></p>

<p>    closing this PR as this issue is fixed in another JIRA</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/240" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/240</a></p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-449">STORM-449</a>]</i>
