### ISSUE TITLE
[STORM-477] Incorrectly set JAVA_HOME is not detected

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4319]
<p>If JAVA_HOME is incorrectly set in a user's environment when launching storm,   </p>

<p>it fails with an error message that is confusing to end users.</p>

<p>Traceback (most recent call last):<br/>
  File "/home/y/bin/storm", line 485, in <module><br/>
    main()<br/>
  File "/home/y/bin/storm", line 482, in main<br/>
    (COMMANDS.get(COMMAND, unknown_command))(*ARGS)<br/>
  File "/home/y/bin/storm", line 225, in listtopos<br/>
    extrajars=<span class="error">&#91;USER_CONF_DIR, STORM_DIR + "/bin"&#93;</span>)<br/>
  File "/home/y/bin/storm", line 153, in exec_storm_class<br/>
    ] + jvmopts + <span class="error">&#91;klass&#93;</span> + list(args)<br/>
  File "/home/y/bin/storm", line 97, in confvalue<br/>
    p = sub.Popen(command, stdout=sub.PIPE)<br/>
  File "/usr/lib64/python2.6/subprocess.py", line 642, in _<em>init</em>_<br/>
    errread, errwrite)<br/>
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child<br/>
    raise child_exception</p>

<p>It would be nice if this were either detected and a proper error message printed, or if it warned and fell back to the java found in PATH.</p>

---
<details><summary><i>Originally reported by <a title="Paul Poulosky" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ppoulosk">ppoulosk</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-477" target="_blank">Incorrectly set JAVA_HOME is not detected</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Paul Poulosky" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ppoulosk">ppoulosk</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-06-26T17:52:09+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>If we force users to set JAVA_HOME, we can detect it easily (by checking existence of java executable file).<br/>
But currently storm script uses 'java' (rely on PATH), which can be hard to detect.<br/>
*Nix can run 'which' and check return code. (not 0 indicates error)<br/>
But I don't know it can be possible with Windows.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>We can probably handle detection of the JAVA_HOME case.  If we are ambitious we could look at catching the exception and seeing if there is a way for us to clean it up to something simpler for the end user to understand.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oleg.ost">oleg.ost</a>:</i>
<p>Hello!<br/>
I would really like to work on this issue. It is my first attempt to contribute in Apache Storm project, so it will be fine if someone could guide me through or give some advices. </p>

<p>I'll start by following steps here: <a href="https://storm.apache.org/documentation/Contributing-to-Storm.html" class="external-link" target="_blank" rel="nofollow noopener">https://storm.apache.org/documentation/Contributing-to-Storm.html</a><br/>
According to this, issues with "newbie" label may be good to start with.  </p>

<p>Could you please provide me more information about the issue and where I can find files realated to it?<br/>
Thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oleg.ost" class="user-hover" rel="oleg.ost">Oleg Ostashchuk</a>,</p>

<p>The file in question is storm in the bin directory <a href="https://github.com/apache/storm/blob/master/bin/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/bin/storm</a> this file really just sets up the environment to call into java and run the storm code there.  But if JAVA_HOME is set incorrectly, or if the java executable cannot be found we get a really odd error that is hard to debug.  The goal here is to output a user readable error if JAVA_HOME is set incorrectly, and if we can manage it to print out a user readable error if JAVA_HOME is not set and java is not on the path.</p>

<p>One of the key parts of this though is that we want it to run on *NIX and Windows.  So using *NIX specific commands like which will not work, unless you can short circuit it for windows.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user ppoulosk opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/457" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/457</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-477" title="Incorrectly set JAVA_HOME is not detected" class="issue-link" data-issue-key="STORM-477"><del>STORM-477</del></a>  Add warning for invalid JAVA_HOME</p>

<p>    This adds a check in the python script to ensure that JAVA_HOME points to an installation of storm, and prints an error message if it is not properly set.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/ppoulosk/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/ppoulosk/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-477" title="Incorrectly set JAVA_HOME is not detected" class="issue-link" data-issue-key="STORM-477"><del>STORM-477</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/457.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/457.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #457</p>

<hr />
<p>commit fc3dd60798c158a26380a931b31325249ca7af16<br/>
Author: Paul Poulosky <ppoulosk@yahoo-inc.com><br/>
Date:   2015-03-05T14:58:38Z</p>

<p>    Add warning for invalid JAVA_HOME</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/457#discussion_r26263810" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/457#discussion_r26263810</a></p>

<p>    &#8212; Diff: bin/storm &#8212;<br/>
    @@ -82,6 +82,8 @@ CONFFILE = ""<br/>
     JAR_JVM_OPTS = shlex.split(os.getenv('STORM_JAR_JVM_OPTS', ''))<br/>
     JAVA_HOME = os.getenv('JAVA_HOME', None)<br/>
     JAVA_CMD = 'java' if not JAVA_HOME else os.path.join(JAVA_HOME, 'bin', 'java')<br/>
    +if JAVA_HOME and not os.path.exists(JAVA_CMD):<br/>
    +    print "WARNING:  Check JAVA_HOME.  Could not find java at %s." % JAVA_HOME<br/>
    &#8212; End diff &#8211;</p>

<p>    I personally would rather have storm exit with an error here instead of just a warning.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oleg.ost">oleg.ost</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ppoulosk" class="user-hover" rel="ppoulosk">Paul Poulosky</a> Does it mean that the issue is solved? Or there still a need to do something?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oleg.ost">oleg.ost</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a> Thank you for answer! Yes, I would really like to work on some issue. Can you please advise me some? I just wasn't sure which email I should contact you. It is my first attempt to contribute in Apache Storm project, so it will be fine to start with something easier.<br/>
Thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oleg.ost" class="user-hover" rel="oleg.ost">Oleg Ostashchuk</a> Happy to help. Lets move this discussion onto mailing list . You can find mailing list info under "Getting Help" section on this page <a href="https://storm.apache.org/documentation/Home.html" class="external-link" target="_blank" rel="nofollow noopener">https://storm.apache.org/documentation/Home.html</a> .</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/457#issuecomment-106586323" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/457#issuecomment-106586323</a></p>

<p>    @ppoulosk any update on this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/457#issuecomment-108567623" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/457#issuecomment-108567623</a></p>

<p>    +1 looks good to me</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/457#issuecomment-110489805" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/457#issuecomment-110489805</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/457" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/457</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/457#issuecomment-115756416" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/457#issuecomment-115756416</a></p>

<p>    @ppoulosk Thank you for the patch. This is merged into the master now.</p>
