### ISSUE TITLE
[STORM-493] Workers don't inherit storm.conf.file/storm.options properties of the supervisor

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4335]
<p>If we override some configuration parameters on the command line (using storm -c "param=value") when we launch the supervisor, workers don't inherit them.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>> cat conf/storm.yaml
storm.zookeeper.servers:
     - "127.0.0.1"
nimbus.host: "127.0.0.1"
storm.zookeeper.root: "/stormtest"
storm.local.dir: "storm-local-main"

> python bin/storm -c "storm.local.dir=\"storm-local-custom\"" supervisor

> less logs/worker-6701.log
[...]
2014-09-10 09:35:00 o.a.s.z.s.ZooKeeperServer [INFO] Server environment:user.dir=/optc/2014-09-05-5aae7686
2014-09-10 09:35:01 b.s.d.worker [INFO] Launching worker for mytopo-1-1410334488 on 96f32da2-2043-4371-988b-ec9ca107ce69:6701 with id b9178c80-922b-4b8d-9984-7cfaf06f3c86 and conf {"dev.zookeeper.path" "/tmp/dev-storm-zookeeper", "topology.tick.tuple.freq.secs" nil, "topology.builtin.metrics.bucket.size.secs" 60, "topology.fall.back.on.java.serialization" true, "topology.max.error.report.per.interval" 5, "zmq.linger.millis" 5000, "topology.skip.missing.kryo.registrations" false, "storm.messaging.netty.client_worker_threads" 1, "ui.childopts" "-Xmx768m", "storm.zookeeper.session.timeout" 20000, "nimbus.reassign" true, "topology.trident.batch.emit.interval.millis" 500, "storm.messaging.netty.flush.check.interval.ms" 10, "nimbus.monitor.freq.secs" 10, "logviewer.childopts" "-Xmx128m", "java.library.path" "/usr/local/lib:/opt/local/lib:/usr/lib", "topology.executor.send.buffer.size" 1024, "storm.local.dir" "storm-local-main", "storm.messaging.netty.buffer_size" 5242880, "supervisor.worker.start.timeout.secs" 120, "topology.enable.message.timeouts" true, "nimbus.cleanup.inbox.freq.secs" 600, "nimbus.inbox.jar.expiration.secs" 3600, "drpc.worker.threads" 64, "storm.meta.serialization.delegate" "backtype.storm.serialization.DefaultSerializationDelegate", "topology.worker.shared.thread.pool.size" 4, "nimbus.host" "127.0.0.1", "storm.messaging.netty.min_wait_ms" 100, "storm.zookeeper.port" 2181, "transactional.zookeeper.port" nil, "topology.executor.receive.buffer.size" 1024, "transactional.zookeeper.servers" nil, "storm.zookeeper.root" "/stormtest", "storm.zookeeper.retry.intervalceiling.millis" 30000, "supervisor.enable" true, "storm.messaging.netty.server_worker_threads" 1, "storm.zookeeper.servers" ["127.0.0.1"], "transactional.zookeeper.root" "/transactional", "topology.acker.executors" nil, "topology.transfer.buffer.size" 1024, "topology.worker.childopts" nil, "drpc.queue.size" 128, "worker.childopts" "-Xmx768m", "supervisor.heartbeat.frequency.secs" 5, "topology.error.throttle.interval.secs" 10, "zmq.hwm" 0, "drpc.port" 3772, "supervisor.monitor.frequency.secs" 3, "drpc.childopts" "-Xmx768m", "topology.receiver.buffer.size" 8, "task.heartbeat.frequency.secs" 3, "topology.tasks" nil, "storm.messaging.netty.max_retries" 300, "topology.spout.wait.strategy" "backtype.storm.spout.SleepSpoutWaitStrategy", "nimbus.thrift.max_buffer_size" 1048576, "topology.max.spout.pending" nil, "storm.zookeeper.retry.interval" 1000, "topology.sleep.spout.wait.strategy.time.ms" 1, "nimbus.topology.validator" "backtype.storm.nimbus.DefaultTopologyValidator", "supervisor.slots.ports" [6700 6701 6702 6703], "topology.environment" nil, "topology.debug" false, "nimbus.task.launch.secs" 120, "nimbus.supervisor.timeout.secs" 60, "topology.message.timeout.secs" 30, "task.refresh.poll.secs" 10, "topology.workers" 1, "supervisor.childopts" "-Xmx256m", "nimbus.thrift.port" 6627, "topology.stats.sample.rate" 0.05, "worker.heartbeat.frequency.secs" 1, "topology.tuple.serializer" "backtype.storm.serialization.types.ListDelegateSerializer", "topology.disruptor.wait.strategy" "com.lmax.disruptor.BlockingWaitStrategy", "topology.multilang.serializer" "backtype.storm.multilang.JsonSerializer", "nimbus.task.timeout.secs" 30, "storm.zookeeper.connection.timeout" 15000, "topology.kryo.factory" "backtype.storm.serialization.DefaultKryoFactory", "drpc.invocations.port" 3773, "logviewer.port" 8000, "zmq.threads" 1, "storm.zookeeper.retry.times" 5, "topology.worker.receiver.thread.count" 1, "storm.thrift.transport" "backtype.storm.security.auth.SimpleTransportPlugin", "topology.state.synchronization.timeout.secs" 60, "supervisor.worker.timeout.secs" 30, "nimbus.file.copy.expiration.secs" 600, "storm.messaging.transport" "backtype.storm.messaging.netty.Context", "logviewer.appender.name" "A1", "storm.messaging.netty.max_wait_ms" 1000, "drpc.request.timeout.secs" 600, "storm.local.mode.zmq" false, "ui.port" 8080, "nimbus.childopts" "-Xmx1024m", "storm.cluster.mode" "distributed", "topology.max.task.parallelism" nil, "storm.messaging.netty.transfer.batch.size" 262144, "topology.classpath" nil}
2014-09-10 09:35:01 b.s.util [DEBUG] Touching file at storm-local-main/workers/b9178c80-922b-4b8d-9984-7cfaf06f3c86/pids/30958
2014-09-10 09:35:01 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.7.0_60]
	at java.io.File.createNewFile(File.java:1006) ~[na:1.7.0_60]
	at backtype.storm.util$touch.invoke(util.clj:519) ~[storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at backtype.storm.daemon.worker$fn__6535$exec_fn__1474__auto____6536.invoke(worker.clj:362) ~[storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.AFn.applyToHelper(AFn.java:185) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__6535$mk_worker__6591.doInvoke(worker.clj:354) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:461) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
2014-09-10 09:35:01 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:319) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__6535$mk_worker__6591.doInvoke(worker.clj:354) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:461) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
[...]
</pre>
</div></div>

<p>The worker tries to use the local directory defined in the configuration file (storm-local-main) instead of the local directory defined on the command line (storm-local-custom).</p>

<hr />

<p>There is a similar problem with configuration file name. If we specify it on the command line, workers don't inherit it and search the default "storm.yaml" file in the classpath.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>> cat conf/storm.yaml
storm.zookeeper.servers:
     - "127.0.0.1"
nimbus.host: "127.0.0.1"
storm.zookeeper.root: "/stormtest"
storm.local.dir: "storm-local-default"

> cat conf/storm-custom.yaml
storm.zookeeper.servers:
     - "127.0.0.1"
nimbus.host: "127.0.0.1"
storm.zookeeper.root: "/stormtest"
storm.local.dir: "storm-local-custom"

> python bin/storm --config storm-custom.yaml supervisor

> less logs/worker-6700.log
[...]
2014-09-10 10:16:01 o.a.s.z.s.ZooKeeperServer [INFO] Server environment:user.dir=/optc/2014-09-05-5aae7686
2014-09-10 10:16:01 b.s.d.worker [INFO] Launching worker for mytopo-1-1410336834 on 38c99fbd-e5e5-4c53-b704-7ec460f5e227:6700 with id 2133bad6-432d-4c63-a156-1184064d296b and conf {"dev.zookeeper.path" "/tmp/dev-storm-zookeeper", "topology.tick.tuple.freq.secs" nil, "topology.builtin.metrics.bucket.size.secs" 60, "topology.fall.back.on.java.serialization" true, "topology.max.error.report.per.interval" 5, "zmq.linger.millis" 5000, "topology.skip.missing.kryo.registrations" false, "storm.messaging.netty.client_worker_threads" 1, "ui.childopts" "-Xmx768m", "storm.zookeeper.session.timeout" 20000, "nimbus.reassign" true, "topology.trident.batch.emit.interval.millis" 500, "storm.messaging.netty.flush.check.interval.ms" 10, "nimbus.monitor.freq.secs" 10, "logviewer.childopts" "-Xmx128m", "java.library.path" "/usr/local/lib:/opt/local/lib:/usr/lib", "topology.executor.send.buffer.size" 1024, "storm.local.dir" "storm-local-default", "storm.messaging.netty.buffer_size" 5242880, "supervisor.worker.start.timeout.secs" 120, "topology.enable.message.timeouts" true, "nimbus.cleanup.inbox.freq.secs" 600, "nimbus.inbox.jar.expiration.secs" 3600, "drpc.worker.threads" 64, "storm.meta.serialization.delegate" "backtype.storm.serialization.DefaultSerializationDelegate", "topology.worker.shared.thread.pool.size" 4, "nimbus.host" "127.0.0.1", "storm.messaging.netty.min_wait_ms" 100, "storm.zookeeper.port" 2181, "transactional.zookeeper.port" nil, "topology.executor.receive.buffer.size" 1024, "transactional.zookeeper.servers" nil, "storm.zookeeper.root" "/stormtest", "storm.zookeeper.retry.intervalceiling.millis" 30000, "supervisor.enable" true, "storm.messaging.netty.server_worker_threads" 1, "storm.zookeeper.servers" ["127.0.0.1"], "transactional.zookeeper.root" "/transactional", "topology.acker.executors" nil, "topology.transfer.buffer.size" 1024, "topology.worker.childopts" nil, "drpc.queue.size" 128, "worker.childopts" "-Xmx768m", "supervisor.heartbeat.frequency.secs" 5, "topology.error.throttle.interval.secs" 10, "zmq.hwm" 0, "drpc.port" 3772, "supervisor.monitor.frequency.secs" 3, "drpc.childopts" "-Xmx768m", "topology.receiver.buffer.size" 8, "task.heartbeat.frequency.secs" 3, "topology.tasks" nil, "storm.messaging.netty.max_retries" 300, "topology.spout.wait.strategy" "backtype.storm.spout.SleepSpoutWaitStrategy", "nimbus.thrift.max_buffer_size" 1048576, "topology.max.spout.pending" nil, "storm.zookeeper.retry.interval" 1000, "topology.sleep.spout.wait.strategy.time.ms" 1, "nimbus.topology.validator" "backtype.storm.nimbus.DefaultTopologyValidator", "supervisor.slots.ports" [6700 6701 6702 6703], "topology.environment" nil, "topology.debug" false, "nimbus.task.launch.secs" 120, "nimbus.supervisor.timeout.secs" 60, "topology.message.timeout.secs" 30, "task.refresh.poll.secs" 10, "topology.workers" 1, "supervisor.childopts" "-Xmx256m", "nimbus.thrift.port" 6627, "topology.stats.sample.rate" 0.05, "worker.heartbeat.frequency.secs" 1, "topology.tuple.serializer" "backtype.storm.serialization.types.ListDelegateSerializer", "topology.disruptor.wait.strategy" "com.lmax.disruptor.BlockingWaitStrategy", "topology.multilang.serializer" "backtype.storm.multilang.JsonSerializer", "nimbus.task.timeout.secs" 30, "storm.zookeeper.connection.timeout" 15000, "topology.kryo.factory" "backtype.storm.serialization.DefaultKryoFactory", "drpc.invocations.port" 3773, "logviewer.port" 8000, "zmq.threads" 1, "storm.zookeeper.retry.times" 5, "topology.worker.receiver.thread.count" 1, "storm.thrift.transport" "backtype.storm.security.auth.SimpleTransportPlugin", "topology.state.synchronization.timeout.secs" 60, "supervisor.worker.timeout.secs" 30, "nimbus.file.copy.expiration.secs" 600, "storm.messaging.transport" "backtype.storm.messaging.netty.Context", "logviewer.appender.name" "A1", "storm.messaging.netty.max_wait_ms" 1000, "drpc.request.timeout.secs" 600, "storm.local.mode.zmq" false, "ui.port" 8080, "nimbus.childopts" "-Xmx1024m", "storm.cluster.mode" "distributed", "topology.max.task.parallelism" nil, "storm.messaging.netty.transfer.batch.size" 262144, "topology.classpath" nil}
2014-09-10 10:16:01 b.s.util [DEBUG] Touching file at storm-local-default/workers/2133bad6-432d-4c63-a156-1184064d296b/pids/31689
2014-09-10 10:16:01 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.7.0_60]
	at java.io.File.createNewFile(File.java:1006) ~[na:1.7.0_60]
	at backtype.storm.util$touch.invoke(util.clj:519) ~[storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at backtype.storm.daemon.worker$fn__6535$exec_fn__1474__auto____6536.invoke(worker.clj:362) ~[storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.AFn.applyToHelper(AFn.java:185) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__6535$mk_worker__6591.doInvoke(worker.clj:354) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:461) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
2014-09-10 10:16:01 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:319) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__6535$mk_worker__6591.doInvoke(worker.clj:354) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:461) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT]
</pre>
</div></div>

<p>The worker tries to use the local directory "storm-local-default" defined in the configuration file "storm.yaml" instead of using the local directory "storm-local-custom" defined in the file "storm-custom.yaml" specified on the command line.</p>

---
<details><summary><i>Originally reported by <a title="Christophe Carré" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chrisz">chrisz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-493" target="_blank">Workers don't inherit storm.conf.file/storm.options properties of the supervisor</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Christophe Carré" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chrisz">chrisz</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-09-24T22:00:30+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user chrisz opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/252" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/252</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-493" title="Workers don&#39;t inherit storm.conf.file/storm.options properties of the supervisor" class="issue-link" data-issue-key="STORM-493"><del>STORM-493</del></a>: Workers inherit storm.conf.file/storm.options properties of their supervisor</p>

<p>    Without this fix, if we override some configuration parameters on the command line (using storm -c "param=value") when we launch the supervisor, workers don't inherit them.<br/>
    There is a similar problem with configuration file name. If we specify it on the command line, workers don't inherit it and search the default "storm.yaml" file in the classpath.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/chrisz/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/chrisz/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-493" title="Workers don&#39;t inherit storm.conf.file/storm.options properties of the supervisor" class="issue-link" data-issue-key="STORM-493"><del>STORM-493</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/252.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/252.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #252</p>

<hr />
<p>commit 4a7e634354df85f9ce52338a33e1e5fc1472f406<br/>
Author: Christophe Carré <christophe.carre@ymail.com><br/>
Date:   2014-09-10T13:32:53Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-493" title="Workers don&#39;t inherit storm.conf.file/storm.options properties of the supervisor" class="issue-link" data-issue-key="STORM-493"><del>STORM-493</del></a>: Workers inherit storm.conf.file/storm.options properties of their supervisor</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user chrisz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/252#issuecomment-55294806" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/252#issuecomment-55294806</a></p>

<p>    I have some difficulties to have a working environment to execute unit tests of Storm: there are some timeout during tests (even before my fix) and I don't know what is bad with ma machine.</p>

<p>    I fixed unit tests related to my change.  I tried to add some tests but I am not comfortable with clojure...</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/252#issuecomment-56730938" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/252#issuecomment-56730938</a></p>

<p>    The test issues we have seen with timeouts seem to show up a lot with VMs, or slow servers.  I don't really know for sure what is happening there.  The code looks like it should work I am +1 for merging this in.</p>

<p>    @Parth-Brahmbhatt writing a test for this really does sound difficult because you would have to spawn a separate process and validate that the config is passed to the new process. If you still do want a test I'll relent, but otherwise I would like to check this in.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks for the fix Christophe,  Keep up the good work.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user clockfly commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/252#issuecomment-61600229" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/252#issuecomment-61600229</a></p>

<p>    @revans2, looks like you mark it as resolved. Have you merged ths into trunk in other PR?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user clockfly commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/252#issuecomment-61639159" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/252#issuecomment-61639159</a></p>

<p>    +1</p>
