### ISSUE TITLE
[STORM-498] storm-kafka: make ZK connection timeout configurable in Kafka spout

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4340]
<p>Currently the Kafka spout uses a hardcoded ZK connection timeout of 15 seconds in <tt>external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java</tt>:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">_curator = CuratorFrameworkFactory.newClient(
    zkStr,
    Utils.getInt(conf.get(Config.STORM_ZOOKEEPER_SESSION_TIMEOUT)),
    15000,
    <span class="code-keyword">new</span> RetryNTimes(Utils.getInt(conf.get(Config.STORM_ZOOKEEPER_RETRY_TIMES)),
Utils.getInt(conf.get(Config.STORM_ZOOKEEPER_RETRY_INTERVAL))));
</pre>
</div></div>

<p>We should make this setting configurable, similar to the ZK session timeout setting.</p>

---
<details><summary><i>Originally reported by <a title="Michael G. Noll" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=miguno">miguno</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-498" target="_blank">storm-kafka: make ZK connection timeout configurable in Kafka spout</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Michael G. Noll" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=miguno">miguno</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-10-09T02:18:19+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user miguno opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/256" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/256</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-498" title="storm-kafka: make ZK connection timeout configurable in Kafka spout" class="issue-link" data-issue-key="STORM-498"><del>STORM-498</del></a>: make ZK connection timeout configurable in Kafka spout</p>

<p>    This change is backwards compatible to the previous semantics because Storm's default.yaml sets the default ZK connection timeout to 15 seconds, which is equal to the previously hardcoded timeout setting in the Kafka spout.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/miguno/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/miguno/incubator-storm</a> master</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/256.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/256.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #256</p>

<hr />
<p>commit c35badeae24cb271d504e3c4005192493e0de335<br/>
Author: Michael G. Noll <mnoll@verisign.com><br/>
Date:   2014-09-16T13:27:12Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-498" title="storm-kafka: make ZK connection timeout configurable in Kafka spout" class="issue-link" data-issue-key="STORM-498"><del>STORM-498</del></a>: make ZK connection timeout configurable in Kafka spout</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/256#issuecomment-55764291" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/256#issuecomment-55764291</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/256#issuecomment-56376508" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256#issuecomment-56376508</a></p>

<p>    Anyone else able to provide feedback?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/256#issuecomment-56382418" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256#issuecomment-56382418</a></p>

<p>    I think this should be fine +1.  My only concern would be that kafka uses a different zookeeper instance so in theory you may want to set the ZK timeout differently for each, but it should not be a big deal. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/256#issuecomment-56383244" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256#issuecomment-56383244</a></p>

<p>    Bobby, I definitely agree with that we may want to decouple ZK (timeout) settings in Kafka from the ZK used by Storm "elsewhere".  But I didn't want to conflate these two related but different issues in the same PR.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/256#issuecomment-56384816" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256#issuecomment-56384816</a></p>

<p>    Michael, I totally agree.  That is why I gave this a +1. I plan on checking it in shortly, which hopefully means today assuming things don't go too badly.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/256#issuecomment-56440942" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256#issuecomment-56440942</a></p>

<p>    I am consistently getting NPE errors in several tests now.<br/>
    ```<br/>
    Tests in error: <br/>
      testMultiplePartitionsOnDifferentHosts(storm.kafka.DynamicBrokersReaderTest): java.lang.RuntimeException: java.lang.NullPointerException<br/>
      testMultiplePartitionsOnDifferentHosts(storm.kafka.DynamicBrokersReaderTest)<br/>
      testSwitchHostForPartition(storm.kafka.DynamicBrokersReaderTest): java.lang.RuntimeException: java.lang.NullPointerException<br/>
      testSwitchHostForPartition(storm.kafka.DynamicBrokersReaderTest)<br/>
      testGetBrokerInfo(storm.kafka.DynamicBrokersReaderTest): java.lang.RuntimeException: java.lang.NullPointerException<br/>
      testGetBrokerInfo(storm.kafka.DynamicBrokersReaderTest)<br/>
      testMultiplePartitionsOnSameHost(storm.kafka.DynamicBrokersReaderTest): java.lang.RuntimeException: java.lang.NullPointerException<br/>
      testMultiplePartitionsOnSameHost(storm.kafka.DynamicBrokersReaderTest)<br/>
    ```<br/>
    It looks like the config is not set and then the errors is just logged.  The NPE happens later on when it tries to use the client but it is NULL because of the exception.</p>

<p>    ```<br/>
    10463 <span class="error">&#91;main&#93;</span> ERROR storm.kafka.DynamicBrokersReader - Couldn't connect to zookeeper<br/>
    java.lang.IllegalArgumentException: Don't know how to convert null to int<br/>
    at backtype.storm.utils.Utils.getInt(Utils.java:301) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
    at storm.kafka.DynamicBrokersReader.<init>(DynamicBrokersReader.java:50) ~<span class="error">&#91;classes/:na&#93;</span><br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/256#issuecomment-56444708" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256#issuecomment-56444708</a></p>

<p>    I'll take a look, Bobby.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user miguno opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/264" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/264</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-498" title="storm-kafka: make ZK connection timeout configurable in Kafka spout" class="issue-link" data-issue-key="STORM-498"><del>STORM-498</del></a>: make ZK connection timeout configurable in Kafka spout</p>

<p>    This change is backwards compatible to the previous semantics because Storm's `defaults.yaml` sets the default ZK connection timeout to 15 seconds, which is equal to the previously hardcoded timeout setting in the Kafka spout.</p>

<p>    This pull request supersedes the previous pull request <a href="https://github.com/apache/storm/pull/256" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256</a>, and fixes the NPE in the `DynamicBrokersReaderTest` test suite.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/miguno/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/miguno/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-498" title="storm-kafka: make ZK connection timeout configurable in Kafka spout" class="issue-link" data-issue-key="STORM-498"><del>STORM-498</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/264.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/264.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #264</p>

<hr />
<p>commit 2596e335f27a57784a93a57823bd93dde587909f<br/>
Author: Michael G. Noll <mnoll@verisign.com><br/>
Date:   2014-09-23T06:55:12Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-498" title="storm-kafka: make ZK connection timeout configurable in Kafka spout" class="issue-link" data-issue-key="STORM-498"><del>STORM-498</del></a>: make ZK connection timeout configurable in Kafka spout</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/256#issuecomment-56482931" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256#issuecomment-56482931</a></p>

<p>    Closed in favor of <a href="https://github.com/apache/storm/pull/264" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/264</a>, which fixes the NPE in the test suite.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/256" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/256</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/264#issuecomment-56538725" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/264#issuecomment-56538725</a></p>

<p>    +1 looks good to me.  Tests pass now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/264#issuecomment-56804078" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/264#issuecomment-56804078</a></p>

<p>    Merged into master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/264" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/264</a></p>
