### ISSUE TITLE
[STORM-512] KafkaBolt doesn't handle ticks properly

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4354]
<p>I found that when using the KafkaBolt the tick tuples are not handled properly. They should be ignored and the reality is that they are not.</p>

---
<details><summary><i>Originally reported by <a title="Niels Basjes" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nielsbasjes">nielsbasjes</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-512" target="_blank">KafkaBolt doesn't handle ticks properly</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Niels Basjes" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nielsbasjes">nielsbasjes</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-04-03T15:40:29+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nielsbasjes">nielsbasjes</a>:</i>
<p>I'm willing to prepare a patch.<br/>
To make this more usable I think the proper way is to create a method that essentially returns a boolean in response to the question "Is this a tick tuple?".<br/>
Now I see two ways of doing this:</p>
<ol>
	<li>A helper class with a static method. i.e.  TupleHelper.isTickTuple(Tuple t)</li>
	<li>An addition to the "Tuple" interface with a method "isTick".</li>
</ol>


<p>I thing the latter is nicer because that also makes it very easy for application developers to handle ticks correctly.</p>

<p>In both scenarios the code would essentially be </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">return</span> tuple.getSourceComponent().equals(Constants.SYSTEM_COMPONENT_ID) &&
   tuple.getSourceStreamId().equals(Constants.SYSTEM_TICK_STREAM_ID);</pre>
</div></div>

<p>Which solution direction do you guys want?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user nielsbasjes opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-512" title="KafkaBolt doesn&#39;t handle ticks properly" class="issue-link" data-issue-key="STORM-512"><del>STORM-512</del></a> KafkaBolt doesn't handle ticks properly</p>

<p>    I implemented this by <br/>
    1.   Adding an 'boolean isTick()' method to the Tuple interface. <br/>
   This way it is for application builders much easier to  determine if the tuple at hand is a Tick or not.<br/>
    2.   Letting the KafkaBolt use that method to ignore the ticks.<br/>
    3.   Updating the other place in the code base that handles ticks differently to use this new method.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/nielsbasjes/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nielsbasjes/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-512" title="KafkaBolt doesn&#39;t handle ticks properly" class="issue-link" data-issue-key="STORM-512"><del>STORM-512</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/275.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #275</p>

<hr />
<p>commit 6c6bec9b1b2b07b5dfb5000297c11911eda5389d<br/>
Author: Niels Basjes <nbasjes@bol.com><br/>
Date:   2014-10-01T09:50:48Z</p>

<p>    New method in the Tuple interface "boolean isTuple()" for easier handling of TickTuples.</p>

<p>commit 73e54a8f8b0ef9a62955c7c1cee20925d359772b<br/>
Author: Niels Basjes <nbasjes@bol.com><br/>
Date:   2014-10-01T09:51:42Z</p>

<p>    KafkaBolt no longer tries to map/process/send Tick Tuples to Kafka.</p>

<p>commit 8888ae631360ad124af9c480d2f8b621b9c51727<br/>
Author: Niels Basjes <nbasjes@bol.com><br/>
Date:   2014-10-01T09:53:17Z</p>

<p>    Use isTick in all relevant places to avoid code duplication.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-60838468" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-60838468</a></p>

<p>    Looks reasonable to me, but I would like someone more familiar with kafka to comment on whether we never want to execute on tick tuples.</p>

<p>    We could move make the static method in <span class="error">&#91;TupleHelpers&#93;</span>(<a href="https://github.com/apache/storm/blob/5a460384f4eb90e4e3870f29090e81633aeafe7b/examples/storm-starter/src/jvm/storm/starter/util/TupleHelpers.java#L29-L30" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/5a460384f4eb90e4e3870f29090e81633aeafe7b/examples/storm-starter/src/jvm/storm/starter/util/TupleHelpers.java#L29-L30</a>) a member method in TupleImpl as you have done, remove TupleHelpers, and then change the example code to use this method.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nielsbasjes commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-60935570" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-60935570</a></p>

<p>    The execute of the KafkaBolt puts the tuple into Kafka as a message.<br/>
    What I ran into is that the Ticks were put into Kafka as messages too. <br/>
    My consumers of this Kafka queue got really upset (lots of deserialisation exceptions) over these ticks.</p>

<p>    I'll update the example code as you indicated.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nielsbasjes commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-61971101" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-61971101</a></p>

<p>    What else can/should I do to get this fix validated and committed?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-63347222" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-63347222</a></p>

<p>    The changes look fine to me.  +1, @d2r in this case the bolt is taking its input and sending it to a kafka queue.  I don't think we want to send ticks to the kafka queue, as the ticks are internal to storm, and will not have the key/value that all other tuples have. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-63349586" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-63349586</a></p>

<p>    OK I am wrong.  When I tried to compile with this change the following tests failed.</p>

<p>    ```<br/>
    Failed tests:   shouldEmitSomethingIfTickTupleIsReceived(storm.starter.bolt.IntermediateRankingsBoltTest): Index: 0, Size: 0<br/>
      shouldEmitNothingIfNoObjectHasBeenCountedYetAndTickTupleIsReceived(storm.starter.bolt.RollingCountBoltTest): <br/>
      shouldEmitSomethingIfAtLeastOneObjectWasCountedAndTickTupleIsReceived(storm.starter.bolt.RollingCountBoltTest): <br/>
      shouldEmitSomethingIfTickTupleIsReceived(storm.starter.bolt.TotalRankingsBoltTest)<br/>
    ```</p>

<p>    It looks like to me that the tick is being used somewhere else.  Why exactly do we not want the ticks?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nielsbasjes commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-63355100" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-63355100</a></p>

<p>    I'll have a look into why these tests failed.</p>

<p>    Regarding the 'why':<br/>
    A Tick is a message between the Storm framework and a bolt that runs within the framework. Kafka bolt should handle the tick any way suitable, but most importantly is must NOT persist the tick into Kafka.<br/>
    I ran into the scenario that a non-Storm consumer of this Kafka topic gave errors because it got a message (= a Tick) that did not adhere to the agreed interface (i.e. I got deserialization exceptions).</p>

<p>    So that's why.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-63355950" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-63355950</a></p>

<p>    That is what I expected, thanks for clarifying @nielsbasjes Now I am very confused why there is a test that looks like it explicitly tests that the ticks are persisted.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nielsbasjes commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-63358387" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-63358387</a></p>

<p>    I think you are right. It seems like the assumption that was made during the development of that test is not 100% accurate in all scenarios.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-66294912" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-66294912</a></p>

<p>    The explanation makes sense.  I still see some test errors:<br/>
    ```<br/>
    java.lang.NullPointerException<br/>
at backtype.storm.tuple.TupleImpl.isTick(TupleImpl.java:218)<br/>
at storm.kafka.bolt.KafkaBolt.execute(KafkaBolt.java:92)<br/>
at storm.kafka.bolt.KafkaBoltTest.executeWithBrokerDown(KafkaBoltTest.java:145)<br/>
    ```<br/>
    ```<br/>
    java.lang.NullPointerException<br/>
at backtype.storm.tuple.TupleImpl.isTick(TupleImpl.java:218)<br/>
at storm.kafka.bolt.KafkaBolt.execute(KafkaBolt.java:92)<br/>
at storm.kafka.bolt.KafkaBoltTest.executeWithoutKey(KafkaBoltTest.java:134)<br/>
    ```<br/>
    ```<br/>
    java.lang.NullPointerException<br/>
at backtype.storm.tuple.TupleImpl.isTick(TupleImpl.java:218)<br/>
at storm.kafka.bolt.KafkaBolt.execute(KafkaBolt.java:92)<br/>
at storm.kafka.bolt.KafkaBoltTest.executeWithByteArrayKeyAndMessage(KafkaBoltTest.java:104)<br/>
    ```<br/>
    ```<br/>
    java.lang.NullPointerException<br/>
at backtype.storm.tuple.TupleImpl.isTick(TupleImpl.java:218)<br/>
at storm.kafka.bolt.KafkaBolt.execute(KafkaBolt.java:92)<br/>
at storm.kafka.bolt.KafkaBoltTest.executeWithKey(KafkaBoltTest.java:91)<br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nielsbasjes commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-66650582" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-66650582</a></p>

<p>    @d2r Thanks! The latest commit I did fixes this problem.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-66666316" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-66666316</a></p>

<p>    @nielsbasjes Yeah that fixed it.  I see all tests passing now. Thank you! +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nielsbasjes commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-66971975" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-66971975</a></p>

<p>    @nathanmarz Thanks I understand your view now. <br/>
    I refactored my patch to meet this requirement and I've tried to make it as small a difference as possible.</p>

<p>    This set of commits should really be squashed before committing to the master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nielsbasjes commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-74696542" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-74696542</a></p>

<p>    @nathanmarz / @revans2 What must I do/change to get this solution committed? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-89020139" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-89020139</a></p>

<p>    @nathanmarz any update on your opinion of this.  Your original concerns were addressed, and I feel we should check this in.  If I don't hear back soon I'll assume that it is OK.  This patch has languished far too long.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-93694857" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-93694857</a></p>

<p>    I created <a href="https://issues.apache.org/jira/browse/STORM-786" title="KafkaBolt should ack tick tuples" class="issue-link" data-issue-key="STORM-786"><del>STORM-786</del></a>(<a href="https://issues.apache.org/jira/browse/STORM-786" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-786</a>) to track the tick tuple acking.  Pull request is already sent.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nielsbasjes commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-93697965" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-93697965</a></p>

<p>     I had this ack for the tick in there in an earlier version of the change.<br/>
    Then I asked on the mailing list if this ack is needed and I was told that it is not required.<br/>
    <a href="http://mail-archives.apache.org/mod_mbox/storm-user/201411.mbox/%3CCAAognGZ1pEt0RfKXn+sSeo+djy38LKQ4e3gw1GBn-WmMqWk9YQ@mail.gmail.com%3E" class="external-link" target="_blank" rel="nofollow noopener">http://mail-archives.apache.org/mod_mbox/storm-user/201411.mbox/%3CCAAognGZ1pEt0RfKXn+sSeo+djy38LKQ4e3gw1GBn-WmMqWk9YQ@mail.gmail.com%3E</a><br/>
    So I took it out. </p>

<p>    Just to understand: Is ackibg a tick needed?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user miguno commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-93699373" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-93699373</a></p>

<p>    My understanding is yes, you do need to ack tick tuples.  See @nathanmarz <span class="error">&#91;comment&#93;</span>(<a href="https://groups.google.com/forum/#!topic/storm-user/ZEJabXT5nQA" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!topic/storm-user/ZEJabXT5nQA</a>) from some time back:</p>

<p>    >> Do I need to ack tick tuples?  Since they're system generated I'm think yes but I'm not sure.<br/>
    ><br/>
    > Nathan's answer: You should ack all tuples.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basti.lj">basti.lj</a>:</i>
<p>I don't think it is necessary. Acker is not used to guarantee that tick tuple is processed. It does not make sense to call ack() here.<br/>
If "not ack" makes incorrect count of failuire message, the relative statistic part of core should be updated.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nathanmarz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/275#issuecomment-94068063" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/275#issuecomment-94068063</a></p>

<p>    I didn't get a notification that you were pinging me – but fwiw I'm +1 on it</p>
