### ISSUE TITLE
[STORM-522] NullPointerException in storm.kafka.ZkCoordinator

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4364]
<p>We've been seeing these about once a week. The nimbus will kill and reassign the topology (on the same hardware) get caught up to "now" in kafka and happily continue running until the next time it encounters an event like this.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2014-09-30 13:59:40 s.k.ZkCoordinator [INFO] Deleted partition managers: [10.1.2.1:9092:0, 10.1.2.2:9092:1, 10.1.2.3:9092:3]
2014-09-30 13:59:40 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: java.lang.NullPointerException
at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:148) ~[stormjar.jar:na]
at storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:77) ~[stormjar.jar:na]
at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:94) ~[stormjar.jar:na]
at backtype.storm.daemon.executor$fn__5573$fn__5588$fn__5617.invoke(executor.clj:563) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.util$async_loop$fn__457.invoke(util.clj:431) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [na:1.7.0_55]
Caused by: java.lang.NullPointerException: <span class="code-keyword">null</span>
at storm.kafka.DynamicPartitionConnections.unregister(DynamicPartitionConnections.java:39) ~[stormjar.jar:na]
at storm.kafka.PartitionManager.close(PartitionManager.java:205) ~[stormjar.jar:na]
at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:135) ~[stormjar.jar:na]
... 6 common frames omitted
2014-09-30 13:59:40 b.s.d.executor [ERROR]
java.lang.RuntimeException: java.lang.NullPointerException
at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:148) ~[stormjar.jar:na]
at storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:77) ~[stormjar.jar:na]
at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:94) ~[stormjar.jar:na]
at backtype.storm.daemon.executor$fn__5573$fn__5588$fn__5617.invoke(executor.clj:563) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at backtype.storm.util$async_loop$fn__457.invoke(util.clj:431) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [na:1.7.0_55]
Caused by: java.lang.NullPointerException: <span class="code-keyword">null</span>
at storm.kafka.DynamicPartitionConnections.unregister(DynamicPartitionConnections.java:39) ~[stormjar.jar:na]
at storm.kafka.PartitionManager.close(PartitionManager.java:205) ~[stormjar.jar:na]
at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:135) ~[stormjar.jar:na]
... 6 common frames omitted
2014-09-30 13:59:40 b.s.util [INFO] Halting process: (<span class="code-quote">"Worker died"</span>)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Peter Haggerty" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=peter-librato">peter-librato</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-522" target="_blank">NullPointerException in storm.kafka.ZkCoordinator</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:32+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
