### ISSUE TITLE
[STORM-536] java.lang.NoClassDefFoundError: org/apache/cassandra/thrift/TBinaryProtocol on windows

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4378]
<p>When I run a program which works with Storm and cassandra in windows7 I got the following error:</p>

<p>java.lang.NoClassDefFoundError: org/apache/cassandra/thrift/TBinaryProtocol<br/>
	at com.netflix.astyanax.thrift.ThriftSyncConnectionFactoryImpl.createConnection(ThriftSyncConnectionFactoryImpl.java:89) ~<span class="error">&#91;Storm-starter.jar:na&#93;</span><br/>
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.tryOpenAsync(SimpleHostConnectionPool.java:416) ~<span class="error">&#91;Storm-starter.jar:na&#93;</span><br/>
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:181) ~<span class="error">&#91;Storm-starter.jar:na&#93;</span><br/>
	at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:66) ~<span class="error">&#91;Storm-starter.jar:na&#93;</span><br/>
	at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:67) ~<span class="error">&#91;Storm-starter.jar:na&#93;</span><br/>
	at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:253) ~<span class="error">&#91;Storm-starter.jar:na&#93;</span><br/>
	at com.netflix.astyanax.thrift.ThriftKeyspaceImpl.executeOperation(ThriftKeyspaceImpl.java:465) ~<span class="error">&#91;Storm-starter.jar:na&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Enayat" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erajabi">erajabi</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-536" target="_blank">java.lang.NoClassDefFoundError: org/apache/cassandra/thrift/TBinaryProtocol on windows</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:55:00+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
