### ISSUE TITLE
[STORM-538] Guava com.google.thirdparty.publicsuffix is not shaded

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4380]
<p>Hi!</p>

<p>I've just tried last 0.9.3-rc1 release which is available on <a href="http://storm.apache.org" class="external-link" target="_blank" rel="nofollow noopener">http://storm.apache.org</a> and I got an issue with seems to be linked to <a href="https://issues.apache.org/jira/browse/STORM-447" title="shade/relocate packages of dependencies that are common causes of dependency conflicts" class="issue-link" data-issue-key="STORM-447"><del>STORM-447</del></a>.</p>

<p>Here is the following stacktrace (stripping our package from trace) :</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.NoSuchFieldError: EXACT
at com.google.common.net.InternetDomainName.findPublicSuffix(InternetDomainName.java:173)
at com.google.common.net.InternetDomainName.<init>(InternetDomainName.java:158)
at com.google.common.net.InternetDomainName.from(InternetDomainName.java:213) 
[...]
</pre>
</div></div>

<p><cite>EXACT field is expected to be present in com.google.thirdparty.publicsuffix.PublicSuffixPatterns</cite></p>

<p>Having a quick look at storm-core-0.9.3-rc1.jar contents :</p>
<ul>
	<li>com.google.common is relocated to org.apache.storm.guava</li>
	<li>com.google.thirdparty.publicsuffix is <b>not</b> relocated so it might conflict with user code (that's my case)</li>
</ul>

<p>Regards,</p>

---
<details><summary><i>Originally reported by <a title="Damien Raude-Morvan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=drazzib">drazzib</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-538" target="_blank">Guava com.google.thirdparty.publicsuffix is not shaded</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-10-27T20:44:35+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user drazzib opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/299" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/299</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-538" title="Guava com.google.thirdparty.publicsuffix is not shaded" class="issue-link" data-issue-key="STORM-538"><del>STORM-538</del></a>: Also shade com.google.thirdparty.publicsuffix from Guava</p>

<p>    Change storm-core/pom.xml to also relocate com.google.thirdparty.publicsuffix<br/>
    package to org.apache.storm.guava</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/Dictanova/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/Dictanova/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-538" title="Guava com.google.thirdparty.publicsuffix is not shaded" class="issue-link" data-issue-key="STORM-538"><del>STORM-538</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/299.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/299.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #299</p>

<hr />
<p>commit dc94bf47886c2c7b80f9eff8feec8054f6b9d43f<br/>
Author: Damien Raude-Morvan <drazzib@drazzib.com><br/>
Date:   2014-10-20T23:05:36Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-538" title="Guava com.google.thirdparty.publicsuffix is not shaded" class="issue-link" data-issue-key="STORM-538"><del>STORM-538</del></a>: Also shade com.google.thirdparty.publicsuffix from Guava</p>

<p>    Change storm-core/pom.xml to also relocate com.google.thirdparty.publicsuffix<br/>
    package to org.apache.storm.guava</p>

<p>commit aae64a0b71ca5bf524bf38542afd43ae6f785252<br/>
Author: Damien Raude-Morvan <drazzib@drazzib.com><br/>
Date:   2014-10-20T23:13:33Z</p>

<p>    Merge branch 'master' into <a href="https://issues.apache.org/jira/browse/STORM-538" title="Guava com.google.thirdparty.publicsuffix is not shaded" class="issue-link" data-issue-key="STORM-538"><del>STORM-538</del></a></p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/299#issuecomment-59982176" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/299#issuecomment-59982176</a></p>

<p>    +1</p>

<p>    targeted for 0.9.3-rc2</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Merged into master. Thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/299" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/299</a></p>
