### ISSUE TITLE
[STORM-550] get an error when use "--config" option to override config file

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4391]
<div class="code panel" style="border-style: solid;border-width: 1px;"><div class="codeHeader panelHeader" style="border-bottom-width: 1px;border-bottom-style: solid;"><b>Utils.java</b></div><div class="codeContent panelContent">
<pre class="code-java">Index: src/jvm/backtype/storm/utils/Utils.java
===================================================================
--- src/jvm/backtype/storm/utils/Utils.java	(revision 4021)
+++ src/jvm/backtype/storm/utils/Utils.java	(working copy)
@@ -19,7 +19,10 @@
 
 <span class="code-keyword">import</span> java.io.ByteArrayInputStream;
 <span class="code-keyword">import</span> java.io.ByteArrayOutputStream;
+<span class="code-keyword">import</span> java.io.File;
+<span class="code-keyword">import</span> java.io.FileNotFoundException;
 <span class="code-keyword">import</span> java.io.FileOutputStream;
+<span class="code-keyword">import</span> java.io.FileInputStream;
 <span class="code-keyword">import</span> java.io.IOException;
 <span class="code-keyword">import</span> java.io.InputStream;
 <span class="code-keyword">import</span> java.io.InputStreamReader;
@@ -31,6 +34,7 @@
 <span class="code-keyword">import</span> java.nio.channels.Channels;
 <span class="code-keyword">import</span> java.nio.channels.WritableByteChannel;
 <span class="code-keyword">import</span> java.util.ArrayList;
+<span class="code-keyword">import</span> java.util.Collections;
 <span class="code-keyword">import</span> java.util.Enumeration;
 <span class="code-keyword">import</span> java.util.HashMap;
 <span class="code-keyword">import</span> java.util.HashSet;
@@ -44,6 +48,7 @@
 
 <span class="code-keyword">import</span> backtype.storm.serialization.DefaultSerializationDelegate;
 <span class="code-keyword">import</span> backtype.storm.serialization.SerializationDelegate;
+
 <span class="code-keyword">import</span> org.apache.curator.framework.CuratorFramework;
 <span class="code-keyword">import</span> org.apache.curator.framework.CuratorFrameworkFactory;
 <span class="code-keyword">import</span> org.apache.commons.lang.StringUtils;
@@ -121,6 +126,27 @@
     <span class="code-keyword">throw</span> <span class="code-keyword">new</span> RuntimeException(e);
 }
     }
+    
+	@SuppressWarnings(<span class="code-quote">"unchecked"</span>)
+	<span class="code-keyword">public</span> <span class="code-keyword">static</span> Map<<span class="code-object">String</span>, <span class="code-object">Object</span>> loadConfigFile(<span class="code-object">String</span> file) {
+		Map<<span class="code-object">String</span>, <span class="code-object">Object</span>> result = <span class="code-keyword">new</span> HashMap<<span class="code-object">String</span>, <span class="code-object">Object</span>>();
+		<span class="code-keyword">if</span> (file == <span class="code-keyword">null</span>) {
+			<span class="code-keyword">return</span> result;
+		}
+		Yaml yaml = <span class="code-keyword">new</span> Yaml();
+		InputStream in;
+		<span class="code-keyword">try</span> {
+			in = <span class="code-keyword">new</span> FileInputStream(<span class="code-keyword">new</span> File(file));
+			<span class="code-object">Object</span> obj = yaml.load(in);
+			<span class="code-keyword">if</span> (!(obj <span class="code-keyword">instanceof</span> Map)) {
+				<span class="code-keyword">return</span> Collections.<<span class="code-object">String</span>, <span class="code-object">Object</span>> emptyMap();
+			}
+			result = (Map<<span class="code-object">String</span>, <span class="code-object">Object</span>>) obj;
+		} <span class="code-keyword">catch</span> (FileNotFoundException e) {
+			<span class="code-keyword">throw</span> <span class="code-keyword">new</span> RuntimeException(e);
+		}
+		<span class="code-keyword">return</span> result;
+	}
 
     <span class="code-keyword">public</span> <span class="code-keyword">static</span> Map findAndReadConfigFile(<span class="code-object">String</span> name, <span class="code-object">boolean</span> mustExist) {
 <span class="code-keyword">try</span> {
@@ -187,7 +213,7 @@
 <span class="code-keyword">if</span> (confFile==<span class="code-keyword">null</span> || confFile.equals("")) {
     storm = findAndReadConfigFile(<span class="code-quote">"storm.yaml"</span>, <span class="code-keyword">false</span>);
 } <span class="code-keyword">else</span> {
-    storm = findAndReadConfigFile(confFile, <span class="code-keyword">true</span>);
+    storm = loadConfigFile(confFile);
 }
 ret.putAll(storm);
 ret.putAll(readCommandLineOpts());
</pre>
</div></div>

<p>bin/storm --config ~/deploy/storm-conf/storm.yaml  supervisor </p>

<div class="code panel" style="border-style: solid;border-width: 1px;"><div class="codeHeader panelHeader" style="border-bottom-width: 1px;border-bottom-style: solid;"><b>Could not find config file on classpath</b></div><div class="codeContent panelContent">
<pre class="code-java">Exception in thread <span class="code-quote">"main"</span> java.lang.ExceptionInInitializerError
	at java.lang.<span class="code-object">Class</span>.forName0(Native Method)
	at java.lang.<span class="code-object">Class</span>.forName(<span class="code-object">Class</span>.java:171)
	at backtype.storm.config$loading__4910__auto__.invoke(config.clj:17)
	at backtype.storm.config__init.load(Unknown Source)
	at backtype.storm.config__init.<clinit>(Unknown Source)
	at java.lang.<span class="code-object">Class</span>.forName0(Native Method)
	at java.lang.<span class="code-object">Class</span>.forName(<span class="code-object">Class</span>.java:249)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5417)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:621)
	at clojure.core$use.doInvoke(core.clj:5507)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at backtype.storm.daemon.common$loading__4910__auto__.invoke(common.clj:16)
	at backtype.storm.daemon.common__init.load(Unknown Source)
	at backtype.storm.daemon.common__init.<clinit>(Unknown Source)
	at java.lang.<span class="code-object">Class</span>.forName0(Native Method)
	at java.lang.<span class="code-object">Class</span>.forName(<span class="code-object">Class</span>.java:249)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5336)
	at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
	at clojure.core$load_lib.doInvoke(core.clj:5374)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$load_libs.doInvoke(core.clj:5417)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:621)
	at clojure.core$use.doInvoke(core.clj:5507)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at backtype.storm.daemon.supervisor$loading__4910__auto__.invoke(supervisor.clj:16)
	at backtype.storm.daemon.supervisor__init.load(Unknown Source)
	at backtype.storm.daemon.supervisor__init.<clinit>(Unknown Source)
	at java.lang.<span class="code-object">Class</span>.forName0(Native Method)
	at java.lang.<span class="code-object">Class</span>.forName(<span class="code-object">Class</span>.java:249)
	at clojure.lang.RT.loadClassForName(RT.java:2098)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:415)
	at backtype.storm.daemon.supervisor.<clinit>(Unknown Source)
Caused by: java.lang.RuntimeException: Could not find config file on classpath /home/caokun/deploy/storm-conf/storm.yaml
	at backtype.storm.utils.Utils.findAndReadConfigFile(Utils.java:129)
	at backtype.storm.utils.Utils.readStormConfig(Utils.java:190)
	at backtype.storm.utils.Utils.<clinit>(Utils.java:71)
	... 57 more
Could not find the main class: backtype.storm.daemon.supervisor.  Program will exit.
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="caofangkun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-550" target="_blank">get an error when use "--config" option to override config file</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="caofangkun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2015-10-09T02:27:52+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user caofangkun opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/310" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-550" title="get an error when use "--config" option to override config file" class="issue-link" data-issue-key="STORM-550"><del>STORM-550</del></a>:fix bug get an error when use --config option to override conf...</p>

<p>    fix bug get an error when use --config option to override conf...</p>

<p>    bin/storm --config ~/deploy/storm-conf/user.yamls  supervisor</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/caofangkun/apache-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/caofangkun/apache-storm</a> storm-550</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/310.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #310</p>

<hr />
<p>commit dd944de09ef30b45306ba3a69b660e6adc8697b7<br/>
Author: caofangkun <caofangkun@gmail.com><br/>
Date:   2014-11-11T06:35:07Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-550" title="get an error when use "--config" option to override config file" class="issue-link" data-issue-key="STORM-550"><del>STORM-550</del></a>:fix bug get an error when use --config option to override config file</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/310#discussion_r20134376" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310#discussion_r20134376</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/utils/Utils.java &#8212;<br/>
    @@ -121,6 +126,27 @@ public static void sleep(long millis) </p>
{
 throw new RuntimeException(e);
     }
<p> }<br/>
    +    <br/>
    +	@SuppressWarnings("unchecked")<br/>
    +	public static Map<String, Object> loadConfigFile(String file) {<br/>
    +		Map<String, Object> result = new HashMap<String, Object>();<br/>
    +		if (file == null) {<br/>
    +			return result;<br/>
    &#8212; End diff &#8211;</p>

<p>    Shouldn't this throw a RunTime exception? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/310#discussion_r20134395" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310#discussion_r20134395</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/utils/Utils.java &#8212;<br/>
    @@ -121,6 +126,27 @@ public static void sleep(long millis) </p>
{
 throw new RuntimeException(e);
     }
<p> }<br/>
    +    <br/>
    +	@SuppressWarnings("unchecked")<br/>
    +	public static Map<String, Object> loadConfigFile(String file) {<br/>
    +		Map<String, Object> result = new HashMap<String, Object>();<br/>
    +		if (file == null) </p>
{
    +			return result;
    +		}
<p>    +		Yaml yaml = new Yaml();<br/>
    +		InputStream in;<br/>
    +		try {<br/>
    +			in = new FileInputStream(new File(file));<br/>
    +			Object obj = yaml.load(in);<br/>
    +			if (!(obj instanceof Map)) {<br/>
    &#8212; End diff &#8211;</p>

<p>    Same as above.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user clockfly commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/310#issuecomment-62510083" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310#issuecomment-62510083</a></p>

<p>    Seems this is duplicate of <a href="https://issues.apache.org/jira/browse/STORM-188" title="Allow user to specify full configuration path when running storm command" class="issue-link" data-issue-key="STORM-188"><del>STORM-188</del></a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user caofangkun commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/310#discussion_r20135808" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310#discussion_r20135808</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/utils/Utils.java &#8212;<br/>
    @@ -121,6 +126,27 @@ public static void sleep(long millis) </p>
{
 throw new RuntimeException(e);
     }
<p> }<br/>
    +    <br/>
    +	@SuppressWarnings("unchecked")<br/>
    +	public static Map<String, Object> loadConfigFile(String file) {<br/>
    +		Map<String, Object> result = new HashMap<String, Object>();<br/>
    +		if (file == null) {<br/>
    +			return result;<br/>
    &#8212; End diff &#8211;</p>

<p>    Any wrong in this way?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/310#issuecomment-63493192" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310#issuecomment-63493192</a></p>

<p>    This is a duplicate of <a href="https://issues.apache.org/jira/browse/STORM-188" title="Allow user to specify full configuration path when running storm command" class="issue-link" data-issue-key="STORM-188"><del>STORM-188</del></a> as @clockfly suggested.  This patch has a regression, in that it does not search the classpath for the --config option.  I don't expect there are many people using this functionality, but I would rather not regress if possible. STROM-188 looks to be a lot closer to a fully functional patch, so I would rather go with that.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user caofangkun commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/310#issuecomment-63588709" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310#issuecomment-63588709</a></p>

<p>    duplicate of <a href="https://issues.apache.org/jira/browse/STORM-188" title="Allow user to specify full configuration path when running storm command" class="issue-link" data-issue-key="STORM-188"><del>STORM-188</del></a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user caofangkun closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/310" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/310</a></p>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-188">STORM-188</a>]</i>
