### ISSUE TITLE
[STORM-582] Nimbus Halt with FileNotFoundException: '../nimbus/../stormconf.ser' dose not exists

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4423]
<p> To notice, it is different from <a href="https://issues.apache.org/jira/browse/STORM-130" title="[Storm 0.8.2]: java.io.FileNotFoundException: File &#39;../stormconf.ser&#39; does not exist" class="issue-link" data-issue-key="STORM-130"><del>STORM-130</del></a>. It is nimbus to halt. We ran into this problem several times, every time it happens is after several days of stable running. Here is the stacktrace<br/>
======================================================<br/>
2014-11-03 14:30:56 b.s.d.nimbus <span class="error">&#91;INFO&#93;</span> Cleaning inbox ... deleted: stormjar-c1c856f0-cf8b-4299-9c20-712f169802b7.jar<br/>
2014-11-12 19:32:33 b.s.d.nimbus <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.io.FileNotFoundException: File '/tmp/storm-0.9.3/nimbus/stormdist/DNSAnalyse-7-1414992073/stormconf.ser' does not exist<br/>
at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1763) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at backtype.storm.daemon.nimbus$read_storm_conf.invoke(nimbus.clj:89) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
at backtype.storm.daemon.nimbus$read_topology_details.invoke(nimbus.clj:324) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
at backtype.storm.daemon.nimbus$mk_assignments$iter_<em>3100</em><em>3104$fn</em>_3105.invoke(nimbus.clj:649) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
at clojure.lang.LazySeq.sval(LazySeq.java:42) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.LazySeq.seq(LazySeq.java:60) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RT.seq(RT.java:484) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$seq.invoke(core.clj:133) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core.protocols$fn__6026.invoke(protocols.clj:54) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core.protocols$fn_<em>5979$G</em><em>5974</em>_5992.invoke(protocols.clj:13) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$reduce.invoke(core.clj:6177) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$into.invoke(core.clj:6229) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:648) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:410) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.nimbus$fn_<em>3281$exec_fn</em><em>1205</em><em>auto</em>__<em>3282$fn</em><em>3287$fn</em>_3288.invoke(nimbus.clj:907) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
at backtype.storm.daemon.nimbus$fn_<em>3281$exec_fn</em><em>1205</em><em>auto</em>__<em>3282$fn</em>_3287.invoke(nimbus.clj:906) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
at backtype.storm.timer$schedule_recurring$this__2169.invoke(timer.clj:99) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
at backtype.storm.timer$mk_timer$fn_<em>2152$fn</em>_2153.invoke(timer.clj:50) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span> <br/>
at backtype.storm.timer$mk_timer$fn__2152.invoke(timer.clj:42) <span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:679) <span class="error">&#91;na:1.6.0_22&#93;</span><br/>
2014-11-12 19:32:33 b.s.util <span class="error">&#91;INFO&#93;</span> Halting process: ("Error when processing an event")<br/>
2014-11-12 19:32:33 b.s.d.nimbus <span class="error">&#91;INFO&#93;</span> Shutting down master<br/>
=====================================================<br/>
To notice, after stable running for 9 days, without printing "Clean up </p>
{storm-id}
<p>" logs, nimbus halt.</p>

---
<details><summary><i>Originally reported by <a title="Jiahong Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Gvain">Gvain</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-582" target="_blank">Nimbus Halt with FileNotFoundException: '../nimbus/../stormconf.ser' dose not exists</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Harsha" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-06-22T05:58:57+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Gvain" class="user-hover" rel="Gvain">Jiahong Li</a> any reason for you to use /tmp for storm-local dir? . Also check if TMPTIME is set whcih can cause tmp directory to be cleaned up by the OS  automatically. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scooler">scooler</a>:</i>
<p>it's also happen in storm-0.9.3<br/>
=============================================================<br/>
2014-12-16T20:23:33.956+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Downloading code for storm id tv-five-minute-51-1418663725 from /opt/data/goldmine/storm/local-dir/nimbus/stormdist/tv-five-minute-51-1418663725<br/>
2014-12-16T20:23:38.914+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Finished downloading code for storm id tv-five-minute-51-1418663725 from /opt/data/goldmine/storm/local-dir/nimbus/stormdist/tv-five-minute-51-1418663725<br/>
2014-12-16T20:23:38.961+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Launching worker with command: '/usr/local/java/jdk/default/bin/java' '-server' '-Xms1536m' '-Xmx1536m' '-XX:NewSize=256m' '-XX:MaxNewSize=256m' '-XX:PermSize=128M' '-XX:+UseConcMarkSweepGC' '-XX:CMSInitiatingOccupancyFraction=70' '-XX:+PrintGCDetails' '-XX:+PrintGCDateStamps' '-XX:+PrintTenuringDistribution' '-Xloggc:/opt/data/goldmine/storm/logs/gc.log' '-Djava.awt.headless=true' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:HeapDumpPath=/opt/data/goldmine/storm/logs/gc_dump' '-Djava.library.path=/opt/data/goldmine/storm/local-dir/supervisor/stormdist/tv-five-minute-51-1418663725/resources/Linux-amd64:/opt/data/goldmine/storm/local-dir/supervisor/stormdist/tv-five-minute-51-1418663725/resources:/usr/local/lib:/usr/lib' '-Dlogfile.name=worker-6702.log' '-Dstorm.home=/usr/local/goldmine/storm/apache-storm-0.9.3' '-Dstorm.conf.file=' '-Dstorm.options=' '-Dstorm.log.dir=/opt/data/goldmine/storm/logs' '-Dlogback.configurationFile=/usr/local/goldmine/storm/apache-storm-0.9.3/logback/cluster.xml' '-Dstorm.id=tv-five-minute-51-1418663725' '-Dworker.id=8cb0ef9e-a02a-4a71-8766-f5fd9b62931f' '-Dworker.port=6702' '-cp' '/usr/local/goldmine/storm/apache-storm-0.9.3/lib/clj-stacktrace-0.2.2.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/commons-logging-1.1.3.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/clojure-1.5.1.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/ring-servlet-0.3.11.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/kryo-2.21.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/ring-core-1.1.5.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/reflectasm-1.07-shaded.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/commons-codec-1.6.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/math.numeric-tower-0.0.1.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/joda-time-2.0.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/carbonite-1.4.0.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/slf4j-api-1.7.5.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/jetty-util-6.1.26.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/json-simple-1.1.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/core.incubator-0.1.0.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/jetty-6.1.26.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/storm-core-0.9.3.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/ring-jetty-adapter-0.3.11.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/commons-fileupload-1.2.1.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/tools.macro-0.1.0.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/logback-classic-1.0.13.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/hiccup-0.3.6.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/logback-core-1.0.13.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/tools.cli-0.2.4.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/ring-devel-0.3.11.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/snakeyaml-1.11.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/chill-java-0.3.5.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/asm-4.0.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/servlet-api-2.5.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/minlog-1.2.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/log4j-over-slf4j-1.6.6.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/jline-2.11.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/tools.logging-0.2.3.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/clj-time-0.4.1.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/jgrapht-core-0.9.0.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/disruptor-2.10.1.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/commons-exec-1.1.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/objenesis-1.2.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/commons-lang-2.5.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/commons-io-2.4.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/clout-1.0.1.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/lib/compojure-1.1.3.jar:/usr/local/goldmine/storm/apache-storm-0.9.3/conf:/opt/data/goldmine/storm/local-dir/supervisor/stormdist/tv-five-minute-51-1418663725/stormjar.jar' 'backtype.storm.daemon.worker' 'tv-five-minute-51-1418663725' '7d010127-4adb-4f72-8928-136e30d1a7ec' '6702' '8cb0ef9e-a02a-4a71-8766-f5fd9b62931f'<br/>
2014-12-16T20:23:40.466+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:40.966+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:41.467+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:41.967+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:42.468+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:42.969+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:43.469+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:43.970+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:44.471+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:23:44.972+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f still hasn't started<br/>
2014-12-16T20:39:53.668+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down and clearing state for id 8cb0ef9e-a02a-4a71-8766-f5fd9b62931f. Current supervisor time: 1418733593. State: :timed-out, Heartbeat: #backtype.storm.daemon.common.WorkerHeartbeat{:time-secs 1418733561, :storm-id "tv-five-minute-51-1418663725", :executors #</p>
{[395 395] [-1 -1] [113 127]}
<p>, :port 6702}<br/>
2014-12-16T20:39:53.669+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down 7d010127-4adb-4f72-8928-136e30d1a7ec:8cb0ef9e-a02a-4a71-8766-f5fd9b62931f<br/>
2014-12-16T20:39:53.672+0800 b.s.util <span class="error">&#91;INFO&#93;</span> Error when trying to kill 2465. Process is probably already dead.<br/>
2014-12-16T20:39:53.995+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Removing code for storm id tv-five-minute-51-1418663725<br/>
2014-12-16T20:39:54.675+0800 b.s.util <span class="error">&#91;INFO&#93;</span> Error when trying to kill 2465. Process is probably already dead.<br/>
2014-12-16T20:39:54.685+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shut down 7d010127-4adb-4f72-8928-136e30d1a7ec:8cb0ef9e-a02a-4a71-8766-f5fd9b62931f<br/>
2014-12-16T20:39:54.689+0800 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Launching worker with assignment #backtype.storm.daemon.supervisor.LocalAssignment{:storm-id "tv-five-minute-51-1418663725", :executors (<span class="error">&#91;395 395&#93;</span> <span class="error">&#91;113 127&#93;</span>)} for this supervisor 7d010127-4adb-4f72-8928-136e30d1a7ec on port 6702 with id e88d43de-e80b-4c2f-ad5f-a9ae5b4d5e45<br/>
2014-12-16T20:39:54.699+0800 b.s.event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.io.FileNotFoundException: File '/opt/data/goldmine/storm/local-dir/supervisor/stormdist/tv-five-minute-51-1418663725/stormconf.ser' does not exist<br/>
at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1763) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at backtype.storm.config$read_supervisor_storm_conf.invoke(config.clj:212) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.daemon.supervisor$fn__4256.invoke(supervisor.clj:509) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.MultiFn.invoke(MultiFn.java:241) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.supervisor$sync_processes$iter_<em>4116</em><em>4120$fn</em>_4121.invoke(supervisor.clj:285) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.LazySeq.sval(LazySeq.java:42) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.LazySeq.seq(LazySeq.java:60) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RT.seq(RT.java:484) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$seq.invoke(core.clj:133) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$dorun.invoke(core.clj:2780) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$doall.invoke(core.clj:2796) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:273) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:397) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2467.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span></p>

<p>===================================================================================<br/>
after removing code for storm id tv-five-minute-51-1418663725<br/>
supervisor logs "Launching worker with assignment......",then throw exception "FileNotFoundException" and supervisor dead</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patelmanishkumar">patelmanishkumar</a>:</i>
<p>we are facing same issue on our cluster environment and need immediate assistance on how to solve this? <br/>
1) Is there way to clean all temp data or logs and restart the storm cluster?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patelmanishkumar" class="user-hover" rel="patelmanishkumar">Manishkumar</a> this is fixed in 0.9.4 . Meanwhile you can configure supervisord to restart in case your supervisors crashes. Once the supervisor restarted it will properly download topology jar and launch workers without any issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patelmanishkumar">patelmanishkumar</a>:</i>
<p>How can I configure to restart the supervisors after crash. Usually, I restart using storm commands.</p>

<p>Currently I tried restarting whole cluster and I am still getting same errors. I tried several time without any luck. This is production environment and I really need to get it up and running.<br/>
on Nimbus, I get below error:<br/>
nimbus.log:java.io.FileNotFoundException: File '/home/nyicstp/batch/storm/temp/nimbus/s1427051518/stormconf.ser</p>

<p>and on Supervisors, I get below errors: <br/>
../storm-0.9.0-rc3/logs/supervisor.log:java.lang.RuntimeException: org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused<br/>
../storm-0.9.0-rc3/logs/supervisor.log:Caused by: org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused<br/>
../storm-0.9.0-rc3/logs/supervisor.log:Caused by: java.net.ConnectException: Connection refused</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patelmanishkumar" class="user-hover" rel="patelmanishkumar">Manishkumar</a> try following these instructions <a href="http://docs.hortonworks.com/HDPDocuments/Ambari-1.6.1.0/bk_ambari_reference/content/ch_config_storm_supervision.xml.html" class="external-link" target="_blank" rel="nofollow noopener">http://docs.hortonworks.com/HDPDocuments/Ambari-1.6.1.0/bk_ambari_reference/content/ch_config_storm_supervision.xml.html</a> . They might not apply exactly to your env. More about supervisord <a href="http://supervisord.org/" class="external-link" target="_blank" rel="nofollow noopener">http://supervisord.org/</a> . Ask in mailing list will be helpful than in jira.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patelmanishkumar">patelmanishkumar</a>:</i>
<p>Thanks for your help. is there way to get rid of the error without updating the configuration you mentioned above. Above URL will help me preventing in the future. How can I get my storm up and running for the issues I am facing now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patelmanishkumar">patelmanishkumar</a>:</i>
<p>I was able to resolve this issue by deleting storm temp folder on nimbus and all supervisor and also deleting everything (except myid) under zookeeper data folder.</p>
