### ISSUE TITLE
[STORM-586] Trident kafka spout fails instead of updating offset when kafka offset is out of range.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4427]
<p>Trident KafkaEmitter does not catch the newly added UpdateOffsetException which results in the spout failing repeatedly instead of automatically updating the offset to earliest time. </p>

<p>PROBLEM:  Exception while using the Trident Kafka Spout.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2014-12-04 18:38:03 b.s.util ERROR Async loop died! 
java.lang.RuntimeException: storm.kafka.UpdateOffsetException 
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:107) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:78) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:77) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at backtype.storm.daemon.executor$fn_4195$fn4207$fn_4254.invoke(executor.clj:745) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at backtype.storm.util$async_loop$fn__442.invoke(util.clj:436) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at clojure.lang.AFn.run(AFn.java:24) clojure-1.4.0.jar:na 
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) na:1.7.0_71 
Caused by: storm.kafka.UpdateOffsetException: <span class="code-keyword">null</span> 
at storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:186) ~stormjar.jar:na 
at storm.kafka.trident.TridentKafkaEmitter.fetchMessages(TridentKafkaEmitter.java:132) ~stormjar.jar:na 
at storm.kafka.trident.TridentKafkaEmitter.doEmitNewPartitionBatch(TridentKafkaEmitter.java:113) ~stormjar.jar:na 
at storm.kafka.trident.TridentKafkaEmitter.failFastEmitNewPartitionBatch(TridentKafkaEmitter.java:72) ~stormjar.jar:na 
at storm.kafka.trident.TridentKafkaEmitter.access$400(TridentKafkaEmitter.java:46) ~stormjar.jar:na 
at storm.kafka.trident.TridentKafkaEmitter$2.emitPartitionBatchNew(TridentKafkaEmitter.java:233) ~stormjar.jar:na 
at storm.kafka.trident.TridentKafkaEmitter$2.emitPartitionBatchNew(TridentKafkaEmitter.java:225) ~stormjar.jar:na 
at storm.trident.spout.PartitionedTridentSpoutExecutor$Emitter$1.init(PartitionedTridentSpoutExecutor.java:125) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at storm.trident.topology.state.RotatingTransactionalState.getState(RotatingTransactionalState.java:83) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at storm.trident.topology.state.RotatingTransactionalState.getStateOrCreate(RotatingTransactionalState.java:110) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at storm.trident.spout.PartitionedTridentSpoutExecutor$Emitter.emitBatch(PartitionedTridentSpoutExecutor.java:121) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:82) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:369) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at backtype.storm.daemon.executor$fn_4195$tuple_action_fn_4197.invoke(executor.clj:630) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at backtype.storm.daemon.executor$mk_task_receiver$fn__4118.invoke(executor.clj:398) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at backtype.storm.disruptor$clojure_handler$reify__723.onEvent(disruptor.clj:58) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:99) ~storm-core-0.9.1.2.1.7.0-784.jar:0.9.1.2.1.7.0-784 
... 6 common frames omitted 
2014-12-04 18:38:03 b.s.d.executor ERROR 
java.lang.RuntimeException: storm.kafka.UpdateOffsetException 
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:107) ~[storm-core-0.9.1.2.1.7.0
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Parth Brahmbhatt" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-586" target="_blank">Trident kafka spout fails instead of updating offset when kafka offset is out of range.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Parth Brahmbhatt" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-12-28T04:54:53+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Parth-Brahmbhatt opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339</a></p>

<p>     <a href="https://issues.apache.org/jira/browse/STORM-586" title="Trident kafka spout fails instead of updating offset when kafka offset is out of range." class="issue-link" data-issue-key="STORM-586"><del>STORM-586</del></a>: TridentKafkaEmitter should catch updateOffsetException.</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/Parth-Brahmbhatt/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/Parth-Brahmbhatt/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-586" title="Trident kafka spout fails instead of updating offset when kafka offset is out of range." class="issue-link" data-issue-key="STORM-586"><del>STORM-586</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/339.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #339</p>

<hr />
<p>commit 65e9f0c814b2cddc772880042259b66194fd6fb7<br/>
Author: Parth Brahmbhatt <brahmbhatt.parth@gmail.com><br/>
Date:   2014-12-05T22:48:34Z</p>

<p>     <a href="https://issues.apache.org/jira/browse/STORM-586" title="Trident kafka spout fails instead of updating offset when kafka offset is out of range." class="issue-link" data-issue-key="STORM-586"><del>STORM-586</del></a>: TridentKafkaEmitter should catch updateOffsetException.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339#discussion_r21414360" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339#discussion_r21414360</a></p>

<p>    &#8212; Diff: external/storm-kafka/src/jvm/storm/kafka/UpdateOffsetException.java &#8212;<br/>
    @@ -17,6 +17,9 @@<br/>
      */<br/>
     package storm.kafka;</p>

<p>    -public class UpdateOffsetException extends RuntimeException {<br/>
    &#8212; End diff &#8211;</p>

<p>    I think UpdateOffsetException shouldn't extend FailedFetchException . They meant to be different exceptions . The problem here is if a method throws UpdateOffsetException and there is a catch for FailedFetchException its get caught in that catch but we want to have different behavior for FailedFetchException and UpdateOffsetException. Also UpdateOffsetException can be named differently, may be TopicOffsetOutOfRangeException and for any other errors use FailedFetchException.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339#discussion_r21495048" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339#discussion_r21495048</a></p>

<p>    &#8212; Diff: external/storm-kafka/src/jvm/storm/kafka/UpdateOffsetException.java &#8212;<br/>
    @@ -17,6 +17,9 @@<br/>
      */<br/>
     package storm.kafka;</p>

<p>    -public class UpdateOffsetException extends RuntimeException {<br/>
    &#8212; End diff &#8211;</p>

<p>    Renaming done. I feel TopicOffsetOutOfRangeException is just another cause for a fetchFailedException so I created a "is a" relationship but on second thoughts you are right. The caller will have a better experience if it had a retriable and non retryable exception that it does not accidently handle in the same catch block. Reverted back to using RunTimeException.  </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339#issuecomment-66206449" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339#issuecomment-66206449</a></p>

<p>    I also tested this locally and it works fine for OpaqueTridentSpout. The TransactionalSpout tries to reemit a batch and when the offset is out of range there is no way to actually do this. I have defaulted the behavior to empty batch so topology can make progress instead of getting stuck. Let me know if you think it is better to let the user control this and I can add a config value.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/339" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339#issuecomment-66829121" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339#issuecomment-66829121</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339#issuecomment-67527319" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339#issuecomment-67527319</a></p>

<p>    Thanks @Parth-Brahmbhatt  overall it looks good to me. +1. I'll give a day or two before I merge this in. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nathanmarz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339#issuecomment-67581379" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339#issuecomment-67581379</a></p>

<p>    -1</p>

<p>    Why are offset out of range exceptions happening when re-emitting a batch? That shouldn't be possible so I'd like to know why this is happening.</p>

<p>    Emitting a different batch than the first time actually breaks the contract of transactional spouts – which is unacceptable (though it's fine for opaque transactional spouts). Because it breaks the contract of transactional spouts, it would be better to just error repeatedly than silently do the wrong thing.</p>

<p>    The part of this code that catches the error and emits an empty batch for the same batch id should only be applied towards the opaque spout. Additionally, by better understanding why those offset out of range exceptions are happening, there may be an alternative solution that doesn't involve breaking the contract of transactional spouts.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339#issuecomment-67593637" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339#issuecomment-67593637</a></p>

<p>    @nathanmarz  there is another case where your topology is running and processed all the existing data and there is no new data came into kafka topic which could cause offset out of range.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user nathanmarz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/339#issuecomment-67615349" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339#issuecomment-67615349</a></p>

<p>    Can you elaborate? It should just keep trying that last offset repeatedly. This is a case I tested repeatedly when I originally wrote this, so if this is the case it's a regression.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/372#issuecomment-68871971" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/372#issuecomment-68871971</a></p>

<p>    @Parth-Brahmbhatt  looks like you might have unintended commit as part of this PR.<br/>
    "<a href="https://issues.apache.org/jira/browse/STORM-586" title="Trident kafka spout fails instead of updating offset when kafka offset is out of range." class="issue-link" data-issue-key="STORM-586"><del>STORM-586</del></a>: TridentKafkaEmitter should catch updateOffsetException."</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/339" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/339</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p>PR merged into master. Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=anavalamudi">anavalamudi</a>:</i>
<p>Updated storm version from 0.9.5 to 0.10, but my spout throws storm.kafka.UpdateOffsetException. </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.RuntimeException: storm.kafka.UpdateOffsetException at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:135) at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:106) at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) at backtype.storm.daemon.executor$fn__5694$fn__5707$fn__5758.invoke(executor.clj:819) at backtype.storm.util$async_loop$fn__545.invoke(util.clj:479) at clojure.lang.AFn.run(AFn.java:22) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) Caused by: storm.kafka.UpdateOffsetException at storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:186) at storm.kafka.trident.TridentKafkaEmitter.fetchMessages(TridentKafkaEmitter.java:132) at storm.kafka.trident.TridentKafkaEmitter.doEmitNewPartitionBatch(TridentKafkaEmitter.java:113) at storm.kafka.trident.TridentKafkaEmitter.failFastEmitNewPartitionBatch(TridentKafkaEmitter.java:72) at storm.kafka.trident.TridentKafkaEmitter.emitNewPartitionBatch(TridentKafkaEmitter.java:79) at storm.kafka.trident.TridentKafkaEmitter.access$000(TridentKafkaEmitter.java:46) at storm.kafka.trident.TridentKafkaEmitter$1.emitPartitionBatch(TridentKafkaEmitter.java:204) at storm.kafka.trident.TridentKafkaEmitter$1.emitPartitionBatch(TridentKafkaEmitter.java:194) at storm.trident.spout.OpaquePartitionedTridentSpoutExecutor$Emitter.emitBatch(OpaquePartitionedTridentSpoutExecutor.java:127) at storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:82) at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:370) at backtype.storm.daemon.executor$fn__5694$tuple_action_fn__5696.invoke(executor.clj:690) at backtype.storm.daemon.executor$mk_task_receiver$fn__5615.invoke(executor.clj:436) at backtype.storm.disruptor$clojure_handler$reify__5189.onEvent(disruptor.clj:58) at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:127) ... 6 more
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Marking as resolved since the patch got merged.</p>
