### ISSUE TITLE
[STORM-602] HdfsBolt dies when the hadoop node is not available

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4443]
<p>When the hadoop nodes are not available, HdfsBolt generates the following run time error, and dies and the topology dies with it too.</p>

<p>12154 <span class="error">&#91;Thread-50-hdfsBolt2&#93;</span> ERROR backtype.storm.util - Halting process: ("Worker died")<br/>
java.lang.RuntimeException: ("Worker died")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:319) <span class="error">&#91;storm-core-0.9.3-SNAPSHOT.jar:0.9.3-SNAPSHOT&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.worker$fn_<em>4770$fn</em>_4771.invoke(worker.clj:452) <span class="error">&#91;storm-core-0.9.3-SNAPSHOT.jar:0.9.3-SNAPSHOT&#93;</span><br/>
at backtype.storm.daemon.executor$mk_executor_data$fn_<em>3287$fn</em>_3288.invoke(executor.clj:239) <span class="error">&#91;storm-core-0.9.3-SNAPSHOT.jar:0.9.3-SNAPSHOT&#93;</span><br/>
at backtype.storm.util$async_loop$fn__458.invoke(util.clj:467) <span class="error">&#91;storm-core-0.9.3-SNAPSHOT.jar:0.9.3-SNAPSHOT&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_65&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="clay teahouse" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clayteahouse">clayteahouse</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-602" target="_blank">HdfsBolt dies when the hadoop node is not available</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2016-02-09T14:32:44+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clayteahouse">clayteahouse</a>:</i>
<p>Further information on the issue:<br/>
1) When starting the topology, if the hadoop nodes are not available, you get "worker died" message and HdfsBolt and the entire topology die.<br/>
java.lang.RuntimeException: ("Worker died")<br/>
......<br/>
2) If the topology is running and then the hadoop nodes become unavailable, you get connection refused error. When hadoop nodes become available, the HdfsBolt never recovers. It keeps giving the following error:<br/>
 org.apache.storm.hdfs.bolt.HdfsBolt - write/sync failed.<br/>
 All datanodes ....... are bad. Aborting...<br/>
at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1008) ~<span class="error">&#91;hadoop-hdfs-2.2.0.jar:na&#93;</span><br/>
at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.processDatanodeError(DFSOutputStream.java:823) ~<span class="error">&#91;hadoop-hdfs-2.2.0.jar:na&#93;</span><br/>
at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:475) ~<span class="error">&#91;hadoop-hdfs-2.2.0.jar:na&#93;</span><br/>
If you restart the topology, everything is OK and HdfsBolt can write to the hdfs nodes.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snd">snd</a>:</i>
<p>We're experiencing the same problem, especially the second issue. It seems that updating <tt>hadoop-client</tt> and <tt>hadoop-hdfs</tt> in the <a href="https://github.com/apache/storm/blob/v0.9.3/external/storm-hdfs/pom.xml" class="external-link" target="_blank" rel="nofollow noopener">storm-hdfs pom.xml</a> to <tt>2.5.2</tt> (our Hadoop is Hadoop 2.5.0-cdh5.2.0) fixed the issue.</p>

<p>Could someone verify this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dossett@gmail.com">dossett@gmail.com</a>:</i>
<p>The second problem ("When hadoop nodes become available, the HdfsBolt never recovers.") has been resolved by <a href="https://issues.apache.org/jira/browse/STORM-969" title="HDFS Bolt can end up in an unrecoverable state" class="issue-link" data-issue-key="STORM-969"><del>STORM-969</del></a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dossett@gmail.com">dossett@gmail.com</a>:</i>
<p>If nobody objects, I will close this ticket as "not a problem" based on my previous comment.</p>
