### ISSUE TITLE
[STORM-603] storm-kafka: Log errors when missing required configuration fields

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4444]
<p>I was upgrading our topologies to storm-0.9.3 this <a href="https://github.com/apache/storm/commit/2596e335f27a57784a93a57823bd93dde587909f" class="external-link" target="_blank" rel="nofollow noopener">commit</a> introduced a change that threw me for a loop. When submitting my topology I got the following error.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">[main] ERROR storm.kafka.DynamicBrokersReader - Couldn't connect to zookeeper
 java.lang.IllegalArgumentException: Don't know how to convert <span class="code-keyword">null</span> to <span class="code-object">int</span>
 	at backtype.storm.utils.Utils.getInt(Utils.java:301) ~[storm-core-0.9.3.jar:0.9.3]
 	at storm.kafka.DynamicBrokersReader.<init>(DynamicBrokersReader.java:47) ~[gambit-storm-threads-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]
 	at com.pearson.gambit.threads.storm.ThreadsTopology.main(ThreadsTopology.java:45) [gambit-storm-threads-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]
 Exception in thread <span class="code-quote">"main"</span> java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
 	at storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:81)
 	at com.pearson.gambit.threads.storm.ThreadsTopology.main(ThreadsTopology.java:48)
 Caused by: java.lang.RuntimeException: java.lang.NullPointerException
 	at storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:94)
 	at storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:65)
 	... 1 more
 Caused by: java.lang.NullPointerException
 	at storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:91)
 	... 2 more 
</pre>
</div></div>

<p>It took me a while to figure out that this error stems from missing the </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">backtype.storm.Config.STORM_ZOOKEEPER_CONNECTION_TIMEOUT</pre>
</div></div>
<p> property in the conf map provided to the </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">storm.kafka.DynamicBrokersReader</pre>
</div></div>
<p> constructer. It would be nice to check the required configuration parameters and throw a RuntimeException if any are missing. </p>

---
<details><summary><i>Originally reported by <a title="Curtis Allen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=curtissallen">curtissallen</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-603" target="_blank">storm-kafka: Log errors when missing required configuration fields</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Curtis Allen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=curtissallen">curtissallen</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-05-04T20:20:23+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user curtisallen opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-603" title="storm-kafka: Log errors when missing required configuration fields" class="issue-link" data-issue-key="STORM-603"><del>STORM-603</del></a> Log errors when required kafka params are missing</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-603" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-603</a></p>

<p>    I was upgrading our topologies to storm-0.9.3 this <span class="error">&#91;commit&#93;</span>(<a href="https://github.com/apache/storm/commit/2596e335f27a57784a93a57823bd93dde587909f" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/commit/2596e335f27a57784a93a57823bd93dde587909f</a>) introduced a change that threw me for a loop. When submitting my topology I got the following error.<br/>
    ```<br/>
    <span class="error">&#91;main&#93;</span> ERROR storm.kafka.DynamicBrokersReader - Couldn't connect to zookeeper<br/>
     java.lang.IllegalArgumentException: Don't know how to convert null to int<br/>
     	at backtype.storm.utils.Utils.getInt(Utils.java:301) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
     	at storm.kafka.DynamicBrokersReader.<init>(DynamicBrokersReader.java:47) ~<span class="error">&#91;gambit-storm-threads-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na&#93;</span><br/>
     	at com.pearson.gambit.threads.storm.ThreadsTopology.main(ThreadsTopology.java:45) <span class="error">&#91;gambit-storm-threads-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na&#93;</span><br/>
     Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException<br/>
     	at storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:81)<br/>
     	at com.pearson.gambit.threads.storm.ThreadsTopology.main(ThreadsTopology.java:48)<br/>
     Caused by: java.lang.RuntimeException: java.lang.NullPointerException<br/>
     	at storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:94)<br/>
     	at storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:65)<br/>
     	... 1 more<br/>
     Caused by: java.lang.NullPointerException<br/>
     	at storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:91)<br/>
     	... 2 more <br/>
    ```</p>

<p>    It took me a while to figure out that this error stems from missing the `backtype.storm.Config.STORM_ZOOKEEPER_CONNECTION_TIMEOUT` property in the `conf` map provided to the `storm.kafka.DynamicBrokersReader` constructer. It would be nice to check the required configuration parameters and throw a RuntimeException if any are missing. <br/>
    This pull requests adds logging when required errors are missing. </p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/curtisallen/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/curtisallen/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-603" title="storm-kafka: Log errors when missing required configuration fields" class="issue-link" data-issue-key="STORM-603"><del>STORM-603</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/361.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #361</p>

<hr />
<p>commit 326cc1c796d073c768de4b5aced1669bd47c6891<br/>
Author: Curtis Allen <curtis.allen@pearson.com><br/>
Date:   2014-12-23T23:13:31Z</p>

<p>    Log errors when required kafka params are missing</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#discussion_r22435307" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#discussion_r22435307</a></p>

<p>    &#8212; Diff: external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java &#8212;<br/>
    @@ -149,4 +158,19 @@ private Broker getBrokerHost(byte[] contents) {<br/>
     }<br/>
 }</p>

<p>    +    private void validateConfig(final Map conf) {<br/>
    +if(conf.get(Config.STORM_ZOOKEEPER_SESSION_TIMEOUT) == null) {<br/>
    &#8212; End diff &#8211;</p>

<p>    These are all storm configs , even if user didn't pass these or set in storm.yaml there are defaults . So not sure checking for this necessary.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#discussion_r22435341" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#discussion_r22435341</a></p>

<p>    &#8212; Diff: external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java &#8212;<br/>
    @@ -41,6 +41,14 @@<br/>
 private String _topic;</p>

<p> public DynamicBrokersReader(Map conf, String zkStr, String zkPath, String topic) {<br/>
    +// Check required parameters<br/>
    +if(conf == null) </p>
{LOG.error("conf cannot be null");}
<p>    &#8212; End diff &#8211;</p>

<p>    Instead putting it in DynamicBrokersReader it will be better if we have this in KafkaConfig and SpoutConfig and have a validate method there.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user curtisallen commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#discussion_r22474024" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#discussion_r22474024</a></p>

<p>    &#8212; Diff: external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java &#8212;<br/>
    @@ -149,4 +158,19 @@ private Broker getBrokerHost(byte[] contents) {<br/>
     }<br/>
 }</p>

<p>    +    private void validateConfig(final Map conf) {<br/>
    +if(conf.get(Config.STORM_ZOOKEEPER_SESSION_TIMEOUT) == null) {<br/>
    &#8212; End diff &#8211;</p>

<p>    @harshach there are no defaults for these values, hence the reason for this pull request. The constructor for the DynamicBrokerReader accepts a `java.util.Map` Which must contain the values that are verified in this `validateConfig` method.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user curtisallen commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#discussion_r22474338" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#discussion_r22474338</a></p>

<p>    &#8212; Diff: external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java &#8212;<br/>
    @@ -41,6 +41,14 @@<br/>
 private String _topic;</p>

<p> public DynamicBrokersReader(Map conf, String zkStr, String zkPath, String topic) {<br/>
    +// Check required parameters<br/>
    +if(conf == null) </p>
{LOG.error("conf cannot be null");}
<p>    &#8212; End diff &#8211;</p>

<p>    @harshach Agreed. I didn't take that approach because it would require significantly more changes to the spout since `DynamicBrokerReader` doesn't reference `KafkaConfig` or `SpoutConfig` currently. Also it would require a modification to `DynamicBrokerReader`'s constructor to accept a `KafkaConfig` instance breaking legacy code. I thought that would be a big change for a minor storm release.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#issuecomment-97201701" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#issuecomment-97201701</a></p>

<p>    @curtisallen Sorry it has taken so long to review this.  I think the changes look OK.  I am curious why we only logging an error instead of throwing an exception.  Wouldn't we just end up throwing an NPE later on in the code?  Why not fail fast?</p>

<p>    @harshach did @curtisallen answer all of your questions?  Do you have any other follow up?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user curtisallen commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#issuecomment-97487810" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#issuecomment-97487810</a></p>

<p>    @revans2 Thanks for looking at this. Before we didn't throw any exceptions when the config was incorrect. I added this <span class="error">&#91;line&#93;</span>(<a href="https://github.com/curtisallen/storm/blob/STORM-603/external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java#L64" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/curtisallen/storm/blob/STORM-603/external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java#L64</a>) that throws an exception if the config is incorrect. Right now it's a RuntimeException however, would you prefer I throw a null pointer exception earlier? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#issuecomment-97512345" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#issuecomment-97512345</a></p>

<p>    @curtisallen I am not really concerned about it being an NPE, or a RuntimeException, my concern is two fold.  </p>

<p>    First If we mis configure something like Config we log <span class="error">&#91;something&#93;</span>(<a href="https://github.com/curtisallen/storm/blob/STORM-603/external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java#L45" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/curtisallen/storm/blob/STORM-603/external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java#L45</a>) it and then later end up throwing a RuntimeException.  In this case the RuntimeException is wrapping an NPE that will only have the line number of where the NPE happened.  If all we had were the logs to go off of then it would not be a big deal, but in storm the exception and the stack trace often are returned and displayed on the UI.  I would much rather see  "Config cannot be null" on the UI instead of NPE on line 162 of DynamicBrokersReader.</p>

<p>    My second concern is around failing fast.  In the case of _zkPath or _topic being null.  There is nothing that explicitly uses them in the constructor.  The failure will happen much later if ever as is the case for _zkPath and _topic, as they appear to only be used as a part of string concatenation with a +.  Which when done with a null writes "null" to the string instead of throwing an NPE, so we could end up trying to read from "/kafka/topics/null/partitions".</p>

<p>    If something is wrong in a way that we cannot recover from I would much rather throw an exception the moment we know it is wrong rather than log an error and hope that the exception will be thrown later on, or that somehow we will manage to not actually need this config to be set. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user curtisallen commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#issuecomment-97513938" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#issuecomment-97513938</a></p>

<p>    @revans2 agreed, the concerns you brought make a lot of sense to me. I should have some time later this week to fail fast <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/wink.png" height="16" width="16" align="absmiddle" alt="" border="0"/> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#issuecomment-97525358" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#issuecomment-97525358</a></p>

<p>    @curtisallen Thanks.  If you could post a comment here when it is updated I'll take a look and we should hopefully be able to get it in soon.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user curtisallen commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#issuecomment-97934446" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#issuecomment-97934446</a></p>

<p>    @revans2 now we throw NPEs if the values are missing. Leveraged guava's `Preconditions` . Let me know if you need anything else. Thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/361#issuecomment-98820091" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361#issuecomment-98820091</a></p>

<p>    +1 looks great.  Thanks for doing this</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/361" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/361</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=curtissallen" class="user-hover" rel="curtissallen">Curtis Allen</a>,</p>

<p>I merged this into master.  Keep up the good work.</p>
