### ISSUE TITLE
[STORM-605] Attempting to call unbound fn during bolt prepare

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4446]
<p>We had a bunch of topologies running very well under Storm 0.8.2 until last<br/>
week when we switched to storm 0.9.2-incubating. We use the clojure DSL,<br/>
and clojure 1.5.1 (only).</p>

<p>Since the change, we have a large topology (about 30 bolts, parallellism=10<br/>
or 20 per bolt, total 372 tasks on 10 workers) that fails on startup with<br/>
several bolts showing the exception :</p>

<p>java.lang.RuntimeException: java.lang.IllegalStateException: Attempting to<br/>
call unbound fn: #'entry-dedup.bolt/dedup__ at<br/>
backtype.storm.clojure.ClojureBolt.prepare(ClojureBolt.java:77) ...</p>

<p>This can occur on one or several bolts at random and is not consistent<br/>
between restarts.</p>

<p>The topology is indeed quite long to initialize (a dozen seconds) due to several models being loaded but this was OK in 0.8.2.</p>

<p>Another (shorter) topology works most of the time but shows this behaviour<br/>
on some restarts sometimes.</p>

<p>We found a workaround that works most of the time : start the topology in<br/>
the INACTIVE state, then wait 200 seconds, then activate it. But this<br/>
doesn't really solve our problem because sometimes Storm tries to rebalance<br/>
the topologies by itself and reassigns the topology without our little trick, effectively crashing them.</p>

<p>The same behavior is present with storm 0.9.3.</p>

<p>So maybe something changed in storm that introduces a kind of race<br/>
condition during initializaion of some bolts on larger topologies ? Maybe this is a consequence to the switch to Netty ?</p>

---
<details><summary><i>Originally reported by <a title="Philippe Guillebert" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=phyce">phyce</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-605" target="_blank">Attempting to call unbound fn during bolt prepare</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:46+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=newday1">newday1</a>:</i>
<p>i'm the same as you. we use clojureDSL under storm 0.9.2-incubating . we also found that and have no idea.<br/>
we expected this bug can be resolved as soon as possible</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=phyce" class="user-hover" rel="phyce">Philippe Guillebert</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=newday1" class="user-hover" rel="newday1">Li Chaomo</a> If possible can you please provide a sample topology which can reproduce this issue. Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=newday1">newday1</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a> hello, i found something today though i don't know why it was</p>

<p>here is the thing , we use clojure dsl under storm . The bolt always loop died when it run the prepare function,So i guess<br/>
maybe something wrong happen when load the clojure code. Then i build a storm from github mirror, modify the sources and add some log where storm load the clojure bolt</p>

<p>backtype.storm.utils/Utils<br/>
    public static IFn loadClojureFn(String namespace, String name) {<br/>
try </p>
{
    clojure.lang.Compiler.eval(RT.readString("(require '" + namespace + ")"));
}
<p> catch (Exception e) </p>
{
LOG.error("读取clojure bolt代码异常 namespace=" + namespace + ", name=" + name, e);
}
<p>return (IFn) RT.var(namespace, name).deref();<br/>
    }</p>

<p>here is the log when the bolt throw exception</p>

<p>2015-02-09 16:19:02 b.s.u.Utils <span class="error">&#91;ERROR&#93;</span> 读取clojure bolt代码异常 namespace=com.pajk.risk.storm.clj.engine, name=count-bolt__<br/>
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: conditionCache in this context, compiling:(com/pajk/risk/storm/clj/calc.clj:12:13)<br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6464) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6406) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:924) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6445) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
	at clojure.lang.Compiler.analyze(Compiler.java:6445) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span></p>

<p>but i do define the conditionCache in a another clojure file, and i load it by :use , here is my code</p>

<p>(ns com.pajk.risk.storm.clj.calc<br/>
  (:import (java.util Map)<br/>
   (com.pajk.risk.engine.api.model UniformEvent))<br/>
  (:use com.pajk.risk.storm.clj.cache)<br/>
  (:use com.pajk.risk.storm.clj.mock)<br/>
  (:use com.pajk.risk.storm.clj.util)<br/>
  (:require <span class="error">&#91;clojure.tools.logging :as log&#93;</span>))</p>

<p>conditionCache is defined in com.pajk.risk.storm.clj.cache</p>

<p>(def ^LoadingCache conditionCache (-> (CacheBuilder/newBuilder)<br/>
      (.maximumSize 10000)<br/>
      (.build (proxy <span class="error">&#91;CacheLoader&#93;</span> [] (load <span class="error">&#91;^String key&#93;</span><br/>
(AviatorEvaluator/compile key))))))</p>

<p>My question is how the storm load my clojure bolt and how to load its dependency , Thx</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=newday1" class="user-hover" rel="newday1">Li Chaomo</a> Thanks for the details. I'll work on reproducing it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=newday1">newday1</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a> </p>

<p>hi, i found something interesting.<br/>
when i merge all my clj sources to one clj file , it works fine.<br/>
Is this a classpath problem? But it is under the same classpath whether it works fine  or failed</p>

<p>i print my classpath when storm load the prepare method</p>

<p>2015-02-26 11:00:14 b.s.c.ClojureBolt <span class="error">&#91;INFO&#93;</span> Storm开始加载bolt闭包com.pajk.risk.storm.clj.engine_count-bolt__ classpath=/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/ring-devel-1.3<br/>
.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/slf4j-api-1.7.5.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/commons-lang-2.5.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/<br/>
lib/storm-core-0.10.0-SNAPSHOT.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/math.numeric-tower-0.0.1.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/commons-codec-1.6.jar:/ho<br/>
me/admin/apache-storm-0.10.0-SNAPSHOT/lib/crypto-equality-1.0.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/reflectasm-1.07-shaded.jar:/home/admin/apache-storm-0.10.0-SNAPSHO<br/>
T/lib/ns-tracker-0.2.2.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/curator-client-2.4.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/commons-exec-1.1.jar:/home/admin/apac<br/>
he-storm-0.10.0-SNAPSHOT/lib/tools.namespace-0.2.4.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/asm-4.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/chill-java-0.3.5.jar:/<br/>
home/admin/apache-storm-0.10.0-SNAPSHOT/lib/ring-core-1.1.5.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/clj-time-0.8.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/ring-s<br/>
ervlet-1.3.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/httpclient-4.3.3.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jline-2.11.jar:/home/admin/apache-storm-0.10.0-SNAP<br/>
SHOT/lib/hadoop-auth-2.4.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/commons-io-2.4.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/tools.logging-0.2.3.jar:/home/admin/apa<br/>
che-storm-0.10.0-SNAPSHOT/lib/clout-1.0.1.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/compojure-1.1.3.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jetty-security-7.6.13.v<br/>
20130916.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/disruptor-2.10.1.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/servlet-api-2.5.jar:/home/admin/apache-storm-0.10.0-SNA<br/>
PSHOT/lib/jetty-servlets-7.6.13.v20130916.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/objenesis-1.2.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/ring-anti-forgery-1.0.0.j<br/>
ar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jetty-http-7.6.13.v20130916.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/javax.servlet-2.5.0.v201103041518.jar:/home/admin/apac<br/>
he-storm-0.10.0-SNAPSHOT/lib/logback-core-1.0.13.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/clojure-1.6.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/carbonite-1.4.0.ja<br/>
r:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jetty-continuation-7.6.13.v20130916.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/logback-classic-1.0.13.jar:/home/admin/apache-s<br/>
torm-0.10.0-SNAPSHOT/lib/curator-framework-2.4.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/snakeyaml-1.11.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/java.classpath-0.<br/>
2.2.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/ring-jetty-adapter-1.3.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jetty-servlet-7.6.13.v20130916.jar:/home/admin/apach<br/>
e-storm-0.10.0-SNAPSHOT/lib/json-simple-1.1.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/minlog-1.2.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/tools.cli-0.2.4.jar:/home/<br/>
admin/apache-storm-0.10.0-SNAPSHOT/lib/core.incubator-0.1.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/commons-logging-1.1.3.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib<br/>
/crypto-random-1.2.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/kryo-2.21.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/httpcore-4.3.2.jar:/home/admin/apache-storm-0.10.0<br/>
-SNAPSHOT/lib/joda-time-2.3.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jetty-io-7.6.13.v20130916.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/tools.macro-0.1.0.jar:/home<br/>
/admin/apache-storm-0.10.0-SNAPSHOT/lib/log4j-over-slf4j-1.6.6.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jetty-client-7.6.13.v20130916.jar:/home/admin/apache-storm-0.10.0-S<br/>
NAPSHOT/lib/jetty-util-7.6.13.v20130916.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jetty-server-7.6.13.v20130916.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/jgrapht-cor<br/>
e-0.9.0.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/commons-fileupload-1.2.1.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/lib/clj-stacktrace-0.2.7.jar:/home/admin/apache-stor<br/>
m-0.10.0-SNAPSHOT/lib/hiccup-0.3.6.jar:/home/admin/apache-storm-0.10.0-SNAPSHOT/conf:/home/admin/storm/localdir/supervisor/stormdist/risk-engine-4-1424919605/stormjar.jar</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeremyheiler">jeremyheiler</a>:</i>
<p>I've been running into this issue as well. It has been more apparent when we did not AOT compile the project, however, we're now seeing it for external libraries that are AOT compiled. I am not yet convinced that this is a race condition between the loading of clj and class files. Is there any proof for that claim?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeremyheiler" class="user-hover" rel="jeremyheiler">Jeremy Heiler</a> Could you give details on which storm version are you using and you are also seeing the same error as<br/>
" Attempting to<br/>
call unbound fn: #'entry-dedup.bolt/dedup__ at"</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeremyheiler">jeremyheiler</a>:</i>
<p>I'm using Storm 0.9.3 (with Netty). And yes, I am seeing the same "unbound fn" error, of course with different vars.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeremyheiler" class="user-hover" rel="jeremyheiler">Jeremy Heiler</a> If possible can you give us an example topology where you seeing this issue. I tried to reproduce this with example shell topologies I am not seeing any errors or issues with them.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=phyce">phyce</a>:</i>
<p>As far as we can tell, since we upgraded to Storm 0.9.4 we did not reproduce this issue. So maybe it got solved by 0.9.4 as a side effect. Can you guys reproduce once you upgrade to 0.9.4 ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeremyheiler">jeremyheiler</a>:</i>
<p>This is not fixed in 0.9.5, at least for my usage.</p>

<p>However, I had isolated one instance of this error to  a custom spout. It would happen when nextTuple is called for the first time. If I put a try/catch in nextTuple, catching IllegalStateException so that the unbound var error is ignored, it eventually stops happening after ~25 seconds on a 1-spout/4-bolt topology with no parallelism.</p>

<p>What could cause this race condition?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rmangi">rmangi</a>:</i>
<p>A bit more discovery. Taking my bolts and spouts and putting them in the same .clj file seems to have fixed it. This suggests to me that when Utils.loadClojureFn requires the namespace for one, the other isn't also being loaded. There are no references from my bolts to my spouts except in the topology, so maybe it's when the topology is resolved that the problem manifests?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=donlee">donlee</a>:</i>
<p>In my case, streamparse api were used to run locally and submit code to STORM cluster, and  it didn't happen during prepare, when I ran it locally it was ok but when it is submitted to STORM cluster, I got</p>

<p>java.lang.RuntimeException: java.lang.IllegalStateException: Attempting to call unbound fn</p>

<p>clojure version is 1.5.1, storm version is 0.9.5, sparse 2.1.3</p>

<p>the error was due to calling "call-to-outside-function" within spout execute, and that function can be 3rd party library as well, the code is as follows:</p>

<p>(defn call-to-outside-function <span class="error">&#91;someArg&#93;</span><br/>
    (do stuff ....))</p>

<p>(defspout kw-spout <span class="error">&#91;"something"&#93;</span><br/>
  <span class="error">&#91;conf context collector&#93;</span><br/>
(spout<br/>
    (nextTuple []<br/>
(Thread/sleep 100)<br/>
(call-to-outside-function "someArgs")<br/>
(emit-spout! collector ("not important"))<br/>
)<br/>
    (ack <span class="error">&#91;id&#93;</span>)<br/>
    ))</p>

<p>It is related to this bug ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
