### ISSUE TITLE
[STORM-633] Nimbus - HTTP Error 413 full HEAD if using kerberos authentication

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4474]
<p>When trying to access Nimbus that is kerberized, a HTTP 413 full HEAD error is received. This seems related to the issue outlined in <a href="https://issues.apache.org/jira/browse/HADOOP-8816" title="HTTP Error 413 full HEAD if using kerberos authentication" class="issue-link" data-issue-key="HADOOP-8816"><del>HADOOP-8816</del></a>.</p>

<p>Setting the Jetty header buffer size with ring-jetty is outlined on Stackoverflow here: <a href="http://stackoverflow.com/questions/9285096/clojure-ring-using-the-ring-jetty-adapter-large-requests-give-me-a-413-full-h" class="external-link" target="_blank" rel="nofollow noopener">http://stackoverflow.com/questions/9285096/clojure-ring-using-the-ring-jetty-adapter-large-requests-give-me-a-413-full-h</a></p>

<p>The setting could be exposed like the host as done in <a href="https://issues.apache.org/jira/browse/STORM-575" title="Ability to specify Jetty host to bind to" class="issue-link" data-issue-key="STORM-575"><del>STORM-575</del></a>.</p>

---
<details><summary><i>Originally reported by <a title="Kevin Risden" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krisden">krisden</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-633" target="_blank">Nimbus - HTTP Error 413 full HEAD if using kerberos authentication</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Harsha" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-02-23T17:55:41+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><span class="error">&#91;~risdenk&#93;</span> Can you please share the details on how are you configuring storm UI. Storm.yaml would be helpful.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amuise">amuise</a>:</i>
<p>Sri,<br/>
Kevin and I are on the same cluster. Here is the cleansed storm.yaml:</p>


<p>dev.zookeeper.path : '/tmp/dev-storm-zookeeper'<br/>
drpc.childopts : '-Xmx768m -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf'<br/>
drpc.invocations.port : 3773<br/>
drpc.port : 3772<br/>
drpc.queue.size : 128<br/>
drpc.request.timeout.secs : 600<br/>
drpc.worker.threads : 64<br/>
java.library.path : '/usr/local/lib:/opt/local/lib:/usr/lib:/usr/hdp/current/storm-client/lib'<br/>
logviewer.appender.name : 'A1'<br/>
logviewer.childopts : '-Xmx128m -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf'<br/>
logviewer.port : 8000<br/>
nimbus.childopts : '-Xmx1024m -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf -javaagent:/usr/hdp/current/storm-nimbus/contrib/storm-jmxetric/lib/jmxetric-1.0.4.jar=host=ac95edimstr01xxxxxxx,port=8649,wireformat31x=true,mode=multicast,config=/usr/hdp/current/storm-nimbus/contrib/storm-jmxetric/conf/jmxetric-conf.xml,process=Nimbus_JVM   -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf'<br/>
nimbus.cleanup.inbox.freq.secs : 600<br/>
nimbus.file.copy.expiration.secs : 600<br/>
nimbus.host : 'ac95edimstr02xxxxxxxxx'<br/>
nimbus.inbox.jar.expiration.secs : 3600<br/>
nimbus.monitor.freq.secs : 10<br/>
nimbus.reassign : true<br/>
nimbus.supervisor.timeout.secs : 60<br/>
nimbus.task.launch.secs : 120<br/>
nimbus.task.timeout.secs : 30<br/>
nimbus.thrift.max_buffer_size : 1048576<br/>
nimbus.thrift.port : 6627<br/>
nimbus.topology.validator : 'backtype.storm.nimbus.DefaultTopologyValidator'<br/>
storm.cluster.mode : 'distributed'<br/>
storm.local.dir : '/opt/hadoop/storm'<br/>
storm.local.mode.zmq : false<br/>
storm.messaging.netty.buffer_size : 5242880<br/>
storm.messaging.netty.client_worker_threads : 1<br/>
storm.messaging.netty.max_retries : 30<br/>
storm.messaging.netty.max_wait_ms : 1000<br/>
storm.messaging.netty.min_wait_ms : 100<br/>
storm.messaging.netty.server_worker_threads : 1<br/>
storm.messaging.transport : 'backtype.storm.messaging.netty.Context'<br/>
storm.zookeeper.connection.timeout : 15000<br/>
storm.zookeeper.port : 2181<br/>
storm.zookeeper.retry.interval : 1000<br/>
storm.zookeeper.retry.intervalceiling.millis : 30000<br/>
storm.zookeeper.retry.times : 5<br/>
storm.zookeeper.root : '/storm'<br/>
storm.zookeeper.servers : <span class="error">&#91;&#39;ac95edimstr01xxxxxx&#39;,&#39;ac95edimstr02xxxxxxx&#39;,&#39;ac95edidata01xxxxxxxx&#39;&#93;</span><br/>
storm.zookeeper.session.timeout : 20000<br/>
supervisor.childopts : '-Xmx256m -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=56431 -javaagent:/usr/hdp/current/storm-supervisor/contrib/storm-jmxetric/lib/jmxetric-1.0.4.jar=host=ac95edimstr01xxxxxxx,port=8650,wireformat31x=true,mode=multicast,config=/usr/hdp/current/storm-supervisor/contrib/storm-jmxetric/conf/jmxetric-conf.xml,process=Supervisor_JVM   -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf'<br/>
supervisor.heartbeat.frequency.secs : 5<br/>
supervisor.monitor.frequency.secs : 3<br/>
supervisor.slots.ports : <span class="error">&#91;6700, 6701&#93;</span><br/>
supervisor.worker.start.timeout.secs : 120<br/>
supervisor.worker.timeout.secs : 30<br/>
task.heartbeat.frequency.secs : 3<br/>
task.refresh.poll.secs : 10<br/>
topology.acker.executors : null<br/>
topology.builtin.metrics.bucket.size.secs : 60<br/>
topology.debug : false<br/>
topology.disruptor.wait.strategy : 'com.lmax.disruptor.BlockingWaitStrategy'<br/>
topology.enable.message.timeouts : true<br/>
topology.error.throttle.interval.secs : 10<br/>
topology.executor.receive.buffer.size : 1024<br/>
topology.executor.send.buffer.size : 1024<br/>
topology.fall.back.on.java.serialization : true<br/>
topology.kryo.factory : 'backtype.storm.serialization.DefaultKryoFactory'<br/>
topology.max.error.report.per.interval : 5<br/>
topology.max.spout.pending : null<br/>
topology.max.task.parallelism : null<br/>
topology.message.timeout.secs : 30<br/>
topology.optimize : true<br/>
topology.receiver.buffer.size : 8<br/>
topology.skip.missing.kryo.registrations : false<br/>
topology.sleep.spout.wait.strategy.time.ms : 1<br/>
topology.spout.wait.strategy : 'backtype.storm.spout.SleepSpoutWaitStrategy'<br/>
topology.state.synchronization.timeout.secs : 60<br/>
topology.stats.sample.rate : 0.05<br/>
topology.tick.tuple.freq.secs : null<br/>
topology.transfer.buffer.size : 1024<br/>
topology.trident.batch.emit.interval.millis : 500<br/>
topology.tuple.serializer : 'backtype.storm.serialization.types.ListDelegateSerializer'<br/>
topology.worker.childopts : null<br/>
topology.worker.shared.thread.pool.size : 4<br/>
topology.workers : 1<br/>
transactional.zookeeper.port : null<br/>
transactional.zookeeper.root : '/transactional'<br/>
transactional.zookeeper.servers : null<br/>
ui.childopts : '-Xmx768m -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf -Dorg.eclipse.jetty.server.ssl.SslSocketConnector.requestHeaderSize=65535 -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf'<br/>
ui.port : 8744<br/>
worker.childopts : '-Xmx768m -Djava.security.auth.login.config=/etc/storm/conf/storm_jaas.conf -javaagent:/usr/hdp/current/storm-client/contrib/storm-jmxetric/lib/jmxetric-1.0.4.jar=host=ac95edimstr01xxxxxxx,port=8650,wireformat31x=true,mode=multicast,config=/usr/hdp/current/storm-client/contrib/storm-jmxetric/conf/jmxetric-conf.xml,process=Worker_%ID%_JVM'<br/>
worker.heartbeat.frequency.secs : 1<br/>
zmq.hwm : 0<br/>
zmq.linger.millis : 5000<br/>
zmq.threads : 1</p>

<p>storm.thrift.transport : "backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin"  </p>

<p>#</p>
<ol>
	<li>Kerberos security section. For the reference please use: <a href="https://github.com/hortonworks/storm/blob/champlain/SECURITY.md" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/hortonworks/storm/blob/champlain/SECURITY.md</a> for details<br/>
#</li>
</ol>


<p>storm.principal.tolocal: "backtype.storm.security.auth.KerberosPrincipalToLocal"<br/>
storm.zookeeper.superACL: "sasl:edi_storm"<br/>
java.security.auth.login.config: "/etc/storm/conf/storm_jaas.conf"<br/>
nimbus.admins:</p>
<ul class="alternate" type="square">
	<li>"edi_storm"<br/>
nimbus.supervisor.users:</li>
	<li>"edi_storm"<br/>
nimbus.authorizer: "backtype.storm.security.auth.authorizer.SimpleACLAuthorizer"<br/>
drpc.authorizer: "backtype.storm.security.auth.authorizer.DRPCSimpleACLAuthorizer"</li>
</ul>


<p>ui.filter: "org.apache.hadoop.security.authentication.server.AuthenticationFilter"<br/>
ui.filter.params:<br/>
  "type": "kerberos"<br/>
  "kerberos.principal": "HTTP/ac95edimstr02xxxxxxx@XXXXXX.ORG"<br/>
  "kerberos.keytab": "/opt/hadoop/keytabs/spnego.service.keytab"<br/>
  "kerberos.name.rules": "DEFAULT"<br/>
supervisor.enable: true</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amuise">amuise</a>:</i>
<p>Details on the 413 from a curl command local to the UI:</p>

<p>curl -i --negotiate -u:edi_storm -b ~/cookiejar.txt -c ~/cookiejar.txt <a href="http://ac95edimstr02xxxxxx:8744/api/v1/cluster/summary" class="external-link" target="_blank" rel="nofollow noopener">http://ac95edimstr02xxxxxx:8744/api/v1/cluster/summary</a></p>

<p>HTTP/1.1 401 Authentication required<br/>
Date: Wed, 21 Jan 2015 16:34:43 GMT<br/>
WWW-Authenticate: Negotiate<br/>
Set-Cookie: hadoop.auth=; Expires=Thu, 01-Jan-1970 00:00:00 GMT; HttpOnly<br/>
Cache-Control: must-revalidate,no-cache,no-store<br/>
Content-Type: text/html;charset=ISO-8859-1<br/>
Content-Length: 1317<br/>
Server: Jetty(7.6.13.v20130916)</p>

<p>HTTP/1.1 413 FULL head<br/>
Content-Length: 0<br/>
Connection: close<br/>
Server: Jetty(7.6.13.v20130916)</p>


<p>And here is the exception in the ui.log from the 413:</p>

<p>The offending header length comes from the Authorization property, it contains a long key. </p>

<p>2015-01-19 08:38:45 o.a.h.s.a.s.AuthenticationFilter <span class="error">&#91;WARN&#93;</span> Authentication exception: GSSException: Defective token detected (Mechanism level: GSSHeader did not find the right tag)<br/>
org.apache.hadoop.security.authentication.client.AuthenticationException: GSSException: Defective token detected (Mechanism level: GSSHeader did not find the right tag)<br/>
at org.apache.hadoop.security.authentication.server.KerberosAuthenticationHandler.authenticate(KerberosAuthenticationHandler.java:360) ~<span class="error">&#91;hadoop-auth-2.4.0.jar:na&#93;</span><br/>
at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:357) ~<span class="error">&#91;hadoop-auth-2.4.0.jar:na&#93;</span><br/>
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291) <span class="error">&#91;jetty-servlet-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443) <span class="error">&#91;jetty-servlet-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372) <span class="error">&#91;jetty-servlet-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.Server.handle(Server.java:369) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644) <span class="error">&#91;jetty-http-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) <span class="error">&#91;jetty-http-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) <span class="error">&#91;jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) <span class="error">&#91;jetty-io-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) <span class="error">&#91;jetty-io-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) <span class="error">&#91;jetty-util-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) <span class="error">&#91;jetty-util-7.6.13.v20130916.jar:7.6.13.v20130916&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_65&#93;</span><br/>
Caused by: org.ietf.jgss.GSSException: Defective token detected (Mechanism level: GSSHeader did not find the right tag)<br/>
at sun.security.jgss.GSSHeader.<init>(GSSHeader.java:97) ~<span class="error">&#91;na:1.7.0_65&#93;</span><br/>
at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:306) ~<span class="error">&#91;na:1.7.0_65&#93;</span><br/>
at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:285) ~<span class="error">&#91;na:1.7.0_65&#93;</span><br/>
at org.apache.hadoop.security.authentication.server.KerberosAuthenticationHandler$2.run(KerberosAuthenticationHandler.java:327) ~<span class="error">&#91;hadoop-auth-2.4.0.jar:na&#93;</span><br/>
at org.apache.hadoop.security.authentication.server.KerberosAuthenticationHandler$2.run(KerberosAuthenticationHandler.java:309) ~<span class="error">&#91;hadoop-auth-2.4.0.jar:na&#93;</span><br/>
at java.security.AccessController.doPrivileged(Native Method) ~<span class="error">&#91;na:1.7.0_65&#93;</span><br/>
at javax.security.auth.Subject.doAs(Subject.java:415) ~<span class="error">&#91;na:1.7.0_65&#93;</span><br/>
at org.apache.hadoop.security.authentication.server.KerberosAuthenticationHandler.authenticate(KerberosAuthenticationHandler.java:309) ~<span class="error">&#91;hadoop-auth-2.4.0.jar:na&#93;</span><br/>
... 20 common frames omitted</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amuise">amuise</a>:</i>
<p>Please note, we are using AD for Kerberos with an encryption type of arcfour-hmac.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p>spoke to <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adam.muise" class="user-hover" rel="adam.muise">Adam Muise</a> offline . In AD MIT kerberos setup the kerberos key size bigger than default jetty requestHeaderSize. This can be fixed by setting "ui.header.buffer.bytes" to 65536 . Will send a PR for SECURITY.md . </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user harshach opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/393" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/393</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-633" title="Nimbus - HTTP Error 413 full HEAD if using kerberos authentication" class="issue-link" data-issue-key="STORM-633"><del>STORM-633</del></a>. Nimbus - HTTP Error 413 full HEAD if using kerberos authentication.</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/harshach/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/harshach/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-633" title="Nimbus - HTTP Error 413 full HEAD if using kerberos authentication" class="issue-link" data-issue-key="STORM-633"><del>STORM-633</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/393.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/393.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #393</p>

<hr />
<p>commit ef85387299e48051abe2434a58adbd74376190e0<br/>
Author: Sriharsha Chintalapani <mail@harsha.io><br/>
Date:   2015-01-22T23:04:35Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-633" title="Nimbus - HTTP Error 413 full HEAD if using kerberos authentication" class="issue-link" data-issue-key="STORM-633"><del>STORM-633</del></a>. Nimbus - HTTP Error 413 full HEAD if using kerberos authentication.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/393#issuecomment-74160282" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/393#issuecomment-74160282</a></p>

<p>    +1 (since this is just a doc update, we probably don't need to wait for additional review)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/393" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/393</a></p>
