### ISSUE TITLE
[STORM-639] storm-maven-plugin not found

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4480]
<p>storm-maven-plugin is required by storm-core, but it cannot be found.</p>

<p>```<br/>
<span class="error">&#91;ERROR&#93;</span> Error resolving version for plugin 'org.apache.storm:storm-maven-plugins' from the repositories <span class="error">&#91;local (/Users/sasakikai/.m2/repository), central (https://repo.maven.apache.org/maven2)&#93;</span>: Plugin not found in any plugin repository -> <span class="error">&#91;Help 1&#93;</span><br/>
org.apache.maven.plugin.version.PluginVersionResolutionException: Error resolving version for plugin 'org.apache.storm:storm-maven-plugins' from the repositories <span class="error">&#91;local (/Users/sasakikai/.m2/repository), central (https://repo.maven.apache.org/maven2)&#93;</span>: Plugin not found in any plugin repository<br/>
at org.apache.maven.plugin.version.internal.DefaultPluginVersionResolver.selectVersion(DefaultPluginVersionResolver.java:236)<br/>
at org.apache.maven.plugin.version.internal.DefaultPluginVersionResolver.resolveFromRepository(DefaultPluginVersionResolver.java:148)<br/>
at org.apache.maven.plugin.version.internal.DefaultPluginVersionResolver.resolve(DefaultPluginVersionResolver.java:96)<br/>
at org.apache.maven.lifecycle.internal.LifecyclePluginResolver.resolveMissingPluginVersions(LifecyclePluginResolver.java:71)<br/>
at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:116)<br/>
at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:135)<br/>
at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:97)<br/>
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)<br/>
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)<br/>
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)<br/>
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)<br/>
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)<br/>
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)<br/>
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)<br/>
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)<br/>
at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)<br/>
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/>
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
at java.lang.reflect.Method.invoke(Method.java:606)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)<br/>
<span class="error">&#91;ERROR&#93;</span><br/>
<span class="error">&#91;ERROR&#93;</span> Re-run Maven using the -X switch to enable full debug logging.<br/>
```</p>

<p>This plugin should be installed in local repository before compile storm-core.</p>

---
<details><summary><i>Originally reported by <a title="Kai" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lewuathe">lewuathe</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-639" target="_blank">storm-maven-plugin not found</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kai" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lewuathe">lewuathe</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:00+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Lewuathe opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/403" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-639" title="storm-maven-plugin not found" class="issue-link" data-issue-key="STORM-639"><del>STORM-639</del></a> storm-maven-plugin not found</p>

<p>    maven compile is fail due to missing storm-maven-plugin. <br/>
    This plugin should be installed before compiling storm-core project.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/Lewuathe/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/Lewuathe/storm</a> maven-plugin-failure</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/403.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #403</p>

<hr />
<p>commit 715dfb9a430990835f531c316c93e0b99df626c8<br/>
Author: lewuathe <lewuathe@me.com><br/>
Date:   2015-01-30T15:08:55Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-639" title="storm-maven-plugin not found" class="issue-link" data-issue-key="STORM-639"><del>STORM-639</del></a> storm-maven-plugin not found</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/403#issuecomment-72268036" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403#issuecomment-72268036</a></p>

<p>    I am seeing this happen too.  Even with this change, if I try to compile with `mvn compile` from the top level, I see the following error:<br/>
    ```<br/>
    Error resolving version for plugin 'org.apache.storm:storm-maven-plugins'<br/>
    ```<br/>
    After `mvn install`, it does compile OK.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Lewuathe commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/403#issuecomment-72318223" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403#issuecomment-72318223</a></p>

<p>    @d2r Thank you for reporting. I'll fix to succeed compile with `mvn compile`.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Lewuathe commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/403#issuecomment-72356826" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403#issuecomment-72356826</a></p>

<p>    It seems that there is no way to install `storm-maven-plugin` in local repository before compiling `storm-core` because with `compile` phase there is no jar files enough to install. So I think there are two options. <br/>
    1. Update documents to install `storm-maven-plugin` before compiling `storm-core` project.<br/>
    2. Deploy `storm-maven-plugin` on remote repository.</p>

<p>    What do you think? If someone has any other ideas, please let me know.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/403#issuecomment-72554412" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403#issuecomment-72554412</a></p>

<p>    > Update documents to install storm-maven-plugin before compiling storm-core project.</p>

<p>    Yeah... I was afraid of that.  It is a binary dependency, and maven does not support making this kind of thing work.</p>

<p>    So I think your suggestion of changing the documents is better.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/318#issuecomment-74683011" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/318#issuecomment-74683011</a></p>

<p>    We put in some changes so the storm build now uses a plugin that is also built as part of the build.  This makes it so you cannot run ```mvn compile``` on its own any more, you need to run at least ```mvn package``` because needs a jar on the classpath.  If you plan on building in just storm-core you need to have installed the plugin  into your local repo first.  We are working on a way to fix this, but don't have a perfect solution yet <a href="https://issues.apache.org/jira/browse/STORM-639" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-639</a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Perhaps the best long term solution is to separate the plugin out into a stand alone plugin that is published/released separately from the rest of storm.  We could reach out to the maven community and see if they would be interested in making the plugin official, but in the short term, we create a new version number for the plugin, that is not the same as storm's and publish the artifact to the maven repo on its own.  We may also need to separate out the build for the plugin from the rest of storm so it does not try to pull it in and get confused.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Lewuathe commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/403#issuecomment-75163410" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403#issuecomment-75163410</a></p>

<p>    I changed documentation. Can someone review it?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/403#issuecomment-75309369" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403#issuecomment-75309369</a></p>

<p>    > Update documents to install storm-maven-plugin before compiling storm-core project.</p>

<p>    It looks as though the documents already say how to build it so that it works.  It does not claim that doing the build directly from storm-core without the plugin jar on the classpath will succeed.  So now I am not sure we want to add to the document one way not to build storm.</p>

<p>    Really, it would be good if the plugin were pushed to maven repositories separately from storm, like @revans2 <span class="error">&#91;suggested&#93;</span>(<a href="https://issues.apache.org/jira/browse/STORM-639?focusedCommentId=14324305&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14324305" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-639?focusedCommentId=14324305&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14324305</a>).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/403" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lewuathe" class="user-hover" rel="lewuathe">Kai</a>,</p>

<p>I merged your doc pull request into master.  I thought it had sat long enough without anything happening on it, and it was good.  but I don't want to close this JIRA until we have separated out the maven plugin's version/release from the rest of the release process.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/403#issuecomment-89378042" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/403#issuecomment-89378042</a></p>

<p>    I forgot to add +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
