### ISSUE TITLE
[STORM-658] config topology.acker.executors default value is null and then should not start acker bolts

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4499]
<p>See Code:<br/>
<a href="https://github.com/caofangkun/apache-storm/blob/master/storm-core/src/clj/backtype/storm/daemon/common.clj#L315" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/caofangkun/apache-storm/blob/master/storm-core/src/clj/backtype/storm/daemon/common.clj#L315</a><br/>
Config "topology.acker.executors" default value is null<br/>
then acker executors will be same as "topology.workers"<br/>
$ storm jar storm-starter-0.10.0-SNAPSHOT.jar storm.starter.ExclamationTopology ExclamationTopology<br/>
Executors show up as 18 executors = 10(word) + 3(exclaim1) + 2(exclaim2) + 3(acker bolt)<br/>
But the 3 acker bolt executors will not be used.</p>

---
<details><summary><i>Originally reported by <a title="caofangkun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-658" target="_blank">config topology.acker.executors default value is null and then should not start acker bolts</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Zhuo Liu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2015-10-09T02:35:02+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user caofangkun opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/417" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-658" title="config topology.acker.executors default value is null and then should not start acker bolts" class="issue-link" data-issue-key="STORM-658"><del>STORM-658</del></a>:when config topology.acker.executors is null, should not start acker bolts</p>

<p>    !<span class="error">&#91;is null&#93;</span>(<a href="https://cloud.githubusercontent.com/assets/1931407/6056600/2b606d70-ad4e-11e4-8c8c-b187f29d4a99.png" class="external-link" target="_blank" rel="nofollow noopener">https://cloud.githubusercontent.com/assets/1931407/6056600/2b606d70-ad4e-11e4-8c8c-b187f29d4a99.png</a>)<br/>
    Before the patch:<br/>
    !<span class="error">&#91;executors num is wrong&#93;</span>(<a href="https://cloud.githubusercontent.com/assets/1931407/6056601/3354dc0a-ad4e-11e4-9f73-4b378bfd65e1.png" class="external-link" target="_blank" rel="nofollow noopener">https://cloud.githubusercontent.com/assets/1931407/6056601/3354dc0a-ad4e-11e4-9f73-4b378bfd65e1.png</a>)</p>

<p>    After the patch:</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/caofangkun/apache-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/caofangkun/apache-storm</a> storm-658</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/417.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #417</p>

<hr />
<p>commit 6c04e1bea802d28ae92a234ddbaad2c1ed0a6835<br/>
Author: caofangkun <caofangkun@gmail.com><br/>
Date:   2015-01-23T01:28:46Z</p>

<p>    Merge pull request #4 from apache/master</p>

<p>    Merger from apache/storm to caofangkun/apache-storm</p>

<p>commit d8c98cb1846bd07aef558bde410607b923aa5c1e<br/>
Author: caofangkun <caofangkun@gmail.com><br/>
Date:   2015-02-04T01:09:22Z</p>

<p>    Merge pull request #5 from apache/master</p>

<p>    Merge from apache/storm to caofangkun/apache-storm</p>

<p>commit 4889f5249bbfa7e11195d55e59dbd8b6afc099ad<br/>
Author: caofangkun <caofangkun@gmail.com><br/>
Date:   2015-02-05T07:44:00Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-658" title="config topology.acker.executors default value is null and then should not start acker bolts" class="issue-link" data-issue-key="STORM-658"><del>STORM-658</del></a>:when config topology.acker.executors is null, should not start acker bolts</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/417#discussion_r24178428" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417#discussion_r24178428</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/daemon/common.clj &#8212;<br/>
    @@ -312,7 +312,7 @@<br/>
 ))</p>

<p>     (defn has-ackers? <span class="error">&#91;storm-conf&#93;</span></p>
<ul class="alternate" type="square">
	<li>(or (nil? (storm-conf TOPOLOGY-ACKER-EXECUTORS)) (> (storm-conf TOPOLOGY-ACKER-EXECUTORS) 0)))<br/>
    +  (and (not (nil? (storm-conf TOPOLOGY-ACKER-EXECUTORS))) (> (storm-conf TOPOLOGY-ACKER-EXECUTORS) 0)))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    can you use not-nil? in util.clj</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/417#discussion_r24178855" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417#discussion_r24178855</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/daemon/common.clj &#8212;<br/>
    @@ -312,7 +312,7 @@<br/>
 ))</p>

<p>     (defn has-ackers? <span class="error">&#91;storm-conf&#93;</span></p>
<ul class="alternate" type="square">
	<li>(or (nil? (storm-conf TOPOLOGY-ACKER-EXECUTORS)) (> (storm-conf TOPOLOGY-ACKER-EXECUTORS) 0)))<br/>
    +  (and (not (nil? (storm-conf TOPOLOGY-ACKER-EXECUTORS))) (> (storm-conf TOPOLOGY-ACKER-EXECUTORS) 0)))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Or leave out both `not` and `nil`?  Would that also work here?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user caofangkun commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/417#discussion_r24216861" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417#discussion_r24216861</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/daemon/common.clj &#8212;<br/>
    @@ -312,7 +312,7 @@<br/>
 ))</p>

<p>     (defn has-ackers? <span class="error">&#91;storm-conf&#93;</span></p>
<ul class="alternate" type="square">
	<li>(or (nil? (storm-conf TOPOLOGY-ACKER-EXECUTORS)) (> (storm-conf TOPOLOGY-ACKER-EXECUTORS) 0)))<br/>
    +  (and (not (nil? (storm-conf TOPOLOGY-ACKER-EXECUTORS))) (> (storm-conf TOPOLOGY-ACKER-EXECUTORS) 0)))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Fixed. Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/417#issuecomment-74128755" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417#issuecomment-74128755</a></p>

<p>    -1. This breaks trident functionality if `topology.acker.executors` is `null` in `storm.yaml` and not overridden in the topology conf.</p>

<p>    I've not dug too far into the root cause, but the situation above results in `StackOverflowError`s in the MasterBatchCoordinator spout. See stack trace below.<br/>
    ```<br/>
    java.lang.StackOverflowError: null<br/>
    at clojure.lang.Numbers.multiply(Numbers.java:3663) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at backtype.storm.stats$curr_time_bucket.invoke(stats.clj:29) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.stats$update_rolling_window.doInvoke(stats.clj:41) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at clojure.lang.RestFn.applyTo(RestFn.java:142) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at clojure.core$apply.invoke(core.clj:628) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at backtype.storm.stats$update_rolling_window_set$iter_<em>2980</em><em>2984$fn</em><em>2985$fn</em>_2986.invoke(stats.clj:77) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.stats$update_rolling_window_set$iter_<em>2980</em><em>2984$fn</em>_2985.invoke(stats.clj:76) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at clojure.lang.LazySeq.sval(LazySeq.java:40) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at clojure.lang.LazySeq.seq(LazySeq.java:49) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at clojure.lang.RT.seq(RT.java:484) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at clojure.core$seq.invoke(core.clj:133) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at clojure.core$dorun.invoke(core.clj:2855) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at clojure.core$doall.invoke(core.clj:2871) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at backtype.storm.stats$update_rolling_window_set.doInvoke(stats.clj:76) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at clojure.lang.RestFn.invoke(RestFn.java:439) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at clojure.lang.Atom.swap(Atom.java:65) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at clojure.core$swap_BANG_.invoke(core.clj:2234) ~<span class="error">&#91;clojure-1.6.0.jar:na&#93;</span><br/>
    at backtype.storm.stats$emitted_tuple_BANG_.invoke(stats.clj:215) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.task$mk_tasks_fn$fn__4329.invoke(task.clj:160) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>4615$fn</em><em>4630$send_spout_msg</em>_4648.invoke(executor.clj:502) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>4615$fn$reify</em>_4657.emit(executor.clj:547) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:49) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at storm.trident.topology.MasterBatchCoordinator.sync(MasterBatchCoordinator.java:176) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at storm.trident.topology.MasterBatchCoordinator.ack(MasterBatchCoordinator.java:145) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$ack_spout_msg.invoke(executor.clj:399) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>4615$fn</em><em>4630$send_spout_msg</em>_4648.invoke(executor.clj:532) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>4615$fn$reify</em>_4657.emit(executor.clj:547) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:49) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at storm.trident.topology.MasterBatchCoordinator.sync(MasterBatchCoordinator.java:200) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at storm.trident.topology.MasterBatchCoordinator.ack(MasterBatchCoordinator.java:145) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$ack_spout_msg.invoke(executor.clj:399) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>4615$fn</em><em>4630$send_spout_msg</em>_4648.invoke(executor.clj:532) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>4615$fn$reify</em>_4657.emit(executor.clj:547) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:49) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at storm.trident.topology.MasterBatchCoordinator.sync(MasterBatchCoordinator.java:176) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at storm.trident.topology.MasterBatchCoordinator.ack(MasterBatchCoordinator.java:145) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$ack_spout_msg.invoke(executor.clj:399) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.daemon.executor$fn_<em>4615$fn</em><em>4630$send_spout_msg</em>_4648.invoke(executor.clj:532) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>:</i>
<p>This Issue raises a valid point that Storm's behavior with a null value for <tt>topology.acker.executors</tt> might seem surprising.  Whether or not the Acker Executors will be used depends on the code.  If the topology components intend to make use of Acking, then it would be good for the common case to be handled. One Acker Executor per Worker seems like a good default here, so I am not too interested in changing it. I could be convinced otherwise.</p>

<p>What we might want to do instead is change the documentation—both the Markdown and the JavaDoc—to explicitly describe what the default behavior is.  We would want to update the description in Config.java and update our document titled "Guaranteeing Message Processing."  (Incidentally, the latter document already describes how to disable launching of the Acker Executors if you know that you do not want acking, which is to use <tt>0</tt>.)</p>

<p>We might also want to either update the example Topologies to actually make use of acking or else update them not to launch the Ackers at all so as to avoid possibly confusing users.</p>

<p>Another thought is that perhaps we should not count Executors that are devoted to running system Tasks like the Acker on the UI Topology Summary, since we have a button at the bottom that enables or disables inclusion of the system stats.  I looked at the UI code, and it seems we have been counting Acker Executors in the Topology Summary for a very long time.  So far we have simply counted all the Executors in the Topology whether or not the user asked to show System Stats.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">(defn add-acker! [storm-conf ^StormTopology ret]
  (let [num-executors (<span class="code-keyword">if</span> (nil? (storm-conf TOPOLOGY-ACKER-EXECUTORS)) (storm-conf TOPOLOGY-WORKERS) (storm-conf TOPOLOGY-ACKER-EXECUTORS))
</pre>
</div></div>

<p>Setting null to "topology.acker.executors" is intentional (It is only way to use 1 acker per worker), but it looks like easy to be confusing (This issue is started with confusion) and it seems not be documented properly any places.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> I agree. I think we should document the current behavior.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>Hi, Fangjun, I see this issue has been inactive for a while. Does it matter if I take a shot on this? <br/>
If it is OK, I will assign it to me and submit a pull request for updating the doc descriptions for TOPOLOGY_ACKER_EXECUTORS. Please feel free to pose if you have a different opinion.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user zhuoliu opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/628" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/628</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-658" title="config topology.acker.executors default value is null and then should not start acker bolts" class="issue-link" data-issue-key="STORM-658"><del>STORM-658</del></a> Add doc descriptions for the TOPOLOGY_ACKER_EXECUTORS</p>

<p>    The current doc for ackers is outdated (it is for TOPOLOGY_ACKERS), we need to update the descriptions for TOPOLOGY_ACKER_EXECUTORS in Config.java, Guaranteeing-message-processing.md and Running-topologies-on-a-production-cluster.md.</p>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/zhuoliu/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/zhuoliu/storm</a> 658</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/628.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/628.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #628</p>

<hr />
<p>commit f3bfaa08d359ab2bf6374bf428bbd3658b097ad6<br/>
Author: zhuol <zhuol@yahoo-inc.com><br/>
Date:   2015-07-10T18:38:06Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-658" title="config topology.acker.executors default value is null and then should not start acker bolts" class="issue-link" data-issue-key="STORM-658"><del>STORM-658</del></a> Add doc descriptions for the TOPOLOGY_ACKER_EXECUTORS</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/417#issuecomment-120494584" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417#issuecomment-120494584</a></p>

<p>    This PR is a bit stale.  Can we move to another PR #628 that adds clarifying documentation, and close this one?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/628#issuecomment-120539193" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/628#issuecomment-120539193</a></p>

<p>    +1, good explanation.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/628#issuecomment-120601264" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/628#issuecomment-120601264</a></p>

<p>    @zhuoliu <br/>
    Btw, I think we need to create new issue cause <a href="https://issues.apache.org/jira/browse/STORM-658" title="config topology.acker.executors default value is null and then should not start acker bolts" class="issue-link" data-issue-key="STORM-658"><del>STORM-658</del></a> is actually wrong.<br/>
    Could you create new issue? Thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user zhuoliu commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/628#issuecomment-120642677" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/628#issuecomment-120642677</a></p>

<p>    Thanks @HeartSaVioR ! Sure, a new issue is created (storm-934). <br/>
    <a href="https://issues.apache.org/jira/browse/STORM-934" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-934</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It is not a problem, but we need to improve documentation to make it clear.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/417#issuecomment-120654669" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417#issuecomment-120654669</a></p>

<p>    @caofangkun Could you please close this PR? Thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user caofangkun closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/417" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/417</a></p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-934">STORM-934</a>]</i>
