### ISSUE TITLE
[STORM-661] java.io.FileNotFoundException: File 'stormconf.ser' does not exist

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4502]
<p>I'm using 0.9.3 and facing this error.</p>

<p>I heard that it's solved in 0.9.0 something but still it's happening.</p>

<p>It's critical since if this happen, supervisor also dies and does not automatically run again.</p>

<p>we've been using Storm from 0.9.2.</p>

<p>2015-02-08 17:22:16 b.s.event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.io.FileNotFoundException: File 'storm-local/supervisor/stormdist/indexer-rescue-135-1422240287/stormconf.ser' does not exist<br/>
at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1763) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at backtype.storm.config$read_supervisor_storm_conf.invoke(config.clj:212) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.daemon.supervisor$fn__4256.invoke(supervisor.clj:509) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.MultiFn.invoke(MultiFn.java:241) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.supervisor$sync_processes$iter_<em>4116</em><em>4120$fn</em>_4121.invoke(supervisor.clj:285) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.LazySeq.sval(LazySeq.java:42) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.LazySeq.seq(LazySeq.java:60) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RT.seq(RT.java:484) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$seq.invoke(core.clj:133) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$dorun.invoke(core.clj:2780) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$doall.invoke(core.clj:2796) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:273) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:397) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2467.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_71&#93;</span><br/>
2015-02-08 17:22:16 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) <span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2467.invoke(event.clj:48) <span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_71&#93;</span><br/>
2015-02-08 17:22:16 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down supervisor 5fbb3cd9-0cd9-4a4c-9f17-3991928ea716</p>

---
<details><summary><i>Originally reported by <a title="Adrian Seungjin Lee" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj">sweetest_sj</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-661" target="_blank">java.io.FileNotFoundException: File 'stormconf.ser' does not exist</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2015-10-09T02:26:39+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj" class="user-hover" rel="sweetest_sj">Adrian Seungjin Lee</a>  This is already filed in <a href="https://issues.apache.org/jira/browse/STORM-130" title="[Storm 0.8.2]: java.io.FileNotFoundException: File &#39;../stormconf.ser&#39; does not exist" class="issue-link" data-issue-key="STORM-130"><del>STORM-130</del></a> and we have patch for both 0.9.3 and master .</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj">sweetest_sj</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a><br/>
Downloading new tarball file from <a href="http://www.apache.org/dyn/closer.cgi/storm/apache-storm-0.9.3/apache-storm-0.9.3.tar.gz" class="external-link" target="_blank" rel="nofollow noopener">http://www.apache.org/dyn/closer.cgi/storm/apache-storm-0.9.3/apache-storm-0.9.3.tar.gz</a><br/>
will solve this problem?</p>

<p>or do I have to checkout from git and build it myself?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj" class="user-hover" rel="sweetest_sj">Adrian Seungjin Lee</a>  code is not merged into 0.9.3 branch yet. Here is the PR <a href="https://github.com/apache/storm/pull/418" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/418</a><br/>
you can checkout 0.9.3 branch , apply the patch  and build it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jia.fu">jia.fu</a>:</i>
<p>I run storm 0.9.3 cluster and still   get this issue .anyone  have a idea how to fix in pro cluster.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jia.fu" class="user-hover" rel="jia.fu">jia.fu</a> This is fixed in 0.9.4 . If you are upgrading I advice you to pick 0.9.5 version as that is the latest one.</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-130">STORM-130</a>]</i>
