### ISSUE TITLE
[STORM-662] java.lang.OutOfMemoryError: Direct buffer memory 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4503]
<p>I'm using Storm 0.9.3 and facing this error in running topology.</p>

<p>Below is our custom configuration but it's pretty small.</p>

<p>supervisor.slots.ports:</p>
<ul class="alternate" type="square">
	<li>6700<br/>
worker.childopts:<br/>
    -Xmx4g -Xms4g<br/>
    -server -Djava.net.preferIPv4Stack=true<br/>
topology.worker.shared.thread.pool.size: 512<br/>
storm.messaging.netty.max_retries: 100</li>
</ul>

<p>Feb 08, 2015 5:17:05 PM org.apache.storm.netty.channel.socket.nio.AbstractNioSelector WARNING: Unexpected exception in the selector loop. java.lang.OutOfMemoryError: Direct buffer memory at java.nio.Bits.reserveMemory(Bits.java:658) at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306) at org.apache.storm.netty.channel.socket.nio.SocketReceiveBufferAllocator.newBuffer(SocketReceiveBufferAllocator.java:64) at org.apache.storm.netty.channel.socket.nio.SocketReceiveBufferAllocator.get(SocketReceiveBufferAllocator.java:44) at org.apache.storm.netty.channel.socket.nio.NioWorker.read(NioWorker.java:62) at org.apache.storm.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) at org.apache.storm.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) at org.apache.storm.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) at org.apache.storm.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) at org.apache.storm.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) at org.apache.storm.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)</p>

---
<details><summary><i>Originally reported by <a title="Adrian Seungjin Lee" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj">sweetest_sj</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-662" target="_blank">java.lang.OutOfMemoryError: Direct buffer memory </a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:50+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jackcptdev">jackcptdev</a>:</i>
<p>please try the off heap memory configuration in worker.childops : -XX:MaxDirectMemorySize=xxx</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
