### ISSUE TITLE
[STORM-671] Measure tuple serialization/deserialization latency.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4512]
<p>Some times the serialization/deserialization cost can be very high, and it is not currently measured anywhere in storm.  We should measure it, at least in a similar way to how we do execute and process latency.</p>

---
<details><summary><i>Originally reported by <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-671" target="_blank">Measure tuple serialization/deserialization latency.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kai" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lewuathe">lewuathe</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:55:02+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lewuathe">lewuathe</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> Can I work on this issue? My understanding to this measurement is that each component save slowest serialization/deserialization time in TopologyInfo and user can lookup this metrics from ui view, right?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#issuecomment-75978633" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#issuecomment-75978633</a></p>

<p>    For the most part things look good.  I really would like to see these stats sent to the MetricsConsumer instances, not just the UI (the systems are separate).  I also would like to see the documentation for the restful web service </p>

<p>    <a href="https://github.com/apache/storm/blob/master/STORM-UI-REST-API.md" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/STORM-UI-REST-API.md</a></p>

<p>    updated to include the new fields you added.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Lewuathe commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#discussion_r25424494" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#discussion_r25424494</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/stats.clj &#8212;<br/>
    @@ -164,13 +164,13 @@<br/>
     (def COMMON-FIELDS <span class="error">&#91;:emitted :transferred&#93;</span>)<br/>
     (defrecord CommonStats <span class="error">&#91;emitted transferred rate&#93;</span>)</p>

<p>    -(def BOLT-FIELDS <span class="error">&#91;:acked :failed :process-latencies :executed :execute-latencies&#93;</span>)<br/>
    +(def BOLT-FIELDS <span class="error">&#91;:acked :failed :process-latencies :executed :execute-latencies :deserialize-time&#93;</span>)<br/>
     ;;acked and failed count individual tuples<br/>
    -(defrecord BoltExecutorStats <span class="error">&#91;common acked failed process-latencies executed execute-latencies&#93;</span>)<br/>
    +(defrecord BoltExecutorStats <span class="error">&#91;common acked failed process-latencies executed execute-latencies deserialize-time&#93;</span>)</p>

<p>    -(def SPOUT-FIELDS <span class="error">&#91;:acked :failed :complete-latencies&#93;</span>)<br/>
    +(def SPOUT-FIELDS <span class="error">&#91;:acked :failed :complete-latencies :deserialize-time&#93;</span>)<br/>
    &#8212; End diff &#8211;</p>

<p>    This might be the point I didn't fully understand. <br/>
    In <span class="error">&#91;here&#93;</span>(<a href="https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/executor.clj#L413-L429" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/executor.clj#L413-L429</a>), all tuple to even spout can go through task-receiver right? I think these values are sent as bolt ones.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#issuecomment-76253245" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#issuecomment-76253245</a></p>

<p>    When I run a topology with acing actually turned on I get the following in the nimbus log in response to trying to view the UI page. The topology seems to be running just fine though.</p>

<p>    ```<br/>
    2015-02-26T13:38:38.319-0600 o.a.t.s.AbstractNonblockingServer$FrameBuffer <span class="error">&#91;ERROR&#93;</span> Unexpected throwable while invoking!<br/>
    java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.String<br/>
    at backtype.storm.generated.SpoutStats$SpoutStatsStandardScheme.write(SpoutStats.java:929) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.SpoutStats$SpoutStatsStandardScheme.write(SpoutStats.java:702) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.SpoutStats.write(SpoutStats.java:616) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.ExecutorSpecificStats.standardSchemeWriteValue(ExecutorSpecificStats.java:220) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at org.apache.thrift7.TUnion$TUnionStandardScheme.write(TUnion.java:244) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at org.apache.thrift7.TUnion$TUnionStandardScheme.write(TUnion.java:213) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at org.apache.thrift7.TUnion.write(TUnion.java:152) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.ExecutorStats$ExecutorStatsStandardScheme.write(ExecutorStats.java:705) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.ExecutorStats$ExecutorStatsStandardScheme.write(ExecutorStats.java:563) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.ExecutorStats.write(ExecutorStats.java:489) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.ExecutorSummary$ExecutorSummaryStandardScheme.write(ExecutorSummary.java:862) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.ExecutorSummary$ExecutorSummaryStandardScheme.write(ExecutorSummary.java:763) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.ExecutorSummary.write(ExecutorSummary.java:655) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.TopologyInfo$TopologyInfoStandardScheme.write(TopologyInfo.java:1118) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.TopologyInfo$TopologyInfoStandardScheme.write(TopologyInfo.java:976) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.TopologyInfo.write(TopologyInfo.java:848) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.Nimbus$getTopologyInfoWithOpts_result$getTopologyInfoWithOpts_resultStandardScheme.write(Nimbus.java:18525) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.Nimbus$getTopologyInfoWithOpts_result$getTopologyInfoWithOpts_resultStandardScheme.write(Nimbus.java:18471) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.generated.Nimbus$getTopologyInfoWithOpts_result.write(Nimbus.java:18406) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:53) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:39) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at backtype.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:156) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at org.apache.thrift7.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) ~<span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at org.apache.thrift7.server.Invocation.run(Invocation.java:18) <span class="error">&#91;storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT&#93;</span><br/>
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) <span class="error">&#91;na:1.8.0&#93;</span><br/>
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) <span class="error">&#91;na:1.8.0&#93;</span><br/>
    at java.lang.Thread.run(Thread.java:744) <span class="error">&#91;na:1.8.0&#93;</span><br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#discussion_r25457668" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#discussion_r25457668</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/stats.clj &#8212;<br/>
    @@ -235,6 +237,11 @@<br/>
       (let [key <span class="error">&#91;component stream&#93;</span>]<br/>
 (update-executor-stat! stats :failed key (stats-rate stats))))</p>

<p>    +(defn bolt-deserialize-time!<br/>
    +  <span class="error">&#91;^BoltExecutorStats stats component stream deserialize-time&#93;</span><br/>
    &#8212; End diff &#8211;</p>

<p>    I am nervious about this being specific to a bolt, and the spout calling into this.  Clojure is going to have to use reflection to make this work, which is slow.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Lewuathe commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#issuecomment-76501848" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#issuecomment-76501848</a></p>

<p>    @revans2 Thank you so much for reviewing. I updated to solve above exception and include builtin metrics. Please check it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#issuecomment-89333447" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#issuecomment-89333447</a></p>

<p>    @Lewuathe, I am really sorry that this took so long. Now that <a href="https://issues.apache.org/jira/browse/STORM-634" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-634</a> has gone in, the code does not merge cleanly.  The big difference is that now we are storing the metrics in thrift in zookeeper.  We also want to support rolling upgrades, so we need to make sure that the new metrics are optional in both the code, and in thrift.  If this is something that you just don't have time to finish I understand, and I'll try to come up with a patch at some point.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#issuecomment-89333934" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#issuecomment-89333934</a></p>

<p>    @Lewuathe I forgot to mention that @Parth-Brahmbhatt might be able to help you out in understanding the changes you need to make to stats for this to work.  Especially the rolling upgrade part.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Lewuathe commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#issuecomment-89586916" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#issuecomment-89586916</a></p>

<p>    @revans2 Thank you for supporting. I'll change this metrics as optional and thrift interface. So all I have to do it 2 points, @Parth-Brahmbhatt ? If there is any other points I should care about, please let me know. </p>
<ul>
	<li>Store metrics in thrift in ZooKeeper.</li>
	<li>Change serialization as optional metrics.</li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Lewuathe commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#issuecomment-90081039" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#issuecomment-90081039</a></p>

<p>    @Parth-Brahmbhatt Thank you for advice. I merged master and updated this patch. Can you review it?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#issuecomment-90117819" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#issuecomment-90117819</a></p>

<p>    I am +1 once you remove all the generated files that has no change other then the generated date.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/442#discussion_r27805696" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/442#discussion_r27805696</a></p>

<p>    &#8212; Diff: storm-core/src/storm.thrift &#8212;<br/>
    @@ -174,12 +174,14 @@ struct BoltStats {<br/>
       3: required map<string, map<GlobalStreamId, double>> process_ms_avg;<br/>
       4: required map<string, map<GlobalStreamId, i64>> executed;  <br/>
       5: required map<string, map<GlobalStreamId, double>> execute_ms_avg;<br/>
    +  6: required map<string, map<GlobalStreamId, double>> deserialize_time;<br/>
    &#8212; End diff &#8211;</p>

<p>    This is still marked as required, if we want a rolling upgrade this needs to be optional, possibly with a reasonable default, and every time we access it, mostly for reads, we need to check to see if it is set.</p>
