### ISSUE TITLE
[STORM-698] Jackson incompatibility ring-json

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4539]
<p>ring-json -> com.fasterxml.jackson.core:jackson-core:2.3.1 incompatibility</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2015-03-04 12:34:35 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.lang.RuntimeException: java.io.InvalidClassException: com.fasterxml.jackson.core.JsonFactory; local <span class="code-keyword">class </span>incompatible: stream classdesc serialVersionUID = 3306684576057132431, local <span class="code-keyword">class </span>serialVersionUID = 3194418244231611666
  at backtype.storm.serialization.DefaultSerializationDelegate.deserialize(DefaultSerializationDelegate.java:56) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.utils.Utils.deserialize(Utils.java:95) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.utils.Utils.getSetComponentObject(Utils.java:234) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.daemon.task$get_task_object.invoke(task.clj:79) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.daemon.task$mk_task_data$fn__4304.invoke(task.clj:181) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.util$assoc_apply_self.invoke(util.clj:894) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.daemon.task$mk_task_data.invoke(task.clj:174) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.daemon.task$mk_task.invoke(task.clj:185) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.daemon.executor$mk_executor$fn__4499.invoke(executor.clj:337) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at clojure.core$map$fn__4245.invoke(core.clj:2557) ~[clojure-1.6.0.jar:na]
  at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.6.0.jar:na]
  at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.6.0.jar:na]
  at clojure.lang.RT.seq(RT.java:484) ~[clojure-1.6.0.jar:na]
  at clojure.core$seq.invoke(core.clj:133) ~[clojure-1.6.0.jar:na]
  at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~[clojure-1.6.0.jar:na]
  at clojure.core.protocols$fn__6078.invoke(protocols.clj:54) ~[clojure-1.6.0.jar:na]
  at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13) ~[clojure-1.6.0.jar:na]
  at clojure.core$reduce.invoke(core.clj:6289) ~[clojure-1.6.0.jar:na]
  at clojure.core$into.invoke(core.clj:6341) ~[clojure-1.6.0.jar:na]
  at backtype.storm.daemon.executor$mk_executor.invoke(executor.clj:337) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at backtype.storm.daemon.worker$fn__5031$exec_fn__1694__auto__$reify__5033$iter__5038__5042$fn__5043.invoke(worker.clj:459) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.6.0.jar:na]
  at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.6.0.jar:na]
  at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.6.0.jar:na]
  at clojure.lang.RT.next(RT.java:598) ~[clojure-1.6.0.jar:na]
  at clojure.core$next.invoke(core.clj:64) ~[clojure-1.6.0.jar:na]
  at clojure.core$dorun.invoke(core.clj:2856) ~[clojure-1.6.0.jar:na]
  at clojure.core$doall.invoke(core.clj:2871) ~[clojure-1.6.0.jar:na]
  at backtype.storm.daemon.worker$fn__5031$exec_fn__1694__auto__$reify__5033.run(worker.clj:459) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_31]
  at javax.security.auth.Subject.doAs(Subject.java:422) ~[na:1.8.0_31]
  at backtype.storm.daemon.worker$fn__5031$exec_fn__1694__auto____5032.invoke(worker.clj:433) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at clojure.lang.AFn.applyToHelper(AFn.java:178) [clojure-1.6.0.jar:na]
  at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.6.0.jar:na]
  at clojure.core$apply.invoke(core.clj:624) ~[clojure-1.6.0.jar:na]
  at backtype.storm.daemon.worker$fn__5031$mk_worker__5108.doInvoke(worker.clj:416) [storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.6.0.jar:na]
  at backtype.storm.daemon.worker$_main.invoke(worker.clj:548) [storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.6.0.jar:na]
  at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.6.0.jar:na]
  at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
Caused by: java.io.InvalidClassException: com.fasterxml.jackson.core.JsonFactory; local <span class="code-keyword">class </span>incompatible: stream classdesc serialVersionUID = 3306684576057132431, local <span class="code-keyword">class </span>serialVersionUID = 3194418244231611666
  at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_31]
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_31]
  at backtype.storm.serialization.DefaultSerializationDelegate.deserialize(DefaultSerializationDelegate.java:52) ~[storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  ... 40 common frames omitted
2015-03-04 12:34:35 b.s.util [ERROR] Halting process: (<span class="code-quote">"Error on initialization"</span>)
java.lang.RuntimeException: (<span class="code-quote">"Error on initialization"</span>)
  at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:332) [storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.6.0.jar:na]
  at backtype.storm.daemon.worker$fn__5031$mk_worker__5108.doInvoke(worker.clj:416) [storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.6.0.jar:na]
  at backtype.storm.daemon.worker$_main.invoke(worker.clj:548) [storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
  at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.6.0.jar:na]
  at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.6.0.jar:na]
  at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.10.0-SNAPSHOT.jar:0.10.0-SNAPSHOT]
2015-03-04 12:34:39 o.a.s.z.ZooKeeper [INFO] Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Seung Eun Choi" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thinker0">thinker0</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-698" target="_blank">Jackson incompatibility ring-json</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:59+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
