### ISSUE TITLE
[STORM-755] An exception occured while executing the Java class. fyp-storm-try.src.jvm.Topology 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4596]
<p>ubuntu@ip-10-0-0-101:~/storm/examples/fyp-storm-try$ sudo mvn exec:java -D storm.topology=fyp-storm-try.src.jvm.Topology<br/>
<span class="error">&#91;INFO&#93;</span> Scanning for projects...<br/>
<span class="error">&#91;WARNING&#93;</span><br/>
<span class="error">&#91;WARNING&#93;</span> Some problems were encountered while building the effective model for org.apache.storm:fyp-storm-try:jar:0.9.4<br/>
<span class="error">&#91;WARNING&#93;</span> 'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ org.apache.storm:storm:0.9.4, /root/.m2/repository/org/apache/storm/storm/0.9.4/storm-0.9.4.pom, line 694, column 21<br/>
<span class="error">&#91;WARNING&#93;</span> 'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-report-plugin is missing. @ org.apache.storm:storm:0.9.4, /root/.m2/repository/org/apache/storm/storm/0.9.4/storm-0.9.4.pom, line 660, column 21<br/>
<span class="error">&#91;WARNING&#93;</span><br/>
<span class="error">&#91;WARNING&#93;</span> It is highly recommended to fix these problems because they threaten the stability of your build.<br/>
<span class="error">&#91;WARNING&#93;</span><br/>
<span class="error">&#91;WARNING&#93;</span> For this reason, future Maven versions might no longer support building such malformed projects.<br/>
<span class="error">&#91;WARNING&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> Building fyp-storm-try 0.9.4<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> >>> exec-maven-plugin:1.2.1:java (default-cli) @ fyp-storm-try >>><br/>
<span class="error">&#91;INFO&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> <<< exec-maven-plugin:1.2.1:java (default-cli) @ fyp-storm-try <<<<br/>
<span class="error">&#91;INFO&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> &#8212; exec-maven-plugin:1.2.1:java (default-cli) @ fyp-storm-try &#8212;<br/>
<span class="error">&#91;WARNING&#93;</span><br/>
java.lang.ClassNotFoundException: fyp-storm-try.src.jvm.Topology<br/>
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)<br/>
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)<br/>
at java.security.AccessController.doPrivileged(Native Method)<br/>
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)<br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)<br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)<br/>
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)<br/>
at java.lang.Thread.run(Thread.java:745)<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> BUILD FAILURE<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> Total time: 3.838s<br/>
<span class="error">&#91;INFO&#93;</span> Finished at: Sun Apr 05 09:09:28 UTC 2015<br/>
<span class="error">&#91;INFO&#93;</span> Final Memory: 9M/22M<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;ERROR&#93;</span> Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project fyp-storm-try: An exception occured while executing the Java class. fyp-storm-try.src.jvm.Topology -> <span class="error">&#91;Help 1&#93;</span><br/>
<span class="error">&#91;ERROR&#93;</span><br/>
<span class="error">&#91;ERROR&#93;</span> To see the full stack trace of the errors, re-run Maven with the -e switch.<br/>
<span class="error">&#91;ERROR&#93;</span> Re-run Maven using the -X switch to enable full debug logging.<br/>
<span class="error">&#91;ERROR&#93;</span><br/>
<span class="error">&#91;ERROR&#93;</span> For more information about the errors and possible solutions, please read the following articles:<br/>
<span class="error">&#91;ERROR&#93;</span> <span class="error">&#91;Help 1&#93;</span> <a href="http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException" class="external-link" target="_blank" rel="nofollow noopener">http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException</a></p>

<p>Below are my pom.xml:<br/>
?xml version="1.0" encoding="UTF-8"?><br/>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 <a href="http://maven.apache.org/xsd/maven-4.0.0.xsd" class="external-link" target="_blank" rel="nofollow noopener">http://maven.apache.org/xsd/maven-4.0.0.xsd</a>"><br/>
  <modelVersion>4.0.0</modelVersion><br/>
  <parent><br/>
      <artifactId>storm</artifactId><br/>
      <groupId>org.apache.storm</groupId><br/>
      <version>0.9.4</version><br/>
      <relativePath>../../pom.xml</relativePath><br/>
  </parent></p>

<p>  <groupId>org.apache.storm</groupId><br/>
  <artifactId>fyp-storm-try</artifactId><br/>
  <packaging>jar</packaging></p>

<p>  <name>fyp-storm-try</name></p>

<p>  <dependencies><br/>
    <dependency><br/>
      <groupId>junit</groupId><br/>
      <artifactId>junit</artifactId><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.testng</groupId><br/>
      <artifactId>testng</artifactId><br/>
      <version>6.8.5</version><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.mockito</groupId><br/>
      <artifactId>mockito-all</artifactId><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.easytesting</groupId><br/>
      <artifactId>fest-assert-core</artifactId><br/>
      <version>2.0M8</version><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.jmock</groupId><br/>
      <artifactId>jmock</artifactId><br/>
      <version>2.6.0</version><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
     <groupId>org.twitter4j</groupId><br/>
     <artifactId>twitter4j-stream</artifactId><br/>
     <version>3.0.3</version><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.apache.storm</groupId><br/>
      <artifactId>storm-core</artifactId><br/>
      <version>${project.version}</version><br/>
      <br/>
      <scope>provided</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>commons-collections</groupId><br/>
      <artifactId>commons-collections</artifactId><br/>
      <version>3.2.1</version><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>com.google.guava</groupId><br/>
      <artifactId>guava</artifactId><br/>
    </dependency><br/>
  </dependencies></p>

<p>  <build><br/>
    <sourceDirectory>src/jvm</sourceDirectory><br/>
    <testSourceDirectory>test/jvm</testSourceDirectory><br/>
    <resources><br/>
      <resource><br/>
<directory>${basedir}/multilang</directory><br/>
      </resource><br/>
    </resources></p>

<p>    <plugins><br/>
      <br/>
      <plugin><br/>
<artifactId>maven-assembly-plugin</artifactId><br/>
<configuration><br/>
  <descriptorRefs><br/>
    <descriptorRef>jar-with-dependencies</descriptorRef><br/>
  </descriptorRefs><br/>
  <archive><br/>
    <manifest><br/>
      <mainClass /><br/>
    </manifest><br/>
  </archive><br/>
</configuration><br/>
<executions><br/>
  <execution><br/>
    <id>make-assembly</id><br/>
    <phase>package</phase><br/>
    <goals><br/>
      <goal>single</goal><br/>
    </goals><br/>
  </execution><br/>
</executions><br/>
      </plugin></p>

<p>      <plugin><br/>
<groupId>com.theoryinpractise</groupId><br/>
<artifactId>clojure-maven-plugin</artifactId><br/>
<extensions>true</extensions><br/>
<configuration><br/>
  <sourceDirectories><br/>
    <sourceDirectory>src/clj</sourceDirectory><br/>
  </sourceDirectories><br/>
</configuration><br/>
<executions><br/>
  <execution><br/>
    <id>compile</id><br/>
    <phase>compile</phase><br/>
    <goals><br/>
      <goal>compile</goal><br/>
    </goals><br/>
  </execution><br/>
</executions><br/>
      </plugin></p>

<p>      <plugin><br/>
<groupId>org.codehaus.mojo</groupId><br/>
<artifactId>exec-maven-plugin</artifactId><br/>
<version>1.2.1</version><br/>
<executions><br/>
  <execution><br/>
		   <phase>test</phase><br/>
    <goals><br/>
      <goal>exec</goal><br/>
    </goals><br/>
  </execution><br/>
</executions><br/>
<configuration><br/>
  <executable>java</executable><br/>
  <includeProjectDependencies>true</includeProjectDependencies><br/>
  <includePluginDependencies>false</includePluginDependencies><br/>
  <classpathScope>compile</classpathScope><br/>
  <mainClass>${storm.topology}</mainClass><br/>
</configuration><br/>
      </plugin><br/>
    </plugins><br/>
  </build><br/>
</project></p>

---
<details><summary><i>Originally reported by <a title="Yuen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Lim Chun Yuen">Lim Chun Yuen</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-755" target="_blank">An exception occured while executing the Java class. fyp-storm-try.src.jvm.Topology </a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2017-12-28T04:58:03+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Lim+Chun+Yuen" class="user-hover" rel="Lim Chun Yuen">Yuen</a> it looks like the issue seems to be with your topology. Can you explain why this is a  bug with storm?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lim chun yuen">lim chun yuen</a>:</i>
<p>Well, as mentioned in detail, I didn't say it is a bug in storm, I just ask a question. I am newbie using storm.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Actually you're encouraged to post a question to mailing list.</p>

<p><a href="http://storm.apache.org/documentation/Home.html" class="external-link" target="_blank" rel="nofollow noopener">http://storm.apache.org/documentation/Home.html</a> for getting user mailing list address.</p>

<p>Storm Users</p>

<p>Storm users should send messages and subscribe to user@storm.apache.org.</p>

<p>You can subscribe to this list by sending an email to user-subscribe@storm.apache.org. Likewise, you can cancel a subscription by sending an email to user-unsubscribe@storm.apache.org.</p>
