### ISSUE TITLE
[STORM-771] Authentication with Kerberos

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4612]
<p>I am using Storm in a Kerberized Cluster. <br/>
There is an user "Robin" in the Storm server. And I follow the steps below to generate keytab for Robin.</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre># /usr/sbin/kadmin.local
# kadmin.local: addprinc -randkey Robin@EXAMPLE.COM
# kadmin.local: xst -norandkey -k Robin.keytab Robin
# scp Robin.keytab Robin@storm_server:/home/Robin
</pre>
</div></div>
<p>After these, I login the Storm server as Robin. And authenticate Robin with his own keytab(Robin.keytab)</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre># kinit -k -t Robin.keytab Robin
</pre>
</div></div>
<p>The output of klist is</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Ticket cache: FILE:/tmp/krb5cc_1006
Default principal: Robin@EXAMPLE.COM

Valid starting     Expires    Service principal
04/15/15 11:34:19  04/16/15 11:34:19  krbtgt/EXAMPLE.COM@EXAMPLE.COM
renew until 04/15/15 11:34:19
</pre>
</div></div>

<p>But there was an authentication error occurred when I executed </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>#storm list
</pre>
</div></div>
<p>The error was</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Exception in thread "main" java.lang.RuntimeException: javax.security.auth.login.LoginException: No password provided
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin.connect(KerberosSaslTransportPlugin.java:108)
at backtype.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:48)
at backtype.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:97)
at backtype.storm.security.auth.ThriftClient.<init>(ThriftClient.java:66)
at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:47)
at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:71)
at backtype.storm.command.list$_main.invoke(list.clj:22)
at clojure.lang.AFn.applyToHelper(AFn.java:159)
at clojure.lang.AFn.applyTo(AFn.java:151)
at backtype.storm.command.list.main(Unknown Source)
Caused by: javax.security.auth.login.LoginException: No password provided
at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:878)
at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:719)
</pre>
</div></div>

<p>Here is my Kerberos settings in "storm.yaml"</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>storm.principal.tolocal: "backtype.storm.security.auth.KerberosPrincipalToLocal"
storm.zookeeper.superACL: "sasl:storm"
java.security.auth.login.config: "/etc/storm/conf/storm_jaas.conf"
nimbus.admins:
  - "storm"
nimbus.supervisor.users:
  - "storm"
nimbus.authorizer: "backtype.storm.security.auth.authorizer.SimpleACLAuthorizer"
drpc.authorizer: "backtype.storm.security.auth.authorizer.DRPCSimpleACLAuthorizer"

ui.filter: "org.apache.hadoop.security.authentication.server.AuthenticationFilter"
ui.filter.params:
  "type": "kerberos"
  "kerberos.principal": "HTTP/slave"
  "kerberos.keytab": "/etc/security/keytabs/spnego.service.keytab"
  "kerberos.name.rules": "DEFAULT"
supervisor.enable: true
</pre>
</div></div>
<p>And "storm_jaas.conf"</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>StormServer {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   keyTab="/etc/security/keytabs/nimbus.service.keytab"
   storeKey=true
   useTicketCache=false
   principal="nimbus/slave@EXAMPLE.COM";
};
StormClient {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   keyTab="/etc/security/keytabs/storm.service.keytab"
   storeKey=true
   useTicketCache=false
   serviceName="nimbus"
   principal="storm@EXAMPLE.COM";
};
Client {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   keyTab="/etc/security/keytabs/storm.service.keytab"
   storeKey=true
   useTicketCache=false
   serviceName="zookeeper"
   principal="storm@EXAMPLE.COM";
};
</pre>
</div></div>

<p>By the way, the cluster is installed via Ambari 1.7.</p>

<p>Thanks in advanced.</p>

---
<details><summary><i>Originally reported by <a title="robinlin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robinlin">robinlin</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-771" target="_blank">Authentication with Kerberos</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2015-10-05T02:15:40+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robinlin" class="user-hover" rel="robinlin">robinlin</a> you need to provide a client storm.yaml and also client_jaas.conf<br/>
for the user robin under home dir create .storm/storm.yaml with these contents</p>

<p>nimbus.host: "nimbus"<br/>
storm.thrift.transport: "backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin"<br/>
java.security.auth.login.config: "client_jaas.conf"</p>

<p>and a client_jaas.conf with </p>

<p>StormClient {<br/>
       com.sun.security.auth.module.Krb5LoginModule required<br/>
       doNotPrompt=true<br/>
       useTicketCache=true<br/>
       serviceName="nimbus_server";<br/>
};</p>

<p>Also please send any questions to users or dev mailing lists instead of opening a JIRA. Here are the details <br/>
<a href="https://storm.apache.org/community.html" class="external-link" target="_blank" rel="nofollow noopener">https://storm.apache.org/community.html</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robinlin">robinlin</a>:</i>
<p>Thanks for your notification!!!</p>
