### ISSUE TITLE
[STORM-805] Supervisor crashes with 'org.apache.commons.io.FileExistsException: Destination already exists' error

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4646]
<p>Version : 0.9.4</p>

<p>All of a sudden supervisor crashed with error log below.</p>

<p>2015-04-29 16:48:24 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> 6d035728-bb86-486e-847e-94cd193a51db still hasn't started<br/>
2015-04-29 16:48:24 b.s.event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
org.apache.commons.io.FileExistsException: Destination '/somepath/storm-6-1430100813' already exists<br/>
at org.apache.commons.io.FileUtils.moveDirectory(FileUtils.java:2748) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at backtype.storm.daemon.supervisor$fn__5554.invoke(supervisor.clj:489) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.MultiFn.invoke(MultiFn.java:241) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__5474.invoke(supervisor.clj:374) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2809.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_75&#93;</span><br/>
2015-04-29 16:48:24 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2809.invoke(event.clj:48) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_75&#93;</span><br/>
2015-04-29 16:48:24 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down supervisor 4f00962b-2af0-4922-97f8-142db00fbddf</p>

---
<details><summary><i>Originally reported by <a title="Adrian Seungjin Lee" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj">sweetest_sj</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-805" target="_blank">Supervisor crashes with 'org.apache.commons.io.FileExistsException: Destination already exists' error</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:39+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanket991">sanket991</a>:</i>
<p>Is this issue not resolved by <a href="https://github.com/apache/storm/pull/400" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/400</a> ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj" class="user-hover" rel="sweetest_sj">Adrian Seungjin Lee</a> This is fixed in the trunk <a href="https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/supervisor.clj#L585" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/supervisor.clj#L585</a><br/>
<a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a> If its not already included we should add this to 0.9.5 and 0.10.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=harsha_ch" class="user-hover" rel="harsha_ch">sriharsha chintalapani</a> The link you mentioned is a commit for <a href="https://issues.apache.org/jira/browse/STORM-130" title="[Storm 0.8.2]: java.io.FileNotFoundException: File &#39;../stormconf.ser&#39; does not exist" class="issue-link" data-issue-key="STORM-130"><del>STORM-130</del></a>, which went out with 0.9.4.</p>

<p>This looks like a different issue. The stack trace posted by <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj" class="user-hover" rel="sweetest_sj">Adrian Seungjin Lee</a> points to the following line:</p>

<p><a href="https://github.com/apache/storm/blob/v0.9.4/storm-core/src/clj/backtype/storm/daemon/supervisor.clj#L489" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v0.9.4/storm-core/src/clj/backtype/storm/daemon/supervisor.clj#L489</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=harsha_ch" class="user-hover" rel="harsha_ch">sriharsha chintalapani</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a></p>

<p>There was an accident about two PRs, changeset of <a href="https://github.com/apache/storm/pull/401" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/401</a> and <a href="https://github.com/apache/storm/pull/418" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/418</a> is not same.<br/>
So it's merged to master well, but not properly merged with 0.9.x branch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> I was able to get the missing piece applied to 0.9.x-branch, but had to do so manually. See the following commit:</p>

<p><a href="https://github.com/apache/storm/commit/46b118a8d4f404d18babf706ec428131b558bd54" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/commit/46b118a8d4f404d18babf706ec428131b558bd54</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>I can see that this commit adds missing part to 0.9.x-branch and 0.10.x-branch doesn't have missing part. Great!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sweetest_sj" class="user-hover" rel="sweetest_sj">Adrian Seungjin Lee</a> Can you try reproducing this with 0.10-beta release . Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
