### ISSUE TITLE
[STORM-806] use storm.zookeeper.connection.timeout in storm-kafka ZkState when newCurator

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4647]
No Description

---
<details><summary><i>Originally reported by <a title="xiajun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-806" target="_blank">use storm.zookeeper.connection.timeout in storm-kafka ZkState when newCurator</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="xiajun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-06-22T05:48:40+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user tedxia opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-806" title="use storm.zookeeper.connection.timeout in storm-kafka ZkState when newCurator" class="issue-link" data-issue-key="STORM-806"><del>STORM-806</del></a>: use storm.zookeeper.connection.timeout in storm-kafka ZkState when newCurator</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/tedxia/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/tedxia/storm</a> use-zookeeper-connnection-timeout</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/540.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #540</p>

<hr />
<p>commit 9a43ad611bc1c27cf977f18d9953ff9505c6f1e4<br/>
Author: xiajun <xiajun@xiaomi.com><br/>
Date:   2015-04-29T13:11:08Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-806" title="use storm.zookeeper.connection.timeout in storm-kafka ZkState when newCurator" class="issue-link" data-issue-key="STORM-806"><del>STORM-806</del></a>: use storm.zookeeper.connection.timeout in storm-kafka ZkState when newCurator</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-97436721" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-97436721</a></p>

<p>    Build is failed from ZkCoordinatorTest.<br/>
    You should also provide Config.STORM_ZOOKEEPER_CONNECTION_TIMEOUT from ZkCoordinatorTest to let build passed.</p>

<p>    ```<br/>
private Map buildZookeeperConfig(TestingServer server) </p>
{
    Map conf = new HashMap();
    conf.put(Config.TRANSACTIONAL_ZOOKEEPER_PORT, server.getPort());
    conf.put(Config.TRANSACTIONAL_ZOOKEEPER_SERVERS, Arrays.asList("localhost"));
    conf.put(Config.STORM_ZOOKEEPER_SESSION_TIMEOUT, 20000);
    conf.put(Config.STORM_ZOOKEEPER_RETRY_TIMES, 3);
    conf.put(Config.STORM_ZOOKEEPER_RETRY_INTERVAL, 30);
    return conf;
}
<p>    ```</p>

<p>    I recommend you to run tests from dev. machine at least once before posting PR.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-97638980" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-97638980</a></p>

<p>    @HeartSaVioR sorry about the failure in test, I had added a new patch to fix this. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-97647385" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-97647385</a></p>

<p>    ```<br/>
    48495 <span class="error">&#91;Thread-229&#93;</span> ERROR backtype.storm.task.ShellBolt - Halting process: ShellBolt died. Command: <span class="error">&#91;ruby, tester_bolt.rb&#93;</span>, ProcessInfo pid:7283, name:2 exitCode:-1, errorString:(Unable to capture error stream) <br/>
    java.io.IOException: Stream closed<br/>
    	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at java.io.BufferedInputStream.read1(BufferedInputStream.java:283) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at java.io.BufferedReader.fill(BufferedReader.java:161) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~<span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    	at backtype.storm.multilang.JsonSerializer.readString(JsonSerializer.java:179) ~<span class="error">&#91;classes/:na&#93;</span><br/>
    	at backtype.storm.multilang.JsonSerializer.readMessage(JsonSerializer.java:166) ~<span class="error">&#91;classes/:na&#93;</span><br/>
    	at backtype.storm.multilang.JsonSerializer.readShellMsg(JsonSerializer.java:100) ~<span class="error">&#91;classes/:na&#93;</span><br/>
    	at backtype.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:99) ~<span class="error">&#91;classes/:na&#93;</span><br/>
    	at backtype.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:321) ~<span class="error">&#91;classes/:na&#93;</span><br/>
    	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_31&#93;</span><br/>
    ```</p>

<p>    Test failed due to the error above, someone have idea about this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-97656066" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-97656066</a></p>

<p>    30.1 is random failure of Kafka tests in Travis CI, which seems to be occurred with slow machine.<br/>
    <a href="https://issues.apache.org/jira/browse/STORM-798" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-798</a></p>

<p>    I can't see reason of failure about 30.2, since it doesn't print out test-report properly.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-97958707" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-97958707</a></p>

<p>    Btw, restricting log level to WARN level is only applied to storm-core now, since I didn't add logback-test.xml on any other modules. Other modules don't print out much so it can be fully printed without issues.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-98583320" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-98583320</a></p>

<p>    ```<br/>
    <span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
    <span class="error">&#91;INFO&#93;</span> Reactor Summary:<br/>
    <span class="error">&#91;INFO&#93;</span> <br/>
    <span class="error">&#91;INFO&#93;</span> Storm ............................................. SUCCESS <span class="error">&#91;0.550s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> maven-shade-clojure-transformer ................... SUCCESS <span class="error">&#91;0.840s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-maven-plugins ............................... SUCCESS <span class="error">&#91;1.063s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> multilang-javascript .............................. SUCCESS <span class="error">&#91;0.105s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> multilang-python .................................. SUCCESS <span class="error">&#91;0.102s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> multilang-ruby .................................... SUCCESS <span class="error">&#91;0.096s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> Storm Core ........................................ SUCCESS <span class="error">&#91;3:48.903s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-starter ..................................... SUCCESS <span class="error">&#91;2.032s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-kafka ....................................... SUCCESS <span class="error">&#91;57.901s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-hdfs ........................................ SUCCESS <span class="error">&#91;0.741s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-hbase ....................................... SUCCESS <span class="error">&#91;0.944s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-hive ........................................ SUCCESS <span class="error">&#91;50.312s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-jdbc ........................................ SUCCESS <span class="error">&#91;1.186s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-redis ....................................... SUCCESS <span class="error">&#91;0.209s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> storm-eventhubs ................................... SUCCESS <span class="error">&#91;2.440s&#93;</span><br/>
    <span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
    <span class="error">&#91;INFO&#93;</span> BUILD SUCCESS<br/>
    <span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
    <span class="error">&#91;INFO&#93;</span> Total time: 5:48.069s<br/>
    <span class="error">&#91;INFO&#93;</span> Finished at: Mon May 04 11:53:15 CST 2015<br/>
    <span class="error">&#91;INFO&#93;</span> Final Memory: 53M/925M<br/>
    ```<br/>
    Without run multilang_test.clj,  all tests pass on my machine. I don't think the change in stom-kafka will break multilang_test, will someone give some advice, thanks a lot.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-98587330" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-98587330</a></p>

<p>    Yes, you don't need to fix current tests since it seems to be random tests failure on slow machine.</p>

<p>    Btw, I'd like to fix kafka tests failure cause it has been occurred with very high probability.<br/>
    But I don't know about Kafka so I wish someone helps me or I will learn Kafka someday and try to fix.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-98589471" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-98589471</a></p>

<p>    I will try to fix <a href="https://issues.apache.org/jira/browse/STORM-798" title="storm-kafka tests are failing intermittently" class="issue-link" data-issue-key="STORM-798"><del>STORM-798</del></a> , but how about this patch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-98656146" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-98656146</a></p>

<p>    LGTM.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-104631119" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-104631119</a></p>

<p>    @ptgoetz Will you have a look at this, thank you.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/540#issuecomment-113997697" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540#issuecomment-113997697</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/540" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/540</a></p>
