### ISSUE TITLE
[STORM-834] Class cast exception Object to Iterable

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4674]
<p>This exception is happening after some hours of running. Unfortunately, nothing in the trace suggests the source of the error for further investigation.</p>

<p>2015-05-23T13:24:22.343-0400 b.s.util <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Iterable<br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:128) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:99) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>3441$fn</em><em>3453$fn</em>_3500.invoke(executor.clj:748) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_75&#93;</span><br/>
Caused by: java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Iterable<br/>
at backtype.storm.util$get_iterator.invoke(util.clj:867) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.daemon.executor$mk_task_receiver$fn__3364.invoke(executor.clj:397) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.disruptor$clojure_handler$reify__1447.onEvent(disruptor.clj:58) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:120) ~<span class="error">&#91;storm-core-0.9.3.jar:0.9.3&#93;</span><br/>
... 6 common frames omitted</p>

---
<details><summary><i>Originally reported by <a title="Jason Kania" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=longtimer">longtimer</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-834" target="_blank">Class cast exception Object to Iterable</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:35+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=longtimer" class="user-hover" rel="longtimer">Jason Kania</a><br/>
Which component throws ClastCastException? (Spout / Bolt / Acker / etc)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=longtimer">longtimer</a>:</i>
<p>The error is coming from a bolt as best I can tell from the log file in which the error is found, but the lack of detail in the exception means i can tell little else.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It might related to <a href="https://issues.apache.org/jira/browse/STORM-770" title="NullPointerException in consumeBatchToCursor" class="issue-link" data-issue-key="STORM-770"><del>STORM-770</del></a> since both things could be related to Disruptor Queue.  </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jbeard6">jbeard6</a>:</i>
<p>I've experienced this several times over the last few days when running a LocalCluster and have a misconfiguration in one of my bolts.  The log records the exception on the thread for an altogether different bolt, however, leading to a large amount of confusion.</p>

<p>I may be able to make a simple example that demonstrates the miscreant behavior.</p>

<p>Running storm 0.9.4 on OS X 10.10.3 using Oracle JDK jdk1.8.0_45.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Yes if you could create a reproducible use case that would be great.  The code in question is the task receiver, which processes tuples sent to a bolt.  It expects to see a list of tuples in a batch, not individual tuples. If an individual tuple showed up it would cause an exception like this.  There are a few places in the code where tuples are injected directly into a receiver queue, the tick tuple, and the metrics tick are the ones that come to mind, but all of them explicitly insert a list for the single tuple they put in.  There is also the possibility that something in the batching code is not handling one use case properly and not putting in a list, but without a reproducible use case it is really hard to tell.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=longtimer">longtimer</a>:</i>
<p>I continue to get this happening after running for a while, but am at a loss as to the cause. I now have several different topologies and several have the error happening, but not all. I was wondering if some code could be put in to check on the insertion side of the storm queues to ensure what is being put on is a valid type? Does this make sense?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=longtimer" class="user-hover" rel="longtimer">Jason Kania</a>,</p>

<p>You could put in a check like that into DisruptorQueue.java.</p>

<p>I am not sure which version of storm you are using, but I would insert it into the publish method <a href="https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java#L496" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java#L496</a></p>

<p>Be aware that there are a lot of unit tests that will probably fail with this change.  Another option is to modify the code around consumeBatchToCurser to catch the exception and print out more information about the object causing the issues.</p>

<p><a href="https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java#L425-L452" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java#L425-L452</a></p>

<p>perhaps changing it to something like the following that adds some debug about what the event is when an exception happens.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">    <span class="code-keyword">private</span> void consumeBatchToCursor(<span class="code-object">long</span> cursor, EventHandler<<span class="code-object">Object</span>> handler) {
<span class="code-keyword">for</span> (<span class="code-object">long</span> curr = _consumer.get() + 1; curr <= cursor; curr++) {
    <span class="code-object">Object</span> o = <span class="code-keyword">null</span>;
    <span class="code-keyword">try</span> {
AtomicReference<<span class="code-object">Object</span>> mo = _buffer.get(curr);
o = mo.getAndSet(<span class="code-keyword">null</span>);
<span class="code-keyword">if</span> (o == INTERRUPT) {
    <span class="code-keyword">throw</span> <span class="code-keyword">new</span> InterruptedException(<span class="code-quote">"Disruptor processing interrupted"</span>);
} <span class="code-keyword">else</span> <span class="code-keyword">if</span> (o == <span class="code-keyword">null</span>) {
    LOG.error(<span class="code-quote">"NULL found in {}:{}"</span>, <span class="code-keyword">this</span>.getName(), cursor);
} <span class="code-keyword">else</span> {
    handler.onEvent(o, curr, curr == cursor);
    <span class="code-keyword">if</span> (_enableBackpressure && _cb != <span class="code-keyword">null</span> && (_metrics.writePos() - curr + _overflowCount.get()) <= _lowWaterMark) {
<span class="code-keyword">try</span> {
    <span class="code-keyword">if</span> (_throttleOn) {
_throttleOn = <span class="code-keyword">false</span>;
_cb.lowWaterMark();
    }
} <span class="code-keyword">catch</span> (Exception e) {
    <span class="code-keyword">throw</span> <span class="code-keyword">new</span> RuntimeException(<span class="code-quote">"Exception during calling lowWaterMark callback!"</span>);
}
    }
}
    } <span class="code-keyword">catch</span> (Exception e) {
<span class="code-keyword">throw</span> <span class="code-keyword">new</span> RuntimeException(<span class="code-quote">"Error <span class="code-keyword">while</span> processing event ("</span>+(o != <span class="code-keyword">null</span> ? o.getClass() : <span class="code-quote">"NULL"</span>) +<span class="code-quote">") "</span>+o, e);
    }
}
_consumer.set(cursor);
    }
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bbaugher">bbaugher</a>:</i>
<p>I've actually seen this issue when I had slf4j-log4j12 in my topology which seems to conflict with log4j-slf4j-impl from storm. Excluding it fixed my issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=johnbaba">johnbaba</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lonerzzz" class="user-hover" rel="lonerzzz">Jason Kania</a> In fact I come into the same problem before, but it haven't happened after I rebuild the topology and rebuild the latest storm. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
