### ISSUE TITLE
[STORM-836] DPRC request failed after DRPC server restarted

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4676]
<p>When the DRPC server was killed and then restarted, the DRPC client would throw a DRPCExecutionException (msg:Request failed) for a while, off and on.</p>

<p>Here is my client code:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">DRPCClient client = <span class="code-keyword">new</span> DRPCClient(<span class="code-quote">"hd181"</span>, 3772);

<span class="code-keyword">for</span> (<span class="code-object">int</span> i = 0; i < 100; ++i) {
	<span class="code-object">System</span>.out.println(client.execute(<span class="code-quote">"drpcFunc"</span>, <span class="code-quote">"aaa"</span>));
}
</pre>
</div></div>

<p>and the error messages:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Exclamation-6:aaa!!!
Exception in thread <span class="code-quote">"main"</span> DRPCExecutionException(msg:Request failed)
	at backtype.storm.generated.DistributedRPC$execute_result.read(DistributedRPC.java:904)
	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78)
	at backtype.storm.generated.DistributedRPC$Client.recv_execute(DistributedRPC.java:92)
	at backtype.storm.generated.DistributedRPC$Client.execute(DistributedRPC.java:78)
	at backtype.storm.utils.DRPCClient.execute(DRPCClient.java:71)
	at com.enjoyor.storm.kafka.example.DRPCTest.main(DRPCTest.java:18)
</pre>
</div></div>

<p>As you can see, the client can get few valid results at beginning and then get a failed request.</p>

<p>This problem would last about 10 minutes after restarting the server, and then the server would be back to normal.</p>

---
<details><summary><i>Originally reported by <a title="Yohn Wei" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Yohn">Yohn</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-836" target="_blank">DPRC request failed after DRPC server restarted</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Yohn Wei" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Yohn">Yohn</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:42+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
