### ISSUE TITLE
[STORM-840] My supervisor crashes when I kill a topology

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4680]
<p>Hello,<br/>
I run 3 topologies inside my cluster.<br/>
Sometimes, when I kill one of them (not one specific). One supervisor goes down and restart. After few restart, it become stable.<br/>
The topology process is in "Zombie state" in the process list.</p>

<p>In version 0.9.3, all the supervisors crashed and couldn't restart. To resolve this, I had to "rm -fr <storm-local-dir>/workers/"<br/>
So I migrate to 0.9.4 (I thought that was <a href="https://issues.apache.org/jira/browse/STORM-682" title="Supervisor local worker state corrupted and failing to start." class="issue-link" data-issue-key="STORM-682"><del>STORM-682</del></a>).</p>

<p>Now it continues but no all the times, but occasionally.</p>

<p>I have these logs inside supervisor.log:<br/>
2015-05-29 15:01:42 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Removing code for storm id nlp-11-1432906756<br/>
2015-05-29 15:01:42 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Removing code for storm id nlp-11-1432906756<br/>
2015-05-29 15:01:42 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down and clearing state for id 355af307-fafc-43a8-865d-0dfbf9baee33. Current supervisor time: 1432911702. State: :disallowed, Heartbeat: #backtype.storm.daemon.common.WorkerHeartbeat{:time-secs 1432911702, :storm-id "nlp-11-1432906756", :executors #</p>
{[2 2] [3 3] [-1 -1] [1 1]}, :port 6700}<br/>
2015-05-29 15:01:42 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down and clearing state for id 355af307-fafc-43a8-865d-0dfbf9baee33. Current supervisor time: 1432911702. State: :disallowed, Heartbeat: #backtype.storm.daemon.common.WorkerHeartbeat{:time-secs 1432911702, :storm-id "nlp-11-1432906756", :executors #{[2 2] [3 3] [-1 -1] [1 1]}
<p>, :port 6700}<br/>
2015-05-29 15:01:42 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down 90f0964b-c48c-4cbc-9d1c-57119c56e99c:355af307-fafc-43a8-865d-0dfbf9baee33<br/>
2015-05-29 15:01:42 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down 90f0964b-c48c-4cbc-9d1c-57119c56e99c:355af307-fafc-43a8-865d-0dfbf9baee33<br/>
2015-05-29 15:01:42 b.s.event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.io.IOException: Cannot run program "kill" (in directory "."): error=2, No such file or directory<br/>
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at java.lang.Runtime.exec(Runtime.java:620) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:254) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:319) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at backtype.storm.util$exec_command_BANG_.invoke(util.clj:386) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.util$send_signal_to_process.invoke(util.clj:415) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.util$kill_process_with_sig_term.invoke(util.clj:426) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.daemon.supervisor$shutdown_worker.invoke(supervisor.clj:197) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:267) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:397) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2809.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_45&#93;</span><br/>
Caused by: java.io.IOException: error=2, No such file or directory<br/>
at java.lang.UNIXProcess.forkAndExec(Native Method) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
... 19 common frames omitted<br/>
2015-05-29 15:01:42 b.s.event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.io.IOException: Cannot run program "kill" (in directory "."): error=2, No such file or directory<br/>
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at java.lang.Runtime.exec(Runtime.java:620) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:254) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:319) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at backtype.storm.util$exec_command_BANG_.invoke(util.clj:386) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.util$send_signal_to_process.invoke(util.clj:415) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.util$kill_process_with_sig_term.invoke(util.clj:426) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.daemon.supervisor$shutdown_worker.invoke(supervisor.clj:197) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:267) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:397) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2809.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_45&#93;</span><br/>
Caused by: java.io.IOException: error=2, No such file or directory<br/>
at java.lang.UNIXProcess.forkAndExec(Native Method) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~<span class="error">&#91;na:1.8.0_45&#93;</span><br/>
... 19 common frames omitted<br/>
2015-05-29 15:01:42 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2809.invoke(event.clj:48) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_45&#93;</span><br/>
2015-05-29 15:01:42 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2809.invoke(event.clj:48) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_45&#93;</span><br/>
2015-05-29 15:01:42 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down supervisor 90f0964b-c48c-4cbc-9d1c-57119c56e99c<br/>
2015-05-29 15:01:42 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down supervisor 90f0964b-c48c-4cbc-9d1c-57119c56e99c<br/>
2015-05-29 15:01:42 b.s.event <span class="error">&#91;INFO&#93;</span> Event manager interrupted<br/>
2015-05-29 15:01:42 b.s.event <span class="error">&#91;INFO&#93;</span> Event manager interrupted<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:host.name=storm-supervisor-01<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:java.version=1.8.0_45<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:java.vendor=Oracle Corporation<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:java.home=/usr/lib/jvm/jre-8-oracle-x64/jre<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:java.class.path=/usr/share/apache-storm-0.9.4/lib/zookeeper-3.4.6.jar:/usr/share/apache-storm-0.9.4/lib/hiccup-0.3.6.jar:/usr/share/apache-storm-0.9.4/lib/chill-java-0.3.5.jar:/usr/share/apache-storm-0.9.4/lib/commons-exec-1.1.jar:/usr/share/apache-storm-0.9.4/lib/tools.macro-0.1.0.jar:/usr/share/apache-storm-0.9.4/lib/jgrapht-core-0.9.0.jar:/usr/share/apache-storm-0.9.4/lib/ring-servlet-0.3.11.jar:/usr/share/apache-storm-0.9.4/lib/clout-1.0.1.jar:/usr/share/apache-storm-0.9.4/lib/storm-core-0.9.4.jar:/usr/share/apache-storm-0.9.4/lib/asm-4.0.jar:/usr/share/apache-storm-0.9.4/lib/tools.cli-0.2.4.jar:/usr/share/apache-storm-0.9.4/lib/disruptor-2.10.1.jar:/usr/share/apache-storm-0.9.4/lib/log4j-over-slf4j-1.6.6.jar:/usr/share/apache-storm-0.9.4/lib/clj-time-0.4.1.jar:/usr/share/apache-storm-0.9.4/lib/slf4j-api-1.7.5.jar:/usr/share/apache-storm-0.9.4/lib/clojure-1.5.1.jar:/usr/share/apache-storm-0.9.4/lib/core.incubator-0.1.0.jar:/usr/share/apache-storm-0.9.4/lib/json-simple-1.1.jar:/usr/share/apache-storm-0.9.4/lib/logback-classic-1.0.13.jar:/usr/share/apache-storm-0.9.4/lib/servlet-api-2.5.jar:/usr/share/apache-storm-0.9.4/lib/logback-core-1.0.13.jar:/usr/share/apache-storm-0.9.4/lib/jetty-6.1.26.jar:/usr/share/apache-storm-0.9.4/lib/clj-stacktrace-0.2.2.jar:/usr/share/apache-storm-0.9.4/lib/ring-devel-0.3.11.jar:/usr/share/apache-storm-0.9.4/lib/minlog-1.2.jar:/usr/share/apache-storm-0.9.4/lib/kryo-2.21.jar:/usr/share/apache-storm-0.9.4/lib/compojure-1.1.3.jar:/usr/share/apache-storm-0.9.4/lib/commons-codec-1.6.jar:/usr/share/apache-storm-0.9.4/lib/tools.logging-0.2.3.jar:/usr/share/apache-storm-0.9.4/lib/ring-jetty-adapter-0.3.11.jar:/usr/share/apache-storm-0.9.4/lib/jetty-util-6.1.26.jar:/usr/share/apache-storm-0.9.4/lib/joda-time-2.0.jar:/usr/share/apache-storm-0.9.4/lib/jline-2.11.jar:/usr/share/apache-storm-0.9.4/lib/commons-logging-1.1.3.jar:/usr/share/apache-storm-0.9.4/lib/reflectasm-1.07-shaded.jar:/usr/share/apache-storm-0.9.4/lib/carbonite-1.4.0.jar:/usr/share/apache-storm-0.9.4/lib/snakeyaml-1.11.jar:/usr/share/apache-storm-0.9.4/lib/objenesis-1.2.jar:/usr/share/apache-storm-0.9.4/lib/ring-core-1.1.5.jar:/usr/share/apache-storm-0.9.4/lib/commons-io-2.4.jar:/usr/share/apache-storm-0.9.4/lib/commons-fileupload-1.2.1.jar:/usr/share/apache-storm-0.9.4/lib/math.numeric-tower-0.0.1.jar:/usr/share/apache-storm-0.9.4/lib/commons-lang-2.5.jar:/usr/share/apache-storm-0.9.4/conf<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:java.library.path=/usr/local/lib:/opt/local/lib:/usr/lib<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:java.io.tmpdir=/tmp<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:java.compiler=<NA><br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:os.name=Linux<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:os.arch=amd64<br/>
2015-05-29 15:01:53 o.a.s.z.ZooKeeper <span class="error">&#91;INFO&#93;</span> Client environment:os.version=3.16.0-0.bpo.4-amd64<br/>
...</p>

---
<details><summary><i>Originally reported by <a title="Damien DESMARETS" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zaide">zaide</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-840" target="_blank">My supervisor crashes when I kill a topology</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2015-10-09T02:09:12+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>:</i>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">  java.io.IOException: Cannot run program <span class="code-quote">"kill"</span> (in directory <span class="code-quote">"."</span>): error=2, No such file or directory
</pre>
</div></div>

<p>looks like  unable to find "kill" command .</p>

<p>Clould you find "kill"  in your docker instance? <br/>
Like:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">  [root@3c46f330f114 /usr/share]# which kill
  /usr/bin/kill
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zaide">zaide</a>:</i>
<p>Hello,<br/>
Yes I finally found the problem.<br/>
kill was the built-in inside bash. After installing procps package it works like a charm!</p>

<p>Sorry for the noise. You can close the ticket or check in the pre-require that kill exists <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/wink.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<p>Damien</p>
