### ISSUE TITLE
[STORM-848] Clean up dependencies and shade as much as possible

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4688]
<p>To help with rolling upgrades in the future we should shade as much of our dependencies as possible, so that customers can include their own versions of things.</p>

---
<details><summary><i>Originally reported by <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-848" target="_blank">Clean up dependencies and shade as much as possible</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-06-05T17:39:58+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-848" title="Clean up dependencies and shade as much as possible" class="issue-link" data-issue-key="STORM-848"><del>STORM-848</del></a> Shade external dependencies</p>

<p>    Shading following dependencies:<br/>
    org.apache.httpcomponents:http*<br/>
    org.apache.zookeeper:zookeeper<br/>
    org.apache.curator:*<br/>
    com.twitter:carbonite<br/>
    com.twitter:chill-java<br/>
    org.objenesis:objenesis<br/>
    org.tukaani:xz<br/>
    org.yaml:snakeyaml<br/>
    org.jgrapht:jgrapht-core<br/>
    commons-httpclient:commons-httpclient<br/>
    org.apache.commons:commons-compress<br/>
    org.apache.commons:commons-exec<br/>
    commons-io:commons-io<br/>
    commons-codec:commons-codec<br/>
    commons-fileupload:commons-fileupload<br/>
    commons-lang:commons-lang<br/>
    com.googlecode.json-simple:json-simple<br/>
    org.clojure:math.numeric-tower<br/>
    org.clojure:tools.cli<br/>
    org.clojure:tools.macro<br/>
    joda-time:joda-time</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-848" title="Clean up dependencies and shade as much as possible" class="issue-link" data-issue-key="STORM-848"><del>STORM-848</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/577.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #577</p>

<hr />
<p>commit 9ecf26cfb1b29ef369a4a99de85e2237645306c3<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-06-04T14:35:49Z</p>

<p>    Shade external dependencies</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-108971727" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-108971727</a></p>

<p>    Can we also shade jetty? Also why there are new dependency on some connectors.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-108989857" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-108989857</a></p>

<p>    @Parth-Brahmbhatt Primarily, anything that's getting directly called from withing clojure is hard to shade. Hence (disruptor, jetty..) etc are not shaded. As such newer version of jetty are self-shaded ( the packages are different.). But it would be a much bigger change to accomplish.</p>

<p>    As the storm-core is shading these dependencies, they need to be called out explicitly by connectors now if they implicitly depended on storm-core so far. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-108990526" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-108990526</a></p>

<p>    I agree with @Parth-Brahmbhatt. I think for components in "/external" we should use the use the shaded classes in storm-core instead of manually adding the dependency. Doing so is just a matter of changing import statements.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-108990802" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-108990802</a></p>

<p>    @kishorvpatil what issues did you run into when you shaded Jetty?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-108991541" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-108991541</a></p>

<p>    @ptgoetz my problem with that is the distribution mechanism is different for external from what it is for storm proper.  Say I create a topology jar with storm-hdfs in it.  At some point in the future storm upgrades the version of snake.yaml and it is a non-backwards compatible change.  Now my topology will not run on a newer version of storm.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-108998003" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-108998003</a></p>

<p>    @revans2 Good point.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-109023252" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-109023252</a></p>

<p>    @ptgoetz  I get following exceptions when I try to shade Jetty<br/>
    ```Console<br/>
    Compiling storm.starter.clj.word-count to /home/kpatil/commun/incubator-storm/examples/storm-starter/target/classes<br/>
    Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes, compiling:(word_count.clj:16:1)<br/>
    	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)<br/>
    	at clojure.lang.Compiler.compile1(Compiler.java:7226)<br/>
    	at clojure.lang.Compiler.compile1(Compiler.java:7216)<br/>
    	at clojure.lang.Compiler.compile(Compiler.java:7292)<br/>
    	at clojure.lang.RT.compile(RT.java:398)<br/>
    	at clojure.lang.RT.load(RT.java:438)<br/>
    	at clojure.lang.RT.load(RT.java:411)<br/>
    	at clojure.core$load$fn__5066.invoke(core.clj:5641)<br/>
    	at clojure.core$load.doInvoke(core.clj:5640)<br/>
    	at clojure.lang.RestFn.invoke(RestFn.java:408)<br/>
    	at clojure.core$load_one.invoke(core.clj:5446)<br/>
    	at clojure.core$compile$fn__5071.invoke(core.clj:5652)<br/>
    	at clojure.core$compile.invoke(core.clj:5651)<br/>
    	at clojure.lang.Var.invoke(Var.java:379)<br/>
    	at clojure.lang.Compile.main(Compile.java:81)<br/>
    Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes<br/>
    	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:286)<br/>
    	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:239)<br/>
    	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:317)<br/>
    	at java.util.jar.JarVerifier.update(JarVerifier.java:228)<br/>
    	at java.util.jar.JarFile.initializeVerifier(JarFile.java:348)<br/>
    	at java.util.jar.JarFile.getInputStream(JarFile.java:415)<br/>
    	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:775)<br/>
    	at sun.misc.Resource.cachedInputStream(Resource.java:77)<br/>
    	at sun.misc.Resource.getByteBuffer(Resource.java:160)<br/>
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:436)<br/>
    	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)<br/>
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)<br/>
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)<br/>
    	at java.security.AccessController.doPrivileged(Native Method)<br/>
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)<br/>
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)<br/>
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)<br/>
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)<br/>
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)<br/>
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)<br/>
    	at java.lang.Class.forName0(Native Method)<br/>
    	at java.lang.Class.forName(Class.java:190)<br/>
    	at storm.starter.clj.word_count$loading_<em>4958</em><em>auto</em>_.invoke(word_count.clj:16)<br/>
    	at clojure.lang.AFn.applyToHelper(AFn.java:152)<br/>
    	at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
    	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3553)</p>

<p>    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-109025180" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-109025180</a></p>

<p>    can you try adding following to the shade-plugin part. See <a href="http://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html" class="external-link" target="_blank" rel="nofollow noopener">http://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html</a> for a full example.</p>

<p>      <filters><br/>
    <filter><br/>
<artifact><b>:</b></artifact><br/>
<excludes><br/>
    <exclude>META-INF/*.SF</exclude><br/>
    <exclude>META-INF/*.DSA</exclude><br/>
    <exclude>META-INF/*.RSA</exclude><br/>
</excludes><br/>
    </filter><br/>
</filters></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-109041007" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-109041007</a></p>

<p>    @kishorvpatil I can't reproduce it. What does your shade config for jetty look like?</p>

<p>    Here are the sections I added to test:</p>

<p>    The include:<br/>
    ```xml<br/>
    <include>org.eclipse.jetty:*</include><br/>
    ```</p>

<p>    The relocation:<br/>
    ```xml<br/>
 <pattern>org.eclipse.jetty</pattern><br/>
<shadedPattern>org.apache.storm.jetty</shadedPattern><br/>
    </relocation><br/>
    ```</p>

<p>    I left out the filter @Parth-Brahmbhatt mentioned, expecting to get the error you did, but everything succeeded.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-109043828" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-109043828</a></p>

<p>    I tried What @Parth-Brahmbhatt  suggested to successfully build it. Testing it now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-109056014" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-109056014</a></p>

<p>    Thank you @ptgoetz. The changes worked. And Jetty is shaded now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-109057662" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-109057662</a></p>

<p>    Thanks @kishorvpatil!</p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-109058294" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-109058294</a></p>

<p>    +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-109301657" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-109301657</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/577" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil" class="user-hover" rel="kishorvpatil">Kishor Patil</a> whats the reason behind making depedencies to be at compile time especially commons-lang. We've hdfs SPNEGO filter as a dependency in storm-core for security and to use it in ui.filter. By removing commons-lang we are getting into class not found issues with this lib</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a>,I hava a patch for your problem <a href="https://github.com/apache/storm/pull/600" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-115080809" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-115080809</a></p>

<p>    With this patch, there are a lot of ClassNotFoundException when nimbus or ui load Plugins such as AutoHdfs, what can we do to fix this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-115269553" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-115269553</a></p>

<p>    @tedxia I responded on your pull request #600 </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/577#issuecomment-115465087" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/577#issuecomment-115465087</a></p>

<p>    @revans2 thanks for your replay.</p>
