### ISSUE TITLE
[STORM-857] Supervisor process fails to write log metadata to YAML file when "supervisor.run.worker.as.user" is enabled

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4697]
<p>When "supervisor.run.worker.as.user" is set to "true" in a kerberized cluster, the supervisor process fails to write log metadata to a YAML file, resulting in the supervisor to shutdown. "/var/log/storm/supervisor.log" shows the following exception:</p>

<p>2015-06-09 16:59:10 b.s.event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.io.FileNotFoundException: /var/log/storm/metadata/test-1-1433861936-worker-6701.yaml (No such file or directory)<br/>
at java.io.FileOutputStream.open0(Native Method) ~<span class="error">&#91;na:1.8.0_40&#93;</span><br/>
at java.io.FileOutputStream.open(FileOutputStream.java:270) ~<span class="error">&#91;na:1.8.0_40&#93;</span><br/>
at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~<span class="error">&#91;na:1.8.0_40&#93;</span><br/>
at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~<span class="error">&#91;na:1.8.0_40&#93;</span><br/>
at java.io.FileWriter.<init>(FileWriter.java:90) ~<span class="error">&#91;na:1.8.0_40&#93;</span><br/>
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~<span class="error">&#91;na:1.8.0_40&#93;</span><br/>
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~<span class="error">&#91;na:1.8.0_40&#93;</span><br/>
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~<span class="error">&#91;na:1.8.0_40&#93;</span><br/>
at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~<span class="error">&#91;na:1.8.0_40&#93;</span>at clojure.lang.Reflector.invokeConstructor(Reflector.java:180) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at backtype.storm.daemon.supervisor$write_log_metadata_to_yaml_file_BANG_.invoke(supervisor.clj:583) ~<span class="error">&#91;storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2&#93;</span>at backtype.storm.daemon.supervisor$write_log_metadata_BANG_.invoke(supervisor.clj:598) ~<span class="error">&#91;storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2&#93;</span>at backtype.storm.daemon.supervisor$fn_<em>5912.invoke(supervisor.clj:679) ~<span class="error">&#91;storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2&#93;</span>at clojure.lang.MultiFn.invoke(MultiFn.java:241) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at backtype.storm.daemon.supervisor$sync_processes$iter</em><em>5762</em><em>5766$fn</em><em>5767.invoke(supervisor.clj:386) ~<span class="error">&#91;storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2&#93;</span>at clojure.lang.LazySeq.sval(LazySeq.java:42) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.lang.LazySeq.seq(LazySeq.java:60) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.lang.RT.seq(RT.java:484) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.core$seq.invoke(core.clj:133) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.core$dorun.invoke(core.clj:2780) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.core$doall.invoke(core.clj:2796) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:374) ~<span class="error">&#91;storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2&#93;</span>at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.core$partial$fn</em>_4190.doInvoke(core.clj:2396) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span>at clojure.lang.RestFn.invoke(RestFn.java:397) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__4027.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_40&#93;</span><br/>
2015-06-09 16:59:10 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:322) <span class="error">&#91;storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__4027.invoke(event.clj:48) <span class="error">&#91;storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_40&#93;</span></p>

<p>When creating the "/var/log/storm/metadata" directory manually, everything works fine. Apparently, lines 599-601 in "supervisor.clj" seem to be the culprit, which create the metadata directory only if the  "supervisor.run.worker.as.user" flag is disabled:</p>

<p>(when (and (not (conf SUPERVISOR-RUN-WORKER-AS-USER))<br/>
      (not (.exists (.getParentFile file))))<br/>
     (.mkdirs (.getParentFile file)))</p>

---
<details><summary><i>Originally reported by <a title="Gunnar Schulze" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gschulze">gschulze</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-857" target="_blank">Supervisor process fails to write log metadata to YAML file when "supervisor.run.worker.as.user" is enabled</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Derek Dagit" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-07-16T21:55:19+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user d2r opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/586" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/586</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-857" title="Supervisor process fails to write log metadata to YAML file when "supervisor.run.worker.as.user" is enabled" class="issue-link" data-issue-key="STORM-857"><del>STORM-857</del></a> create logs metadata dir when running securely</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/d2r/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/d2r/storm</a> storm-857-mkdir-metadata-run-as-user</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/586.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/586.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #586</p>

<hr />
<p>commit f021d1fd0db14c4d446813783be908596e816be8<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2015-06-09T23:31:38Z</p>

<p>    create logs metadata dir when running securely</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/586#issuecomment-113996119" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/586#issuecomment-113996119</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dossett@gmail.com">dossett@gmail.com</a>:</i>
<p>My team has run into this issue several times since all of our clusters use kerberos.  There are manual workarounds, but a fix for the .10 release would be great!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/586#issuecomment-122085853" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/586#issuecomment-122085853</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/586" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/586</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit" class="user-hover" rel="dagit">Derek Dagit</a>,</p>

<p>I merged this into master.</p>
