### ISSUE TITLE
[STORM-858] nimbus start failed due to ThriftServer startup NPE

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4698]
<p>When I run storm with master, I got NPE when nimbus start in ThriftServer<br/>
```<br/>
5213 <span class="error">&#91;main&#93;</span> ERROR b.s.s.a.ThriftServer - ThriftServer is being stopped due to: java.lang.NullPointerException<br/>
java.lang.NullPointerException<br/>
at backtype.storm.security.auth.AuthUtils.get(AuthUtils.java:271) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin.getServerTransportFactory(KerberosSaslTransportPlugin.java:77) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.SaslTransportPlugin.getServer(SaslTransportPlugin.java:71) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.ThriftServer.serve(ThriftServer.java:70) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1370) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1394) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.daemon.nimbus$_main.invoke(nimbus.clj:1417) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:152) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:144) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at backtype.storm.daemon.nimbus.main(Unknown Source) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
```<br/>
After add some debug log, I found that in AuthUtils::getConfiguration, It get "java.security.auth.login.config" from storm_conf, but there is never someone had put "java.security.auth.login.config" to storm_config,(<a href="https://github.com/apache/storm/blob/master/storm-core/src/jvm/backtype/storm/security/auth/AuthUtils.java#L55" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/jvm/backtype/storm/security/auth/AuthUtils.java#L55</a>), and then login_conf will always be null, so (<a href="https://github.com/apache/storm/blob/master/storm-core/src/jvm/backtype/storm/security/auth/kerberos/KerberosSaslTransportPlugin.java#L77" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/jvm/backtype/storm/security/auth/kerberos/KerberosSaslTransportPlugin.java#L77</a>) will got NPE;</p>

---
<details><summary><i>Originally reported by <a title="xiajun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-858" target="_blank">nimbus start failed due to ThriftServer startup NPE</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="xiajun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2015-10-09T02:08:44+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user tedxia opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/587" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/587</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-858" title="nimbus start failed due to ThriftServer startup NPE" class="issue-link" data-issue-key="STORM-858"><del>STORM-858</del></a>: add "java.security.auth.login.config" to storm config</p>

<p>    PR for <a href="https://issues.apache.org/jira/browse/STORM-858" title="nimbus start failed due to ThriftServer startup NPE" class="issue-link" data-issue-key="STORM-858"><del>STORM-858</del></a>(<a href="https://issues.apache.org/jira/browse/STORM-858" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-858</a>)</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/tedxia/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/tedxia/storm</a> add-auth-config-to-storm-config</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/587.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/587.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #587</p>

<hr />
<p>commit 18973737a3d4743dffc63db3c4a6df70669ad176<br/>
Author: xiajun <xiajun@xiaomi.com><br/>
Date:   2015-06-10T03:42:49Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-858" title="nimbus start failed due to ThriftServer startup NPE" class="issue-link" data-issue-key="STORM-858"><del>STORM-858</del></a>: add "java.security.auth.login.config" to storm config</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Friendly reminder: It would be better to describe why you marked this as "won't fix", and close relevant PR.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/587" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/587</a></p>
