### ISSUE TITLE
[STORM-863] UI report TTransportException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4703]
No Description

---
<details><summary><i>Originally reported by <a title="xiajun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-863" target="_blank">UI report TTransportException</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:11+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>:</i>
<p>When I use storm with kerberos authentication, UI sometimes report TTransportException, such as:<br/>
```<br/>
<span class="error">&#91;qtp1237749363-31&#93;</span> ERROR b.s.s.a.k.KerberosSaslTransportPlugin - Client failed to open SaslClientTransport to interact with a server during session initiation: org.apache.thrift7.transport.TTransportException: Peer indicated failure: GSS initiate failed<br/>
org.apache.thrift7.transport.TTransportException: Peer indicated failure: GSS initiate failed<br/>
at org.apache.thrift7.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:199) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslTransport.open(TSaslTransport.java:277) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslClientTransport.open(TSaslClientTransport.java:37) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$1.run(KerberosSaslTransportPlugin.java:146) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$1.run(KerberosSaslTransportPlugin.java:142) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.security.AccessController.doPrivileged(Native Method) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at javax.security.auth.Subject.doAs(Subject.java:396) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin.connect(KerberosSaslTransportPlugin.java:141) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:48) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:103) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.ThriftClient.<init>(ThriftClient.java:72) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:69) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:75) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.ui.core$cluster_summary.invoke(core.clj:546) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.ui.core$fn__9894.invoke(core.clj:947) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at compojure.core$make_route$fn__4484.invoke(core.clj:93) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at compojure.core$if_route$fn__4472.invoke(core.clj:39) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at compojure.core$if_method$fn__4465.invoke(core.clj:24) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at compojure.core$routing$fn__4490.invoke(core.clj:106) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at clojure.core$some.invoke(core.clj:2515) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at compojure.core$routing.doInvoke(core.clj:106) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at clojure.lang.RestFn.applyTo(RestFn.java:139) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:626) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at compojure.core$routes$fn__4494.invoke(core.clj:111) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.json$wrap_json_params$fn__9178.invoke(json.clj:56) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.multipart_params$wrap_multipart_params$fn__5544.invoke(multipart_params.clj:103) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.reload$wrap_reload$fn__6271.invoke(reload.clj:22) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.ui.core$catch_errors$fn__9971.invoke(core.clj:1055) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.keyword_params$wrap_keyword_params$fn__5477.invoke(keyword_params.clj:27) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.nested_params$wrap_nested_params$fn__5516.invoke(nested_params.clj:65) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.params$wrap_params$fn__5449.invoke(params.clj:55) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.multipart_params$wrap_multipart_params$fn__5544.invoke(multipart_params.clj:103) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.flash$wrap_flash$fn__5725.invoke(flash.clj:14) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.session$wrap_session$fn__5714.invoke(session.clj:43) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.middleware.cookies$wrap_cookies$fn__5645.invoke(cookies.clj:160) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.util.servlet$make_service_method$fn__5362.invoke(servlet.clj:127) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.util.servlet$servlet$fn__5366.invoke(servlet.clj:136) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHolder.handle(ServletHolder.java:654) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.Server.handle(Server.java:369) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.http.HttpParser.parseNext(HttpParser.java:644) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
```<br/>
and nimbus report <br/>
```<br/>
1266878 <span class="error">&#91;pool-7-thread-62&#93;</span> ERROR o.a.t.t.TSaslTransport - SASL negotiation failure<br/>
javax.security.sasl.SaslException: GSS initiate failed<br/>
at com.sun.security.sasl.gsskerb.GssKrb5Server.evaluateResponse(GssKrb5Server.java:159) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at org.apache.thrift7.transport.TSaslTransport$SaslParticipant.evaluateChallengeOrResponse(TSaslTransport.java:539) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslTransport.open(TSaslTransport.java:283) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory$1.run(KerberosSaslTransportPlugin.java:196) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory$1.run(KerberosSaslTransportPlugin.java:193) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.security.AccessController.doPrivileged(Native Method) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at javax.security.auth.Subject.doAs(Subject.java:396) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory.getTransport(KerberosSaslTransportPlugin.java:192) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:268) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
Caused by: org.ietf.jgss.GSSException: Failure unspecified at GSS-API level (Mechanism level: Request is a replay (34))<br/>
at sun.security.jgss.krb5.Krb5Context.acceptSecContext(Krb5Context.java:741) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:323) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:267) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at com.sun.security.sasl.gsskerb.GssKrb5Server.evaluateResponse(GssKrb5Server.java:137) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
... 13 more<br/>
Caused by: sun.security.krb5.internal.KrbApErrException: Request is a replay (34)<br/>
at sun.security.krb5.KrbApReq.authenticate(KrbApReq.java:298) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at sun.security.krb5.KrbApReq.<init>(KrbApReq.java:134) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at sun.security.jgss.krb5.InitSecContextToken.<init>(InitSecContextToken.java:79) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at sun.security.jgss.krb5.Krb5Context.acceptSecContext(Krb5Context.java:724) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:323) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at sun.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:267) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at com.sun.security.sasl.gsskerb.GssKrb5Server.evaluateResponse(GssKrb5Server.java:137) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
... 13 more<br/>
default etypes for permitted_enctypes: 3 1 23 16 17 18.<br/>
1266879 <span class="error">&#91;pool-7-thread-62&#93;</span> ERROR b.s.s.a.k.KerberosSaslTransportPlugin - Storm server failed to open transport to interact with a client during session initiation: java.lang.RuntimeException: org.apache.thrift7.transport.TTransportException: GSS initiate failed<br/>
java.lang.RuntimeException: org.apache.thrift7.transport.TTransportException: GSS initiate failed<br/>
at org.apache.thrift7.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory$1.run(KerberosSaslTransportPlugin.java:196) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory$1.run(KerberosSaslTransportPlugin.java:193) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.security.AccessController.doPrivileged(Native Method) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at javax.security.auth.Subject.doAs(Subject.java:396) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory.getTransport(KerberosSaslTransportPlugin.java:192) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:268) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
Caused by: org.apache.thrift7.transport.TTransportException: GSS initiate failed<br/>
at org.apache.thrift7.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslTransport.open(TSaslTransport.java:316) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
... 9 more<br/>
>>> EType: sun.security.krb5.internal.crypto.ArcFourHmacEType<br/>
1266879 <span class="error">&#91;pool-7-thread-62&#93;</span> ERROR b.s.s.a.k.KerberosSaslTransportPlugin - Storm server failed to open transport to interact with a client during session initiation: java.lang.NullPointerException<br/>
java.lang.NullPointerException<br/>
at org.apache.thrift7.transport.TSocket.open(TSocket.java:170) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslTransport.open(TSaslTransport.java:266) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory$1.run(KerberosSaslTransportPlugin.java:196) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory$1.run(KerberosSaslTransportPlugin.java:193) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.security.AccessController.doPrivileged(Native Method) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at javax.security.auth.Subject.doAs(Subject.java:396) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory.getTransport(KerberosSaslTransportPlugin.java:192) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
1266879 <span class="error">&#91;pool-7-thread-62&#93;</span> ERROR o.a.t.s.TThreadPoolServer - Error occurred during processing of message.<br/>
java.lang.NullPointerException<br/>
at backtype.storm.security.auth.SaslTransportPlugin$TUGIWrapProcessor.process(SaslTransportPlugin.java:125) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
```<br/>
This not happen every time, some one will give me some advice, thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
