### ISSUE TITLE
[STORM-873] Flux does not handle "diamond" topologies

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4713]
<p>From email report on user@:</p>

<p>It builds something like below (imagine the arrow from A-> B, A-> C,<br/>
B->D, and C->D)<br/>
---------------------------------------------------------<br/>
   Bolt_B<br/>
Spout -> Bolt_A  -> Bolt_D<br/>
   Bolt_C<br/>
---------------------------------------------------------</p>

<p>I get an error below in FLUX.</p>

<p>Exception in thread "main" java.lang.IllegalArgumentException: Bolt<br/>
has already been declared for id bolt_D<br/>
   at backtype.storm.topology.TopologyBuilder.validateUnusedId(TopologyBuilder.java:212)<br/>
   at backtype.storm.topology.TopologyBuilder.setBolt(TopologyBuilder.java:139)<br/>
   at org.apache.storm.flux.FluxBuilder.buildStreamDefinitions(FluxBuilder.java:158)<br/>
   at org.apache.storm.flux.FluxBuilder.buildTopology(FluxBuilder.java:94)<br/>
   at org.apache.storm.flux.Flux.runCli(Flux.java:153)<br/>
   at org.apache.storm.flux.Flux.main(Flux.java:98)</p>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-873" target="_blank">Flux does not handle "diamond" topologies</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-06-27T17:33:52+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user ptgoetz opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/596" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/596</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-873" title="Flux does not handle "diamond" topologies" class="issue-link" data-issue-key="STORM-873"><del>STORM-873</del></a>: Flux does not handle diamond topologies</p>

<p>    JIRA: <a href="https://issues.apache.org/jira/browse/STORM-873" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-873</a></p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/ptgoetz/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/ptgoetz/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-873" title="Flux does not handle "diamond" topologies" class="issue-link" data-issue-key="STORM-873"><del>STORM-873</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/596.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/596.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #596</p>

<hr />
<p>commit f95196031144bac23453ccce813667e8ec652a63<br/>
Author: P. Taylor Goetz <ptgoetz@gmail.com><br/>
Date:   2015-06-18T03:59:58Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-873" title="Flux does not handle "diamond" topologies" class="issue-link" data-issue-key="STORM-873"><del>STORM-873</del></a>: Flux does not handle diamond topologies</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Post fix:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">---------- TOPOLOGY DETAILS ----------
Topology Name: diamond-topology
--------------- SPOUTS ---------------
spout-1 [1] (backtype.storm.testing.TestWordSpout)
---------------- BOLTS ---------------
A [1] (org.apache.storm.flux.wrappers.bolts.LogInfoBolt)
B [1] (org.apache.storm.flux.wrappers.bolts.LogInfoBolt)
C [1] (org.apache.storm.flux.wrappers.bolts.LogInfoBolt)
D [1] (org.apache.storm.flux.wrappers.bolts.LogInfoBolt)
--------------- STREAMS ---------------
spout-1 --FIELDS--> A
A --SHUFFLE--> B
A --SHUFFLE--> C
C --SHUFFLE--> D
B --SHUFFLE--> D
--------------------------------------
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/596#issuecomment-113254899" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/596#issuecomment-113254899</a></p>

<p>    LGTM. +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/596#issuecomment-113552940" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/596#issuecomment-113552940</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/596" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/596</a></p>
