### ISSUE TITLE
[STORM-874] Netty Threads do not handle Errors properly

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4714]
<p>When low on memory, netty thread could get OOM which if not handled correctly can lead to unexpected behavior such as netty connection leaks.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658) ~[?:1.8.0_25]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[?:1.8.0_25]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_25]
	at org.jboss.netty.buffer.ChannelBuffers.directBuffer(ChannelBuffers.java:167) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.buffer.ChannelBuffers.directBuffer(ChannelBuffers.java:151) ~[netty-3.9.4.Final.jar:?]
	at backtype.storm.messaging.netty.MessageBatch.buffer(MessageBatch.java:101) ~[storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
	at backtype.storm.messaging.netty.MessageEncoder.encode(MessageEncoder.java:32) ~[storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.Channels.write(Channels.java:704) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.Channels.write(Channels.java:671) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248) ~[netty-3.9.4.Final.jar:?]
	at backtype.storm.messaging.netty.Client.tryDeliverMessages(Client.java:226) ~[storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
	at backtype.storm.messaging.netty.Client.send(Client.java:173) ~[storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-874" target="_blank">Netty Threads do not handle Errors properly</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-30T21:00:03+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-874" title="Netty Threads do not handle Errors properly" class="issue-link" data-issue-key="STORM-874"><del>STORM-874</del></a> Add UncaughtExceptionHandler for netty threads</p>

<p>    The netty threads need to handle uncaught exceptions. This would help ensure that JVM exits if netty threads hit OOM Error  while allocating new buffer.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> storm874</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/597.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #597</p>

<hr />
<p>commit 6c4f8bf61fd5a4b86fc6df1bf33a2a90f5f5797e<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-06-17T21:15:51Z</p>

<p>    Add UncaughtExceptionHandler for netty threads as it should for JVM halt in case or OOM Error</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#issuecomment-113995243" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#issuecomment-113995243</a></p>

<p>    @kishorvpatil would it makes sense to log the exception as well? , allows users to know the cause of jvm exit.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#discussion_r33100021" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#discussion_r33100021</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/messaging/netty/NettyUncaughtExceptionHandler.java &#8212;<br/>
    @@ -0,0 +1,35 @@<br/>
    +/**<br/>
    + * Licensed to the Apache Software Foundation (ASF) under one<br/>
    + * or more contributor license agreements.  See the NOTICE file<br/>
    + * distributed with this work for additional information<br/>
    + * regarding copyright ownership.  The ASF licenses this file<br/>
    + * to you under the Apache License, Version 2.0 (the<br/>
    + * "License"); you may not use this file except in compliance<br/>
    + * with the License.  You may obtain a copy of the License at<br/>
    + *<br/>
    + * <a href="http://www.apache.org/licenses/LICENSE-2.0" class="external-link" target="_blank" rel="nofollow noopener">http://www.apache.org/licenses/LICENSE-2.0</a><br/>
    + *<br/>
    + * Unless required by applicable law or agreed to in writing, software<br/>
    + * distributed under the License is distributed on an "AS IS" BASIS,<br/>
    + * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.<br/>
    + * See the License for the specific language governing permissions and<br/>
    + * limitations under the License.<br/>
    + */<br/>
    +package backtype.storm.messaging.netty;<br/>
    +<br/>
    +import backtype.storm.utils.Utils;<br/>
    +import org.slf4j.Logger;<br/>
    +import org.slf4j.LoggerFactory;<br/>
    +<br/>
    +public class NettyUncaughtExceptionHandler implements Thread.UncaughtExceptionHandler {<br/>
    +  private static final Logger LOG = LoggerFactory.getLogger(NettyUncaughtExceptionHandler.class);<br/>
    +  @Override<br/>
    +  public void uncaughtException(Thread t, Throwable e) {<br/>
    +    try {<br/>
    +      Utils.handleUncaughtException(e);<br/>
    &#8212; End diff &#8211;</p>

<p>    @kishorvpatil <br/>
    Utils.handleUncaughtException() only takes care of Error, and any kinds of Exception will be silently ignored without leaving any logs. <br/>
    Is it intentional? Or do we need to take care?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user eshioji commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#issuecomment-120603640" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#issuecomment-120603640</a></p>

<p>    If the thread is used in `ThreadPoolExecutor` (like the boss & worker thread pool currently used), `UncaughtExceptionHandler` are not invoked because `ThreadPoolExecutor` suppress uncaught exceptions coming from tasks (see e.g. <a href="http://stackoverflow.com/questions/1838923/why-is-uncaughtexceptionhandler-not-called-by-executorservice" class="external-link" target="_blank" rel="nofollow noopener">http://stackoverflow.com/questions/1838923/why-is-uncaughtexceptionhandler-not-called-by-executorservice</a>). There are workarounds but they are quite hacky.</p>

<p>    Maybe it makes more sense to consider the service unhealthy if messages are unable to be dispatched, rather than based on whether an uncaught exception was encountered?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#issuecomment-134759973" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#issuecomment-134759973</a></p>

<p>    @eshioji We are catching `Error` not `RunTimeException` which shows more of a JVM  resource issue - hence we do exit from the JVM - its more serious than just considering some service being down.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#discussion_r37927420" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#discussion_r37927420</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/messaging/netty/NettyUncaughtExceptionHandler.java &#8212;<br/>
    @@ -0,0 +1,35 @@<br/>
    +/**<br/>
    + * Licensed to the Apache Software Foundation (ASF) under one<br/>
    + * or more contributor license agreements.  See the NOTICE file<br/>
    + * distributed with this work for additional information<br/>
    + * regarding copyright ownership.  The ASF licenses this file<br/>
    + * to you under the Apache License, Version 2.0 (the<br/>
    + * "License"); you may not use this file except in compliance<br/>
    + * with the License.  You may obtain a copy of the License at<br/>
    + *<br/>
    + * <a href="http://www.apache.org/licenses/LICENSE-2.0" class="external-link" target="_blank" rel="nofollow noopener">http://www.apache.org/licenses/LICENSE-2.0</a><br/>
    + *<br/>
    + * Unless required by applicable law or agreed to in writing, software<br/>
    + * distributed under the License is distributed on an "AS IS" BASIS,<br/>
    + * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.<br/>
    + * See the License for the specific language governing permissions and<br/>
    + * limitations under the License.<br/>
    + */<br/>
    +package backtype.storm.messaging.netty;<br/>
    +<br/>
    +import backtype.storm.utils.Utils;<br/>
    +import org.slf4j.Logger;<br/>
    +import org.slf4j.LoggerFactory;<br/>
    +<br/>
    +public class NettyUncaughtExceptionHandler implements Thread.UncaughtExceptionHandler {<br/>
    +  private static final Logger LOG = LoggerFactory.getLogger(NettyUncaughtExceptionHandler.class);<br/>
    +  @Override<br/>
    +  public void uncaughtException(Thread t, Throwable e) {<br/>
    +    try {<br/>
    +      Utils.handleUncaughtException(e);<br/>
    &#8212; End diff &#8211;</p>

<p>    @HeartSaVioR  We consider the Netty message handlers should take care of all those exceptions. We leave JVM level Error to be handled at executorservice handler level.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#issuecomment-134761846" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#issuecomment-134761846</a></p>

<p>    @harshach Sorry for so long in responding to it. The `Utils.handleUncaughtException` writes ot STDOUT to avoid further major exception by attempting to log exceptions. But otherwise we log them. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#discussion_r43150246" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#discussion_r43150246</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/messaging/netty/NettyUncaughtExceptionHandler.java &#8212;<br/>
    @@ -0,0 +1,35 @@<br/>
    +/**<br/>
    + * Licensed to the Apache Software Foundation (ASF) under one<br/>
    + * or more contributor license agreements.  See the NOTICE file<br/>
    + * distributed with this work for additional information<br/>
    + * regarding copyright ownership.  The ASF licenses this file<br/>
    + * to you under the Apache License, Version 2.0 (the<br/>
    + * "License"); you may not use this file except in compliance<br/>
    + * with the License.  You may obtain a copy of the License at<br/>
    + *<br/>
    + * <a href="http://www.apache.org/licenses/LICENSE-2.0" class="external-link" target="_blank" rel="nofollow noopener">http://www.apache.org/licenses/LICENSE-2.0</a><br/>
    + *<br/>
    + * Unless required by applicable law or agreed to in writing, software<br/>
    + * distributed under the License is distributed on an "AS IS" BASIS,<br/>
    + * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.<br/>
    + * See the License for the specific language governing permissions and<br/>
    + * limitations under the License.<br/>
    + */<br/>
    +package backtype.storm.messaging.netty;<br/>
    +<br/>
    +import backtype.storm.utils.Utils;<br/>
    +import org.slf4j.Logger;<br/>
    +import org.slf4j.LoggerFactory;<br/>
    +<br/>
    +public class NettyUncaughtExceptionHandler implements Thread.UncaughtExceptionHandler {<br/>
    +  private static final Logger LOG = LoggerFactory.getLogger(NettyUncaughtExceptionHandler.class);<br/>
    +  @Override<br/>
    +  public void uncaughtException(Thread t, Throwable e) {<br/>
    +    try {<br/>
    +      Utils.handleUncaughtException(e);<br/>
    &#8212; End diff &#8211;</p>

<p>    I agree with @HeartSaVioR , we should at least log any (unchecked) Exception instead of swallow it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#discussion_r43150822" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#discussion_r43150822</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/messaging/netty/NettyUncaughtExceptionHandler.java &#8212;<br/>
    @@ -0,0 +1,35 @@<br/>
    +/**<br/>
    + * Licensed to the Apache Software Foundation (ASF) under one<br/>
    + * or more contributor license agreements.  See the NOTICE file<br/>
    + * distributed with this work for additional information<br/>
    + * regarding copyright ownership.  The ASF licenses this file<br/>
    + * to you under the Apache License, Version 2.0 (the<br/>
    + * "License"); you may not use this file except in compliance<br/>
    + * with the License.  You may obtain a copy of the License at<br/>
    + *<br/>
    + * <a href="http://www.apache.org/licenses/LICENSE-2.0" class="external-link" target="_blank" rel="nofollow noopener">http://www.apache.org/licenses/LICENSE-2.0</a><br/>
    + *<br/>
    + * Unless required by applicable law or agreed to in writing, software<br/>
    + * distributed under the License is distributed on an "AS IS" BASIS,<br/>
    + * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.<br/>
    + * See the License for the specific language governing permissions and<br/>
    + * limitations under the License.<br/>
    + */<br/>
    +package backtype.storm.messaging.netty;<br/>
    +<br/>
    +import backtype.storm.utils.Utils;<br/>
    +import org.slf4j.Logger;<br/>
    +import org.slf4j.LoggerFactory;<br/>
    +<br/>
    +public class NettyUncaughtExceptionHandler implements Thread.UncaughtExceptionHandler {<br/>
    +  private static final Logger LOG = LoggerFactory.getLogger(NettyUncaughtExceptionHandler.class);<br/>
    +  @Override<br/>
    +  public void uncaughtException(Thread t, Throwable e) {<br/>
    +    try {<br/>
    +      Utils.handleUncaughtException(e);<br/>
    &#8212; End diff &#8211;</p>

<p>    Also, the name Utils/handleUncaughtException here implies we are handling exceptions that could not be otherwise be dealt with, and so this is the end of the road.  It does not seem that we should return from this handler expecting some other code to deal with the situation, but we should bring down the JVM or throw.  If the code is not intended to be used this way, then we should rename and/or document what is expected of the caller to do with `t` after we return.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#issuecomment-160759703" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#issuecomment-160759703</a></p>

<p>    These changes went in as part of #838. So closing the PR and JIRA</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/597" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>:</i>
<p>This issue is addressed with <a href="https://issues.apache.org/jira/browse/STORM-885" title="Heartbeat Server (Pacemaker)" class="issue-link" data-issue-key="STORM-885"><del>STORM-885</del></a></p>
