### ISSUE TITLE
[STORM-903] fix class missing when ui.filter set to org.apache.hadoop.security.authentication.server.AuthenticationFilter

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4741]
<p>When I set ui.filter=org.apache.hadoop.security.authentication.server.AuthenticationFilter, there are java.lang.NoClassDefFoundError about the ui:<br/>
```<br/>
org/apache/commons/codec/binary/Base64<br/>
java.lang.NoClassDefFoundError:<br/>
at org.apache.hadoop.security.authentication.server.KerberosAuthenticationHandler.authenticate(KerberosAuthenticationHandler.java:305) ~<span class="error">&#91;hadoop-auth-2.4.0.jar:?&#93;</span><br/>
at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:357) ~<span class="error">&#91;hadoop-auth-2.4.0.jar:?&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.Server.handle(Server.java:369) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.http.HttpParser.parseNext(HttpParser.java:644) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.server.ssl.SslSocketConnector$SslConnectorEndPoint.run(SslSocketConnector.java:670) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
at java.lang.Thread.run(Thread.java:662) <span class="error">&#91;?:1.6.0_37&#93;</span><br/>
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Base64<br/>
at java.net.URLClassLoader$1.run(URLClassLoader.java:202) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.security.AccessController.doPrivileged(Native Method) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~<span class="error">&#91;?:1.6.0_37&#93;</span><br/>
... 25 more<br/>
```</p>

<p>This is because missing commons-code.</p>

---
<details><summary><i>Originally reported by <a title="xiajun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tedxia">tedxia</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-903" target="_blank">fix class missing when ui.filter set to org.apache.hadoop.security.authentication.server.AuthenticationFilter</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:14+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user tedxia opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-903" title="fix class missing when ui.filter set to org.apache.hadoop.security.authentication.server.AuthenticationFilter" class="issue-link" data-issue-key="STORM-903"><del>STORM-903</del></a>: fix java.lang.ClassNotFoundException with org.apache.commo…</p>

<p>    …ns.codec.binary.Base64 when set ui.filter to org.apache.hadoop.security.authentication.server.AuthenticationFilter</p>

<p>    PR for <a href="https://issues.apache.org/jira/browse/STORM-903" title="fix class missing when ui.filter set to org.apache.hadoop.security.authentication.server.AuthenticationFilter" class="issue-link" data-issue-key="STORM-903"><del>STORM-903</del></a>(<a href="https://issues.apache.org/jira/browse/STORM-903" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-903</a>)</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/tedxia/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/tedxia/storm</a> ted-fix-missing-codex-when-use-ui-filter-as-AuthenticationFilter</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/600.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #600</p>

<hr />
<p>commit 155478204705e78777ccb5972ac495eb28f700d6<br/>
Author: xiajun <xiajun@xiaomi.com><br/>
Date:   2015-06-19T08:18:26Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-903" title="fix class missing when ui.filter set to org.apache.hadoop.security.authentication.server.AuthenticationFilter" class="issue-link" data-issue-key="STORM-903"><del>STORM-903</del></a>: fix java.lang.ClassNotFoundException with org.apache.commons.codec.binary.Base64 when set ui.filter to org.apache.hadoop.security.authentication.server.AuthenticationFilter</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-114657493" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-114657493</a></p>

<p>    @kishorvpatil I think you may want to take care of it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115263584" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115263584</a></p>

<p>    @tedxia We shaded this for a reason.  If AutoHDFS is not able to find it, then we should look at updating AutoHDFS to use the shaded version of the library.  I am not sure if that is possible or not.  It depends on if it is us that is using commons-codec directly or if it is another dependency.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115269037" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115269037</a></p>

<p>    @tedxia sorry I am wrong.  hadoop-hdfs itself depends on commons-codec.  But the issue is around the packaging of auto-hdfs.</p>

<p>    For most users who want to use storm-hdfs in their topologies they will include it as a dependency and include it as part of an uber-jar.  This will pull in commons-codec correctly.  The issue is if you want to just include it in the classpath by default.  If all you do is take storm-hdfs and put it in the lib directory you will get these errors.  If you don't want your users to have to package auto-hdfs with their topology then you need to include storm-hdfs, and all of its dependencies in the lib directory or set STORM_EXT_CLASSPATH before launching the various daemons.  This is nice because it lets you potentially query a hadoop install already on the box for it's classpath instead of trying to figure it all out yourself.</p>

<p>    Alternatively you could just set it up for storm-hdfs to be on the daemons classpath and not pollute the worker classpath.  You can do this by using STORM_EXT_CLASSPATH_DAEMON and/or extlib-daemon directory.  What we really need is some better documentation about how to install and setup atuo-hdfs.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115349321" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115349321</a></p>

<p>    @revans2 not sure this addresses the issue for using KerberosFilter from hadoop for securing UI when used in kerberos cluster. We excluded commons-codec from hadoop-auth because storm is including it in the classpath <a href="https://github.com/apache/storm/blob/master/storm-core/pom.xml#L259" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/pom.xml#L259</a> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115355904" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115355904</a></p>

<p>    @harshach If you are pulling in an external library, like the KerberosFilter, you are responsible for making sure all of its dependencies are on the classpath.  If we have shaded some of them, then you need to pull them over and include them.  If it is something that a worker does not need access to, like the KerberosFilter, then you can include it in the extlib-damone directory where it will not show up on the worker's classpath.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115360459" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115360459</a></p>

<p>    @revans2 we are shipping security in 0.10 that means we need to provide a way for UI daemon to be secured hence the reason we are including kerberos filter as part of storm-core/pom.xml that its easier for users to just add a config ui.filter and use kerberos filter. Now the patch <a href="https://issues.apache.org/jira/browse/STORM-848" title="Clean up dependencies and shade as much as possible" class="issue-link" data-issue-key="STORM-848"><del>STORM-848</del></a> which shaded and removed commons-codec should also remove the exclusion of commons-codec from hadoop-auth. I don't think making this as user's responsibility makes sense here.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user tedxia commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115479231" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115479231</a></p>

<p>    @revans2 thanks for  your replay. But I still think we must add storm-hdfs and all of its dependencies to lib or extlib, and storm user must add storm-hdfs as topology's dependency as it use HdfsBolt and so on. The reason why we should add storm-hdfs to daemon's CLASS_PATH is that daemons such as nimbus and supervisor will directly call AutoHDFS‘s interface. I think it is a good idea if we add storm-hdfs and storm-hbase and all of their dependencies to extlib-daemon by default. The jars that have been shaded by storm-core must also add to extlib-daemon, if they are depended by storm-hdfs or storm-hbase, just because AutoHDFS and AutoHBase load by class loader and they can't identify the shaded jars. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115872534" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115872534</a></p>

<p>    @harshach so what you are saying is that if we should remove the exclude, but leave in the shading.  This means we will have two copies of commons-codec, one shaded that storm will use, and one that hadoop-auth will use that is not shaded and will be on the path?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115875141" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115875141</a></p>

<p>    So this pull request is what you want to have happen.  I am OK with that, but if we are going to have commons-codec on the classpath, then lets not bother shading it at all.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/600#issuecomment-115940765" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/600#issuecomment-115940765</a></p>

<p>    @revans2  agree on not shading. Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
