### ISSUE TITLE
[STORM-930] Nimbus server shutting down

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4768]
<p>2015-07-09 18:40:53 b.s.d.nimbus <span class="error">&#91;INFO&#93;</span> Starting Nimbus server...<br/>
2015-07-09 18:40:54 b.s.d.nimbus <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.lang.NullPointerException: null<br/>
	at clojure.lang.Numbers.ops(Numbers.java:942) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.Numbers.isZero(Numbers.java:90) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at backtype.storm.util$partition_fixed.invoke(util.clj:868) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:163) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$apply.invoke(core.clj:617) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:163) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at backtype.storm.util$map_val$iter_<em>273</em><em>277$fn</em>_278.invoke(util.clj:291) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.LazySeq.seq(LazySeq.java:60) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.Cons.next(Cons.java:39) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.RT.next(RT.java:598) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$next.invoke(core.clj:64) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core.protocols$fn__6034.invoke(protocols.clj:146) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core.protocols$fn_<em>6005$G</em><em>6000</em>_6014.invoke(protocols.clj:19) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core.protocols$fn__6026.invoke(protocols.clj:54) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core.protocols$fn_<em>5979$G</em><em>5974</em>_5992.invoke(protocols.clj:13) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$reduce.invoke(core.clj:6177) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$into.invoke(core.clj:6229) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at backtype.storm.util$map_val.invoke(util.clj:290) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.daemon.nimbus$compute_executors.invoke(nimbus.clj:435) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.daemon.nimbus$compute_executor__GT_component.invoke(nimbus.clj:446) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.daemon.nimbus$read_topology_details.invoke(nimbus.clj:339) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.daemon.nimbus$mk_assignments$iter_<em>7285</em><em>7289$fn</em>_7290.invoke(nimbus.clj:665) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.LazySeq.seq(LazySeq.java:60) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.lang.RT.seq(RT.java:484) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$seq.invoke(core.clj:133) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core.protocols$fn__6026.invoke(protocols.clj:54) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core.protocols$fn_<em>5979$G</em><em>5974</em>_5992.invoke(protocols.clj:13) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$reduce.invoke(core.clj:6177) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at clojure.core$into.invoke(core.clj:6229) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at backtype.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:664) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:410) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at backtype.storm.daemon.nimbus$fn_<em>7518$exec_fn</em><em>1491</em><em>auto</em>__<em>7519$fn</em><em>7524$fn</em>_7525.invoke(nimbus.clj:994) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.daemon.nimbus$fn_<em>7518$exec_fn</em><em>1491</em><em>auto</em>__<em>7519$fn</em>_7524.invoke(nimbus.clj:993) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.timer$schedule_recurring$this__2034.invoke(timer.clj:99) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.timer$mk_timer$fn_<em>2017$fn</em>_2018.invoke(timer.clj:50) ~<span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.timer$mk_timer$fn__2017.invoke(timer.clj:42) <span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_75&#93;</span><br/>
2015-07-09 18:40:54 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:322) <span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at backtype.storm.daemon.nimbus$nimbus_data$fn__6891.invoke(nimbus.clj:85) <span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.timer$mk_timer$fn_<em>2017$fn</em>_2018.invoke(timer.clj:68) <span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at backtype.storm.timer$mk_timer$fn__2017.invoke(timer.clj:42) <span class="error">&#91;storm-core-0.9.3.2.2.6.0-2800.jar:0.9.3.2.2.6.0-2800&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_75&#93;</span><br/>
2015-07-09 18:40:54 b.s.d.nimbus <span class="error">&#91;INFO&#93;</span> Shutting down master</p>

---
<details><summary><i>Originally reported by <a title="Vezly Gracies" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vezly.gracies">vezly.gracies</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-930" target="_blank">Nimbus server shutting down</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Incomplete
<li><b>resolved</b>: 2016-01-12T21:38:11+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>:</i>
<p>See:<br/>
<a href="https://github.com/apache/storm/blob/v0.9.3-rc1/storm-core/src/clj/backtype/storm/util.clj#L824" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v0.9.3-rc1/storm-core/src/clj/backtype/storm/util.clj#L824</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">(defn partition-fixed
  [max-num-chunks aseq]
  (<span class="code-keyword">if</span> (zero? max-num-chunks)
    []
   ... 
</pre>
</div></div>

<p>Do you set parallelism-hint of your topology component ? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=babu cervenkova">babu cervenkova</a>:</i>
<p>We have similar issue, but the problem is that Nimbus is not able to start at all:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">o.a.s.c.f.s.ConnectionStateManager [INFO] State change: CONNECTED
b.s.cluster [WARN] Received event ::none: with disconnected Zookeeper.
b.s.d.nimbus [INFO] Starting Nimbus server...
o.a.s.z.Login [INFO] successfully logged in.
b.s.s.a.k.KerberosSaslTransportPlugin [INFO] Service principal:nimbus@REALM
b.s.s.a.k.KerberosSaslTransportPlugin [INFO] SASL GSSAPI transport factory will be used
b.s.d.nimbus [ERROR] Error when processing event
java.lang.NullPointerException: <span class="code-keyword">null</span>
	at clojure.lang.Numbers.ops(Numbers.java:942) ~[clojure-1.5.1.jar:na]
	at clojure.lang.Numbers.isZero(Numbers.java:90) ~[clojure-1.5.1.jar:na]
	at backtype.storm.util$partition_fixed.invoke(util.clj:868) ~[storm-core-0.9.3.2.2.4.2-2.jar:0.9.3.2.2.4.2-2]
</pre>
</div></div>

<p>We have there one topology that may not have setted parallelism-hint, but the problem is that without Nimbus running we are not able to remove it. Any suggestions? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Not enough information. Please re-open and add additional information to reproduce the issue if you are still having a problem.</p>
