### ISSUE TITLE
[STORM-933] NullPointerException during KafkaSpout deactivation

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4771]
<p>We are seeing this during a topology shutdown</p>

<p>2015-07-09 19:51:48-0700 b.s.util <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
java.lang.NullPointerException: null<br/>
at storm.kafka.KafkaSpout.commit(KafkaSpout.java:190) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.KafkaSpout.deactivate(KafkaSpout.java:180) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at com.relateiq.storm.JMXActivatableSpout.deactivate(JMXActivatableSpout.java:75) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>6579$fn</em><em>6594$fn</em>_6623.invoke(executor.clj:570) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.util$async_loop$fn__459.invoke(util.clj:463) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_31&#93;</span><br/>
2015-07-09 19:51:48-0700 b.s.d.executor <span class="error">&#91;ERROR&#93;</span></p>

<p>Thanks</p>

---
<details><summary><i>Originally reported by <a title="Patricio Echague" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patricioe">patricioe</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-933" target="_blank">NullPointerException during KafkaSpout deactivation</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="caofangkun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-08-03T00:02:31+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanket991">sanket991</a>:</i>
<p>I am interested to resolve the issue, can you let me know how to reproduce the error</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patricioe">patricioe</a>:</i>
<p>Hi. I happens to us during a topology shutdown after issuing a kill<br/>
command.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user caofangkun opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/660" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/660</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-933" title="NullPointerException during KafkaSpout deactivation" class="issue-link" data-issue-key="STORM-933"><del>STORM-933</del></a>:NullPointerException during KafkaSpout deactivation</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/caofangkun/apache-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/caofangkun/apache-storm</a> storm-933</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/660.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/660.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #660</p>

<hr />
<p>commit 2a1a417f922cbce6239b5c85eb75363b92b9a2d0<br/>
Author: caofangkun <caofangkun@gmail.com><br/>
Date:   2015-07-31T02:36:42Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-933" title="NullPointerException during KafkaSpout deactivation" class="issue-link" data-issue-key="STORM-933"><del>STORM-933</del></a>:NullPointerException during KafkaSpout deactivation</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/660#issuecomment-127075818" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/660#issuecomment-127075818</a></p>

<p>    We can add null check from KafkaSpout.commit() to save tiny memory (by lazy allocation), but it is really tiny so I think current approach is acceptable.<br/>
    +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun" class="user-hover" rel="caofangkun">caofangkun</a>,<br/>
I merged this into master, 0.10.x-branch, 0.9.x-branch respectively.</p>

<p>Seems like Github mirror has issue again. When it becomes stable, your PR could be automatically marked as merged.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/660#issuecomment-127082994" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/660#issuecomment-127082994</a></p>

<p>    I merged this into master, 0.10.x-branch, 0.9.x-branch respectively.<br/>
    Seems like Github mirror has issue again. When it becomes stable, your PR could be automatically marked as merged.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/660" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/660</a></p>
