### ISSUE TITLE
[STORM-944] storm-hive pom.xml has a dependency conflict with calcite

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4782]
<p>Hive 0.14.0 has a dependency on calcite-0.9.2-incubating-SNAPSHOT which can't be resolved in maven central.  See <a href="https://issues.apache.org/jira/browse/HIVE-8906" title="Hive 0.14.0 release depends on Tez and Calcite SNAPSHOT artifacts" class="issue-link" data-issue-key="HIVE-8906"><del>HIVE-8906</del></a> for details.</p>

<p>This gives a harmless compile warning for storm-hive but it does prevent some IDEs (IntelliJ for certain, probably others) from correctly resolving the project dependencies.  storm-hive already has a dependency on calcite-0.9.2-incubating so calcite should be excluded from the hive dependency.</p>

<p>Compile warning:<br/>
<span class="error">&#91;WARNING&#93;</span> Missing POM for org.apache.calcite:calcite-core:jar:0.9.2-incubating-SNAPSHOT<br/>
<span class="error">&#91;WARNING&#93;</span> Missing POM for org.apache.calcite:calcite-avatica:jar:0.9.2-incubating-SNAPSHOT</p>

---
<details><summary><i>Originally reported by <a title="Aaron Dossett" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dossett@gmail.com">dossett@gmail.com</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-944" target="_blank">storm-hive pom.xml has a dependency conflict with calcite</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Blake Niskode-Dossett" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dossett">dossett</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-08-11T23:14:53+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dossett@gmail.com">dossett@gmail.com</a>:</i>
<p>Pull request available here:</p>

<p><a href="https://github.com/apache/storm/pull/609" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/609</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/609#issuecomment-129640139" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/609#issuecomment-129640139</a></p>

<p>    There're some issues regarding using SNAPSHOT version of dependencies.</p>

<ul class="alternate" type="square">
	<li>Tez: <a href="https://issues.apache.org/jira/browse/HIVE-8845" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/HIVE-8845</a></li>
	<li>Calcite: <a href="https://issues.apache.org/jira/browse/HIVE-8873" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/HIVE-8873</a></li>
</ul>


<p>    For now, without this PR, builds are failed cause it tries to fetch SNAPSHOT version of calcite but nexus.codehaus.org is unreachable.<br/>
    Behavior of depending on SNAPSHOT is fixed at 1.0.0.</p>

<p>    I didn't have time to use Hive, so I have some questions, </p>

<ul class="alternate" type="square">
	<li>Is it safe for users to upgrade hive version to 1.x.y without compatibility issues?</li>
	<li>If it is, is it better to notify users to use Hive version to 1.0.0 and higher while using storm-hive?</li>
</ul>


<p>    IMO we would be better to try avoiding any workarounds unless we can't resolve it without workaround. </p>

<p>    @dossett @caofangkun @harshach @ptgoetz @revans2 </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dossett commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/609#issuecomment-129663786" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/609#issuecomment-129663786</a></p>

<p>    I think this PR is preferable to stating a requirement for Hive 1.0.0 (of course, as the author of the PR, I would think that <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/> )</p>

<ul class="alternate" type="square">
	<li>I could be wrong, but I think the vast majority of Hive installs are not yet at 1.0.0 since HDP 2.2.X is at 0.14.0 and 2.3 has not had time to be widely adopted.  Other Hadoop distributions are slower to upgrade Hive than HDP.</li>
</ul>


<ul class="alternate" type="square">
	<li>This PR doesn't try to change any functional behavior. It just prevents maven from trying to resolve a dependency that will fail anyway.</li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user caofangkun commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/609#issuecomment-129689692" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/609#issuecomment-129689692</a></p>

<p>    1 This PR is outdated now and  should upmerge this with master<br/>
    2  [ org.apache.calcite:calcite-core:0.9.2-incubating](<a href="https://github.com/apache/storm/blob/master/external/storm-hive/pom.xml#L83" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/external/storm-hive/pom.xml#L83</a>) also not necessary be brought in .<br/>
    3 This PR only and should only resolve fails of  fetching SNAPSHOT version of calcite<br/>
       I do not think there's compatibility issue right now , and of course we could file another issue if necessary.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/609#issuecomment-129836616" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/609#issuecomment-129836616</a></p>

<p>    @dossett <br/>
    Makes sense.<br/>
    Last thing I'd like to know is that current patch can work with Hive 1.x.y.<br/>
    If it isn't, storm-hive is just for 0.14.0 since you showed storm-hive doesn't work with Hive 0.13.0.<br/>
    It would be better to specify supporting Hive versions to README.</p>

<p>    @caofangkun <br/>
    If it doesn't affect storm-hive, I also think it would be better to remove explicit dependency about calcite, since higher version of Hive could require higher version of calcite.<br/>
    But as I stated earlier, I didn't use Hive so verification and confirmation from Committer Sponsors are required.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dossett commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/609#issuecomment-129860736" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/609#issuecomment-129860736</a></p>

<p>    @HeartSaVioR <br/>
    This PR works with hive.version=1.0.0   By "works" I mean that it compiles and passes all unit tests.</p>

<p>    It does NOT work with hive.version=1.2.1 (the version of Hive that ships with HDP 2.3).  Hive 1.2.1 depends on Calcite 1.2.0 and several tests fail if it's excluded.  I could get past these first problems by updating the calcite version in storm-hive/pom.xml to 1.2.0.  However, one test still fails (see below).  I have not had time to investigate these further, but it looks like some Hive behavior changes unrelated to the calcite dependency issue.</p>

<p>    A new JIRA for Hive 1.2.1 support seems appropriate for that issue.</p>

<p>    ```<br/>
    Running org.apache.storm.hive.bolt.TestHiveBolt<br/>
    Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.488 sec <<< FAILURE! - in org.apache.storm.hive.bolt.TestHiveBolt<br/>
    testWithTimeformat(org.apache.storm.hive.bolt.TestHiveBolt)  Time elapsed: 0.692 sec  <<< FAILURE!<br/>
    org.mockito.exceptions.verification.WantedButNotInvoked: <br/>
    Wanted but not invoked:<br/>
    collector.ack(<br/>
source: null:1, stream: , id: {}, <span class="error">&#91;100, test-123, null, null&#93;</span><br/>
    );<br/>
    -> at org.apache.storm.hive.bolt.TestHiveBolt.testWithTimeformat(TestHiveBolt.java:235)</p>

<p>    However, there were other interactions with this mock:<br/>
    -> at backtype.storm.task.OutputCollector.reportError(OutputCollector.java:223)<br/>
    -> at backtype.storm.task.OutputCollector.fail(OutputCollector.java:218)<br/>
    -> at backtype.storm.task.OutputCollector.reportError(OutputCollector.java:223)<br/>
    -> at backtype.storm.task.OutputCollector.fail(OutputCollector.java:218)</p>

<p>    	at org.apache.storm.hive.bolt.TestHiveBolt.testWithTimeformat(TestHiveBolt.java:235)</p>

<p>    Running org.apache.storm.hive.common.TestHiveWriter<br/>
    Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.387 sec - in org.apache.storm.hive.common.TestHiveWriter</p>

<p>    Results :</p>

<p>    Failed tests: <br/>
      TestHiveBolt.testWithTimeformat:235 <br/>
    Wanted but not invoked:<br/>
    collector.ack(<br/>
source: null:1, stream: , id: {}, <span class="error">&#91;100, test-123, null, null&#93;</span><br/>
    );<br/>
    -> at org.apache.storm.hive.bolt.TestHiveBolt.testWithTimeformat(TestHiveBolt.java:235)</p>

<p>    However, there were other interactions with this mock:<br/>
    -> at backtype.storm.task.OutputCollector.reportError(OutputCollector.java:223)<br/>
    -> at backtype.storm.task.OutputCollector.fail(OutputCollector.java:218)<br/>
    -> at backtype.storm.task.OutputCollector.reportError(OutputCollector.java:223)<br/>
    -> at backtype.storm.task.OutputCollector.fail(OutputCollector.java:218)</p>


<p>    Tests run: 12, Failures: 1, Errors: 0, Skipped: 0<br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/609#issuecomment-130092091" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/609#issuecomment-130092091</a></p>

<p>    For now, all Travis CI builds are failing due to SNAPSHOT issue on storm-hive.<br/>
    It is already bothering us, so I think we should take this first, and discuss later improvements for this issue.<br/>
    +1.</p>

<p>    @caofangkun <br/>
    I'm sorry but removing calcite-core from dependency is minor at now. It would be better to be addressed again when we agree to check hive version compatibilities.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/609" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/609</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dossett" class="user-hover" rel="dossett">Aaron Blake Niskode-Dossett</a>, I merged this to master.</p>

<p>I don't have an idea we should apply this to 0.10.0, so I'd like to let Committer Sponsors decide it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/718" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/718</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-944" title="storm-hive pom.xml has a dependency conflict with calcite" class="issue-link" data-issue-key="STORM-944"><del>STORM-944</del></a>: storm-hive pom.xml has a dependency conflict with calcite (backport to 0.10.x)</p>

<p>    For future maintaining 0.10.x-branch.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-944" title="storm-hive pom.xml has a dependency conflict with calcite" class="issue-link" data-issue-key="STORM-944"><del>STORM-944</del></a>-0.10-x-branch</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/718.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/718.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #718</p>

<hr />
<p>commit 9b89cf0a0e418ad243f88c527577f0c4886bf8e0<br/>
Author: Aaron Dossett <aaron.dossett@target.com><br/>
Date:   2015-06-30T19:49:38Z</p>

<p>    resolve calcite dependency conflict</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/718#issuecomment-137580109" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/718#issuecomment-137580109</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/718" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/718</a></p>
