### ISSUE TITLE
[STORM-965] excessive logging in storm when non-kerberos client tries to connect.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4803]
<p>Ambari alert service pings nimbus thrift port to check if the process is alive or not. This causes unnecessary logging </p>

<p>b.s.s.a.k.KerberosSaslTransportPlugin <span class="error">&#91;ERROR&#93;</span> Storm server failed to open transport to interact with a client during session initiation: java.lang.NullPointerException<br/>
java.lang.NullPointerException: null<br/>
	at org.apache.thrift7.transport.TSocket.open(TSocket.java:170) ~<span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at org.apache.thrift7.transport.TSaslTransport.open(TSaslTransport.java:266) ~<span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at org.apache.thrift7.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~<span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at org.apache.thrift7.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~<span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory$1.run(KerberosSaslTransportPlugin.java:195) <span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory$1.run(KerberosSaslTransportPlugin.java:192) <span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at java.security.AccessController.doPrivileged(Native Method) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
	at javax.security.auth.Subject.doAs(Subject.java:415) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
	at backtype.storm.security.auth.kerberos.KerberosSaslTransportPlugin$TUGIAssumingTransportFactory.getTransport(KerberosSaslTransportPlugin.java:191) <span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) <span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
2015-07-17T10:35:52.723+0000 o.a.t.s.TThreadPoolServer <span class="error">&#91;ERROR&#93;</span> Error occurred during processing of message.<br/>
java.lang.NullPointerException: null<br/>
	at backtype.storm.security.auth.SaslTransportPlugin$TUGIWrapProcessor.process(SaslTransportPlugin.java:120) ~<span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285) ~<span class="error">&#91;storm-core-0.10.0.2.3.0.0-2557.jar:0.10.0.2.3.0.0-2557&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_67&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Harsha" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-965" target="_blank">excessive logging in storm when non-kerberos client tries to connect.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Parag Shah" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pshah">pshah</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-09-10T20:39:14+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user priyank5485 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/686" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/686</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-965" title="excessive logging in storm when non-kerberos client tries to connect." class="issue-link" data-issue-key="STORM-965"><del>STORM-965</del></a>: Fix excessive logging</p>

<p>    The reason for this pull request is that when a non-secure client tries to connect to nimbus host in a secure cluster, an exception was being thrown and a null transport object was being returned. This null object in turn was being used by thrift library class and threw a null pointer exception. Both the classes where exception was thrown and caught were logging this exception, creating unnecessary lengthy log statements. Disabling logging in storm code by changing it from error to debug took care of one part but to work around the issue of exception being logged in the thrift jar a NoOpTTrasport.java had to be created. Two main things to consider during review<br/>
    1. Change from Logger.error to Logger.debug in KerberosSaslTransportPlugin.java<br/>
    2. Early return false in SaslTransportPlugin.java which is presumed and tested with one nimbus client to work okay. </p>

<p>    Note: TProcess interface process method does not have documentation saying what the returned boolean indicates. </p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/priyank5485/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/priyank5485/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-965" title="excessive logging in storm when non-kerberos client tries to connect." class="issue-link" data-issue-key="STORM-965"><del>STORM-965</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/686.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/686.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #686</p>

<hr />
<p>commit f29de472a21a9f5936cb13d26cc5a36669c48164<br/>
Author: Priyank <pshah@hortonworks.com><br/>
Date:   2015-08-13T22:42:24Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-965" title="excessive logging in storm when non-kerberos client tries to connect." class="issue-link" data-issue-key="STORM-965"><del>STORM-965</del></a>: Fix excessive logging</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/686#issuecomment-131219427" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/686#issuecomment-131219427</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/686" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/686</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pshah" class="user-hover" rel="pshah">Parag Shah</a> merged into master.</p>
