### ISSUE TITLE
[STORM-973] Netty-Client Connection Failed

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4811]
<p>When Storm Topology startup in a distribution cluster I found netty connection will failed and messages will be droped by client itself. </p>

<p>worker log info as following :</p>

<p>```<br/>
2015-08-07T11:43:18.903+0800 b.s.m.n.StormClientErrorHandler <span class="error">&#91;INFO&#93;</span> Connection failed Netty-Client-storm-01<br/>
java.io.IOException: Connection reset by peer<br/>
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~<span class="error">&#91;na:1.7.0_75&#93;</span><br/>
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~<span class="error">&#91;na:1.7.0_75&#93;</span><br/>
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~<span class="error">&#91;na:1.7.0_75&#93;</span><br/>
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~<span class="error">&#91;na:1.7.0_75&#93;</span><br/>
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~<span class="error">&#91;na:1.7.0_75&#93;</span><br/>
	at org.apache.storm.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
	at org.apache.storm.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
	at org.apache.storm.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
	at org.apache.storm.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
	at org.apache.storm.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
	at org.apache.storm.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
	at org.apache.storm.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) <span class="error">&#91;storm-core-0.9.4.jar:0.9.4&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;na:1.7.0_75&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;na:1.7.0_75&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_75&#93;</span><br/>
2015-08-07T11:43:19.426+0800 b.s.m.n.Client <span class="error">&#91;INFO&#93;</span> connection attempt 1 to Netty-Client-syq-storm-01.meilishuo.com/172.16.7.25:8711 scheduled to run in 0 ms<br/>
2015-08-07T11:43:19.427+0800 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> connection to Netty-Client-storm-01 is unavailable<br/>
2015-08-07T11:43:19.427+0800 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> dropping 1 message(s) destined for Netty-Client-storm-01<br/>
2015-08-07T11:43:19.428+0800 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> connection to Netty-Client-storm-01 is unavailable<br/>
2015-08-07T11:43:19.428+0800 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> dropping 103 message(s) destined for Netty-Client-storm-01 <br/>
2015-08-07T11:43:19.428+0800 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> connection to Netty-Client-storm-01 is unavailable<br/>
2015-08-07T11:43:19.428+0800 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> dropping 35 message(s) destined for Netty-Client-storm-01<br/>
```</p>

---
<details><summary><i>Originally reported by <a title="darion yaphet" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=darion">darion</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-973" target="_blank">Netty-Client Connection Failed</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-06-29T05:06:13+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alex.panov">alex.panov</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=darion" class="user-hover" rel="darion">darion yaphet</a> Can you please attach a unit test that reproduces the error?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=darion">darion</a>:</i>
<p>Hello  Alex ~  It's seems difficulty because this is dependent on network envirnment .</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=noppanit">noppanit</a>:</i>
<p>I got the same problem but in my case one of the worker was just too busy doing GC. I increased the memory and things are working fine. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vesense">vesense</a>:</i>
<p>hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=darion" class="user-hover" rel="darion">darion yaphet</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=noppanit" class="user-hover" rel="noppanit">Noppanit Charassinvichai</a></p>

<p>This issue should has been fixed by <a href="https://issues.apache.org/jira/browse/STORM-763" title="nimbus reassigned worker A to another machine, but other worker&#39;s netty client can&#39;t connect to the new worker A " class="issue-link" data-issue-key="STORM-763"><del>STORM-763</del></a>. You can upgrade your storm to solve the problem.</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1409">STORM-1409</a>]</i>
