### ISSUE TITLE
[STORM-981] Random test failures on backtype.storm.security.auth.drpc-auth-test

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4819]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">--------------------------------------------------
Error parsing /home/travis/build/HeartSaVioR/storm/storm-core/target/test-reports/backtype.storm.security.auth.drpc-auth-test.xml
<?xml version=<span class="code-quote">"1.0"</span> encoding=<span class="code-quote">"UTF-8"</span>?>
<testsuites>
    <testsuite <span class="code-keyword">package</span>=<span class="code-quote">"backtype.storm.security.auth"</span> name=<span class="code-quote">"drpc-auth-test"</span>>
<testcase name=<span class="code-quote">"deny-drpc-digest-test"</span> classname=<span class="code-quote">"backtype.storm.security.auth.drpc-auth-test"</span>>
    <system-out>
<![CDATA[151632 [main] INFO  b.s.u.Utils - Using defaults.yaml from resources
151639 [main] INFO  b.s.s.a.drpc-auth-test - storm conf:{<span class="code-quote">"topology.builtin.metrics.bucket.size.secs"</span> 60, <span class="code-quote">"nimbus.childopts"</span> <span class="code-quote">"-Xmx1024m"</span>, <span class="code-quote">"ui.filter.params"</span> nil, <span class="code-quote">"storm.cluster.mode"</span> <span class="code-quote">"distributed"</span>, <span class="code-quote">"storm.messaging.netty.client_worker_threads"</span> 1, <span class="code-quote">"supervisor.run.worker.as.user"</span> <span class="code-keyword">false</span>, <span class="code-quote">"topology.max.task.parallelism"</span> nil, <span class="code-quote">"zmq.threads"</span> 1, <span class="code-quote">"storm.group.mapping.service"</span> <span class="code-quote">"backtype.storm.security.auth.ShellBasedGroupsMapping"</span>, <span class="code-quote">"transactional.zookeeper.root"</span> <span class="code-quote">"/transactional"</span>, <span class="code-quote">"topology.sleep.spout.wait.strategy.time.ms"</span> 1, <span class="code-quote">"drpc.invocations.port"</span> 33709, <span class="code-quote">"topology.multilang.serializer"</span> <span class="code-quote">"backtype.storm.multilang.JsonSerializer"</span>, <span class="code-quote">"storm.messaging.netty.server_worker_threads"</span> 1, <span class="code-quote">"topology.max.error.report.per.interval"</span> 5, <span class="code-quote">"storm.thrift.transport"</span> <span class="code-quote">"backtype.storm.security.auth.digest.DigestSaslTransportPlugin"</span>, <span class="code-quote">"zmq.hwm"</span> 0, <span class="code-quote">"storm.principal.tolocal"</span> <span class="code-quote">"backtype.storm.security.auth.DefaultPrincipalToLocal"</span>, <span class="code-quote">"supervisor.worker.shutdown.sleep.secs"</span> 1, <span class="code-quote">"storm.zookeeper.retry.times"</span> 5, <span class="code-quote">"ui.actions.enabled"</span> <span class="code-keyword">true</span>, <span class="code-quote">"zmq.linger.millis"</span> 5000, <span class="code-quote">"supervisor.enable"</span> <span class="code-keyword">true</span>, <span class="code-quote">"topology.stats.sample.rate"</span> 0.05, <span class="code-quote">"storm.messaging.netty.min_wait_ms"</span> 100, <span class="code-quote">"storm.zookeeper.port"</span> 2181, <span class="code-quote">"supervisor.heartbeat.frequency.secs"</span> 5, <span class="code-quote">"topology.enable.message.timeouts"</span> <span class="code-keyword">true</span>, <span class="code-quote">"drpc.worker.threads"</span> 64, <span class="code-quote">"drpc.queue.size"</span> 128, <span class="code-quote">"drpc.https.keystore.password"</span> <span class="code-quote">"", "</span>logviewer.port<span class="code-quote">" 8000, "</span>nimbus.reassign<span class="code-quote">" <span class="code-keyword">true</span>, "</span>topology.executor.send.buffer.size<span class="code-quote">" 1024, "</span>topology.spout.wait.strategy<span class="code-quote">" "</span>backtype.storm.spout.SleepSpoutWaitStrategy<span class="code-quote">", "</span>ui.host<span class="code-quote">" "</span>0.0.0.0<span class="code-quote">", "</span>storm.nimbus.retry.interval.millis<span class="code-quote">" 2000, "</span>nimbus.inbox.jar.expiration.secs<span class="code-quote">" 3600, "</span>dev.zookeeper.path<span class="code-quote">" "</span>/tmp/dev-storm-zookeeper<span class="code-quote">", "</span>topology.acker.executors<span class="code-quote">" nil, "</span>topology.fall.back.on.java.serialization<span class="code-quote">" <span class="code-keyword">true</span>, "</span>storm.zookeeper.servers<span class="code-quote">" ["</span>localhost<span class="code-quote">"], "</span>nimbus.thrift.threads<span class="code-quote">" 64, "</span>logviewer.cleanup.age.mins<span class="code-quote">" 10080, "</span>topology.worker.childopts<span class="code-quote">" nil, "</span>topology.classpath<span class="code-quote">" nil, "</span>drpc.authorizer<span class="code-quote">" "</span>backtype.storm.security.auth.authorizer.DenyAuthorizer<span class="code-quote">", "</span>supervisor.monitor.frequency.secs<span class="code-quote">" 3, "</span>nimbus.credential.renewers.freq.secs<span class="code-quote">" 600, "</span>topology.skip.missing.kryo.registrations<span class="code-quote">" <span class="code-keyword">false</span>, "</span>drpc.authorizer.acl.filename<span class="code-quote">" "</span>drpc-auth-acl.yaml<span class="code-quote">", "</span>storm.group.mapping.service.cache.duration.secs<span class="code-quote">" 120, "</span>topology.testing.always.<span class="code-keyword">try</span>.serialize<span class="code-quote">" <span class="code-keyword">false</span>, "</span>nimbus.monitor.freq.secs<span class="code-quote">" 10, "</span>supervisor.supervisors<span class="code-quote">" [], "</span>topology.tasks<span class="code-quote">" nil, "</span>topology.bolts.outgoing.overflow.buffer.enable<span class="code-quote">" <span class="code-keyword">false</span>, "</span>storm.messaging.netty.socket.backlog<span class="code-quote">" 500, "</span>topology.workers<span class="code-quote">" 1, "</span>storm.local.dir<span class="code-quote">" "</span>storm-local<span class="code-quote">", "</span>worker.childopts<span class="code-quote">" "</span>-Xmx768m<span class="code-quote">", "</span>storm.auth.simple-white-list.users<span class="code-quote">" [], "</span>topology.message.timeout.secs<span class="code-quote">" 30, "</span>topology.state.synchronization.timeout.secs<span class="code-quote">" 60, "</span>topology.tuple.serializer<span class="code-quote">" "</span>backtype.storm.serialization.types.ListDelegateSerializer<span class="code-quote">", "</span>supervisor.supervisors.commands<span class="code-quote">" [], "</span>logviewer.childopts<span class="code-quote">" "</span>-Xmx128m<span class="code-quote">", "</span>topology.environment<span class="code-quote">" nil, "</span>topology.debug<span class="code-quote">" <span class="code-keyword">false</span>, "</span>storm.messaging.netty.max_retries<span class="code-quote">" 300, "</span>ui.childopts<span class="code-quote">" "</span>-Xmx768m<span class="code-quote">", "</span>storm.zookeeper.session.timeout<span class="code-quote">" 20000, "</span>drpc.childopts<span class="code-quote">" "</span>-Xmx768m<span class="code-quote">", "</span>drpc.http.creds.plugin<span class="code-quote">" "</span>backtype.storm.security.auth.DefaultHttpCredentialsPlugin<span class="code-quote">", "</span>storm.zookeeper.connection.timeout<span class="code-quote">" 15000, "</span>storm.zookeeper.auth.user<span class="code-quote">" nil, "</span>storm.meta.serialization.delegate<span class="code-quote">" "</span>backtype.storm.serialization.GzipThriftSerializationDelegate<span class="code-quote">", "</span>topology.max.spout.pending<span class="code-quote">" nil, "</span>nimbus.supervisor.timeout.secs<span class="code-quote">" 60, "</span>nimbus.task.timeout.secs<span class="code-quote">" 30, "</span>drpc.port<span class="code-quote">" 33708, "</span>storm.zookeeper.retry.intervalceiling.millis<span class="code-quote">" 30000, "</span>nimbus.thrift.port<span class="code-quote">" 6627, "</span>storm.auth.simple-acl.admins<span class="code-quote">" [], "</span>storm.nimbus.retry.times<span class="code-quote">" 5, "</span>supervisor.worker.start.timeout.secs<span class="code-quote">" 120, "</span>storm.zookeeper.retry.interval<span class="code-quote">" 1000, "</span>logs.users<span class="code-quote">" nil, "</span>transactional.zookeeper.port<span class="code-quote">" nil, "</span>drpc.max_buffer_size<span class="code-quote">" 1048576, "</span>task.credentials.poll.secs<span class="code-quote">" 30, "</span>drpc.https.keystore.type<span class="code-quote">" "</span>JKS<span class="code-quote">", "</span>topology.worker.receiver.thread.count<span class="code-quote">" 1, "</span>supervisor.slots.ports<span class="code-quote">" [6700 6701 6702 6703], "</span>topology.transfer.buffer.size<span class="code-quote">" 1024, "</span>topology.worker.shared.thread.pool.size<span class="code-quote">" 4, "</span>drpc.authorizer.acl.strict<span class="code-quote">" <span class="code-keyword">false</span>, "</span>nimbus.file.copy.expiration.secs<span class="code-quote">" 600, "</span>topology.executor.receive.buffer.size<span class="code-quote">" 1024, "</span>java.security.auth.login.config<span class="code-quote">" "</span>test/clj/backtype/storm/security/auth/jaas_digest.conf<span class="code-quote">", "</span>nimbus.task.launch.secs<span class="code-quote">" 120, "</span>storm.local.mode.zmq<span class="code-quote">" <span class="code-keyword">false</span>, "</span>storm.messaging.netty.buffer_size<span class="code-quote">" 5242880, "</span>worker.heartbeat.frequency.secs<span class="code-quote">" 1, "</span>ui.http.creds.plugin<span class="code-quote">" "</span>backtype.storm.security.auth.DefaultHttpCredentialsPlugin<span class="code-quote">", "</span>storm.zookeeper.root<span class="code-quote">" "</span>/storm<span class="code-quote">", "</span>topology.tick.tuple.freq.secs<span class="code-quote">" nil, "</span>drpc.https.port<span class="code-quote">" -1, "</span>task.refresh.poll.secs<span class="code-quote">" 10, "</span>task.heartbeat.frequency.secs<span class="code-quote">" 3, "</span>storm.messaging.netty.max_wait_ms<span class="code-quote">" 1000, "</span>drpc.http.port<span class="code-quote">" 3774, "</span>topology.error.throttle.interval.secs<span class="code-quote">" 10, "</span>storm.messaging.transport<span class="code-quote">" "</span>backtype.storm.messaging.netty.Context<span class="code-quote">", "</span>storm.messaging.netty.authentication<span class="code-quote">" <span class="code-keyword">false</span>, "</span>topology.kryo.factory<span class="code-quote">" "</span>backtype.storm.serialization.DefaultKryoFactory<span class="code-quote">", "</span>worker.gc.childopts<span class="code-quote">" "</span><span class="code-quote">", "</span>nimbus.topology.validator<span class="code-quote">" "</span>backtype.storm.nimbus.DefaultTopologyValidator<span class="code-quote">", "</span>nimbus.cleanup.inbox.freq.secs<span class="code-quote">" 600, "</span>ui.users<span class="code-quote">" nil, "</span>transactional.zookeeper.servers<span class="code-quote">" nil, "</span>supervisor.worker.timeout.secs<span class="code-quote">" 30, "</span>storm.zookeeper.auth.password<span class="code-quote">" nil, "</span>supervisor.childopts<span class="code-quote">" "</span>-Xmx256m<span class="code-quote">", "</span>ui.filter<span class="code-quote">" nil, "</span>ui.header.buffer.bytes<span class="code-quote">" 4096, "</span>topology.disruptor.wait.timeout.millis<span class="code-quote">" 1000, "</span>storm.nimbus.retry.intervalceiling.millis<span class="code-quote">" 60000, "</span>topology.trident.batch.emit.interval.millis<span class="code-quote">" 500, "</span>topology.disruptor.wait.strategy<span class="code-quote">" "</span>com.lmax.disruptor.BlockingWaitStrategy<span class="code-quote">", "</span>storm.auth.simple-acl.users<span class="code-quote">" [], "</span>drpc.invocations.threads<span class="code-quote">" 64, "</span>java.library.path<span class="code-quote">" "</span>/usr/local/lib:/opt/local/lib:/usr/lib<span class="code-quote">", "</span>ui.port<span class="code-quote">" 8080, "</span>storm.messaging.netty.transfer.batch.size<span class="code-quote">" 262144, "</span>logviewer.appender.name<span class="code-quote">" "</span>A1<span class="code-quote">", "</span>nimbus.thrift.max_buffer_size<span class="code-quote">" 1048576, "</span>nimbus.host<span class="code-quote">" "</span>localhost<span class="code-quote">", "</span>storm.auth.simple-acl.users.commands<span class="code-quote">" [], "</span>drpc.request.timeout.secs" 600}
151639 [main] INFO  b.s.s.a.drpc-auth-test - Starting DRPC invocation server ...
151640 [<span class="code-object">Thread</span>-1350] INFO  b.s.s.a.d.DigestSaslTransportPlugin - SASL DIGEST-MD5 transport factory will be used
151696 [<span class="code-object">Thread</span>-1203-SendThread(localhost:2000)] WARN  o.a.z.ClientCnxn - Session 0x14f1c8c8933000a <span class="code-keyword">for</span> server <span class="code-keyword">null</span>, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_31]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[?:1.8.0_31]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) [zookeeper-3.4.6.jar:3.4.6-1569965]
151740 [main] INFO  b.s.s.a.drpc-auth-test - Starting DRPC handler server ...
151741 [<span class="code-object">Thread</span>-1351] INFO  b.s.s.a.d.DigestSaslTransportPlugin - SASL DIGEST-MD5 transport factory will be used
151845 [pool-1377-thread-1] INFO  b.s.s.a.d.ServerCallbackHandler - Successfully authenticated client: authenticationID = bob authorizationID = bob
151848 [pool-1376-thread-1] INFO  b.s.s.a.d.ServerCallbackHandler - Successfully authenticated client: authenticationID = bob authorizationID = bob
151855 [pool-1377-thread-1] INFO  b.s.s.a.a.DenyAuthorizer - [req 124] Access  from: /127.0.0.1 principal:bob op:execute topoology:<span class="code-keyword">null</span>
151862 [pool-1376-thread-1] INFO  b.s.s.a.a.DenyAuthorizer - [req 125] Access  from: /127.0.0.1 principal:bob op:fetchRequest topoology:<span class="code-keyword">null</span>
151864 [main] INFO  b.s.s.a.drpc-auth-test - Stopping DRPC servers ...
]]>    </system-out>
</testcase>
<testcase name=<span class="code-quote">"drpc-per-function-auth-non-strict-test"</span> classname=<span class="code-quote">"backtype.storm.security.auth.drpc-auth-test"</span>>
    <system-out>
<![CDATA[151868 [main] INFO  b.s.s.a.drpc-auth-test - storm conf:{<span class="code-quote">"topology.builtin.metrics.bucket.size.secs"</span> 60, <span class="code-quote">"nimbus.childopts"</span> <span class="code-quote">"-Xmx1024m"</span>, <span class="code-quote">"ui.filter.params"</span> nil, <span class="code-quote">"storm.cluster.mode"</span> <span class="code-quote">"distributed"</span>, <span class="code-quote">"storm.messaging.netty.client_worker_threads"</span> 1, <span class="code-quote">"supervisor.run.worker.as.user"</span> <span class="code-keyword">false</span>, <span class="code-quote">"topology.max.task.parallelism"</span> nil, <span class="code-quote">"zmq.threads"</span> 1, <span class="code-quote">"storm.group.mapping.service"</span> <span class="code-quote">"backtype.storm.security.auth.ShellBasedGroupsMapping"</span>, <span class="code-quote">"transactional.zookeeper.root"</span> <span class="code-quote">"/transactional"</span>, <span class="code-quote">"topology.sleep.spout.wait.strategy.time.ms"</span> 1, <span class="code-quote">"drpc.invocations.port"</span> 38836, <span class="code-quote">"topology.multilang.serializer"</span> <span class="code-quote">"backtype.storm.multilang.JsonSerializer"</span>, <span class="code-quote">"storm.messaging.netty.server_worker_threads"</span> 1, <span class="code-quote">"topology.max.error.report.per.interval"</span> 5, <span class="code-quote">"storm.thrift.transport"</span> <span class="code-quote">"backtype.storm.security.auth.digest.DigestSaslTransportPlugin"</span>, <span class="code-quote">"zmq.hwm"</span> 0, <span class="code-quote">"storm.principal.tolocal"</span> <span class="code-quote">"backtype.storm.security.auth.DefaultPrincipalToLocal"</span>, <span class="code-quote">"supervisor.worker.shutdown.sleep.secs"</span> 1, <span class="code-quote">"storm.zookeeper.retry.times"</span> 5, <span class="code-quote">"ui.actions.enabled"</span> <span class="code-keyword">true</span>, <span class="code-quote">"zmq.linger.millis"</span> 5000, <span class="code-quote">"supervisor.enable"</span> <span class="code-keyword">true</span>, <span class="code-quote">"topology.stats.sample.rate"</span> 0.05, <span class="code-quote">"storm.messaging.netty.min_wait_ms"</span> 100, <span class="code-quote">"storm.zookeeper.port"</span> 2181, <span class="code-quote">"supervisor.heartbeat.frequency.secs"</span> 5, <span class="code-quote">"topology.enable.message.timeouts"</span> <span class="code-keyword">true</span>, <span class="code-quote">"drpc.worker.threads"</span> 64, <span class="code-quote">"drpc.queue.size"</span> 128, <span class="code-quote">"drpc.https.keystore.password"</span> <span class="code-quote">"", "</span>logviewer.port<span class="code-quote">" 8000, "</span>nimbus.reassign<span class="code-quote">" <span class="code-keyword">true</span>, "</span>topology.executor.send.buffer.size<span class="code-quote">" 1024, "</span>topology.spout.wait.strategy<span class="code-quote">" "</span>backtype.storm.spout.SleepSpoutWaitStrategy<span class="code-quote">", "</span>ui.host<span class="code-quote">" "</span>0.0.0.0<span class="code-quote">", "</span>storm.nimbus.retry.interval.millis<span class="code-quote">" 2000, "</span>nimbus.inbox.jar.expiration.secs<span class="code-quote">" 3600, "</span>dev.zookeeper.path<span class="code-quote">" "</span>/tmp/dev-storm-zookeeper<span class="code-quote">", "</span>topology.acker.executors<span class="code-quote">" nil, "</span>topology.fall.back.on.java.serialization<span class="code-quote">" <span class="code-keyword">true</span>, "</span>storm.zookeeper.servers<span class="code-quote">" ["</span>localhost<span class="code-quote">"], "</span>nimbus.thrift.threads<span class="code-quote">" 64, "</span>logviewer.cleanup.age.mins<span class="code-quote">" 10080, "</span>topology.worker.childopts<span class="code-quote">" nil, "</span>topology.classpath<span class="code-quote">" nil, "</span>drpc.authorizer<span class="code-quote">" "</span>backtype.storm.security.auth.authorizer.DRPCSimpleACLAuthorizer<span class="code-quote">", "</span>supervisor.monitor.frequency.secs<span class="code-quote">" 3, "</span>nimbus.credential.renewers.freq.secs<span class="code-quote">" 600, "</span>topology.skip.missing.kryo.registrations<span class="code-quote">" <span class="code-keyword">false</span>, "</span>drpc.authorizer.acl.filename<span class="code-quote">" "</span>drpc-simple-acl-test-scenario.yaml<span class="code-quote">", "</span>storm.group.mapping.service.cache.duration.secs<span class="code-quote">" 120, "</span>topology.testing.always.<span class="code-keyword">try</span>.serialize<span class="code-quote">" <span class="code-keyword">false</span>, "</span>nimbus.monitor.freq.secs<span class="code-quote">" 10, "</span>supervisor.supervisors<span class="code-quote">" [], "</span>topology.tasks<span class="code-quote">" nil, "</span>topology.bolts.outgoing.overflow.buffer.enable<span class="code-quote">" <span class="code-keyword">false</span>, "</span>storm.messaging.netty.socket.backlog<span class="code-quote">" 500, "</span>topology.workers<span class="code-quote">" 1, "</span>storm.local.dir<span class="code-quote">" "</span>storm-local<span class="code-quote">", "</span>worker.childopts<span class="code-quote">" "</span>-Xmx768m<span class="code-quote">", "</span>storm.auth.simple-white-list.users<span class="code-quote">" [], "</span>topology.message.timeout.secs<span class="code-quote">" 30, "</span>topology.state.synchronization.timeout.secs<span class="code-quote">" 60, "</span>topology.tuple.serializer<span class="code-quote">" "</span>backtype.storm.serialization.types.ListDelegateSerializer<span class="code-quote">", "</span>supervisor.supervisors.commands<span class="code-quote">" [], "</span>logviewer.childopts<span class="code-quote">" "</span>-Xmx128m<span class="code-quote">", "</span>topology.environment<span class="code-quote">" nil, "</span>topology.debug<span class="code-quote">" <span class="code-keyword">false</span>, "</span>storm.messaging.netty.max_retries<span class="code-quote">" 300, "</span>ui.childopts<span class="code-quote">" "</span>-Xmx768m<span class="code-quote">", "</span>storm.zookeeper.session.timeout<span class="code-quote">" 20000, "</span>drpc.childopts<span class="code-quote">" "</span>-Xmx768m<span class="code-quote">", "</span>drpc.http.creds.plugin<span class="code-quote">" "</span>backtype.storm.security.auth.DefaultHttpCredentialsPlugin<span class="code-quote">", "</span>storm.zookeeper.connection.timeout<span class="code-quote">" 15000, "</span>storm.zookeeper.auth.user<span class="code-quote">" nil, "</span>storm.meta.serialization.delegate<span class="code-quote">" "</span>backtype.storm.serialization.GzipThriftSerializationDelegate<span class="code-quote">", "</span>topology.max.spout.pending<span class="code-quote">" nil, "</span>nimbus.supervisor.timeout.secs<span class="code-quote">" 60, "</span>nimbus.task.timeout.secs<span class="code-quote">" 30, "</span>drpc.port<span class="code-quote">" 38835, "</span>storm.zookeeper.retry.intervalceiling.millis<span class="code-quote">" 30000, "</span>nimbus.thrift.port<span class="code-quote">" 6627, "</span>storm.auth.simple-acl.admins<span class="code-quote">" [], "</span>storm.nimbus.retry.times<span class="code-quote">" 5, "</span>supervisor.worker.start.timeout.secs<span class="code-quote">" 120, "</span>storm.zookeeper.retry.interval<span class="code-quote">" 1000, "</span>logs.users<span class="code-quote">" nil, "</span>transactional.zookeeper.port<span class="code-quote">" nil, "</span>drpc.max_buffer_size<span class="code-quote">" 1048576, "</span>task.credentials.poll.secs<span class="code-quote">" 30, "</span>drpc.https.keystore.type<span class="code-quote">" "</span>JKS<span class="code-quote">", "</span>topology.worker.receiver.thread.count<span class="code-quote">" 1, "</span>supervisor.slots.ports<span class="code-quote">" [6700 6701 6702 6703], "</span>topology.transfer.buffer.size<span class="code-quote">" 1024, "</span>topology.worker.shared.thread.pool.size<span class="code-quote">" 4, "</span>drpc.authorizer.acl.strict<span class="code-quote">" <span class="code-keyword">false</span>, "</span>nimbus.file.copy.expiration.secs<span class="code-quote">" 600, "</span>topology.executor.receive.buffer.size<span class="code-quote">" 1024, "</span>java.security.auth.login.config<span class="code-quote">" "</span>test/clj/backtype/storm/security/auth/drpc-auth-server.jaas<span class="code-quote">", "</span>nimbus.task.launch.secs<span class="code-quote">" 120, "</span>storm.local.mode.zmq<span class="code-quote">" <span class="code-keyword">false</span>, "</span>storm.messaging.netty.buffer_size<span class="code-quote">" 5242880, "</span>worker.heartbeat.frequency.secs<span class="code-quote">" 1, "</span>ui.http.creds.plugin<span class="code-quote">" "</span>backtype.storm.security.auth.DefaultHttpCredentialsPlugin<span class="code-quote">", "</span>storm.zookeeper.root<span class="code-quote">" "</span>/storm<span class="code-quote">", "</span>topology.tick.tuple.freq.secs<span class="code-quote">" nil, "</span>drpc.https.port<span class="code-quote">" -1, "</span>task.refresh.poll.secs<span class="code-quote">" 10, "</span>task.heartbeat.frequency.secs<span class="code-quote">" 3, "</span>storm.messaging.netty.max_wait_ms<span class="code-quote">" 1000, "</span>drpc.http.port<span class="code-quote">" 3774, "</span>topology.error.throttle.interval.secs<span class="code-quote">" 10, "</span>storm.messaging.transport<span class="code-quote">" "</span>backtype.storm.messaging.netty.Context<span class="code-quote">", "</span>storm.messaging.netty.authentication<span class="code-quote">" <span class="code-keyword">false</span>, "</span>topology.kryo.factory<span class="code-quote">" "</span>backtype.storm.serialization.DefaultKryoFactory<span class="code-quote">", "</span>worker.gc.childopts<span class="code-quote">" "</span><span class="code-quote">", "</span>nimbus.topology.validator<span class="code-quote">" "</span>backtype.storm.nimbus.DefaultTopologyValidator<span class="code-quote">", "</span>nimbus.cleanup.inbox.freq.secs<span class="code-quote">" 600, "</span>ui.users<span class="code-quote">" nil, "</span>transactional.zookeeper.servers<span class="code-quote">" nil, "</span>supervisor.worker.timeout.secs<span class="code-quote">" 30, "</span>storm.zookeeper.auth.password<span class="code-quote">" nil, "</span>supervisor.childopts<span class="code-quote">" "</span>-Xmx256m<span class="code-quote">", "</span>ui.filter<span class="code-quote">" nil, "</span>ui.header.buffer.bytes<span class="code-quote">" 4096, "</span>topology.disruptor.wait.timeout.millis<span class="code-quote">" 1000, "</span>storm.nimbus.retry.intervalceiling.millis<span class="code-quote">" 60000, "</span>topology.trident.batch.emit.interval.millis<span class="code-quote">" 500, "</span>topology.disruptor.wait.strategy<span class="code-quote">" "</span>com.lmax.disruptor.BlockingWaitStrategy<span class="code-quote">", "</span>storm.auth.simple-acl.users<span class="code-quote">" [], "</span>drpc.invocations.threads<span class="code-quote">" 64, "</span>java.library.path<span class="code-quote">" "</span>/usr/local/lib:/opt/local/lib:/usr/lib<span class="code-quote">", "</span>ui.port<span class="code-quote">" 8080, "</span>storm.messaging.netty.transfer.batch.size<span class="code-quote">" 262144, "</span>logviewer.appender.name<span class="code-quote">" "</span>A1<span class="code-quote">", "</span>nimbus.thrift.max_buffer_size<span class="code-quote">" 1048576, "</span>nimbus.host<span class="code-quote">" "</span>localhost<span class="code-quote">", "</span>storm.auth.simple-acl.users.commands<span class="code-quote">" [], "</span>drpc.request.timeout.secs" 600}
151868 [main] INFO  b.s.s.a.drpc-auth-test - Starting DRPC invocation server ...
151869 [<span class="code-object">Thread</span>-1354] INFO  b.s.s.a.d.DigestSaslTransportPlugin - SASL DIGEST-MD5 transport factory will be used
151869 [<span class="code-object">Thread</span>-1354] ERROR b.s.s.a.ThriftServer - ThriftServer is being stopped due to: org.apache.thrift.transport.TTransportException: Could not create ServerSocket on address 0.0.0.0/0.0.0.0:38836.
org.apache.thrift.transport.TTransportException: Could not create ServerSocket on address 0.0.0.0/0.0.0.0:38836.
	at org.apache.thrift.transport.TServerSocket.<init>(TServerSocket.java:109) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.transport.TServerSocket.<init>(TServerSocket.java:91) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.transport.TServerSocket.<init>(TServerSocket.java:83) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.transport.TServerSocket.<init>(TServerSocket.java:76) ~[libthrift-0.9.2.jar:0.9.2]
	at backtype.storm.security.auth.SaslTransportPlugin.getServer(SaslTransportPlugin.java:72) ~[classes/:?]
	at backtype.storm.security.auth.ThriftServer.serve(ThriftServer.java:70) [classes/:?]
	at backtype.storm.security.auth.drpc_auth_test$launch_server$fn__6974.invoke(drpc_auth_test.clj:52) [?:?]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.6.0.jar:?]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_31]

--------------------------------------------------
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-981" target="_blank">Random test failures on backtype.storm.security.auth.drpc-auth-test</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2018-02-01T11:09:39+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtask of parent task STORM-915

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/752" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/752</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-981" title="Random test failures on backtype.storm.security.auth.drpc-auth-test" class="issue-link" data-issue-key="STORM-981"><del>STORM-981</del></a> Wait for shutdown DRPC servers while testing in drpc_auth_test</p>

<p>    SaslTransportPlugin.getServer() returns TThreadPoolServer, and when TThreadPoolServer.stop() is called, it just flip a stop flag.</p>

<p>    <a href="https://github.com/apache/thrift/blob/0.9.2/lib/java/src/org/apache/thrift/server/TThreadPoolServer.java" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/thrift/blob/0.9.2/lib/java/src/org/apache/thrift/server/TThreadPoolServer.java</a></p>

<p>    Actual shutdown takes some time, so sometimes another unit test runs while TThreadPoolServer is being shutdown.<br/>
    Fortunately, it calls setServing(false) when shutdown is completed.</p>

<p>    I ran whole tests from Travis CI five times and drpc_auth_test is always succeed.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-981" title="Random test failures on backtype.storm.security.auth.drpc-auth-test" class="issue-link" data-issue-key="STORM-981"><del>STORM-981</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/752.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/752.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #752</p>

<hr />
<p>commit 4740a94c5233432c4e6f2f9022cb422cfa7f1b20<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2015-09-21T23:03:59Z</p>

<p>    Wait for shutdown DRPC servers while testing</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/752#issuecomment-142159071" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/752#issuecomment-142159071</a></p>

<p>    adds 2 passes on my fork and PR. <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/752#issuecomment-142164455" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/752#issuecomment-142164455</a></p>

<p>    I found that this PR can't resolve drpc_auth_test properly.<br/>
    <a href="https://travis-ci.org/HeartSaVioR/storm/jobs/81493823" class="external-link" target="_blank" rel="nofollow noopener">https://travis-ci.org/HeartSaVioR/storm/jobs/81493823</a></p>

<p>    I'll see what we can do for this failure. Closing PR for now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/752" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/752</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It's from old version we don't support now, and we don't see similar issue recently. Closing.</p>
