### ISSUE TITLE
[STORM-1022] disconnectiong between workers

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4860]
<p>We upgraded to 0.9.5 ando ran into the following exception. The supervisors did go down:</p>

<p>1 caution in our upgrade is we started a new nimbus, without any supervisors attached. Then we deployed topologies (from CICD). Next we build new supervisors and the supervisors will start on startup. However, in between the network service is restarted (due to hostname changed during the build <- chef). Just wanna throw this out in case this makes a difference.</p>

<p>In other word, it could be that supervisors started, picked up work,  then network restarted. </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">SEVERE: RuntimeException <span class="code-keyword">while</span> executing runnable org.apache.storm.guava.util.concurrent.Futures$4@445058b with executor org.apache.storm.guava.util.concurrent.MoreExecutors$SameThreadExecutorService@691bc565
java.lang.RuntimeException: Failed to connect to Netty-Client-usw2b-grunt-drone32-prod.amz.relateiq.com/10.30.103.202:6700
at backtype.storm.messaging.netty.Client.connect(Client.java:308)
at backtype.storm.messaging.netty.Client.access$1100(Client.java:78)
at backtype.storm.messaging.netty.Client$2.reconnectAgain(Client.java:297)
at backtype.storm.messaging.netty.Client$2.onSuccess(Client.java:283)
at backtype.storm.messaging.netty.Client$2.onSuccess(Client.java:275)
at org.apache.storm.guava.util.concurrent.Futures$4.run(Futures.java:1181)
at org.apache.storm.guava.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
at org.apache.storm.guava.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
at org.apache.storm.guava.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
at org.apache.storm.guava.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
at java.util.concurrent.FutureTask.set(FutureTask.java:233)
at java.util.concurrent.FutureTask.run(FutureTask.java:274)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.lang.RuntimeException: Giving up to connect to Netty-Client-usw2b-grunt-drone32-prod.amz.relateiq.com/10.30.103.202:6700 after 102 failed attempts
at backtype.storm.messaging.netty.Client.connect(Client.java:303)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jackson Chung" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cywjackson">cywjackson</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1022" target="_blank">disconnectiong between workers</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:40+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jaihind213">jaihind213</a>:</i>
<p>hi Robert,</p>

<p>The Stack trace provided is of the Metric Consumer I registered with storm.<br/>
i.e. "at com.pocketmath.nebula.metric.storm.NewRelicMetricConsumer.handleDataPoints(NewRelicMetricConsumer.java:55)`" belongs to my metric consumer code.</p>

<p>The metric consumer code threw a Runtime exception which resulted in the worker dying and supervisor trying to restart it.</p>

<p>In my Scenario, the Metric Consumer threw the Runtime exception and that lead to the main exception reported in the description.</p>

<p>Any Metric Consumer which throws a runtime exception should lead to this scenario.</p>

<p>-vishnu rao</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jaihind213">jaihind213</a>:</i>
<p>hi Robert,</p>

<p>the scenario i mentioned lead to the same exception mentioned in this jira</p>

<p>hence i wanted to share this scenario too, but in my case the worker died.</p>

<p>-vishnu</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=howardhl">howardhl</a>:</i>
<p>Recently we meet the same problem caused by Netty after several times retrial except that It's not caused by supervisor but worker them selfs.</p>
<blockquote>
<p>2016-10-24T17:12:05.981+0800 STDIO <span class="error">&#91;ERROR&#93;</span> Oct 24, 2016 5:12:05 PM org.apache.storm.guava.util.concurrent.ExecutionList executeListener<br/>
SEVERE: RuntimeException while executing runnable org.apache.storm.guava.util.concurrent.Futures$4@43f31edc with executor org.apache.storm.guava.util.concurrent.MoreExecutors$SameThreadExecutorService@e6f205e<br/>
java.lang.RuntimeException: Failed to connect to Netty-Client-xxx/xx.xx.xx.173:6721<br/>
at backtype.storm.messaging.netty.Client.connect(Client.java:308)<br/>
at backtype.storm.messaging.netty.Client.access$1100(Client.java:78)<br/>
at backtype.storm.messaging.netty.Client$2.reconnectAgain(Client.java:297)<br/>
at backtype.storm.messaging.netty.Client$2.onSuccess(Client.java:283)<br/>
at backtype.storm.messaging.netty.Client$2.onSuccess(Client.java:275)<br/>
at org.apache.storm.guava.util.concurrent.Futures$4.run(Futures.java:1181)<br/>
at org.apache.storm.guava.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)<br/>
at org.apache.storm.guava.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)<br/>
at org.apache.storm.guava.util.concurrent.ExecutionList.execute(ExecutionList.java:145)<br/>
at org.apache.storm.guava.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91)<br/>
at java.util.concurrent.FutureTask$Sync.innerSet(FutureTask.java:251)<br/>
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)<br/>
at java.util.concurrent.FutureTask.run(FutureTask.java:138)<br/>
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)<br/>
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)<br/>
at java.util.concurrent.FutureTask.run(FutureTask.java:138)<br/>
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)<br/>
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)<br/>
at java.lang.Thread.run(Thread.java:662)<br/>
Caused by: java.lang.RuntimeException: Giving up to connect to Netty-Client-sd-bigdata-storm5-73-173.idc.vip.com/10.208.73.173:6721 after 12 failed attempts<br/>
at backtype.storm.messaging.netty.Client.connect(Client.java:303)<br/>
... 20 more</p></blockquote>
<p>when workers start, they tried to connect each other. After several times retrial, one worker failed, and throw an <b>RuntimeException</b>. The <b>RuntimeException</b> is swallowed by guava, as shown in the error stack. The code is as following in ExecutionList.java line 154 in guava 16.0.1:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">private</span> <span class="code-keyword">static</span> void executeListener(<span class="code-object">Runnable</span> runnable, Executor executor) {
    <span class="code-keyword">try</span> {
      executor.execute(runnable);
    } <span class="code-keyword">catch</span> (RuntimeException e) {
      <span class="code-comment">// Log it and keep going, bad runnable and/or executor.  Don't
</span>      <span class="code-comment">// punish the other runnables <span class="code-keyword">if</span> we're given a bad one.  We only
</span>      <span class="code-comment">// <span class="code-keyword">catch</span> RuntimeException because we want Errors to propagate up.
</span>      log.log(Level.SEVERE, <span class="code-quote">"RuntimeException <span class="code-keyword">while</span> executing runnable "</span>
  + runnable + <span class="code-quote">" with executor "</span> + executor, e);
    }
  }
</pre>
</div></div>
<p>The RuntimeException will never been thrown to the timer thread of worker and thus will not cause the dead of the worker. And the worker will never try to reconnect again. The worker should die, so that supervisor will pull it up again——this won't happen if this bug exists.<br/>
Our storm version is 0.9.4 . And I can see the storm 0.9.6 has removed guava in the code. So the problem was solved in new version of storm.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
