### ISSUE TITLE
[STORM-1023] Nimbus server hogs 100% CPU and clients are stuck 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4861]
<p>Testing environment is Storm 0.9.5 / thrift java 0.7.<br/>
Test scenario: <br/>
  Deploy storm topology in loop.<br/>
  When nimbus cleanup timeout is reached, an error is thrown by thrift server: <br/>
  "Exception while invoking ..." ... TException</p>

<p>Test result:<br/>
  Thrift java server in nimbus goes 100% CPU in infinite loop in:</p>

<p>jstack:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-quote">"<span class="code-object">Thread</span>-5"</span> prio=10 tid=0x00007fb134aab800 nid=0x6767 runnable [0x00007fb129c9b000]
   java.lang.<span class="code-object">Thread</span>.State: RUNNABLE
      at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
      at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
      at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
      at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
...
at org.apache.thrift7.server.TNonblockingServer$SelectThread.select(TNonblockingServer.java:284) 
</pre>
</div></div>

<p>strace:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">epoll_wait(70, {{EPOLLIN, {u32=866, u64=866}}, {EPOLLIN, {u32=876, u64=876}}}, 4096, 4294967295) = 2
</pre>
</div></div>

<p>Investigation and tests show that:<br/>
Any Exception thrown during the processor execution will bypass the call to </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> responseReady() </pre>
</div></div>
<p> and will cause the counter </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">       readBufferBytesAllocated.addAndGet(-buffer_.array().length); </pre>
</div></div>
<p> not to be decremented by the size of the request buffer.</p>

<p>After a bunch of failed requests, this counter almost reaches the max value MAX_READ_BUFFER_BYTES causing any subsequent request to be delayed forever because the following test in </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> read() </pre>
</div></div>
<p>:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">   <span class="code-keyword">if</span> (readBufferBytesAllocated.get() + frameSize > MAX_READ_BUFFER_BYTES)  </pre>
</div></div>
<p> is always true.</p>

<p>At the end, the server thread loops in select() which immediately wakes up for read() since the content of the socket was never drained.</p>

<p>This loops forever between select and read() method above causing a 100% CPU on server thread.<br/>
Moreover, all client requests are stuck forever.</p>

<p>Example of failed request:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2015-09-01T12:19:35.954+0200 b.s.d.nimbus [WARN] Topology submission exception. (topology name=<span class="code-quote">'mytopology'</span>) #<IllegalArgumentException java.lang.IllegalArgumentException: /opt/SPE/share/stor
m/storm/local/nimbus/inbox/stormjar-3f8f3ba7-5420-4773-af24-bfa294cceb79.jar to copy to /opt/SPE/share/storm/storm/local/nimbus/stormdist/mytopology-87-1441102775 does not exist!>
2015-09-01T12:19:35.955+0200 o.a.t.s.TNonblockingServer [ERROR] Unexpected exception <span class="code-keyword">while</span> invoking!
java.lang.IllegalArgumentException: /opt/SPE/share/storm/storm/local/nimbus/inbox/stormjar-3f8f3ba7-5420-4773-af24-bfa294cceb79.jar to copy to /opt/SPE/share/storm/storm/local/nimbus/stormdis
t/mytopology-87-1441102775 does not exist!
at backtype.storm.daemon.nimbus$fn__3827.invoke(nimbus.clj:1173) ~[storm-core-0.9.5.jar:0.9.5]
at clojure.lang.MultiFn.invoke(MultiFn.java:236) ~[clojure-1.5.1.jar:na]
at backtype.storm.daemon.nimbus$setup_storm_code.invoke(nimbus.clj:307) ~[storm-core-0.9.5.jar:0.9.5]
at backtype.storm.daemon.nimbus$fn__3724$exec_fn__1103__auto__$reify__3737.submitTopologyWithOpts(nimbus.clj:953) ~[storm-core-0.9.5.jar:0.9.5]
at backtype.storm.daemon.nimbus$fn__3724$exec_fn__1103__auto__$reify__3737.submitTopology(nimbus.clj:966) ~[storm-core-0.9.5.jar:0.9.5]
at backtype.storm.generated.Nimbus$Processor$submitTopology.getResult(Nimbus.java:1240) ~[storm-core-0.9.5.jar:0.9.5]
at backtype.storm.generated.Nimbus$Processor$submitTopology.getResult(Nimbus.java:1228) ~[storm-core-0.9.5.jar:0.9.5]
at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:32) ~[storm-core-0.9.5.jar:0.9.5]
at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:34) ~[storm-core-0.9.5.jar:0.9.5]
at org.apache.thrift7.server.TNonblockingServer$FrameBuffer.invoke(TNonblockingServer.java:632) ~[storm-core-0.9.5.jar:0.9.5]
at org.apache.thrift7.server.THsHaServer$Invocation.run(THsHaServer.java:201) [storm-core-0.9.5.jar:0.9.5]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [na:1.7.0_75]
</pre>
</div></div> 

---
<details><summary><i>Originally reported by <a title="Frantz Mazoyer" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fmazoyer">fmazoyer</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1023" target="_blank">Nimbus server hogs 100% CPU and clients are stuck </a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:09+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
