### ISSUE TITLE
[STORM-1043] Concurrent access to state on local FS by multiple supervisors

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4881]
<p>Hi,</p>

<p>we are running storm-mesos cluster and occassionaly workers die or are "lost" in mesos. When this happens it often coincides with errors in logs related to supervisors local state.</p>

<p>By looking at the storm code it seems this might be caused by the way how multiple supervisor processes access the local state in the same directory via VersionedStore.</p>

<p>For example: <a href="https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/supervisor.clj#L434" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/supervisor.clj#L434</a></p>

<p>Here every supervisor does this concurrently:<br/>
1. reads latest state from FS<br/>
2. possibly updates the state<br/>
3. writes the new version of the state</p>

<p>Some updates could be lost if there are 2+ supervisors and they execute above steps concurrently - then only the updates from last supervisor would remain on the last state version on the disk.</p>

<p>We observed local state changes quite often (seconds), so the likelihood of this concurrency issue occurring is high.</p>

<p>Some examples of exeptions:<br/>
------------------------------------------<br/>
java.lang.RuntimeException: Version already exists or data already exists<br/>
at backtype.storm.utils.VersionedStore.createVersion(VersionedStore.java:85) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.utils.VersionedStore.createVersion(VersionedStore.java:79) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.utils.LocalState.persist(LocalState.java:101) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.utils.LocalState.put(LocalState.java:82) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.utils.LocalState.put(LocalState.java:76) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this7400.invoke(supervisor.clj:382) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.event$event_manager$fn2625.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_60&#93;</span></p>

<p>---------------------------------------<br/>
java.io.FileNotFoundException: File '/var/lib/storm/supervisor/localstate/1441034838231' does not exist<br/>
at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1763) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
at backtype.storm.utils.LocalState.deserializeLatestVersion(LocalState.java:61) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.utils.LocalState.snapshot(LocalState.java:47) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.utils.LocalState.get(LocalState.java:72) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:234) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$partial$fn4190.doInvoke(core.clj:2396) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:397) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn2625.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.8.0_60&#93;</span><br/>
-----------------------------------------</p>

---
<details><summary><i>Originally reported by <a title="Ernestas Vaiciukevičius" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ernisv">ernisv</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1043" target="_blank">Concurrent access to state on local FS by multiple supervisors</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Erik Weathers" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erikdw">erikdw</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2015-10-09T02:07:37+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Having multiple supervisors share the same storm-local is bad and can result in a lot of other errors beyond this.</p>

<p>If you want to run multiple supervisors on the same node please set </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">storm.local.dir</pre>
</div></div>
<p> differently for each of them.  I am not totally sure how you are launching your supervisors through mesos, but you can set configs on the command line using -c when launching the supervisor just like you can when launching a topology.</p>

<p>You are also going to have to set the </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">supervisor.slots.ports</pre>
</div></div>
<p> to be different for each supervisor or the workers will collide with each other when trying to run.  There are likely to be other issues too.  This is not officially supported.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ernisv">ernisv</a>:</i>
<p>The link to submitted issue: <a href="https://github.com/mesos/storm/issues/60" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/mesos/storm/issues/60</a></p>
