### ISSUE TITLE
[STORM-1051] Netty Client.java's flushMessages produces a NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4889]
<p><a href="https://issues.apache.org/jira/browse/STORM-763" title="nimbus reassigned worker A to another machine, but other worker&#39;s netty client can&#39;t connect to the new worker A " class="issue-link" data-issue-key="STORM-763"><del>STORM-763</del></a> replaced `return batch != null && !batch.isEmpty();` with `if(batch.isEmpty())`... which means that if batch == null, a NullPointerException is thrown. Problem is, batch is often null, which means that 763 made Storm unusable...</p>

---
<details><summary><i>Originally reported by <a title="Michael Schonfeld" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=BaconSeason">BaconSeason</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1051" target="_blank">Netty Client.java's flushMessages produces a NullPointerException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Michael Schonfeld" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=BaconSeason">BaconSeason</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-09-20T23:07:35+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user schonfeld opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/742" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/742</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1051" title="Netty Client.java&#39;s flushMessages produces a NullPointerException" class="issue-link" data-issue-key="STORM-1051"><del>STORM-1051</del></a> Fix for flushMessagse NPE</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-763" title="nimbus reassigned worker A to another machine, but other worker&#39;s netty client can&#39;t connect to the new worker A " class="issue-link" data-issue-key="STORM-763"><del>STORM-763</del></a> introduced a situation in which flushMessages could receive batch = null, in which case, an NPE is thrown because we weren't validating != null</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/schonfeld/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/schonfeld/storm</a> 0.10.x-branch</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/742.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/742.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #742</p>

<hr />
<p>commit bcc1cc6ce1b1455a68eae8f0b1d4ceafe93d8488<br/>
Author: Michael Schonfeld <michael@schonfeld.org><br/>
Date:   2015-09-17T15:57:07Z</p>

<p>    fix npe issue</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/742#issuecomment-141480621" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/742#issuecomment-141480621</a></p>

<p>    @schonfeld <br/>
    Could you post a new PR which points to master, too?<br/>
    Thanks in advance!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user schonfeld opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1051" title="Netty Client.java&#39;s flushMessages produces a NullPointerException" class="issue-link" data-issue-key="STORM-1051"><del>STORM-1051</del></a> Fix for flushMessagse NPE</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-763" title="nimbus reassigned worker A to another machine, but other worker&#39;s netty client can&#39;t connect to the new worker A " class="issue-link" data-issue-key="STORM-763"><del>STORM-763</del></a> introduced a situation in which flushMessages could receive batch = null, in which case, an NPE is thrown because we weren't validating != null</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/schonfeld/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/schonfeld/storm</a> master</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/745.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #745</p>

<hr />
<p>commit 8b845392e920d753eb24fcffead0263416bc6227<br/>
Author: Michael Schonfeld <michael@schonfeld.org><br/>
Date:   2015-09-18T16:31:32Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1051" title="Netty Client.java&#39;s flushMessages produces a NullPointerException" class="issue-link" data-issue-key="STORM-1051"><del>STORM-1051</del></a> Fix for flushMessagse NPE</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user schonfeld closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/742" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/742</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745#issuecomment-141545624" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745#issuecomment-141545624</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It could occur easily, and the result is shown as strange worker dying. So changing priority to critical.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745#issuecomment-141593615" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745#issuecomment-141593615</a></p>

<p>    Reminder: It should be applied into all version branches.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baconseason">baconseason</a>:</i>
<p>Do I need to attach a patch file? Or is the pull request on GitHub sufficient? Also, should I mark this as resolved?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user schonfeld commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745#issuecomment-141593725" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745#issuecomment-141593725</a></p>

<p>    @HeartSaVioR all branches >= 0.9.6 ... that's when <a href="https://issues.apache.org/jira/browse/STORM-763" title="nimbus reassigned worker A to another machine, but other worker&#39;s netty client can&#39;t connect to the new worker A " class="issue-link" data-issue-key="STORM-763"><del>STORM-763</del></a> introduced the bug.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user schonfeld commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745#issuecomment-141595905" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745#issuecomment-141595905</a></p>

<p>    Ah, ok! Here's what it looked like in our logs, just in case someone else tries to Google the exception at some point...</p>

<p>    ```<br/>
    2015-09-17 15:03:22 b.s.m.n.StormClientHandler <span class="error">&#91;INFO&#93;</span> Connection failed Netty-Client-/10.244.114.24:6703<br/>
    java.lang.NullPointerException<br/>
      at backtype.storm.messaging.netty.Client.flushMessages(Client.java:320) ~<span class="error">&#91;storm-core-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT&#93;</span><br/>
      at backtype.storm.messaging.netty.Client.notifyInterestChanged(Client.java:455) ~<span class="error">&#91;storm-core-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT&#93;</span><br/>
      at backtype.storm.messaging.netty.StormClientHandler.channelInterestChanged(StormClientHandler.java:36) ~<span class="error">&#91;storm-core-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT&#93;</span><br/>
      at org.apache.storm.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:106) ~<span class="error">&#91;storm-core-0.10.1-SNAPSHOT.jar:0.10.1-SNAPSHOT&#93;</span><br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>We are waiting for more reviewer to review.<br/>
In bylaws, we should wait at least 1 day to merge PR into repository.<br/>
Please refer <a href="https://github.com/apache/storm/blob/master/DEVELOPER.md" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/DEVELOPER.md</a> and <a href="http://storm.apache.org/documentation/BYLAWS.html" class="external-link" target="_blank" rel="nofollow noopener">http://storm.apache.org/documentation/BYLAWS.html</a>.</p>

<p>Issue will be resolved by committer who merges PR, when PR gets merged into repository.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user erikdw commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745#discussion_r39913836" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745#discussion_r39913836</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/messaging/netty/Client.java &#8212;<br/>
    @@ -317,7 +317,7 @@ private int iteratorSize(Iterator<TaskMessage> msgs) {</p>
<ul>
	<li>If the write operation fails, then we will close the channel and trigger a reconnect.<br/>
  */<br/>
 private void flushMessages(Channel channel, final MessageBatch batch) {</li>
</ul>
<ul class="alternate" type="square">
	<li>if(batch.isEmpty()){<br/>
    +if(null == batch || batch.isEmpty()){
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    style nits:</p>
<ul>
	<li>`if(` -> `if (`</li>
	<li>`){` -> `) {`</li>
</ul>


<p>    Those are more consistent with the rest of this file.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user schonfeld commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745#issuecomment-141625088" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745#issuecomment-141625088</a></p>

<p>    @erikdw better now</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user schonfeld commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745#discussion_r39916772" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745#discussion_r39916772</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/messaging/netty/Client.java &#8212;<br/>
    @@ -317,7 +317,7 @@ private int iteratorSize(Iterator<TaskMessage> msgs) {</p>
<ul>
	<li>If the write operation fails, then we will close the channel and trigger a reconnect.<br/>
  */<br/>
 private void flushMessages(Channel channel, final MessageBatch batch) {</li>
</ul>
<ul class="alternate" type="square">
	<li>if(batch.isEmpty()){<br/>
    +if(null == batch || batch.isEmpty()){
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    @erikdw better now</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user erikdw commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/745#issuecomment-141631234" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745#issuecomment-141631234</a></p>

<p>    @schonfeld: thx!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/745" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/745</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=BaconSeason" class="user-hover" rel="BaconSeason">Michael Schonfeld</a> for fixing serious bug. Great work!<br/>
I merged into master, 0.10.x, 0.9.x branches.</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-763">STORM-763</a>]</i>
