### ISSUE TITLE
[STORM-1100] TNonblockingServer [ERROR] Unexpected exception while invoking!

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4938]
<p>I'm new to storm and first time to write issue here so Sorry if i made any mistake </p>

<p>when i tried to submit topology spout didn't emit anything (ZERO)<br/>
then found in Supervisor log file that hasn't still start <br/>
and in Worker log file found this <br/>
Error on initialization of server mk-worker java.io.IOException: No such file or directory at java.io.UnixFileSystem.createFileExclusively(Native Method) at java.io.File.createNewFile(Unknown Source) at backtype.storm.util$touch.invoke(util.clj:432) at backtype.storm.daemon.worker$fn_<em>4348$exec_fn</em><em>1228</em><em>auto</em>__<em>4349.invoke(worker.clj:331) at clojure.lang.AFn.applyToHelper(AFn.java:185) at clojure.lang.AFn.applyTo(AFn.java:151) at clojure.core$apply.invoke(core.clj:601) at backtype.storm.daemon.worker$fn</em><em>4348$mk_worker</em>_4404.doInvoke(worker.clj:323) at clojure.lang.RestFn.invoke(RestFn.java:512) at backtype.storm.daemon.worker$_main.invoke(worker.clj:433) at clojure.lang.AFn.applyToHelper(AFn.java:172) at clojure.lang.AFn.applyTo(AFn.java:151) at backtype.storm.daemon.worker.main(Unknown Source) 2015-10-09 02:58:47 util <span class="error">&#91;INFO&#93;</span> Halting process: ("Error on initialization")</p>

<p>and after few minutes in Nimbus log file <br/>
TNonblockingServer <span class="error">&#91;ERROR&#93;</span> Unexpected exception while invoking! java.io.FileNotFoundException: File 'storm-local/nimbus/stormdist/fsd-1-1444356616/stormcode.ser' does not exist at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:137) at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1135) at backtype.storm.daemon.nimbus$read_storm_topology.invoke(nimbus.clj:305) at backtype.storm.daemon.nimbus$fn_<em>3592$exec_fn</em><em>1228</em><em>auto</em><em>$reify</em>_3605.getTopologyInfo(nimbus.clj:1066)  </p>

---
<details><summary><i>Originally reported by <a title="SamMohel" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=SamMohel">SamMohel</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1100" target="_blank">TNonblockingServer [ERROR] Unexpected exception while invoking!</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="SamMohel" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=SamMohel">SamMohel</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:14+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
