### ISSUE TITLE
[STORM-1101] test-retry-read-assignments in backtype.storm.supervisor-test fails

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4939]
<p><a href="https://travis-ci.org/mjsax/storm/builds/84478972" class="external-link" target="_blank" rel="nofollow noopener">https://travis-ci.org/mjsax/storm/builds/84478972</a></p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>ava.lang.RuntimeException: Should not have multiple topologies assigned to one port
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_76]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_76]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_76]
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:180) ~[clojure-1.7.0.jar:?]
	at backtype.storm.util$throw_runtime.doInvoke(util.clj:845) ~[classes/:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.7.0.jar:?]
	at backtype.storm.daemon.supervisor$read_assignments$fn__9770.doInvoke(supervisor.clj:84) ~[classes/:?]
	at clojure.lang.RestFn.invoke(RestFn.java:421) ~[clojure-1.7.0.jar:?]
	at clojure.core$merge_with$merge_entry__4649.invoke(core.clj:2932) ~[clojure-1.7.0.jar:?]
	at clojure.core$reduce1.invoke(core.clj:909) ~[clojure-1.7.0.jar:?]
	at clojure.core$merge_with$merge2__4651.invoke(core.clj:2935) ~[clojure-1.7.0.jar:?]
	at clojure.core$reduce1.invoke(core.clj:909) ~[clojure-1.7.0.jar:?]
	at clojure.core$reduce1.invoke(core.clj:900) ~[clojure-1.7.0.jar:?]
	at clojure.core$merge_with.doInvoke(core.clj:2936) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) ~[clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:632) ~[clojure-1.7.0.jar:?]
	at backtype.storm.daemon.supervisor$read_assignments.invoke(supervisor.clj:84) ~[classes/:?]
	at backtype.storm.daemon.supervisor$read_assignments.invoke(supervisor.clj:86) ~[classes/:?]
	at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__10013.invoke(supervisor.clj:449) ~[classes/:?]
	at backtype.storm.event$event_manager$fn__9629.invoke(event.clj:40) [classes/:?]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Matthias J. Sax" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mjsax">mjsax</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1101" target="_blank">test-retry-read-assignments in backtype.storm.supervisor-test fails</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2018-02-01T11:11:11+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtask of parent task STORM-915

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It's from old version we don't support now, and we don't see similar issue recently. Closing.</p>
