### ISSUE TITLE
[STORM-1108] Random test failure : reset-log-levels-timer fails with NPE

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4946]
<p><a href="https://travis-ci.org/apache/storm/jobs/84955623" class="external-link" target="_blank" rel="nofollow noopener">https://travis-ci.org/apache/storm/jobs/84955623</a></p>

<p>"test-component-specific-config-clojure" shows this issue.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">94755 [reset-log-levels-timer] ERROR b.s.d.worker - Error when processing event
java.lang.NullPointerException
	at backtype.storm.utils.Time.sleepUntil(Time.java:61) ~[classes/:?]
	at backtype.storm.utils.Time.sleep(Time.java:81) ~[classes/:?]
	at backtype.storm.timer$mk_timer$fn__4130$fn__4131.invoke(timer.clj:60) [classes/:?]
	at backtype.storm.timer$mk_timer$fn__4130.invoke(timer.clj:42) [classes/:?]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_31]
94755 [reset-log-levels-timer] ERROR b.s.d.worker - Error when processing event
java.lang.NullPointerException
	at backtype.storm.utils.Time.sleepUntil(Time.java:61) ~[classes/:?]
	at backtype.storm.utils.Time.sleep(Time.java:81) ~[classes/:?]
	at backtype.storm.timer$mk_timer$fn__4130$fn__4131.invoke(timer.clj:60) [classes/:?]
	at backtype.storm.timer$mk_timer$fn__4130.invoke(timer.clj:42) [classes/:?]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_31]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1108" target="_blank">Random test failure : reset-log-levels-timer fails with NPE</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-10-15T19:38:23+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtask of parent task STORM-915

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Seems like there's race condition in Time.java.</p>

<p>1. Thread A calls Time.sleepUntil(), and passes first if statement.<br/>
2. Thread B calls Time.stopSimulating(), and acquire sleepTimesLock, and set simulating to false, and threadSleepTimes to null, and release sleepTimesLock.<br/>
3. Thread A acquire sleepTimesLock, and put sleep time to threadSleepTimes which should throw NPE.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I have a fix for this, I'll throw up a pull request soon.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user revans2 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/798" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/798</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1108" title="Random test failure : reset-log-levels-timer fails with NPE" class="issue-link" data-issue-key="STORM-1108"><del>STORM-1108</del></a>: Fix NPE in simulated time.</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/revans2/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/revans2/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1108" title="Random test failure : reset-log-levels-timer fails with NPE" class="issue-link" data-issue-key="STORM-1108"><del>STORM-1108</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/798.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/798.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #798</p>

<hr />
<p>commit 5b86f4712f92d34c32134e933b8f2c7fc3c866f0<br/>
Author: Robert (Bobby) Evans <evans@yahoo-inc.com><br/>
Date:   2015-10-14T18:33:27Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1108" title="Random test failure : reset-log-levels-timer fails with NPE" class="issue-link" data-issue-key="STORM-1108"><del>STORM-1108</del></a>: Fix NPE in simulated time.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/798#issuecomment-148165474" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/798#issuecomment-148165474</a></p>

<p>    The travis failure looks unrelated.  It is a kafka test failure.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/798#issuecomment-148225899" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/798#issuecomment-148225899</a></p>

<p>    Great work, +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/798" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/798</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I just merged this into master.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a>,</p>

<p>If you want me to cherry pick it back to 0.10.x I can, I just don't know how much more unit testing we are going to do there.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks for the work, <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a>.</p>

<p>As far as I think, we may have to get some works for 0.10.1 if some issues from 0.10.0 will be reported.<br/>
I'm also curious that how much time we should make a patch target to 0.10.x-branch, but since this patch seems be easy to backport, I'll try to.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Backported to 0.10.x-branch.</p>
