### ISSUE TITLE
[STORM-1109] Worker exists frequently due to java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4947]
<p>One of the supervisor is exiting frequently , following is the log</p>

<p>015-10-13T20:57:20.245+0530 k.c.SimpleConsumer <span class="error">&#91;INFO&#93;</span> Reconnect due to socket error: null<br/>
2015-10-13T20:57:30.284+0530 b.s.util <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
java.lang.RuntimeException: java.net.SocketTimeoutException<br/>
at storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:146) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.PartitionManager.fill(PartitionManager.java:134) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.PartitionManager.next(PartitionManager.java:108) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:123) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>6579$fn</em><em>6594$fn</em>_6623.invoke(executor.clj:565) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.util$async_loop$fn__459.invoke(util.clj:463) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
Caused by: java.net.SocketTimeoutException: null<br/>
at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:229) ~<span class="error">&#91;na:1.7.0_67&#93;</span><br/>
at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103) ~<span class="error">&#91;na:1.7.0_67&#93;</span><br/>
at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385) ~<span class="error">&#91;na:1.7.0_67&#93;</span><br/>
at kafka.utils.Utils$.read(Utils.scala:395) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.network.Receive$class.readCompletely(Transmission.scala:56) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.network.BoundedByteBufferReceive.readCompletely(BoundedByteBufferReceive.scala:29) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.network.BlockingChannel.receive(BlockingChannel.scala:100) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:81) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:71) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:110) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:110) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:110) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:109) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:109) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:109) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:108) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.javaapi.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:48) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:141) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
... 7 common frames omitted<br/>
2015-10-13T20:57:30.285+0530 b.s.d.executor <span class="error">&#91;ERROR&#93;</span><br/>
java.lang.RuntimeException: java.net.SocketTimeoutException<br/>
at storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:146) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.PartitionManager.fill(PartitionManager.java:134) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.PartitionManager.next(PartitionManager.java:108) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:123) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>6579$fn</em><em>6594$fn</em>_6623.invoke(executor.clj:565) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.util$async_loop$fn__459.invoke(util.clj:463) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
Caused by: java.net.SocketTimeoutException: null<br/>
at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:229) ~<span class="error">&#91;na:1.7.0_67&#93;</span><br/>
at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103) ~<span class="error">&#91;na:1.7.0_67&#93;</span><br/>
at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385) ~<span class="error">&#91;na:1.7.0_67&#93;</span><br/>
at kafka.utils.Utils$.read(Utils.scala:395) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.network.Receive$class.readCompletely(Transmission.scala:56) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.network.BoundedByteBufferReceive.readCompletely(BoundedByteBufferReceive.scala:29) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.network.BlockingChannel.receive(BlockingChannel.scala:100) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:81) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:71) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:110) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:110) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:110) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:109) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:109) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:109) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:108) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at kafka.javaapi.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:48) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
at storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:141) ~<span class="error">&#91;stormjar.jar:na&#93;</span><br/>
... 7 common frames omitted<br/>
2015-10-13T20:57:47.906+0530 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Worker died")<br/>
java.lang.RuntimeException: ("Worker died")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.daemon.worker$fn_<em>7028$fn</em>_7029.invoke(worker.clj:497) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.daemon.executor$mk_executor_data$fn_<em>6480$fn</em>_6481.invoke(executor.clj:240) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.util$async_loop$fn__459.invoke(util.clj:473) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
2015-10-13T20:57:47.907+0530 b.s.d.worker <span class="error">&#91;INFO&#93;</span> Shutting down worker</p>

<p>this is usually accompanied by the following error is supervisor.</p>

<p>2015-10-13T20:58:21.858+0530 b.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Shutting down fa862fbe-bfd2-4b53-9abb-cd951303ecb8:42ccaf83-6a17-4dcb-92e6-47416486806d<br/>
2015-10-13T20:58:21.869+0530 b.s.event <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.io.IOException: . doesn't exist.<br/>
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:157) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147) ~<span class="error">&#91;commons-exec-1.1.jar:1.1&#93;</span><br/>
at backtype.storm.util$exec_command_BANG_.invoke(util.clj:386) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.util$send_signal_to_process.invoke(util.clj:415) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.util$kill_process_with_sig_term.invoke(util.clj:426) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.daemon.supervisor$shutdown_worker.invoke(supervisor.clj:197) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:267) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.applyToHelper(AFn.java:161) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.AFn.applyTo(AFn.java:151) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$apply.invoke(core.clj:619) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:397) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2625.invoke(event.clj:40) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_67&#93;</span><br/>
2015-10-13T20:58:21.877+0530 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at backtype.storm.event$event_manager$fn__2625.invoke(event.clj:48) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_67&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="rakesh" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kraks">kraks</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1109" target="_blank">Worker exists frequently due to java.net.SocketTimeoutException</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:49+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kraks" class="user-hover" rel="kraks">rakesh</a>,</p>

<p>I think this is the worker and not the supervisor that is crashing.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kraks">kraks</a>:</i>
<p>Its both actually, I have provided the error that I see in  supervisor.log in the issue description just below the worker log stack trace.</p>

<p>we run storm-supervisor with supervisord, with 999 retries but it wont comeback.<br/>
However, if we clear the supervisor state by clearing the folders/files under storm/supervisor and start the supervisor it comes back</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
