### ISSUE TITLE
[STORM-1110] System Components Page is not available

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4948]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">org.apache.thrift7.transport.TTransportException
	at org.apache.thrift7.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift7.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift7.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
	at org.apache.thrift7.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.thrift7.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift7.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift7.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift7.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:69)
	at backtype.storm.generated.Nimbus$Client.recv_getComponentPageInfo(Nimbus.java:793)
	at backtype.storm.generated.Nimbus$Client.getComponentPageInfo(Nimbus.java:777)
	at backtype.storm.ui.core$component_page.invoke(core.clj:728)
	at backtype.storm.ui.core$fn__11410.invoke(core.clj:869)
	at org.apache.storm.shade.compojure.core$make_route$fn__8404.invoke(core.clj:93)
	at org.apache.storm.shade.compojure.core$if_route$fn__8392.invoke(core.clj:39)
	at org.apache.storm.shade.compojure.core$if_method$fn__8385.invoke(core.clj:24)
	at org.apache.storm.shade.compojure.core$routing$fn__8410.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2570)
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at org.apache.storm.shade.compojure.core$routes$fn__8414.invoke(core.clj:111)
	at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__10896.invoke(json.clj:56)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__8938.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__9777.invoke(reload.clj:22)
	at backtype.storm.ui.core$catch_errors$fn__11523.invoke(core.clj:1003)
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__8869.invoke(keyword_params.clj:27)
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__8909.invoke(nested_params.clj:65)
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__8840.invoke(params.clj:55)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__8938.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__9124.invoke(flash.clj:14)
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__9112.invoke(session.clj:43)
	at org.apache.storm.shade.ring.middleware.cookies$wrap_cookies$fn__9040.invoke(cookies.clj:160)
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__8746.invoke(servlet.clj:127)
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__8750.invoke(servlet.clj:136)
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)

</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1110" target="_blank">System Components Page is not available</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-10-20T14:24:11+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1110" title="System Components Page is not available" class="issue-link" data-issue-key="STORM-1110"><del>STORM-1110</del></a> Fix Component Page for system components</p>

<ul class="alternate" type="square">
	<li>Remove redundant method `system-id?` - as is calls into static `Utils/isSystemId`</li>
	<li>All System components are of type bolts.</li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> storm1110</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/799.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #799</p>

<hr />
<p>commit 8281115371e852eb540246fd127b29d1da5e6f6a<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-10-14T18:45:20Z</p>

<p>    Remove redundent clojure method system-id</p>

<p>commit 88bfa5af12ec07c0fb4c2d4a66f1812fee004edf<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-10-14T18:46:32Z</p>

<p>    The system components are of type bolts</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799#issuecomment-148177465" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799#issuecomment-148177465</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799#issuecomment-148178178" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799#issuecomment-148178178</a></p>

<p>    +1 pending no relevant build issues.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799#issuecomment-148178374" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799#issuecomment-148178374</a></p>

<p>    +1 pending build</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799#issuecomment-148182253" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799#issuecomment-148182253</a></p>

<p>    The failures look unrelated.  We got failures in nimbus-auth-test, but nothing showed up in the logs, so I am not really sure how/why they failed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799#issuecomment-148193041" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799#issuecomment-148193041</a></p>

<p>    Tests pass on my machine. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799#issuecomment-149356704" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799#issuecomment-149356704</a></p>

<p>    testing travis build..</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/799" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil reopened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1110" title="System Components Page is not available" class="issue-link" data-issue-key="STORM-1110"><del>STORM-1110</del></a> Fix Component Page for system components</p>

<ul class="alternate" type="square">
	<li>Remove redundant method `system-id?` - as is calls into static `Utils/isSystemId`</li>
	<li>All System components are of type bolts.</li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> storm1110</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/799.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #799</p>

<hr />
<p>commit 8281115371e852eb540246fd127b29d1da5e6f6a<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-10-14T18:45:20Z</p>

<p>    Remove redundent clojure method system-id</p>

<p>commit 88bfa5af12ec07c0fb4c2d4a66f1812fee004edf<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-10-14T18:46:32Z</p>

<p>    The system components are of type bolts</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799#issuecomment-149365765" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799#issuecomment-149365765</a></p>

<p>    Since there're so many random test failures for now, we may be OK to treat test is passed when more than one of two Travis build are success.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/799#issuecomment-149566508" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799#issuecomment-149566508</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/799" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/799</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil" class="user-hover" rel="kishorvpatil">Kishor Patil</a>,<br/>
I merged into master.</p>
