### ISSUE TITLE
[STORM-1129] Storm should use topology name instead of ids for url in storm UI.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4967]
<p>Currently, in storm UI details about a topology can be viewed at a URL which has a topology id as a query parameter. When a topology is updated and  redeployed a new id is assigned by storm and existing URL(and any bookmarks relying on it) for the topology do not work since the id has changed. We should change it so that topology name is used instead of id.</p>

---
<details><summary><i>Originally reported by <a title="Parag Shah" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pshah">pshah</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1129" target="_blank">Storm should use topology name instead of ids for url in storm UI.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Parag Shah" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pshah">pshah</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:14+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user priyank5485 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1129" title="Storm should use topology name instead of ids for url in storm UI." class="issue-link" data-issue-key="STORM-1129"><del>STORM-1129</del></a>: Use topology name instead of id in UI calls.</p>

<p>    Note that all-topologies-summary has been used to get topology id from a topology name. That involves a few calls to zookeeper which is not ideal. However, UI does not seem to take any significant performance hit. If needed we can handle it possibly using one of the options below. Since its a separate performance issue we can handle it in a separate JIRA.</p>

<p>    1. Have nimbus thrift server cache summary for topologies so it does not hit zookeeper every time we try to get topology id from name.<br/>
    2. Update nimbus thrift api with a method that takes options and use that to do only the minimal necessary interaction with zookeeper for a given option.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/priyank5485/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/priyank5485/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1129" title="Storm should use topology name instead of ids for url in storm UI." class="issue-link" data-issue-key="STORM-1129"><del>STORM-1129</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/854.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #854</p>

<hr />
<p>commit 77b73af52bdc2d691ae172a1a2905a94395c3c70<br/>
Author: Priyank <pshah@hortonworks.com><br/>
Date:   2015-11-04T00:20:50Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1129" title="Storm should use topology name instead of ids for url in storm UI." class="issue-link" data-issue-key="STORM-1129"><del>STORM-1129</del></a>: Use topology name instead of id in UI calls.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user jerrypeng commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153816194" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153816194</a></p>

<p>    Topology names are not unique.  Users can submit topologies with the same name, but the their auto generated topology ids will be unique.  I am not sure this is the right way to go about this</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153818643" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153818643</a></p>

<p>    @jerrypeng they can submit topologies with the same name, but not at the same time.  You can only have one "foo" topology running at any point in time.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user priyank5485 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153819160" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153819160</a></p>

<p>    @jerrypeng We have a check and it throws the following exception.</p>

<p>    Exception in thread "main" java.lang.RuntimeException: Topology with name `wordcount` already exists on cluster<br/>
    	at backtype.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:231)<br/>
    	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:275)<br/>
    	at backtype.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:311)<br/>
    	at backtype.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:292)<br/>
    	at storm.starter.WordCountTopology.main(WordCountTopology.java:94)</p>

<p>    @revans2 Thanks for chiming in.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153819804" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153819804</a></p>

<p>    @jerrypeng topology names are unique</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153836316" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153836316</a></p>

<p>    +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user jerrypeng commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153838740" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153838740</a></p>

<p>    thanks for the explanation and clarification everybody</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153854331" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153854331</a></p>

<p>    This is a non-backwards compatible change to the REST API and I really would prefer to maintain compatibility if at all possible.  It seems fairly simple to make the REST API work with the name or the id.  We call get-id-from-name all over the place, it seems fairly simple to check to see if there is a topology with that as the ID, if not check to see if there is a topology with it as the name. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#discussion_r43935706" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#discussion_r43935706</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/ui/core.clj &#8212;<br/>
    @@ -851,141 +859,151 @@<br/>
 (populate-context! servlet-request)<br/>
 (assert-authorized-user "getClusterInfo")<br/>
 (json-response (all-topologies-summary) (:callback m)))</p>
<ul class="alternate" type="square">
	<li>(GET "/api/v1/topology/:id" [:as {:keys <span class="error">&#91;cookies servlet-request scheme&#93;</span>} id & m]</li>
	<li>(populate-context! servlet-request)</li>
	<li>(assert-authorized-user "getTopology" (topology-config id))</li>
	<li>(let <span class="error">&#91;user (get-user-name servlet-request)&#93;</span></li>
	<li>(json-response (topology-page id (:window m) (check-include-sys? (:sys m)) user (= scheme :https)) (:callback m))))</li>
	<li>(GET "/api/v1/topology/:id/visualization-init" [:as {:keys <span class="error">&#91;cookies servlet-request&#93;</span>} id & m]</li>
	<li>(populate-context! servlet-request)</li>
	<li>(assert-authorized-user "getTopology" (topology-config id))</li>
	<li>(json-response (build-visualization id (:window m) (check-include-sys? (:sys m))) (:callback m)))</li>
	<li>(GET "/api/v1/topology/:id/visualization" [:as {:keys <span class="error">&#91;cookies servlet-request&#93;</span>} id & m]</li>
	<li>(populate-context! servlet-request)</li>
	<li>(assert-authorized-user "getTopology" (topology-config id))</li>
	<li>(json-response (mk-visualization-data id (:window m) (check-include-sys? (:sys m))) (:callback m)))</li>
	<li>(GET "/api/v1/topology/:id/component/:component" [:as {:keys <span class="error">&#91;cookies servlet-request scheme&#93;</span>} id component & m]</li>
	<li>(populate-context! servlet-request)</li>
	<li>(assert-authorized-user "getTopology" (topology-config id))</li>
	<li>(let <span class="error">&#91;user (get-user-name servlet-request)&#93;</span></li>
	<li>(json-response</li>
	<li>(component-page id component (:window m) (check-include-sys? (:sys m)) user (= scheme :https))</li>
	<li>(:callback m))))</li>
	<li>(GET "/api/v1/topology/:id/logconfig" [:as {:keys <span class="error">&#91;cookies servlet-request&#93;</span>} id & m]</li>
	<li>(populate-context! servlet-request)</li>
	<li>(assert-authorized-user "getTopology" (topology-config id))</li>
	<li>(json-response (log-config id) (:callback m)))</li>
	<li>(POST "/api/v1/topology/:id/activate" [:as {:keys <span class="error">&#91;cookies servlet-request&#93;</span>} id & m]</li>
	<li>(populate-context! servlet-request)</li>
	<li>(assert-authorized-user "activate" (topology-config id))</li>
	<li>(thrift/with-configured-nimbus-connection nimbus</li>
	<li>(let [tplg (->> (doto</li>
	<li>(GetInfoOptions.)</li>
	<li>(.set_num_err_choice NumErrorsChoice/NONE))</li>
	<li>(.getTopologyInfoWithOpts ^Nimbus$Client nimbus id))</li>
	<li>name (.get_name tplg)]</li>
	<li>(.activate nimbus name)</li>
	<li>(log-message "Activating topology '" name "'")))</li>
	<li>(json-response (topology-op-response id "activate") (m "callback")))</li>
	<li>(POST "/api/v1/topology/:id/deactivate" [:as {:keys <span class="error">&#91;cookies servlet-request&#93;</span>} id & m]</li>
	<li>(populate-context! servlet-request)</li>
	<li>(assert-authorized-user "deactivate" (topology-config id))</li>
	<li>(thrift/with-configured-nimbus-connection nimbus<br/>
    +  (GET "/api/v1/topology/:name" [:as {:keys <span class="error">&#91;cookies servlet-request scheme&#93;</span>} name & m]<br/>
    +    (let <span class="error">&#91;id (get-id-from-name name)&#93;</span><br/>
    +      (populate-context! servlet-request)
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    We have to populate the context before ever talking to nimbus.  `get-id-from-name` talks to nimbus and could potentially authenticate with the wrong user to nimbus.  This needs to be fixed everywhere.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#discussion_r43935881" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#discussion_r43935881</a></p>

<p>    &#8212; Diff: storm-core/src/ui/public/component.html &#8212;<br/>
    @@ -116,7 +116,7 @@</p>

<p>     var componentSummary = $("#component-summary");<br/>
     var componentActions = $("#component-actions");</p>
<ul class="alternate" type="square">
	<li>var buttonJsonData = componentActionJson(response<span class="error">&#91;"encodedTopologyId"&#93;</span>, response<span class="error">&#91;"encodedId"&#93;</span>, response<span class="error">&#91;"id"&#93;</span>,<br/>
    +var buttonJsonData = componentActionJson(response<span class="error">&#91;"name"&#93;</span>, response<span class="error">&#91;"encodedId"&#93;</span>, response<span class="error">&#91;"id"&#93;</span>,
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    We need to encode the name just like we conded the topologyId, or we have the possibility of an incorrect URL for odd characters in a topology name.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153855653" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153855653</a></p>

<p>    @priyank5485 for the most part this change looks good to me, but there are a few serious bugs/incompatibilities that need to be fixed before this can go in.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Parth-Brahmbhatt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-153864538" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-153864538</a></p>

<p>    I agree with @revans2 , lets maintain backward compatibility.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user priyank5485 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-154136188" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-154136188</a></p>

<p>    @revans2 @Parth-Brahmbhatt @jerrypeng @harshach  Thanks all for the feedback.  Other than the changes here there are some commits to apache/master after creation of this PR which added some more apis in UI using topology id making this PR unmergeable. I will  sort all of that out and update the PR.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-154151451" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-154151451</a></p>

<p>    @priyank5485 thanks for doing this.  I think it is going to make the UI much more usable.  Essentially giving us perma-links to a topology. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user wuchong commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-154403920" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-154403920</a></p>

<p>    +1 </p>

<p>    In Alibaba, we implement our monitor system using topology name instead of id. And it is very useful , as users often resubmit topology several times , and they do not need to find the new topology page link.</p>

<p>    But we should  maintain backward compatibility. maybe we can deal with  topology-id arg in function  `get-id-from-name`</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-195881422" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-195881422</a></p>

<p>    @priyank5485 sorry for the delay. can you please upmerge this patch and open up another PR for 1.x-branch as well.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user priyank5485 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1129" title="Storm should use topology name instead of ids for url in storm UI." class="issue-link" data-issue-key="STORM-1129"><del>STORM-1129</del></a>: Update ui to use topology name</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/priyank5485/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/priyank5485/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1129" title="Storm should use topology name instead of ids for url in storm UI." class="issue-link" data-issue-key="STORM-1129"><del>STORM-1129</del></a>-1.x</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1277</p>

<hr />
<p>commit 2648d74cad7d1e46ec9bcceb9b3b388cb98cfc8d<br/>
Author: Priyank <pshah@hortonworks.com><br/>
Date:   2016-03-29T05:31:08Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1129" title="Storm should use topology name instead of ids for url in storm UI." class="issue-link" data-issue-key="STORM-1129"><del>STORM-1129</del></a>: Update ui to use topology name</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user priyank5485 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/854#issuecomment-203246876" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/854#issuecomment-203246876</a></p>

<p>    @harshach @revans2 I have addressed the comments  and raised a PR <a href="https://github.com/apache/storm/pull/1277" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277</a> against the 1.x branch as I could not test my branch off of master due to another issue. Can you please review the PR against 1.x branch? I will port the same to master by updating this PR.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#issuecomment-203279789" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#issuecomment-203279789</a></p>

<p>    @priyank5485 I see that you have the changed the logviewer urls in the topology page to use topology name but there are no changes in logviewer.clj. I think logviewer links should just point to topology id since log links are anyway tied to a specific instance of topology run. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#discussion_r57843883" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#discussion_r57843883</a></p>

<p>    &#8212; Diff: storm-core/src/ui/public/component.html &#8212;<br/>
    @@ -176,7 +176,7 @@<br/>
       var loc = $(row<span class="error">&#91;3&#93;</span>)<span class="error">&#91;0&#93;</span>; // logviewer URL<br/>
       return '<input type="checkbox" class="workerActionCheckbox"'+<br/>
   'id="'<ins>checkboxId</ins>'" value="'<ins>host_port</ins>'"'<ins>checkedString</ins>'/> '+</p>
<ul class="alternate" type="square">
	<li>'<a href="'<ins>loc.protocol</ins>'//'<ins>loc.host</ins>'/dumps/'<ins>topologyId</ins>'/'+<br/>
    +      '<a href="'<ins>loc.protocol</ins>'//'<ins>loc.host</ins>'/dumps/'<ins>topologyName</ins>'/'+
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    should be left as it is. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user priyank5485 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#issuecomment-203557013" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#issuecomment-203557013</a></p>

<p>    @abhishekagarwal87 Thanks for the catch. I have updated the PR. Can you please review?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#discussion_r57948138" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#discussion_r57948138</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/ui/core.clj &#8212;<br/>
    @@ -466,6 +466,21 @@<br/>
    "assignedCpu" (.get_assigned_cpu t)})<br/>
 "schedulerDisplayResource" (<b>STORM-CONF</b> Config/SCHEDULER_DISPLAY_RESOURCE)}))</p>

<p>    +(defn get-topology-id <span class="error">&#91;topology-name-or-id&#93;</span><br/>
    +  (let [summary ((all-topologies-summary) "topologies")<br/>
    +filter-fun-name (fn<span class="error">&#91;topo-summary&#93;</span> (= (topo-summary "name") topology-name-or-id))<br/>
    +filter-fun-id (fn<span class="error">&#91;topo-summary&#93;</span> (= (topo-summary "id") topology-name-or-id))<br/>
    +matching-topologies-by-name (filter filter-fun-name summary)<br/>
    +matching-topologies-by-id (filter filter-fun-id summary)<br/>
    +matching-topologies<br/>
    +(cond<br/>
    +  (not-empty matching-topologies-by-name) matching-topologies-by-name<br/>
    +  (not-empty matching-topologies-by-id) matching-topologies-by-id<br/>
    +  :else nil)<br/>
    +_ (when (empty? matching-topologies) (throw (NotAliveException. (str topology-name-or-id " is not alive"))))<br/>
    +id ((first matching-topologies) "id")]<br/>
    +    id))<br/>
    &#8212; End diff &#8211;</p>

<p>    We should probably prioritize matching ids here instead of matching names. As it is now, If I give my topology a name that matches another topology's id, the topology whose id I stole will become inaccessible. Since we're prioritizing names, it will match that topology's id to my topology's name, and display my topology instead.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user priyank5485 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#discussion_r57950485" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#discussion_r57950485</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/ui/core.clj &#8212;<br/>
    @@ -466,6 +466,21 @@<br/>
    "assignedCpu" (.get_assigned_cpu t)})<br/>
 "schedulerDisplayResource" (<b>STORM-CONF</b> Config/SCHEDULER_DISPLAY_RESOURCE)}))</p>

<p>    +(defn get-topology-id <span class="error">&#91;topology-name-or-id&#93;</span><br/>
    +  (let [summary ((all-topologies-summary) "topologies")<br/>
    +filter-fun-name (fn<span class="error">&#91;topo-summary&#93;</span> (= (topo-summary "name") topology-name-or-id))<br/>
    +filter-fun-id (fn<span class="error">&#91;topo-summary&#93;</span> (= (topo-summary "id") topology-name-or-id))<br/>
    +matching-topologies-by-name (filter filter-fun-name summary)<br/>
    +matching-topologies-by-id (filter filter-fun-id summary)<br/>
    +matching-topologies<br/>
    +(cond<br/>
    +  (not-empty matching-topologies-by-name) matching-topologies-by-name<br/>
    +  (not-empty matching-topologies-by-id) matching-topologies-by-id<br/>
    +  :else nil)<br/>
    +_ (when (empty? matching-topologies) (throw (NotAliveException. (str topology-name-or-id " is not alive"))))<br/>
    +id ((first matching-topologies) "id")]<br/>
    +    id))<br/>
    &#8212; End diff &#8211;</p>

<p>    @knusbaum Thats true. But if we prioritize ids would not your topology become inaccessible? I think going forward we should use topology names in ui and elsewhere so that we can have permanent links and since thats the identifier given by the user. Support for lookup with ids was added for backwards compatibility as suggested by @revans2 and others.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#discussion_r57951884" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#discussion_r57951884</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/ui/core.clj &#8212;<br/>
    @@ -466,6 +466,21 @@<br/>
    "assignedCpu" (.get_assigned_cpu t)})<br/>
 "schedulerDisplayResource" (<b>STORM-CONF</b> Config/SCHEDULER_DISPLAY_RESOURCE)}))</p>

<p>    +(defn get-topology-id <span class="error">&#91;topology-name-or-id&#93;</span><br/>
    +  (let [summary ((all-topologies-summary) "topologies")<br/>
    +filter-fun-name (fn<span class="error">&#91;topo-summary&#93;</span> (= (topo-summary "name") topology-name-or-id))<br/>
    +filter-fun-id (fn<span class="error">&#91;topo-summary&#93;</span> (= (topo-summary "id") topology-name-or-id))<br/>
    +matching-topologies-by-name (filter filter-fun-name summary)<br/>
    +matching-topologies-by-id (filter filter-fun-id summary)<br/>
    +matching-topologies<br/>
    +(cond<br/>
    +  (not-empty matching-topologies-by-name) matching-topologies-by-name<br/>
    +  (not-empty matching-topologies-by-id) matching-topologies-by-id<br/>
    +  :else nil)<br/>
    +_ (when (empty? matching-topologies) (throw (NotAliveException. (str topology-name-or-id " is not alive"))))<br/>
    +id ((first matching-topologies) "id")]<br/>
    +    id))<br/>
    &#8212; End diff &#8211;</p>

<p>    That's fine with me. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#issuecomment-203743167" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#issuecomment-203743167</a></p>

<p>    Thanks @priyank5485 - Though I am still not sure how logviewer links will work. topologyId variable is not assigned any value. Original code -<br/>
    <a href="https://github.com/apache/storm/blob/master/storm-core/src/ui/public/component.html#L136" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/ui/public/component.html#L136</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user priyank5485 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#issuecomment-203751947" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#issuecomment-203751947</a></p>

<p>    @abhishekagarwal87 Please look at the $.getJson method. Line 190 in component.html. Now, instead of topologyId being assigned on onReady i do it in $.getJson. Its a side effect of squashing commits that makes it hard to look at the commits that addressed review comments. Sorry about that. Do you guys usually keep separate commits and squash in the end? I will do that next time.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277#issuecomment-203756449" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277#issuecomment-203756449</a></p>

<p>    I think either way is fine. My only concern was logviewer links which I think you have addressed. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1277" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1277</a></p>

<p>    @priyank5485 sorry for the delay on this. Can you up merge this patch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
