### ISSUE TITLE
[STORM-1170] Consistent Unit Test failure in Travis in backtype.storm.utils.DisruptorQueueTest

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5008]
<p>testInOrder(backtype.storm.utils.DisruptorQueueTest)  Time elapsed: 2.141 sec  <<< FAILURE!<br/>
junit.framework.AssertionFailedError: producer 0 is still alive<br/>
	at junit.framework.Assert.fail(Assert.java:57)<br/>
	at junit.framework.Assert.assertTrue(Assert.java:22)<br/>
	at junit.framework.Assert.assertFalse(Assert.java:39)<br/>
	at junit.framework.TestCase.assertFalse(TestCase.java:210)<br/>
	at backtype.storm.utils.DisruptorQueueTest.run(DisruptorQueueTest.java:112)<br/>
	at backtype.storm.utils.DisruptorQueueTest.testInOrder(DisruptorQueueTest.java:83)</p>

---
<details><summary><i>Originally reported by <a title="Boyang Jerry Peng" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jerrypeng">jerrypeng</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1170" target="_blank">Consistent Unit Test failure in Travis in backtype.storm.utils.DisruptorQueueTest</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Zhuo Liu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-05T20:55:19+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>I also met the same problem in CI. I think that is because the producer sometimes cannot finish publishing 1M tuples before TIMEOUT(1000ms). The root cause is that the producer.interrupt() can set the interrupted flag to be true but not really terminate the producer thread. As there is no blocking functions (sleep, wait, join) inside producer's run function, so no InterruptedException will be thrown.</p>

<p>We can solve the issue by checking the interrupted flag inside producer's run function. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/859#issuecomment-153856336" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/859#issuecomment-153856336</a></p>

<p>    Looks good to me +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user jerrypeng commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/859#issuecomment-154126288" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/859#issuecomment-154126288</a></p>

<p>    +1 @zhuoliu  thanks for fixing this</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/859" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/859</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu" class="user-hover" rel="zhuoliu">Zhuo Liu</a>,</p>

<p>I merged this into master</p>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1183">STORM-1183</a>]</i>
