### ISSUE TITLE
[STORM-1189] client.getClusterInfo() fails with Required field 'nimbus_uptime_secs' is unset!

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5027]
<p>Hi,</p>

<p>we are about to upgrade our cluster from 0.9.1-incubating to 0.10.0. I'm currently testing whether the functionality is still working with 0.10.0 in VMs.</p>

<p>On 0.10.0 the following throws the exception mentioned below:<br/>
...<br/>
NimbusClient nimbusClient = NimbusClient.getConfiguredClient(readConfig);<br/>
Client client = nimbusClient.getClient();<br/>
ClusterSummary clusterInfo = client.getClusterInfo();</p>

<p>Exception:<br/>
org.apache.thrift7.protocol.TProtocolException: Required field 'nimbus_uptime_secs' is unset! Struct:ClusterSummary(supervisors:<span class="error">&#91;SupervisorSummary(host:n3.t3k.siemens.com, uptime_secs:24297, num_workers:4, num_used_workers:0, supervisor_id:4a87f03b-ea91-4b12-8cb9-9f7e26703b26, version:0.10.0.2.3.0.0-2557)&#93;</span>, nimbus_uptime_secs:0, topologies:[])<br/>
	at backtype.storm.generated.ClusterSummary.validate(ClusterSummary.java:515)<br/>
	at backtype.storm.generated.ClusterSummary$ClusterSummaryStandardScheme.read(ClusterSummary.java:613)<br/>
	at backtype.storm.generated.ClusterSummary$ClusterSummaryStandardScheme.read(ClusterSummary.java:549)<br/>
	at backtype.storm.generated.ClusterSummary.read(ClusterSummary.java:473)<br/>
	at backtype.storm.generated.Nimbus$getClusterInfo_result$getClusterInfo_resultStandardScheme.read(Nimbus.java:16546)<br/>
	at backtype.storm.generated.Nimbus$getClusterInfo_result$getClusterInfo_resultStandardScheme.read(Nimbus.java:16531)<br/>
	at backtype.storm.generated.Nimbus$getClusterInfo_result.read(Nimbus.java:16470)<br/>
	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78)<br/>
	at backtype.storm.generated.Nimbus$Client.recv_getClusterInfo(Nimbus.java:569)<br/>
	at backtype.storm.generated.Nimbus$Client.getClusterInfo(Nimbus.java:557)</p>

<p>Switching back to 0.9.1-incubating showed, that the code still works fine there.</p>

<p>BR Michael</p>

---
<details><summary><i>Originally reported by <a title="Michael Sonst" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msonst">msonst</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1189" target="_blank">client.getClusterInfo() fails with Required field 'nimbus_uptime_secs' is unset!</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-10T15:05:30+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>Hi Michael, are you doing a rolling-upgrade from 0.9 to 0.10?<br/>
It seems that the field "nimbus_uptime_secs" only exists in 0.9.x for ClusterSummary; in 0.11.0, this field no longer exists because we introduce multiple nimbuses in HA. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msonst">msonst</a>:</i>
<p>Hi Zhuo</p>

<p>thanks for your reply.</p>

<p>The Cluster installation is a fresh installation in VMs of Hortonworks 2.3 (Storm 0.10.0) as we wanted to test in a virtual environment before upgrading the production cluster.<br/>
The client code is a fresh compile with upgrading storm-core 0.10.0 via gradle.</p>

<p>Even when the field is not used anymore by the server, it seems that it is still validiated in ClusterSummary:<br/>
public void validate()<br/>
   if (!is_set_nimbus_uptime_secs()) </p>
{
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'nimbus_uptime_secs' is unset! Struct:" + toString());
    }

<p>The class seems to be autogenerated. Could it be that the autogeneration was not performed for this class before releasing 0.10.0? The date in the header looks outdated:<br/>
@SuppressWarnings(</p>
{"cast", "rawtypes", "serial", "unchecked"}
<p>)<br/>
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-2-6")<br/>
public class ClusterSummary implements ...</p>


<p>BR Michael</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>Sorry for the confusion. Both 0.9 and 0.10 still has the field, 0.11 does not. <br/>
Not sure why clusterSummary.setFieldValue is not called for nimbus_uptime_secs to set its field bit to be true.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msonst">msonst</a>:</i>
<p>Hi,</p>

<p>In which class is it supposed to be set? Can we probably turn on logging<br/>
there?</p>

<p>Br Michael</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>There is either a bug in thrift or you have a client server mismatch.  Nimbus will validate the object before serializing it out using essentially the same code that is being used to validate the object after deserializing.  The reason I use essentially is because if we have a mismatch in the versions of storm on the client and server the validation logic will be different.</p>

<p>Hortonworks 2.3 has storm 0.10.0 but it also has HA merged into it, so it is closer to 0.11.x for this. </p>

<p>I really don't like the idea of fully removing a required field.  It make doing a rolling upgrade impossible.  I would very much prefer to deprecate it, and either always set it to 0, or set it to the lowest uptime of all nimbuses.  I'll see if I can through together a patch for that quickly.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user revans2 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1189" title="client.getClusterInfo() fails with Required field &#39;nimbus_uptime_secs&#39; is unset!" class="issue-link" data-issue-key="STORM-1189"><del>STORM-1189</del></a>: Maintain wire compatability with 0.10.x versions of storm.</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/revans2/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/revans2/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1189" title="client.getClusterInfo() fails with Required field &#39;nimbus_uptime_secs&#39; is unset!" class="issue-link" data-issue-key="STORM-1189"><del>STORM-1189</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/868.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #868</p>

<hr />
<p>commit 5c818b093350f572a38a5c59f9e083625b298ddd<br/>
Author: Robert (Bobby) Evans <evans@yahoo-inc.com><br/>
Date:   2015-11-09T14:44:36Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1189" title="client.getClusterInfo() fails with Required field &#39;nimbus_uptime_secs&#39; is unset!" class="issue-link" data-issue-key="STORM-1189"><del>STORM-1189</del></a>: Maintain wire compatability with 0.10.x versions of storm.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I just put up a pull request that should fix the issue with storm.  If Hortonworks wants it they are going to have to cherry-pick it back themselves.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868#issuecomment-155084311" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868#issuecomment-155084311</a></p>

<p>    I have not tested this manually between a 0.10.x client and a 0.11.x server, but I do plan to.</p>

<p>    Note that this only maintains wire compatibility, not API compatibility.  The constructor for ClusterSummary is not the same, as required parameters have been removed.  I don't see this as critical because only internal storm code should ever be creating instances of this class, but it is an incompatibility with 0.10.x.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868#issuecomment-155093325" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868#issuecomment-155093325</a></p>

<p>    LGTM. +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user zhuoliu commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868#issuecomment-155099830" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868#issuecomment-155099830</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868#issuecomment-155104869" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868#issuecomment-155104869</a></p>

<p>    I just ran the test and I was able to use a 0.10.1 UI against a nimbus instance running using this patch.</p>

<p>    I did find that ShellBolt is not backwards compatible.  I will file a JIRA around that.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868#issuecomment-155222663" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868#issuecomment-155222663</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/868" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I merged the fix into master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user spicoflorin commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868#issuecomment-159317100" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868#issuecomment-159317100</a></p>

<p>    Hello!<br/>
     I have downloaded the version 0.10.0 and applied the patch from  <a href="https://patch-diff.githubusercontent.com/raw/apache/storm/pull/868.patch" class="external-link" target="_blank" rel="nofollow noopener">https://patch-diff.githubusercontent.com/raw/apache/storm/pull/868.patch</a>, but I got compilation errors. I would like to use the 0.10.0 storm version. Can you please test again? Or what code version should I use : the one from tags (0.10.0) or the one from the branch 0.10.x master?<br/>
     ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project storm-core: Compilation failure: Compilation failure:<br/>
    ERROR] /d:/Temp/stom-10/storm-0.10.0/storm-core/src/jvm/backtype/storm/generated/ClusterSummary.java:<span class="error">&#91;321,5&#93;</span> duplicate case label<br/>
    ERROR] /d:/Temp/stom-10/storm-0.10.0/storm-core/src/jvm/backtype/storm/generated/ClusterSummary.java:<span class="error">&#91;403,13&#93;</span> variable this_present_nimbus_uptime_secs is already defined in method equals(backtype.storm.generated.ClusterSummary)<br/>
    ERROR] /d:/Temp/stom-10/storm-0.10.0/storm-core/src/jvm/backtype/storm/generated/ClusterSummary.java:<span class="error">&#91;404,13&#93;</span> variable that_present_nimbus_uptime_secs is already defined in method equals(backtype.storm.generated.ClusterSummary)<br/>
    ERROR] /d:/Temp/stom-10/storm-0.10.0/storm-core/src/jvm/backtype/storm/generated/ClusterSummary.java:<span class="error">&#91;617,11&#93;</span> duplicate case label<br/>
    ERROR] -> <span class="error">&#91;Help 1&#93;</span></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user YuChem commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868#issuecomment-169778882" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868#issuecomment-169778882</a></p>

<p>    @spicoflorin: I have encountered the same issue. Did you get it resolved? Would you mind get some tips on how to workaround?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user spicoflorin commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/868#issuecomment-178437230" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/868#issuecomment-178437230</a></p>

<p>    Hi!<br/>
      I didn't solve it. </p>
