### ISSUE TITLE
[STORM-1194] java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.Log4jLoggerFactory

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5032]
<p>can not consume topic from Kafka using storm-kafka, failed with </p>

<p>java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.Log4jLoggerFactory<br/>
	at org.apache.log4j.Logger.getLogger(Logger.java:39) ~<span class="error">&#91;log4j-over-slf4j-1.6.6.jar:1.6.6&#93;</span><br/>
	at kafka.utils.Logging$class.logger(Logging.scala:24) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.network.BlockingChannel.logger$lzycompute(BlockingChannel.scala:35) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.network.BlockingChannel.logger(BlockingChannel.scala:35) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.utils.Logging$class.debug(Logging.scala:51) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.network.BlockingChannel.debug(BlockingChannel.scala:35) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.network.BlockingChannel.connect(BlockingChannel.scala:64) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.consumer.SimpleConsumer.connect(SimpleConsumer.scala:44) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.consumer.SimpleConsumer.getOrMakeConnection(SimpleConsumer.scala:142) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:69) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:124) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.javaapi.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:79) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:77) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:67) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.PartitionManager.<init>(PartitionManager.java:83) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:98) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:69) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:135) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at backtype.storm.daemon.executor$fn_<em>3371$fn</em><em>3386$fn</em>_3415.invoke(executor.clj:565) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
	at backtype.storm.util$async_loop$fn__460.invoke(util.clj:463) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_80&#93;</span><br/>
67167 <span class="error">&#91;Thread-20-spout&#93;</span> ERROR backtype.storm.daemon.executor - <br/>
java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.Log4jLoggerFactory<br/>
	at org.apache.log4j.Logger.getLogger(Logger.java:39) ~<span class="error">&#91;log4j-over-slf4j-1.6.6.jar:1.6.6&#93;</span><br/>
	at kafka.utils.Logging$class.logger(Logging.scala:24) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.network.BlockingChannel.logger$lzycompute(BlockingChannel.scala:35) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.network.BlockingChannel.logger(BlockingChannel.scala:35) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.utils.Logging$class.debug(Logging.scala:51) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.network.BlockingChannel.debug(BlockingChannel.scala:35) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.network.BlockingChannel.connect(BlockingChannel.scala:64) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.consumer.SimpleConsumer.connect(SimpleConsumer.scala:44) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.consumer.SimpleConsumer.getOrMakeConnection(SimpleConsumer.scala:142) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:69) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:124) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at kafka.javaapi.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:79) ~<span class="error">&#91;kafka_2.10-0.8.1.1.jar:na&#93;</span><br/>
	at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:77) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:67) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.PartitionManager.<init>(PartitionManager.java:83) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:98) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:69) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:135) ~<span class="error">&#91;storm-kafka-0.9.5.jar:0.9.5&#93;</span><br/>
	at backtype.storm.daemon.executor$fn_<em>3371$fn</em><em>3386$fn</em>_3415.invoke(executor.clj:565) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
	at backtype.storm.util$async_loop$fn__460.invoke(util.clj:463) ~<span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_80&#93;</span><br/>
67235 <span class="error">&#91;Thread-20-spout&#93;</span> ERROR backtype.storm.util - Halting process: ("Worker died")<br/>
java.lang.RuntimeException: ("Worker died")<br/>
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at backtype.storm.daemon.worker$fn_<em>4694$fn</em>_4695.invoke(worker.clj:493) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
	at backtype.storm.daemon.executor$mk_executor_data$fn_<em>3272$fn</em>_3273.invoke(executor.clj:240) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
	at backtype.storm.util$async_loop$fn__460.invoke(util.clj:473) <span class="error">&#91;storm-core-0.9.5.jar:0.9.5&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;na:1.7.0_80&#93;</span></p>

<p>Here's the pom.xml</p>

<p>ack=true</test.extra.args></p>

<p>    <br/>
    <clojure.version>1.5.1</clojure.version><br/>
    <compojure.version>1.1.3</compojure.version><br/>
    <hiccup.version>0.3.6</hiccup.version><br/>
    <commons-io.version>2.4</commons-io.version><br/>
    <commons-lang.version>2.5</commons-lang.version><br/>
    <commons-exec.version>1.1</commons-exec.version><br/>
    <curator.version>2.5.0</curator.version><br/>
    <json-simple.version>1.1</json-simple.version><br/>
    <ring.version>0.3.11</ring.version><br/>
    <clojure.tools.logging.version>0.2.3</clojure.tools.logging.version><br/>
    <clojure.math.numeric-tower.version>0.0.1</clojure.math.numeric-tower.version><br/>
    <carbonite.version>1.4.0</carbonite.version><br/>
    <httpclient.version>4.3.3</httpclient.version><br/>
    <clojure.tools.cli.version>0.2.4</clojure.tools.cli.version><br/>
    <disruptor.version>2.10.1</disruptor.version><br/>
    <jgrapht.version>0.9.0</jgrapht.version><br/>
    <guava.version>16.0.1</guava.version><br/>
    <logback-classic.version>1.0.13</logback-classic.version><br/>
    <mockito.version>1.9.5</mockito.version><br/>
    <storm-core.version>0.9.5</storm-core.version><br/>
    <storm-kafka.version>0.9.5</storm-kafka.version><br/>
    <snakeyaml.version>1.16</snakeyaml.version><br/>
    <storm.crawler.core.version>0.7</storm.crawler.core.version></p>

<p>  </properties></p>

<p>  <build><br/>
    <sourceDirectory>src/jvm</sourceDirectory><br/>
    <testSourceDirectory>test/jvm</testSourceDirectory><br/>
    <resources><br/>
      <resource><br/>
<directory>${basedir}/multilang</directory><br/>
      </resource><br/>
    </resources></p>

<p>    <plugins></p>

<p>      <plugin><br/>
<groupId>org.apache.maven.plugins</groupId><br/>
<artifactId>maven-compiler-plugin</artifactId><br/>
      </plugin></p>

<p>      <br/>
      <plugin><br/>
<artifactId>maven-assembly-plugin</artifactId><br/>
<configuration><br/>
  <descriptorRefs><br/>
    <descriptorRef>jar-with-dependencies</descriptorRef><br/>
  </descriptorRefs><br/>
  <archive><br/>
    <manifest><br/>
      <mainClass /><br/>
    </manifest><br/>
  </archive><br/>
</configuration><br/>
<executions><br/>
  <execution><br/>
    <id>make-assembly</id><br/>
    <phase>package</phase><br/>
    <goals><br/>
      <goal>single</goal><br/>
    </goals><br/>
  </execution><br/>
</executions><br/>
      </plugin></p>

<p>      <plugin><br/>
<groupId>org.codehaus.mojo</groupId><br/>
<artifactId>exec-maven-plugin</artifactId><br/>
<version>1.3.2</version><br/>
<executions><br/>
  <execution><br/>
    <goals><br/>
      <goal>exec</goal><br/>
    </goals><br/>
  </execution><br/>
</executions><br/>
<configuration><br/>
  <executable>java</executable><br/>
  <includeProjectDependencies>true</includeProjectDependencies><br/>
  <includePluginDependencies>false</includePluginDependencies><br/>
  <classpathScope>compile</classpathScope><br/>
  <killAfter>-1</killAfter><br/>
  <mainClass>${storm.topology}</mainClass><br/>
</configuration><br/>
      </plugin><br/>
    </plugins><br/>
  </build></p>

<p>  <dependencies><br/>
    <dependency><br/>
      <groupId>junit</groupId><br/>
      <artifactId>junit</artifactId><br/>
      <version>3.8.1</version><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.testng</groupId><br/>
      <artifactId>testng</artifactId><br/>
      <version>6.8.5</version><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.mockito</groupId><br/>
      <artifactId>mockito-all</artifactId><br/>
      <version>${mockito.version}</version><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.easytesting</groupId><br/>
      <artifactId>fest-assert-core</artifactId><br/>
      <version>2.0M8</version><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.jmock</groupId><br/>
      <artifactId>jmock</artifactId><br/>
      <version>2.6.0</version><br/>
      <scope>test</scope><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.twitter4j</groupId><br/>
      <artifactId>twitter4j-stream</artifactId><br/>
      <version>3.0.3</version><br/>
    </dependency></p>

<p>    <dependency><br/>
      <groupId>org.apache.kafka</groupId><br/>
      <artifactId>kafka_2.10</artifactId><br/>
      <version>0.8.1.1</version><br/>
      <exclusions><br/>
<exclusion><br/>
  <groupId>org.apache.zookeeper</groupId><br/>
  <artifactId>zookeeper</artifactId><br/>
</exclusion><br/>
<exclusion><br/>
  <groupId>log4j</groupId><br/>
  <artifactId>log4j</artifactId><br/>
</exclusion><br/>
      </exclusions><br/>
    </dependency></p>

<p>    <dependency><br/>
      <groupId>org.apache.storm</groupId><br/>
      <artifactId>storm-core</artifactId><br/>
      <version>${storm-core.version}</version><br/>
      <scope>provided</scope><br/>
    </dependency></p>

<p>    <dependency><br/>
      <groupId>org.apache.storm</groupId><br/>
      <artifactId>storm-kafka</artifactId><br/>
      <version>${storm-kafka.version}</version><br/>
      <exclusions><br/>
<exclusion><br/>
  <groupId>org.apache.zookeeper</groupId><br/>
  <artifactId>zookeeper</artifactId><br/>
</exclusion></p>

<p><exclusion><br/>
  <groupId>org.slf4j</groupId><br/>
  <artifactId>slf4j-simple</artifactId><br/>
</exclusion></p>

<p><exclusion><br/>
  <groupId>org.slf4j</groupId><br/>
  <artifactId>slf4j-sl4j12</artifactId><br/>
</exclusion></p>

<p>      </exclusions><br/>
    </dependency></p>

<p>    <dependency><br/>
      <groupId>org.apache.zookeeper</groupId><br/>
      <artifactId>zookeeper</artifactId><br/>
      <version>3.4.6</version><br/>
      <exclusions><br/>
<exclusion><br/>
  <groupId>com.sun.jmx</groupId><br/>
  <artifactId>jmxri</artifactId><br/>
</exclusion></p>

<p><exclusion><br/>
  <groupId>com.sun.jdmk</groupId><br/>
  <artifactId>jmxtools</artifactId><br/>
</exclusion></p>

<p><exclusion><br/>
  <groupId>javax.jms</groupId><br/>
  <artifactId>jms</artifactId><br/>
</exclusion></p>

<p>      </exclusions><br/>
    </dependency></p>

<p>    <dependency><br/>
      <groupId>commons-collections</groupId><br/>
      <artifactId>commons-collections</artifactId><br/>
      <version>3.2.1</version><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>com.google.guava</groupId><br/>
      <artifactId>guava</artifactId><br/>
      <version>${guava.version}</version><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>org.yaml</groupId><br/>
      <artifactId>snakeyaml</artifactId><br/>
      <version>${snakeyaml.version}</version><br/>
    </dependency><br/>
    <dependency><br/>
      <groupId>com.digitalpebble</groupId><br/>
      <artifactId>storm-crawler-core</artifactId><br/>
      <version>${storm.crawler.core.version}</version><br/>
    </dependency></p>

<p>    <dependency><br/>
      <groupId>com.netflix.curator</groupId><br/>
      <artifactId>curator-test</artifactId><br/>
      <version>1.2.5</version></p>

<p>      <exclusions><br/>
<exclusion><br/>
  <groupId>org.slf4j</groupId><br/>
  <artifactId>slf4j-log4j12</artifactId><br/>
</exclusion><br/>
<exclusion><br/>
  <groupId>log4j</groupId><br/>
  <artifactId>log4j</artifactId><br/>
</exclusion><br/>
      </exclusions><br/>
    </dependency></p>

<p>  </dependencies></p>

---
<details><summary><i>Originally reported by <a title="Yitao Jiang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jiangytcn">jiangytcn</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1194" target="_blank">java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.Log4jLoggerFactory</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:40+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
