### ISSUE TITLE
[STORM-1195] Doesn't start storm nimbus

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5033]
<p>After start nimbus it crashed </p>

<p>2015-11-10 11:06:03.431 o.a.s.s.o.a.c.f.s.ConnectionStateManager <span class="error">&#91;INFO&#93;</span> State change: CONNECTED<br/>
2015-11-10 11:06:03.472 b.s.d.nimbus <span class="error">&#91;ERROR&#93;</span> Error on initialization of server service-handler<br/>
java.lang.RuntimeException: java.lang.RuntimeException: java.util.zip.ZipException: Not in GZIP format<br/>
<------>at backtype.storm.serialization.GzipThriftSerializationDelegate.deserialize(GzipThriftSerializationDelegate.java:54) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.utils.Utils.deserialize(Utils.java:80) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.cluster$maybe_deserialize.invoke(cluster.clj:246) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.cluster$mk_storm_cluster_state$reify__5120.storm_base(cluster.clj:426) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~<span class="error">&#91;?:1.7.0_55&#93;</span><br/>
<------>at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~<span class="error">&#91;?:1.7.0_55&#93;</span><br/>
<------>at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~<span class="error">&#91;?:1.7.0_55&#93;</span><br/>
<------>at java.lang.reflect.Method.invoke(Method.java:606) ~<span class="error">&#91;?:1.7.0_55&#93;</span><br/>
<------>at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$transition_BANG_.invoke(nimbus.clj:205) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$transition_BANG_.invoke(nimbus.clj:200) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$fn_<em>6583$exec_fn</em><em>1236</em><em>auto</em>___6584.invoke(nimbus.clj:1018) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at clojure.lang.AFn.applyToHelper(AFn.java:156) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at clojure.lang.AFn.applyTo(AFn.java:144) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at clojure.core$apply.invoke(core.clj:624) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$fn_<em>6583$service_handler</em>_6703.doInvoke(nimbus.clj:1010) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at clojure.lang.RestFn.invoke(RestFn.java:421) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1368) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1399) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$_main.invoke(nimbus.clj:1422) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at clojure.lang.AFn.applyToHelper(AFn.java:152) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at clojure.lang.AFn.applyTo(AFn.java:144) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus.main(Unknown Source) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: Not in GZIP format<br/>
<------>at backtype.storm.utils.Utils.gunzip(Utils.java:135) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.serialization.GzipThriftSerializationDelegate.deserialize(GzipThriftSerializationDelegate.java:51) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>... 23 more<br/>
Caused by: java.util.zip.ZipException: Not in GZIP format<br/>
<------>at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~<span class="error">&#91;?:1.7.0_55&#93;</span><br/>
<------>at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78) ~<span class="error">&#91;?:1.7.0_55&#93;</span><br/>
<------>at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90) ~<span class="error">&#91;?:1.7.0_55&#93;</span><br/>
<------>at backtype.storm.utils.Utils.gunzip(Utils.java:125) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.serialization.GzipThriftSerializationDelegate.deserialize(GzipThriftSerializationDelegate.java:51) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>... 23 more<br/>
2015-11-10 11:09:59.655 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error on initialization")<br/>
java.lang.RuntimeException: ("Error on initialization")<br/>
<------>at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:336) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$fn_<em>6583$service_handler</em>_6703.doInvoke(nimbus.clj:1010) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at clojure.lang.RestFn.invoke(RestFn.java:421) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1368) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1399) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus$_main.invoke(nimbus.clj:1422) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
<------>at clojure.lang.AFn.applyToHelper(AFn.java:152) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at clojure.lang.AFn.applyTo(AFn.java:144) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
<------>at backtype.storm.daemon.nimbus.main(Unknown Source) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Vedetskey Dmytro" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Hellion">Hellion</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1195" target="_blank">Doesn't start storm nimbus</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2015-11-10T14:07:32+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>The upgrade to 0.10.x is not a rolling upgrade.  The format of the state in zookeeper and elsewhere was changed to be thrift serialized.  You need to wipe out the state on nimbus and each of the workers as part of the install/upgrade process.  This is to allow us to make almost all upgrades in the future rolling upgrades.</p>

<p>If you are still having issues after clearing out the contents of storm-local please feel free to ask on the users or dev mailing lists.  If you feel it is a bug in storm feel free to reopen this JIRA</p>
