### ISSUE TITLE
[STORM-1208] UI: NPE seen when aggregating bolt streams stats

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5046]
<p>A stack trace is seen on the UI via its thrift connection to nimbus.</p>

<p>On nimbus, a stack trace similar to the following is seen:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2015-11-09 19:26:48.921 o.a.t.s.TThreadPoolServer [ERROR] Error occurred during processing of message.
java.lang.NullPointerException
at backtype.storm.stats$agg_bolt_streams_lat_and_count$iter__2219__2223$fn__2224.invoke(stats.clj:346) ~[storm-core-0.10.1.jar:0.10.1]
at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.6.0.jar:?]
at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.6.0.jar:?]
at clojure.lang.RT.seq(RT.java:484) ~[clojure-1.6.0.jar:?]
at clojure.core$seq.invoke(core.clj:133) ~[clojure-1.6.0.jar:?]
at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~[clojure-1.6.0.jar:?]
at clojure.core.protocols$fn__6078.invoke(protocols.clj:54) ~[clojure-1.6.0.jar:?]
at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13) ~[clojure-1.6.0.jar:?]
at clojure.core$reduce.invoke(core.clj:6289) ~[clojure-1.6.0.jar:?]
at clojure.core$into.invoke(core.clj:6341) ~[clojure-1.6.0.jar:?]
at backtype.storm.stats$agg_bolt_streams_lat_and_count.invoke(stats.clj:344) ~[storm-core-0.10.1.jar:0.10.1]
at backtype.storm.stats$agg_pre_merge_comp_page_bolt.invoke(stats.clj:439) ~[storm-core-0.10.1.jar:0.10.1]
at backtype.storm.stats$fn__2578.invoke(stats.clj:1093) ~[storm-core-0.10.1.jar:0.10.1]
at clojure.lang.MultiFn.invoke(MultiFn.java:241) ~[clojure-1.6.0.jar:?]
at clojure.lang.AFn.applyToHelper(AFn.java:165) ~[clojure-1.6.0.jar:?]
at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.6.0.jar:?]
at clojure.core$apply.invoke(core.clj:628) ~[clojure-1.6.0.jar:?]
at clojure.core$partial$fn__4230.doInvoke(core.clj:2470) ~[clojure-1.6.0.jar:?]
at clojure.lang.RestFn.invoke(RestFn.java:421) ~[clojure-1.6.0.jar:?]
at clojure.core.protocols$fn__6086.invoke(protocols.clj:143) ~[clojure-1.6.0.jar:?]
at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19) ~[clojure-1.6.0.jar:?]
at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31) ~[clojure-1.6.0.jar:?]
at clojure.core.protocols$fn__6078.invoke(protocols.clj:54) ~[clojure-1.6.0.jar:?]
at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13) ~[clojure-1.6.0.jar:?]
at clojure.core$reduce.invoke(core.clj:6289) ~[clojure-1.6.0.jar:?]
at backtype.storm.stats$aggregate_comp_stats_STAR_.invoke(stats.clj:1106) ~[storm-core-0.10.1.jar:0.10.1]
at clojure.lang.AFn.applyToHelper(AFn.java:165) ~[clojure-1.6.0.jar:?]
at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.6.0.jar:?]
at clojure.core$apply.invoke(core.clj:624) ~[clojure-1.6.0.jar:?]
at backtype.storm.stats$fn__2589.doInvoke(stats.clj:1127) ~[storm-core-0.10.1.jar:0.10.1]
at clojure.lang.RestFn.invoke(RestFn.java:436) ~[clojure-1.6.0.jar:?]
at clojure.lang.MultiFn.invoke(MultiFn.java:236) ~[clojure-1.6.0.jar:?]
at backtype.storm.stats$agg_comp_execs_stats.invoke(stats.clj:1303) ~[storm-core-0.10.1.jar:0.10.1]
at backtype.storm.daemon.nimbus$fn__5893$exec_fn__1502__auto__$reify__5917.getComponentPageInfo(nimbus.clj:1715) ~[storm-core-0.10.1.jar:0.10.1]
at backtype.storm.generated.Nimbus$Processor$getComponentPageInfo.getResult(Nimbus.java:3677) ~[storm-core-0.10.1.jar:0.10.1]
at backtype.storm.generated.Nimbus$Processor$getComponentPageInfo.getResult(Nimbus.java:3661) ~[storm-core-0.10.1.jar:0.10.1]
at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:39) ~[storm-core-0.10.1.jar:0.10.1]
at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:39) ~[storm-core-0.10.1.jar:0.10.1]
at backtype.storm.security.auth.SaslTransportPlugin$TUGIWrapProcessor.process(SaslTransportPlugin.java:143) ~[storm-core-0.10.1.jar:0.10.1]
at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285) [storm-core-0.10.1.jar:0.10.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Derek Dagit" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1208" target="_blank">UI: NPE seen when aggregating bolt streams stats</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Derek Dagit" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-18T19:50:55+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user d2r opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1208" title="UI: NPE seen when aggregating bolt streams stats" class="issue-link" data-issue-key="STORM-1208"><del>STORM-1208</del></a> Guard against NPE, and avoid using NaN values</p>

<ul>
	<li>Removes malformed preconditions that don't do anything, and if they did work would throw Errors that would crash nimbus.</li>
	<li>When reading and writing average-type metrics, use `0` instead of `NaN`</li>
	<li>Avoid NPE accessing some maps by doing `(get m k)` instead of `(m k)`.</li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/d2r/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/d2r/storm</a> storm-1208-ui-npe-nan</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/881.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #881</p>

<hr />
<p>commit 3857644b4c459cbe42b78ca8a13bd55ef704fd30<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2015-11-16T20:15:15Z</p>

<p>    Guard against NPE, and avoid using NaN values</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#issuecomment-157164426" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#issuecomment-157164426</a></p>

<p>    LGTM. +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user redsanket commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#issuecomment-157175212" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#issuecomment-157175212</a></p>

<p>    +1 NB</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user zhuoliu commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#issuecomment-157178283" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#issuecomment-157178283</a></p>

<p>    Nice fix. +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user hustfxj commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#issuecomment-157268072" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#issuecomment-157268072</a></p>

<p>    it looks good</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user wuchong commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#discussion_r45027342" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#discussion_r45027342</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/metric/internal/LatencyStatAndMetric.java &#8212;<br/>
    @@ -242,7 +248,7 @@ private synchronized void rotate(long lat, long count, long timeSpent, long targ<br/>
 totalCount += countBuckets<span class="error">&#91;i&#93;</span>;<br/>
 timeNeeded -= bucketTime<span class="error">&#91;i&#93;</span>;<br/>
     }</p>
<ul class="alternate" type="square">
	<li>return ((double)totalLat)/totalCount;<br/>
    +return totalCount > 0 ? ((double)totalLat)/totalCount : 0.0;
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Maybe we can pull the code out into a function named like `div-or-0`, as it appears more than once.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#discussion_r45077073" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#discussion_r45077073</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/metric/internal/LatencyStatAndMetric.java &#8212;<br/>
    @@ -242,7 +248,7 @@ private synchronized void rotate(long lat, long count, long timeSpent, long targ<br/>
 totalCount += countBuckets<span class="error">&#91;i&#93;</span>;<br/>
 timeNeeded -= bucketTime<span class="error">&#91;i&#93;</span>;<br/>
     }</p>
<ul class="alternate" type="square">
	<li>return ((double)totalLat)/totalCount;<br/>
    +return totalCount > 0 ? ((double)totalLat)/totalCount : 0.0;
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Yes we should do this.</p>

<p>    In fact, while reading the documentation again, it seems we must guard against both values of `NaN` and `Infinity`.</p>

<p>    ```<br/>
    user=> (/ 0. 0.)<br/>
    NaN<br/>
    user=> (/ 1. 0.)<br/>
    Infinity<br/>
    ```</p>

<p>    We have only seen the NaN case recently, but it would not hurt to handle both cases, since the dividend and divisor could be 0 independently, especially since the metrics are sampled independently.</p>


<p>    I will update the code to refactor and to check both.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#issuecomment-157440029" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#issuecomment-157440029</a></p>

<p>    @hustfxj , @kishorvpatil , @zhuoliu , @redsanket,</p>

<p>    Added checking for `Infinity` plus some refactoring as per @hustfxj's review.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#issuecomment-157540452" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#issuecomment-157540452</a></p>

<p>    still +1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user wuchong commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#issuecomment-157572950" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#issuecomment-157572950</a></p>

<p>    +1 LGTM</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user jerrypeng commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#discussion_r45250004" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#discussion_r45250004</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/stats.clj &#8212;<br/>
    @@ -335,30 +358,21 @@<br/>
     (defn- agg-bolt-streams-lat-and-count<br/>
       "Aggregates number executed and process & execute latencies."<br/>
       <span class="error">&#91;idk->exec-avg idk->proc-avg idk->executed&#93;</span></p>
<ul class="alternate" type="square">
	<li>{:pre (apply = (map #(set (keys %))</li>
	<li>[idk->exec-avg</li>
	<li>idk->proc-avg</li>
	<li>idk->executed]))}</li>
	<li>(letfn [(weight-avg <span class="error">&#91;id avg&#93;</span> (let <span class="error">&#91;num-e (idk->executed id)&#93;</span></li>
	<li>(if (and avg num-e)</li>
	<li>(* avg num-e)</li>
	<li>0)))]<br/>
    +  (letfn [(weight-avg <span class="error">&#91;id avg&#93;</span><br/>
    +    (let <span class="error">&#91;num-e (idk->executed id)&#93;</span><br/>
    +      (product-or-0 avg num-e)))]<br/>
 (into {}<br/>
   (for <span class="error">&#91;k (keys idk->exec-avg)&#93;</span></li>
	<li>[k {:executeLatencyTotal (weight-avg k (idk->exec-avg k))</li>
	<li>:processLatencyTotal (weight-avg k (idk->proc-avg k))<br/>
    +[k {:executeLatencyTotal (weight-avg k (get idk->exec-avg k))<br/>
    +    :processLatencyTotal (weight-avg k (get idk->proc-avg k))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    what is the point of adding the get especially for (get idk->exec-avg k)? you are getting the keys from the map and then accessing it right? the keys cannot possibly not exist in the map</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/881" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/881#discussion_r45251619" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/881#discussion_r45251619</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/stats.clj &#8212;<br/>
    @@ -335,30 +358,21 @@<br/>
     (defn- agg-bolt-streams-lat-and-count<br/>
       "Aggregates number executed and process & execute latencies."<br/>
       <span class="error">&#91;idk->exec-avg idk->proc-avg idk->executed&#93;</span></p>
<ul class="alternate" type="square">
	<li>{:pre (apply = (map #(set (keys %))</li>
	<li>[idk->exec-avg</li>
	<li>idk->proc-avg</li>
	<li>idk->executed]))}</li>
	<li>(letfn [(weight-avg <span class="error">&#91;id avg&#93;</span> (let <span class="error">&#91;num-e (idk->executed id)&#93;</span></li>
	<li>(if (and avg num-e)</li>
	<li>(* avg num-e)</li>
	<li>0)))]<br/>
    +  (letfn [(weight-avg <span class="error">&#91;id avg&#93;</span><br/>
    +    (let <span class="error">&#91;num-e (idk->executed id)&#93;</span><br/>
    +      (product-or-0 avg num-e)))]<br/>
 (into {}<br/>
   (for <span class="error">&#91;k (keys idk->exec-avg)&#93;</span></li>
	<li>[k {:executeLatencyTotal (weight-avg k (idk->exec-avg k))</li>
	<li>:processLatencyTotal (weight-avg k (idk->proc-avg k))<br/>
    +[k {:executeLatencyTotal (weight-avg k (get idk->exec-avg k))<br/>
    +    :processLatencyTotal (weight-avg k (get idk->proc-avg k))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    ```<br/>
    user=> (def nilmap nil)<br/>
    #'user/nilmap<br/>
    user=> (get nilmap :somekey)<br/>
    nil<br/>
    user=> (nilmap :somekey)<br/>
    NullPointerException   user/eval3 (NO_SOURCE_FILE:4)<br/>
    ```<br/>
    `get` guards against the map itself is `nil`.</p>
