### ISSUE TITLE
[STORM-1213] Remove sigar binaries from source tree

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5051]
<p>In <tt>external/storm-metrics</tt> sigar native binaries were added to the source tree. Since Apache releases are source-only, these binaries can't be included in a release.</p>

<p>My initial thought was just to exclude the binaries from the source distribution, but that would mean that distributions built from a source tarball would not match the convenience binaries from a release (the sigar native binaries would not be included.</p>

<p>The solution I came up with was to leverage the fact that pre-built native binaries are included in the sigar maven distribution (<tt>sigar-x.x.x-native.jar</tt>) and use the maven dependency plugin to unpack them into place during the build, rather than check them into git. One benefit is that it will ensure the versions of the sigar jar and the native binaries match. Another is that mavens checksum/signature checking mechanism will also be applied.</p>

<p>This isn't an ideal solution since the <tt>sigar-x.x.x-native.jar</tt> only includes binaries for linux, OSX, and solaris (notably missing windows DLLs), whereas the non-maven sigar download includes support for a wider range of OSes and architectures.</p>

<p>I view this as an interim measure until we can find a better way to include the native binaries in the build process, rather than checking them into the source tree &#8211; which would be a blocker for releasing.</p>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1213" target="_blank">Remove sigar binaries from source tree</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-23T22:05:41+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>How is having a binary different from having a gif or a png in a release?  Especially a png generated from something else like an SVG file, which we have had in the past for the docs?  If you want to break windows I am not going to stand in your way, but it would be nice to know some more details about what constitutes a "source only release".</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>A compiled binary is by definition not open source, and is very different from an image file (which doesn't require compilation). This is why the RAT (Release Audit Tool) will flag binaries, but not fail the build &#8211; RAT can't distinguish between an image file and a compiled binary.</p>

<p>See <a href="http://incubator.apache.org/guides/releasemanagement.html#check-list" class="external-link" target="_blank" rel="nofollow noopener">http://incubator.apache.org/guides/releasemanagement.html#check-list</a> : "Release consists of source code only, no binaries." ... "This package may not contain compiled components (such as "jar" files) because compiled components are not open source, even if they were built from open source."</p>

<p>also <a href="http://www.apache.org/dev/release.html#what-must-every-release-contain" class="external-link" target="_blank" rel="nofollow noopener">http://www.apache.org/dev/release.html#what-must-every-release-contain</a> : "It is also necessary for the PMC to ensure that the source package is sufficient to build any binary artifacts associated with the release."</p>

<p>This should be as second nature to us as checking for Apache license headers in new source files.</p>

<p>And I don't <em>want to break windows</em>. I want to be able to create a release that complies with ASF policy, which we can't if we include those binaries. As I mentioned in the original description, this is an interim solution (not ideal) that allows us to release. I hope we can find a better way.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157843581" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157843581</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157858618" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157858618</a></p>

<p>    Sorry about the comments after giving it a +1.  I manually ran LatencyVsThroughput and saw that it was not working.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157862181" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157862181</a></p>

<p>    Even with changing the directory I am getting <br/>
    ```<br/>
    java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getPid()J<br/>
    	at org.hyperic.sigar.Sigar.getPid(Native Method) ~<span class="error">&#91;stormjar.jar:0.11.0-SNAPSHOT&#93;</span><br/>
    	at org.apache.storm.metrics.sigar.CPUMetric.<init>(CPUMetric.java:38) ~<span class="error">&#91;stormjar.jar:0.11.0-SNAPSHOT&#93;</span><br/>
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~<span class="error">&#91;?:1.8.0&#93;</span><br/>
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~<span class="error">&#91;?:1.8.0&#93;</span><br/>
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~<span class="error">&#91;?:1.8.0&#93;</span><br/>
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~<span class="error">&#91;?:1.8.0&#93;</span><br/>
    	at java.lang.Class.newInstance(Class.java:433) ~<span class="error">&#91;?:1.8.0&#93;</span><br/>
    	at backtype.storm.utils.Utils.newInstance(Utils.java:91) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
    	at backtype.storm.metric.SystemBolt.registerMetrics(SystemBolt.java:150) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
    	at backtype.storm.metric.SystemBolt.prepare(SystemBolt.java:143) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
    	at backtype.storm.daemon.executor$fn_<em>5157$fn</em>_5170.invoke(executor.clj:777) ~<span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
    	at backtype.storm.util$async_loop$fn__556.invoke(util.clj:480) <span class="error">&#91;storm-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT&#93;</span><br/>
    	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
    	at java.lang.Thread.run(Thread.java:744) <span class="error">&#91;?:1.8.0&#93;</span><br/>
    ```</p>

<p>    We need to do some more work to understand the difference between this patch and what we were doing before.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157868784" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157868784</a></p>

<p>    @revans2 How are you running it (i.e. local/remote/unit test)? My first thought is that we may just need to bind the dependency plugin to a different maven lifecycle.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157869384" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157869384</a></p>

<p>    @revans2 That directory structure is what's in master right now:</p>

<p>    <a href="https://github.com/apache/storm/tree/master/external/storm-metrics/src/main/resources/resources" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/tree/master/external/storm-metrics/src/main/resources/resources</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157873921" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157873921</a></p>

<p>    In master <a href="https://github.com/apache/storm/tree/master/external/storm-metrics/src/main/resources" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/tree/master/external/storm-metrics/src/main/resources</a> gets mapped into the base directory of the jar.  So <a href="https://github.com/apache/storm/tree/master/external/storm-metrics/src/main/resources/resources" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/tree/master/external/storm-metrics/src/main/resources/resources</a> goes to jar://storm-merics.jar/resources/</p>

<p>    For my tests I launch a single node cluster</p>

<p>    ```<br/>
    $ mvn clean install -DskipTests -Drat.skip<br/>
    $ cd storm-dist/binary<br/>
    $ mvn clean package<br/>
    $ tar -xzvf ./target/*.tar.gz<br/>
    $ cd apache-strom*<br/>
    $ ./bin/storm dev-zookeeper & #nimbus, ui, logviewer, supervisor,<br/>
    $ ./bin/storm jar ./examples/storm-starter/storm-starter-topologies-0.11.0-SNAPSHOT.jar storm.starter.ThroughputVsLatency 2000 1 5<br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157874959" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157874959</a></p>

<p>    I just did a diff of the contents of the two jars, old and new(this patch plus me moving the native libraries) and I came up with the following. Around the max native pieces</p>

<p>    ```<br/>
    Only in ./new/resources: libsigar-universal64-macosx-1.6.4.dylib<br/>
    Only in ./old/resources: libsigar-universal-macosx.dylib<br/>
    Only in ./old/resources: libsigar-universal64-macosx.dylib<br/>
    ```<br/>
    It looks like the version number in the dylib might be messing up the linking somehow.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157876251" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157876251</a></p>

<p>    yes that is it.  When I moved `resources/libsigar-universal64-macosx-1.6.4.dylib` to `resources/libsigar-universal64-macosx.dylib` and reran it all worked.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-157880047" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-157880047</a></p>

<p>    @revans2 Ah... okay. So we need to change `resources/resources` to just `resources`, and remove the `-1.6.4` from the libraries, correct?</p>

<p>    That should be doable with the dependency plugin.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-158094151" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-158094151</a></p>

<p>    @ptgoetz Yes you are correct about the changes.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-158184985" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-158184985</a></p>

<p>    @revans2 I couldn't get the maven dependency plugin to do what I wanted, so I changed tactics. I switched to using the maven antrun plugin to download and unpack the sigar native binaries. It downloads the archive to the local maven repository alongside the other sigar dependencies so it only needs to download it once.</p>

<p>    The good news is that allowed me to use the full binary archive, so it includes support for windows and other OSes/architectures. On the down side it's somewhat brittle compared to using "pure" maven, and IMO is kind of ugly. It's also hard-coded to use google code, which is supposedly going away at some point, but that's the only place I could find the archive with a published checksum.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/887#issuecomment-158199509" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887#issuecomment-158199509</a></p>

<p>    @ptgoetz <br/>
    +1 the changes look good and my manual tests all pass.</p>

<p>    I Agree the it kind of ugly.  Ideally what we need to do is to talk to sigar and see if they can update their native jar to do what we want.  It should be fairly simple to have them remove the version number from the jar.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/887" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/887</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a>,</p>

<p>I merged this into master.</p>
