### ISSUE TITLE
[STORM-1215] Use Async Loggers to avoid locking  and logging overhead

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5053]
<p>The loggers are synchronous with immediateFlush to disk, making some of the daemons slow down. In  some other cases, nimbus is slow too with submit-lock.<br/>
Making loggers asynchronous with no necessity to write to disk on every logger event would improve cpu resource usage for logging.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-quote">"pool-7-thread-986"</span> #1025 prio=5 os_prio=0 tid=0x00007f0f9628c800 nid=0x1b84 runnable [0x00007f0f0fa2a000]
   java.lang.<span class="code-object">Thread</span>.State: RUNNABLE
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	- locked <0x00000003c00ae520> (a java.io.BufferedOutputStream)
	at java.io.PrintStream.write(PrintStream.java:482)
	- locked <0x00000003c00ae500> (a java.io.PrintStream)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	- locked <0x00000003c00ae640> (a java.io.OutputStreamWriter)
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
	at java.io.PrintStream.write(PrintStream.java:527)
	- locked <0x00000003c00ae500> (a java.io.PrintStream)
	at java.io.PrintStream.print(PrintStream.java:669)
	at java.io.PrintStream.println(PrintStream.java:806)
	- locked <0x00000003c00ae500> (a java.io.PrintStream)
	at org.apache.logging.log4j.status.StatusConsoleListener.log(StatusConsoleListener.java:81)
	at org.apache.logging.log4j.status.StatusLogger.logMessage(StatusLogger.java:218)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:344)
	at org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:59)
	at org.apache.logging.log4j.core.appender.AbstractAppender.error(AbstractAppender.java:86)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:116)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:198)
	at clojure.tools.logging$eval1$fn__7.invoke(NO_SOURCE_FILE:0)
	at clojure.tools.logging.impl$fn__28$G__8__39.invoke(impl.clj:16)
	at clojure.tools.logging$log_STAR_.invoke(logging.clj:59)
	at backtype.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:781)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1215" target="_blank">Use Async Loggers to avoid locking  and logging overhead</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-19T17:48:39+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1215" title="Use Async Loggers to avoid locking  and logging overhead" class="issue-link" data-issue-key="STORM-1215"><del>STORM-1215</del></a> Use Asynchronous logger for improving performance.</p>

<p>    The changes to loggers for all daemons and workers.</p>
<ul class="alternate" type="square">
	<li>Turn off immediateFlush.</li>
	<li>Enable async logging.</li>
	<li>Turn off Immediate Fail for log events on syslog logger to avoid making blocking call without timeout.</li>
</ul>




<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1215" title="Use Async Loggers to avoid locking  and logging overhead" class="issue-link" data-issue-key="STORM-1215"><del>STORM-1215</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/888.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #888</p>

<hr />
<p>commit 601efa5cad6604bf922f7f1ef843e3f8ae9bf1f2<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-11-17T16:14:56Z</p>

<p>    All daemons should Async Logging to avoid locking issues</p>

<p>commit 1660da0e36b6f5647bc21f9813f3eca1c3c53afa<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2015-11-17T17:23:38Z</p>

<p>    Make worker log appenders async for performance</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157487326" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157487326</a></p>

<p>    This also switches to UTF-8 encoding for syslog, for compatibility.  We have seen issues with this in the past.</p>

<p>    Evidently we cannot configure the context except via a System property, so looks OK to me.</p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157500178" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157500178</a></p>

<p>    The log level changes on the UI still work, and performance seems fine too, but if I enable topology.debug I am seeing some very odd things that I would like to explore some more.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157501592" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157501592</a></p>

<p>    OK I got a heap dump and when debug is enabled we are logging faster then the logger can write.  This is resulting in the async logger disruptor queue starting to fill up, and making lots of GC problems.  Can we disable this for the worker process or find a way to configure it so the memory usage is not unbounded?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157501985" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157501985</a></p>

<p>    @revans2 Thank you for testing and quick feedback on it. I have reverted the changes for worker, so worker will continue to log synchronously.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157531549" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157531549</a></p>

<p>    +1 I just tested and the workers are no longer crashing, but it might be good to set immediateFlush="false" in the worker.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157538628" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157538628</a></p>

<p>    @revans2  Turned off immediateFlush for worker.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157843173" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157843173</a></p>

<p>    +1 looks good to me</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157843254" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157843254</a></p>

<p>    @d2r any other comments on the most recent changes?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/888#issuecomment-157878854" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/888#issuecomment-157878854</a></p>

<p>    Looks good to me +1</p>
