### ISSUE TITLE
[STORM-1223] test-nimbus-check-authorization-params consistently crashes (not fails) on Windows

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5061]
<p>test-nimbus-check-authorization-params consistently crashes on Windows.  This appears to be a crash, not a testcase-recognized "failure" or "error".  I'm testing now against master (a8d253a9b725b8fb3181efbfcac78d06e186bea9), but I've been seeing it for several days, so it's been an issue longer than the latest commit.</p>

<p>Here's the system-out portion of the test report:</p>

<blockquote>
<p><testcase name="test-nimbus-check-authorization-params" classname="backtype.storm.nimbus-test"><br/>
    <system-out><br/>
<![CDATA[66921 <span class="error">&#91;main&#93;</span> INFO  b.s.zookeeper - Starting inprocess zookeeper at port 2000 and dir C:\Users\cburgess\AppData\Local\Temp\6baba454-c591-4699-8a55-d3161b02b7e3<br/>
66939 <span class="error">&#91;main&#93;</span> INFO  b.s.d.nimbus - Starting Nimbus with conf </p>
<div class="error"><span class="error">Unknown macro: {"topology.builtin.metrics.bucket.size.secs" 60, "nimbus.childopts" "-Xmx1024m", "ui.filter.params" nil, "storm.cluster.mode" "local", "storm.messaging.netty.client_worker_threads" 1, "logviewer.max.per.worker.logs.size.mb" 2048, "supervisor.run.worker.as.user" false, "topology.max.task.parallelism" nil, "zmq.threads" 1, "storm.group.mapping.service" "backtype.storm.security.auth.ShellBasedGroupsMapping", "transactional.zookeeper.root" "/transactional", "topology.sleep.spout.wait.strategy.time.ms" 1, "scheduler.display.resource" false, "topology.max.replication.wait.time.sec" 60, "drpc.invocations.port" 3773, "topology.multilang.serializer" "backtype.storm.multilang.JsonSerializer", "storm.messaging.netty.server_worker_threads" 1, "topology.max.error.report.per.interval" 5, "storm.thrift.transport" "backtype.storm.security.auth.SimpleTransportPlugin", "zmq.hwm" 0, "storm.group.mapping.service.params" nil, "worker.profiler.enabled" true, "storm.principal.tolocal" "backtype.storm.security.auth.DefaultPrincipalToLocal", "supervisor.worker.shutdown.sleep.secs" 1, "storm.zookeeper.retry.times" 5, "ui.actions.enabled" true, "zmq.linger.millis" 0, "supervisor.enable" true, "topology.stats.sample.rate" 0.05, "storm.messaging.netty.min_wait_ms" 100, "worker.log.level.reset.poll.secs" 30, "storm.zookeeper.port" 2000, "supervisor.heartbeat.frequency.secs" 5, "topology.enable.message.timeouts" false, "supervisor.cpu.capacity" 400.0, "drpc.worker.threads" 64, "drpc.queue.size" 128, "topology.backpressure.enable" true, "drpc.https.keystore.password" "", "nimbus.code.sync.freq.secs" 300, "logviewer.port" 8000, "topology.executor.send.buffer.size" 1024, "topology.worker.logwriter.childopts" "-Xmx64m", "topology.spout.wait.strategy" "backtype.storm.spout.SleepSpoutWaitStrategy", "ui.host" "0.0.0.0", "storm.nimbus.retry.interval.millis" 2000, "nimbus.inbox.jar.expiration.secs" 3600, "dev.zookeeper.path" "/tmp/dev-storm-zookeeper", "topology.acker.executors" nil, "topology.fall.back.on.java.serialization" true, "topology.eventlogger.executors" nil, "storm.zookeeper.servers" ["localhost"], "nimbus.thrift.threads" 64, "logviewer.cleanup.age.mins" 10080, "topology.worker.childopts" nil, "topology.classpath" nil, "supervisor.monitor.frequency.secs" 3, "nimbus.credential.renewers.freq.secs" 600, "topology.skip.missing.kryo.registrations" true, "drpc.authorizer.acl.filename" "drpc-auth-acl.yaml", "storm.group.mapping.service.cache.duration.secs" 120, "topology.testing.always.try.serialize" false, "nimbus.monitor.freq.secs" 10, "storm.health.check.timeout.ms" 5000, "supervisor.supervisors" [], "topology.tasks" nil, "topology.bolts.outgoing.overflow.buffer.enable" false, "storm.messaging.netty.socket.backlog" 500, "topology.workers" 1, "storm.local.dir" "C}</span> </div>
<p>66939 <span class="error">&#91;main&#93;</span> INFO  b.s.d.nimbus - Using default scheduler<br/>
66939 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
66944 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
66977 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
66977 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - Zookeeper state update: :connected:none<br/>
66998 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
66998 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - Zookeeper state update: :connected:none<br/>
67048 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67050 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67069 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67089 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67334 <span class="error">&#91;main&#93;</span> INFO  b.s.zookeeper - Queued up for leader lock.<br/>
67334 <span class="error">&#91;main&#93;</span> INFO  b.s.d.nimbus - not a leader, skipping cleanup-corrupt-topologies<br/>
67381 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67414 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67414 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - Zookeeper state update: :connected:none<br/>
67435 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - ITOC049.progressrail.com gained leadership, checking if it has all the topology code locally.<br/>
67456 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67456 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - active-topology-ids [] local-topology-ids [] diff-topology []<br/>
67456 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - Accepting leadership, all active topology found localy.<br/>
67458 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67476 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67497 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67497 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - Zookeeper state update: :connected:none<br/>
67526 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67547 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67551 <span class="error">&#91;main&#93;</span> INFO  b.s.d.supervisor - Starting Supervisor with conf </p>
<div class="error"><span class="error">Unknown macro: {"topology.builtin.metrics.bucket.size.secs" 60, "nimbus.childopts" "-Xmx1024m", "ui.filter.params" nil, "storm.cluster.mode" "local", "storm.messaging.netty.client_worker_threads" 1, "logviewer.max.per.worker.logs.size.mb" 2048, "supervisor.run.worker.as.user" false, "topology.max.task.parallelism" nil, "zmq.threads" 1, "storm.group.mapping.service" "backtype.storm.security.auth.ShellBasedGroupsMapping", "transactional.zookeeper.root" "/transactional", "topology.sleep.spout.wait.strategy.time.ms" 1, "scheduler.display.resource" false, "topology.max.replication.wait.time.sec" 60, "drpc.invocations.port" 3773, "topology.multilang.serializer" "backtype.storm.multilang.JsonSerializer", "storm.messaging.netty.server_worker_threads" 1, "topology.max.error.report.per.interval" 5, "storm.thrift.transport" "backtype.storm.security.auth.SimpleTransportPlugin", "zmq.hwm" 0, "storm.group.mapping.service.params" nil, "worker.profiler.enabled" true, "storm.principal.tolocal" "backtype.storm.security.auth.DefaultPrincipalToLocal", "supervisor.worker.shutdown.sleep.secs" 1, "storm.zookeeper.retry.times" 5, "ui.actions.enabled" true, "zmq.linger.millis" 0, "supervisor.enable" true, "topology.stats.sample.rate" 0.05, "storm.messaging.netty.min_wait_ms" 100, "worker.log.level.reset.poll.secs" 30, "storm.zookeeper.port" 2000, "supervisor.heartbeat.frequency.secs" 5, "topology.enable.message.timeouts" false, "supervisor.cpu.capacity" 400.0, "drpc.worker.threads" 64, "drpc.queue.size" 128, "topology.backpressure.enable" true, "drpc.https.keystore.password" "", "nimbus.code.sync.freq.secs" 300, "logviewer.port" 8000, "topology.executor.send.buffer.size" 1024, "topology.worker.logwriter.childopts" "-Xmx64m", "topology.spout.wait.strategy" "backtype.storm.spout.SleepSpoutWaitStrategy", "ui.host" "0.0.0.0", "storm.nimbus.retry.interval.millis" 2000, "nimbus.inbox.jar.expiration.secs" 3600, "dev.zookeeper.path" "/tmp/dev-storm-zookeeper", "topology.acker.executors" nil, "topology.fall.back.on.java.serialization" true, "topology.eventlogger.executors" nil, "storm.zookeeper.servers" ["localhost"], "nimbus.thrift.threads" 64, "logviewer.cleanup.age.mins" 10080, "topology.worker.childopts" nil, "topology.classpath" nil, "supervisor.monitor.frequency.secs" 3, "nimbus.credential.renewers.freq.secs" 600, "topology.skip.missing.kryo.registrations" true, "drpc.authorizer.acl.filename" "drpc-auth-acl.yaml", "storm.group.mapping.service.cache.duration.secs" 120, "topology.testing.always.try.serialize" false, "nimbus.monitor.freq.secs" 10, "storm.health.check.timeout.ms" 5000, "supervisor.supervisors" [], "topology.tasks" nil, "topology.bolts.outgoing.overflow.buffer.enable" false, "storm.messaging.netty.socket.backlog" 500, "topology.workers" 1, "storm.local.dir" "C}</span> </div>
<p>67558 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67593 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67593 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - Zookeeper state update: :connected:none<br/>
67631 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67651 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67681 <span class="error">&#91;main&#93;</span> INFO  b.s.d.supervisor - Starting supervisor with id c15c718b-a6a2-4fd1-910e-c28343b9526f at host ITOC049.progressrail.com<br/>
67682 <span class="error">&#91;main&#93;</span> INFO  b.s.d.supervisor - Starting Supervisor with conf </p>
<div class="error"><span class="error">Unknown macro: {"topology.builtin.metrics.bucket.size.secs" 60, "nimbus.childopts" "-Xmx1024m", "ui.filter.params" nil, "storm.cluster.mode" "local", "storm.messaging.netty.client_worker_threads" 1, "logviewer.max.per.worker.logs.size.mb" 2048, "supervisor.run.worker.as.user" false, "topology.max.task.parallelism" nil, "zmq.threads" 1, "storm.group.mapping.service" "backtype.storm.security.auth.ShellBasedGroupsMapping", "transactional.zookeeper.root" "/transactional", "topology.sleep.spout.wait.strategy.time.ms" 1, "scheduler.display.resource" false, "topology.max.replication.wait.time.sec" 60, "drpc.invocations.port" 3773, "topology.multilang.serializer" "backtype.storm.multilang.JsonSerializer", "storm.messaging.netty.server_worker_threads" 1, "topology.max.error.report.per.interval" 5, "storm.thrift.transport" "backtype.storm.security.auth.SimpleTransportPlugin", "zmq.hwm" 0, "storm.group.mapping.service.params" nil, "worker.profiler.enabled" true, "storm.principal.tolocal" "backtype.storm.security.auth.DefaultPrincipalToLocal", "supervisor.worker.shutdown.sleep.secs" 1, "storm.zookeeper.retry.times" 5, "ui.actions.enabled" true, "zmq.linger.millis" 0, "supervisor.enable" true, "topology.stats.sample.rate" 0.05, "storm.messaging.netty.min_wait_ms" 100, "worker.log.level.reset.poll.secs" 30, "storm.zookeeper.port" 2000, "supervisor.heartbeat.frequency.secs" 5, "topology.enable.message.timeouts" false, "supervisor.cpu.capacity" 400.0, "drpc.worker.threads" 64, "drpc.queue.size" 128, "topology.backpressure.enable" true, "drpc.https.keystore.password" "", "nimbus.code.sync.freq.secs" 300, "logviewer.port" 8000, "topology.executor.send.buffer.size" 1024, "topology.worker.logwriter.childopts" "-Xmx64m", "topology.spout.wait.strategy" "backtype.storm.spout.SleepSpoutWaitStrategy", "ui.host" "0.0.0.0", "storm.nimbus.retry.interval.millis" 2000, "nimbus.inbox.jar.expiration.secs" 3600, "dev.zookeeper.path" "/tmp/dev-storm-zookeeper", "topology.acker.executors" nil, "topology.fall.back.on.java.serialization" true, "topology.eventlogger.executors" nil, "storm.zookeeper.servers" ["localhost"], "nimbus.thrift.threads" 64, "logviewer.cleanup.age.mins" 10080, "topology.worker.childopts" nil, "topology.classpath" nil, "supervisor.monitor.frequency.secs" 3, "nimbus.credential.renewers.freq.secs" 600, "topology.skip.missing.kryo.registrations" true, "drpc.authorizer.acl.filename" "drpc-auth-acl.yaml", "storm.group.mapping.service.cache.duration.secs" 120, "topology.testing.always.try.serialize" false, "nimbus.monitor.freq.secs" 10, "storm.health.check.timeout.ms" 5000, "supervisor.supervisors" [], "topology.tasks" nil, "topology.bolts.outgoing.overflow.buffer.enable" false, "storm.messaging.netty.socket.backlog" 500, "topology.workers" 1, "storm.local.dir" "C}</span> </div>
<p>67689 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67717 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67718 <span class="error">&#91;main-EventThread&#93;</span> INFO  b.s.zookeeper - Zookeeper state update: :connected:none<br/>
67739 <span class="error">&#91;main&#93;</span> INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting<br/>
67767 <span class="error">&#91;main-EventThread&#93;</span> INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED<br/>
67797 <span class="error">&#91;main&#93;</span> INFO  b.s.d.supervisor - Starting supervisor with id 1d0d7361-0e29-4ff5-9cfd-e0b3a4eceaf9 at host ITOC049.progressrail.com<br/>
67798 <span class="error">&#91;main&#93;</span> INFO  b.s.l.ThriftAccessLogger - Request ID: 1 access from:  principal:  operation: submitTopology<br/>
67799 <span class="error">&#91;main&#93;</span> INFO  b.s.d.nimbus - Received topology submission for test-nimbus-check-autho-params with conf </p>
<div class="error"><span class="error">Unknown macro: {"topology.max.task.parallelism" nil, "topology.submitter.principal" "", "topology.acker.executors" nil, "topology.eventlogger.executors" nil, "storm.zookeeper.superACL" nil, "topology.users" (), "topology.submitter.user" "", "topology.kryo.register" nil, "topology.kryo.decorators" (), "storm.id" "test-nimbus-check-autho-params-1-1448071948", "topology.name" "test-nimbus-check-autho-params"}</span> </div>
<p>67839 <span class="error">&#91;main&#93;</span> INFO  b.s.d.nimbus - nimbus file location:C:\Users\cburgess\AppData\Local\Temp\e2a608d7-edc6-4348-b18b-5224d1cd3b17\nimbus\stormdist\test-nimbus-check-autho-params-1-1448071948<br/>
67897 <span class="error">&#91;main&#93;</span> INFO  b.s.d.nimbus - desired replication count of 1 not achieved but we have hit the max wait time 60 so moving on with replication count = 0<br/>
67961 <span class="error">&#91;main&#93;</span> INFO  b.s.d.nimbus - Activating test-nimbus-check-autho-params: test-nimbus-check-autho-params-1-1448071948<br/>
68019 <span class="error">&#91;timer&#93;</span> ERROR b.s.d.nimbus - Error when processing event<br/>
java.lang.NullPointerException<br/>
	at backtype.storm.daemon.common$all_components$iter_<em>1523</em><em>1527$fn</em>_1528.invoke(common.clj:130) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.Cons.next(Cons.java:39) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.RT.boundedLength(RT.java:1735) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.RestFn.applyTo(RestFn.java:130) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.core$apply.invoke(core.clj:632) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at backtype.storm.daemon.common$all_components.invoke(common.clj:128) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.daemon.common$storm_task_info.invoke(common.clj:358) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.daemon.nimbus$compute_executors.invoke(nimbus.clj:537) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.daemon.nimbus$compute_executor__GT_component.invoke(nimbus.clj:549) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.daemon.nimbus$read_topology_details.invoke(nimbus.clj:441) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.daemon.nimbus$mk_assignments$iter_<em>10041</em><em>10045$fn</em>_10046.invoke(nimbus.clj:797) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.RT.seq(RT.java:507) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.core$seq__4128.invoke(core.clj:137) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.core.protocols$fn__6506.invoke(protocols.clj:101) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.core.protocols$fn_<em>6452$G</em><em>6447</em>_6465.invoke(protocols.clj:13) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.core$reduce.invoke(core.clj:6519) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.core$into.invoke(core.clj:6600) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at backtype.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:796) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:410) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at backtype.storm.daemon.nimbus$fn_<em>10320$exec_fn</em><em>1460</em><em>auto</em>__<em>10321$fn</em><em>10334$fn</em>_10335.invoke(nimbus.clj:1280) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.daemon.nimbus$fn_<em>10320$exec_fn</em><em>1460</em><em>auto</em>__<em>10321$fn</em>_10334.invoke(nimbus.clj:1279) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.timer$schedule_recurring$this__1826.invoke(timer.clj:105) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.timer$mk_timer$fn_<em>1809$fn</em>_1810.invoke(timer.clj:50) <span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.timer$mk_timer$fn__1809.invoke(timer.clj:42) <span class="error">&#91;classes/:?&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:744) <span class="error">&#91;?:1.7.0_45&#93;</span><br/>
68022 <span class="error">&#91;timer&#93;</span> ERROR b.s.util - Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:339) <span class="error">&#91;classes/:?&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at backtype.storm.daemon.nimbus$nimbus_data$fn__9579.invoke(nimbus.clj:160) <span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.timer$mk_timer$fn_<em>1809$fn</em>_1810.invoke(timer.clj:71) <span class="error">&#91;classes/:?&#93;</span><br/>
	at backtype.storm.timer$mk_timer$fn__1809.invoke(timer.clj:42) <span class="error">&#91;classes/:?&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:744) <span class="error">&#91;?:1.7.0_45&#93;</span><br/>
68023 <span class="error">&#91;main&#93;</span> INFO  b.s.d.nimbus - Shutting down master</p></blockquote>

---
<details><summary><i>Originally reported by <a title="Chuck Burgess" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashnazg">ashnazg</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1223" target="_blank">test-nimbus-check-authorization-params consistently crashes (not fails) on Windows</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Chuck Burgess" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashnazg">ashnazg</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-12-02T16:31:40+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>I think this might the same thing I saw with building the master branch on JDK 1.7 on OSX.</p>

<p>On OS X its manifests as a sementation fault (jvm crash). But it doesn't happen with 1.8.</p>

<p>Can you try with 1.8?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashnazg">ashnazg</a>:</i>
<p>This test is now running fine for me on master (1059735f78bb5e7a15831e1d225ca9f97df06f8d), still with JDK7, so some recent change has solved it.</p>
