### ISSUE TITLE
[STORM-1364] Log storm version on daemon start

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5199]
<p>As an admin, I would like each storm daemon to log its version of storm, so that I can more easily root cause issues happening near an upgrade of the cluster.</p>

---
<details><summary><i>Originally reported by <a title="Derek Dagit" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1364" target="_blank">Log storm version on daemon start</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Derek Dagit" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-12-07T19:06:28+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user d2r opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1364" title="Log storm version on daemon start" class="issue-link" data-issue-key="STORM-1364"><del>STORM-1364</del></a> logs the storm version when starting</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/d2r/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/d2r/storm</a> storm-1364-deamons-log-version-on-start</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/916.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #916</p>

<hr />
<p>commit b52988ab1d6c3ef853769ebb272e27caaf55ec38<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2015-12-03T15:55:26Z</p>

<p>    logs the storm version when starting</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user unsleepy22 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-161705726" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-161705726</a></p>

<p>    LGTM +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-161728319" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-161728319</a></p>

<p>    ```<br/>
    testPollWhileThereAreNoDataAvailable(backtype.storm.utils.ShellBoltMessageQueueTest)  Time elapsed: 1.005 sec  <<< FAILURE!<br/>
    junit.framework.AssertionFailedError: null<br/>
    	at junit.framework.Assert.fail(Assert.java:55)<br/>
    	at junit.framework.Assert.assertTrue(Assert.java:22)<br/>
    	at junit.framework.Assert.assertTrue(Assert.java:31)<br/>
    	at junit.framework.TestCase.assertTrue(TestCase.java:201)<br/>
    	at backtype.storm.utils.ShellBoltMessageQueueTest.testPollWhileThereAreNoDataAvailable(ShellBoltMessageQueueTest.java:55)<br/>
    ```</p>

<p>    This is the test I see failing both in this pull request and also on my travis<br/>
    ci setup.</p>

<p>    It does not seem related to my changes, but it is causing the overall check to<br/>
    fail for storm-core, and that causes the other modules not to be tested.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-161782690" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-161782690</a></p>

<p>    closing/reopening to trigger another ci build</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/916" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user d2r reopened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1364" title="Log storm version on daemon start" class="issue-link" data-issue-key="STORM-1364"><del>STORM-1364</del></a> logs the storm version when starting</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/d2r/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/d2r/storm</a> storm-1364-deamons-log-version-on-start</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/916.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #916</p>

<hr />
<p>commit b52988ab1d6c3ef853769ebb272e27caaf55ec38<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2015-12-03T15:55:26Z</p>

<p>    logs the storm version when starting</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-161784128" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-161784128</a></p>

<p>    +1 looks good to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-161800044" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-161800044</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user wuchong commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-161851976" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-161851976</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-161999062" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-161999062</a></p>

<p>    3 failures in nimbus-auth-test for storm-core on jdk8 only.  Need to look at why it happened.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user darionyaphet commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-162433815" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-162433815</a></p>

<p>    It seems just add some log info </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user jerrypeng commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-162589790" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-162589790</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-162593739" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-162593739</a></p>

<p>    > 3 failures in nimbus-auth-test for storm-core on jdk8 only. Need to look at why it happened.</p>

<p>    I did look at these test failures.  They are likely not related to this change.  There is a race condition whenever we try to get an ephemeral port from the system such that sometimes multiple tests launch nimbus nodes with the same port.</p>

<p>    Separately I will look into tightening the race and/or locking such that each test case will use only the test nimbus instance that is configured especially for it.</p>

<p>    In the meantime, I will close and re-open this pull request to start another travis-ci build.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/916" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user d2r reopened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1364" title="Log storm version on daemon start" class="issue-link" data-issue-key="STORM-1364"><del>STORM-1364</del></a> logs the storm version when starting</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/d2r/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/d2r/storm</a> storm-1364-deamons-log-version-on-start</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/916.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #916</p>

<hr />
<p>commit b52988ab1d6c3ef853769ebb272e27caaf55ec38<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2015-12-03T15:55:26Z</p>

<p>    logs the storm version when starting</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/916#issuecomment-162618653" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916#issuecomment-162618653</a></p>

<p>    Created <a href="https://issues.apache.org/jira/browse/STORM-1377" title="nimbus_auth_test: very short timeouts causing spurious failures" class="issue-link" data-issue-key="STORM-1377"><del>STORM-1377</del></a>(<a href="https://issues.apache.org/jira/browse/STORM-1377" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1377</a>) for nimbus-auth-test issues.</p>

<p>    Checks have passed, so I will merge this since there are binding +1s and no unresolved issues after 1 day.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/916" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/916</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>:</i>
<p>Merged to master</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1377">STORM-1377</a>]</i>
