### ISSUE TITLE
[STORM-1367] Issue with OpaqueTridentKafkaSpout - TridentKafkaConfig getting (java.lang.RuntimeException: kafka.common.OffsetOutOfRangeException)

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5202]
<p>I'm using trident topology with OpaqueTridentKafkaSpout.</p>

<p>Code snippet of TridentKafkaConfig i’m using :-</p>

<p>OpaqueTridentKafkaSpout kafkaSpout = null;<br/>
TridentKafkaConfig spoutConfig = new TridentKafkaConfig(new ZkHosts("xxx.x.x.9:2181,xxx.x.x.1:2181,xxx.x.x.2:2181"), "topic_name");<br/>
			spoutConfig.scheme = new SchemeAsMultiScheme(new StringScheme());<br/>
			spoutConfig.forceFromStart = true;<br/>
spoutConfig.fetchSizeBytes = 147483600;<br/>
			kafkaSpout = new OpaqueTridentKafkaSpout(spoutConfig);</p>

<p>I get this runtime exception from one of the workers :-</p>

<p>java.lang.RuntimeException: storm.kafka.UpdateOffsetException at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:135) at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:106) at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) at backtype.storm.daemon.executor$fn_<em>5694$fn</em><em>5707$fn</em><em>5758.invoke(executor.clj:819) at backtype.storm.util$async_loop$fn</em><em>545.invoke(util.clj:479) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745) Caused by: storm.kafka.UpdateOffsetException at storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:186) at storm.kafka.trident.TridentKafkaEmitter.fetchMessages(TridentKafkaEmitter.java:132) at storm.kafka.trident.TridentKafkaEmitter.doEmitNewPartitionBatch(TridentKafkaEmitter.java:113) at storm.kafka.trident.TridentKafkaEmitter.failFastEmitNewPartitionBatch(TridentKafkaEmitter.java:72) at storm.kafka.trident.TridentKafkaEmitter.emitNewPartitionBatch(TridentKafkaEmitter.java:79) at storm.kafka.trident.TridentKafkaEmitter.access$000(TridentKafkaEmitter.java:46) at storm.kafka.trident.TridentKafkaEmitter$1.emitPartitionBatch(TridentKafkaEmitter.java:204) at storm.kafka.trident.TridentKafkaEmitter$1.emitPartitionBatch(TridentKafkaEmitter.java:194) at storm.trident.spout.OpaquePartitionedTridentSpoutExecutor$Emitter.emitBatch(OpaquePartitionedTridentSpoutExecutor.java:127) at storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:82) at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:370) at backtype.storm.daemon.executor$fn</em><em>5694$tuple_action_fn</em><em>5696.invoke(executor.clj:690) at backtype.storm.daemon.executor$mk_task_receiver$fn</em><em>5615.invoke(executor.clj:436) at backtype.storm.disruptor$clojure_handler$reify</em>_5189.onEvent(disruptor.clj:58) at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:127) ... 6 more</p>

<p>But when i set spoutConfig.forceFromStart = true... It works fine for a while and then fails throwing this exception. I need a trident topology to give out accurate exactly-once processing even when the topology is restarted. </p>

<p>As per some posts, I have tried setting spoutConfig :-</p>

<p>spoutConfig.maxOffsetBehind = Long.MAX_VALUE;</p>

<p>spoutConfig.startOffsetTime = kafka.api.OffsetRequest.EarliestTime();</p>

<p>My Kafka retention time is default - 128 Hours i.e. 7 Days and kafka producer is sending 6800 messages/second to Storm/Trident topology. I have gone through most of the posts, but none of them seem to solve this issue. </p>

---
<details><summary><i>Originally reported by <a title="Rakesh Surendra" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=anavalamudi">anavalamudi</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1367" target="_blank">Issue with OpaqueTridentKafkaSpout - TridentKafkaConfig getting (java.lang.RuntimeException: kafka.common.OffsetOutOfRangeException)</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Harsha" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:46+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=anavalamudi">anavalamudi</a>:</i>
<p>Kafka was resetting after a while and TridentKafkaSpout was not able to find the previous offset and thus throwing this exception.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=anavalamudi">anavalamudi</a>:</i>
<p>Re-opening this issue. I assumed it was solved. But one of the workers still throws this exception after a while.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=anavalamudi">anavalamudi</a>:</i>
<p>Update : This looks like an issue with Trident Kafka Spout and zookeeper. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
