### ISSUE TITLE
[STORM-1370] Bug fixes for MultitenantScheduler

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5205]
<p>Bug 1:</p>

<p>Sort nodes by slots used when scheduing isolated<br/>
Because nimbus removes "dead" slots (slots for which their workers have<br/>
not yet sent a heartbeat) before schedule is called, we cannot rely on<br/>
teh number of free slots on a node.  This will break for clusters whose<br/>
nodes have a heterogenious number of slots configured.</p>

<p>Derive the effective number of hosts by taking the minimum of the<br/>
config's value and the number of executors in the topology.</p>

<p>If the user requests the topology be scheduled among a number of hosts,<br/>
then retry scheduling when the effective number does not match the<br/>
scheduled number.</p>

<p>Bug 2:</p>

<p>Nimbus crashes from an exception being thrown by the multitenant scheduler trying to assign executors from an isolated topology to a node that is full.<br/>
Error in nimbus.log:<br/>
java.lang.IllegalStateException: Trying to assign to a full node xxxxxxxxxxxxx<br/>
at backtype.storm.scheduler.multitenant.Node.assign(Node.java:232) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at backtype.storm.scheduler.multitenant.NodePool$RoundRobinSlotScheduler.assignSlotTo(NodePool.java:171) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at backtype.storm.scheduler.multitenant.IsolatedPool.scheduleAsNeeded(IsolatedPool.java:164) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at backtype.storm.scheduler.multitenant.MultitenantScheduler.schedule(MultitenantScheduler.java:96) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~<span class="error">&#91;?:1.8.0_40&#93;</span><br/>
at java.lang.reflect.Method.invoke(Method.java:497) ~<span class="error">&#91;?:1.8.0_40&#93;</span><br/>
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at backtype.storm.daemon.nimbus$compute_new_scheduler_assignments.invoke(nimbus.clj:750) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at backtype.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:806) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:410) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at backtype.storm.daemon.nimbus$fn_6009$exec_fn1502auto__6010$fn6020$fn_6021.invoke(nimbus.clj:1245) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at backtype.storm.daemon.nimbus$fn_6009$exec_fn1502auto__6010$fn_6020.invoke(nimbus.clj:1244) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at backtype.storm.timer$schedule_recurring$this__4635.invoke(timer.clj:105) ~<span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at backtype.storm.timer$mk_timer$fn_4618$fn_4619.invoke(timer.clj:50) <span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at backtype.storm.timer$mk_timer$fn__4618.invoke(timer.clj:42) <span class="error">&#91;storm-core-0.10.1.y.jar:0.10.1.y&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_40&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Boyang Jerry Peng" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jerrypeng">jerrypeng</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1370" target="_blank">Bug fixes for MultitenantScheduler</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Boyang Jerry Peng" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jerrypeng">jerrypeng</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-12-10T17:16:06+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user jerrypeng opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/923" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/923</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1370" title="Bug fixes for MultitenantScheduler" class="issue-link" data-issue-key="STORM-1370"><del>STORM-1370</del></a> - Bug fixes for MultitenantScheduler</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/jerrypeng/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jerrypeng/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1370" title="Bug fixes for MultitenantScheduler" class="issue-link" data-issue-key="STORM-1370"><del>STORM-1370</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/923.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/923.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #923</p>

<hr />
<p>commit 82f9d969446898bc6bdbdb03f2b927a55174f97c<br/>
Author: Boyang Jerry Peng <jerrypeng@yahoo-inc.com><br/>
Date:   2015-12-04T16:23:10Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1370" title="Bug fixes for MultitenantScheduler" class="issue-link" data-issue-key="STORM-1370"><del>STORM-1370</del></a> - Bug fixes for MultitenantScheduler</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user jerrypeng commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/923#issuecomment-162010840" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/923#issuecomment-162010840</a></p>

<p>    @d2r can you take a look thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/923#discussion_r46701044" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/923#discussion_r46701044</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/scheduler/multitenant/Node.java &#8212;<br/>
    @@ -334,7 +334,7 @@ public static int countTotalSlotsAlive(Collection<Node> nodes) {<br/>
       public static final Comparator<Node> FREE_NODE_COMPARATOR_DEC = new Comparator<Node>() {<br/>
 @Override<br/>
 public int compare(Node o1, Node o2) {</p>
<ul class="alternate" type="square">
	<li>return o2.totalSlotsFree() - o1.totalSlotsFree();<br/>
    +      return o1.totalSlotsUsed() - o2.totalSlotsUsed();
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Yes, this was the fix for spreading components on isolated nodes when certain workers are having trouble coming up.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user jerrypeng commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/923#issuecomment-162014757" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/923#issuecomment-162014757</a></p>

<p>    unrelated travis failure only for java 8 storm-core build</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/923#issuecomment-163046542" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/923#issuecomment-163046542</a></p>

<p>    +1 looks good to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/923" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/923</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jerrypeng" class="user-hover" rel="jerrypeng">Boyang Jerry Peng</a>,</p>

<p>I merged this into master.</p>
