### ISSUE TITLE
[STORM-1374] Random test failures on WindowManagerTest

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5209]
<p><a href="https://travis-ci.org/apache/storm/jobs/94768693" class="external-link" target="_blank" rel="nofollow noopener">https://travis-ci.org/apache/storm/jobs/94768693</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">testTimeBasedWindow(backtype.storm.windowing.WindowManagerTest)  Time elapsed: 0.176 sec  <<< FAILURE!

java.lang.AssertionError: expected:<100> but was:<0>

    at org.junit.Assert.fail(Assert.java:88)

    at org.junit.Assert.failNotEquals(Assert.java:743)

    at org.junit.Assert.assertEquals(Assert.java:118)

    at org.junit.Assert.assertEquals(Assert.java:555)

    at org.junit.Assert.assertEquals(Assert.java:542)

    at backtype.storm.windowing.WindowManagerTest.testTimeBasedWindow(WindowManagerTest.java:163)

testTimeBasedWindowExpiry(backtype.storm.windowing.WindowManagerTest)  Time elapsed: 0.16 sec  <<< FAILURE!

java.lang.AssertionError: expected:<[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]> but was:<[]>

    at org.junit.Assert.fail(Assert.java:88)

    at org.junit.Assert.failNotEquals(Assert.java:743)

    at org.junit.Assert.assertEquals(Assert.java:118)

    at org.junit.Assert.assertEquals(Assert.java:144)

    at backtype.storm.windowing.WindowManagerTest.testTimeBasedWindowExpiry(WindowManagerTest.java:199)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1374" target="_blank">Random test failures on WindowManagerTest</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-12-09T01:16:20+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtask of parent task STORM-915

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan" class="user-hover" rel="arunmahadevan">Arun Mahadevan</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-comment">// add more events with past ts
</span><span class="code-keyword">for</span> (<span class="code-object">int</span> i : seq(WindowManager.EXPIRE_EVENTS_THRESHOLD + 1, WindowManager.EXPIRE_EVENTS_THRESHOLD + 100)) {
    windowManager.add(i, now - 1000);
}
<span class="code-comment">// wait <span class="code-keyword">for</span> time trigger
</span><span class="code-object">Thread</span>.sleep(120);

<span class="code-comment">// 100 events with past ts should expire
</span>assertEquals(100, listener.onExpiryEvents.size());
</pre>
</div></div>

<p>I think trigger could be called two times in 120 milliseconds, which first one has the events which are actually we want, and second one resets it, which makes test failed.<br/>
What do you think?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1374" title="Random test failures on WindowManagerTest" class="issue-link" data-issue-key="STORM-1374"><del>STORM-1374</del></a> fix random failure on WindowManagerTest</p>

<ul>
	<li>Problem: Trigger could be called two times while sleeping</li>
	<li>which first one has the events which are actually we want</li>
	<li>and second one resets it, which makes test failed</li>
	<li>Solution: Trigger manually</li>
	<li>and remove sleep if not necessary</li>
</ul>


<p>    @arunmahadevan Please verify this shouldn't break your intention on WindowManagerTest.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1374" title="Random test failures on WindowManagerTest" class="issue-link" data-issue-key="STORM-1374"><del>STORM-1374</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/925.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #925</p>

<hr />
<p>commit 98c90f0fa583e2932c2c8639e9ec483915c47ff1<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2015-12-04T23:03:22Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1374" title="Random test failures on WindowManagerTest" class="issue-link" data-issue-key="STORM-1374"><del>STORM-1374</del></a> fix random failure on WindowManagerTest</p>

<ul>
	<li>Problem: Trigger could be called two times while sleeping</li>
	<li>which first one has the events which are actually we want</li>
	<li>and second one resets it, which makes test failed</li>
	<li>Solution: Trigger manually</li>
	<li>and remove sleep if not necessary</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user arunmahadevan commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925#issuecomment-162242973" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925#issuecomment-162242973</a></p>

<p>    @HeartSaVioR thanks for providing the patch. I had overlooked the edge cases where the TimeTrigger might not fire or fires twice causing tests to fail.<br/>
    The patch you have provided addresses the issue. Only concern is that the existing TimeEvictionPolicy uses System.currentTimeMillis() to evict the events so it relies on the passage of time to expire events and if you manually invoke the trigger, the expected events may not expire.</p>

<p>    However I verified that the tests pass with your changes so it can be merged to fix the random test failures.</p>

<p>    In <a href="https://github.com/apache/storm/pull/900" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/900</a> an api is added to set the reference timestamp for the eviction policy instead of it relying on system timestamp. With that PR I will fix the unit tests by setting the future timestamp to simulate passage of time and invoke the trigger manually.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925#issuecomment-162321885" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925#issuecomment-162321885</a></p>

<p>    @arunmahadevan <br/>
    Yes, actually I don't remove sleep at some places since we still need to wait for eviction though we trigger manually.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user arunmahadevan commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925#issuecomment-162341005" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925#issuecomment-162341005</a></p>

<p>    @HeartSaVioR so I think it will cause trigger to fire two times (during sleep and then manually). For the current test cases it does not matter so your patch would work.</p>

<p>    I updated the unit tests as a part of PR#900 to not rely on sleep and trigger manually.<br/>
    <a href="https://github.com/apache/storm/pull/900/files#diff-04ed7847355c5e160efb25a9a5dc8a25R157" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/900/files#diff-04ed7847355c5e160efb25a9a5dc8a25R157</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925#issuecomment-162381755" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925#issuecomment-162381755</a></p>

<p>    @arunmahadevan <br/>
    Yes, it requires changing of trigger policy to never fire.<br/>
    I'll take a look at #900 and discard this PR when #900 covers this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925#issuecomment-162637158" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925#issuecomment-162637158</a></p>

<p>    #900 is a change of much larger scope, and looking at it just now, there are two other new problems preventing tests passing successfully.  Would it be better to merge this in ahead of #900, given that it is a change of much smaller scope, rather than making the test fix wait on other unrelated changes?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user arunmahadevan commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925#issuecomment-162642091" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925#issuecomment-162642091</a></p>

<p>    @d2r this can get merged. <br/>
    I have fixed the issues as a part of PR#900 and will resolve the conflicts once this gets merged.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925#issuecomment-163046082" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925#issuecomment-163046082</a></p>

<p>    +1 this looks god to me.  Could someone also file a JIRA to use simulated time instead of sleeping for these tests.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/925#issuecomment-163072586" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925#issuecomment-163072586</a></p>

<p>    @revans2 <br/>
    Seems like #900 already got it. @arunmahadevan removes all places which calls Thread.sleep().<br/>
    Btw, we may want to take some time to review #900 since it is not small patch, so though #900 now covers #925, I think we'd better to get #925 merged.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/925" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/925</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Merged to master.</p>
