### ISSUE TITLE
[STORM-1375] Blobstore broke Pacemaker

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5210]
<p>When using the new Pacemaker (which, you kind of have to, cos the alternative of not using it is abusing ZK to the point of deadlocking it...), you cannot submit topologies because <em>submitTopology</em> is calling ClusterState's <em>delete_node_blobstore</em> which never got implemented in <em>pacemaker_state_factory.clj</em>.</p>

<p>Here's a nice stack trace:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2015-12-05 07:07:21 b.s.d.nimbus [WARN] Topology submission exception. (topology name='cron-ba161de') #error {
 :cause org.apache.storm.pacemaker.pacemaker_state_factory$_mkState$reify__3956.delete_node_blobstore(Ljava/lang/String;Ljava/lang/String;)V
 :via
 [{:type java.lang.AbstractMethodError
   :message org.apache.storm.pacemaker.pacemaker_state_factory$_mkState$reify__3956.delete_node_blobstore(Ljava/lang/String;Ljava/lang/String;)V
   :at [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]}]
 :trace
 [[sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
  [java.lang.reflect.Method invoke Method.java 497]
  [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
  [clojure.lang.Reflector invokeInstanceMethod Reflector.java 28]
  [backtype.storm.cluster$mk_storm_cluster_state$reify__3846 setup_blobstore_BANG_ cluster.clj 345]
  [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
  [java.lang.reflect.Method invoke Method.java 497]
  [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
  [clojure.lang.Reflector invokeInstanceMethod Reflector.java 28]
  [backtype.storm.daemon.nimbus$setup_storm_code invoke nimbus.clj 467]
  [backtype.storm.daemon.nimbus$fn__7774$exec_fn__2579__auto__$reify__7803 submitTopologyWithOpts nimbus.clj 1523]
  [backtype.storm.generated.Nimbus$Processor$submitTopologyWithOpts getResult Nimbus.java 2940]
  [backtype.storm.generated.Nimbus$Processor$submitTopologyWithOpts getResult Nimbus.java 2924]
  [org.apache.thrift7.ProcessFunction process ProcessFunction.java 39]
  [org.apache.thrift7.TBaseProcessor process TBaseProcessor.java 39]
  [backtype.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor process SimpleTransportPlugin.java 158]
  [org.apache.thrift7.server.AbstractNonblockingServer$FrameBuffer invoke AbstractNonblockingServer.java 518]
  [org.apache.thrift7.server.Invocation run Invocation.java 18]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}
2015-12-05 07:07:21 o.a.t.s.AbstractNonblockingServer$FrameBuffer [ERROR] Unexpected throwable while invoking!
java.lang.AbstractMethodError: org.apache.storm.pacemaker.pacemaker_state_factory$_mkState$reify__3956.delete_node_blobstore(Ljava/lang/String;Ljava/lang/String;)V
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
  at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
  at backtype.storm.cluster$mk_storm_cluster_state$reify__3846.setup_blobstore_BANG_(cluster.clj:345)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
  at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
  at backtype.storm.daemon.nimbus$setup_storm_code.invoke(nimbus.clj:467)
  at backtype.storm.daemon.nimbus$fn__7774$exec_fn__2579__auto__$reify__7803.submitTopologyWithOpts(nimbus.clj:1523)
  at backtype.storm.generated.Nimbus$Processor$submitTopologyWithOpts.getResult(Nimbus.java:2940)
  at backtype.storm.generated.Nimbus$Processor$submitTopologyWithOpts.getResult(Nimbus.java:2924)
  at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:39)
  at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:39)
  at backtype.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)
  at org.apache.thrift7.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)
  at org.apache.thrift7.server.Invocation.run(Invocation.java:18)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Michael Schonfeld" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=BaconSeason">BaconSeason</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1375" target="_blank">Blobstore broke Pacemaker</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ilya Ostrovskiy" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iostat">iostat</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-12-07T13:56:29+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user redsanket commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162259989" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162259989</a></p>

<p>    +1 NB</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user iostat commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162525572" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162525572</a></p>

<p>    ugh, seems like github wants to hold on to the previous 3 commits, so now I have 5 commits <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/>. Worth just reopening this PR, or do any of you know a trick for this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user schonfeld commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162526706" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162526706</a></p>

<p>    I suppose you could just reset the branch to master, copy/paste the change, and force push to this branch</p>

<p>    > On Dec 7, 2015, at 08:32, Ilya Ostrovskiy <notifications@github.com> wrote:<br/>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user iostat commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162527130" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162527130</a></p>

<p>    alright there we go.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162529152" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162529152</a></p>

<p>    Thanks for the update. +1 again.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/926" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user iostat commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162530017" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162530017</a></p>

<p>    Cool. Thanks for the merge!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iostat" class="user-hover" rel="iostat">Ilya Ostrovskiy</a>, I merged into master.</p>
