### ISSUE TITLE
[STORM-1378] Windows File Handling Issues with Blobstore

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5213]
<p>Since the Blobstore merge to master (7029ae), several tests show consistent issues with file system interaction on Windows.</p>

<p>I first noticed it as several of these in backtype.storm.multilang-test.test-python:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">30970 [<span class="code-object">Thread</span>-8] ERROR b.s.event - Error when processing event

java.io.IOException: Unable to delete file: C:\Users\cburgess\AppData\Local\Temp\6d2e5448-3710-44c0-8e0a-8bfef14d065d\supervisor\tmp\fcc042a9-ddf4-498d-9114-a29626429310\stormconf.ser
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.moveDirectory(FileUtils.java:2756) ~[commons-io-2.4.jar:2.4]
	at backtype.storm.daemon.supervisor$fn__2392.invoke(supervisor.clj:1134) ~[classes/:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:243) ~[clojure-1.7.0.jar:?]
	at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__2118.invoke(supervisor.clj:565) ~[classes/:?]
	at backtype.storm.event$event_manager$fn__5761.invoke(event.clj:40) [classes/:?]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:744) [?:1.7.0_45]
</pre>
</div></div>

<p>When running a full test build, the LocalizerTest and BlobStoreTest cases stop the build due to Windows file interaction errors:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Failed tests:
  LocalizerTest.testDirPaths:147 get local user dir doesn't <span class="code-keyword">return</span> right value expected:<...c5-8a25-f0a888dc95e0[/usercache/]user1> but was:<...c5-8a25-f0a888dc95e0[\usercache\]user1>
Tests in error:
backtype.storm.blobstore.BlobStoreTest.testBasicLocalFs(backtype.storm.blobstore.BlobStoreTest)
  Run 1: BlobStoreTest.testBasicLocalFs:164->testBasic:313 ╗ <span class="code-object">Runtime</span> java.nio.file.Dire...
  Run 2: BlobStoreTest.cleanup:74 ╗ IO Unable to delete file: \tmp\blob-store-test-0a66...

  BlobStoreTest.cleanup:74 ╗ IO Unable to delete file: \tmp\blob-store-test-9ada...
backtype.storm.blobstore.BlobStoreTest.testLocalFsWithAuth(backtype.storm.blobstore.BlobStoreTest)
  Run 1: BlobStoreTest.testLocalFsWithAuth:159->testWithAuthentication:227 ╗ <span class="code-object">Runtime</span> ja...
  Run 2: BlobStoreTest.cleanup:74 ╗ IO Unable to delete file: \tmp\blob-store-test-594f...

backtype.storm.blobstore.BlobStoreTest.testMultipleLocalFs(backtype.storm.blobstore.BlobStoreTest)
  Run 1: BlobStoreTest.testMultipleLocalFs:169->testMultiple:398 ╗ AccessDenied C:\tmp\...
  Run 2: BlobStoreTest.cleanup:74 ╗ IO Unable to delete file: \tmp\blob-store-test-5356...

  LocalizerTest.testArchivesJar:260->testArchives:286 ╗ IO Error getting blobs
  LocalizerTest.testArchivesTar:254->testArchives:286 ╗ IO Error getting blobs
backtype.storm.localizer.LocalizerTest.testArchivesTarGz(backtype.storm.localizer.LocalizerTest)
  Run 1: LocalizerTest.testArchivesTarGz:248->testArchives:286 ╗ IO Error getting blobs
  Run 2: LocalizerTest.tearDown:125 ╗ IO Unable to delete file: \tmp\blob-store-localiz...

backtype.storm.localizer.LocalizerTest.testArchivesTgz(backtype.storm.localizer.LocalizerTest)
  Run 1: LocalizerTest.testArchivesTgz:236->testArchives:286 ╗ IO Error getting blobs
  Run 2: LocalizerTest.tearDown:125 ╗ IO Unable to delete file: \tmp\blob-store-localiz...

  LocalizerTest.testArchivesZip:242->testArchives:286 ╗ IO Error getting blobs
  LocalizerTest.testBasic:363 ╗ IO Error getting blobs
  LocalizerTest.testMultipleKeysOneUser:435 ╗ IO Error getting blobs
  LocalizerTest.testMultipleUsers:563 ╗ IO Error getting blobs
  LocalizerTest.testUpdate:637 ╗ IO Error getting blobs

Tests run: 95, Failures: 1, Errors: 13, Skipped: 0
</pre>
</div></div>

<p>Most of these are also due to "Unable to delete file".  They also all seem to be regarding stormconf.ser.</p>

<p>Is it possible that some process/thread that created these stormconf.ser files has not released/closed their own file interactions before the storm code tries to delete them?</p>

<p>Because 7029ae looks to be the entire feature squashed into one commit, I cannot bisect any deeper.</p>

---
<details><summary><i>Originally reported by <a title="Chuck Burgess" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashnazg">ashnazg</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1378" target="_blank">Windows File Handling Issues with Blobstore</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Chuck Burgess" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashnazg">ashnazg</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-12-10T17:31:24+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user ashnazg opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/928" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/928</a></p>

<p>    Use File.separator for OS independence in Blobstore LocalizerTest</p>

<p>    This clears up one incidental issue shown on <a href="https://issues.apache.org/jira/browse/STORM-1378" title="Windows File Handling Issues with Blobstore" class="issue-link" data-issue-key="STORM-1378"><del>STORM-1378</del></a>, the one test failure due solely to "/" vs "\" in the path comparison.  This does <em>not</em> solve the larger issue on <a href="https://issues.apache.org/jira/browse/STORM-1378" title="Windows File Handling Issues with Blobstore" class="issue-link" data-issue-key="STORM-1378"><del>STORM-1378</del></a>.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/ashnazg/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/ashnazg/storm</a> fileSep</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/928.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/928.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #928</p>

<hr />
<p>commit 8e7a6f227cdaeb166f743ed931df8d2508f31de1<br/>
Author: Chuck Burgess <cburgess@progressrail.com><br/>
Date:   2015-12-07T21:39:57Z</p>

<p>    use File.separator for OS independence;</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashnazg">ashnazg</a>:</i>
<p>PR #928 solves the one failure that's shown (due solely to "/" vs "\" in the path comparison), but it does not address the main issue of this JIRA.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanket991">sanket991</a>:</i>
<p>readBlobTo in BlobStore.java does not close the output stream before the move is performed inside the supervisor code. I suspect that might fix the problem. It would be great if you can test for it</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashnazg">ashnazg</a>:</i>
<p>@sanket991 good eye, though that didn't solve it.</p>

<p>A large part of these failures is the Windows symlink issue with Adminstrators group (<a href="http://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7" class="external-link" target="_blank" rel="nofollow noopener">http://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7</a>)</p>

<p>At best, my PR clears up the incidental failures due to OS path slashes and testcase cleanup failures.  The symlink issue cannot be solved.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ashnazg commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/928#issuecomment-163412824" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/928#issuecomment-163412824</a></p>

<p>    These last additions are the best that can be done.  The symlink issue can't be solved (see JIRA).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/928#issuecomment-163675116" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/928#issuecomment-163675116</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/928" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/928</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ashnazg" class="user-hover" rel="ashnazg">Chuck Burgess</a>,</p>

<p>I merged this into master.</p>
