### ISSUE TITLE
[STORM-1384] util [INFO] Halting process

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5219]
<p>i'm using storm-0.8.2 with zookeeper-3.4.7 <br/>
i submitted topology but i got in the supervisor log file <br/>
still hasn't start <br/>
and in the worker log file <br/>
<span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
org.zeromq.ZMQException: Address already in use(0x62)<br/>
	at org.zeromq.ZMQ$Socket.bind(Native Method)<br/>
	at zilch.mq$bind.invoke(mq.clj:69)<br/>
	at backtype.storm.messaging.zmq.ZMQContext.bind(zmq.clj:57)<br/>
	at backtype.storm.messaging.loader$launch_receive_thread_BANG_$fn__1629.invoke(loader.clj:26)<br/>
	at backtype.storm.util$async_loop$fn__465.invoke(util.clj:375)<br/>
	at clojure.lang.AFn.run(AFn.java:24)<br/>
	at java.lang.Thread.run(Thread.java:701)<br/>
2015-12-10 00:43:01 util <span class="error">&#91;INFO&#93;</span> Halting process: </p>

<p>i tried to use another version like storm-0.9.5 but got in the worker that it cannot bind port 6703 </p>

<p>how can i fix it ? </p>

---
<details><summary><i>Originally reported by <a title="beginner" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beginner1">beginner1</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1384" target="_blank">util [INFO] Halting process</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="beginner" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beginner1">beginner1</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:21+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>We may try to check whether the port is used by other processes on the node, e.g., "lsof -i :6703".</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beginner1">beginner1</a>:</i>
<p>i checked it and got <br/>
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME<br/>
java    5124 user   71u  IPv4  37584      0t0  TCP *:6703 (LISTEN)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>Can we further run a "ps aux |grep 5124" to check what this process is doing?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beginner1">beginner1</a>:</i>
<p>i got this <br/>
user      5124  7.4  2.7 3444276 109680 pts/9  Sl+  00:31   7:55 java -server -Djava.net.preferIPv4Stack=true -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dlogfile.name=worker-6703.log -Dstorm.home=/home/user/storm-0.8.2 -Dlog4j.configuration=storm.log.properties -cp /home/user/storm-0.8.2/storm-0.8.2.jar:/home/user/storm-0.8.2/lib/commons-exec-1.1.jar:/home/user/storm-0.8.2/lib/carbonite-1.5.0.jar:/home/user/storm-0.8.2/lib/ring-jetty-adapter-0.3.11.jar:/home/user/storm-0.8.2/lib/minlog-1.2.jar:/home/user/storm-0.8.2/lib/hiccup-0.3.6.jar:/home/user/storm-0.8.2/lib/commons-lang-2.5.jar:/home/user/storm-0.8.2/lib/math.numeric-tower-0.0.1.jar:/home/user/storm-0.8.2/lib/servlet-api-2.5-20081211.jar:/home/user/storm-0.8.2/lib/slf4j-log4j12-1.5.8.jar:/home/user/storm-0.8.2/lib/commons-logging-1.1.1.jar:/home/user/storm-0.8.2/lib/tools.logging-0.2.3.jar:/home/user/storm-0.8.2/lib/log4j-1.2.16.jar:/home/user/storm-0.8.2/lib/clout-1.0.1.jar:/home/user/storm-0.8.2/lib/httpcore-4.1.jar:/home/user/storm-0.8.2/lib/servlet-api-2.5.jar:/home/user/storm-0.8.2/lib/objenesis-1.2.jar:/home/user/storm-0.8.2/lib/clojure-1.4.0.jar:/home/user/storm-0.8.2/lib/json-simple-1.1.jar:/home/user/storm-0.8.2/lib/First-Story-Detection-1.0-SNAPSHOT.jar:/home/user/storm-0.8.2/lib/httpclient-4.1.1.jar:/home/user/storm-0.8.2/lib/jzmq-2.1.0.jar:/home/user/storm-0.8.2/lib/core.incubator-0.1.0.jar:/home/user/storm-0.8.2/lib/junit-3.8.1.jar:/home/user/storm-0.8.2/lib/guava-13.0.jar:/home/user/storm-0.8.2/lib/jgrapht-0.8.3.jar:/home/user/storm-0.8.2/lib/commons-io-1.4.jar:/home/user/storm-0.8.2/lib/curator-framework-1.0.1.jar:/home/user/storm-0.8.2/lib/ring-servlet-0.3.11.jar:/home/user/storm-0.8.2/lib/tools.macro-0.1.0.jar:/home/user/storm-0.8.2/lib/asm-4.0.jar:/home/user/storm-0.8.2/lib/jetty-6.1.26.jar:/home/user/storm-0.8.2/lib/reflectasm-1.07-shaded.jar:/home/user/storm-0.8.2/lib/joda-time-2.0.jar:/home/user/storm-0.8.2/lib/jline-0.9.94.jar:/home/user/storm-0.8.2/lib/libthrift7-0.7.0.jar:/home/user/storm-0.8.2/lib/tools.cli-0.2.2.jar:/home/user/storm-0.8.2/lib/commons-fileupload-1.2.1.jar:/home/user/storm-0.8.2/lib/zookeeper-3.3.3.jar:/home/user/storm-0.8.2/lib/First-Story-Detection-1.0-SNAPSHOT-jar-with-dependencies.jar:/home/user/storm-0.8.2/lib/slf4j-api-1.5.8.jar:/home/user/storm-0.8.2/lib/kryo-2.17.jar:/home/user/storm-0.8.2/lib/compojure-1.1.3.jar:/home/user/storm-0.8.2/lib/curator-client-1.0.1.jar:/home/user/storm-0.8.2/lib/jetty-util-6.1.26.jar:/home/user/storm-0.8.2/lib/ring-core-1.1.5.jar:/home/user/storm-0.8.2/lib/snakeyaml-1.9.jar:/home/user/storm-0.8.2/lib/disruptor-2.10.1.jar:/home/user/storm-0.8.2/lib/commons-codec-1.4.jar:/home/user/storm-0.8.2/lib/clj-time-0.4.1.jar:/home/user/storm-0.8.2/log4j:/home/user/storm-0.8.2/conf:/home/user/storms/storm/supervisor/stormdist/fsd-1-1449700287/stormjar.jar backtype.storm.daemon.worker fsd-1-1449700287 6e4dc763-7eb0-4c24-9185-4c312dce7e8f 6703 f9ccebdf-b2cc-4734-a129-164afe1c2ad2<br/>
user      5844  0.0  0.0  16016  2268 pts/27   S+   02:18   0:00 grep --color=auto 5124</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>Can we do this: <br/>
a. Shutdown storm, check the port's usage again to make sure the port is not being used by other processes; <br/>
b. may also try profiling this with storm-0.9.5; <br/>
c. for storm-0.9.5, paste the stacktrace/error message from supervisor.log and/or worker log for the exception if available.<br/>
Thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beginner1">beginner1</a>:</i>
<p>thanks , i did number a and got nothing <br/>
for b how can i delete current version of storm ? <br/>
Thanks for your time <br/>
last point <br/>
i'm using ubuntu 14.04 and when i installed it i didn't made anything with network configuration just i put wire net <br/>
is there any configuration i should do it ? </p>

<p>and do you mind to get this project just to run it in your machine to ensure that the problem with me ? i'll appreciate that <br/>
i need to finish this project as soon as possible , this problem made me confusing </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beginner1">beginner1</a>:</i>
<p>this my storm.yaml <br/>
storm.zookeeper.servers:</p>
<ul class="alternate" type="square">
	<li>"127.0.0.1"<br/>
nimbus.host: "127.0.0.1"<br/>
storm.local.dir: /home/user/storms/storm<br/>
supervisor.childopts: "-Djava.net.preferIPv4Stack=true"<br/>
nimbus.childopts: "-Djava.net.preferIPv4Stack=true"<br/>
worker.childopts: "-Djava.net.preferIPv4Stack=true"<br/>
supervisor.slots.ports:</li>
	<li>6700</li>
	<li>6701</li>
	<li>6702</li>
	<li>6703<br/>
is there anything wrong here ? </li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>I do not find anything wrong with your configuration.<br/>
For a clean delete, you can "killall -9 java; rm -rf  /home/user/storms/storm;", and removing zookeeper data dir would be a plus.<br/>
I would suggest downloading the storm-0.9.5 release or 0.10 release, you can try extract and start storm with pure default<br/>
configuration (not editing conf/storm.yaml will still work as long as your zookeeper server is launched locally at port 2181).<br/>
I tried both releases on my machine with default setting, it works fine.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beginner1">beginner1</a>:</i>
<p>thanks but i tried before something and got strange problem </p>

<p>i installed storm-0.8.2 then deleted storm-0.8.2 folder to uninstall it and knew after that , it's wrong way <br/>
then install storm-0.9.5 and every time i run storm -0.9.5 . storm-0.8.2 folder recreated itself with empty !!</p>

<p>NOW <br/>
i reinstalled ubuntu again from scratch and installed storm-0.8.2 to run the project that coder used this version i think it should work fine with me but didn't !! </p>

<p>I need to know how can i uninstall storm-0.8.2 to install new version ?? <br/>
and project i have , has storm-0.8.2 in m2/repository should i delete it or what ? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>You can try deleting your whole m2 directory. From what I can see, if you download a binary version, you can install storm by simply extracting the zip file <a href="http://www.apache.org/dyn/closer.lua/storm/apache-storm-0.10.0/apache-storm-0.10.0.zip" class="external-link" target="_blank" rel="nofollow noopener">storm-0.10.0 </a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beginner1">beginner1</a>:</i>
<p>Thanks but I think you didn't got what I mean . I'm asking for delete<br/>
current version if storm to become ready for installing new version</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>Gotcha. Are you using apt-get to install storm? Then you may need to run apt-get remove to uninstall rather than removing the directory. Also make sure /etc/storm/conf/storm.yaml is deleted.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
