### ISSUE TITLE
[STORM-1404] Fix Mockito test failures in storm-kafka

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5239]
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.194 sec <<< FAILURE! - in storm.kafka.bolt.KafkaBoltTest

executeWithByteArrayKeyAndMessageAsync(storm.kafka.bolt.KafkaBoltTest)  Time elapsed: 3.526 sec  <<< FAILURE!

org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:

collector.ack(

    source: null:1, stream: , id: {}, [[B@29e2aabd, [B@603773c6]

);

-> at storm.kafka.bolt.KafkaBoltTest.executeWithByteArrayKeyAndMessageAsync(KafkaBoltTest.java:144)

However, there were other interactions with this mock:

-> at backtype.storm.task.OutputCollector.reportError(OutputCollector.java:223)

-> at backtype.storm.task.OutputCollector.fail(OutputCollector.java:218)

	at storm.kafka.bolt.KafkaBoltTest.executeWithByteArrayKeyAndMessageAsync(KafkaBoltTest.java:144)
</pre>
</div></div>

<p>Seen <a href="https://travis-ci.org/apache/storm/jobs/97734764#L352" class="external-link" target="_blank" rel="nofollow noopener">here</a></p>

<p>Not sure about how often this happens, but it is definitely not 100% of the time.</p>

---
<details><summary><i>Originally reported by <a title="Derek Dagit" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1404" target="_blank">Fix Mockito test failures in storm-kafka</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Haohui Mai" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wheat9">wheat9</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-01-11T15:15:02+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtask of parent task STORM-915

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It is not easy to track cause it doesn't leave any logs. Just calling reportError() doesn't help Travis CI.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user haohui opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/993" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/993</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1404" title="Fix Mockito test failures in storm-kafka" class="issue-link" data-issue-key="STORM-1404"><del>STORM-1404</del></a>. Mockito test failures in storm-kafka.</p>

<p>    This PR fixes the failed test reported in <a href="https://issues.apache.org/jira/browse/STORM-1404" title="Fix Mockito test failures in storm-kafka" class="issue-link" data-issue-key="STORM-1404"><del>STORM-1404</del></a>. It replaces the unreliable `Thread.sleep()` with comprehensive mocking to make sure the tests are reliable.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/haohui/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/haohui/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1404" title="Fix Mockito test failures in storm-kafka" class="issue-link" data-issue-key="STORM-1404"><del>STORM-1404</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/993.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/993.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #993</p>

<hr />
<p>commit de90b185c4976522562dc6f161ed88dbedd2a0fa<br/>
Author: Haohui Mai <wheat9@apache.org><br/>
Date:   2016-01-07T02:04:13Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1404" title="Fix Mockito test failures in storm-kafka" class="issue-link" data-issue-key="STORM-1404"><del>STORM-1404</del></a>. Mockito test failures in storm-kafka.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/993#issuecomment-169539886" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/993#issuecomment-169539886</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user haohui commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/993#issuecomment-170099926" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/993#issuecomment-170099926</a></p>

<p>    The test passed locally. Committing.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user haohui commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/993#issuecomment-170101211" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/993#issuecomment-170101211</a></p>

<p>    Merged in 1f1ba77be849e50cdc09fcfe08dcec8f4984b4f9</p>
