### ISSUE TITLE
[STORM-1432] Spurious failure in storm-kafka test

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5267]
<p>ExponentialBackoffMsgRetryManagerTest.testMaxBackoff() fails sometimes, I think due to too small times. It can miss the mark on slow machines.</p>

---
<details><summary><i>Originally reported by <a title="Kyle Nusbaum" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=knusbaum">knusbaum</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1432" target="_blank">Spurious failure in storm-kafka test</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kyle Nusbaum" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=knusbaum">knusbaum</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-01-11T17:03:13+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user knusbaum opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/990" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/990</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1432" title="Spurious failure in storm-kafka test" class="issue-link" data-issue-key="STORM-1432"><del>STORM-1432</del></a>: Spurious failure in storm-kafka test</p>

<p>    ExponentialBackoffMsgRetryManagerTest.testMaxBackoff() fails sometimes, I think due to too small times. It can miss the mark on slow machines.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/knusbaum/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/knusbaum/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1432" title="Spurious failure in storm-kafka test" class="issue-link" data-issue-key="STORM-1432"><del>STORM-1432</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/990.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/990.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #990</p>

<hr />
<p>commit 6712e8d7e4cf48e045eb0d46187291296d99a1f2<br/>
Author: Kyle Nusbaum <kylejnusbaum@gmail.com><br/>
Date:   2016-01-05T18:22:23Z</p>

<p>    Fixing <a href="https://issues.apache.org/jira/browse/STORM-1432" title="Spurious failure in storm-kafka test" class="issue-link" data-issue-key="STORM-1432"><del>STORM-1432</del></a></p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/990#issuecomment-169091553" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/990#issuecomment-169091553</a></p>

<p>    I'm not sure that this fixed it.</p>

<p>    ```Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.696 sec <<< FAILURE! - in storm.kafka.ExponentialBackoffMsgRetryManagerTest<br/>
    testSingleDelay(storm.kafka.ExponentialBackoffMsgRetryManagerTest)  Time elapsed: 0.001 sec  <<< FAILURE!<br/>
    java.lang.AssertionError: expect no message ready for retry yet expected null, but was:<101><br/>
    	at org.junit.Assert.fail(Assert.java:88)<br/>
    	at org.junit.Assert.failNotNull(Assert.java:664)<br/>
    	at org.junit.Assert.assertNull(Assert.java:646)<br/>
    	at storm.kafka.ExponentialBackoffMsgRetryManagerTest.testSingleDelay(ExponentialBackoffMsgRetryManagerTest.java:57)<br/>
    ```</p>

<p>    From the travis CI JDK8 build.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/990#issuecomment-169098388" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/990#issuecomment-169098388</a></p>

<p>    @revans2 I'll keep testing.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/990#issuecomment-169098913" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/990#issuecomment-169098913</a></p>

<p>    That looks like a different test entirely that has the same problem. I'll try to fix that one as well.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/990#issuecomment-170585765" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/990#issuecomment-170585765</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/990" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/990</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=knusbaum" class="user-hover" rel="knusbaum">Kyle Nusbaum</a>,</p>

<p>I merged this into master.</p>
