### ISSUE TITLE
[STORM-1441] Random test failure on nimbus-auth-test

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5276]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Running backtype.storm.security.auth.nimbus-auth-test
63484 [pool-937-thread-1-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
63485 [main] INFO  b.s.d.nimbus - Shutting down master
63487 [main] INFO  b.s.zookeeper - closing zookeeper connection of leader elector.
63489 [main] INFO  b.s.d.nimbus - Shut down master
63490 [pool-937-thread-1] INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting
63495 [main] INFO  b.s.testing - Shutting down in process zookeeper
63499 [main] INFO  b.s.testing - Done shutting down in process zookeeper
63499 [main] INFO  b.s.testing - Deleting temporary path /tmp/7268ca66-4258-407e-8920-33e611eed59b
63500 [main] INFO  b.s.testing - Deleting temporary path /tmp/c486768a-2c3d-4db3-8711-23770759444a
63774 [main] INFO  b.s.d.nimbus - Shutting down master
63825 [main] INFO  b.s.zookeeper - closing zookeeper connection of leader elector.
63827 [pool-957-thread-1-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
63828 [main] INFO  b.s.d.nimbus - Shut down master
63828 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000] WARN  o.a.z.s.NIOServerCnxn - caught end of stream exception
org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x151a5a7ecc20000, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_31]
63856 [main] INFO  b.s.testing - Shutting down in process zookeeper
63857 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2000] WARN  o.a.z.s.NIOServerCnxnFactory - Ignoring unexpected runtime exception
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73) ~[?:1.8.0_31]
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87) ~[?:1.8.0_31]
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:187) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_31]
63862 [SyncThread:0] ERROR o.a.z.s.NIOServerCnxn - Unexpected Exception: 
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73) ~[?:1.8.0_31]
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77) ~[?:1.8.0_31]
	at org.apache.zookeeper.server.NIOServerCnxn.sendBuffer(NIOServerCnxn.java:151) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.NIOServerCnxn.sendResponse(NIOServerCnxn.java:1081) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.FinalRequestProcessor.processRequest(FinalRequestProcessor.java:404) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.SyncRequestProcessor.flush(SyncRequestProcessor.java:200) [zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.server.SyncRequestProcessor.run(SyncRequestProcessor.java:131) [zookeeper-3.4.6.jar:3.4.6-1569965]
63864 [main] INFO  b.s.testing - Done shutting down in process zookeeper
63864 [main] INFO  b.s.testing - Deleting temporary path /tmp/4ff1e17c-3996-422d-822d-d15fa28a08c8
63865 [main] INFO  b.s.testing - Deleting temporary path /tmp/1efc1124-61de-4a8f-a4a6-d0d1ac0b64f6
Tests run: 5, Passed: 37, Failures: 2, Errors: 0
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1441" target="_blank">Random test failure on nimbus-auth-test</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2018-02-01T11:12:15+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtask of parent task STORM-915

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>We don't see similar issue recently. Closing.</p>
