### ISSUE TITLE
[STORM-1448] How to return objects in declare output fields

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5283]
<p>I was working on twitter data using kafka-storm. I was using deserialize method to parse the twitter data using storm spout , here in parser I was facing a problem of returning all the objects. What I have done is I added them in a list and returned the list. Up to that it's working fine but, while coming to getOutputFields() it showing runtime error i.e., </p>

<p>ERROR : java.lang.IllegalArgumentException: Tuple created with wrong number of fields. Expected 6 fields but got 140 fields at backtype.storm.tuple.TupleImpl.<init>(TupleImpl.java:58) at backtype.storm.daemon.executor$fn_5624$fn5639$send_spout_msg5658.invoke(executor.clj:529) at backtype.storm.daemon.executor$fn5624$fn$reify5668.emit(executor.clj:568) at backtype.storm.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:49) at backtype.storm.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:63) at storm.kafka.PartitionManager.next(PartitionManager.java:141) at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:141) at backtype.storm.daemon.executor$fn5624$fn5639$fn5670.invoke(executor.clj:607) at backtype.storm.util$async_loop$fn_545.invoke(util.clj:479) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745) </p>

<p>I was returning 6 objects but it showing that its getting 60 fields . How to solve that ? Can anyone suggest me the solution ?<br/>
Below is the program which I am working on .</p>

<p>Program : </p>

<p>package Demo;</p>

<p>import java.sql.Timestamp;<br/>
import java.text.DateFormat;<br/>
import java.text.SimpleDateFormat;<br/>
import java.util.Date;<br/>
import java.io.IOException;<br/>
import java.util.Properties;<br/>
import java.util.*;<br/>
import twitter4j.JSONArray;<br/>
import twitter4j.JSONObject;<br/>
import twitter4j.JSONObjectType;<br/>
import java.io.UnsupportedEncodingException;<br/>
import backtype.storm.spout.Scheme;<br/>
import backtype.storm.spout.RawScheme;<br/>
import backtype.storm.spout.SpoutOutputCollector;<br/>
import backtype.storm.task.TopologyContext;<br/>
import backtype.storm.topology.OutputFieldsDeclarer;<br/>
import backtype.storm.topology.base.BaseRichSpout;<br/>
import backtype.storm.tuple.Fields;<br/>
import backtype.storm.tuple.Values;</p>

<p>public class TwitterTweet implements Scheme{</p>

<p>	//twitter_tweets fields</p>

<p>	String created_at;<br/>
	String id;<br/>
	String id_str;<br/>
	String text;<br/>
	String source;<br/>
	String truncated;</p>

<p>	int i=0;int j=0;</p>

<p>	@Override<br/>
	public List<Object> deserialize(final byte[] bytes) {</p>

<p>		List<Object> list = new ArrayList<Object>() {<br/>
			{<br/>
	try{<br/>
		String twitterEvent = new String(bytes, "UTF-8");</p>

<p>	 JSONArray JSON = new JSONArray(twitterEvent); // kafka topic name(twitterEvent)<br/>
     	for(i=0;i<JSON.length();i++)<br/>
{<br/>
    JSONObject object_tweet=JSON.getJSONObject<img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/information.png" height="16" width="16" align="absmiddle" alt="" border="0"/>;</p>

<p>   	//Tweet status 		 		</p>

<p>		try</p>
{

	 	add(created_at=object_tweet.getString("created_at"));
	 	add(id=object_tweet.getString("id"));
		add(id_str=object_tweet.getString("id_str"));
		add(text=object_tweet.getString("text"));
		add(source=object_tweet.getString("source"));
		add(truncated=object_tweet.getString("truncated"));
		
			}
<p>catch(Exception e){}</p>

<p>		}//JSON main_array for close</p>

<p>	}catch(Exception e){} // UTF- try close</p>

<p>	}<br/>
	};</p>

<p>return list;</p>

<p>     } //deserialize method close</p>

<p>public Fields getOutputFields() </p>
{
	return new Fields ("created_at","id","id_str","text","source","truncated");

		}
<p> // getOutputFields() method close</p>

<p>	}  //class close</p>

---
<details><summary><i>Originally reported by <a title="Jayasree" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Jayasree">Jayasree</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1448" target="_blank">How to return objects in declare output fields</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:10+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
