### ISSUE TITLE
[STORM-1453] nimbus.clj/wait-for-desired-code-replication print wrong log message

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5288]
<p><a href="https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/nimbus.clj#L516" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/nimbus.clj#L516</a></p>

---
<details><summary><i>Originally reported by <a title="caofangkun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1453" target="_blank">nimbus.clj/wait-for-desired-code-replication print wrong log message</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="caofangkun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caofangkun">caofangkun</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Trivial
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-01-13T17:28:47+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user caofangkun opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/996" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/996</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1453" title="nimbus.clj/wait-for-desired-code-replication print wrong log message" class="issue-link" data-issue-key="STORM-1453"><del>STORM-1453</del></a> nimbus.clj/wait-for-desired-code-replication print wrong log message</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/caofangkun/apache-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/caofangkun/apache-storm</a> storm-1453</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/996.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/996.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #996</p>

<hr />
<p>commit ed25dfda1f47a6fffcaea681f0a395f274ff1bf6<br/>
Author: ablecao <ablecao@tencent.com><br/>
Date:   2016-01-08T08:56:58Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1453" title="nimbus.clj/wait-for-desired-code-replication print wrong log message" class="issue-link" data-issue-key="STORM-1453"><del>STORM-1453</del></a> nimbus.clj/wait-for-desired-code-replication print wrong log message</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/996#issuecomment-170039698" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/996#issuecomment-170039698</a></p>

<p>    Test failures are the same, and they look unrelated.  We may want a new Jira created under <a href="https://issues.apache.org/jira/browse/STORM-915" title="Track and resolve any further random tests failure" class="issue-link" data-issue-key="STORM-915"><del>STORM-915</del></a>(<a href="https://issues.apache.org/jira/browse/STORM-915" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-915</a>).</p>

<p>    ```<br/>
    Running storm.kafka.bolt.KafkaBoltTest<br/>
    Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.346 sec <<< FAILURE! - in storm.kafka.bolt.KafkaBoltTest<br/>
    executeWithByteArrayKeyAndMessageFire(storm.kafka.bolt.KafkaBoltTest)  Time elapsed: 1.71 sec  <<< ERROR!<br/>
    storm.kafka.TopicOffsetOutOfRangeException: Partition</p>
{host=localhost:59874, topic=test-topic, partition=0}
<p> Got fetch request with offset out of range: <span class="error">&#91;-1&#93;</span><br/>
    	at storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:203)<br/>
    	at storm.kafka.bolt.KafkaBoltTest.verifyMessage(KafkaBoltTest.java:275)<br/>
    	at storm.kafka.bolt.KafkaBoltTest.executeWithByteArrayKeyAndMessageFire(KafkaBoltTest.java:188)<br/>
    ```</p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/996#issuecomment-170584316" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/996#issuecomment-170584316</a></p>

<p>    +1, but this needs to be upmerged.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user caofangkun opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1003" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1003</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1453" title="nimbus.clj/wait-for-desired-code-replication print wrong log message" class="issue-link" data-issue-key="STORM-1453"><del>STORM-1453</del></a> nimbus.clj/wait-for-desired-code-replication print wrong log message</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/caofangkun/apache-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/caofangkun/apache-storm</a> storm-1453-1</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1003.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1003.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1003</p>

<hr />
<p>commit 64a57a39fe1d4b0a1f3d15a264eb3335d72e1af6<br/>
Author: ablecao <ablecao@tencent.com><br/>
Date:   2016-01-12T01:38:41Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1453" title="nimbus.clj/wait-for-desired-code-replication print wrong log message" class="issue-link" data-issue-key="STORM-1453"><del>STORM-1453</del></a> nimbus.clj/wait-for-desired-code-replication print wrong log message</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user caofangkun commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/996#issuecomment-170755067" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/996#issuecomment-170755067</a></p>

<p>    Updated as PR #1003 </p>

<p>    Close this PR .</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user caofangkun closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/996" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/996</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1003#issuecomment-170937719" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1003#issuecomment-170937719</a></p>

<p>    I thought I merged this in, but I guess I messed something up with the merger.  +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1003#issuecomment-171045749" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1003#issuecomment-171045749</a></p>

<p>    @revans2 looks like this was originally #996, which had the requisite +1s, but needed an upmerge. I think @caofangkun just opened a new pull request and closed #996.</p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user haohui commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1003#issuecomment-171078363" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1003#issuecomment-171078363</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1003" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1003</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Merged to master/1.x-branch.</p>
