### ISSUE TITLE
[STORM-1454] UI cannot handle topology names with spaces

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5289]
<p>If I submit a topology with an name that contains spaces (eg, "Linear Road Benchmark", I cannot access the detailed topology view. If I click on the topology name in the Web UI, I get the following:</p>

<p>Internal Server Error</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>NotAliveException(msg:Linear+Road+Benchmark-3-1452252242)
	at backtype.storm.generated.Nimbus$getTopologyInfo_result.read(Nimbus.java:11347)
	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78)
	at backtype.storm.generated.Nimbus$Client.recv_getTopologyInfo(Nimbus.java:491)
	at backtype.storm.generated.Nimbus$Client.getTopologyInfo(Nimbus.java:478)
	at backtype.storm.ui.core$topology_page.invoke(core.clj:628)
	at backtype.storm.ui.core$fn__8020.invoke(core.clj:853)
	at compojure.core$make_route$fn__6199.invoke(core.clj:93)
	at compojure.core$if_route$fn__6187.invoke(core.clj:39)
	at compojure.core$if_method$fn__6180.invoke(core.clj:24)
	at compojure.core$routing$fn__6205.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2443)
	at compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:619)
	at compojure.core$routes$fn__6209.invoke(core.clj:111)
	at ring.middleware.reload$wrap_reload$fn__6234.invoke(reload.clj:14)
	at backtype.storm.ui.core$catch_errors$fn__8059.invoke(core.clj:909)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__6876.invoke(keyword_params.clj:27)
	at ring.middleware.nested_params$wrap_nested_params$fn__6915.invoke(nested_params.clj:65)
	at ring.middleware.params$wrap_params$fn__6848.invoke(params.clj:55)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__6943.invoke(multipart_params.clj:103)
	at ring.middleware.flash$wrap_flash$fn__7124.invoke(flash.clj:14)
	at ring.middleware.session$wrap_session$fn__7113.invoke(session.clj:43)
	at ring.middleware.cookies$wrap_cookies$fn__7044.invoke(cookies.clj:160)
	at ring.adapter.jetty$proxy_handler$fn__7324.invoke(jetty.clj:16)
	at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
</pre>
</div></div>

<p>The link says: <a href="http://dbis71:8080/topology.html?id=Linear+Road+Benchmark-5-1452255348" class="external-link" target="_blank" rel="nofollow noopener">http://dbis71:8080/topology.html?id=Linear+Road+Benchmark-5-1452255348</a><br/>
If I replace the "+" with spaces manually I can access the page. However, I cannot "kill" the topology &#8211; a click on "kill" has no effect.</p>

---
<details><summary><i>Originally reported by <a title="Matthias J. Sax" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mjsax">mjsax</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1454" target="_blank">UI cannot handle topology names with spaces</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:12+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
