### ISSUE TITLE
[STORM-1470] org.apache.hadoop:hadoop-auth not shaded, breaks spnego authentication

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5305]
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2016-01-12 20:07:45.642 o.a.s.s.o.e.j.s.ServletHandler [WARN] Error for /favicon.ico
java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64
at org.apache.hadoop.security.authentication.server.KerberosAuthenticationHandler.authenticate(KerberosAuthenticationHandler.java:343)
at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:519)
at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)
at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
at java.lang.Thread.run(Thread.java:745)
</pre>
</div></div>

<p>We already shade commons-codec:commons-codec, but we don't apply that shading to org.apache.hadoop:hadoop-auth.</p>

---
<details><summary><i>Originally reported by <a title="Derek Dagit" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1470" target="_blank">org.apache.hadoop:hadoop-auth not shaded, breaks spnego authentication</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Derek Dagit" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dagit">dagit</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-01-15T17:01:40+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user d2r opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1010" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1010</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1470" title="org.apache.hadoop:hadoop-auth not shaded, breaks spnego authentication" class="issue-link" data-issue-key="STORM-1470"><del>STORM-1470</del></a> Applies shading to hadoop-auth, cleaner exclusions</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/d2r/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/d2r/storm</a> storm-1470-hadoop-auth-shade-master</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1010.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1010.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1010</p>

<hr />
<p>commit 70197332bba46ffd2b38da183e835bd370a68e70<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2016-01-13T17:26:10Z</p>

<p>    Applies shading to hadoop-auth, cleaner exclusions</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user d2r opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1011" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1011</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1470" title="org.apache.hadoop:hadoop-auth not shaded, breaks spnego authentication" class="issue-link" data-issue-key="STORM-1470"><del>STORM-1470</del></a> Applies shading to hadoop-auth, cleaner exclusions</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/d2r/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/d2r/storm</a> storm-1470-hadoop-auth-shade-1.x</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1011.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1011.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1011</p>

<hr />
<p>commit 57021116d1399108acd17d22ab94962d82516177<br/>
Author: Derek Dagit <derekd@yahoo-inc.com><br/>
Date:   2016-01-13T17:26:10Z</p>

<p>    Applies shading to hadoop-auth, cleaner exclusions</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1010#issuecomment-171780642" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1010#issuecomment-171780642</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1011#issuecomment-171796975" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1011#issuecomment-171796975</a></p>

<p>    Personally, I don't think we need separate pull requests for each branch yet (master and 1.x have not diverged enough to cause conflicts), as it kind of confuses things in terms of +1s and comments. It might be easier to add a note requesting that it also be applied to another branch, e.g. "I would also like to see this applied to the X branch."</p>

<p>    If for some reason the patch couldn't be applied to the other branch(es), the committer doing the merge could either resolve the conflicts or request an additional pull request against the conflicted branch.</p>

<p>    Thoughts?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1011#issuecomment-171802477" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1011#issuecomment-171802477</a></p>

<p>    See #1010</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1011" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1011</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1010" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1010</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Merged to master/1.x-branch.</p>
