### ISSUE TITLE
[STORM-1495] Topology visualization is broken

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5330]
<p>Clicking the show visualization button results in a stacktracke:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">org.apache.storm.thrift.transport.TTransportException
	at org.apache.storm.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.storm.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.storm.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
	at org.apache.storm.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.storm.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
	at org.apache.storm.generated.Nimbus$Client.recv_getTopology(Nimbus.java:1333)
	at org.apache.storm.generated.Nimbus$Client.getTopology(Nimbus.java:1320)
	at org.apache.storm.ui.core$build_visualization.invoke(core.clj:491)
	at org.apache.storm.ui.core$fn__12083.invoke(core.clj:972)
	at org.apache.storm.shade.compojure.core$make_route$fn__2468.invoke(core.clj:93)
	at org.apache.storm.shade.compojure.core$if_route$fn__2456.invoke(core.clj:39)
	at org.apache.storm.shade.compojure.core$if_method$fn__2449.invoke(core.clj:24)
	at org.apache.storm.shade.compojure.core$routing$fn__2474.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2570)
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at org.apache.storm.shade.compojure.core$routes$fn__2478.invoke(core.clj:111)
	at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__11535.invoke(json.clj:56)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__3544.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__4287.invoke(reload.clj:22)
	at org.apache.storm.ui.helpers$requests_middleware$fn__3771.invoke(helpers.clj:46)
	at org.apache.storm.ui.core$catch_errors$fn__12255.invoke(core.clj:1230)
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__3475.invoke(keyword_params.clj:27)
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__3515.invoke(nested_params.clj:65)
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__3446.invoke(params.clj:55)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__3544.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__3730.invoke(flash.clj:14)
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__3718.invoke(session.clj:43)
	at org.apache.storm.shade.ring.middleware.cookies$wrap_cookies$fn__3646.invoke(cookies.clj:160)
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__3352.invoke(servlet.clj:127)
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__3356.invoke(servlet.clj:136)
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
	at org.apache.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:47)
	at org.apache.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:39)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1495" target="_blank">Topology visualization is broken</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Sanket Reddy" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanket991">sanket991</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-01-25T23:28:47+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It may be related to <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a> since I was seen stack trace logs in <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a> when clicking 'Topology Visualization' button.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Confirmed that fix for <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a> (<a href="https://github.com/apache/storm/pull/1035" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1035</a>) also fixes misfunction of 'Topology Visualization'.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Also resolved via <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a><br/>
(check once more to see <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a> can resolve <a href="https://issues.apache.org/jira/browse/STORM-1495" title="Topology visualization is broken" class="issue-link" data-issue-key="STORM-1495"><del>STORM-1495</del></a>)</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1491%20label%3Aepic">STORM-1491</a>]</i>
