### ISSUE TITLE
[STORM-1496] Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5331]
<p>Blobstore periodically throws exception:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-01-22 16:13:21.205 o.a.s.d.nimbus [INFO] Created download session <span class="code-keyword">for</span> wordcount-3-1453497194-stormjar.jar with id 0d84a3e1-e4c9-46fc-b0c7-8f02f48fb016
2016-01-22 16:13:21.499 o.a.s.d.nimbus [INFO] Created download session <span class="code-keyword">for</span> wordcount-3-1453497194-stormcode.ser with id c33cbb90-92a1-4191-8ac0-24b2547503da
2016-01-22 16:13:21.503 o.a.s.d.nimbus [INFO] Created download session <span class="code-keyword">for</span> wordcount-3-1453497194-stormconf.ser with id ac1ba1ce-5697-4490-84eb-2c74b6415d62
2016-01-22 16:15:19.509 o.a.s.t.s.AbstractNonblockingServer$FrameBuffer [ERROR] Unexpected throwable <span class="code-keyword">while</span> invoking!
java.lang.IllegalArgumentException: No matching method found: readBlob <span class="code-keyword">for</span> <span class="code-keyword">class </span>java.lang.<span class="code-object">String</span>
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:53)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at org.apache.storm.daemon.nimbus$read_storm_topology_as_nimbus.invoke(nimbus.clj:529)
	at org.apache.storm.daemon.nimbus$try_read_storm_topology.invoke(nimbus.clj:1249)
	at org.apache.storm.daemon.nimbus$fn__7312$exec_fn__1827__auto__$reify__7341.getTopology(nimbus.clj:1776)
	at org.apache.storm.generated.Nimbus$Processor$getTopology.getResult(Nimbus.java:3878)
	at org.apache.storm.generated.Nimbus$Processor$getTopology.getResult(Nimbus.java:3862)
	at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)
	at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)
	at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

<p>Steps to reproduce:</p>

<p>1. Setup one node cluster.<br/>
2. Deploy word count topology.<br/>
3. Kill word count topology.<br/>
4. Monitor nimbus.log</p>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1496" target="_blank">Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Sanket Reddy" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanket991">sanket991</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-01-25T23:15:41+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user redsanket opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1035" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1035</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a> Nimbus periodically throws blobstore-related exception</p>

<p>    I would like to have this merged in the master as well</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/redsanket/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/redsanket/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1035.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1035.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1035</p>

<hr />
<p>commit 4a440b59890a87c7fbbd0dba66a9f52392448e26<br/>
Author: Sanket <schintap@untilservice-lm><br/>
Date:   2016-01-22T23:04:36Z</p>

<p>    sporadic failures in blobstore <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a></p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1035#issuecomment-174358485" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1035#issuecomment-174358485</a></p>

<p>    +1 Confirmed that blobstore-related error log from nimbus.log are gone. Also it fixes misfunction of 'Topology Visualization'.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1035#issuecomment-174359536" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1035#issuecomment-174359536</a></p>

<p>    @redsanket <br/>
    Could you create a pull request which targets to master? It is easier to merge & backport.<br/>
    Thanks for quick fix!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user redsanket commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1035#issuecomment-174549834" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1035#issuecomment-174549834</a></p>

<p>    @HeartSaVioR yes I agree, that would be better, I am closing it now and will create a PR for master</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user redsanket closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1035" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1035</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user redsanket opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1042" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1042</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a> Nimbus periodically throws blobstore-related exception</p>

<p>    Can backport to 1.x-branch</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/redsanket/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/redsanket/storm</a> BLOBSTORE-<a href="https://issues.apache.org/jira/browse/STORM-1496" title="Nimbus periodically throws blobstore-related exception: No matching method found: readBlob for class java.lang.String" class="issue-link" data-issue-key="STORM-1496"><del>STORM-1496</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1042.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1042.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1042</p>

<hr />
<p>commit bddd0db945baf4752c7cae9cf707fcd1616db38d<br/>
Author: Sanket <schintap@untilservice-lm><br/>
Date:   2016-01-25T16:37:19Z</p>

<p>    fixing sporadic nimbus log failure and topology visualization</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1042#issuecomment-174576378" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1042#issuecomment-174576378</a></p>

<p>    +1 pending screwdriver</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user redsanket commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1042#issuecomment-174636013" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1042#issuecomment-174636013</a></p>

<p>    @HeartSaVioR - Put a pull request against master as per the suggestion</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1042#issuecomment-174722414" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1042#issuecomment-174722414</a></p>

<p>    +1 </p>

<p>    I think we can merge now cause origin pull request (#1035) waits for 3 days, and now there're two committers' +1. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1042" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1042</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanket991" class="user-hover" rel="sanket991">Sanket Reddy</a> for the quick fix.<br/>
I merged to master and 1.x-branch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user satishd commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1042#issuecomment-174821689" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1042#issuecomment-174821689</a></p>

<p>    Verified that topology visualization works fine with this fix.</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1491%20label%3Aepic">STORM-1491</a>]</i>
