### ISSUE TITLE
[STORM-1515] LocalState corruption after hard reboot on Windows

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5350]
<p>After a hard reboot on windows I'm seeing <tt>LocalState</tt> files for the supervisor that contain a few hundred NULs, resulting in a <tt>StreamCorruptedException</tt> on deserialization and the supervisor failing to start.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2016-01-27T17:04:10.848-0700 b.s.d.supervisor [INFO] Starting supervisor with id 45b27917-4ca0-4d96-8727-914909e3ac47 at host jtorbiak-ws.nj.invidi.com
2016-01-27T17:04:11.673-0700 b.s.event [ERROR] Error when processing event
java.lang.RuntimeException: java.io.StreamCorruptedException: invalid stream header: 00000000
at backtype.storm.serialization.DefaultSerializationDelegate.deserialize(DefaultSerializationDelegate.java:56) ~[storm-core-0.9.4.jar:0.9.4]
at backtype.storm.utils.Utils.deserialize(Utils.java:89) ~[storm-core-0.9.4.jar:0.9.4]
at backtype.storm.utils.LocalState.deserializeLatestVersion(LocalState.java:65) ~[storm-core-0.9.4.jar:0.9.4]
at backtype.storm.utils.LocalState.snapshot(LocalState.java:47) ~[storm-core-0.9.4.jar:0.9.4]
at backtype.storm.utils.LocalState.get(LocalState.java:72) ~[storm-core-0.9.4.jar:0.9.4]
at backtype.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:234) ~[storm-core-0.9.4.jar:0.9.4]
at clojure.lang.AFn.applyToHelper(AFn.java:161) [clojure-1.5.1.jar:na]
at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
at clojure.core$apply.invoke(core.clj:619) ~[clojure-1.5.1.jar:na]
at clojure.core$partial$fn__4190.doInvoke(core.clj:2396) ~[clojure-1.5.1.jar:na]
at clojure.lang.RestFn.invoke(RestFn.java:397) ~[clojure-1.5.1.jar:na]
at backtype.storm.event$event_manager$fn__2809.invoke(event.clj:40) ~[storm-core-0.9.4.jar:0.9.4]
at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.io.StreamCorruptedException: invalid stream header: 00000000
at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806) ~[na:1.8.0_45]
at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299) ~[na:1.8.0_45]
at backtype.storm.serialization.DefaultSerializationDelegate.deserialize(DefaultSerializationDelegate.java:51) ~[storm-core-0.9.4.jar:0.9.4]
... 13 common frames omitted
2016-01-27T17:04:11.674-0700 b.s.util [ERROR] Halting process: ("Error when processing an event")
java.lang.RuntimeException: ("Error when processing an event")
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) [storm-core-0.9.4.jar:0.9.4]
at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
at backtype.storm.event$event_manager$fn__2809.invoke(event.clj:48) [storm-core-0.9.4.jar:0.9.4]
at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2016-01-27T17:04:11.695-0700 b.s.d.supervisor [INFO] Shutting down supervisor 45b27917-4ca0-4d96-8727-914909e3ac47
</pre>
</div></div>

<p>This is very similar to <a href="https://issues.apache.org/jira/browse/STORM-307" title="After host crash, supervisor is unable to restart itself" class="issue-link" data-issue-key="STORM-307"><del>STORM-307</del></a>, except the <tt>LocalState</tt> files contain NULs instead of being empty. I'm guessing this corruption type is specific to Windows.</p>

---
<details><summary><i>Originally reported by <a title="Jordan Torbiak" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=torbiak">torbiak</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1515" target="_blank">LocalState corruption after hard reboot on Windows</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Tim Frison" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=frison">frison</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-09-04T18:23:41+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user torbiak opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1067" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1067</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1515" title="LocalState corruption after hard reboot on Windows" class="issue-link" data-issue-key="STORM-1515"><del>STORM-1515</del></a>: Reset LocalState if corrupted after a hard reboot on Windows</p>

<p>    On Windows LocalState IO requests interrupted by a hard reboot can<br/>
    result in a file full of NULs, similar to the empty-file corruption seen in <a href="https://issues.apache.org/jira/browse/STORM-307" title="After host crash, supervisor is unable to restart itself" class="issue-link" data-issue-key="STORM-307"><del>STORM-307</del></a>.</p>

<p>    I've fixed this for 0.9.x first since I haven't upgraded to 0.10 yet. The fix for 0.10 will be slightly different due to the move to Thrift for LocalState serialization.</p>

<p>    It might be desirable to catch EOFException instead of checking serialized.length, since it could cover more cases of corruption, like a partially-written serialization stream.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/torbiak/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/torbiak/storm</a> 0.9.x-branch</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1067.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1067.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1067</p>

<hr />
<p>commit 69c90bdda052e68c18a2ecfe43c34999869aa144<br/>
Author: Jordan Torbiak <jtorbiak@invidi.com><br/>
Date:   2016-02-02T01:48:53Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1515" title="LocalState corruption after hard reboot on Windows" class="issue-link" data-issue-key="STORM-1515"><del>STORM-1515</del></a>: Reset LocalState if corrupted after a hard reboot on Windows</p>

<p>    On Windows LocalState IO requests interrupted by a hard reboot can<br/>
    result in a file full of NULs, similar to the empty-file corruption seen<br/>
    in <a href="https://issues.apache.org/jira/browse/STORM-307" title="After host crash, supervisor is unable to restart itself" class="issue-link" data-issue-key="STORM-307"><del>STORM-307</del></a>.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user frison commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1067#issuecomment-180625941" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1067#issuecomment-180625941</a></p>

<p>    I see no way that CI failed because of this commit.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1067#issuecomment-182554149" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1067#issuecomment-182554149</a></p>

<p>    The change looks fine to me, but we need to pull this into master, 1.x-branch and 0.10.x-branch before we can pull it into 0.9.x-branch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=torbiak">torbiak</a>:</i>
<p>I won't be able to work on it anytime soon.</p>
