### ISSUE TITLE
[STORM-1516] Topology workers are not getting killed when a topology is killed.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5351]
<p>When topology with timebased windowing bolts are killed, respective workers are not shutdown properly and they remain running. When you want to deploy a new topology, it throws with the below Exception as the earlier worker is not shutdown. This issue is not specific with this topology though.</p>

<p>2016-02-02 10:07:42.845 o.a.s.d.worker <span class="error">&#91;ERROR&#93;</span> Error on initialization of server mk-worker<br/>
org.apache.storm.shade.org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:6700<br/>
	at org.apache.storm.shade.org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.messaging.netty.Server.<init>(Server.java:101) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.messaging.netty.Context.bind(Context.java:67) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.daemon.worker$worker_data$fn__6329.invoke(worker.clj:265) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.util$assoc_apply_self.invoke(util.clj:934) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.daemon.worker$worker_data.invoke(worker.clj:262) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.daemon.worker$fn_<em>6627$exec_fn</em><em>2511</em><em>auto</em><em>$reify</em>_6629.run(worker.clj:605) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at java.security.AccessController.doPrivileged(Native Method) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at javax.security.auth.Subject.doAs(Subject.java:422) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at org.apache.storm.daemon.worker$fn_<em>6627$exec_fn</em><em>2511</em><em>auto</em>___6628.invoke(worker.clj:603) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:178) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.AFn.applyTo(AFn.java:144) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.core$apply.invoke(core.clj:630) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at org.apache.storm.daemon.worker$fn_<em>6627$mk_worker</em>_6722.doInvoke(worker.clj:577) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:512) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at org.apache.storm.daemon.worker$_main.invoke(worker.clj:764) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:165) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.AFn.applyTo(AFn.java:144) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at org.apache.storm.daemon.worker.main(Unknown Source) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
Caused by: java.net.BindException: Address already in use<br/>
	at sun.nio.ch.Net.bind0(Native Method) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at sun.nio.ch.Net.bind(Net.java:433) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at sun.nio.ch.Net.bind(Net.java:425) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
2016-02-02 10:07:42.857 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error on initialization")</p>

---
<details><summary><i>Originally reported by <a title="Satish Duggana" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1516" target="_blank">Topology workers are not getting killed when a topology is killed.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Satish Duggana" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-02-22T16:28:56+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>:</i>
<p>org.apache.storm.starter.SlidingWindowTopology can be used to reproduce this issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>:</i>
<p>Whenever a topology is submitted, it creates respective workers on supervisor/s. These worker pids are stored as files in ${storm-localdir}/workers/</p>
{worker-id}
<p>/pids/ on supervisor. But there is an issue in storing worker pids. So, supervisor could not find respective worker pids when a topology is killed. Subsequent topology deployment workers are failed because of earlier workers are still alive and bound to the respective ports. This issue occurs only on 2.0 branch. </p>

<p>The issue here is that worker.clj # mk-server has below bug.<br/>
(ConfigUtils/clusterMode conf) returns a string but it is compared with keyword which returns false, because of which pids are not stored. </p>

<p>  (when (= :distributed (ConfigUtils/clusterMode conf)) <br/>
    (let <span class="error">&#91;pid (process-pid)&#93;</span><br/>
      (touch (ConfigUtils/workerPidPath conf worker-id pid))<br/>
      (spit (ConfigUtils/workerArtifactsPidPath conf storm-id port) pid)))</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user satishd opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1516" title="Topology workers are not getting killed when a topology is killed." class="issue-link" data-issue-key="STORM-1516"><del>STORM-1516</del></a> Fixed issue in writing pids with distributed cluster mode.</p>

<p>    Whenever a topology is submitted, it creates respective workers on supervisor/s. These worker pids are stored as files in ${storm-localdir}/workers/</p>
{worker-id}
<p>/pids/ on supervisor. But there is an issue in storing worker pids. So, supervisor could not find respective worker pids when a topology is killed. Subsequent topology deployment workers are failed because of earlier workers are still alive and bound to the respective ports. </p>

<p>    Fixed worker.clj to have right checks while writing pids to respective locations.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/satishd/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/satishd/storm</a> storm-1516</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1084</p>

<hr />
<p>commit a27e5034b693b9a22b8e1226fec76232f6b6dffc<br/>
Author: Satish Duggana <sduggana@hortonworks.com><br/>
Date:   2016-02-05T12:15:43Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1516" title="Topology workers are not getting killed when a topology is killed." class="issue-link" data-issue-key="STORM-1516"><del>STORM-1516</del></a> Fixed issue in writing pids with distributed cluster mode.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#discussion_r52013516" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#discussion_r52013516</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/daemon/worker.clj &#8212;<br/>
    @@ -577,11 +577,11 @@<br/>
     (defserverfn mk-worker <span class="error">&#91;conf shared-mq-context storm-id assignment-id port worker-id&#93;</span><br/>
       (log-message "Launching worker for " storm-id " on " assignment-id ":" port " with id " worker-id<br/>
    " and conf " conf)</p>
<ul class="alternate" type="square">
	<li>(if-not (ConfigUtils/isLocalMode conf)</li>
	<li>(redirect-stdio-to-slf4j!))<br/>
       ;; because in local mode, its not a separate<br/>
       ;; process. supervisor will register it in this case</li>
	<li>(when (= :distributed (ConfigUtils/clusterMode conf))<br/>
    +  ;; if (ConfigUtils/isLocalMode conf) returns false then it is in distributed mode.<br/>
    +  (when-not (ConfigUtils/isLocalMode conf)
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    how is this different from checking state == "distributed"</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#discussion_r52015347" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#discussion_r52015347</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/daemon/worker.clj &#8212;<br/>
    @@ -577,11 +577,11 @@<br/>
     (defserverfn mk-worker <span class="error">&#91;conf shared-mq-context storm-id assignment-id port worker-id&#93;</span><br/>
       (log-message "Launching worker for " storm-id " on " assignment-id ":" port " with id " worker-id<br/>
    " and conf " conf)</p>
<ul class="alternate" type="square">
	<li>(if-not (ConfigUtils/isLocalMode conf)</li>
	<li>(redirect-stdio-to-slf4j!))<br/>
       ;; because in local mode, its not a separate<br/>
       ;; process. supervisor will register it in this case</li>
	<li>(when (= :distributed (ConfigUtils/clusterMode conf))<br/>
    +  ;; if (ConfigUtils/isLocalMode conf) returns false then it is in distributed mode.<br/>
    +  (when-not (ConfigUtils/isLocalMode conf)
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    <a href="https://issues.apache.org/jira/browse/STORM-1516?focusedCommentId=15134067&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15134067" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1516?focusedCommentId=15134067&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15134067</a></p>

<p>    Satish already explains why it occurs via JIRA comment.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#discussion_r52015690" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#discussion_r52015690</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/daemon/worker.clj &#8212;<br/>
    @@ -577,11 +577,11 @@<br/>
     (defserverfn mk-worker <span class="error">&#91;conf shared-mq-context storm-id assignment-id port worker-id&#93;</span><br/>
       (log-message "Launching worker for " storm-id " on " assignment-id ":" port " with id " worker-id<br/>
    " and conf " conf)</p>
<ul class="alternate" type="square">
	<li>(if-not (ConfigUtils/isLocalMode conf)</li>
	<li>(redirect-stdio-to-slf4j!))<br/>
       ;; because in local mode, its not a separate<br/>
       ;; process. supervisor will register it in this case</li>
	<li>(when (= :distributed (ConfigUtils/clusterMode conf))<br/>
    +  ;; if (ConfigUtils/isLocalMode conf) returns false then it is in distributed mode.<br/>
    +  (when-not (ConfigUtils/isLocalMode conf)
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Easy explanation: <br/>
    ```<br/>
    => (= :dist "dist")<br/>
    false<br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user arunmahadevan commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#issuecomment-180411794" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#issuecomment-180411794</a></p>

<p>    @satishd Is it happening with all topologies ? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#discussion_r52034936" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#discussion_r52034936</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/daemon/worker.clj &#8212;<br/>
    @@ -577,11 +577,11 @@<br/>
     (defserverfn mk-worker <span class="error">&#91;conf shared-mq-context storm-id assignment-id port worker-id&#93;</span><br/>
       (log-message "Launching worker for " storm-id " on " assignment-id ":" port " with id " worker-id<br/>
    " and conf " conf)</p>
<ul class="alternate" type="square">
	<li>(if-not (ConfigUtils/isLocalMode conf)</li>
	<li>(redirect-stdio-to-slf4j!))<br/>
       ;; because in local mode, its not a separate<br/>
       ;; process. supervisor will register it in this case</li>
	<li>(when (= :distributed (ConfigUtils/clusterMode conf))<br/>
    +  ;; if (ConfigUtils/isLocalMode conf) returns false then it is in distributed mode.<br/>
    +  (when-not (ConfigUtils/isLocalMode conf)
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Thanks @HeartSaVioR . Got it now. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user satishd commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#issuecomment-180478178" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#issuecomment-180478178</a></p>

<p>    @arunmahadevan Right, this issue happens with all topologies. There is nothing specific about the mentioned topology in JIRA.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user arunmahadevan commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#issuecomment-180695960" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#issuecomment-180695960</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#issuecomment-181484415" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#issuecomment-181484415</a></p>

<p>    The code looks fine to me, but for some reason nimbus-test is failing fairly consistently.  Also storm-hdfs is very unstable right now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#issuecomment-181485037" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#issuecomment-181485037</a></p>

<p>    I just did some poking around and it looks like these failures are likely unrelated.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Remove Epic since it affects only master, not 1.x.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#issuecomment-185018716" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#issuecomment-185018716</a></p>

<p>    @satishd can you upmerge this and also open another PR for 1.x-branch if we want this there as well. Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user satishd commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084#issuecomment-185038798" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084#issuecomment-185038798</a></p>

<p>    @harshach Upmerged and resolved conflicts. We do not need this on 1.x.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1084" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1084</a></p>
