### ISSUE TITLE
[STORM-1520] Nimbus Clojure/Zookeeper issue ("stateChanged" method not found)

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5355]
<p>Placeholder until I can gather more information for reproducing the issue.</p>

<p>The following appears in nimbus.log after deploying/undeploying topologies:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-02-02 21:34:04.308 o.a.s.s.o.a.c.f.l.ListenerContainer [ERROR] Listener (org.apache.storm.cluster_state.zookeeper_state_factory$_mkState$reify$reify__12660@22587507) threw an exception
java.lang.IllegalArgumentException: No matching method found: stateChanged <span class="code-keyword">for</span> <span class="code-keyword">class </span>org.apache.storm.cluster$mk_storm_cluster_state$reify$reify__6413
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:53)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at org.apache.storm.cluster_state.zookeeper_state_factory$_mkState$reify$reify__12660.stateChanged(zookeeper_state_factory.clj:145)
	at org.apache.storm.shade.org.apache.curator.framework.state.ConnectionStateManager$2.apply(ConnectionStateManager.java:259)
	at org.apache.storm.shade.org.apache.curator.framework.state.ConnectionStateManager$2.apply(ConnectionStateManager.java:255)
	at org.apache.storm.shade.org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:92)
	at org.apache.storm.shade.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at org.apache.storm.shade.org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84)
	at org.apache.storm.shade.org.apache.curator.framework.state.ConnectionStateManager.processEvents(ConnectionStateManager.java:253)
	at org.apache.storm.shade.org.apache.curator.framework.state.ConnectionStateManager.access$000(ConnectionStateManager.java:43)
	at org.apache.storm.shade.org.apache.curator.framework.state.ConnectionStateManager$1.call(ConnectionStateManager.java:111)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

<p><del>Basic functionality does not seem to be affected.</del></p>

<p>Nimbus becomes unresponsive and needs to be manually restarted.</p>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1520" target="_blank">Nimbus Clojure/Zookeeper issue ("stateChanged" method not found)</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-02-09T02:43:54+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Easy way to reproduce</p>

<p>with binary distribution version of Storm 1.0.0-SNAPSHOT</p>

<p>1. ./bin/storm dev-zookeeper<br/>
2. ./bin/storm nimbus<br/>
3. kill dev-zookeeper by pressing CTRL+C<br/>
4. confirm that nimbus.log prints stack trace like description stated</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1520" title="Nimbus Clojure/Zookeeper issue ("stateChanged" method not found)" class="issue-link" data-issue-key="STORM-1520"><del>STORM-1520</del></a> <span class="error">&#91;for master branch&#93;</span> Nimbus Clojure/Zookeeper issue ("stateChanged" method not found)</p>

<p>    Please take a look at the mapping between Curator ConnectionState and Storm ConnectionState.</p>

<p>    When pull request is merged, I'll craft the pull request which can be applied to 1.x-branch.<br/>
    (It would be nearly same to this pull request but I've seen small conflict since we ported ZK to Java.)</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1520" title="Nimbus Clojure/Zookeeper issue ("stateChanged" method not found)" class="issue-link" data-issue-key="STORM-1520"><del>STORM-1520</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1077</p>

<hr />
<p>commit 25f8b2af7ac007ca4da304e3e25813a4f0079af4<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2016-02-04T09:17:15Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1520" title="Nimbus Clojure/Zookeeper issue ("stateChanged" method not found)" class="issue-link" data-issue-key="STORM-1520"><del>STORM-1520</del></a> Nimbus Clojure/Zookeeper issue ("stateChanged" method not found)</p>

<ul>
	<li>fix a bug which passes wrong type of parameter to ClusterStateListener.stateChanged()</li>
	<li>we passed ConnectionState from Curator which method needs storm's ConnectionState</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Since this bug also affects master branch (2.x), I submitted a pull request for master.<br/>
Crafting pull request for 1.x-branch would be easy, so I'd like to let PR for master branch in reviewing first.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077#issuecomment-179939934" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077#issuecomment-179939934</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077#discussion_r51973468" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077#discussion_r51973468</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/cluster_state/zookeeper_state_factory.clj &#8212;<br/>
    @@ -144,7 +145,7 @@<br/>
    (let [curator-listener (reify ConnectionStateListener<br/>
     (stateChanged<br/>
       <span class="error">&#91;this client newState&#93;</span></p>
<ul class="alternate" type="square">
	<li>(.stateChanged listener client newState)))]<br/>
    +  (.stateChanged listener (StormConnectionStateConverter/convert newState))))]
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    In this line, listener is ClusterStateListener which was introduced to unify interfaces between Zookeeper and Pacemaker.</p>

<p>    Method signature of ClusterStateLister.stateChanged() is <br/>
    `void stateChanged(org.apache.storm.cluster.ConnectionState newState)`,<br/>
     while ConnectionStateListener.stateChanged() is <br/>
    `void stateChanged(org.apache.curator.framework.CuratorFramework client, org.apache.curator.framework.state.ConnectionState newState)`</p>

<p>    So it should remove client from parameter, and convert ConnectionState from Curator to ConnectionState from Storm.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077#issuecomment-180175739" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077#issuecomment-180175739</a></p>

<p>    Seems like I didn't explain why this occurs and how to fix. Explained inline.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user erikdw commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077#discussion_r51973554" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077#discussion_r51973554</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/cluster_state/zookeeper_state_factory.clj &#8212;<br/>
    @@ -144,7 +145,7 @@<br/>
    (let [curator-listener (reify ConnectionStateListener<br/>
     (stateChanged<br/>
       <span class="error">&#91;this client newState&#93;</span></p>
<ul class="alternate" type="square">
	<li>(.stateChanged listener client newState)))]<br/>
    +  (.stateChanged listener (StormConnectionStateConverter/convert newState))))]
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Nice explanation!  Helps a lot to have such "whys" explained out, thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077#discussion_r51978814" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077#discussion_r51978814</a></p>

<p>    &#8212; Diff: storm-core/src/clj/org/apache/storm/cluster_state/zookeeper_state_factory.clj &#8212;<br/>
    @@ -144,7 +145,7 @@<br/>
    (let [curator-listener (reify ConnectionStateListener<br/>
     (stateChanged<br/>
       <span class="error">&#91;this client newState&#93;</span></p>
<ul class="alternate" type="square">
	<li>(.stateChanged listener client newState)))]<br/>
    +  (.stateChanged listener (StormConnectionStateConverter/convert newState))))]
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Thanks for kind words. <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/> I hope that Storm will get rid of many kinds of type / signature / typo problems when ported to Java, static typed language.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077#issuecomment-181489256" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077#issuecomment-181489256</a></p>

<p>    +1 Nice clean fix.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1077#issuecomment-181676428" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1077#issuecomment-181676428</a></p>

<p>    It doesn't make any conflicts with 1.x-branch, so I merged to 1.x-branch without new pull request.<br/>
    Thanks all for the review! </p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1491%20label%3Aepic">STORM-1491</a>]</i>
