### ISSUE TITLE
[STORM-1525] Topology visualization causes integer overlfow error

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5360]
<p>We have seen the following exception when looking at topology visualization.  It looks like it was adding up the emitted tuples from a set of terminal bolts, so it should have been adding up a bunch of zeros.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.ArithmeticException: integer overflow
	at clojure.lang.Numbers.throwIntOverflow(Numbers.java:1424)
	at clojure.lang.Numbers.add(Numbers.java:1723)
	at clojure.lang.Numbers$LongOps.add(Numbers.java:447)
	at clojure.lang.Numbers.add(Numbers.java:126)
	at clojure.core$_PLUS_.invoke(core.clj:951)
	at clojure.core$merge_with$merge_entry__4318.invoke(core.clj:2773)
	at clojure.core$reduce1.invoke(core.clj:903)
	at clojure.core$merge_with$merge2__4320.invoke(core.clj:2776)
	at clojure.core$reduce1.invoke(core.clj:903)
	at clojure.core$reduce1.invoke(core.clj:894)
	at clojure.core$merge_with.doInvoke(core.clj:2777)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at backtype.storm.stats$aggregate_counts$fn__2726.invoke(stats.clj:1369)
	at clojure.core$merge_with$merge_entry__4318.invoke(core.clj:2773)
	at clojure.core$reduce1.invoke(core.clj:903)
	at clojure.core$merge_with$merge2__4320.invoke(core.clj:2776)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core$reduce1.invoke(core.clj:901)
	at clojure.core$reduce1.invoke(core.clj:894)
	at clojure.core$merge_with.doInvoke(core.clj:2777)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:626)
	at backtype.storm.stats$aggregate_counts.invoke(stats.clj:1366)
	at backtype.storm.stats$aggregate_common_stats.invoke(stats.clj:1373)
	at backtype.storm.stats$aggregate_bolt_stats.invoke(stats.clj:1379)
	at backtype.storm.stats$bolt_streams_stats.invoke(stats.clj:1470)
	at backtype.storm.ui.core$visualization_data$iter__10652__10656$fn__10657.invoke(core.clj:221)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2855)
	at clojure.core$doall.invoke(core.clj:2871)
	at backtype.storm.ui.core$visualization_data.invoke(core.clj:250)
	at backtype.storm.ui.core$build_visualization.invoke(core.clj:431)
	at backtype.storm.ui.core$fn__11091.invoke(core.clj:842)
	at org.apache.storm.shade.compojure.core$make_route$fn__8804.invoke(core.clj:93)
	at org.apache.storm.shade.compojure.core$if_route$fn__8792.invoke(core.clj:39)
	at org.apache.storm.shade.compojure.core$if_method$fn__8785.invoke(core.clj:24)
	at org.apache.storm.shade.compojure.core$routing$fn__8810.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2515)
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:626)
	at org.apache.storm.shade.compojure.core$routes$fn__8814.invoke(core.clj:111)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__9325.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__10128.invoke(reload.clj:22)
	at backtype.storm.ui.helpers$requests_middleware$fn__9522.invoke(helpers.clj:46)
	at backtype.storm.ui.core$catch_errors$fn__11228.invoke(core.clj:1072)
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__9258.invoke(keyword_params.clj:27)
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__9297.invoke(nested_params.clj:65)
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__9230.invoke(params.clj:55)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__9325.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__9506.invoke(flash.clj:14)
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__9495.invoke(session.clj:43)
	at org.apache.storm.shade.ring.middleware.cookies$wrap_cookies$fn__9426.invoke(cookies.clj:160)
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__9143.invoke(servlet.clj:127)
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__9147.invoke(servlet.clj:136)
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1317)
	at backtype.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:47)
	at backtype.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:39)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at yjava.servlet.FilterChainInvoker$ServletFilterChainInvoker.invoke(FilterChainInvoker.java:49)
	at yjava.servlet.filter.BouncerFilter.doFilter(BouncerFilter.java:231)
	at yjava.servlet.filter.BouncerFilter.doFilter(BouncerFilter.java:110)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Paul Poulosky" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ppoulosk">ppoulosk</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1525" target="_blank">Topology visualization causes integer overlfow error</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:04+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
