### ISSUE TITLE
[STORM-1533] topologies with metric consumers fail in config validation phase

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5368]
<p>Storm expects the parallelism hint to be long. When the yaml is read, parallelism hint is read as an integer, and topology submission fails. </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>,Exception in thread "main" java.lang.IllegalArgumentException: Field TOPOLOGY_METRICS_CONSUMER_REGISTER list entry must be of type class java.lang.Long. Object: 1 actual type: class java.lang.Integer
	at backtype.storm.validation.ConfigValidation$SimpleTypeValidator.validateField(ConfigValidation.java:90)
	at backtype.storm.validation.ConfigValidation$MetricRegistryValidator.validateField(ConfigValidation.java:476)
	at backtype.storm.validation.ConfigValidation$ListEntryCustomValidator.validateField(ConfigValidation.java:339)
	at backtype.storm.validation.ConfigValidation$ListEntryCustomValidator.validateField(ConfigValidation.java:323)
	at backtype.storm.validation.ConfigValidation.validateField(ConfigValidation.java:624)
	at backtype.storm.validation.ConfigValidation.validateFields(ConfigValidation.java:659)
	at backtype.storm.validation.ConfigValidation.validateFields(ConfigValidation.java:638)
	at backtype.storm.StormSubmitter.validateConfs(StormSubmitter.java:464)
	at backtype.storm.StormSubmitter.submit,TopologyAs(StormSubmitter.java:201)
	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:288)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Abhishek Agarwal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1533" target="_blank">topologies with metric consumers fail in config validation phase</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Abhishek Agarwal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-02-11T15:35:37+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user abhishekagarwal87 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1091" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1091</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1533" title="topologies with metric consumers fail in config validation phase" class="issue-link" data-issue-key="STORM-1533"><del>STORM-1533</del></a>: IntegerValidator for metric consumer parallelism hint</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/abhishekagarwal87/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/abhishekagarwal87/storm</a> release1</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1091.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1091.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1091</p>

<hr />
<p>commit f8ee7b892a8236bb7f2f11ec427549d3bf438169<br/>
Author: Abhishek Agarwal <abhishek.agarwal@inmobi.com><br/>
Date:   2016-02-09T15:53:07Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1534" title="Incompatible jackson dependencies are being packed in storm package" class="issue-link" data-issue-key="STORM-1534"><del>STORM-1534</del></a>: Pick correct version of jackson-annotations jar</p>

<p>commit 8fe6cf7dfbdaaae84e1272af0d4cf9292138da9e<br/>
Author: Abhishek Agarwal <abhishek.agarwal@inmobi.com><br/>
Date:   2016-02-09T15:53:51Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1533" title="topologies with metric consumers fail in config validation phase" class="issue-link" data-issue-key="STORM-1533"><del>STORM-1533</del></a>: IntegerValidator for metric consumer parallelism hint</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1091#issuecomment-182702569" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1091#issuecomment-182702569</a></p>

<p>    Thanks for review @knusbaum . This PR has fix for <a href="https://issues.apache.org/jira/browse/STORM-1533" title="topologies with metric consumers fail in config validation phase" class="issue-link" data-issue-key="STORM-1533"><del>STORM-1533</del></a> and <a href="https://issues.apache.org/jira/browse/STORM-1534" title="Incompatible jackson dependencies are being packed in storm package" class="issue-link" data-issue-key="STORM-1534"><del>STORM-1534</del></a>. Since commits have the individual JIRA ids attached, I have sent the fix in same PR. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1091#issuecomment-182892954" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1091#issuecomment-182892954</a></p>

<p>    +1 looks good to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1091#issuecomment-182900605" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1091#issuecomment-182900605</a></p>

<p>    Thanks @revans2 - can you also merge this PR? This affects 1.x release so it should be backported as well. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1091" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1091</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal" class="user-hover" rel="abhishek.agarwal">Abhishek Agarwal</a>,</p>

<p>I merged this into master and 1.x-branch</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1491%20label%3Aepic">STORM-1491</a>]</i>
