### ISSUE TITLE
[STORM-1534] Incompatible jackson dependencies are being packed in storm package

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5369]
<p>I see jackson-annotations-2.1.1.jar with  jackson-databind-2.6.3.jar. This is leading to exception in my application </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonProperty$Access
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.findAccess(POJOPropertyBuilder.java:542) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.removeNonVisible(POJOPropertyBuilder.java:623) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._removeUnwantedAccessor(POJOPropertiesCollector.java:697) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:298) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:169) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:222) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:355) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildMapSerializer(BasicSerializerFactory.java:771) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildContainerSerializer(BasicSerializerFactory.java:580) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:194) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:153) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1203) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1157) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:481) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:679) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:107) ~[jackson-databind-2.6.3.jar:2.6.3]
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3437) ~[jackson-databind-2.6.3.jar:2.6.3]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Abhishek Agarwal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1534" target="_blank">Incompatible jackson dependencies are being packed in storm package</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Abhishek Agarwal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-02-11T15:35:59+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal" class="user-hover" rel="abhishek.agarwal">Abhishek Agarwal</a>,</p>

<p>I merged this into master and 1.x-branch</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1491%20label%3Aepic">STORM-1491</a>]</i>
