### ISSUE TITLE
[STORM-1538] Exception being thrown after Utils conversion to java

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5373]
<p>1. TTransportException thrown when trying to visit topology page in UI:</p>

<p>When trying to access the topology page on the storm ui, exceptions are thrown.</p>

<p>Visiting a topology page displays a TTransportException.</p>

<p>The cause can be seen in nimbus.log:</p>

<p>java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.core$<em>PLUS</em><br/>
	at clojure.lang.RT.seqFrom(RT.java:528)<br/>
	at clojure.lang.RT.seq(RT.java:509)<br/>
	at clojure.core$seq__4128.invoke(core.clj:137)<br/>
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:26)<br/>
	at clojure.core.protocols$fn__6500.invoke(protocols.clj:83)<br/>
	at clojure.core.protocols$fn_<em>6452$G</em><em>6447</em>_6465.invoke(protocols.clj:13)<br/>
	at clojure.core$reduce.invoke(core.clj:6515)<br/>
	at org.apache.storm.stats$agg_pre_merge_topo_page_bolt.invoke(stats.clj:564)<br/>
	at org.apache.storm.stats$agg_topo_exec_stats_STAR_.invoke(stats.clj:744)<br/>
	at org.apache.storm.stats$fn__1257.invoke(stats.clj:792)<br/>
	at clojure.lang.MultiFn.invoke(MultiFn.java:243)<br/>
	at clojure.core$partial$fn__4529.invoke(core.clj:2501)<br/>
	at clojure.core.protocols$fn__6523.invoke(protocols.clj:167)<br/>
	at clojure.core.protocols$fn_<em>6478$G</em><em>6473</em>_6487.invoke(protocols.clj:19)<br/>
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)<br/>
	at clojure.core.protocols$fn__6506.invoke(protocols.clj:101)<br/>
	at clojure.core.protocols$fn_<em>6452$G</em><em>6447</em>_6465.invoke(protocols.clj:13)<br/>
	at clojure.core$reduce.invoke(core.clj:6519)<br/>
	at org.apache.storm.stats$aggregate_topo_stats.invoke(stats.clj:874)<br/>
	at org.apache.storm.stats$agg_topo_execs_stats.invoke(stats.clj:1037)<br/>
	at org.apache.storm.daemon.nimbus$fn_<em>4817$exec_fn</em><em>2064</em><em>auto</em><em>$reify</em>_4846.getTopologyPageInfo(nimbus.clj:2105)<br/>
	at org.apache.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3800)<br/>
	at org.apache.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3784)<br/>
	at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39)<br/>
	at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39)<br/>
	at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)<br/>
	at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)<br/>
	at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br/>
	at java.lang.Thread.run(Thread.java:745)</p>

<p>2. Exception thrown in supervisor: </p>

<p>java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String<br/>
	at org.apache.storm.daemon.supervisor$create_artifacts_link.invoke(supervisor.clj:1083)<br/>
	at org.apache.storm.daemon.supervisor$fn__7494.invoke(supervisor.clj:1180)<br/>
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)<br/>
	at org.apache.storm.daemon.supervisor$get_valid_new_worker_ids$iter_<em>7081</em><em>7085$fn</em>_7086.invoke(supervisor.clj:393)<br/>
	at clojure.lang.LazySeq.sval(LazySeq.java:40)<br/>
	at clojure.lang.LazySeq.seq(LazySeq.java:49)<br/>
	at clojure.lang.RT.seq(RT.java:507)<br/>
	at clojure.core$seq__4128.invoke(core.clj:137)<br/>
	at clojure.core$dorun.invoke(core.clj:3009)<br/>
	at clojure.core$doall.invoke(core.clj:3025)<br/>
	at org.apache.storm.daemon.supervisor$get_valid_new_worker_ids.invoke(supervisor.clj:380)<br/>
	at org.apache.storm.daemon.supervisor$sync_processes.invoke(supervisor.clj:447)<br/>
	at clojure.core$partial$fn__4527.invoke(core.clj:2492)<br/>
	at org.apache.storm.event$event_manager$fn__6781.invoke(event.clj:40)<br/>
	at clojure.lang.AFn.run(AFn.java:22)<br/>
	at java.lang.Thread.run(Thread.java:745)</p>

<p>3. Exception in UI:</p>

<p>java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number<br/>
	at org.apache.storm.ui.core$worker_log_link.invoke(core.clj:150)<br/>
	at org.apache.storm.ui.core$get_error_json.invoke(core.clj:531)<br/>
	at org.apache.storm.ui.core$fn__11747.invoke(core.clj:553)<br/>
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)<br/>
	at clojure.core$partial$fn__4529.invoke(core.clj:2500)<br/>
	at clojure.core$map$fn__4553.invoke(core.clj:2624)<br/>
	at clojure.lang.LazySeq.sval(LazySeq.java:40)<br/>
	at clojure.lang.LazySeq.seq(LazySeq.java:49)<br/>
	at clojure.lang.RT.seq(RT.java:507)<br/>
	at clojure.lang.SeqIterator.hasNext(SeqIterator.java:38)</p>

---
<details><summary><i>Originally reported by <a title="Boyang Jerry Peng" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jerrypeng">jerrypeng</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1538" target="_blank">Exception being thrown after Utils conversion to java</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kyle Nusbaum" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=knusbaum">knusbaum</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-02-12T17:27:41+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user knusbaum opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1099" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1099</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1538" title="Exception being thrown after Utils conversion to java" class="issue-link" data-issue-key="STORM-1538"><del>STORM-1538</del></a>: Exception being thrown after Utils conversion to java</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/knusbaum/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/knusbaum/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1538" title="Exception being thrown after Utils conversion to java" class="issue-link" data-issue-key="STORM-1538"><del>STORM-1538</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1099.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1099.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1099</p>

<hr />
<p>commit 747080e08af0bd46624e53264111cc3be1a0a74f<br/>
Author: Kyle Nusbaum <kylejnusbaum@gmail.com><br/>
Date:   2016-02-11T22:17:20Z</p>

<p>    Fixing Plus thingy.</p>

<p>commit d3d0a868069ff783ba25d9698ff4b9311e58d796<br/>
Author: Kyle Nusbaum <kylejnusbaum@gmail.com><br/>
Date:   2016-02-11T22:30:09Z</p>

<p>    Fixing other exceptions.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>What branches does this affect?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1099#issuecomment-183089890" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1099#issuecomment-183089890</a></p>

<p>    +1 pending Travis CI Build..</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1099" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1099</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jerrypeng" class="user-hover" rel="jerrypeng">Boyang Jerry Peng</a> Just a gentle reminder that pull requests should remain open for review for at least 24 hrs. after the last code change to allow others to review. Not a big deal for this one since it was somewhat minor and had a lot of committer support.</p>

<p>Also please try to remember to resolve the JIRA and set the fix version.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Merged to master.</p>
