### ISSUE TITLE
[STORM-1540] Topology Debug/Sampling Breaks Trident Topologies

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5375]
<p>Steps to reproduce:</p>

<p>1. Deploy a Trident topology.<br/>
2. Turn on debug/sampling.</p>

<p>Workers will crash with the following error:</p>

<p>2016-02-11 14:13:23.617 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
java.lang.RuntimeException: java.lang.RuntimeException: java.io.NotSerializableException: org.apache.storm.trident.tuple.ConsList<br/>
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:448) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:414) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.disruptor$consume_loop_STAR_$fn__7651.invoke(disruptor.clj:83) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.util$async_loop$fn__554.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_72&#93;</span><br/>
Caused by: java.lang.RuntimeException: java.io.NotSerializableException: org.apache.storm.trident.tuple.ConsList<br/>
	at org.apache.storm.serialization.SerializableSerializer.write(SerializableSerializer.java:41) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568) ~<span class="error">&#91;kryo-2.21.jar:?&#93;</span><br/>
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:75) ~<span class="error">&#91;kryo-2.21.jar:?&#93;</span><br/>
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:18) ~<span class="error">&#91;kryo-2.21.jar:?&#93;</span><br/>
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:486) ~<span class="error">&#91;kryo-2.21.jar:?&#93;</span><br/>
	at org.apache.storm.serialization.KryoValuesSerializer.serializeInto(KryoValuesSerializer.java:44) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.serialization.KryoTupleSerializer.serialize(KryoTupleSerializer.java:44) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.daemon.worker$mk_transfer_fn$transfer_fn__8346.invoke(worker.clj:186) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.daemon.executor$start_batch_transfer_<em>GT_worker_handler_BANG</em>$fn__8037.invoke(executor.clj:309) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.disruptor$clojure_handler$reify__7634.onEvent(disruptor.clj:40) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:435) ~<span class="error">&#91;storm-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT&#93;</span><br/>
	... 6 more</p>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1540" target="_blank">Topology Debug/Sampling Breaks Trident Topologies</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Arun Mahadevan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan">arunmahadevan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-02-25T23:36:18+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan">arunmahadevan</a>:</i>
<p>Actually this issue happens only when the trident tuples has to be transferred over the network (and has to be serialized). </p>

<p>To reproduce, I set numWorkers to '4' in TridentWordCount, topology.eventlogger.executors: 1 in storm.yaml, ran the topology and then turn on debug/sampling from UI.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user arunmahadevan opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1540" title="Topology Debug/Sampling Breaks Trident Topologies" class="issue-link" data-issue-key="STORM-1540"><del>STORM-1540</del></a> Fix Debug/Sampling for Trident</p>

<p>    When ConsList emitted by a trident spout has to be transferred over<br/>
    the network, it fails during Serialization. The proposed fix is to make ConsList<br/>
    kyro serializable.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/arunmahadevan/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/arunmahadevan/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1540" title="Topology Debug/Sampling Breaks Trident Topologies" class="issue-link" data-issue-key="STORM-1540"><del>STORM-1540</del></a>-new</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1112</p>

<hr />
<p>commit 0f0dea0b4d2b17d6e8dc32e82341b8aec70ef6e9<br/>
Author: Arun Mahadevan <aiyer@hortonworks.com><br/>
Date:   2016-02-16T10:25:25Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1540" title="Topology Debug/Sampling Breaks Trident Topologies" class="issue-link" data-issue-key="STORM-1540"><del>STORM-1540</del></a> Fix Debug/Sampling for Trident</p>

<p>    When ConsList emitted by a trident spout has to be transferred over<br/>
    the network, it fails during Serialization. The proposed fix is to make ConsList<br/>
    kyro serializable.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112#issuecomment-184703067" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112#issuecomment-184703067</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112#issuecomment-184703475" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112#issuecomment-184703475</a></p>

<p>    Could we look at turning on "topology.testing.always.try.serialize" for the thrift unit tests?  This config should have caught it without the need for multiple real workers.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ppoulosk commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112#issuecomment-184879965" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112#issuecomment-184879965</a></p>

<p>    +1, NB</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112#issuecomment-184905183" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112#issuecomment-184905183</a></p>

<p>    +0 at this time just because I'd like to do some additional testing and verification.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112#issuecomment-186371004" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112#issuecomment-186371004</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112#issuecomment-189022623" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112#issuecomment-189022623</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1112" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1112</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan" class="user-hover" rel="arunmahadevan">Arun Mahadevan</a>,<br/>
I merged into master and 1.x-branch respectively.</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1491%20label%3Aepic">STORM-1491</a>]</i>
