### ISSUE TITLE
[STORM-1545] Topology Debug Event Log in Wrong Location

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5380]
<p>Currently the <tt>events.log</tt> file is not created where the log viewer expects it so be, so the "events" link under debug in Storm UI returns a 404.</p>

<p>The file should be in:</p>

<p><tt>$storm.log.dir/workers-artifacts/$topology_id/$port/events.log</tt></p>

<p>but is instead in:</p>

<p><tt>$storm.local.dir/workers-artifacts/$topology_id/$port/events.log</tt></p>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1545" target="_blank">Topology Debug Event Log in Wrong Location</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Maciej Prochniak" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mproch">mproch</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-02-26T07:21:26+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user mproch opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123</a></p>

<p>    closes <a href="https://issues.apache.org/jira/browse/STORM-1545" title="Topology Debug Event Log in Wrong Location" class="issue-link" data-issue-key="STORM-1545"><del>STORM-1545</del></a></p>

<p>    Use ConfigUtils.workerArtifactsRoot to determine correct path</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/mproch/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/mproch/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1545" title="Topology Debug Event Log in Wrong Location" class="issue-link" data-issue-key="STORM-1545"><del>STORM-1545</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1123</p>

<hr />
<p>commit dca0e8476f5e55e5b8f8f064e9e47cfd8c3e27c5<br/>
Author: Maciek Próchniak <mpr@touk.pl><br/>
Date:   2016-02-18T18:16:12Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1545" title="Topology Debug Event Log in Wrong Location" class="issue-link" data-issue-key="STORM-1545"><del>STORM-1545</del></a></p>

<p>commit 02ae42ebe8e42da7a567c2a49309dd6ca4aa5155<br/>
Author: Maciek Próchniak <mpr@touk.pl><br/>
Date:   2016-02-18T18:32:18Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1545" title="Topology Debug Event Log in Wrong Location" class="issue-link" data-issue-key="STORM-1545"><del>STORM-1545</del></a> - more common code</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user arunmahadevan commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#discussion_r53427904" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#discussion_r53427904</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/org/apache/storm/metric/FileBasedEventLogger.java &#8212;<br/>
    @@ -79,26 +80,18 @@ public void run() {</p>

<p> @Override<br/>
 public void prepare(Map stormConf, TopologyContext context) {</p>
<ul class="alternate" type="square">
	<li>String logDir; // storm local directory<br/>
     String stormId = context.getStormId();<br/>
     int port = context.getThisWorkerPort();</li>
	<li>if ((logDir = System.getProperty("storm.local.dir")) == null &&</li>
	<li>(logDir = (String)stormConf.get("storm.local.dir")) == null) 
{
    -    String msg = "Could not determine the directory to log events.";
    -    LOG.error(msg);
    -    throw new RuntimeException(msg);
    -}
<p> else {</p></li>
	<li>LOG.info("FileBasedEventLogger log directory {}.", logDir);</li>
	<li>}<br/>
    +<br/>
    +String workersArtifactRoot = ConfigUtils.workerArtifactsRoot(stormConf, stormId, port);</li>
</ul>


<p>     /*</p>
<ul>
	<li>Include the topology name & worker port in the file name so that</li>
	<li>multiple event loggers can log independently.<br/>
      */</li>
</ul>
<ul class="alternate" type="square">
	<li>Path path = Paths.get(logDir, "workers-artifacts", stormId, Integer.toString(port), "events.log");<br/>
    +Path path = Paths.get(workersArtifactRoot, "events.log");<br/>
     if (!path.isAbsolute()) {
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    <span class="error">&#91;ConfigUtils&#93;</span>(<a href="https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/utils/ConfigUtils.java#L407" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/utils/ConfigUtils.java#L407</a>) appears to take care of the relative path, so this check could be removed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user arunmahadevan commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#issuecomment-186090463" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#issuecomment-186090463</a></p>

<p>    Can you update the PR title ?</p>

<p>    Theres a PR <a href="https://github.com/apache/storm/pull/1109" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1109</a> for the same issue but it does not make use of the ConfigUtils since it had to be merged to 1.x as well. Since this PR is a better fix for 2.0, I will close <a href="https://github.com/apache/storm/pull/1109" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1109</a> and raise that against 1.x-branch.</p>

<p>    +1 to merge against master (not 1.x-branch) once review comment is addressed. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user mproch commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#issuecomment-186895540" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#issuecomment-186895540</a></p>

<p>    I removed relative path handling and updated the title - hope this is what you meant?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user arunmahadevan commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#issuecomment-187022132" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#issuecomment-187022132</a></p>

<p>    When the unit tests are run it creates log files under /logs. It should ideally be under system tmp directory. </p>

<p>    Maybe unrelated, but when an example topology is submitted worker crashes with the below error,</p>

<p>    `2016-02-22 10:56:51.085 o.a.s.d.worker <span class="error">&#91;ERROR&#93;</span> Error on initialization of server mk-worker<br/>
    java.lang.ClassCastException: java.lang.String cannot be cast to java.io.File<br/>
      at org.apache.storm.daemon.worker$fn_<em>6265$exec_fn</em><em>1730</em><em>auto</em>___6266.invoke(worker.clj:622) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
      at clojure.lang.AFn.applyToHelper(AFn.java:178) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
      at clojure.lang.AFn.applyTo(AFn.java:144) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
      at clojure.core$apply.invoke(core.clj:630) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
      at org.apache.storm.daemon.worker$fn_<em>6265$mk_worker</em>_6362.doInvoke(worker.clj:613) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
      at clojure.lang.RestFn.invoke(RestFn.java:512) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
      at org.apache.storm.daemon.worker$_main.invoke(worker.clj:810) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
      at clojure.lang.AFn.applyToHelper(AFn.java:165) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
      at clojure.lang.AFn.applyTo(AFn.java:144) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
      at org.apache.storm.daemon.worker.main(Unknown Source) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span>`</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user satishd commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#issuecomment-187024988" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#issuecomment-187024988</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1566" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1566</a> is raised for the above issue. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#issuecomment-187033903" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#issuecomment-187033903</a></p>

<p>    Thanks @mproch Looks good to me (NB) for merge with master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#issuecomment-189065774" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#issuecomment-189065774</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Note: This issue is also fixed via <a href="https://issues.apache.org/jira/browse/STORM-1552" title="Fix topology event sampling log directory " class="issue-link" data-issue-key="STORM-1552"><del>STORM-1552</del></a> for 1.x-branch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#issuecomment-189074528" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#issuecomment-189074528</a></p>

<p>    @mproch <br/>
    Thanks for the work! I merged this into master.</p>

<p>    I'd like to also set assignee from JIRA issue to you but I couldn't find your name in Apache JIRA.<br/>
    If you have your account in JIRA, please do the followings,</p>

<ul class="alternate" type="square">
	<li>set assignee to yourself at <a href="https://issues.apache.org/jira/browse/STORM-1545" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1545</a></li>
	<li>resolve issue as 'resolved'</li>
	<li>set fix version/s to 2.0.0</li>
</ul>


<p>    Please let me know if you're not interested to do the things. I'll just assign assignee as reporter and resolve issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user mproch commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1123#issuecomment-189144444" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1123#issuecomment-189144444</a></p>

<p>    @HeartSaVioR <br/>
    thanks, I resolved jira issue.</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1491%20label%3Aepic">STORM-1491</a>]</i>
