### ISSUE TITLE
[STORM-1560] Topology stops processing after Netty catches/swallows Throwable

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5395]
<p>In some scenarios, netty connection problems can leave a topology in an unrecoverable state. The likely culprit is the Netty <tt>HashedWheelTimer</tt> class that contains the following code:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">public</span> void expire() {
    <span class="code-keyword">if</span>(<span class="code-keyword">this</span>.compareAndSetState(0, 2)) {
<span class="code-keyword">try</span> {
    <span class="code-keyword">this</span>.task.run(<span class="code-keyword">this</span>);
} <span class="code-keyword">catch</span> (Throwable var2) {
    <span class="code-keyword">if</span>(HashedWheelTimer.logger.isWarnEnabled()) {
HashedWheelTimer.logger.warn(<span class="code-quote">"An exception was thrown by "</span> + TimerTask.<span class="code-keyword">class.</span>getSimpleName() + <span class="code-quote">'.'</span>, var2);
    }
}
    }
}
</pre>
</div></div>

<p>The exception being swallowed can be seen below:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-02-18 08:46:59.116 o.a.s.m.n.Client [INFO] closing Netty Client Netty-Client-/192.168.202.6:6701
2016-02-18 08:46:59.173 o.a.s.m.n.Client [INFO] waiting up to 600000 ms to send 0 pending messages to Netty-Client-/192.168.202.6:6701
2016-02-18 08:46:59.271 STDIO [ERROR] Feb 18, 2016 8:46:59 AM org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer
WARNING: An exception was thrown by TimerTask.
java.lang.RuntimeException: Giving up to scheduleConnect to Netty-Client-/192.168.202.6:6701 after 44 failed attempts. 3 messages were lost
	at org.apache.storm.messaging.netty.Client$Connect.run(Client.java:573)
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:546)
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$Worker.notifyExpiredTimeouts(HashedWheelTimer.java:446)
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:395)
	at org.apache.storm.shade.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

<p>The netty client then never recovers, and the follows messages repeat forever:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-02-18 09:42:56.251 o.a.s.m.n.Client [ERROR] discarding 1 messages because the Netty client to Netty-Client-/192.168.202.6:6701 is being closed
2016-02-18 09:43:25.248 o.a.s.m.n.Client [ERROR] discarding 1 messages because the Netty client to Netty-Client-/192.168.202.6:6701 is being closed
2016-02-18 09:43:55.248 o.a.s.m.n.Client [ERROR] discarding 1 messages because the Netty client to Netty-Client-/192.168.202.6:6701 is being closed
2016-02-18 09:43:55.752 o.a.s.m.n.Client [ERROR] discarding 2 messages because the Netty client to Netty-Client-/192.168.202.6:6701 is being closed
2016-02-18 09:43:56.252 o.a.s.m.n.Client [ERROR] discarding 1 messages because the Netty client to Netty-Client-/192.168.202.6:6701 is being closed
2016-02-18 09:44:25.249 o.a.s.m.n.Client [ERROR] discarding 1 messages because the Netty client to Netty-Client-/192.168.202.6:6701 is being closed
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1560" target="_blank">Topology stops processing after Netty catches/swallows Throwable</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:01+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a> <br/>
Providing more log lines may be helpful to determine what things were occurred.<br/>
For example, is there any log messages "connection attempt %s to %s failed" before "closing Netty Client"?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Strange... Let's focus that Client seems to be closed but worker still call send() to that Client.<br/>
There're methods which closes the Client...</p>

<p>1.  mk-refresh-connection</p>

<p>mk-refresh-connection replaces cached-task->node+port first, and closes remove-connections, so send() shouldn't be called to that Client.</p>

<p>2. Context.term()</p>

<p>It means that worker is in progress of shutdown, so eventually send() shouldn't be called.</p>

<p>3. Connect.run()</p>

<p>Connect.run() only calls Client.close() when closing is true, which means that either 1 or 2 should occur before this one.</p>

<p>Please comment new paths here which I'm missing.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p>I also checked without any success. One possible cause could be context returning a stale value of client. (host-port --> connections) map inside the context class is not thread safe. There are synchronized blocks but they do not guarantee visibility consistency. <br/>
However, other than shutdown, I could not see any scenario wherein the put and get to this map is called from different thread. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Lowering priority to major and removing from 1.0 release epic since I (and others) are unable to reliably reproduce.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=huyl08">huyl08</a>:</i>
<p>Similar problem as following.</p>

<p>I got everything well when I ran topology in Eclipse LocalCluster. </p>

<p>I used Kafka Spout/StateUpdater in Trident State.</p>

<p>2016-03-29 16:40:36.461 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> connection attempt 12 to Netty-Client-bt-199-036.bta.net.cn/202.106.199.36:6702 failed: org.apache.storm.shade.org.jboss.netty.channel.ConnectTimeoutException: connection timed out: bt-199-036.bta.net.cn/202.106.199.36:6702<br/>
2016-03-29 16:40:36.859 STDIO <span class="error">&#91;ERROR&#93;</span> 三月 29, 2016 4:40:36 下午 org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer<br/>
警告: An exception was thrown by TimerTask.<br/>
java.lang.RuntimeException: Giving up to scheduleConnect to Netty-Client-bt-199-036.bta.net.cn/202.106.199.36:6702 after 12 failed attempts. 0 messages were lost<br/>
	at backtype.storm.messaging.netty.Client$Connect.run(Client.java:511)<br/>
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:546)<br/>
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$Worker.notifyExpiredTimeouts(HashedWheelTimer.java:446)<br/>
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:395)<br/>
	at org.apache.storm.shade.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)<br/>
	at java.lang.Thread.run(Thread.java:745)<br/>
2016-03-29 16:40:44.466 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> connection attempt 1 to Netty-Client-bt-199-036.bta.net.cn/202.106.199.36:6703 failed: org.apache.storm.shade.org.jboss.netty.channel.ConnectTimeoutException: connection timed out: bt-199-036.bta.net.cn/202.106.199.36:6703<br/>
2016-03-29 16:40:54.665 b.s.m.n.Client <span class="error">&#91;ERROR&#93;</span> connection attempt 2 to Netty-Client-bt-199-036.bta.net.cn/202.106.199.36:6703 failed:</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=johnbaba">johnbaba</a>:</i>
<p>Connect.run() only calls Client.close() when closing is true. We see the connections calls client.close by Connect.run() from the log. So we should call the close() previously. Thus the log should print the "closing Netty Client {}" when calls close() previously. <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a>   can you find the a little earlier log about close()?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=huyl08">huyl08</a>:</i>
<p>Maybe this is a problem due to incompatibility of different Zookeeper versions. I solved my problem by removing Zookeeper dependencies in my $STORM_HOME/extlib. </p>

<p>Previously, I used Zookeeper-3.4.7 as my zk cluster and imported zookeeper-3.4.6.jar from kafka_2.11-0.8.2.2/lib, and the problem came into being. After I removed the wrong version zk jar, everything went ok with me. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Zookeeper does have netty as a dependency, but in the versions we have been using it is not configured to be on.  Perhaps newer versions of zookeeper have it packaged with it somehow?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Johnbaba" class="user-hover" rel="Johnbaba">John Fang</a>, unfortunately I don't. I ran into it when testing on a virtualized cluster that I've since destroyed. Next time I'll be better at saving off the log files. <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raviraj">raviraj</a>:</i>
<p>I have been facing a similar issue in storm. keep getting a error like <br/>
<span class="error">&#91;ERROR&#93;</span> discarding 1 messages because the Netty client to Netty-Client-/</p>
{host}
<p>:</p>
{port}
<p> is being closed</p>

<p>I have seen it appear when the storm nodes had connectivity issues<br/>
1. connectivity issues within storm nodes<br/>
2. connectivity issues between kafka spout and kafka broker.<br/>
Even after the connectivity is recovered , the issue still remains.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p>That could possibly be because the topology workers are getting restarted frequently. It usually happens when there is an uncaught exception in the topology. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raviraj">raviraj</a>:</i>
<p>Even if the topology workers are getting restarted, why should it lead to discarding a message. Even when the worker is back up,i see these errors and some missing messgaes. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nico.meyer">nico.meyer</a>:</i>
<p>Is it certain that this problem affects version 1.0.0? Because I observed the same problem  in 0.9.6 when workers restarted in short succession. That often happens if one worker crashes since nimbus tends to reassign tasks right around the time the crashed worker is restarted by the supervisor (most likely because by default both heartbeat timeouts are 30 second).<br/>
I had a patch that solved it, but it is no longer necessary for 1.0.0.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yunfanfighting@foxmail.com">yunfanfighting@foxmail.com</a>:</i>
<p>I meet same problem in 0.9.6. Can you tell me, how you slove the problem in that version?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hitsdx">hitsdx</a>:</i>
<p>Hi,Nico Meyer,the same problem appears in version 0.10.0.The situation is similar to what you say.Can I know how you solve this problem?I am Looking forward to your replay.Thanks a lot.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nico.meyer">nico.meyer</a>:</i>
<p>Patch for 0.9.6</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nico.meyer">nico.meyer</a>:</i>
<p>Hi sun, sorry for the long delay, but I forgot my password and the reset function didn't work for me last week.</p>

<p>I attached our patch against 0.9.6 (created with 'git diff') that seemed to do the trick, but no guarantees. We upgraded to 1.0.2 by now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sunny.davy">sunny.davy</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nico.meyer" class="user-hover" rel="nico.meyer">Nico Meyer</a></p>

<p>Because of the Log </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-02-18 08:46:59.116 o.a.s.m.n.Client [INFO] closing Netty Client Netty-Client-/192.168.202.6:6701
</pre>
</div></div>
<p>,<br/>
the method <font color="red">close()</font> in backtype.storm.messaging.netty.Client is invoked.</p>

<p>So your Patch maybe to not working because reconnectingAllowed will always return <font color="red">FALSE</font>.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">public</span> void run(Timeout timeout)
      <span class="code-keyword">throws</span> Exception
    {
      <span class="code-keyword">if</span> (Client.<span class="code-keyword">this</span>.reconnectingAllowed())
      {
</pre>
</div></div>

<p><a href="https://issues.apache.org/jira/browse/STORM-2561" class="external-link" rel="nofollow">STORM-2561</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nico.meyer">nico.meyer</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sunny.davy" class="user-hover" rel="sunny.davy">ryan.jin</a></p>

<p>I don't remember the details to be honest, since I wrote this over a year ago. And we moved on to Storm 1.0.2 by now, which does not have this problem any more.<br/>
All I can say is, that we used the patch in production for quite some time and did not ever observe the lockup problem again.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sunny.davy">sunny.davy</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nico.meyer" class="user-hover" rel="nico.meyer">Nico Meyer</a></p>

<p>Okey, maybe I will upgrade to 0.10.2 firstly. <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nico.meyer">nico.meyer</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sunny.davy" class="user-hover" rel="sunny.davy">ryan.jin</a><br/>
I would propose upgrading to 1.0.3 directly. It is a little bit of work to fix all the namespaces, and some other minor things. But there are a lot of other improvements in the 1.x version that warrant the time spent in my opinion.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sunny.davy">sunny.davy</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nico.meyer" class="user-hover" rel="nico.meyer">Nico Meyer</a></p>

<p><img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/>  I will review the diff between 0.10.x and 1.0.x , thank you</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=saurav689">saurav689</a>:</i>
<p>Hi ,</p>

<p>I also got similar error. I am using storm 1.1.1 . Please advise.</p>

<p>2017-10-10 13:17:47.674 o.a.s.m.n.Client client-boss-1 <span class="error">&#91;ERROR&#93;</span> connection attempt 199 to Netty-Client-/192.168.2.195:6702 failed: java.net.ConnectException: Connection refused: /192.168.2.195:6702<br/>
2017-10-10 13:17:47.674 o.a.s.u.StormBoundedExponentialBackoffRetry client-boss-1 <span class="error">&#91;WARN&#93;</span> WILL SLEEP FOR 738ms (MAX)<br/>
2017-10-10 13:17:48.474 o.a.s.m.n.Client client-boss-1 <span class="error">&#91;ERROR&#93;</span> connection attempt 200 to Netty-Client-/192.168.2.195:6702 failed: java.net.ConnectException: Connection refused: /192.168.2.195:6702<br/>
2017-10-10 13:17:48.475 o.a.s.u.StormBoundedExponentialBackoffRetry client-boss-1 <span class="error">&#91;WARN&#93;</span> WILL SLEEP FOR 741ms (MAX)<br/>
2017-10-10 13:17:48.972 o.a.s.m.n.Client refresh-connections-timer <span class="error">&#91;INFO&#93;</span> closing Netty Client Netty-Client-/192.168.2.195:6702<br/>
2017-10-10 13:17:48.977 o.a.s.m.n.Client refresh-connections-timer <span class="error">&#91;INFO&#93;</span> waiting up to 600000 ms to send 0 pending messages to Netty-Client-/192.168.2.195:6702<br/>
2017-10-10 13:17:49.271 STDIO client-schedule-service-1 <span class="error">&#91;ERROR&#93;</span> Oct 10, 2017 1:17:49 PM org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer<br/>
WARNING: An exception was thrown by TimerTask.<br/>
java.lang.RuntimeException: Giving up to scheduleConnect to Netty-Client-/192.168.2.195:6702 after 200 failed attempts. 0 messages were lost<br/>
	at org.apache.storm.messaging.netty.Client$Connect.run(Client.java:606)<br/>
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:546)<br/>
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$Worker.notifyExpiredTimeouts(HashedWheelTimer.java:446)<br/>
	at org.apache.storm.shade.org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:395)<br/>
	at org.apache.storm.shade.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)<br/>
	at java.lang.Thread.run(Thread.java:748)<br/>
2017-10-10 13:19:55.636 o.a.s.m.n.StormServerHandler Netty-server-localhost-6702-worker-1 <span class="error">&#91;ERROR&#93;</span> server errors in handling the request<br/>
java.io.IOException: Connection reset by peer<br/>
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64) <span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) <span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) <span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) <span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) <span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) <span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) <span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) <span class="error">&#91;?:1.8.0_131&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) <span class="error">&#91;?:1.8.0_131&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_131&#93;</span><br/>
2017-10-10 13:28:14.369 o.a.s.m.n.StormServerHandler Netty-server-localhost-6702-worker-1 <span class="error">&#91;ERROR&#93;</span> server errors in handling the request<br/>
java.io.IOException: Connection reset by peer</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=saurav689" class="user-hover" rel="saurav689">Saurav Suman</a>,</p>

<p>In 1.1.1 The only time that "Giving up to schedule" is thrown, is when the netty client is closing.  The only time that it is closing is when the scheduling has changed and we no longer have a need to that client, which is what you have in your logs with the refresh-connections-timer.</p>

<p>From the logs it looks like your topology had a worker scheduled to be on 192.168.2.195:6702, but that worker never came up for some reason.  You didn't include the logs so I cannot tell.  After some time nimbus rescheduled the worker to be on a different host/port.  At that point you got an exception while we were closing the client. </p>

<p>The later logs for Netty-server-localhost-6702-worker-1 indicate that a worker that was connected to this worker broke the connection.  They are most likely not related to the first one.</p>

<p>Did your topology eventually recover?  Did you ever look at the logs for 192.168.2.195:6702 to try and see why it didn't come up?  In 2.x we have added in better logging so hopefully we would be able to see which worker disconnected from the server.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>:</i>
<p>Hello,</p>

<p>FYI - We get same error about one time per month in our production Storm cluster.</p>

<p>Our by-pass is to monitor our topologies using Storm web services and restart impacted topologies when we detect they are impacted (poor's man by pass...)</p>

<p> </p>

<p>Best regards,</p>

<p>Alexandre Vermeerbergen</p>

<p> </p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Looks similar to <a href="https://issues.apache.org/jira/browse/STORM-3055" title="never refresh connection" class="issue-link" data-issue-key="STORM-3055"><del>STORM-3055</del></a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
