### ISSUE TITLE
[STORM-1572] throw NPE when parsing the command line arguments by CLI

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5407]
<p>$ storm kill test<br/>
Running: /data/nfs_share/soft/jdk1.7.0_79/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/data/nfs_share/soft/storm -Dstorm.log.dir=/home/admin/storm_logs -Djava.library.path=/usr/local/lib -Dstorm.conf.file= -cp /data/nfs_share/soft/storm/lib/servlet-api-2.5.jar:/data/nfs_share/soft/storm/lib/slf4j-api-1.7.7.jar:/data/nfs_share/soft/storm/lib/log4j-over-slf4j-1.6.6.jar:/data/nfs_share/soft/storm/lib/reflectasm-1.07-shaded.jar:/data/nfs_share/soft/storm/lib/log4j-api-2.1.jar:/data/nfs_share/soft/storm/lib/storm-core-2.0.0-SNAPSHOT.jar:/data/nfs_share/soft/storm/lib/log4j-core-2.1.jar:/data/nfs_share/soft/storm/lib/kryo-2.21.jar:/data/nfs_share/soft/storm/lib/clojure-1.7.0.jar:/data/nfs_share/soft/storm/lib/log4j-slf4j-impl-2.1.jar:/data/nfs_share/soft/storm/lib/minlog-1.2.jar:/data/nfs_share/soft/storm/lib/disruptor-3.3.2.jar:/data/nfs_share/soft/storm/lib/asm-4.0.jar:/home/admin/.storm:/data/nfs_share/soft/storm/bin org.apache.storm.command.KillTopology test<br/>
Exception in thread "main" java.lang.NullPointerException<br/>
at org.apache.storm.command.CLI$CLIBuilder.parse(CLI.java:243)<br/>
at org.apache.storm.command.KillTopology.main(KillTopology.java:33)</p>

---
<details><summary><i>Originally reported by <a title="John Fang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Johnbaba">Johnbaba</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1572" target="_blank">throw NPE when parsing the command line arguments by CLI</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="John Fang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Johnbaba">Johnbaba</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-02-24T16:44:53+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user hustfxj opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1142" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1142</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1572" title="throw NPE when parsing the command line arguments by CLI" class="issue-link" data-issue-key="STORM-1572"><del>STORM-1572</del></a> throw NPE when parsing the command line arguments by CLI</p>

<p>    $ storm kill test<br/>
    Running: /data/nfs_share/soft/jdk1.7.0_79/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/data/nfs_share/soft/storm -Dstorm.log.dir=/home/admin/storm_logs -Djava.library.path=/usr/local/lib -Dstorm.conf.file= -cp /data/nfs_share/soft/storm/lib/servlet-api-2.5.jar:/data/nfs_share/soft/storm/lib/slf4j-api-1.7.7.jar:/data/nfs_share/soft/storm/lib/log4j-over-slf4j-1.6.6.jar:/data/nfs_share/soft/storm/lib/reflectasm-1.07-shaded.jar:/data/nfs_share/soft/storm/lib/log4j-api-2.1.jar:/data/nfs_share/soft/storm/lib/storm-core-2.0.0-SNAPSHOT.jar:/data/nfs_share/soft/storm/lib/log4j-core-2.1.jar:/data/nfs_share/soft/storm/lib/kryo-2.21.jar:/data/nfs_share/soft/storm/lib/clojure-1.7.0.jar:/data/nfs_share/soft/storm/lib/log4j-slf4j-impl-2.1.jar:/data/nfs_share/soft/storm/lib/minlog-1.2.jar:/data/nfs_share/soft/storm/lib/disruptor-3.3.2.jar:/data/nfs_share/soft/storm/lib/asm-4.0.jar:/home/admin/.storm:/data/nfs_share/soft/storm/bin org.apache.storm.command.KillTopology test<br/>
    Exception in thread "main" java.lang.NullPointerException<br/>
    at org.apache.storm.command.CLI$CLIBuilder.parse(CLI.java:243)<br/>
    at org.apache.storm.command.KillTopology.main(KillTopology.java:33)</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/hustfxj/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/hustfxj/storm</a> 0223</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1142.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1142.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1142</p>

<hr />
<p>commit 3af457f8cd3dec53af969a70f7f5238b4502dada<br/>
Author: xiaojian.fxj <xiaojian.fxj@alibaba-inc.com><br/>
Date:   2016-02-23T15:11:44Z</p>

<p>    fix CLI about parsing the command line arguments</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1142#issuecomment-187738243" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1142#issuecomment-187738243</a></p>

<p>    +1 I guess I never did test without a -w option.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user wuchong commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1142#discussion_r53898826" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1142#discussion_r53898826</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/org/apache/storm/command/CLI.java &#8212;<br/>
    @@ -238,10 +238,13 @@ public CLIBuilder arg(String name, Parse parse, Assoc assoc) {<br/>
 DefaultParser parser = new DefaultParser();<br/>
 CommandLine cl = parser.parse(options, rawArgs);<br/>
 HashMap<String, Object> ret = new HashMap<>();</p>
<ul class="alternate" type="square">
	<li>for (Opt opt: opts) {<br/>
    +    for (Opt opt : opts) {<br/>
     Object current = null;</li>
	<li>for (String val: cl.getOptionValues(opt.shortName)) {</li>
	<li>current = opt.process(current, val);<br/>
    +String[] strings = cl.getOptionValues(opt.shortName);<br/>
    +if (strings != null) {<br/>
    +    for (String val : cl.getOptionValues(opt.shortName)) {
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    replace `cl.getOptionValues(opt.shortName)` with `strings` to avoid duplicate getOptionValues</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user wuchong commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1142#issuecomment-188100054" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1142#issuecomment-188100054</a></p>

<p>    +1 except a minor comment</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1142#discussion_r53965439" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1142#discussion_r53965439</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/org/apache/storm/command/CLI.java &#8212;<br/>
    @@ -238,10 +238,13 @@ public CLIBuilder arg(String name, Parse parse, Assoc assoc) {<br/>
 DefaultParser parser = new DefaultParser();<br/>
 CommandLine cl = parser.parse(options, rawArgs);<br/>
 HashMap<String, Object> ret = new HashMap<>();</p>
<ul class="alternate" type="square">
	<li>for (Opt opt: opts) {<br/>
    +    for (Opt opt : opts) {<br/>
     Object current = null;</li>
	<li>for (String val: cl.getOptionValues(opt.shortName)) {</li>
	<li>current = opt.process(current, val);<br/>
    +String[] strings = cl.getOptionValues(opt.shortName);<br/>
    +if (strings != null) {<br/>
    +    for (String val : cl.getOptionValues(opt.shortName)) {
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    The change is minor so I will do it as I merge it in.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1142" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1142</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Johnbaba" class="user-hover" rel="Johnbaba">John Fang</a>,</p>

<p>I merged this into master.</p>
