### ISSUE TITLE
[STORM-1579] Got NoSuchFileException when running tests in storm-core

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5414]
<p>Stacktrace:<br/>
125277 [Thread-1736-__eventlogger-executor<span class="error">&#91;4 4&#93;</span>] ERROR o.a.s.m.FileBasedEventLogger - Error setting up FileBasedEventLogger.<br/>
java.nio.file.NoSuchFileException: /logs/workers-artifacts/metrics-tester-1-0/1024/events.log<br/>
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~<span class="error">&#91;?:1.7.0_75&#93;</span><br/>
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~<span class="error">&#91;?:1.7.0_75&#93;</span><br/>
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~<span class="error">&#91;?:1.7.0_75&#93;</span><br/>
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~<span class="error">&#91;?:1.7.0_75&#93;</span><br/>
    at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:430) ~<span class="error">&#91;?:1.7.0_75&#93;</span><br/>
    at java.nio.file.Files.newOutputStream(Files.java:172) ~<span class="error">&#91;?:1.7.0_75&#93;</span><br/>
    at java.nio.file.Files.newBufferedWriter(Files.java:2722) ~<span class="error">&#91;?:1.7.0_75&#93;</span><br/>
    at org.apache.storm.metric.FileBasedEventLogger.initLogWriter(FileBasedEventLogger.java:51) <span class="error">&#91;classes/:?&#93;</span><br/>
    at org.apache.storm.metric.FileBasedEventLogger.prepare(FileBasedEventLogger.java:97) <span class="error">&#91;classes/:?&#93;</span><br/>
    at org.apache.storm.metric.EventLoggerBolt.prepare(EventLoggerBolt.java:48) <span class="error">&#91;classes/:?&#93;</span><br/>
    at org.apache.storm.daemon.executor$fn_<em>6507$bolt_transfer_fn</em>_6522.invoke(executor.clj:792) <span class="error">&#91;classes/:?&#93;</span><br/>
    at clojure.lang.AFn.call(AFn.java:18) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
    at org.apache.storm.utils.Utils$6.run(Utils.java:2177) <span class="error">&#91;classes/:?&#93;</span><br/>
    at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_75&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Cody" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Cody">Cody</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1579" target="_blank">Got NoSuchFileException when running tests in storm-core</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Cody" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Cody">Cody</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-03-02T17:28:15+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Did you run the integration test? <br/>
`mvn clean install` on current master doesn't reproduce this behavior. <br/>
Could you pull the latest and try again?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cody">cody</a>:</i>
<p>I was running mvn clean package and it's the latest code from master. I've never met such exceptions before pulling the latest code today.<br/>
By running mvn clean install I get the same exceptions, note that the exceptions don't affect final test results, it's just unexpected exceptions.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cody">cody</a>:</i>
<p>Sorry, it was NoSuchFileException, updated title.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Cody" class="user-hover" rel="Cody">Cody</a><br/>
I also can see the issue you stated from test-report.</p>

<p>Maybe the change comes from this commit, <a href="https://github.com/apache/storm/commit/0fc58437badb0f6b464141889d532dea87ff4457" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/commit/0fc58437badb0f6b464141889d532dea87ff4457</a></p>

<p>Related configuration are here.</p>

<ul class="alternate" type="square">
	<li>storm.log.dir</li>
	<li>storm.home</li>
	<li>storm.workers.artifacts.dir</li>
</ul>


<p>You can refer ConfigUtils.workerArtifactsRoot() to track down why your test tried to write "events.log" file to "/logs/workers-artifacts/<topology id>/<port>/events.log". </p>

<p>Unfortunately if we doesn't set any of these root dir of worker artifacts is set to /logs/workers-artifacts.<br/>
The user account we normally use doesn't have permission to create /logs, so mkdirs() fails "quitely" and we see NoSuchFileException when creating or append actual file.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Running </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">sudo mvn install</pre>
</div></div>
<p> resolves this issue, but we need to make it clear that it's OK to set log dir to /logs when three params are default.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cody">cody</a>:</i>
<p>Yes this will resolve the issue, but not natural, I've changed and opened a PR <a href="https://github.com/apache/storm/pull/1161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1161</a>, would you please help review?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Cody" class="user-hover" rel="Cody">Cody</a>,</p>

<p>I merged this into master.</p>
