### ISSUE TITLE
[STORM-1587] ThroughputVsLatency printMetrics Throws NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5422]
<p>The printmetrics can cause NPE.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">1701 [main] INFO  o.a.s.StormSubmitter - Submitting topology wc-test in distributed mode with conf {<span class="code-quote">"topology.worker.metrics"</span>:{<span class="code-quote">"CPU"</span>:<span class="code-quote">"org.apache.storm.metrics.sigar.CPUMetric"</span>},<span class="code-quote">"storm.zookeeper.topology.auth.scheme"</span>:<span class="code-quote">"digest"</span>,<span class="code-quote">"topology.worker.gc.childopts"</span>:<span class="code-quote">"-XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:NewSize=128m -XX:CMSInitiatingOccupancyFraction=70 -XX:-CMSConcurrentMTEnabled"</span>,<span class="code-quote">"topology.workers"</span>:4,<span class="code-quote">"topology.builtin.metrics.bucket.size.secs"</span>:10,<span class="code-quote">"topology.worker.childopts"</span>:<span class="code-quote">"-Xmx2g"</span>,<span class="code-quote">"storm.zookeeper.topology.auth.payload"</span>:<span class="code-quote">"-5601074936064852696:-8332153375154710952"</span>,<span class="code-quote">"topology.metrics.consumer.register"</span>:[{<span class="code-quote">"argument"</span>:<span class="code-keyword">null</span>,<span class="code-quote">"class"</span>:<span class="code-quote">"org.apache.storm.metric.LoggingMetricsConsumer"</span>,<span class="code-quote">"parallelism.hint"</span>:1},{<span class="code-quote">"argument"</span>:<span class="code-quote">"http:\/\/survivedlived.corp.ir2.yahoo.com:45976\/"</span>,<span class="code-quote">"class"</span>:<span class="code-quote">"org.apache.storm.metric.HttpForwardingMetricsConsumer"</span>,<span class="code-quote">"parallelism.hint"</span>:1}]}
2137 [main] INFO  o.a.s.StormSubmitter - Finished submitting topology: wc-test
Exception in thread <span class="code-quote">"main"</span> java.lang.NullPointerException
	at org.apache.storm.starter.ThroughputVsLatency.printMetrics(ThroughputVsLatency.java:277)
	at org.apache.storm.starter.ThroughputVsLatency.main(ThroughputVsLatency.java:425)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1587" target="_blank">ThroughputVsLatency printMetrics Throws NullPointerException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-03-01T18:55:27+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1167#issuecomment-190845814" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1167#issuecomment-190845814</a></p>

<p>    Can we pull this into 1.x-branch as well?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1167#issuecomment-190846044" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1167#issuecomment-190846044</a></p>

<p>    sure</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1167" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1167</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil" class="user-hover" rel="kishorvpatil">Kishor Patil</a>,</p>

<p>I merged this into master and 1.x-branch</p>
