### ISSUE TITLE
[STORM-1601] Cluster-state must check if znode exists before getting children for storm backpressure

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5436]
<p>You see below exception in the integration tests..</p>

<div class="panel" style="border-width: 1px;"><div class="panelContent">
<p>15:46:23 java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /backpressure/topologytest-22ffcfa0-8992-4258-b8b6-52346a129b58-1-0<br/>
15:46:23 	at backtype.storm.util$wrap_in_runtime.invoke(util.clj:52) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at backtype.storm.zookeeper$get_children.invoke(zookeeper.clj:168) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at backtype.storm.cluster_state.zookeeper_state_factory$<em>mkState$reify</em>_4184.get_children(zookeeper_state_factory.clj:129) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
15:46:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
15:46:23 	at java.lang.reflect.Method.invoke(Method.java:497) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
15:46:23 	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
15:46:23 	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
15:46:23 	at backtype.storm.cluster$mk_storm_cluster_state$reify__4091.topology_backpressure(cluster.clj:407) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
15:46:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
15:46:23 	at java.lang.reflect.Method.invoke(Method.java:497) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
15:46:23 	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
15:46:23 	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
15:46:23 	at backtype.storm.daemon.worker$fn_<em>6837$exec_fn</em><em>1477</em><em>auto</em><em>$reify</em><em>6839$check_throttle_changed</em><em>6910$cb</em>_6911.doInvoke(worker.clj:704) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at clojure.lang.RestFn.invoke(RestFn.java:408) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
15:46:23 	at backtype.storm.cluster$issue_map_callback_BANG_.invoke(cluster.clj:183) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at backtype.storm.cluster$mk_storm_cluster_state$fn__4081.invoke(cluster.clj:239) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at backtype.storm.cluster_state.zookeeper_state_factory$<em>mkState$fn</em>_4166.invoke(zookeeper_state_factory.clj:45) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at backtype.storm.zookeeper$mk_client$reify__2993.eventReceived(zookeeper.clj:63) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.CuratorFrameworkImpl$8.apply(CuratorFrameworkImpl.java:860) <span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.CuratorFrameworkImpl$8.apply(CuratorFrameworkImpl.java:853) <span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:92) <span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) <span class="error">&#91;guava-16.0.1.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:83) <span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processEvent(CuratorFrameworkImpl.java:850) <span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$000(CuratorFrameworkImpl.java:57) <span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.CuratorFrameworkImpl$1.process(CuratorFrameworkImpl.java:138) <span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.ConnectionState.process(ConnectionState.java:152) <span class="error">&#91;curator-client-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522) <span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
15:46:23 	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) <span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
15:46:23 Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /backpressure/topologytest-22ffcfa0-8992-4258-b8b6-52346a129b58-1-0<br/>
15:46:23 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
15:46:23 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
15:46:23 	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
15:46:23 	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1625) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:210) ~<span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203) ~<span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~<span class="error">&#91;curator-client-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:199) ~<span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191) ~<span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38) ~<span class="error">&#91;curator-framework-2.5.0.jar:?&#93;</span><br/>
15:46:23 	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
15:46:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
15:46:23 	at java.lang.reflect.Method.invoke(Method.java:497) ~<span class="error">&#91;?:1.8.0_60&#93;</span><br/>
15:46:23 	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
15:46:23 	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~<span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
15:46:23 	at backtype.storm.zookeeper$get_children.invoke(zookeeper.clj:166) ~<span class="error">&#91;classes/:?&#93;</span><br/>
15:46:23 	... 29 more</p>
</div></div>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1601" target="_blank">Cluster-state must check if znode exists before getting children for storm backpressure</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-03-04T15:48:09+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1181" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1181</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1601" title="Cluster-state must check if znode exists before getting children for storm backpressure" class="issue-link" data-issue-key="STORM-1601"><del>STORM-1601</del></a> Check if /backpressure/storm-id node exists before requesting children</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> storm1601</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1181.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1181.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1181</p>

<hr />
<p>commit 177a4c3ad269855532edc7c00312c7a79e1a4da7<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2016-03-03T18:32:19Z</p>

<p>    Check if /backpressure/storm-id before requesting children</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kishorvpatil opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1182" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1182</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1601" title="Cluster-state must check if znode exists before getting children for storm backpressure" class="issue-link" data-issue-key="STORM-1601"><del>STORM-1601</del></a> Check if /backpressure/storm-id znode  exists before requesting children</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kishorvpatil/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kishorvpatil/incubator-storm</a> storm1601-1.x-branch</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1182.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1182.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1182</p>

<hr />
<p>commit 4fdb14a0b24ca52ad6a3f4616965e75613472452<br/>
Author: Kishor Patil <kpatil@yahoo-inc.com><br/>
Date:   2016-03-03T18:38:01Z</p>

<p>    Check if /backpressure/storm-id znode  exists before requesting children</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user hustfxj commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1182#issuecomment-192108715" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1182#issuecomment-192108715</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1181#issuecomment-192318678" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1181#issuecomment-192318678</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1182#issuecomment-192324639" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1182#issuecomment-192324639</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1181" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1181</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1182" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1182</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil" class="user-hover" rel="kishorvpatil">Kishor Patil</a>,</p>

<p>I merged this into master and 1.x-branch</p>
