### ISSUE TITLE
[STORM-1635] Master branch broken! Exception thrown immediately after submitting topology

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5470]
<p>Exception thrown:</p>

<p>2016-03-16 22:20:14.940 o.a.s.t.s.AbstractNonblockingServer$FrameBuffer <span class="error">&#91;ERROR&#93;</span> Unexpected throwable while invoking!<br/>
java.lang.NullPointerException<br/>
at clojure.lang.RT.intCast(RT.java:1163)<br/>
at org.apache.storm.daemon.nimbus$fn_<em>2162$exec_fn</em><em>589</em><em>auto</em><em>$reify</em><em>2191$iter</em><em>2267</em><em>2271$fn</em>_2272.invoke(nimbus.clj:1837)<br/>
at clojure.lang.LazySeq.sval(LazySeq.java:40)<br/>
at clojure.lang.LazySeq.seq(LazySeq.java:49)<br/>
at clojure.lang.RT.seq(RT.java:507)<br/>
at clojure.core$seq__4128.invoke(core.clj:137)<br/>
at clojure.core$dorun.invoke(core.clj:3009)<br/>
at clojure.core$doall.invoke(core.clj:3025)<br/>
at org.apache.storm.daemon.nimbus$fn_<em>2162$exec_fn</em><em>589</em><em>auto</em><em>$reify</em>_2191.getClusterInfo(nimbus.clj:1822)<br/>
at org.apache.storm.generated.Nimbus$Processor$getClusterInfo.getResult(Nimbus.java:3724)<br/>
at org.apache.storm.generated.Nimbus$Processor$getClusterInfo.getResult(Nimbus.java:3708)<br/>
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39)<br/>
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39)<br/>
at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)<br/>
at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)<br/>
at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br/>
at java.lang.Thread.run(Thread.java:745)</p>

<p>This is also causing UI to not work.</p>

---
<details><summary><i>Originally reported by <a title="Boyang Jerry Peng" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jerrypeng">jerrypeng</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1635" target="_blank">Master branch broken! Exception thrown immediately after submitting topology</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="John Fang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Johnbaba">Johnbaba</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2016-03-17T04:31:22+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jerrypeng">jerrypeng</a>:</i>
<p>Dup of <a href="https://issues.apache.org/jira/browse/STORM-1623" title="nimbus.clj&#39;s minor bug" class="issue-link" data-issue-key="STORM-1623"><del>STORM-1623</del></a></p>
