### ISSUE TITLE
[STORM-1642] NullPointerException when deserialize

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5477]
<p>Hi:<br/>
I've encountered the following NPE when storm tries to deserialize. I did not use OutputCollector concurrently in my code.  The only object we are passing between bolts are a thrift object, and we have written a serializer for it. I've attached the code of serializer and please help to check whether there are any potential bugs there.</p>

<p>2016-03-04 17:17:43.583 b.s.util <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
java.lang.RuntimeException: java.lang.NullPointerException<br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:135) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:106) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>5694$fn</em><em>5707$fn</em>_5758.invoke(executor.clj:819) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.util$async_loop$fn__545.invoke(util.clj:479) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_60&#93;</span><br/>
Caused by: java.lang.NullPointerException<br/>
at com.esotericsoftware.kryo.io.Input.setBuffer(Input.java:57) ~<span class="error">&#91;kryo-2.21.jar:?&#93;</span><br/>
at backtype.storm.serialization.KryoTupleDeserializer.deserialize(KryoTupleDeserializer.java:47) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.daemon.executor$mk_task_receiver$fn__5615.invoke(executor.clj:433) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.disruptor$clojure_handler$reify__5189.onEvent(disruptor.clj:58) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:132) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
... 6 more<br/>
2016-03-04 17:17:43.584 b.s.d.executor <span class="error">&#91;ERROR&#93;</span><br/>
java.lang.RuntimeException: java.lang.NullPointerException<br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:135) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:106) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.daemon.executor$fn_<em>5694$fn</em><em>5707$fn</em>_5758.invoke(executor.clj:819) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.util$async_loop$fn__545.invoke(util.clj:479) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_60&#93;</span><br/>
Caused by: java.lang.NullPointerException<br/>
at com.esotericsoftware.kryo.io.Input.setBuffer(Input.java:57) ~<span class="error">&#91;kryo-2.21.jar:?&#93;</span><br/>
at backtype.storm.serialization.KryoTupleDeserializer.deserialize(KryoTupleDeserializer.java:47) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.daemon.executor$mk_task_receiver$fn__5615.invoke(executor.clj:433) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.disruptor$clojure_handler$reify__5189.onEvent(disruptor.clj:58) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:132) ~<span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
... 6 more<br/>
2016-03-04 17:17:43.648 b.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Worker died")<br/>
java.lang.RuntimeException: ("Worker died")<br/>
at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:336) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at backtype.storm.daemon.worker$fn_<em>7188$fn</em>_7189.invoke(worker.clj:536) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.daemon.executor$mk_executor_data$fn_<em>5523$fn</em>_5524.invoke(executor.clj:261) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at backtype.storm.util$async_loop$fn__545.invoke(util.clj:489) <span class="error">&#91;storm-core-0.10.0.jar:0.10.0&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.6.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_60&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Renjie Liu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=liurenjie1024">liurenjie1024</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1642" target="_blank">NullPointerException when deserialize</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Govind Menon" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gmenon">gmenon</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-06-12T01:49:38+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Is this 100% reproducible?  The NPE is happening because the buffer passed into the <tt>KryoTupleDeserializer</tt> and in turn into <tt>Input</tt> is null.  This means that the msg placed into a batch had to be null.  With the version fo disruptor that we have in 0.10 it is possible that you emitted sent a null, but I don't know for sure.</p>

<p>I don't see your attached code like you mentioned though.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=liurenjie1024">liurenjie1024</a>:</i>
<p>I do not know how to reproduce this NPE but it just happens several hours or several days. I've went through storm's code and I don't think it's possible for the msg to be null since the MessageDecoder only returns null when length of payload is zero but it's impossible since the payload   contains like source component id, source task id, etc. This means that even if I emit a null the payload can not be null.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=liurenjie1024">liurenjie1024</a>:</i>
<p>It turns out that this is caused by messages sent from machines outside storm cluster. When storm receives a TaskMessage that can not be deserialized, the worker will be shutdown. I'll propose a patch to fix this issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user liurenjie1024 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1642" title="NullPointerException when deserialize" class="issue-link" data-issue-key="STORM-1642"><del>STORM-1642</del></a></p>

<p>    This patch aims to fix bug <a href="https://issues.apache.org/jira/browse/STORM-1642" title="NullPointerException when deserialize" class="issue-link" data-issue-key="STORM-1642"><del>STORM-1642</del></a>.  When we failed to deserialize a tuple, we should skip this tuple and print a log rather than just shutdown the work.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/MediaV/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/MediaV/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1642" title="NullPointerException when deserialize" class="issue-link" data-issue-key="STORM-1642"><del>STORM-1642</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1316</p>

<hr />
<p>commit fff27f37be6beb54a67f45071259aa2fb83614e4<br/>
Author: liurenjie1024 <liurenjie2008@gmail.com><br/>
Date:   2016-04-06T10:51:00Z</p>

<p>    Bug fix</p>

<p>commit fbfcd8ce31410849f233d617881dc82bed8b9fbd<br/>
Author: liurenjie1024 <liurenjie2008@gmail.com><br/>
Date:   2016-04-07T02:19:01Z</p>

<p>    fix build break</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#issuecomment-206701464" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#issuecomment-206701464</a></p>

<p>    How was deserialization failure resulting in NPE? Other than that, deserialization failure is the problem with an application itself which application should correct by registering correct serializer/deserializer. storm framework should not skip such tuples on its own. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user liurenjie1024 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#issuecomment-206713335" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#issuecomment-206713335</a></p>

<p>    As I have mentioned in bug report, the reason why NPE happens is that storm is vulnerable to fraud message from  processes outside the cluster. To reproduce the NPE, you just need to send a message <span class="error">&#91;taskid 0&#93;</span> to <span class="error">&#91;host&#93;</span>:<span class="error">&#91;port&#93;</span> from anywhere, where taskid is id of one of the tasks running on <span class="error">&#91;host&#93;</span>:<span class="error">&#91;port&#93;</span>. In this case, storm will return a TaskMessage with payload set to null to the deserializer. <br/>
    Storm does not check whether the task message is from processes within the cluster, so deserialization may fail. I  think storm should skip the fruad task message rather than shutdowning the worker when deserialization failed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#issuecomment-206724794" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#issuecomment-206724794</a></p>

<p>    I can't think of a reason of why would such a message be sent to storm from outside the cluster. Ideally only cluster machines and daemons should have access to the worker ports. Or if it indeeds needs to be solved, then a better method would be to ignore the zero length payload and not add `new TaskMessage(task, null)`.  Before you make any change, let's wait for comments from someone who is more familiar with this part of code. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user liurenjie1024 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#issuecomment-206732733" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#issuecomment-206732733</a></p>

<p>    The reason why such a message is sent is that our security team is scanning all the ports listened on each server and tries to detect potential weakness.<br/>
    At first thought I just wanted to ignore messages with zero payload, but I think ignoring messages failed to be deserialized would be more robust. I think this also matches storm's design since it throws away messages whose target task id is not in the worker and this patch is just a complement.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#discussion_r58954552" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#discussion_r58954552</a></p>

<p>    &#8212; Diff: storm-core/src/clj/backtype/storm/daemon/executor.clj &#8212;<br/>
    @@ -431,13 +431,14 @@<br/>
   (fn <span class="error">&#91;tuple-batch sequence-id end-of-batch?&#93;</span><br/>
     (fast-list-iter [<span class="error">&#91;task-id msg&#93;</span> tuple-batch]<br/>
       (let <span class="error">&#91;^TupleImpl tuple (if (instance? Tuple msg) msg (.deserialize deserializer msg))&#93;</span></p>
<ul class="alternate" type="square">
	<li>(when debug? (log-message "Processing received message FOR " task-id " TUPLE: " tuple))</li>
	<li>(if task-id</li>
	<li>(tuple-action-fn task-id tuple)</li>
	<li>;; null task ids are broadcast tuples</li>
	<li>(fast-list-iter <span class="error">&#91;task-id task-ids&#93;</span><br/>
    +    (if tuple<br/>
    +      ((when debug? (log-message "Processing received message FOR " task-id " TUPLE: " tuple))<br/>
    +      (if task-id<br/>
     (tuple-action-fn task-id tuple)</li>
	<li>))<br/>
    +;; null task ids are broadcast tuples<br/>
    +(fast-list-iter <span class="error">&#91;task-id task-ids&#93;</span><br/>
    +  (tuple-action-fn task-id tuple)<br/>
    +  ))))
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Lots of parenthetical and formatting problems here.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#issuecomment-207576535" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#issuecomment-207576535</a></p>

<p>    Why not no both? I don't see any reason to propagate `TaskMessage`s with null payloads, but I agree we should be dropping tuples that failed to deserialize in the iterator. </p>

<p>    This is very much on the critical path, so someone else might want to weigh in.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user liurenjie1024 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#issuecomment-207660738" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#issuecomment-207660738</a></p>

<p>    NPE is just a special case of deserialization failure, right?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#issuecomment-207676736" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#issuecomment-207676736</a></p>

<p>    What do you mean?</p>

<p>    If you mean null payloads are a special case, I disagree. In fact, it's not a failure at all. We received a null message, so we can perform a NOP as soon as possible.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user liurenjie1024 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#issuecomment-207678155" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#issuecomment-207678155</a></p>

<p>    Yes, I agree with you that we should drop a task message with null payload as soon as possible, and I'll push another commit to drop task messages with null payload.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user gzm55 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1316#discussion_r71503230" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1316#discussion_r71503230</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/messaging/netty/MessageBatch.java &#8212;<br/>
    @@ -112,6 +115,9 @@ private void writeTaskMessage(ChannelBufferOutputStream bout, TaskMessage messag<br/>
 throw new RuntimeException("Task ID should not exceed "+Short.MAX_VALUE);</p>

<p>     bout.writeShort((short)task_id);<br/>
    +if (payload_len == 0) {<br/>
    +    LOG.warn("Zero length payload to task {}.", (short)task_id);<br/>
    &#8212; End diff &#8211;</p>

<p>    is this a debugging log? should remove them? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kailas">kailas</a>:</i>
<p>Hello All,<br/>
I am using storm version 1.0.0 and I am still facing the same exception. Can anyone please confirm whether this issue still present in this version. Also what is the possible impact of this issue. Will it automatically get resolved on retry,</p>

<p>java.lang.NullPointerException<br/>
	at com.esotericsoftware.kryo.io.Input.setBuffer(Input.java:81) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
	at org.apache.storm.serialization.KryoTupleDeserializer.deserialize(KryoTupleDeserializer.java:44) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.messaging.DeserializingConnectionCallback.recv(DeserializingConnectionCallback.java:56) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.messaging.netty.Server.enqueue(Server.java:133) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.messaging.netty.Server.received(Server.java:254) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.messaging.netty.StormServerHandler.messageReceived(StormServerHandler.java:61) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) <span class="error">&#91;?:1.8.0_77&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) <span class="error">&#91;?:1.8.0_77&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_77&#93;</span></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=liurenjie1024">liurenjie1024</a>:</i>
<p>I've proposed a patch for this issue but the PMC does not accept that.</p>
