### ISSUE TITLE
[STORM-1645] nimbus.thrift.port command line argument leads to java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5480]
<p>When you supply the commandline parameter for a custom Nimbus thrift port, the number value is interpreted as a Long, but internally used as an Integer. This leads to a ClassCastException.</p>

<p>This is executed (redacted):<br/>
/opt/storm/apache-storm-0.10.0/bin/storm kill -w 10 -c nimbus.thrift.port=6627 -c nimbus.host=vm0009 #</p>
{topology}
<p>"</p>

<p>This is the output:</p>
<ul>
	<li>
	<ul>
		<li><span class="error">&#91;out :: vm0009&#93;</span> 2627 <span class="error">&#91;main&#93;</span> INFO  b.s.u.Utils - Using defaults.yaml from resources</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> 2795 <span class="error">&#91;main&#93;</span> INFO  b.s.u.Utils - Using storm.yaml from resources</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> 4262 <span class="error">&#91;main&#93;</span> INFO  b.s.u.Utils - Using defaults.yaml from resources</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> 4287 <span class="error">&#91;main&#93;</span> INFO  b.s.u.Utils - Using storm.yaml from resources</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> 4328 <span class="error">&#91;main&#93;</span> INFO  b.s.thrift - Connecting to Nimbus at vm0009:6627 as user:</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> 4328 <span class="error">&#91;main&#93;</span> INFO  b.s.u.Utils - Using defaults.yaml from resources</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> 4348 <span class="error">&#91;main&#93;</span> INFO  b.s.u.Utils - Using storm.yaml from resources</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> Exception in thread "main"</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span></li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:75)</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span></li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:72)</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span></li>
		<li><span class="error">&#91;out :: vm0009&#93;</span></li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> at backtype.storm.command.kill_topology$_main.doInvoke(kill_topology.clj:26)</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span></li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> at clojure.lang.RestFn.applyTo(RestFn.java:137)</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span></li>
		<li><span class="error">&#91;out :: vm0009&#93;</span> at backtype.storm.command.kill_topology.main(Unknown Source)</li>
		<li><span class="error">&#91;out :: vm0009&#93;</span></li>
	</ul>
	</li>
</ul>

<p>I have seen other related issues: <a href="https://issues.apache.org/jira/browse/STORM-1578" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1578</a><br/>
I believe this is the same issue (internally using an Integer, but converting the input to a Long) in a different area.</p>

---
<details><summary><i>Originally reported by <a title="Waatze Goldewijk" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Waatze Goldewijk">Waatze Goldewijk</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1645" target="_blank">nimbus.thrift.port command line argument leads to java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Abhishek Agarwal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-04-26T17:46:37+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p>This problem exists only for the 0.10.x branch and it is a minor bug. So I am not completely sure if this needs to be fixed. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aswen">aswen</a>:</i>
<p>For us, running multiple storm nimbus instances on one server this is quite an annoying problem as we have to set three ports for the nimbus instances to listen on. So, we would be very happy if this bug gets solved. Thanks in advance for reconsidering this.</p>

<p>Best regards,<br/>
Alex</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aswen" class="user-hover" rel="aswen">Alexander Swen</a>,</p>

<p>It should be a very simple fix.</p>

<p>Change</p>

<p><a href="https://github.com/apache/storm/blob/v0.10.0/storm-core/src/clj/backtype/storm/thrift.clj#L76" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v0.10.0/storm-core/src/clj/backtype/storm/thrift.clj#L76</a></p>

<p>to be</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> nimbusClient (NimbusClient. conf host (<span class="code-object">int</span> port) nil as-user)
</pre>
</div></div>

<p>I don't really have time to test this myself, but if you want to test it and create a pull request that would be great.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user abhishekagarwal87 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1301" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1301</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1645" title="nimbus.thrift.port command line argument leads to java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer" class="issue-link" data-issue-key="STORM-1645"><del>STORM-1645</del></a>: convert nimbus.thrift.port to int to avoid ClassCastException</p>

<p>    Verified that it works</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/abhishekagarwal87/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/abhishekagarwal87/storm</a> 0.10.x-branch</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1301.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1301.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1301</p>

<hr />
<p>commit 5d9fede5d240645b1bd17835ed2cf7a4c6fad93b<br/>
Author: Abhishek Agarwal <abhishek.agarwal@inmobi.com><br/>
Date:   2016-04-02T07:56:57Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1645" title="nimbus.thrift.port command line argument leads to java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer" class="issue-link" data-issue-key="STORM-1645"><del>STORM-1645</del></a>: convert nimbus.thrift.port to int to avoid ClassCastException</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1301#issuecomment-208800261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1301#issuecomment-208800261</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1301#issuecomment-209359442" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1301#issuecomment-209359442</a></p>

<p>    @HeartSaVioR - can you merge this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1301" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1301</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Merged to 0.10.x-branch.</p>
