### ISSUE TITLE
[STORM-1663] Clicking on an active topology from storm ui home page and then refreshing the page throws exception

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5498]
<p>The exception thrown is:</p>

<p>org.apache.storm.thrift.transport.TTransportException<br/>
	at org.apache.storm.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)<br/>
	at org.apache.storm.thrift.transport.TTransport.readAll(TTransport.java:86)<br/>
	at org.apache.storm.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)<br/>
	at org.apache.storm.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)<br/>
	at org.apache.storm.thrift.transport.TTransport.readAll(TTransport.java:86)<br/>
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)<br/>
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)<br/>
	at org.apache.storm.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)<br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:77)<br/>
	at org.apache.storm.generated.Nimbus$Client.recv_getTopologyPageInfo(Nimbus.java:1243)<br/>
	at org.apache.storm.generated.Nimbus$Client.getTopologyPageInfo(Nimbus.java:1228)<br/>
	at org.apache.storm.ui.core$topology_page.invoke(core.clj:638)<br/>
	at org.apache.storm.ui.core$fn__3662.invoke(core.clj:987)<br/>
	at org.apache.storm.shade.compojure.core$make_route$fn__302.invoke(core.clj:93)<br/>
	at org.apache.storm.shade.compojure.core$if_route$fn__290.invoke(core.clj:39)<br/>
	at org.apache.storm.shade.compojure.core$if_method$fn__283.invoke(core.clj:24)<br/>
	at org.apache.storm.shade.compojure.core$routing$fn__308.invoke(core.clj:106)<br/>
	at clojure.core$some.invoke(core.clj:2570)<br/>
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:106)<br/>
	at clojure.lang.RestFn.applyTo(RestFn.java:139)<br/>
	at clojure.core$apply.invoke(core.clj:632)<br/>
	at org.apache.storm.shade.compojure.core$routes$fn__312.invoke(core.clj:111)<br/>
	at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__1204.invoke(json.clj:56)<br/>
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__765.invoke(multipart_params.clj:103)<br/>
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__724.invoke(reload.clj:22)<br/>
	at org.apache.storm.ui.helpers$requests_middleware$fn__3091.invoke(helpers.clj:50)<br/>
	at org.apache.storm.ui.core$catch_errors$fn__3837.invoke(core.clj:1250)<br/>
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__2852.invoke(keyword_params.clj:27)<br/>
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__2892.invoke(nested_params.clj:65)<br/>
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__2823.invoke(params.clj:55)<br/>
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__765.invoke(multipart_params.clj:103)<br/>
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__3075.invoke(flash.clj:14)<br/>
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__3063.invoke(session.clj:43)<br/>
	at org.apache.storm.shade.ring.middleware.cookies$wrap_cookies$fn__2991.invoke(cookies.clj:160)<br/>
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__2729.invoke(servlet.clj:127)<br/>
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__2733.invoke(servlet.clj:136)<br/>
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)<br/>
	at org.apache.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:47)<br/>
	at org.apache.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:39)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)<br/>
	at java.lang.Thread.run(Thread.java:745)</p>

---
<details><summary><i>Originally reported by <a title="Parag Shah" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pshah">pshah</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1663" target="_blank">Clicking on an active topology from storm ui home page and then refreshing the page throws exception</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-03-31T19:22:10+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pshah" class="user-hover" rel="pshah">Parag Shah</a>, Could you look in the nimbus log and see what error messages are there.  This exception just indicates there was a thrift error on one of the calls to nimbus.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I reproduced this myself and it saw the following exception</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-03-30 13:31:55.974 o.a.s.t.s.AbstractNonblockingServer$FrameBuffer [ERROR] Unexpected throwable <span class="code-keyword">while</span> invoking!
java.lang.NullPointerException
at org.apache.storm.stats.StatsUtil.extractDataFromHb(StatsUtil.java:1509)
at org.apache.storm.stats.StatsUtil.extractDataFromHb(StatsUtil.java:1473)
at org.apache.storm.stats.StatsUtil.aggTopoExecsStats(StatsUtil.java:644)
at org.apache.storm.daemon.nimbus$fn__4160$exec_fn__784__auto__$reify__4189.getTopologyPageInfo(nimbus.clj:2081)
at org.apache.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3800)
at org.apache.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3784)
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39)
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)
at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)
at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:744)
2016-03-30 13:32:01.532 o.a.s.t.s.AbstractNonblockingServer$FrameBuffer [ERROR] Unexpected throwable <span class="code-keyword">while</span> invoking!
java.lang.NullPointerException
at org.apache.storm.stats.StatsUtil.extractDataFromHb(StatsUtil.java:1509)
at org.apache.storm.stats.StatsUtil.extractDataFromHb(StatsUtil.java:1473)
at org.apache.storm.stats.StatsUtil.aggTopoExecsStats(StatsUtil.java:644)
at org.apache.storm.daemon.nimbus$fn__4160$exec_fn__784__auto__$reify__4189.getTopologyPageInfo(nimbus.clj:2081)
at org.apache.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3800)
at org.apache.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3784)
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39)
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)
at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)
at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:744)
2016-03-30 13:33:21.375 o.a.s.t.s.AbstractNonblockingServer$FrameBuffer [ERROR] Unexpected throwable <span class="code-keyword">while</span> invoking!
java.lang.NullPointerException
at org.apache.storm.stats.StatsUtil.extractDataFromHb(StatsUtil.java:1509)
at org.apache.storm.stats.StatsUtil.extractDataFromHb(StatsUtil.java:1473)
at org.apache.storm.stats.StatsUtil.aggTopoExecsStats(StatsUtil.java:644)
at org.apache.storm.daemon.nimbus$fn__4160$exec_fn__784__auto__$reify__4189.getTopologyPageInfo(nimbus.clj:2081)
at org.apache.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3800)
at org.apache.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3784)
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39)
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)
at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)
at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>This looks like <a href="https://issues.apache.org/jira/browse/STORM-1665" title="Worker cannot instantiate kryo" class="issue-link" data-issue-key="STORM-1665"><del>STORM-1665</del></a> is exposing an issue with the stats code so the two are related, but somewhat separate.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user revans2 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1279</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1663" title="Clicking on an active topology from storm ui home page and then refreshing the page throws exception" class="issue-link" data-issue-key="STORM-1663"><del>STORM-1663</del></a>: Stats couldn't handle null worker HB. </p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/revans2/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/revans2/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1663" title="Clicking on an active topology from storm ui home page and then refreshing the page throws exception" class="issue-link" data-issue-key="STORM-1663"><del>STORM-1663</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1279.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1279.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1279</p>

<hr />
<p>commit ecf4586bc8f32b2c253c134ed0e7380b0a3f917a<br/>
Author: Robert (Bobby) Evans <evans@yahoo-inc.com><br/>
Date:   2016-03-30T19:01:08Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1663" title="Clicking on an active topology from storm ui home page and then refreshing the page throws exception" class="issue-link" data-issue-key="STORM-1663"><del>STORM-1663</del></a>: Stats couldn't handle null worker HB.</p>

<p>commit 08eb49e8122f7df607716cc7ed054b368b5b9b50<br/>
Author: Robert (Bobby) Evans <evans@yahoo-inc.com><br/>
Date:   2016-03-30T19:23:06Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1665" title="Worker cannot instantiate kryo" class="issue-link" data-issue-key="STORM-1665"><del>STORM-1665</del></a>: Worker cannot instantiate kryo</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://github.com/apache/storm/pull/1279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1279</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1279#issuecomment-203596039" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1279#issuecomment-203596039</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1279#issuecomment-203597011" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1279#issuecomment-203597011</a></p>

<p>    @knusbaum please look again, just fixes <a href="https://issues.apache.org/jira/browse/STORM-1666" title="Kill from the UI fails silently." class="issue-link" data-issue-key="STORM-1666"><del>STORM-1666</del></a> on this too, they are all related</p>
