### ISSUE TITLE
[STORM-1665] Worker cannot instantiate kryo

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5500]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NoClassDefFoundError: org/objenesis/strategy/InstantiatorStrategy
at org.apache.storm.serialization.DefaultKryoFactory.getKryo(DefaultKryoFactory.java:47) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:51) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.serialization.KryoValuesSerializer.<init>(KryoValuesSerializer.java:33) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.messaging.netty.Server.<init>(Server.java:71) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.messaging.netty.Context.bind(Context.java:67) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.worker$worker_data$fn__1953.invoke(worker.clj:280) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.util$assoc_apply_self.invoke(util.clj:201) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.worker$worker_data.invoke(worker.clj:277) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.worker$fn__2256$exec_fn__784__auto__$reify__2258.run(worker.clj:652) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0]
at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0]
at org.apache.storm.daemon.worker$fn__2256$exec_fn__784__auto____2257.invoke(worker.clj:650) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at clojure.lang.AFn.applyToHelper(AFn.java:178) ~[clojure-1.7.0.jar:?]
at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.7.0.jar:?]
at clojure.core$apply.invoke(core.clj:630) ~[clojure-1.7.0.jar:?]
at org.apache.storm.daemon.worker$fn__2256$mk_worker__2353.doInvoke(worker.clj:624) [storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.7.0.jar:?]
at org.apache.storm.daemon.worker$_main.invoke(worker.clj:821) [storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.7.0.jar:?]
at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:?]
at org.apache.storm.daemon.worker.main(Unknown Source) [storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
Caused by: java.lang.ClassNotFoundException: org.objenesis.strategy.InstantiatorStrategy
at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0]
at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0]
at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0]
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:424) ~[?:1.8.0]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0]
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:357) ~[?:1.8.0]
... 21 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1665" target="_blank">Worker cannot instantiate kryo</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-03-31T19:22:27+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Went in with <a href="https://issues.apache.org/jira/browse/STORM-1663" title="Clicking on an active topology from storm ui home page and then refreshing the page throws exception" class="issue-link" data-issue-key="STORM-1663"><del>STORM-1663</del></a></p>
