### ISSUE TITLE
[STORM-1672] Stats not get class cast exception

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5507]
<p>Component page in UI</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-03-31 14:21:44.576 o.a.s.t.s.AbstractNonblockingServer$FrameBuffer [ERROR] Unexpected throwable <span class="code-keyword">while</span> invoking!
java.lang.ClassCastException: java.lang.<span class="code-object">Long</span> cannot be <span class="code-keyword">cast</span> to java.util.Map
at org.apache.storm.stats.StatsUtil.filterSysStreams(StatsUtil.java:1696)
at org.apache.storm.stats.StatsUtil.aggPreMergeCompPageBolt(StatsUtil.java:240)
at org.apache.storm.stats.StatsUtil.aggCompExecStats(StatsUtil.java:1130)
at org.apache.storm.stats.StatsUtil.aggregateCompStats(StatsUtil.java:1108)
at org.apache.storm.stats.StatsUtil.aggCompExecsStats(StatsUtil.java:1236)
at org.apache.storm.daemon.nimbus$fn__3490$exec_fn__789__auto__$reify__3519.getComponentPageInfo(nimbus.clj:2130)
at org.apache.storm.generated.Nimbus$Processor$getComponentPageInfo.getResult(Nimbus.java:3826)
at org.apache.storm.generated.Nimbus$Processor$getComponentPageInfo.getResult(Nimbus.java:3810)
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39)
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)
at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)
at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:744)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1672" target="_blank">Stats not get class cast exception</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-05-16T07:32:34+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user revans2 opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1286" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1286</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1672" title="Stats not get class cast exception" class="issue-link" data-issue-key="STORM-1672"><del>STORM-1672</del></a>: Stats getting class cast exception</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/revans2/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/revans2/incubator-storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1672" title="Stats not get class cast exception" class="issue-link" data-issue-key="STORM-1672"><del>STORM-1672</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1286.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1286.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1286</p>

<hr />
<p>commit 6763f71b3e4f1d8e5b8f1f05b61f622db0969642<br/>
Author: Robert (Bobby) Evans <evans@yahoo-inc.com><br/>
Date:   2016-03-31T20:45:06Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1672" title="Stats not get class cast exception" class="issue-link" data-issue-key="STORM-1672"><del>STORM-1672</del></a>: Stats getting class cast exception</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1286#issuecomment-204127228" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1286#issuecomment-204127228</a></p>

<p>    LGTM. +1 </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1286#issuecomment-204127745" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1286#issuecomment-204127745</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1286#issuecomment-216482595" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1286#issuecomment-216482595</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a>, I merged into master.</p>
