### ISSUE TITLE
[STORM-1687] Divide by zero exception in stats

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5522]
<p>Since uptime can be 0, this will cause ArithmeticException: Divide by zero in compute-agg-capacity.</p>

<p>This will happen for both stats.clj in 1.x and StatsUtil.java in master (2.0).</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.ArithmeticException: Divide by zero
at clojure.lang.Numbers.divide(Numbers.java:156)
at clojure.core$SLASH.invoke(core.clj:986)
at clojure.lang.AFn.applyToHelper(AFn.java:156)
at clojure.lang.RestFn.applyTo(RestFn.java:132)
at clojure.core$apply.invoke(core.clj:626)
at backtype.storm.util$div.doInvoke(util.clj:355)
at clojure.lang.RestFn.invoke(RestFn.java:423)
at backtype.storm.stats$compute_agg_capacity$fn__2249.invoke(stats.clj:409)
at backtype.storm.stats$compute_agg_capacity.invoke(stats.clj:404)
at backtype.storm.stats$agg_pre_merge_topo_page_bolt.invoke(stats.clj:555)
at backtype.storm.stats$agg_topo_exec_stats_STAR_.invoke(stats.clj:724)
at backtype.storm.stats$fn__2319.invoke(stats.clj:772)
at clojure.lang.MultiFn.invoke(MultiFn.java:241)
at clojure.lang.AFn.applyToHelper(AFn.java:165)
at clojure.lang.AFn.applyTo(AFn.java:144)
at clojure.core$apply.invoke(core.clj:628)
at clojure.core$partial$fn__4230.doInvoke(core.clj:2470)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at clojure.core.protocols$fn__6086.invoke(protocols.clj:143)
at clojure.core.protocols$fn_6057$G6052_6066.invoke(protocols.clj:19)
at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
at clojure.core.protocols$fn_6031$G6026_6044.invoke(protocols.clj:13)
at clojure.core$reduce.invoke(core.clj:6289)
at backtype.storm.stats$aggregate_topo_stats.invoke(stats.clj:854)
at backtype.storm.stats$agg_topo_execs_stats.invoke(stats.clj:1008)
at backtype.storm.daemon.nimbus$fn_5838$exec_fn1478auto$reify_5862.getTopologyPageInfo(nimbus.clj:1729)
at backtype.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3651)
at backtype.storm.generated.Nimbus$Processor$getTopologyPageInfo.getResult(Nimbus.java:3635)
at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:39)
at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:39)
at backtype.storm.security.auth.SaslTransportPlugin$TUGIWrapProcessor.process(SaslTransportPlugin.java:143)
at org.apache.thrift7.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Zhuo Liu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1687" target="_blank">Divide by zero exception in stats</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Zhuo Liu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-04-11T21:36:56+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user zhuoliu opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1311" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1311</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1687" title="Divide by zero exception in stats" class="issue-link" data-issue-key="STORM-1687"><del>STORM-1687</del></a>-1.x divide by zero in stats</p>

<p>    This fixes the "divide by zero" error in stats/compute-agg-capacity.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/zhuoliu/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/zhuoliu/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1687" title="Divide by zero exception in stats" class="issue-link" data-issue-key="STORM-1687"><del>STORM-1687</del></a>-1.x-branch</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1311.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1311.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1311</p>

<hr />
<p>commit 7e5a74fddd82570107c401963fc971080b7fa54f<br/>
Author: zhuol <zhuol@yahoo-inc.com><br/>
Date:   2016-04-06T00:56:57Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1687" title="Divide by zero exception in stats" class="issue-link" data-issue-key="STORM-1687"><del>STORM-1687</del></a>-1.x divide by zero in stats</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user zhuoliu opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1312" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1312</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1687" title="Divide by zero exception in stats" class="issue-link" data-issue-key="STORM-1687"><del>STORM-1687</del></a> divide by zero in StatsUtil</p>

<p>    uptime sometimes equals to zero which causes divide exception.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/zhuoliu/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/zhuoliu/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1687" title="Divide by zero exception in stats" class="issue-link" data-issue-key="STORM-1687"><del>STORM-1687</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1312.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1312.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1312</p>

<hr />
<p>commit 44343318a116b8d546df3dedadc2bbea427ae3eb<br/>
Author: zhuol <zhuol@yahoo-inc.com><br/>
Date:   2016-04-06T01:03:02Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1687" title="Divide by zero exception in stats" class="issue-link" data-issue-key="STORM-1687"><del>STORM-1687</del></a> divide by zero in StatsUtil</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu" class="user-hover" rel="zhuoliu">Zhuo Liu</a> You added this issue to the epic. Does it mean that you're going to vote -1 on RC2 and add this before shipping?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>Just found that rc2 is already out, do we think we should add this bug fix to the 1.0.0 list and call an rc3 vote? <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a><br/>
This issue happened to our production, though not causing anything to crash.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>It depends on the priority of the issue.<br/>
If priority of the issue is critical or blocker, we just vote -1 with issue description on release vote thread.<br/>
IMO, if it doesn't crash anything (thus marked as non-critical or blocker), we could remove this issue from epic and add this as 1.0.1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user unsleepy22 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1312#issuecomment-206103981" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1312#issuecomment-206103981</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user redsanket commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1312#issuecomment-206451182" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1312#issuecomment-206451182</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user redsanket commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1311#issuecomment-206451308" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1311#issuecomment-206451308</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> Make sense. Deleted the epic link. We might later put this fix in 1.0.1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1311#issuecomment-208225585" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1311#issuecomment-208225585</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1312#issuecomment-208225804" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1312#issuecomment-208225804</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user satishd commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1311#issuecomment-208262202" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1311#issuecomment-208262202</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1312#issuecomment-208383656" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1312#issuecomment-208383656</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1312" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1312</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1311#issuecomment-208548610" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1311#issuecomment-208548610</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1721%20label%3Aepic">STORM-1721</a>]</i>
