### ISSUE TITLE
[STORM-1710] java.lang.ClassNotFoundException: backtype.storm.generated.LSSupervisorId

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5545]
<p>2016-04-14 09:07:22.226 o.a.s.d.supervisor <span class="error">&#91;ERROR&#93;</span> Error on initialization of server mk-supervisor<br/>
java.lang.RuntimeException: java.lang.ClassNotFoundException: backtype.storm.generated.LSSupervisorId<br/>
	at org.apache.storm.utils.LocalState.deserialize(LocalState.java:83)<br/>
	at org.apache.storm.utils.LocalState.get(LocalState.java:130)<br/>
	at org.apache.storm.local_state$ls_supervisor_id.invoke(local_state.clj:61)<br/>
	at org.apache.storm.daemon.supervisor$standalone_supervisor$reify__9646.prepare(supervisor.clj:1228)<br/>
	at org.apache.storm.daemon.supervisor$fn_<em>9503$exec_fn</em><em>1826</em><em>auto</em>___9504.invoke(supervisor.clj:781)<br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br/>
	at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
	at clojure.core$apply.invoke(core.clj:630)<br/>
	at org.apache.storm.daemon.supervisor$fn_<em>9503$mk_supervisor</em>_9548.doInvoke(supervisor.clj:779)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:436)<br/>
	at org.apache.storm.daemon.supervisor$_launch.invoke(supervisor.clj:1216)<br/>
	at org.apache.storm.daemon.supervisor$_main.invoke(supervisor.clj:1249)<br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:152)<br/>
	at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
	at org.apache.storm.daemon.supervisor.main(Unknown Source)<br/>
Caused by: java.lang.ClassNotFoundException: backtype.storm.generated.LSSupervisorId<br/>
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)<br/>
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)<br/>
	at java.security.AccessController.doPrivileged(Native Method)<br/>
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)<br/>
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)<br/>
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)<br/>
	at java.lang.Class.forName0(Native Method)<br/>
	at java.lang.Class.forName(Class.java:186)<br/>
	at org.apache.storm.utils.LocalState.deserialize(LocalState.java:78)<br/>
	... 14 more<br/>
2016-04-14 09:07:22.239 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error on initialization")<br/>
java.lang.RuntimeException: ("Error on initialization")<br/>
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423)<br/>
	at org.apache.storm.daemon.supervisor$fn_<em>9503$mk_supervisor</em>_9548.doInvoke(supervisor.clj:779)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:436)<br/>
	at org.apache.storm.daemon.supervisor$_launch.invoke(supervisor.clj:1216)<br/>
	at org.apache.storm.daemon.supervisor$_main.invoke(supervisor.clj:1249)<br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:152)<br/>
	at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
	at org.apache.storm.daemon.supervisor.main(Unknown Source)</p>

---
<details><summary><i>Originally reported by <a title="Guangxin Zhang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=江山如画">江山如画</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1710" target="_blank">java.lang.ClassNotFoundException: backtype.storm.generated.LSSupervisorId</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2016-04-14T14:38:34+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=江山如画">江山如画</a>:</i>
<p>storm-core-0.10.0.jar <br/>
    -backtype.storm.generated<br/>
but in storm-core-1.0.0.jar<br/>
    -org.apache.storm.generated<br/>
so, java.lang.ClassNotFoundException: backtype.storm.generated.LSSupervisorId<br/>
is there something change when make storm-core jar ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=江山如画">江山如画</a>:</i>
<p>i found this in storm-1.0.0 pom.xml,<br/>
<configuration><br/>
    <excludes><br/>
<exclude>org/apache/storm/generated/*</exclude> <!-<del>Thrift generated code</del>-><br/>
    </excludes><br/>
    <includes><br/>
<include>backtype/<b>/</b>/<b>/</b></include><br/>
<include>backtype/<b>/</b>/*</include><br/>
<include>backtype/<b>/</b></include><br/>
<include>backtype/*</include><br/>
<include>zilch/*</include><br/>
<include>storm/<b>/</b>/<b>/</b></include><br/>
<include>storm/<b>/</b>/*</include><br/>
<include>storm/<b>/</b></include><br/>
<include>storm/*</include><br/>
    </includes><br/>
</configuration></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>The issue is that with storm 1.0 we moved from backtype.storm to org.apache.storm.  This is not a rolling upgrade so if you have any state in zookeeper or stored on the local disk for your cluster you need to delete it, and also update any configs that you have that are pointing to backtype.storm classes.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p>If you don't want to clean the older storm, you can choose an other directory for storm 1.0.0. To do that, change the <b>storm.local.dir</b> and <b>storm.zookeeper.root</b> e.g.</p>

<p>storm.local.dir: "storm-local-1"<br/>
storm.zookeeper.root: "/storm-1"</p>
