### ISSUE TITLE
[STORM-1747] storm-kafka-client KafkaSpoutRetryExponentialBackoff throws exception

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5582]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.ClassCastException: org.apache.kafka.common.TopicPartition cannot be <span class="code-keyword">cast</span> to java.lang.Comparable
	at java.util.TreeMap.compare(TreeMap.java:1188) ~[?:1.7.0_80]
	at java.util.TreeMap.put(TreeMap.java:531) ~[?:1.7.0_80]
	at java.util.TreeSet.add(TreeSet.java:255) ~[?:1.7.0_80]
	at org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff.retriableTopicPartitions(KafkaSpoutRetryExponentialBackoff.java:170) ~[storm-kafka-client-1.0.0.jar:1.0.0]
	at org.apache.storm.kafka.spout.KafkaSpout.doSeekRetriableTopicPartitions(KafkaSpout.java:245) ~[storm-kafka-client-1.0.0.jar:1.0.0]
	at org.apache.storm.kafka.spout.KafkaSpout.pollKafkaBroker(KafkaSpout.java:236) ~[storm-kafka-client-1.0.0.jar:1.0.0]
	at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:202) ~[storm-kafka-client-1.0.0.jar:1.0.0]
	at org.apache.storm.daemon.executor$fn__7877$fn__7892$fn__7923.invoke(executor.clj:647) ~[storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.util$async_loop$fn__625.invoke(util.clj:484) [storm-core-1.0.0.jar:1.0.0]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.7.0_80]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jifeng Yin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=flisky">flisky</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1747" target="_blank">storm-kafka-client KafkaSpoutRetryExponentialBackoff throws exception</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Hugo Da Cruz Louro" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmclouro">hmclouro</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2016-04-30T16:21:13+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=flisky" class="user-hover" rel="flisky">Jifeng Yin</a> can you add kafka version details as well.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmclouro">hmclouro</a>:</i>
<p>This bug has already been fixed and merged into 1.x-branch. There is currently a PR based off master.<br/>
<a href="https://github.com/apache/storm/pull/1382" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1382</a></p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1725">STORM-1725</a>]</i>
