### ISSUE TITLE
[STORM-1762] storm pom.xml miss some dependency

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5597]
<p>Hi, all:<br/>
    I download storm v0.9.5 from github, and want to compile and install it with maven. Unfortunately, I got the following errors when I use command "mvn clean install -DskipTests -X":<br/>
    ...<br/>
   <span class="error">&#91;ERROR&#93;</span> Failed to execute goal com.theoryinpractise:clojure-maven-plugin:1.3.18:compile (compile-clojure) on project storm-core: Clojure failed. -> <span class="error">&#91;Help 1&#93;</span><br/>
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.theoryinpractise:clojure-maven-plugin:1.3.18:compile (compile-clojure) on project storm-core: Clojure failed.<br/>
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)<br/>
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)<br/>
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)<br/>
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)<br/>
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)<br/>
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)<br/>
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)<br/>
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)<br/>
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)<br/>
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)<br/>
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)<br/>
at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)<br/>
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/>
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
at java.lang.reflect.Method.invoke(Method.java:606)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)<br/>
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)<br/>
Caused by: org.apache.maven.plugin.MojoExecutionException: Clojure failed.<br/>
at com.theoryinpractise.clojure.AbstractClojureCompilerMojo.callClojureWith(AbstractClojureCompilerMojo.java:453)<br/>
at com.theoryinpractise.clojure.AbstractClojureCompilerMojo.callClojureWith(AbstractClojureCompilerMojo.java:367)<br/>
at com.theoryinpractise.clojure.AbstractClojureCompilerMojo.callClojureWith(AbstractClojureCompilerMojo.java:344)<br/>
at com.theoryinpractise.clojure.ClojureCompilerMojo.execute(ClojureCompilerMojo.java:47)<br/>
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)<br/>
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)<br/>
... 19 more</p>

<p>    The trace log only shows something wrong in the process of clojure compile. To slove this problem I debug and found the deep cause: the storm-core pom.xml missing some dependency package, and I have made a path file.</p>

---
<details><summary><i>Originally reported by <a title="L.Z. Xiang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xiangLZ">xiangLZ</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1762" target="_blank">storm pom.xml miss some dependency</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="L.Z. Xiang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xiangLZ">xiangLZ</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:09+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xianglz">xianglz</a>:</i>
<p>storm/pom.xml and storm/storm-core/pom.xml patch file which is generated by git diff</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
