### ISSUE TITLE
[STORM-1776] Error when processing event java.io.FileNotFoundException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5611]
<p>when i am trying to start storm cluster , i got the below error.<br/>
24628 <span class="error">&#91;Thread-10&#93;</span> INFO  o.a.s.d.supervisor - Copying resources at jar:<a href="file:/D:/.m2/repository/org/apache/storm/flux-core/1.0.0/flux-core-1.0.0.jar!/resources" class="external-link" target="_blank" rel="nofollow noopener">file:/D:/.m2/repository/org/apache/storm/flux-core/1.0.0/flux-core-1.0.0.jar!/resources</a> to C:\Users\MAGESH~1\AppData\Local\Temp\1991ad4f-acbc-44ed-b07b-24643381f7a0\supervisor\stormdist\test-1-1462884218\resources<br/>
24631 <span class="error">&#91;Thread-10&#93;</span> ERROR o.a.s.event - Error when processing event<br/>
java.io.FileNotFoundException: Source 'file:\D:\.m2\repository\org\apache\storm\flux-core\1.0.0\flux-core-1.0.0.jar!\resources' does not exist<br/>
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor$fn__9351.invoke(supervisor.clj:1194) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at clojure.lang.MultiFn.invoke(MultiFn.java:243) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this_<em>9070$fn</em>_9088.invoke(supervisor.clj:582) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9070.invoke(supervisor.clj:581) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.event$event_manager$fn__8622.invoke(event.clj:40) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_65&#93;</span><br/>
24638 <span class="error">&#91;Thread-8&#93;</span> INFO  o.a.s.d.supervisor - Copying resources at jar:<a href="file:/D:/.m2/repository/org/apache/storm/flux-core/1.0.0/flux-core-1.0.0.jar!/resources" class="external-link" target="_blank" rel="nofollow noopener">file:/D:/.m2/repository/org/apache/storm/flux-core/1.0.0/flux-core-1.0.0.jar!/resources</a> to C:\Users\MAGESH~1\AppData\Local\Temp\f4009546-87fe-4885-a0b0-cb775e8b784f\supervisor\stormdist\test-1-1462884218\resources<br/>
24638 <span class="error">&#91;Thread-8&#93;</span> ERROR o.a.s.event - Error when processing event<br/>
java.io.FileNotFoundException: Source 'file:\D:\.m2\repository\org\apache\storm\flux-core\1.0.0\flux-core-1.0.0.jar!\resources' does not exist<br/>
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor$fn__9351.invoke(supervisor.clj:1194) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at clojure.lang.MultiFn.invoke(MultiFn.java:243) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this_<em>9070$fn</em>_9088.invoke(supervisor.clj:582) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9070.invoke(supervisor.clj:581) ~<span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at org.apache.storm.event$event_manager$fn__8622.invoke(event.clj:40) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_65&#93;</span><br/>
24642 <span class="error">&#91;Thread-10&#93;</span> ERROR o.a.s.util - Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at org.apache.storm.event$event_manager$fn__8622.invoke(event.clj:48) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_65&#93;</span><br/>
24643 <span class="error">&#91;Thread-8&#93;</span> ERROR o.a.s.util - Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at org.apache.storm.event$event_manager$fn__8622.invoke(event.clj:48) <span class="error">&#91;storm-core-1.0.0.jar:1.0.0&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_65&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Mageshkumar" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mageshrkumar">mageshrkumar</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1776" target="_blank">Error when processing event java.io.FileNotFoundException</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:05+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
