### ISSUE TITLE
[STORM-1837] Running local clusters without simulating time breaks Testing.completeTopology, and may cause message loss

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5620]
<p>Since <a href="https://github.com/apache/storm/pull/810" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/810</a> it is no longer possible to call Testing.completeTopology when time is not simulating, because a call to advance-cluster-time is made from the function, which calls Time/advanceTime. advance-cluster-time should only be called if time is simulating.</p>

<p>Since <a href="https://github.com/apache/storm/pull/830" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/830</a> a local cluster run without time simulation may lose messages. When a worker emits messages for a worker that hasn't started yet, the message is lost. This can happen because spouts may start emitting before all workers have started, when time simulation is disabled. Local clusters usually run without message timeouts, so this will make tests relying on Testing.withLocalCluster flaky.</p>

<p>The problem is that there are no longer any queues to store messages for workers that haven't started yet. See <a href="https://github.com/apache/storm/pull/830/files#diff-c6ff4208ef84c7a5a1a6b8b6bd1f7d19R104" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/830/files#diff-c6ff4208ef84c7a5a1a6b8b6bd1f7d19R104</a>. A queue should be added for messages for workers that haven't registered a receive callback yet.</p>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1837" target="_blank">Running local clusters without simulating time breaks Testing.completeTopology, and may cause message loss</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-09-19T21:44:15+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1417#issuecomment-219545865" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1417#issuecomment-219545865</a></p>

<p>    The code changes look good. <br/>
    I ran unit test and had `netty_unit_test` timeout once. I think we need to change the timeout for <a href="https://github.com/apache/storm/blob/master/storm-core/test/clj/org/apache/storm/messaging/netty_unit_test.clj#L115" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/test/clj/org/apache/storm/messaging/netty_unit_test.clj#L115</a></p>

<p>    ```<br/>
    <error message="Uncaught exception, not in assertion.">Uncaught exception, not in assertion.<br/>
    expected: nil<br/>
      actual: java.lang.AssertionError: Test timed out (5000ms) (empty? (.getLoad client <span class="error">&#91;(int 1) (int 2)&#93;</span>))<br/>
     at org.apache.storm.messaging.netty_unit_test$test_load_fn.invoke (netty_unit_test.clj:115)<br/>
org.apache.storm.messaging.netty_unit_test/fn (netty_unit_test.clj:143)<br/>
clojure.test$test_var$fn__7670.invoke (test.clj:704)<br/>
clojure.test$test_var.invoke (test.clj:704)<br/>
clojure.test$test_vars$fn_<em>7692$fn</em>_7697.invoke (test.clj:722)<br/>
clojure.test$default_fixture.invoke (test.clj:674)<br/>
clojure.test$test_vars$fn__7692.invoke (test.clj:722)<br/>
clojure.test$default_fixture.invoke (test.clj:674)<br/>
clojure.test$test_vars.invoke (test.clj:718)<br/>
clojure.test$test_all_vars.invoke (test.clj:728)<br/>
clojure.test$test_ns.invoke (test.clj:747)<br/>
clojure.core$map$fn__4553.invoke (core.clj:2624)<br/>
clojure.lang.LazySeq.sval (LazySeq.java:40)<br/>
clojure.lang.LazySeq.seq (LazySeq.java:49)<br/>
clojure.lang.Cons.next (Cons.java:39)<br/>
clojure.lang.RT.boundedLength (RT.java:1735)<br/>
clojure.lang.RestFn.applyTo (RestFn.java:130)<br/>
clojure.core$apply.invoke (core.clj:632)<br/>
clojure.test$run_tests.doInvoke (test.clj:762)<br/>
clojure.lang.RestFn.invoke (RestFn.java:408)<br/>
org.apache.storm.testrunner$eval8790$iter_<em>8791</em><em>8795$fn</em><em>8796$fn</em><em>8797$fn</em>_8798.invoke (test_runner.clj:107)<br/>
org.apache.storm.testrunner$eval8790$iter_<em>8791</em><em>8795$fn</em><em>8796$fn</em>_8797.invoke (test_runner.clj:53)<br/>
org.apache.storm.testrunner$eval8790$iter_<em>8791</em><em>8795$fn</em>_8796.invoke (test_runner.clj:52)<br/>
clojure.lang.LazySeq.sval (LazySeq.java:40)<br/>
clojure.lang.LazySeq.seq (LazySeq.java:49)<br/>
clojure.lang.RT.seq (RT.java:507)<br/>
clojure.core/seq (core.clj:137)<br/>
clojure.core$dorun.invoke (core.clj:3009)<br/>
org.apache.storm.testrunner$eval8790.invoke (test_runner.clj:52)<br/>
clojure.lang.Compiler.eval (Compiler.java:6782)<br/>
clojure.lang.Compiler.load (Compiler.java:7227)<br/>
clojure.lang.Compiler.loadFile (Compiler.java:7165)<br/>
clojure.main$load_script.invoke (main.clj:275)<br/>
clojure.main$script_opt.invoke (main.clj:337)<br/>
clojure.main$main.doInvoke (main.clj:421)<br/>
clojure.lang.RestFn.invoke (RestFn.java:421)<br/>
clojure.lang.Var.invoke (Var.java:383)<br/>
clojure.lang.AFn.applyToHelper (AFn.java:156)<br/>
clojure.lang.Var.applyTo (Var.java:700)<br/>
clojure.main.main (main.java:37)</p>

<p>  at: test_runner.clj:105</error><br/>
    </testcase><br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user srdo commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1417#issuecomment-219549248" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1417#issuecomment-219549248</a></p>

<p>    I'd be happy to bump it. I don't think test-load-fn actually hits any of the changed code though, since it uses the netty.Context rather than local.Context. What do you think is a reasonable timeout? 15-20 seconds?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1417#issuecomment-219600127" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1417#issuecomment-219600127</a></p>

<p>    @kishorvpatil <br/>
    Nice finding. I think it should reflect STORM_TEST_TIMEOUT_MS, but it can be done with another JIRA issue since it seems not related on this PR.</p>

<p>    Btw, other test failure is observed from Travis CI, which I think is also not related to this PR.</p>

<p>    ```<br/>
    Running org.apache.storm.utils.DisruptorQueueTest<br/>
    Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.352 sec <<< FAILURE! - in org.apache.storm.utils.DisruptorQueueTest<br/>
    testInOrderBatch(org.apache.storm.utils.DisruptorQueueTest)  Time elapsed: 0.405 sec  <<< FAILURE!<br/>
    junit.framework.AssertionFailedError: producer 0 is still alive<br/>
    	at junit.framework.Assert.fail(Assert.java:57)<br/>
    	at junit.framework.Assert.assertTrue(Assert.java:22)<br/>
    	at junit.framework.Assert.assertFalse(Assert.java:39)<br/>
    	at junit.framework.TestCase.assertFalse(TestCase.java:210)<br/>
    	at org.apache.storm.utils.DisruptorQueueTest.run(DisruptorQueueTest.java:135)<br/>
    	at org.apache.storm.utils.DisruptorQueueTest.testInOrderBatch(DisruptorQueueTest.java:106)<br/>
    ```</p>

<p>    @srdo <br/>
    I guess what @kishorvpatil reported is a kind of intermittent failure, since one of storm-core build is passed on Travis CI.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user srdo commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1417#issuecomment-219674715" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1417#issuecomment-219674715</a></p>

<p>    Something like this? <a href="https://github.com/apache/storm/pull/1421" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1421</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1417#issuecomment-219741531" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1417#issuecomment-219741531</a></p>

<p>    @HeartSaVioR, you are right, I did not notice the `DisruptorQueueTest` failure.<br/>
    @srdo, Thank you for putting up #1421. It's ironic to see `LocalNimbusTest` fail for that PR. <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/> I am bumping this on up.<br/>
    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>,</p>

<p>I merged this into master and branch-1.x</p>
