### ISSUE TITLE
[STORM-1842] Forward references in storm.thrift cause tooling issues

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5625]
<p>In recent versions of Storm (starting with version 1.0.0, I believe), storm.thrift uses several types before they are declared:</p>

<ul>
	<li>HBPulse</li>
	<li>HBRecords</li>
	<li>HBNodes</li>
</ul>

<p>These types are used in the definition of HBMessageData.</p>

<p>This causes issues with downstream tools. For example, generating Python wrappers for the Storm Thrift types creates a module that will not import successfully.</p>

<p>Would it be possible to reorder this code to define the types before using them? This appears to be a simple change.</p>

---
<details><summary><i>Originally reported by <a title="Barry Hart" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart">barrywhart</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1842" target="_blank">Forward references in storm.thrift cause tooling issues</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-05-20T19:15:09+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart">barrywhart</a>:</i>
<p>I'm marking this as critical because it is preventing Petrel, a Python wrapper for Storm, from supporting Storm 1.0 and beyond.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart">barrywhart</a>:</i>
<p><a href="https://github.com/AirSage/Petrel/issues/75" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/AirSage/Petrel/issues/75</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart">barrywhart</a>:</i>
<p>Error message from generated Python:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/vagrant/petrel/petrel/cmdline.py", line 12, in <module>
    from .package import build_jar
  File "/vagrant/petrel/petrel/package.py", line 13, in <module>
    from topologybuilder import TopologyBuilder
  File "/vagrant/petrel/petrel/topologybuilder.py", line 6, in <module>
    from petrel.generated.storm.ttypes import ComponentCommon, Grouping, NullStruct, GlobalStreamId
  File "/vagrant/petrel/petrel/generated/storm/ttypes.py", line 10080, in <module>
    class HBMessageData:
  File "/vagrant/petrel/petrel/generated/storm/ttypes.py", line 10094, in HBMessageData
    (2, TType.STRUCT, 'pulse', (HBPulse, HBPulse.thrift_spec), None, ), # 2
NameError: name 'HBPulse' is not defined
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart">barrywhart</a>:</i>
<p>Attached file ttypes.py references HBPulse before its definition. This occurs with the latest Python thrift library (0.9.3).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1423#issuecomment-219698986" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1423#issuecomment-219698986</a></p>

<p>    I'm not sure it breaks backward compatibility, so if anyone checks it doesn't break compatibility that would be great.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart">barrywhart</a>:</i>
<p>More of a general question &#8211; are there any automated tests for the generated Python code? Simply attempting to import ttypes.py would've detected this error. If there is no such test, adding one could help avoid problems like this in the future.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1423#issuecomment-219709570" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1423#issuecomment-219709570</a></p>

<p>    @barrywhart <br/>
    <a href="https://repository.apache.org/releases/" class="external-link" target="_blank" rel="nofollow noopener">https://repository.apache.org/releases/</a> returns 503 now, which makes Travis CI failed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Yeah, good to have a new JIRA issue, and if you would contribute that I'd be really appreciated! </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart">barrywhart</a>:</i>
<p>Done. <a href="https://issues.apache.org/jira/browse/STORM-1846" title="Need a smoke test for the generated Python code" class="issue-link" data-issue-key="STORM-1846"><del>STORM-1846</del></a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart" class="user-hover" rel="barrywhart">Barry Hart</a> <br/>
Here's custom build of Storm 1.0.2 SNAPSHOT + <a href="https://issues.apache.org/jira/browse/STORM-1842" title="Forward references in storm.thrift cause tooling issues" class="issue-link" data-issue-key="STORM-1842"><del>STORM-1842</del></a> patch.<br/>
<a href="http://people.apache.org/~kabhwan/storm-core-1.0.2-SNAPSHOT.jar" class="external-link" target="_blank" rel="nofollow noopener">http://people.apache.org/~kabhwan/storm-core-1.0.2-SNAPSHOT.jar</a></p>

<p>If it incurs other issues please let me know so that I just apply <a href="https://issues.apache.org/jira/browse/STORM-1842" title="Forward references in storm.thrift cause tooling issues" class="issue-link" data-issue-key="STORM-1842"><del>STORM-1842</del></a> with Storm 1.0.1 and rebuild.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barrywhart">barrywhart</a>:</i>
<p>I tested with the updated storm.thrift from your pull request. This addresses my Python thrift issues.</p>

<p>I'm now working on some unrelated Java compilation and runtime issues.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user barrywhart commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1423#issuecomment-219865469" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1423#issuecomment-219865469</a></p>

<p>    I tested with the updated storm.thrift from this pull request. It addresses the Python Thrift issues I was encountering.</p>

<p>    From my perspective, this change is ready for merge.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1434#issuecomment-220489095" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1434#issuecomment-220489095</a></p>

<p>    Hi @et1975 thanks for the contribution. It's filed to <a href="https://issues.apache.org/jira/browse/STORM-1842" title="Forward references in storm.thrift cause tooling issues" class="issue-link" data-issue-key="STORM-1842"><del>STORM-1842</del></a> and #1423 is also ready to review.<br/>
    Could you check #1423 and see it also works for C# thrift compiler?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1423#issuecomment-220677726" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1423#issuecomment-220677726</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1424#issuecomment-220677791" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1424#issuecomment-220677791</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1425#issuecomment-220677854" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1425#issuecomment-220677854</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1424" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1424</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1425" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1425</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Merged to master, 1.0.x and 1.x branches.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a> Seems like you missed to merge this to master. (pull request is not closed and storm.thrift is same.) I'll handle it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1423#issuecomment-220884435" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1423#issuecomment-220884435</a></p>

<p>    I merged into master but github seems to not recognize merge commits as pull request. <br/>
    Closed via 45e62a75ce667012fa0cf74e1543784b1620d36b</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1423" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1423</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Merged. Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz" class="user-hover" rel="ptgoetz">P. Taylor Goetz</a> for reviewing and merging!</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1855%20label%3Aepic">STORM-1855</a>]</i>
