### ISSUE TITLE
[STORM-1854] Trident transactional spouts are broken in 1.0.x

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5637]
<p>In the process of upgrading our Storm code from 0.10.0 to 1.0.0, I've run into an issue with TransactionalTridentKafkaSpout. When running one of our topologies I'm getting the following exception:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be <span class="code-keyword">cast</span> to java.lang.<span class="code-object">Integer</span>
	at org.apache.storm.trident.spout.PartitionedTridentSpoutExecutor$Coordinator.initializeTransaction(PartitionedTridentSpoutExecutor.java:55) ~[storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.trident.spout.PartitionedTridentSpoutExecutor$Coordinator.initializeTransaction(PartitionedTridentSpoutExecutor.java:43) ~[storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.trident.spout.TridentSpoutCoordinator.execute(TridentSpoutCoordinator.java:70) ~[storm-core-1.0.0.jar:1.0.0]
	at org.apache.storm.topology.BasicBoltExecutor.execute(BasicBoltExecutor.java:50) ~[storm-core-1.0.0.jar:1.0.0]
</pre>
</div></div>

<p>The issue appears to be caused by a change in PartitionedTridentSpoutExecutor between the two versions, specifically this method:</p>

<p>1.0.0 - <a href="https://github.com/apache/storm/blob/v1.0.0/storm-core/src/jvm/org/apache/storm/trident/spout/PartitionedTridentSpoutExecutor.java#L51" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v1.0.0/storm-core/src/jvm/org/apache/storm/trident/spout/PartitionedTridentSpoutExecutor.java#L51</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">public</span> <span class="code-object">Integer</span> initializeTransaction(<span class="code-object">long</span> txid, <span class="code-object">Integer</span> prevMetadata, <span class="code-object">Integer</span> currMetadata) {
    <span class="code-keyword">if</span>(currMetadata!=<span class="code-keyword">null</span>) {
<span class="code-keyword">return</span> currMetadata;
    } <span class="code-keyword">else</span> {
<span class="code-keyword">return</span> _coordinator.getPartitionsForBatch();    
    }
}
</pre>
</div></div>

<p>0.10.0 - <a href="https://github.com/apache/storm/blob/v0.10.0/storm-core/src/jvm/storm/trident/spout/PartitionedTridentSpoutExecutor.java#L51" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v0.10.0/storm-core/src/jvm/storm/trident/spout/PartitionedTridentSpoutExecutor.java#L51</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">public</span> <span class="code-object">Object</span> initializeTransaction(<span class="code-object">long</span> txid, <span class="code-object">Object</span> prevMetadata, <span class="code-object">Object</span> currMetadata) {
    <span class="code-keyword">if</span>(currMetadata!=<span class="code-keyword">null</span>) {
<span class="code-keyword">return</span> currMetadata;
    } <span class="code-keyword">else</span> {
<span class="code-keyword">return</span> _coordinator.getPartitionsForBatch();    
    }
}
</pre>
</div></div>

<p>This was introduced by: <a href="https://github.com/apache/storm/commit/9e4c3df17ffbc737210e606d3d8a9cdae8f86634" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/commit/9e4c3df17ffbc737210e606d3d8a9cdae8f86634</a></p>

<p>TransactionalTridentKafkaSpout uses List<GlobalPartitionInformation> for its metadata. Generally, transactional spouts should have metadata that is more complex than just an Integer. OpaquePartitionedTridentSpoutExecutor uses Object for its metadata and correctly handles the metadata used by OpaqueTridentKafkaSpout (List<GlobalPartitionInformation>).</p>

<p>It looks like reverting the metadata type for transactional spouts in PartitionedTridentSpoutExecutor should work, but I haven't tried this yet.</p>

---
<details><summary><i>Originally reported by <a title="Morrigan Jones" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=morrigan.jones@gmail.com">morrigan.jones@gmail.com</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1854" target="_blank">Trident transactional spouts are broken in 1.0.x</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2016-05-20T21:03:17+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=morrigan.jones@gmail.com">morrigan.jones@gmail.com</a>:</i>
<p>Looks like this is a duplicate of <a href="https://issues.apache.org/jira/browse/STORM-1728" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1728</a></p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1728">STORM-1728</a>]</i>
