### ISSUE TITLE
[STORM-1887] Help message for the set_log_level command does not have the topology name parameter

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5669]
<p>The help message for the set_log_level command does not have the topology-name parameter:</p>

<p>$ storm help set_log_level</p>

<p>    Dynamically change topology log levels</p>

<p>    Syntax: [storm set_log_level -l <span class="error">&#91;logger name&#93;</span>=<span class="error">&#91;log level&#93;</span><span class="error">&#91;:optional timeout&#93;</span> -r <span class="error">&#91;logger name&#93;</span><br/>
    where log level is one of:<br/>
ALL, TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF<br/>
    and timeout is integer seconds.<br/>
(...)</p>

<p>If you don't pass a `topology-name` as last parameter, you'll get the following error:</p>

<p>$ storm set_log_level -l com.myapp=WARN<br/>
Running: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/usr/local/Cellar/storm/1.0.1/libexec -Dstorm.log.dir=/usr/local/Cellar/storm/1.0.1/libexec/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /usr/local/Cellar/storm/1.0.1/libexec/lib/asm-5.0.3.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/clojure-1.7.0.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/disruptor-3.3.2.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/kryo-3.0.3.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-api-2.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-core-2.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-over-slf4j-1.6.6.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-slf4j-impl-2.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/minlog-1.3.0.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/objenesis-2.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/reflectasm-1.10.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/servlet-api-2.5.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/slf4j-api-1.7.7.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/storm-core-1.0.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/storm-rename-hack-1.0.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/conf:/usr/local/Cellar/storm/1.0.1/libexec/bin org.apache.storm.command.set_log_level -l com.myapp=WARN<br/>
2670 <span class="error">&#91;main&#93;</span> INFO  o.a.s.c.set-log-level - Sent log config LogConfig(named_logger_level:</p>
{com.myapp=LogLevel(action:UPDATE, target_log_level:WARN, reset_log_level_timeout_secs:0)}
<p>) for topology<br/>
Exception in thread "main" java.lang.IllegalArgumentException: No matching field found: IllegalArgumentException for class java.lang.String<br/>
    at clojure.lang.Reflector.getInstanceField(Reflector.java:271)<br/>
    at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:315)<br/>
    at org.apache.storm.command.set_log_level$get_storm_id.invoke(set_log_level.clj:31)<br/>
    at org.apache.storm.command.set_log_level$_main.doInvoke(set_log_level.clj:75)<br/>
    at clojure.lang.RestFn.applyTo(RestFn.java:137)<br/>
    at org.apache.storm.command.set_log_level.main(Unknown Source)<br/>
(...)</p>

<p>I opened a PR to fix this: <a href="https://github.com/apache/storm/pull/1463" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1463</a></p>

---
<details><summary><i>Originally reported by <a title="Francisco Lopes" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=falmp">falmp</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1887" target="_blank">Help message for the set_log_level command does not have the topology name parameter</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Francisco Lopes" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=falmp">falmp</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-06-08T16:28:53+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user falmp commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1463" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1463</a></p>

<p>    Sure: <a href="https://issues.apache.org/jira/browse/STORM-1887" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1887</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1463" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1463</a></p>

<p>    @falmp Do you mind editing the title of this PR so it starts with "<a href="https://issues.apache.org/jira/browse/STORM-1887" title="Help message for the set_log_level command does not have the topology name parameter" class="issue-link" data-issue-key="STORM-1887"><del>STORM-1887</del></a>: "? That way any comments here will get mirrored to JIRA as well.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1463" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1463</a></p>

<p>    +1 </p>

<p>    Thanks @falmp!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1463" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1463</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1463" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1463</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=harshach" class="user-hover" rel="harshach">Harsha Chadhar</a> When merging to multiple branches, please leave a comment as to which branches it was merged to. That makes it much easier to track.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Merged to master, 1.x-branch and 1.0.x-branch.</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1855%20label%3Aepic">STORM-1855</a>]</i>
