### ISSUE TITLE
[STORM-1903] Intermittent Travis test failures in org.apache.storm.nimbus.LocalNimbusTest.testSubmitTopologyToLocalNimbus

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5685]
<p>testSubmitTopologyToLocalNimbus fails with following error</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.RuntimeException: org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
	at org.apache.storm.generated.Nimbus$Client.recv_getTopologyInfo(Nimbus.java:1182)
	at org.apache.storm.generated.Nimbus$Client.getTopologyInfo(Nimbus.java:1169)
	at org.apache.storm.utils.Utils.getTopologyInfo(Utils.java:1465)
	at org.apache.storm.LocalCluster$submit_hook.invoke(LocalCluster.clj:44)
	at org.apache.storm.LocalCluster$_submitTopology.invoke(LocalCluster.clj:52)
	at org.apache.storm.LocalCluster.submitTopology(Unknown Source)
	at org.apache.storm.nimbus.LocalNimbusTest.testSubmitTopologyToLocalNimbus(LocalNimbusTest.java:65)
</pre>
</div></div>

<p>The exception on server is </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>283607 [pool-75-thread-3] ERROR o.a.t.s.AbstractNonblockingServer$FrameBuffer - Unexpected throwable while invoking!
java.lang.NullPointerException
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:26) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__4758$iter__4869__4873$fn__4874.invoke(nimbus.clj:1870) ~[classes/:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.7.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.seq(RT.java:507) ~[clojure-1.7.0.jar:?]
	at clojure.core$seq__4128.invoke(core.clj:137) ~[clojure-1.7.0.jar:?]
	at clojure.core$dorun.invoke(core.clj:3009) ~[clojure-1.7.0.jar:?]
	at clojure.core$doall.invoke(core.clj:3025) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__4758.getTopologyInfoWithOpts(nimbus.clj:1868) ~[classes/:?]
	at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__4758.getTopologyInfo(nimbus.clj:1907) ~[classes/:?]
	at org.apache.storm.generated.Nimbus$Processor$getTopologyInfo.getResult(Nimbus.java:3748) ~[classes/:?]
	at org.apache.storm.generated.Nimbus$Processor$getTopologyInfo.getResult(Nimbus.java:3732) ~[classes/:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158) ~[classes/:?]
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.server.Invocation.run(Invocation.java:18) [libthrift-0.9.3.jar:0.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Abhishek Agarwal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1903" target="_blank">Intermittent Travis test failures in org.apache.storm.nimbus.LocalNimbusTest.testSubmitTopologyToLocalNimbus</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:46+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I think it much be a race between when the nimbus daemon is up and ready to serve requests, and at what point we submit the topology.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Please don't put in a sleep, we need a way to tell if it is bound or not, because the test already takes over 30 seconds, adding in more delays is far from ideal. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Actually I am wrong, the NPE indicates that the connection was up, but for some reason nimbus had an issue with getting the cluster info and there was something null in the data structure.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Looks like there are cases where beats which comes from the heart beat cache can be nil.  We are checking other places for the values in it if they are nil, but not beats itself.  It should be a simple one line fix.</p>
