### ISSUE TITLE
[STORM-1925] Nimbus fails to start in secure mode 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5707]
<p>We are noticing a failure in secure cluster as nimbus failed to start<br/>
2016-06-23 06:43:48.874 o.a.s.d.nimbus <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
java.lang.NullPointerException<br/>
	at org.apache.storm.security.auth.authorizer.SimpleACLAuthorizer.permit(SimpleACLAuthorizer.java:114)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:497)<br/>
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)<br/>
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)<br/>
	at org.apache.storm.daemon.nimbus$check_authorization_BANG_.invoke(nimbus.clj:1047)<br/>
	at org.apache.storm.daemon.nimbus$check_authorization_BANG_.invoke(nimbus.clj:1051)<br/>
	at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__11183.getClusterInfo(nimbus.clj:1772)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:497)<br/>
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)<br/>
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)<br/>
	at org.apache.storm.daemon.nimbus$send_cluster_metrics_to_executors.invoke(nimbus.clj:1393)<br/>
	at org.apache.storm.daemon.nimbus$fn_<em>11394$exec_fn</em><em>3529</em><em>auto</em>__<em>11395$fn</em>_11421.invoke(nimbus.clj:2254)<br/>
	at org.apache.storm.timer$schedule_recurring$this__2156.invoke(timer.clj:105)<br/>
	at org.apache.storm.timer$mk_timer$fn_<em>2139$fn</em>_2140.invoke(timer.clj:50)<br/>
	at org.apache.storm.timer$mk_timer$fn__2139.invoke(timer.clj:42)<br/>
	at clojure.lang.AFn.run(AFn.java:22)<br/>
	at java.lang.Thread.run(Thread.java:745)<br/>
2016-06-23 06:43:48.877 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error when processing an event")<br/>
java.lang.RuntimeException: ("Error when processing an event")<br/>
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423)<br/>
	at org.apache.storm.daemon.nimbus$nimbus_data$fn__10332.invoke(nimbus.clj:205)<br/>
	at org.apache.storm.timer$mk_timer$fn_<em>2139$fn</em>_2140.invoke(timer.clj:71)<br/>
	at org.apache.storm.timer$mk_timer$fn__2139.invoke(timer.clj:42)<br/>
	at clojure.lang.AFn.run(AFn.java:22)<br/>
	at java.lang.Thread.run(Thread.java:745)</p>

---
<details><summary><i>Originally reported by <a title="Harsha" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1925" target="_blank">Nimbus fails to start in secure mode </a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-06-24T09:46:09+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Harsha pointed out I'm calling Nimbus thrift API inside of Nimbus. <br/>
I guess common logic can be extracted as function and both of reified INimbus and send_cluster_metrics_to_executors can call that.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1513" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1513</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1925" title="Nimbus fails to start in secure mode " class="issue-link" data-issue-key="STORM-1925"><del>STORM-1925</del></a> Remove Nimbus thrift call from Nimbus itself</p>

<ul>
	<li>Nimbus fails to start in secure mode since authrization is not passed</li>
</ul>


<p>    Extract the logic of getClusterInfo to new function 'get-cluster-info' and let both of callers call this function instead.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1925" title="Nimbus fails to start in secure mode " class="issue-link" data-issue-key="STORM-1925"><del>STORM-1925</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1513.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1513.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1513</p>

<hr />
<p>commit afa953ea440f228aec6ddb7b3fe66ed41ebc0850<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2016-06-23T07:25:04Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1925" title="Nimbus fails to start in secure mode " class="issue-link" data-issue-key="STORM-1925"><del>STORM-1925</del></a> Remove Nimbus thrift call from Nimbus itself</p>

<ul>
	<li>Nimbus fails to start in secure mode since authrization is not passed</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1514" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1514</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1925" title="Nimbus fails to start in secure mode " class="issue-link" data-issue-key="STORM-1925"><del>STORM-1925</del></a> Remove Nimbus thrift call from Nimbus itself (1.x)</p>

<ul>
	<li>Nimbus fails to start in secure mode since authrization is not passed</li>
	<li>Extract the logic of getClusterInfo to new function 'get-cluster-info'</li>
	<li>and let both of callers call this function instead</li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1925" title="Nimbus fails to start in secure mode " class="issue-link" data-issue-key="STORM-1925"><del>STORM-1925</del></a>-1.x</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1514.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1514.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1514</p>

<hr />
<p>commit f66de6d7edaf4758cd4af83949165fb40ffca559<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2016-06-23T08:46:51Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1925" title="Nimbus fails to start in secure mode " class="issue-link" data-issue-key="STORM-1925"><del>STORM-1925</del></a> Remove Nimbus thrift call from Nimbus itself</p>

<ul>
	<li>Nimbus fails to start in secure mode since authrization is not passed</li>
	<li>Extract the logic of getClusterInfo to new function 'get-cluster-info'</li>
	<li>and let both of callers call this function instead</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1513" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1513</a></p>

<p>    Confirmed that before patch Nimbus has crashed in kerberized environment, and this patch fixes that issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1514" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1514</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1513" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1513</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1514" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1514</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1513" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1513</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Merged to master and 1.x-branch.</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1856%20label%3Aepic">STORM-1856</a>]</i>
