### ISSUE TITLE
[STORM-1939] Frequent InterruptedException raised by ShellBoltMessageQueue.poll

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5721]
<p>We've recently started testing out Storm 1.0.1 on a beta cluster we have setup, and we've noticed that one of our topologies frequently crashes with the following stack trace:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.InterruptedException 
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017) 
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2095) 
    at org.apache.storm.utils.ShellBoltMessageQueue.poll(ShellBoltMessageQueue.java:104) 
    at org.apache.storm.task.ShellBolt$BoltWriterRunnable.run(ShellBolt.java:383) 
    at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

<p>We're using a lot of Python components with streamparse 3.0.0.dev3 and are using the <a href="https://github.com/YelpArchive/pyleus/blob/develop/topology_builder/src/main/java/com/yelp/pyleus/serializer/MessagePackSerializer.java" class="external-link" target="_blank" rel="nofollow noopener">MessagePackSerializer that was originally from pyleus</a> with all the instances of "backtype" replaced with "org.apache".</p>

<p>Aside from the frequent bolt deaths from these exceptions, things seem to work, so I'm not sure what's going on here.</p>

---
<details><summary><i>Originally reported by <a title="Dan Blanchard" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.blanchard">dan.blanchard</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1939" target="_blank">Frequent InterruptedException raised by ShellBoltMessageQueue.poll</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-07-14T14:15:49+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Not sure why that thread get interrupted, but we can just cover this by catching and re-calling poll.<br/>
What do you think?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.blanchard" class="user-hover" rel="dan.blanchard">Dan Blanchard</a> I also would like to know there're other error messages on that worker/topology. That would be possible that the thread got interrupted due to stopping worker for other issues.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.blanchard">dan.blanchard</a>:</i>
<p>As I look into it further, it's only one of our six topologies that gets this error, and it's only in the bolts.  There are a couple exceptions happening on the Python side, and annoyingly the MessagePackSerializer we're using sometimes chokes when trying to serialize an exception, so I think this is just an exception that happens sometimes when a ShellBolt dies and takes the worker down with it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Yeah than I think it's natural to see it raised, and we don't need to catch it. (Or we can catch it and ignore.)<br/>
What do you think?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.blanchard">dan.blanchard</a>:</i>
<p>I think catching it and ignoring it would be better, because otherwise it makes you think there's something wrong with Storm itself, when it's really just your topology.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>OK. That makes sense. Do you have a plan to submit a pull request? Or would you like someone to have it resolved? Either is fine.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Never mind. I just worked on it and submitted a patch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1543" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1543</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1939" title="Frequent InterruptedException raised by ShellBoltMessageQueue.poll" class="issue-link" data-issue-key="STORM-1939"><del>STORM-1939</del></a> Ignore InterruptedException on ShellBoltMessageQueue</p>

<p>    InterruptedException makes false alarm for ShellBolt shutting down.<br/>
    Since it's likely throwing InterruptedException when ShellBolt is shutting down, so we're ok to just consume that and continue.</p>

<p>    Please see <a href="https://issues.apache.org/jira/browse/STORM-1939" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1939</a> for more details.</p>

<p>    It should be applied to master, 1.x, 1.0.x branches.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1939" title="Frequent InterruptedException raised by ShellBoltMessageQueue.poll" class="issue-link" data-issue-key="STORM-1939"><del>STORM-1939</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1543.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1543.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1543</p>

<hr />
<p>commit 675e45547c2a27bcab4fcd1ce95ab51bc68cfbbe<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2016-07-07T03:58:37Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1939" title="Frequent InterruptedException raised by ShellBoltMessageQueue.poll" class="issue-link" data-issue-key="STORM-1939"><del>STORM-1939</del></a> Ignore InterruptedException on ShellBoltMessageQueue</p>

<ul>
	<li>Since it's likely throwing InterruptedException when ShellBolt is shutting down</li>
	<li>so we're ok to just consume that and continue</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1543#discussion_r69857393" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1543#discussion_r69857393</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/org/apache/storm/task/ShellBolt.java &#8212;<br/>
    @@ -158,8 +158,8 @@ public void execute(Tuple input) </p>
{
     
 _pendingWrites.putBoltMsg(boltMsg);
     }
<p> catch(InterruptedException e) {</p>
<ul class="alternate" type="square">
	<li>String processInfo = _process.getProcessInfoString() + _process.getProcessTerminationInfoString();</li>
	<li>throw new RuntimeException("Error during multilang processing " + processInfo, e);<br/>
    +    // It's likely that Bolt is shutting down so no need to throw RuntimeException
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    It will be good to have a jvm wide flag to indicate whether jvm shutdown is in progress. There is also a java hack for the same. I can add that flag in a separate PR. Do you mind holding onto this PR till I come up with that? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1543#discussion_r69858030" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1543#discussion_r69858030</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/org/apache/storm/task/ShellBolt.java &#8212;<br/>
    @@ -158,8 +158,8 @@ public void execute(Tuple input) </p>
{
     
 _pendingWrites.putBoltMsg(boltMsg);
     }
<p> catch(InterruptedException e) {</p>
<ul class="alternate" type="square">
	<li>String processInfo = _process.getProcessInfoString() + _process.getProcessTerminationInfoString();</li>
	<li>throw new RuntimeException("Error during multilang processing " + processInfo, e);<br/>
    +    // It's likely that Bolt is shutting down so no need to throw RuntimeException
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Yes sure. Please ping me once it's done.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1543#discussion_r70780928" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1543#discussion_r70780928</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/org/apache/storm/task/ShellBolt.java &#8212;<br/>
    @@ -158,8 +158,8 @@ public void execute(Tuple input) </p>
{
     
 _pendingWrites.putBoltMsg(boltMsg);
     }
<p> catch(InterruptedException e) {</p>
<ul class="alternate" type="square">
	<li>String processInfo = _process.getProcessInfoString() + _process.getProcessTerminationInfoString();</li>
	<li>throw new RuntimeException("Error during multilang processing " + processInfo, e);<br/>
    +    // It's likely that Bolt is shutting down so no need to throw RuntimeException
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    @abhishekagarwal87 Do you have update on this? If your work is expected to take longer, please review this first and we could handle your improvement by separate issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user abhishekagarwal87 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1543#discussion_r70785048" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1543#discussion_r70785048</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/org/apache/storm/task/ShellBolt.java &#8212;<br/>
    @@ -158,8 +158,8 @@ public void execute(Tuple input) </p>
{
     
 _pendingWrites.putBoltMsg(boltMsg);
     }
<p> catch(InterruptedException e) {</p>
<ul class="alternate" type="square">
	<li>String processInfo = _process.getProcessInfoString() + _process.getProcessTerminationInfoString();</li>
	<li>throw new RuntimeException("Error during multilang processing " + processInfo, e);<br/>
    +    // It's likely that Bolt is shutting down so no need to throw RuntimeException
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    My bad @HeartSaVioR. You can merge this for now. I have captured the improvement in <br/>
    <a href="https://issues.apache.org/jira/browse/STORM-1600" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1600</a></p>
