### ISSUE TITLE
[STORM-1949] Backpressure can cause spout to stop emitting and stall topology

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5731]
<p>Problem can be reproduced by this <a href="https://github.com/hortonworks/storm/blob/perftopos1.x/examples/storm-starter/src/jvm/org/apache/storm/starter/perf/FileReadWordCountTopo.java" class="external-link" target="_blank" rel="nofollow noopener">Word count topology</a><br/>
within a IDE.<br/>
I ran it with 1 spout instance, 2 splitter bolt instances, 2 counter bolt instances.</p>

<p>The problem is more easily reproduced with WC topology as it causes an explosion of tuples due to splitting a sentence tuple into word tuples. As the bolts have to process more tuples than the  spout is producing, spout needs to operate slower.</p>

<p>The amount of time it takes for the topology to stall can vary.. but typically under 10 mins. </p>

<p><b>My theory:</b>  I suspect there is a race condition in the way ZK is being utilized to enable/disable back pressure. When congested (i.e pressure exceeds high water mark), the bolt's worker records this congested situation in ZK by creating a node. Once the congestion is reduced below the low water mark, it deletes this node. <br/>
The spout's worker has setup a watch on the parent node, expecting a callback whenever there is change in the child nodes. On receiving the callback the spout's worker lists the parent node to check if there are 0 or more child nodes.... it is essentially trying to figure out the nature of state change in ZK to determine whether to throttle or not. Subsequently  it setsup another watch in ZK to keep an eye on future changes.</p>

<p>When there are multiple bolts, there can be rapid creation/deletion of these ZK nodes. Between the time the worker receives a callback and sets up the next watch.. many changes may have undergone in ZK which will go unnoticed by the spout. </p>

<p>The condition that the bolts are no longer congested may not get noticed as a result of this.</p>

---
<details><summary><i>Originally reported by <a title="Roshan Naik" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1949" target="_blank">Backpressure can cause spout to stop emitting and stall topology</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Alessandro Bellina" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abellina">abellina</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:20+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p>can we also have a thread stack taken after the topology gets stalled? It may be of help in debugging the problem further. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>And I think we need to include section to UI representing "in-backpressure" by which components/tasks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>We have a backup on the write where we will poll every 100ms to be sure everything is in sync.  We should have a backup polling for reading the data from ZK too.  I thought we did, because we have that on all of the other triggers from ZK, but looking at the code I don't see it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> Not sure what you mean by "back on the write" .. are u saying have background thread that simply polls ZK every so often ?  That might fix this issue.</p>

<p>However, there is one basic issue with this BP mechanism in general. It can put too much load on ZK. For each enable/disable throttle signal raised by any worker we have all this interaction going on with ZK..</p>

<ul class="alternate" type="square">
	<li>Some worker adds/deletes ZK node</li>
	<li>ZK issues callbacks to all workers with watches setup</li>
	<li>All those workers will list the parent node in ZK to count the number of children (expensive?)</li>
	<li>All those workers will setup another watch in ZK</li>
</ul>


<p>Given that PaceMaker was introduced to take load off of ZK... this approach feels like a regression in terms of ability to scale. There are some other issues as well but thats for later.</p>

<p>After reviewing BP, I done feel it is sufficiently mature to be considered stable and ready for production. </p>

<p>IMO Until we have a more solid BP mechanism we should disable it by default as soon as possible. I can open another jira for that.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p>+1. Given that there are few issues we should turn it off in defaults.yaml.</p>

<p>My understanding of backpressure by talking to/debugging with <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik" class="user-hover" rel="roshan_naik">Roshan Naik</a> is as soon as we hit the higher or lower ceiling we take an action. <br/>
I would like to see if we can add a time duration to understand that if the bolt is actually hit the ceiling continuously i.e we are not constantly sending signal to spout turn it on or off. Lets say as user if I set this time duration to 1min we can check the higher watermark being hit consistently for 1min than send a signal to turn on back pressure and similarly on lower watermark part. Otherwise we can end up generating false positives on turning on back pressure. </p>

<p>Also agree with <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik" class="user-hover" rel="roshan_naik">Roshan Naik</a> about increased load on zookeeper. If possible explore the possibility of it by a message transfer back to spout or via acker. I am not clear if this is possible need to look into it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik" class="user-hover" rel="roshan_naik">Roshan Naik</a>,</p>

<p>When writing to ZK every 100 ms we will check to be sure that the ZK state matches the local worker state, just in case there is a race condition and they got off some how.  So yes we should have a backup thread to poll ZK for backpressure in case we get off some how with the triggers.</p>

<p>As for the load on ZooKeeper yes, that too is one of my concerns, and we at Yahoo have been holding off turning it on by default until it has stabilized a bit and until we have moved all of our clusters to pacemaker.  We expect to turn it on fairly soon.  How expensive is it though?  If you are running zookeeper in the default configuration it can be very expensive because you are constrained by a single disk's IOps, and if you have lots of throttling going on then those IOps can get eaten up fairly quickly.  If you have the flush turned off, then it is going to be constrained by the write log to the disk, or by the network whichever saturates first.  If it is the write log then you get about 80MB/sec of writes, this is just writing a small amount of metadata, so it should not have that big of an impact, but I have not really measured it.  If the network then reads will likely saturate first because of the listings, but again this is a relatively small amount of metadata, so it should have a relatively small impact.</p>

<p>If you want to turn it off in defaults.yaml that is fine, just file a separate JIRA for that.  If you have a better solution that will reduce the load on ZK that would be great, again file another JIRA for that and we can discuss details there.  I am skeptical that we will get anywhere near as good of a throughput if we put in a delay of some sort, and I think we would start to run into issues with heaps filling up if we put in too much of a delay.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>:</i>

<p>Have not worked out a concrete solution to avoiding ZK as yet. But <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a>'s  line of thinking is interesting ... basically see if we can use the internal messaging system as opposed to messaging over ZK. </p>

<p>Opened <a href="https://issues.apache.org/jira/browse/STORM-1956" title="Disable Backpressure by default" class="issue-link" data-issue-key="STORM-1956"><del>STORM-1956</del></a> for disabling BP by default. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>I'm OK to disable backpressure by default for short time, but we should work on resolving backpressure issue now, and enable backpressure again at next release or so.<br/>
This is not same as 'event logging', cause event logging is a kind of unique feature of Storm, but backpressure is common feature of recent streaming frameworks. Also backpressure is the only choice of non-ACK topology which needs throttle.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I am not sure that we can use our internal messaging as is to make this work.  The messages to turn on and off backpressure would likely get blocked behind actual data messages and never make it to the spout that is throttled off.  I would prefer to see us go towards the model of JStorm and have a topology master, there is a lot of work that ZK is doing that could be moved over to a master. It could easily take over the responsibilities of both pacemaker/ZK(for metrics) and ZK for backpressure.</p>

<p>I'm not sure I am ready to let the master reschedule the topology itself, I prefer to still have centralized scheduling, but I could be persuaded.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p>I have the same concern as Jungtake with disabling backpressue by default. If my understanding is correct, transfer queues are not bounded anymore and if acking is not enabled, can keep growing. This will result in out of memory exceptions. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal" class="user-hover" rel="abhishek.agarwal">Abhishek Agarwal</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> As we can see keeping this as default is resulting in performance degradation that we are unable to fix in near-term. Since this is a new feature turning it off by default makes sense until we figure out more details.<br/>
<a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> of course the idea is to fix any issues and make it default.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a> We can disable the back-pressure. But I want to know what will be the alternative for topologies with non-acking? If backpressure is not enabled, there should be some other way to bound the send/receive queues.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal" class="user-hover" rel="abhishek.agarwal">Abhishek Agarwal</a> we don't have alternative for non-acking before this back pressure feature. We always told users to depend on acking & topology.max.spout.pending if they need a way to control the fast spout.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=knusbaum">knusbaum</a>:</i>
<p>I'm okay with polling ZK for changes as a fix (for now) so we can keep backpressure on by default. There are obviously issues with the design of backpressure in general, but polling shouldn't make these issues significantly worse. I don't think the load on ZK will increase appreciably from a few nodes polling. The load problem is inherent to other parts of backpressure design.</p>

<p>We could also turn it off by default, but it's nice to have a flow-control mechanism that works automatically without needing the user to perform acking. It might be some time until we have a better system in place. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p>ok. my understanding was that spout will continue emitting new tuples even if consumer is not consuming fast enough. But that won't happen because spout doesn't emit further if transfer queue is full - <br/>
<a href="https://github.com/apache/storm/blob/1.x-branch/storm-core/src/clj/org/apache/storm/daemon/executor.clj#L647" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/1.x-branch/storm-core/src/clj/org/apache/storm/daemon/executor.clj#L647</a><br/>
<a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> doesn't this address your concern? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=knusbaum" class="user-hover" rel="knusbaum">Kyle Nusbaum</a> another issue that we've seen is erratic toggling between back pressure on/off. IMO adding a time duration before turning the back pressure on/off might yield a better experience here. Currently we toggle as soon as we hit the higher watermark , how about we observe the pattern for configurable amount of time before we turn on the back pressure. Does this makes sense.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>If my understanding is right, DisruptorQueue.publish() is only called with block=true from background thread (Flusher), and for other threads it's not blocked. (This change is from Disruptor Batching of Storm 1.0.0.)<br/>
So receive queues for tasks will receive tuples anyway unless OOME has occurred. There's no blocking on consumer side.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abhishek.agarwal">abhishek.agarwal</a>:</i>
<p>I see. You mean to say that consumer may be slow but transfer thread will continue to populate receive queues. Since transfer thread doesn't slow down, spout too will keep pumping out the data. is that correct?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Receive thread in downstream is not blocked at all, so transfer thread in upstream is not blocked at all unless there're some other issues which make worker unable to send messages (for example,  downstream worker crash)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Removing EPIC since hotfix (<a href="https://issues.apache.org/jira/browse/STORM-1956" title="Disable Backpressure by default" class="issue-link" data-issue-key="STORM-1956"><del>STORM-1956</del></a>) is applied to 1.0.2.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik" class="user-hover" rel="roshan_naik">Roshan Naik</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=knusbaum" class="user-hover" rel="knusbaum">Kyle Nusbaum</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a>,</p>

<p>I tested with the word count example sent by Roshan, the results is: Backpressure works fine for 1.x-branch while in master (2.x), we have a NullPointerExecution in SpoutExecutor.</p>

<p>(1) in 1.x-branch, back pressure works well (see the attached screenshot). The back pressure flag gets set and unset intermittently depending on the population in disruptor queues. <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik" class="user-hover" rel="roshan_naik">Roshan Naik</a>, I think your guess of reason (racing condition) is incorrect since we have cyclic check of flags every 100 ms, as mentioned by Bobby.</p>


<p>(2) in test for master, I see the topology gets stalled quickly, less than a minute. But the reason is not because of the bug of back pressure, it is due to the NullPointerException in Executor.<br/>
<a href="https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java#L205" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java#L205</a><br/>
<a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Cody" class="user-hover" rel="Cody">Cody</a> Could you help with this NPE since you worked on Storm-1277? <br/>
Thanks a lot!</p>


<p> 80 2016-08-16 21:19:15.102 o.a.s.m.EventLoggerBolt <span class="error">&#91;INFO&#93;</span> EventLoggerBolt prepare called<br/>
 81 2016-08-16 21:19:15.107 o.a.s.m.FileBasedEventLogger <span class="error">&#91;INFO&#93;</span> logFilePath /Users/zliu6/git/joe/storm/storm-dist/binary/target/storm/logs/workers-artifacts/FileReadWordCountTopo-1-1471407540/6700    /events.log<br/>
 82 2016-08-16 21:19:15.110 o.a.s.e.b.BoltExecutor <span class="error">&#91;INFO&#93;</span> Prepared bolt __eventlogger:<span class="error">&#91;2&#93;</span><br/>
 83 2016-08-16 21:20:17.242 o.a.s.u.Utils <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
 84 java.lang.RuntimeException: java.lang.NullPointerException<br/>
 85     at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:468) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 86     at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:434) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 87     at org.apache.storm.utils.DisruptorQueue.consumeBatch(DisruptorQueue.java:424) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 88     at org.apache.storm.executor.spout.SpoutExecutor$2.call(SpoutExecutor.java:137) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 89     at org.apache.storm.utils.Utils$7.run(Utils.java:2227) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 90     at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_77&#93;</span><br/>
 91 Caused by: java.lang.NullPointerException<br/>
 92     at org.apache.storm.executor.spout.SpoutExecutor.tupleActionFn(SpoutExecutor.java:205) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 93     at org.apache.storm.executor.Executor.onEvent(Executor.java:257) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 94     at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:455) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 95     ... 5 more<br/>
 96 2016-08-16 21:20:17.860 o.a.s.e.e.ReportError <span class="error">&#91;ERROR&#93;</span> Error<br/>
 97 java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException<br/>
 98     at org.apache.storm.utils.Utils$7.run(Utils.java:2237) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
 99     at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_77&#93;</span><br/>
100 Caused by: java.lang.RuntimeException: java.lang.NullPointerException<br/>
101     at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:468) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
102     at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:434) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
103     at org.apache.storm.utils.DisruptorQueue.consumeBatch(DisruptorQueue.java:424) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
104     at org.apache.storm.executor.spout.SpoutExecutor$2.call(SpoutExecutor.java:137) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
105     at org.apache.storm.utils.Utils$7.run(Utils.java:2227) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
106     ... 1 more<br/>
107 Caused by: java.lang.NullPointerException<br/>
108     at org.apache.storm.executor.spout.SpoutExecutor.tupleActionFn(SpoutExecutor.java:205) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
109     at org.apache.storm.executor.Executor.onEvent(Executor.java:257) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
110     at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:455) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
111     at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:434) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
112     at org.apache.storm.utils.DisruptorQueue.consumeBatch(DisruptorQueue.java:424) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
113     at org.apache.storm.executor.spout.SpoutExecutor$2.call(SpoutExecutor.java:137) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
114     at org.apache.storm.utils.Utils$7.run(Utils.java:2227) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
115     ... 1 more</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu" class="user-hover" rel="zhuoliu">Zhuo Liu</a>  The problem we encountered not the storm workers are unable to add a node in zookeeper but it rather happening very fast thus erratic on/off behavior with backpressure. Thats what we are discussing in this jira. Its not just NPE but the current behavior in backpressure not ideal and there are some proposals here in improving it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>:</i>
<p>With BP disabled the topo ran fine. Dont think saw any NPE during my runs.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=danny0405">danny0405</a>:</i>
<p>I have test storm 1.0.1 ABP in our staging cluster[ 10 machine nodes and a topology with 32 workers, 120 executors ] on, the topology will stall within 10 mins very possibly<br/>
    i see that when all the topology tasks throttle off, the backpressure root node on ZK still have child nodes which cause   the "stall", if i delete the child node manually, the spouts will continue to consume normally(but will again stall within 10 minutes), so  i agree with @Roshan Naik</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>:</i>
<p>Attaching the wordcount topo that i used.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vaibhavnir007">vaibhavnir007</a>:</i>
<p>We are using Storm version 1.0.1.2.5.3.0-37 and the issue is still reproducible   ,      </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhuoliu">zhuoliu</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vaibhavnir007" class="user-hover" rel="vaibhavnir007">Vaibhav</a> thanks for the information.<br/>
See <a href="https://issues.apache.org/jira/browse/STORM-2039" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-2039</a><br/>
I see the fix from <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abellina" class="user-hover" rel="abellina">Alessandro Bellina</a> went into 2.0.0, 1.1.0, 1.0.3,<br/>
so 1.0.1* may not have it. Really appreciate if you could try with 1.0.3 or up. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
