### ISSUE TITLE
[STORM-1972] Storm throws java.lang.ClassNotFoundException on Bolt class

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5754]
<p>I'm trying to debug very simple topology (1 spout 2 bolts)</p>

<p>public class JoinerTopologyTest {</p>

<p>public static void main(String[] args) throws IOException {<br/>
    Config conf = new Config();<br/>
    conf.setNumWorkers(5);<br/>
    conf.setDebug(true);</p>

<p>    TopologyBuilder builder = new TopologyBuilder();<br/>
    builder.setSpout("SPOUT-1",new MySpout(),1);<br/>
    builder.setBolt("BOLT-1",new Bolt1(), 3)<br/>
    .shuffleGrouping("SPOUT-1");<br/>
    builder.setBolt("JOINER", new JoinerBolt(),1)<br/>
    .shuffleGrouping("BOLT-1")<br/>
    .shuffleGrouping("SPOUT-1","str1");</p>

<p>    final LocalCluster cluster = new LocalCluster();<br/>
    cluster.submitTopology("TOPO1",conf,builder.createTopology());</p>

<p>    System.in.read();</p>

<p>    cluster.shutdown();<br/>
}<br/>
}</p>

<p>But when i run it from InteliJ IDEA i get:</p>

<p>java.lang.RuntimeException: java.lang.ClassNotFoundException: com.pixonic.zephyr.compaction.tests.Bolt1 at org.apache.storm.utils.Utils.javaDeserialize(Utils.java:181) ~<span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span> at org.apache.storm.utils.Utils.getSetComponentObject(Utils.java:430) ~<span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
and</p>

<p><span class="error">&#91;Thread-15&#93;</span> ERROR o.a.s.d.worker - Error on initialization of server mk-worker java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.storm.daemon.acker at org.apache.storm.utils.Utils.javaDeserialize(Utils.java:181) ~<span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span> at org.apache.storm.utils.Utils.getSetComponentObject(Utils.java:430) ~<span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
but same topology runs well in Cluster mode. PS in my pom.xml in debug mode i have:</p>

<p>    <dependency><br/>
<groupId>org.apache.storm</groupId><br/>
<artifactId>storm-core</artifactId><br/>
<version>1.0.1</version><br/>
    </dependency></p>

<p>project to reproduce bug: <a href="https://github.com/holinov/storm-101-localcluster/tree/master" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/holinov/storm-101-localcluster/tree/master</a></p>

---
<details><summary><i>Originally reported by <a title="Ilya Kholinow" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=frutb">frutb</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1972" target="_blank">Storm throws java.lang.ClassNotFoundException on Bolt class</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:12+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
