### ISSUE TITLE
[STORM-1977] Leader Nimbus crashes with getClusterInfo when it doesn't have one or more replicated topology codes

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5759]
<p>While investigating <a href="https://issues.apache.org/jira/browse/STORM-1976" title="Storm Nimbus H/A has issue on cleaning corrupted topologies" class="issue-link" data-issue-key="STORM-1976"><del>STORM-1976</del></a>, I found that there're cases for nimbus to not having topology codes. <br/>
Before BlobStore, only nimbuses which is having all topology codes can gain leadership, otherwise they give up leadership immediately. While introducing BlobStore, this logic is removed.</p>

<p>I don't know it's intended or not, but it incurs one of nimbus to gain leadership which doesn't have replicated topology code, and the nimbus will be crashed when getClusterInfo is requested.</p>

<p>Easiest way to reproduce is:</p>

<p>1. comment cleanup-corrupt-topologies! from nimbus.clj (It's a quick workaround for resolving <a href="https://issues.apache.org/jira/browse/STORM-1976" title="Storm Nimbus H/A has issue on cleaning corrupted topologies" class="issue-link" data-issue-key="STORM-1976"><del>STORM-1976</del></a>), and patch Storm cluster<br/>
2. Launch Nimbus 1 (leader)<br/>
3. Run topology<br/>
4. Kill Nimbus 1<br/>
5. Launch Nimbus 2 from different node<br/>
6. Nimbus 2 gains leadership <br/>
7. getClusterInfo is requested to Nimbus 2, and Nimbus 2 gets crashed</p>

<p>Log:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-07-17 08:47:48.378 o.a.s.b.FileBlobStoreImpl [INFO] Creating <span class="code-keyword">new</span> blob store based in /grid/0/hadoop/storm/blobs
...
2016-07-17 08:47:48.619 o.a.s.zookeeper [INFO] Queued up <span class="code-keyword">for</span> leader lock.
2016-07-17 08:47:48.651 o.a.s.zookeeper [INFO] <node1> gained leadership
...
2016-07-17 08:47:48.833 o.a.s.d.nimbus [INFO] Starting nimbus server <span class="code-keyword">for</span> storm version <span class="code-quote">'1.1.1-SNAPSHOT'</span>
2016-07-17 08:47:49.295 o.a.s.t.ProcessFunction [ERROR] Internal error processing getClusterInfo
KeyNotFoundException(msg:production-topology-2-1468745167-stormcode.ser)
at org.apache.storm.blobstore.LocalFsBlobStore.getStoredBlobMeta(LocalFsBlobStore.java:149)
at org.apache.storm.blobstore.LocalFsBlobStore.getBlobReplication(LocalFsBlobStore.java:268)
...
at org.apache.storm.daemon.nimbus$get_blob_replication_count.invoke(nimbus.clj:498)
at org.apache.storm.daemon.nimbus$get_cluster_info$iter__9520__9524$fn__9525.invoke(nimbus.clj:1427)
...
at org.apache.storm.daemon.nimbus$get_cluster_info.invoke(nimbus.clj:1401)
at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__9612.getClusterInfo(nimbus.clj:1838)
at org.apache.storm.generated.Nimbus$Processor$getClusterInfo.getResult(Nimbus.java:3724)
at org.apache.storm.generated.Nimbus$Processor$getClusterInfo.getResult(Nimbus.java:3708)
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39)
...
2016-07-17 08:47:49.397 o.a.s.b.BlobStoreUtils [ERROR] Could not download blob with keyproduction-topology-2-1468745167-stormconf.ser
2016-07-17 08:47:49.400 o.a.s.b.BlobStoreUtils [ERROR] Could not update the blob with keyproduction-topology-2-1468745167-stormconf.ser
2016-07-17 08:47:49.402 o.a.s.d.nimbus [ERROR] Error when processing event
KeyNotFoundException(msg:production-topology-2-1468745167-stormconf.ser)
at org.apache.storm.blobstore.LocalFsBlobStore.getStoredBlobMeta(LocalFsBlobStore.java:149)
at org.apache.storm.blobstore.LocalFsBlobStore.getBlob(LocalFsBlobStore.java:239)
at org.apache.storm.blobstore.BlobStore.readBlobTo(BlobStore.java:271)
at org.apache.storm.blobstore.BlobStore.readBlob(BlobStore.java:300)
...
       at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
at org.apache.storm.daemon.nimbus$read_storm_conf_as_nimbus.invoke(nimbus.clj:548)
at org.apache.storm.daemon.nimbus$read_topology_details.invoke(nimbus.clj:555)
at org.apache.storm.daemon.nimbus$mk_assignments$iter__9205__9209$fn__9210.invoke(nimbus.clj:912)
...
at org.apache.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:911)
at clojure.lang.RestFn.invoke(RestFn.java:410)
at org.apache.storm.daemon.nimbus$fn__9769$exec_fn__1363__auto____9770$fn__9781$fn__9782.invoke(nimbus.clj:2216)
at org.apache.storm.daemon.nimbus$fn__9769$exec_fn__1363__auto____9770$fn__9781.invoke(nimbus.clj:2215)
at org.apache.storm.timer$schedule_recurring$this__1732.invoke(timer.clj:105)
at org.apache.storm.timer$mk_timer$fn__1715$fn__1716.invoke(timer.clj:50)
at org.apache.storm.timer$mk_timer$fn__1715.invoke(timer.clj:42)
...
2016-07-17 08:47:49.408 o.a.s.util [ERROR] Halting process: (<span class="code-quote">"Error when processing an event"</span>)
java.lang.RuntimeException: (<span class="code-quote">"Error when processing an event"</span>)
at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341)
at clojure.lang.RestFn.invoke(RestFn.java:423)
at org.apache.storm.daemon.nimbus$nimbus_data$fn__8727.invoke(nimbus.clj:205)
at org.apache.storm.timer$mk_timer$fn__1715$fn__1716.invoke(timer.clj:71)
at org.apache.storm.timer$mk_timer$fn__1715.invoke(timer.clj:42)
at clojure.lang.AFn.run(AFn.java:22)
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
2016-07-17 08:47:49.410 o.a.s.d.nimbus [INFO] Shutting down master
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1977" target="_blank">Leader Nimbus crashes with getClusterInfo when it doesn't have one or more replicated topology codes</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-07-20T00:31:55+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Leader nimbus should give away leadership when that nimbus doesn't have all of topologies codes, especially cluster is using Local BlobStore. This is a kind of regression between Nimbus H/A and BlobStore.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1573" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1573</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a> Restore logic: give up leadership when elected as leader but doesn't have any of topology codes on local</p>

<ul>
	<li>Nimbus H/A introduced condition for becoming a leader</li>
	<li>It got removed when BlobStore was introduced</li>
	<li>This patch is restoring previous logic with making logic compatible to BlobStore</li>
</ul>


<p>    Please refer <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a>(issues.apache.org/jira/browse/<a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a>) for more details.</p>

<p>    Tested with the scenario I've described from <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a></p>

<p>    1. comment cleanup-corrupt-topologies! from nimbus.clj (It's a quick workaround for resolving <a href="https://issues.apache.org/jira/browse/STORM-1976" title="Storm Nimbus H/A has issue on cleaning corrupted topologies" class="issue-link" data-issue-key="STORM-1976"><del>STORM-1976</del></a>), and patch Storm cluster<br/>
    2. Launch Nimbus 1 (leader)<br/>
    3. Run topology1<br/>
    4. Kill Nimbus 1<br/>
    5. Launch Nimbus 2 from different node<br/>
    6. Nimbus 2 gains leadership but since it doesn't have topology1 it gives up leadership</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1573.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1573.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1573</p>

<hr />
<p>commit 8ce4811ba00f3853ad4a4d8a37af7ecb4742e9f5<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2016-07-18T04:38:36Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a> Restore logic: give up leadership when elected as leader but doesn't have any of topology codes on local</p>

<ul>
	<li>Nimbus H/A introduced condition for becoming a leader</li>
	<li>It got removed when BlobStore was introduced</li>
	<li>This patch is restoring previous logic with making logic compatible to BlobStore</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a> Restore logic: give up leadership when elected as leader but doesn't have any of topology codes on local (1.x)</p>

<ul>
	<li>Nimbus H/A introduced condition for becoming a leader</li>
	<li>It got removed when BlobStore was introduced</li>
	<li>This patch is restoring previous logic with making logic compatible to BlobStore</li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a>-1.x</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1574</p>

<hr />
<p>commit 401cd09a699d3937e0c9e800e8262fc627649da7<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2016-07-18T02:51:33Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a> Restore logic: give up leadership when elected as leader but doesn't have any of topology codes on local</p>

<ul>
	<li>Nimbus H/A introduced condition for becoming a leader</li>
	<li>It got removed when BlobStore was introduced</li>
	<li>This patch is restoring previous logic with making logic compatible to BlobStore</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    The code to do the leader election based off of the IDs was removed because architecturally the blobstore should be in charge of maintaining high availability.  Exposing what is stored on the local disk in an implementation detail and exposing that to nimbus breaks a lot of things.  Not to mention is not really possible with some blobstore implementations, like the HDFS backed one.</p>

<p>    To offset this we made sure that you could access the version of the blob even if it is stored on a different instance of the blobstore.</p>

<p>    Additionally the old code did not guarantee consistency either.  There was a timeout where if nimbus waited long enough to get a copy of all of the items it gave up and would still become leader.  If there really is no guarantee why add in the extra overhead?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>The entire procedure to reproduce the issue is part of the problem.  If you don't have both nimbus instances up at the same time they cannot possibly stay in sync with each other.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @revans2 <br/>
    If we can guarantee that leader nimbus has all topologies code, leader nimbus can function well. Old code is based on this assumption, not considering followers and also not about code distribution. It should be eventually distributed since each nimbus runs sync-code / sync-blob periodically to try to sync up. </p>

<p>    In leader nimbus' point of view I think old code is consistent, and this code is trying to have same guarantee.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @revans2 <br/>
    And local BlobStore should be designed to achieve hive availability just same as HDFS BlobStore. But the process BlobStore is behind is Nimbus, which is designed to fail-fast, which I think is just not same way.</p>

<p>    For example, suppose the scenario what I addressed from <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a>.</p>

<p>    Tested with the scenario I've described from <a href="https://issues.apache.org/jira/browse/STORM-1977" title="Leader Nimbus crashes with getClusterInfo when it doesn&#39;t have one or more replicated topology codes" class="issue-link" data-issue-key="STORM-1977"><del>STORM-1977</del></a></p>

<p>    1. comment cleanup-corrupt-topologies! from nimbus.clj (It's a quick workaround for resolving <a href="https://issues.apache.org/jira/browse/STORM-1976" title="Storm Nimbus H/A has issue on cleaning corrupted topologies" class="issue-link" data-issue-key="STORM-1976"><del>STORM-1976</del></a>), and patch Storm cluster<br/>
    2. Launch Nimbus 1 (leader)<br/>
    3. Run topology1<br/>
    4. Kill Nimbus 1<br/>
    5. Launch Nimbus 2 from different node</p>

<p>    Without having condition for granting leadership, Nimbus 2 can grant leadership, and act as leader. This is not a blocker for BlobStore's view, since replication count for topology1 is 0 but it doesn't make them crashed, and reviving Nimbus 1 should eventually replicate topology 1 to Nimbus 2.<br/>
    The thing is, leader nimbus should do the own work as Nimbus. In this case just requesting getClusterInfo can make Nimbus 2 crashed, and Nimbus 1 comes in later and gain leadership, but replication count for topology1 is still 1 until Nimbus 2 comes in.</p>

<p>    With having condition for granting leadership, Nimbus 2 gives up leadership, and continuously waits for new leader. (No leader at that time) And Nimbus 1 comes in, and topology1 is eventually replicated to Nimbus 2 to ensure replication count.</p>

<p>    Due to this behavior, the crash and recovery scenario heavily depends on sequence of launching Nimbuses. I think this is not a good UX.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @HeartSaVioR <br/>
    I am OK with this change, like I am OK with the change for <a href="https://issues.apache.org/jira/browse/STORM-1976" title="Storm Nimbus H/A has issue on cleaning corrupted topologies" class="issue-link" data-issue-key="STORM-1976"><del>STORM-1976</del></a>.  I just don't think that this is the final solution for the local blobstore+nimbus, nor do I think that either is a blocker.   The reality is if I use HDFS as the backing for the blobstore and I only set it to have a single replica, then I lose a datanode, nimbus will still crash in almost exactly the same way.  Is this a bug in nimbus?  Is it a bug in the blobstore or HDFS? I would say no. It is user error because the user is trying to make something HA without configuring it properly. Then when an error happens we cannot recover.  So the question is, if it does happen is it better for nimbus to crash or is it better for nimbus to hang?  Because all this does is it switches from one to the other.  I can see advantages for hanging over crashing, so I am OK with this fix.</p>

<p>    Does the blobstore code have bugs in it and things that we can change to make it work better? I would expect it to, it is software after all.  I just want us to spend some time thinking about how we really want it to behave and fix it properly.  If that proper fix comes after making a few patches to improve things, that is fine.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    +1. Agree on having a discussion around these scenarios in another JIRA.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @revans2 <br/>
    I'm just thinking about the responsibility of Nimbus. </p>

<ul class="alternate" type="square">
	<li>Nimbus was "soft" SPOF and we claimed that Nimbus is designed to fail-fast and stateless so just supervising Nimbus works like a charm. But it doesn't help from machine failure, and moving Nimbus to other machine requires at least configuration change of whole cluster. (This assumes that Supervisor is also supervised by aux. process. If not starting Supervisor should be done manually.)</li>
	<li>Nimbus H/A came in. It was relatively easier than other process on other project since Nimbus is designed as stateless so no need to sync. Only thing Nimbuses should sync up is topology code, and Nimbus H/A tried to address this by full replications and restriction of becoming leader. It made some overhead trying to replicate topology codes to all of Nimbuses but it was a best try to achieve higher availability. When other nimbuses crashed but only one 'leader' nimbus was alive, that was completely OK for that moment. There was a chance for all alive nimbuses not having complete set of topology code thus no leader and hang, but it was relatively smaller than counting replication count since it was doing full replication at all.</li>
	<li>BlobStore came in. I don't know the details of BlobStore so hard to tell. I'd be happy if you fill out this : After BlobStore.</li>
</ul>


<p>    One thing I'm concerning is, there's new requirement for Nimbus to not easily crashed since every Nimbuses are also replica of BlobStore like DataNode, but Nimbus itself has lots of works to do (sure for leader, and not sure for followers) and it is still based on fail-fast. Is it OK to play together?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @revans2 <br/>
    Let me back to code change. Could you clarify that this change can also work well with HDFS backed BlobStore? If not how to do this?<br/>
    I'd like to address this as abstraction level of BlobStore by preventing nimbus to gain leadership when there's a topology which one of code is not available (replication count 0), but don't have an idea for how to do. If you feel more convenient to make a patch by yourself, please take over and go ahead.<br/>
    I think I should have a time to play with BlobStore by local and HDFS backed, but I'm not sure I can do that right now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @HeartSaVioR the local file system blobstore behaves exactly the same as the nimbus HA before it.  It tries to replicate all of the blobs to all of the nimbus nodes as quickly as possible.  It stores the metadata for each blob in ZK, just like the original nimbus HA code.  The big difference is that it can store a general set of blobs and they are all versioned so you can upload a new one, and if you ask for a blob that is not currently local on that nimbus it will speed up they sync process and go grab it from another nimbus instance for you.</p>

<p>    There is still a race, like with nimbus HA where it may not have fully replicated, but if you set the replication count when the blob is uploaded it should be waiting for the replication to complete before declaring success.</p>

<p>    The one bug I saw while going through the code is that when we list keys, we are doing it only from the local storage, not form ZK.  If we were doing it from ZK then when someone asks for all of the keys they would be guaranteed to get all of the keys, but this patch would do no good. Simply because it would not have an API to know what is local and what is not local.  In the short term I think this is OK, but long term we need to discuss how we really want all of this to work in the different failure cases.</p>

<p>    When configured to use HDFS as the backing, all of the "blobs" are stored in HDFS.  We do a directory listing to get the key listing.  With that nimbus truly becomes stateless, and you can stand up a nimbus on a different node and not have to worry about it.  This code would simply do the directory listing and then become a noop.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @revans2 <br/>
    I might be wrong with explaining my patch. My understanding is that `title` is wrong instead of `code`. No need to be in local, just need to be available at Blobstore.</p>

<p>    I didn't still see the details of Blobstore, so please correct me if I'm wrong.</p>

<p>    I had a change to review this patch myself, and realize that I didn't rely on implementation details.<br/>
    If local BlobStore is properly abstracted, BlobStore.filterAndListKeys() should handle underlying mechanism, thus it should list keys from blobstore regardless of locality of blob, and apply filter. So `code-ids` should be working well with local and HDFS, and `diff-topology` should only have missing topology code for all available blobstore replicas.</p>

<p>    If you also think title is wrong please let me know so that I can correct JIRA and PR title. Thanks in advance!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @revans2 <br/>
    I'm not clear on part of your comment,</p>

<p>    > The one bug I saw while going through the code is that when we list keys, we are doing it only from the local storage, not form ZK. If we were doing it from ZK then when someone asks for all of the keys they would be guaranteed to get all of the keys, but this patch would do no good. Simply because it would not have an API to know what is local and what is not local. In the short term I think this is OK, but long term we need to discuss how we really want all of this to work in the different failure cases.</p>

<p>    I think the one bug you stated is about BlobStore, right? Because `code-ids` just uses exposed BlobStore API, so underlying mechanism shouldn't be affected to its behavior. And achieving abstraction for BlobStore, like we pull a file from HDFS and expect pull will be succeed if there's at least one replica serving that file, when we use local BlobStore and pull blob which is not available for this nimbus, it should pull from another nimbus automatically without waiting for nimbus to next sync up cycle.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @HeartSaVioR yes there is no bug with this code.  I am +1 on merging this in as is.</p>

<p>    The bug I found is in the BlobStore implementation.  It impacts this patch in the future, because if we fix it, this will no longer work.  I just wanted to point that out.  It should not be a big deal, again because all of the nimbus instances should be synching with one another, so the race should be very small.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    @revans2 <br/>
    IMO this patch will still work if we address both of the expectations: 1) BlobStore should list keys for all available keys for listing keys. 2) BlobStore should ensure that it will pull from another replica when blob is not in local. If we address only 1) it will break this patch and go back to now.</p>

<p>    Suppose both things are achieved, we would like to have nimbus giving up leadership rather than crash when we have zero replication count on one of topologies code in blobstore. Like we talked we don't want to crash Nimbus in this case, since itself is a replica of blobstore, so it incurs decreasing replication count of some part of blobs, and next leader nimbus has more chance to crash.</p>

<p>    But also as you said there should be few problem if we have enough nimbuses and syncing up blobs is enough fast and done often.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1573" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1573</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user harshach commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    Thanks @HeartSaVioR . Merged into 1.0.x, 1.1-x and master.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Set fix version/s to 1.0.3 tentatively. It's up to vote result, and this could be 1.0.2.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the issue:</p>

<p>    <a href="https://github.com/apache/storm/pull/1574" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1574</a></p>

<p>    Filed an issue regarding local BlobStore bug what @revans2 mentioned.<br/>
    <a href="https://issues.apache.org/jira/browse/STORM-1986" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1986</a></p>

<p>    Btw, get / delete / set / update operations seems to have proper logic: it finds blob from local and download if it's not, though it doesn't check download is succeed or not. So we don't need to care about this for now.</p>
