### ISSUE TITLE
[STORM-1981] storm command hangs

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5763]
<p>I ran the following command which threw an exception and never completed. I understand that the topology has some issues which caused this hang. The problem that I want to emphasize is the <b>hang</b>. We can't assume that user code will always be doing things correctly.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">test@host:/grid/0/hadoopqe$ /usr/hdp/current/storm-client/bin/storm -c java.security.auth.login.config=/etc/storm/conf/client_jaas.conf -c storm.thrift.transport=org.apache.storm.security.auth.kerberos.KerberosSaslTransportPlugin jar /usr/hdp/current/storm-client/contrib/storm-starter/storm-starter-topologies-1.0.1.jar org.apache.storm.starter.trident.TridentKafkaWordCount nat-d7-vnas-storm-5.openstacklocal:6667
Running: /usr/jdk64/jdk1.8.0_77/bin/java -server -Ddaemon.name= -Dstorm.options=java.security.auth.login.config%3D%2Fetc%2Fstorm%2Fconf%2Fclient_jaas.conf,storm.thrift.transport%3Dorg.apache.storm.security.auth.kerberos.KerberosSaslTransportPlugin -Dstorm.home=/storm -Dstorm.log.dir=/grid/0/log/storm -Djava.library.path=/usr/local/lib:/o\
pt/local/lib:/usr/lib -Dstorm.conf.file= -cp /storm/lib/slf4j-api-1.7.7.jar:/storm/lib/clojure-1.7.0.jar:/storm/lib/minlog-1.3.0.jar:/storm/lib/log4j-over-slf4j-1.6.6.jar:/storm/lib/ambari-metrics-storm-sink.jar:/storm/lib/reflectasm-1.10.1.jar:/storm/lib/ring-cors-0.1.5.jar:/storm/lib/disruptor-3.3.2.jar:/storm/lib/storm-rename-hack-1.0.1.jar:/storm/lib/log4j-api-2.1.jar:/storm/lib/log4j-slf4j-impl-2.1.jar:/storm/lib/zoo\
keeper.jar:/storm/lib/kryo-3.0.3.jar:/storm/lib/log4j-core-2.1.jar:/storm/lib/storm-core-1.0.1.jar:/storm/lib/servlet-api-2.5.jar:/storm/lib/objenesis-2.1.jar:/storm/lib/asm-5.0.3.jar:/storm/extlib/scala-library-2.10.4.jar:/storm/extlib/storm-kafka-1.0.1.jar:/storm/extlib/kafka_2.10-0.10.0.jar org.apache.storm.daemon.ClientJarTransformerRunner org.apache.storm.hack.StormShadeTransformer /usr/hdp/current/storm-client/contrib/storm-starter/storm-starter-topologies-1.0.1.jar /tmp/1bb42b0a4d2f11e6871dfa163e434686.jar
Running: /usr/jdk64/jdk1.8.0_77/bin/java -client -Ddaemon.name= -Dstorm.options=java.security.auth.login.config%3D%2Fetc%2Fstorm%2Fconf%2Fclient_jaas.conf,storm.thrift.transport%3Dorg.apache.storm.security.auth.kerberos.KerberosSaslTransportPlugin -Dstorm.home=/storm -Dstorm.log.dir=/grid/0/log/storm -Djava.library.path=/usr/local/lib:/o\
pt/local/lib:/usr/lib:/usr/hdp/current/storm-client/lib -Dstorm.conf.file= -cp /storm/lib/slf4j-api-1.7.7.jar:/storm/lib/clojure-1.7.0.jar:/storm/lib/minlog-1.3.0.jar:/storm/lib/log4j-over-slf4j-1.6.6.jar:/storm/lib/ambari-metrics-storm-sink.jar:/storm/lib/reflectasm-1.10.1.jar:/storm/lib/ring-cors-0.1.5.jar:/storm/lib/disruptor-3.3.2.jar:/storm/lib/storm-rename-hack-1.0.1.jar:/storm/lib/log4j-api-2.1.jar:/storm/lib/log4j-slf4j-impl-2.1.jar:/gri\
d/0/hdp/2.5.0.0-1016/storm/lib/zookeeper.jar:/storm/lib/kryo-3.0.3.jar:/storm/lib/log4j-core-2.1.jar:/storm/lib/storm-core-1.0.1.jar:/storm/lib/servlet-api-2.5.jar:/storm/lib/objenesis-2.1.jar:/storm/lib/asm-5.0.3.jar:/storm/extlib/scala-library-2.10.4.jar:/storm/extlib/storm-kafka-1.0.1.jar:/storm/extlib/kafka_2.10-0.10.0.jar:/tmp/1bb42b0a4d2f11e6871dfa163e434686.jar:/usr/hdp/current/storm-supervisor/conf:/storm/bin -Dstorm.jar=/tmp/1bb42b0a4d2f11e6871dfa163e434686.jar org.apache.storm.starter.trident.TridentKafkaWordCount nat-d7-vnas-storm-5.openstacklocal:6667
Using Kafka zookeeper url: nat-d7-vnas-storm-5.openstacklocal:6667 broker url: localhost:9092
Exception in thread <span class="code-quote">"main"</span> java.lang.ExceptionInInitializerError
at java.lang.<span class="code-object">Class</span>.forName0(Native Method)
at java.lang.<span class="code-object">Class</span>.forName(<span class="code-object">Class</span>.java:348)
at clojure.lang.RT.classForName(RT.java:2154)
at clojure.lang.RT.classForName(RT.java:2163)
at clojure.lang.RT.loadClassForName(RT.java:2182)
at clojure.lang.RT.load(RT.java:436)
at clojure.lang.RT.load(RT.java:412)
at clojure.core$load$fn__5448.invoke(core.clj:5866)
at clojure.core$load.doInvoke(core.clj:5865)
...
...
...
at clojure.lang.Var.invoke(Var.java:379)
at org.apache.storm.LocalCluster.<clinit>(Unknown Source)
at org.apache.storm.starter.trident.TridentKafkaWordCount.runMain(TridentKafkaWordCount.java:254)
at org.apache.storm.starter.trident.TridentKafkaWordCount.main(TridentKafkaWordCount.java:240)
Caused by: java.lang.ClassNotFoundException: org.apache.ranger.authorization.storm.authorizer.RangerStormAuthorizer
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:357)
at java.lang.<span class="code-object">Class</span>.forName0(Native Method)
at java.lang.<span class="code-object">Class</span>.forName(<span class="code-object">Class</span>.java:264)
at org.apache.storm.daemon.common$mk_authorization_handler.invoke(common.clj:421)
at org.apache.storm.ui.core__init.load(Unknown Source)
at org.apache.storm.ui.core__init.<clinit>(Unknown Source)
... 83 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Raghav Kumar Gautam" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raghavgautam">raghavgautam</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1981" target="_blank">storm command hangs</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:58+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>The code indicates that your command is looking to pull in <tt>org.apache.ranger.authorization.storm.authorizer.RangerStormAuthorizer</tt> but could not find it.  This is not a part of storm, it appears to be a part of ranger, so my guess would be that you need to include ranger, or part of it on your classpath.  You could do this by putting it in the lib directory under the storm.home directory. You might also want to try asking on the ranger or storm user mailing lists, because honestly I don't use ranger.  At this point it does not look like a bug in storm, it looks like user error or an issue with your configuration, so I am going to close this JIRA.  If you disagree that it is actually a bug in storm feel free to reopen this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raghavgautam">raghavgautam</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> When I run a storm command I expect it to complete in a reasonable time. In this case I expect that it will complete saying - client code did not finish in say 30 sec and hence was forcibly killed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>OK Makes since thanks for clarifying <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raghavgautam" class="user-hover" rel="raghavgautam">Raghav Kumar Gautam</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
