### ISSUE TITLE
[STORM-2008] kafka jars must be part of the storm-kafka topology

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5790]
<p>As of now the dependency is present but it's scope is provided, this is incorrect.<br/>
<a href="https://github.com/apache/storm/blob/master/external/storm-kafka/pom.xml#L121" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/external/storm-kafka/pom.xml#L121</a></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>${storm.kafka.artifact.id}</artifactId>
    <version>${storm.kafka.version}</version>
    <scope>provided</scope>
</dependency>
</pre>
</div></div>

<p>This leads to following stacktrace in worker, when we try to run TridentKafkaWordCount topology.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">    This is <span class="code-keyword">for</span> solving following exception:
    Exception in thread <span class="code-quote">"main"</span> java.lang.NoClassDefFoundError: kafka/api/OffsetRequest
at org.apache.storm.kafka.KafkaConfig.<init>(KafkaConfig.java:48)
at org.apache.storm.kafka.trident.TridentKafkaConfig.<init>(TridentKafkaConfig.java:30)
at org.apache.storm.starter.trident.TridentKafkaWordCount.createTransactionalKafkaSpout(TridentKafkaWordCount.java:102)
at org.apache.storm.starter.trident.TridentKafkaWordCount.addTridentState(TridentKafkaWordCount.java:131)
at org.apache.storm.starter.trident.TridentKafkaWordCount.buildConsumerTopology(TridentKafkaWordCount.java:149)
at org.apache.storm.starter.trident.TridentKafkaWordCount.runMain(TridentKafkaWordCount.java:249)
at org.apache.storm.starter.trident.TridentKafkaWordCount.main(TridentKafkaWordCount.java:240)
    Caused by: java.lang.ClassNotFoundException: kafka.api.OffsetRequest
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:357)
... 7 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Raghav Kumar Gautam" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raghavgautam">raghavgautam</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2008" target="_blank">kafka jars must be part of the storm-kafka topology</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2016-07-27T00:12:17+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user raghavgautam opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1596" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1596</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-2008" title="kafka jars must be part of the storm-kafka topology" class="issue-link" data-issue-key="STORM-2008"><del>STORM-2008</del></a>: </p>

<p>    This is for solving following exception that we see when we try to run TridentKafkaWordCount topology.<br/>
    ``<br/>
Exception in thread "main" java.lang.NoClassDefFoundError: kafka/api/OffsetRequest<br/>
    at org.apache.storm.kafka.KafkaConfig.<init>(KafkaConfig.java:48)<br/>
    at org.apache.storm.kafka.trident.TridentKafkaConfig.<init>(TridentKafkaConfig.java:30)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.createTransactionalKafkaSpout(TridentKafkaWordCount.java:102)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.addTridentState(TridentKafkaWordCount.java:131)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.buildConsumerTopology(TridentKafkaWordCount.java:149)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.runMain(TridentKafkaWordCount.java:249)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.main(TridentKafkaWordCount.java:240)<br/>
Caused by: java.lang.ClassNotFoundException: kafka.api.OffsetRequest<br/>
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)<br/>
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)<br/>
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)<br/>
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)<br/>
    ... 7 more<br/>
    ``</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/raghavgautam/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/raghavgautam/storm</a> master</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1596.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1596.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1596</p>

<hr />
<p>commit 2813a79a0fb93ce57c80169e7ec5954e0edf21a0<br/>
Author: Raghav Kumar Gautam <raghav@apache.org><br/>
Date:   2016-07-26T18:30:51Z</p>

<p>    kafka jars must be part of the topology</p>

<p>This is for solving following exception:<br/>
Exception in thread "main" java.lang.NoClassDefFoundError: kafka/api/OffsetRequest<br/>
    at org.apache.storm.kafka.KafkaConfig.<init>(KafkaConfig.java:48)<br/>
    at org.apache.storm.kafka.trident.TridentKafkaConfig.<init>(TridentKafkaConfig.java:30)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.createTransactionalKafkaSpout(TridentKafkaWordCount.java:102)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.addTridentState(TridentKafkaWordCount.java:131)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.buildConsumerTopology(TridentKafkaWordCount.java:149)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.runMain(TridentKafkaWordCount.java:249)<br/>
    at org.apache.storm.starter.trident.TridentKafkaWordCount.main(TridentKafkaWordCount.java:240)<br/>
Caused by: java.lang.ClassNotFoundException: kafka.api.OffsetRequest<br/>
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)<br/>
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)<br/>
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)<br/>
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)<br/>
    ... 7 more</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raghavgautam">raghavgautam</a>:</i>
<p>Looks this this was a conscious decision by community.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user raghavgautam closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1596" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1596</a></p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1876">STORM-1876</a>]</i>
