### ISSUE TITLE
[STORM-2019] NullPointerException in Kafka-Spout

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5801]
<p>KafkaSpout reports following error:<br/>
java.lang.NullPointerException<br/>
at java.util.TreeMap.rotateLeft(TreeMap.java:2220) ~<span class="error">&#91;?:1.8.0_77&#93;</span><br/>
at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2287) ~<span class="error">&#91;?:1.8.0_77&#93;</span><br/>
at java.util.TreeMap.put(TreeMap.java:582) ~<span class="error">&#91;?:1.8.0_77&#93;</span><br/>
at org.apache.storm.kafka.PartitionManager.fill(PartitionManager.java:235) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.PartitionManager.next(PartitionManager.java:138) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:135) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at applications.spout.KafkaSpoutWrapper.nextTuple(KafkaSpoutWrapper.java:64) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>7885$fn</em><em>7900$fn</em>_7931.invoke(executor.clj:645) ~<span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.util$async_loop$fn__625.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_77&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="zhang shuhao" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shuhao.zhang">shuhao.zhang</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2019" target="_blank">NullPointerException in Kafka-Spout</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2016-08-04T07:49:48+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shuhao.zhang">shuhao.zhang</a>:</i>
<p>To make a customized kafkaspout, one cannot create container class for kafkaspout class, because it will make tthe kafkaspout thread-unsafe. The correct way is to extend kafkaspout instead.</p>
