### ISSUE TITLE
[STORM-2022] FieldsTest.selectingUnknownFieldThrowsTest is failing

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5804]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><testcase name=<span class="code-quote">"selectingUnknownFieldThrowsTest"</span> classname=<span class="code-quote">"org.apache.storm.tuple.FieldsTest"</span> time=<span class="code-quote">"0.007"</span>>
    <error message=<span class="code-quote">"Unexpected exception, expected&lt;java.lang.NullPointerException&gt; but was&lt;java.lang.IllegalArgumentException&gt;"</span> type=<span class="code-quote">"java.lang.Exception"</span>><![CDATA[java.lang.Exception: Unexpected exception, expected<java.lang.NullPointerException> but was<java.lang.IllegalArgumentException>
at org.apache.storm.tuple.Fields.fieldIndex(Fields.java:104)
at org.apache.storm.tuple.Fields.select(Fields.java:63)
at org.apache.storm.tuple.FieldsTest.selectingUnknownFieldThrowsTest(FieldsTest.java:124)
]]></error>
  </testcase>
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2022" target="_blank">FieldsTest.selectingUnknownFieldThrowsTest is failing</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-08-05T19:58:14+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lujinhong">lujinhong</a>:</i>
<p>my bad, sorry.</p>
