### ISSUE TITLE
[STORM-2040] Config.TOPOLOGY_TESTING_ALWAYS_TRY_SERIALIZE=true causes j.l.UnsupportedOperationException: nth not supported on this type: AddressedTuple

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5822]
<p>When Config.TOPOLOGY_TESTING_ALWAYS_TRY_SERIALIZE is enabled for a topology, the components fail with the following exception:</p>

<p>26168 [Thread-13-disruptor-executor<span class="error">&#91;1 1&#93;</span>-send-queue] ERROR o.a.s.d.executor - <br/>
java.lang.RuntimeException: java.lang.UnsupportedOperationException: nth not supported on this type: AddressedTuple<br/>
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:464) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:430) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.disruptor$consume_loop_STAR_$fn__7509.invoke(disruptor.clj:83) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_102&#93;</span><br/>
Caused by: java.lang.UnsupportedOperationException: nth not supported on this type: AddressedTuple<br/>
	at clojure.lang.RT.nthFrom(RT.java:933) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at clojure.lang.RT.nth(RT.java:883) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at org.apache.storm.daemon.worker$assert_can_serialize.invoke(worker.clj:130) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.daemon.worker$mk_transfer_fn$fn__8214.invoke(worker.clj:202) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.daemon.executor$start_batch_transfer_<em>GT_worker_handler_BANG</em>$fn__7898.invoke(executor.clj:312) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.disruptor$clojure_handler$reify__7492.onEvent(disruptor.clj:40) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:451) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	... 6 more<br/>
26171 [Thread-15-__acker-executor<span class="error">&#91;163 163&#93;</span>] INFO  o.a.s.d.executor - Preparing bolt __acker:(163)<br/>
26171 [Thread-15-__acker-executor<span class="error">&#91;163 163&#93;</span>] INFO  o.a.s.d.executor - Prepared bolt __acker:(163)</p>

---
<details><summary><i>Originally reported by <a title="Kirill Shirokov" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kirill.shirokov">kirill.shirokov</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2040" target="_blank">Config.TOPOLOGY_TESTING_ALWAYS_TRY_SERIALIZE=true causes j.l.UnsupportedOperationException: nth not supported on this type: AddressedTuple</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-10-01T05:18:00+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2046">STORM-2046</a>]</i>
