### ISSUE TITLE
[STORM-2055] Exception when running topology from Maven exec with Flux

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5837]
<p>When running a topology from Maven with Flux as a dependency, we get</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">11335 [<span class="code-object">Thread</span>-8] ERROR o.a.s.event - Error when processing event
java.io.FileNotFoundException: Source <span class="code-quote">'file:/home/julien/.m2/repository/org/apache/storm/flux-core/1.0.1/flux-core-1.0.1.jar!/resources'</span> does not exist
    at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.daemon.supervisor$fn__9359.invoke(supervisor.clj:1194) ~[storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.MultiFn.invoke(MultiFn.java:243) ~[clojure-1.7.0.jar:?]
    at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9078$fn__9096.invoke(supervisor.clj:582) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9078.invoke(supervisor.clj:581) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.event$event_manager$fn__8630.invoke(event.clj:40) [storm-core-1.0.1.jar:1.0.1]
    at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
    at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_101]
</pre>
</div></div>

<p>The same topology runs fine when executed with Eclipse or via the storm command.</p>

<p>See <a href="https://github.com/DigitalPebble/storm-crawler/issues/324" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DigitalPebble/storm-crawler/issues/324</a></p>

---
<details><summary><i>Originally reported by <a title="Julien Nioche" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jnioche">jnioche</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2055" target="_blank">Exception when running topology from Maven exec with Flux</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Julien Nioche" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jnioche">jnioche</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2017-08-24T06:46:15+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jnioche">jnioche</a>:</i>
<p>Fixed in Storm 1.0.3</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2324">STORM-2324</a>]</i>
