### ISSUE TITLE
[STORM-2062] Hive streaming doesn't support non string partition fields

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5844]
<p>create hive table with an int partition column</p>

<p>CREATE TABLE CDRDWH.CDR_FACT (<br/>
geo_id int,<br/>
time_id smallint,<br/>
cust_id smallint,<br/>
vend_id smallint,<br/>
cust_rel_id smallint,<br/>
vend_rel_id smallint,<br/>
route tinyint,<br/>
connect boolean,<br/>
earlyEvent boolean,<br/>
Call_duration_cust double,<br/>
I_PDD double,<br/>
E_PDD double,<br/>
orig_number string,<br/>
term_number string<br/>
)<br/>
partitioned by (date_id int)<br/>
clustered by (geo_id, time_id) into 16 buckets<br/>
stored as ORC<br/>
tblproperties ("orc.compress"="SNAPPY”);</p>

<p>When i try to stream my topolgy output to Hive I get the following exception:</p>

<p>11829 [Thread-31-hivewriter-executor<span class="error">&#91;5 5&#93;</span>] ERROR o.a.s.d.executor - <br/>
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String<br/>
at org.apache.storm.tuple.TupleImpl.getStringByField(TupleImpl.java:153) ~<span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.hive.bolt.mapper.DelimitedRecordHiveMapper.mapPartitions(DelimitedRecordHiveMapper.java:92) ~<span class="error">&#91;storm-hive-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.hive.bolt.HiveBolt.execute(HiveBolt.java:112) <span class="error">&#91;storm-hive-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>7953$tuple_action_fn</em>_7955.invoke(executor.clj:728) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.daemon.executor$mk_task_receiver$fn__7874.invoke(executor.clj:461) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.disruptor$clojure_handler$reify__7390.onEvent(disruptor.clj:40) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:439) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:418) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>7953$fn</em><em>7966$fn</em>_8019.invoke(executor.clj:847) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.util$async_loop$fn__625.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_77&#93;</span></p>

<p>Line 92 of DelimtedRecordHiveMapper is attempting to access my integer field as a String and the subsequent exception is thrown<br/>
 @Override<br/>
    public List<String> mapPartitions(Tuple tuple) {<br/>
List<String> partitionList = new ArrayList<String>();<br/>
if(this.partitionFields != null) {<br/>
    for(String field: this.partitionFields) </p>
{
partitionList.add(tuple.getStringByField(field));
    }
<p>}<br/>
if (this.timeFormat != null) </p>
{
    partitionList.add(getPartitionsByTimeFormat());
}
<p>return partitionList;<br/>
    }</p>

---
<details><summary><i>Originally reported by <a title="Ryan Templeton" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ryan_templeton">ryan_templeton</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2062" target="_blank">Hive streaming doesn't support non string partition fields</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:13+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
