### ISSUE TITLE
[STORM-2067] "array element type mismatch" from compute-executors in nimbus.clj

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5849]
<p>In some scenarios, Nimbus throws "java.lang.IllegalArgumentException: array element type mismatch".</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>08:49:35.321 [timer] ERROR o.a.s.d.nimbus - Error when processing event
java.lang.IllegalArgumentException: array element type mismatch
	at java.lang.reflect.Array.set(Native Method) ~[?:1.8.0_66]
	at clojure.lang.RT.seqToTypedArray(RT.java:1719) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.seqToTypedArray(RT.java:1692) ~[clojure-1.7.0.jar:?]
	at clojure.core$into_array.invoke(core.clj:3319) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.nimbus$compute_executors$fn__4307.doInvoke(nimbus.clj:645) ~[classes/:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.nimbus$compute_executors.invoke(nimbus.clj:645) ~[classes/:?]
	at org.apache.storm.daemon.nimbus$compute_executor__GT_component.invoke(nimbus.clj:655) ~[classes/:?]
	at org.apache.storm.daemon.nimbus$read_topology_details.invoke(nimbus.clj:565) ~[classes/:?]
	at org.apache.storm.daemon.nimbus$mk_assignments$iter__4668__4672$fn__4673.invoke(nimbus.clj:967) ~[classes/:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.7.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.7.0.jar:?]
	at clojure.lang.RT.seq(RT.java:507) ~[clojure-1.7.0.jar:?]
	at clojure.core$seq__4128.invoke(core.clj:137) ~[clojure-1.7.0.jar:?]
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30) ~[clojure-1.7.0.jar:?]
	at clojure.core.protocols$fn__6506.invoke(protocols.clj:101) ~[clojure-1.7.0.jar:?]
	at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13) ~[clojure-1.7.0.jar:?]
	at clojure.core$reduce.invoke(core.clj:6519) ~[clojure-1.7.0.jar:?]
	at clojure.core$into.invoke(core.clj:6600) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.nimbus$mk_assignments.doInvoke(nimbus.clj:966) ~[classes/:?]
	at clojure.lang.RestFn.invoke(RestFn.java:410) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.nimbus$fn__5354$exec_fn__579__auto____5355$fn__5366$fn__5367.invoke(nimbus.clj:2409) ~[classes/:?]
	at org.apache.storm.daemon.nimbus$fn__5354$exec_fn__579__auto____5355$fn__5366.invoke(nimbus.clj:2408) ~[classes/:?]
	at clojure.lang.AFn.run(AFn.java:22) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.StormTimer$1.run(StormTimer.java:190) ~[classes/:?]
	at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:83) [classes/:?]
</pre>
</div></div>

<p>The exception is thrown from into-array, which is called from below line:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">((fn [ & maps ] (Utils/joinMaps (into-array (into [component->executors] maps)))))
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2067" target="_blank">"array element type mismatch" from compute-executors in nimbus.clj</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-09-13T05:49:26+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>This is due to Clojure's optimization.<br/>
Clojure has two implicit types of persistent map: PersistentArrayMap and PersistentHashMap. Which type Clojure uses for persisting map is determined by specific threshold, so in fact Clojure should make sure that users don't need to care about this.<br/>
But this is not true for into-array with no type information. If into-array is called with no type information, into-array uses the class which is type of first element.</p>

<p>Unfortunately, from below line, component->executors and maps were different types which one is PersistentArrayMap and another one is PersistentHashMap.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">(into-array (into [component->executors] maps))
</pre>
</div></div>

<p>We should pass common type of two maps. Since parameter type of Utils/joinMaps is Map[], we can pass Map to into-array.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Merged to master.</p>
