### ISSUE TITLE
[STORM-2068] org.apache.storm.utils.NimbusLeaderNotFoundException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5850]
<p>my storm version is apache-storm-2.0.0-SNAPSHOT<br/>
from git clone "storm github", mvn clean install command<br/>
and, setting storm.yaml like bellow:</p>

<p>storm.zookeeper.servers:</p>
<ul class="alternate" type="square">
	<li>"NN"</li>
	<li>"DN01"</li>
	<li>"DN02"</li>
	<li>"DN03"</li>
	<li>"DN04"</li>
</ul>

<p>nimbus.seeds: <span class="error">&#91;"NN"&#93;</span></p>

<p>supervisor.slots.ports:</p>
<ul class="alternate" type="square">
	<li>6700</li>
	<li>6701</li>
	<li>6702</li>
	<li>6703</li>
</ul>

<p>ui.port: 8989</p>

<p>storm cluster is woring well. but, UI, storm jar command rise ERROR</p>

<p>org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts <span class="error">&#91;"NN"&#93;</span>. Did you specify a valid list of nimbus hosts for config nimbus.seeds?<br/>
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:106)<br/>
	at org.apache.storm.ui.core$all_topologies_summary.invoke(core.clj:508)<br/>
	at org.apache.storm.ui.core$fn__3916.invoke(core.clj:1141)<br/>
	at org.apache.storm.shade.compojure.core$make_route$fn__989.invoke(core.clj:100)<br/>
	at org.apache.storm.shade.compojure.core$if_route$fn__977.invoke(core.clj:46)<br/>
	at org.apache.storm.shade.compojure.core$if_method$fn__970.invoke(core.clj:31)<br/>
	at org.apache.storm.shade.compojure.core$routing$fn__995.invoke(core.clj:113)<br/>
	at clojure.core$some.invoke(core.clj:2570)<br/>
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:113)<br/>
	at clojure.lang.RestFn.applyTo(RestFn.java:139)<br/>
	at clojure.core$apply.invoke(core.clj:632)<br/>
	at org.apache.storm.shade.compojure.core$routes$fn__999.invoke(core.clj:118)<br/>
	at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__1956.invoke(json.clj:56)<br/>
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__1491.invoke(multipart_params.clj:118)<br/>
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__1412.invoke(reload.clj:22)<br/>
	at org.apache.storm.ui.helpers$requests_middleware$fn__3226.invoke(helpers.clj:54)<br/>
	at org.apache.storm.ui.core$catch_errors$fn__4103.invoke(core.clj:1425)<br/>
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__2955.invoke(keyword_params.clj:35)<br/>
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__2998.invoke(nested_params.clj:84)<br/>
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__2927.invoke(params.clj:64)<br/>
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__1491.invoke(multipart_params.clj:118)<br/>
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__3213.invoke(flash.clj:35)<br/>
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__3199.invoke(session.clj:98)<br/>
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__2821.invoke(servlet.clj:127)<br/>
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__2825.invoke(servlet.clj:136)<br/>
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)<br/>
	at org.apache.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:47)<br/>
	at org.apache.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:39)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)<br/>
	at java.lang.Thread.run(Thread.java:745)</p>

---
<details><summary><i>Originally reported by <a title="seokwoo yang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=seokwoo">seokwoo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2068" target="_blank">org.apache.storm.utils.NimbusLeaderNotFoundException</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2016-08-30T09:31:44+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Please post this question to user@ mailing list so that one of users / devs can answer this.<br/>
<a href="http://storm.apache.org/getting-help.html" class="external-link" target="_blank" rel="nofollow noopener">http://storm.apache.org/getting-help.html</a></p>

<p>If it turns out to a bug we can file an issue with more details information.<br/>
I'll close this. Thanks.</p>
