### ISSUE TITLE
[STORM-2095] Nimbus dies and never recovers due to java.nio.file.DirectoryNotEmptyException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5877]
<p>To Recreate:<br/>
--------------------------------------<br/>
1) Create a blobstore key for a large file (1 or 2 GB). Size of the file does not matter if nimbus can be killed while the blob is being created.<br/>
2) while the blob is being created, restart nimbus (this is easiest way to regenerate, there can be various reasons due to which a blob couldn't be successfully created in nimbus)<br/>
3) When nimbus tries to start on restart, it will keep dying due to DirectoryNotEmptyException and never come up.</p>

<p>Expected Behavior<br/>
--------------------------------------<br/>
Partial blobstore key is deleted cleanly and doesn't affect nimbus.</p>

<p>The actual, incorrect behavior.<br/>
--------------------------------------<br/>
2016-09-14 15:07:48.518 o.a.s.zookeeper <span class="error">&#91;INFO&#93;</span> Queued up for leader lock.<br/>
2016-09-14 15:07:48.576 o.a.s.zookeeper <span class="error">&#91;INFO&#93;</span> xxx gained leadership<br/>
2016-09-14 15:07:48.581 o.a.s.d.nimbus <span class="error">&#91;ERROR&#93;</span> Error on initialization of server service-handler<br/>
java.lang.RuntimeException: java.nio.file.DirectoryNotEmptyException: /opt/storm/storm-local/blobs/955/some_big_file<br/>
	at org.apache.storm.blobstore.LocalFsBlobStore.deleteBlob(LocalFsBlobStore.java:229)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:497)<br/>
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)<br/>
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)<br/>
	at org.apache.storm.daemon.nimbus$setup_blobstore.invoke(nimbus.clj:1196)<br/>
	at org.apache.storm.daemon.nimbus$fn_<em>7064$exec_fn</em><em>2461</em><em>auto</em>___7065.invoke(nimbus.clj:1416)<br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:156)<br/>
	at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
	at clojure.core$apply.invoke(core.clj:630)<br/>
	at org.apache.storm.daemon.nimbus$fn_<em>7064$service_handler</em>_7308.doInvoke(nimbus.clj:1358)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:421)<br/>
	at org.apache.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:2206)<br/>
	at org.apache.storm.daemon.nimbus$_launch.invoke(nimbus.clj:2239)<br/>
	at org.apache.storm.daemon.nimbus$_main.invoke(nimbus.clj:2262)<br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:152)<br/>
	at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
	at org.apache.storm.daemon.nimbus.main(Unknown Source)<br/>
Caused by: java.nio.file.DirectoryNotEmptyException: /opt/storm/storm-local/blobs/955/some_big_file<br/>
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)<br/>
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)<br/>
	at java.nio.file.Files.deleteIfExists(Files.java:1165)<br/>
	at org.apache.storm.blobstore.FileBlobStoreImpl.delete(FileBlobStoreImpl.java:239)<br/>
	at org.apache.storm.blobstore.FileBlobStoreImpl.deleteKey(FileBlobStoreImpl.java:178)<br/>
	at org.apache.storm.blobstore.LocalFsBlobStore.deleteBlob(LocalFsBlobStore.java:226)<br/>
	... 19 more<br/>
2016-09-14 15:07:48.588 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error on initialization")<br/>
java.lang.RuntimeException: ("Error on initialization")<br/>
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423)<br/>
	at org.apache.storm.daemon.nimbus$fn_<em>7064$service_handler</em>_7308.doInvoke(nimbus.clj:1358)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:421)<br/>
	at org.apache.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:2206)<br/>
	at org.apache.storm.daemon.nimbus$_launch.invoke(nimbus.clj:2239)<br/>
	at org.apache.storm.daemon.nimbus$_main.invoke(nimbus.clj:2262)<br/>
	at clojure.lang.AFn.applyToHelper(AFn.java:152)<br/>
	at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
	at org.apache.storm.daemon.nimbus.main(Unknown Source)</p>

<p><span class="error">&#91;root&#93;</span># ls -l  /opt/storm/storm-local/blobs/955/some_big_file<br/>
total 591060<br/>
<del>rw-r</del><del>r</del>- 1 storm storm 605241344 Sep 14 15:07 1473865562841.tmp</p>

---
<details><summary><i>Originally reported by <a title="Abid Mohammed" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abid.m">abid.m</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2095" target="_blank">Nimbus dies and never recovers due to java.nio.file.DirectoryNotEmptyException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Matt Wissman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mwissman">mwissman</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-01-03T14:18:39+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mwissman">mwissman</a>:</i>
<p>When nimbus dies while a blob is being created, the temp file is left in the directory. When Nimbus starts up and tries to delete the blob, it's looking for a file named after the blob name. That file doesn't exist, and when the delete of the blob folder is attempted, it fails.</p>

<p>To fix this, when deleting the folder for the blob, this will also delete any partially uploaded temp files.</p>

<p>I created a pull request for this: <a href="https://github.com/apache/storm/pull/1848" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1848</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mwissman" class="user-hover" rel="mwissman">Matt Wissman</a>, I merged into master, 1.x, 1.0.x branches.</p>
