### ISSUE TITLE
[STORM-2100] Few tests are getting failed in external/sql module with JDK 7 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5882]
<p>Tests run: 11, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 31.095 sec <<< FAILURE! - in org.apache.storm.sql.compiler.backends.trident.TestPlanCompiler<br/>
testCompileEquiJoinWithRightOuterJoin(org.apache.storm.sql.compiler.backends.trident.TestPlanCompiler)  Time elapsed: 2.434 sec  <<< FAILURE!<br/>
org.junit.internal.ArrayComparisonFailure: arrays first differed at element <span class="error">&#91;0&#93;</span>; expected:<<span class="error">&#91;2, null&#93;</span>> but was:<<span class="error">&#91;3, null&#93;</span>><br/>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:50)<br/>
	at org.junit.Assert.internalArrayEquals(Assert.java:473)<br/>
	at org.junit.Assert.assertArrayEquals(Assert.java:265)<br/>
	at org.junit.Assert.assertArrayEquals(Assert.java:280)<br/>
	at org.apache.storm.sql.compiler.backends.trident.TestPlanCompiler.testCompileEquiJoinWithRightOuterJoin(TestPlanCompiler.java:161)</p>

<p>testCompileEquiJoinWithFullOuterJoin(org.apache.storm.sql.compiler.backends.trident.TestPlanCompiler)  Time elapsed: 2.447 sec  <<< FAILURE!<br/>
org.junit.internal.ArrayComparisonFailure: arrays first differed at element <span class="error">&#91;0&#93;</span>; expected:<<span class="error">&#91;null, dept-2&#93;</span>> but was:<<span class="error">&#91;null, dept-3&#93;</span>><br/>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:50)<br/>
	at org.junit.Assert.internalArrayEquals(Assert.java:473)<br/>
	at org.junit.Assert.assertArrayEquals(Assert.java:265)<br/>
	at org.junit.Assert.assertArrayEquals(Assert.java:280)<br/>
	at org.apache.storm.sql.compiler.backends.trident.TestPlanCompiler.testCompileEquiJoinWithFullOuterJoin(TestPlanCompiler.java:179)</p>

<p>testCompileEquiJoinWithLeftOuterJoin(org.apache.storm.sql.compiler.backends.trident.TestPlanCompiler)  Time elapsed: 2.381 sec  <<< FAILURE!<br/>
org.junit.internal.ArrayComparisonFailure: arrays first differed at element <span class="error">&#91;0&#93;</span>; expected:<<span class="error">&#91;2, null&#93;</span>> but was:<<span class="error">&#91;3, null&#93;</span>><br/>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:50)<br/>
	at org.junit.Assert.internalArrayEquals(Assert.java:473)<br/>
	at org.junit.Assert.assertArrayEquals(Assert.java:265)<br/>
	at org.junit.Assert.assertArrayEquals(Assert.java:280)<br/>
	at org.apache.storm.sql.compiler.backends.trident.TestPlanCompiler.testCompileEquiJoinWithLeftOuterJoin(TestPlanCompiler.java:143)</p>

---
<details><summary><i>Originally reported by <a title="Satish Duggana" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2100" target="_blank">Few tests are getting failed in external/sql module with JDK 7 </a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-09-21T04:50:55+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Took a look about this. Overall rows are same, but it doesn't keep row order in JDK7.<br/>
In this case, I think we should modify the test to not rely on ordering, since we don't sort it.</p>
