### ISSUE TITLE
[STORM-2117] Supervisor V2 with local mode extracts resources directory to topology root directory instead of temporary directory

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5899]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">20:43:57.692 [timer] INFO  o.a.s.d.nimbus - Setting <span class="code-keyword">new</span> assignment <span class="code-keyword">for</span> topology id storm-sql-1-1474544636: #org.apache.storm.daemon.common.Assignment{:master-code-dir <span class="code-quote">"/<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T<span class="code-comment">//ba7ef925-0dd5-4ddd-91ad-02ff877b99ef"</span>, :node->host {<span class="code-quote">"35e30049-e731-40e7-a093-2ac22d9efa34"</span> <span class="code-quote">"192.168.0.9"</span>}, :executor->node+port {[4 4] [<span class="code-quote">"35e30049-e731-40e7-a093-2ac22d9efa34"</span> 1024], [3 3] [<span class="code-quote">"35e30049-e731-40e7-a093-2ac22d9efa34"</span> 1024], [6 6] [<span class="code-quote">"35e30049-e731-40e7-a093-2ac22d9efa34"</span> 1024], [2 2] [<span class="code-quote">"35e30049-e731-40e7-a093-2ac22d9efa34"</span> 1024], [5 5] [<span class="code-quote">"35e30049-e731-40e7-a093-2ac22d9efa34"</span> 1024], [1 1] [<span class="code-quote">"35e30049-e731-40e7-a093-2ac22d9efa34"</span> 1024]}, :executor->start-time-secs {[1 1] 1474544637, [2 2] 1474544637, [3 3] 1474544637, [4 4] 1474544637, [5 5] 1474544637, [6 6] 1474544637}, :worker->resources {[<span class="code-quote">"35e30049-e731-40e7-a093-2ac22d9efa34"</span> 1024] [0.0 0.0 0.0]}}
</span>20:43:57.824 [Async Localizer] INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting
20:43:57.825 [SLOT_1024] INFO  o.a.s.d.s.Slot - STATE EMPTY msInState: 1016 -> WAITING_FOR_BASIC_LOCALIZATION msInState: 0
20:43:57.827 [Async Localizer] INFO  o.a.s.b.FileBlobStoreImpl - Creating <span class="code-keyword">new</span> blob store based in /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/ba7ef925-0dd5-4ddd-91ad-02ff877b99ef/blobs
20:43:57.830 [Async Localizer-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
20:43:57.846 [Curator-Framework-0] INFO  o.a.c.f.i.CuratorFrameworkImpl - backgroundOperationsLoop exiting
20:43:57.920 [Async Localizer] INFO  o.a.s.l.AsyncLocalizer - Extracting resources from jar at /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/lib/ant-javafx.jar to /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/tmp/0271204f-6007-4571-b8e7-4a7aa124f274/resources
20:43:57.941 [Async Localizer] WARN  o.a.s.l.AsyncLocalizer - Failed to download basic resources <span class="code-keyword">for</span> topology-id storm-sql-1-1474544636
20:43:57.941 [Async Localizer] INFO  o.a.s.d.s.AdvancedFSOps - Deleting path /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/tmp/0271204f-6007-4571-b8e7-4a7aa124f274
20:43:57.944 [Async Localizer] INFO  o.a.s.d.s.AdvancedFSOps - Deleting path /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/stormdist/storm-sql-1-1474544636
20:43:57.947 [Async Localizer] WARN  o.a.s.l.AsyncLocalizer - Caught Exception While Downloading (rethrowing)... 
java.nio.file.FileSystemException: /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/tmp/0271204f-6007-4571-b8e7-4a7aa124f274 -> /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/stormdist/storm-sql-1-1474544636: Directory not empty
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_66]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_66]
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:396) ~[?:1.8.0_66]
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262) ~[?:1.8.0_66]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_66]
	at org.apache.storm.daemon.supervisor.AdvancedFSOps.moveDirectoryPreferAtomic(AdvancedFSOps.java:159) ~[classes/:?]
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:144) [classes/:?]
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:98) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_66]
20:43:57.953 [SLOT_1024] ERROR o.a.s.d.s.Slot - Error when processing event
java.util.concurrent.ExecutionException: java.nio.file.FileSystemException: /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/tmp/0271204f-6007-4571-b8e7-4a7aa124f274 -> /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/stormdist/storm-sql-1-1474544636: Directory not empty
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) ~[?:1.8.0_66]
	at org.apache.storm.localizer.LocalDownloadedResource$NoCancelFuture.get(LocalDownloadedResource.java:63) ~[classes/:?]
	at org.apache.storm.daemon.supervisor.Slot.handleWaitingForBasicLocalization(Slot.java:413) ~[classes/:?]
	at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:273) ~[classes/:?]
	at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:741) [classes/:?]
Caused by: java.nio.file.FileSystemException: /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/tmp/0271204f-6007-4571-b8e7-4a7aa124f274 -> /<span class="code-keyword">var</span>/folders/t7/dd7tgll1435bm2kbsdy358880000gn/T/043fbb03-fbdc-4271-bbae-923f1138745d/supervisor/stormdist/storm-sql-1-1474544636: Directory not empty
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_66]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_66]
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:396) ~[?:1.8.0_66]
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262) ~[?:1.8.0_66]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_66]
	at org.apache.storm.daemon.supervisor.AdvancedFSOps.moveDirectoryPreferAtomic(AdvancedFSOps.java:159) ~[classes/:?]
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:144) ~[classes/:?]
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:98) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_66]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) ~[?:1.8.0_66]
20:43:57.954 [SLOT_1024] ERROR o.a.s.u.Utils - Halting process: Error when processing an event
java.lang.RuntimeException: Halting process: Error when processing an event
	at org.apache.storm.utils.Utils.exitProcess(Utils.java:1771) [classes/:?]
	at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:774) [classes/:?]

<span class="code-object">Process</span> finished with exit code 20
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2117" target="_blank">Supervisor V2 with local mode extracts resources directory to topology root directory instead of temporary directory</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-10-27T17:08:34+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Reopen to change fix versions.</p>
