### ISSUE TITLE
[STORM-2129] start storm application get CuratorConnectionLossException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5911]
<p>32257 [Thread-32-kafka-reader-executor<span class="error">&#91;4 4&#93;</span>] ERROR o.a.c.ConnectionState - Connection timed out for connection string (yj-es-6:2181,yj-es-5:2181) and timeout (15000) / elapsed (15084)<br/>
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss<br/>
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:200) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:111) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:84) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.trident.ZkBrokerReader.<init>(ZkBrokerReader.java:44) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.KafkaUtils.makeBrokerReader(KafkaUtils.java:58) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.KafkaSpout.open(KafkaSpout.java:77) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.daemon.executor$fn_<em>7990$fn</em>_8005.invoke(executor.clj:604) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:482) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_79&#93;</span><br/>
32257 [Thread-30-kafka-reader-executor<span class="error">&#91;5 5&#93;</span>] ERROR o.a.c.ConnectionState - Connection timed out for connection string (yj-es-6:2181,yj-es-5:2181) and timeout (15000) / elapsed (15083)<br/>
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss<br/>
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:200) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:111) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:84) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.trident.ZkBrokerReader.<init>(ZkBrokerReader.java:44) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.KafkaUtils.makeBrokerReader(KafkaUtils.java:58) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.KafkaSpout.open(KafkaSpout.java:77) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.daemon.executor$fn_<em>7990$fn</em>_8005.invoke(executor.clj:604) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:482) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_79&#93;</span><br/>
32257 [Thread-24-kafka-reader-executor<span class="error">&#91;6 6&#93;</span>] ERROR o.a.c.ConnectionState - Connection timed out for connection string (yj-es-6:2181,yj-es-5:2181) and timeout (15000) / elapsed (15084)<br/>
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss<br/>
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108) <span class="error">&#91;curator-client-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:200) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38) <span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
	at org.apache.storm.kafka.DynamicBrokersReader.getNumPartitions(DynamicBrokersReader.java:111) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.DynamicBrokersReader.getBrokerInfo(DynamicBrokersReader.java:84) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.trident.ZkBrokerReader.<init>(ZkBrokerReader.java:44) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.KafkaUtils.makeBrokerReader(KafkaUtils.java:58) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.kafka.KafkaSpout.open(KafkaSpout.java:77) <span class="error">&#91;storm-kafka-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.daemon.executor$fn_<em>7990$fn</em>_8005.invoke(executor.clj:604) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:482) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_79&#93;</span></p>

---
<details><summary><i>Originally reported by <a title=".D." href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Joker.D.">Joker.D.</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2129" target="_blank">start storm application get CuratorConnectionLossException</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:00+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
