### ISSUE TITLE
[STORM-2132] NullPointerException in KafkaSpout

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5914]
<p>Received a null pointer exception using storm-kafka-client.  Not sure what caused it, was just sitting idle in my IDE.  It did crash my topology.</p>

<p>Here's the consumer information:<br/>
topic 	0	1,546	2,802	2,798	4<br/>
topic 	1	1,663	2,856	2,856	0<br/>
topic 	2	1,671	3,031	3,022	9<br/>
topic 	3	1,648	2,760	2,760	0<br/>
topic 	4	1,618	2,828	2,824	4<br/>
topic 	5	1,537	2,599	2,595	4<br/>
topic 	6	1,469	2,522	2,522	0</p>

<p>java.lang.NullPointerException<br/>
	at org.apache.storm.kafka.spout.KafkaSpout.doSeekRetriableTopicPartitions(KafkaSpout.java:249)<br/>
	at org.apache.storm.kafka.spout.KafkaSpout.pollKafkaBroker(KafkaSpout.java:237)<br/>
	at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:203)<br/>
	at org.apache.storm.daemon.executor$fn_<em>7990$fn</em><em>8005$fn</em>_8036.invoke(executor.clj:648)<br/>
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484)<br/>
	at clojure.lang.AFn.run(AFn.java:22)<br/>
	at java.lang.Thread.run(Thread.java:745)<br/>
[Thread-34-kafka-spout-executor<span class="error">&#91;4 5&#93;</span>] ERROR org.apache.storm.daemon.executor - <br/>
java.lang.NullPointerException<br/>
	at org.apache.storm.kafka.spout.KafkaSpout.doSeekRetriableTopicPartitions(KafkaSpout.java:249)<br/>
	at org.apache.storm.kafka.spout.KafkaSpout.pollKafkaBroker(KafkaSpout.java:237)<br/>
	at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:203)<br/>
	at org.apache.storm.daemon.executor$fn_<em>7990$fn</em><em>8005$fn</em>_8036.invoke(executor.clj:648)<br/>
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484)<br/>
	at clojure.lang.AFn.run(AFn.java:22)<br/>
	at java.lang.Thread.run(Thread.java:745)<br/>
[Thread-34-kafka-spout-executor<span class="error">&#91;4 5&#93;</span>] ERROR org.apache.storm.util - Halting process: ("Worker died")<br/>
java.lang.RuntimeException: ("Worker died")<br/>
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341)<br/>
	at clojure.lang.RestFn.invoke(RestFn.java:423)<br/>
	at org.apache.storm.daemon.worker$fn_<em>8659$fn</em>_8660.invoke(worker.clj:761)<br/>
	at org.apache.storm.daemon.executor$mk_executor_data$fn_<em>7875$fn</em>_7876.invoke(executor.clj:274)<br/>
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:494)<br/>
	at clojure.lang.AFn.run(AFn.java:22)<br/>
	at java.lang.Thread.run(Thread.java:745)</p>

---
<details><summary><i>Originally reported by <a title="Nick Cuneo" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=logikz">logikz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2132" target="_blank">NullPointerException in KafkaSpout</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:14+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=f1sherox">f1sherox</a>:</i>
<p>Fixed in <a href="https://issues.apache.org/jira/browse/STORM-2104" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-2104</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
