### ISSUE TITLE
[STORM-2138] java.io.FileNotFoundException: stormconf.ser does not exist

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5920]
<p>We are seeing problems in our storm topology whereby all our workers crash.</p>

<p>The errors we see are</p>

<p>2016-10-07 09:49:33.599 o.a.s.d.supervisor <span class="error">&#91;ERROR&#93;</span> Error on initialization of server mk-supervisor<br/>
java.io.FileNotFoundException: File '/opt/storm_local/supervisor/stormdist/production_2016_09_13-1-1475831938/stormconf.ser' does not exist<br/>
at org.apache.storm.shade.org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:292)<br/>
at org.apache.storm.shade.org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1815)<br/>
at org.apache.storm.config$read_supervisor_storm_conf_given_path.invoke(config.clj:142)<br/>
at org.apache.storm.config$read_supervisor_storm_conf.invoke(config.clj:221)<br/>
at org.apache.storm.daemon.supervisor$add_blob_references.invoke(supervisor.clj:495)<br/>
at org.apache.storm.daemon.supervisor$fn_<em>9307$exec_fn</em><em>2466</em><em>auto</em>___9308.invoke(supervisor.clj:795)<br/>
at clojure.lang.AFn.applyToHelper(AFn.java:160)<br/>
at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
at clojure.core$apply.invoke(core.clj:630)<br/>
at org.apache.storm.daemon.supervisor$fn_<em>9307$mk_supervisor</em>_9352.doInvoke(supervisor.clj:763)<br/>
at clojure.lang.RestFn.invoke(RestFn.java:436)<br/>
at org.apache.storm.daemon.supervisor$_launch.invoke(supervisor.clj:1200)<br/>
at org.apache.storm.daemon.supervisor$_main.invoke(supervisor.clj:1233)<br/>
at clojure.lang.AFn.applyToHelper(AFn.java:152)<br/>
at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
at org.apache.storm.daemon.supervisor.main(Unknown Source)<br/>
2016-10-07 09:49:33.608 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error on initialization")<br/>
java.lang.RuntimeException: ("Error on initialization")<br/>
at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341)<br/>
at clojure.lang.RestFn.invoke(RestFn.java:423)<br/>
at org.apache.storm.daemon.supervisor$fn_<em>9307$mk_supervisor</em>_9352.doInvoke(supervisor.clj:763)<br/>
at clojure.lang.RestFn.invoke(RestFn.java:436)<br/>
at org.apache.storm.daemon.supervisor$_launch.invoke(supervisor.clj:1200)<br/>
at org.apache.storm.daemon.supervisor$_main.invoke(supervisor.clj:1233)<br/>
at clojure.lang.AFn.applyToHelper(AFn.java:152)<br/>
at clojure.lang.AFn.applyTo(AFn.java:144)<br/>
at org.apache.storm.daemon.supervisor.main(Unknown Source)<br/>
2016-10-07 09:49:34.668 o.a.s.d.supervisor <span class="error">&#91;INFO&#93;</span> Removing code for storm id production_2016_09_13-1-1475831938</p>

<p>We have looked at <a href="https://github.com/apache/storm/pull/418" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/418</a> and <a href="https://issues.apache.org/jira/browse/STORM-130" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-130</a>, which both show the first issue as being fixed - however we are still experiencing it in 1.0.2. The changes from the fixing commit (<a href="https://github.com/apache/storm/pull/418/commits/ccd28f8a356f468e66865fa9d9901b0a2628ec74" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/418/commits/ccd28f8a356f468e66865fa9d9901b0a2628ec74</a>) don't seem to be in the current version of the file (<a href="https://github.com/apache/storm/blob/v1.0.2/storm-core/src/clj/org/apache/storm/daemon/supervisor.clj" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v1.0.2/storm-core/src/clj/org/apache/storm/daemon/supervisor.clj</a>).</p>

<p>We get this often when resubmitting a topology, and our only workaround is to stop the topology, delete the whole /opt/storm_local directory (which is our storm.local.dir) and resubmit the topology. Often, the workers seem to be looking for stormconf.ser in the local directory of an old topology that isn't even running at the time.</p>

---
<details><summary><i>Originally reported by <a title="Eddy" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eddy">eddy</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2138" target="_blank">java.io.FileNotFoundException: stormconf.ser does not exist</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:03+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kristopherkane">kristopherkane</a>:</i>
<p>I can confirm this on 1.0.2 but instead of worker failure, I see the Supervisor shut down after a time.  Inspecting the supervisor after it is noticed as down, I see that the stormconf.ser file is present, with the correct ownership, in the reported missing file location. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hummel.michel@gmail.com">hummel.michel@gmail.com</a>:</i>
<p>Same issue with 1.0.3, sometime supervisors shutdown on java.lang.RuntimeException: java.io.FileNotFoundException: File '/space/StormData/storm-data/supervisor/stormdist/MyTopo/stormconf.ser' does not exist)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hummel.michel@gmail.com">hummel.michel@gmail.com</a>:</i>
<p>This issue still exists in V1.2.2.</p>

<p>I think there is a race condition when a topology is stopping:</p>

<p>the supervisor is removing the local files:</p>

<p> </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2018-09-14 21:33:03.718 o.a.s.d.s.Container [INFO] Cleaning up 5485e983-34a9-46ad-8679-bbe79c110cba:32173038-42d8-40c7-94ce-9229e3177b6e
2018-09-14 21:33:03.718 o.a.s.d.s.Container [INFO] GET worker-user for 32173038-42d8-40c7-94ce-9229e3177b6e
2018-09-14 21:33:03.718 o.a.s.d.s.AdvancedFSOps [INFO] Deleting path /space/StormData/storm-data/workers/32173038-42d8-40c7-94ce-9229e3177b6e/pids/69074
2018-09-14 21:33:03.718 o.a.s.d.s.AdvancedFSOps [INFO] Deleting path /space/StormData/storm-data/workers/32173038-42d8-40c7-94ce-9229e3177b6e/heartbeats
2018-09-14 21:33:03.730 o.a.s.d.s.AdvancedFSOps [INFO] Deleting path /space/StormData/storm-data/workers/32173038-42d8-40c7-94ce-9229e3177b6e/pids
2018-09-14 21:33:03.731 o.a.s.d.s.AdvancedFSOps [INFO] Deleting path /space/StormData/storm-data/workers/32173038-42d8-40c7-94ce-9229e3177b6e/tmp
2018-09-14 21:33:03.731 o.a.s.d.s.AdvancedFSOps [INFO] Deleting path /space/StormData/storm-data/workers/32173038-42d8-40c7-94ce-9229e3177b6e
2018-09-14 21:33:03.732 o.a.s.d.s.Container [INFO] REMOVE worker-user 32173038-42d8-40c7-94ce-9229e3177b6e
2018-09-14 21:33:03.732 o.a.s.d.s.AdvancedFSOps [INFO] Deleting path /space/StormData/storm-data/workers-users/32173038-42d8-40c7-94ce-9229e3177b6e
2018-09-14 21:33:03.734 o.a.s.d.s.BasicContainer [INFO] Removed Worker ID 32173038-42d8-40c7-94ce-9229e3177b6e
2018-09-14 21:33:03.734 o.a.s.l.AsyncLocalizer [INFO] Released blob reference ipc-fci-nrt_Tsit-RCFD_2017100_02222018-09-14T21-22-51-429Z-100-1536960172 6702 Cleaning up BLOB references...
2018-09-14 21:33:03.735 o.a.s.l.AsyncLocalizer [INFO] Released blob reference ipc-fci-nrt_Tsit-RCFD_2017100_02222018-09-14T21-22-51-429Z-100-1536960172 6702 Cleaning up basic files...
2018-09-14 21:33:03.735 o.a.s.d.s.AdvancedFSOps [INFO] Deleting path /space/StormData/storm-data/supervisor/stormdist/ipc-fci-nrt_Tsit-RCFD_2017100_02222018-09-14T21-22-51-429Z-100-1536960172
</pre>
</div></div>
<p>and if the blobUpdateTimer is trigged at the same time</p>

<p> </p>

<p><a href="https://github.com/apache/storm/blob/v1.2.2/storm-core/src/jvm/org/apache/storm/daemon/supervisor/timer/UpdateBlobs.java" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v1.2.2/storm-core/src/jvm/org/apache/storm/daemon/supervisor/timer/UpdateBlobs.java</a> </p>

<p>it will search for the topology configuration which doesn't exists anymore:</p>

<p> </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2018-09-14 21:33:03.796 o.a.s.e.EventManagerImp [ERROR] {} Error when processing event
java.lang.RuntimeException: java.io.FileNotFoundException: File '/space/StormData/storm-data/supervisor/stormdist/ipc-fci-nrt_Tsit-RCFD_2017100_02222018-09-14T21-22-51-429Z-100-1536960172/stormconf.ser' does not exist
at org.apache.storm.utils.Utils.wrapInRuntime(Utils.java:1571) ~[storm-core-1.2.2.jar:1.2.2]
at org.apache.storm.daemon.supervisor.timer.UpdateBlobs.run(UpdateBlobs.java:86) ~[storm-core-1.2.2.jar:1.2.2]
at org.apache.storm.event.EventManagerImp$1.run(EventManagerImp.java:54) [storm-core-1.2.2.jar:1.2.2]
Caused by: java.io.FileNotFoundException: File '/space/StormData/storm-data/supervisor/stormdist/ipc-fci-nrt_Tsit-RCFD_2017100_02222018-09-14T21-22-51-429Z-100-1536960172/stormconf.ser' does not exist
at org.apache.storm.shade.org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:292) ~[storm-core-1.2.2.jar:1.2.2]
at org.apache.storm.shade.org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1815) ~[storm-core-1.2.2.jar:1.2.2]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfGivenPath(ConfigUtils.java:262) ~[storm-core-1.2.2.jar:1.2.2]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfImpl(ConfigUtils.java:374) ~[storm-core-1.2.2.jar:1.2.2]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConf(ConfigUtils.java:368) ~[storm-core-1.2.2.jar:1.2.2]
at org.apache.storm.daemon.supervisor.timer.UpdateBlobs.updateBlobsForTopology(UpdateBlobs.java:100) ~[storm-core-1.2.2.jar:1.2.2]
at org.apache.storm.daemon.supervisor.timer.UpdateBlobs.run(UpdateBlobs.java:76) ~[storm-core-1.2.2.jar:1.2.2]
... 1 more
</pre>
</div></div>
<p>I think that dealing with this race condition is hard without doing a lock may-be adding a catch on FileNotFoundException could be an acceptable fix ?</p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
