### ISSUE TITLE
[STORM-2158] OutOfMemoryError in Nimbus' SimpleTransportPlugin

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5940]
<p><tt>OutOfMemoryError</tt> is thrown by Nimbus' <tt>SimpleTransportPlugin</tt> if malformed Thrift request is posted:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">echo <span class="code-quote">"Hello"</span> | nc localhost 6627
</pre>
</div></div>

<p>In nimbus.log:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2016-10-20 12:54:09.978 b.s.d.nimbus [INFO] Starting Nimbus server...
2016-10-20 12:54:42.926 o.a.t.s.THsHaServer [ERROR] run() exiting due to uncaught error
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57) ~[?:1.8.0_92-internal]
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335) ~[?:1.8.0_92-internal]
	at org.apache.thrift7.server.AbstractNonblockingServer$FrameBuffer.read(AbstractNonblockingServer.java:371) ~[storm-core-0.10.3-SNAPSHOT.jar:0.10.3-SNAPSHOT]
	at org.apache.thrift7.server.AbstractNonblockingServer$AbstractSelectThread.handleRead(AbstractNonblockingServer.java:203) ~[storm-core-0.10.3-SNAPSHOT.jar:0.10.3-SNAPSHOT]
	at org.apache.thrift7.server.TNonblockingServer$SelectAcceptThread.select(TNonblockingServer.java:207) ~[storm-core-0.10.3-SNAPSHOT.jar:0.10.3-SNAPSHOT]
	at org.apache.thrift7.server.TNonblockingServer$SelectAcceptThread.run(TNonblockingServer.java:158) [storm-core-0.10.3-SNAPSHOT.jar:0.10.3-SNAPSHOT]
2016-10-20 12:54:42.942 b.s.d.nimbus [INFO] Shutting down master
2016-10-20 12:54:43.003 b.s.d.nimbus [INFO] Shut down master
</pre>
</div></div>

<p>The problem is caused by the lack of specification of the <tt>maxReadBufferBytes</tt> of <tt>THsHaServer</tt>'s arguments.</p>

---
<details><summary><i>Originally reported by <a title="Tibor Kiss" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor.kiss@gmail.com">tibor.kiss@gmail.com</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2158" target="_blank">OutOfMemoryError in Nimbus' SimpleTransportPlugin</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Tibor Kiss" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor.kiss@gmail.com">tibor.kiss@gmail.com</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-10-25T22:28:14+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor.kiss@gmail.com">tibor.kiss@gmail.com</a>:</i>
<p>Kerberized Storm is unaffected by this change as THsHaServer is not used there.</p>
