### ISSUE TITLE
[STORM-2175] Supervisor V2 can possibly shut down workers twice in local mode

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5957]
<p>See <a href="https://github.com/apache/storm/pull/1697#issuecomment-256456889" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1697#issuecomment-256456889</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NullPointerException
    at org.apache.storm.utils.DisruptorQueue$FlusherPool.stop(DisruptorQueue.java:110)
    at org.apache.storm.utils.DisruptorQueue$Flusher.close(DisruptorQueue.java:293)
    at org.apache.storm.utils.DisruptorQueue.haltWithInterrupt(DisruptorQueue.java:410)
    at org.apache.storm.disruptor$halt_with_interrupt_BANG_.invoke(disruptor.clj:77)
    at org.apache.storm.daemon.executor$mk_executor$reify__4923.shutdown(executor.clj:412)
    at sun.reflect.GeneratedMethodAccessor303.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
    at org.apache.storm.daemon.worker$fn__5550$exec_fn__1372__auto__$reify__5552$shutdown_STAR___5572.invoke(worker.clj:668)
    at org.apache.storm.daemon.worker$fn__5550$exec_fn__1372__auto__$reify$reify__5598.shutdown(worker.clj:706)
    at org.apache.storm.ProcessSimulator.killProcess(ProcessSimulator.java:66)
    at org.apache.storm.ProcessSimulator.killAllProcesses(ProcessSimulator.java:79)
    at org.apache.storm.testing$kill_local_storm_cluster.invoke(testing.clj:207)
    at org.apache.storm.testing4j$_withLocalCluster.invoke(testing4j.clj:93)
    at org.apache.storm.Testing.withLocalCluster(Unknown Source)
</pre>
</div></div>

<p>and</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.IllegalStateException: Timer is not active
    at org.apache.storm.timer$check_active_BANG_.invoke(timer.clj:87)
    at org.apache.storm.timer$cancel_timer.invoke(timer.clj:120)
    at org.apache.storm.daemon.worker$fn__5550$exec_fn__1372__auto__$reify__5552$shutdown_STAR___5572.invoke(worker.clj:682)
    at org.apache.storm.daemon.worker$fn__5550$exec_fn__1372__auto__$reify$reify__5598.shutdown(worker.clj:706)
    at org.apache.storm.ProcessSimulator.killProcess(ProcessSimulator.java:66)
    at org.apache.storm.ProcessSimulator.killAllProcesses(ProcessSimulator.java:79)
    at org.apache.storm.testing$kill_local_storm_cluster.invoke(testing.clj:207)
    at org.apache.storm.testing4j$_withLocalCluster.invoke(testing4j.clj:93)
    at org.apache.storm.Testing.withLocalCluster(Unknown Source)
</pre>
</div></div>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> is still working on getting a reproducible use case for us. But I will try to reproduce/fix it myself in the mean time.</p>

---
<details><summary><i>Originally reported by <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2175" target="_blank">Supervisor V2 can possibly shut down workers twice in local mode</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-11-03T00:22:34+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> This seems to provoke the errors reasonably often <a href="https://github.com/srdo/storm/blob/STORM-2175-reproduction/examples/storm-starter/test/jvm/org/apache/storm/starter/tools/STORM2175.java" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/srdo/storm/blob/STORM-2175-reproduction/examples/storm-starter/test/jvm/org/apache/storm/starter/tools/STORM2175.java</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>,</p>

<p>Thanks I was able to reproduce the issue with this.  I could not make it happen on master though, so I am really interested to see what is going on.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>OK I was looking through the logs and found what happened (and honestly I think it is actually a good thing).</p>

<p>When shutting down a local mode cluster inside testing.clj we have.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">  (doseq [s @(:supervisors cluster-map)]
    (.shutdownAllWorkers s)
    ;; race condition here? will it launch the workers again?
    (.close s))
  (ProcessSimulator/killAllProcesses)
</pre>
</div></div>

<p>NOTE: the comment above is not what is causing this issue.</p>

<p>So all of the supervisors are shut down, first by killing all of the worker processes and then by closing the supervisor.<br/>
After all of the supervisors are shut down, just to be sure, we then kill all of the processes still registered with the process simulator.</p>

<p>The code for killing all of the workers in a supervisor is the following...</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">    <span class="code-keyword">public</span> <span class="code-keyword">synchronized</span> void shutdownAllWorkers() {
<span class="code-keyword">for</span> (Slot slot: slots.values()) {
    slot.setNewAssignment(<span class="code-keyword">null</span>);
}

<span class="code-keyword">for</span> (Slot slot: slots.values()) {
    <span class="code-keyword">try</span> {
<span class="code-object">int</span> count = 0;
<span class="code-keyword">while</span> (slot.getMachineState() != MachineState.EMPTY) {
    <span class="code-keyword">if</span> (count > 10) {
LOG.warn(<span class="code-quote">"DONE waiting <span class="code-keyword">for</span> {} to finish {}"</span>, slot, slot.getMachineState());
<span class="code-keyword">break</span>;
    }
    <span class="code-keyword">if</span> (Time.isSimulating()) {
Time.advanceTime(1000);
<span class="code-object">Thread</span>.sleep(100);
    } <span class="code-keyword">else</span> {
Time.sleep(100);
    }
    count++;
}
    } <span class="code-keyword">catch</span> (Exception e) {
LOG.error(<span class="code-quote">"Error trying to shutdown workers in {}"</span>, slot, e);
    }
}
    }
</pre>
</div></div>

<p>It tells the Slot that it is not assigned anything any more and waits for it to kill the worker under it.  I saw in the logs that for the one worker in question it timed out ("DONE waiting for...") and went on to kill/shut down other things. </p>

<p>The ProcessSimulator code to kill local mode worker is.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">    /**
     * Kill a process
     *
     * @param pid
     */
    <span class="code-keyword">public</span> <span class="code-keyword">static</span> void killProcess(<span class="code-object">String</span> pid) {
<span class="code-keyword">synchronized</span> (lock) {
    LOG.info(<span class="code-quote">"Begin killing process "</span> + pid);
    Shutdownable shutdownHandle = processMap.get(pid);
    <span class="code-keyword">if</span> (shutdownHandle != <span class="code-keyword">null</span>) {
shutdownHandle.shutdown();
    }
    processMap.remove(pid);
    LOG.info(<span class="code-quote">"Successfully killed process "</span> + pid);
}
    }

    /**
     * Kill all processes
     */
    <span class="code-keyword">public</span> <span class="code-keyword">static</span> void killAllProcesses() {
Set<<span class="code-object">String</span>> pids = processMap.keySet();
<span class="code-keyword">for</span> (<span class="code-object">String</span> pid : pids) {
    killProcess(pid);
}
    }
</pre>
</div></div>

<p>Inside the logs I don't see a corresponding "Successfully killed process " for the "Begin killing process ".  This means that an exception was thrown during the shutdown process.  Looking at the code the only exception that could have caused this is an InterruptedException or something caused by it (or else the entire processes would have exited).</p>

<p>This means that the ProcessSimulator partially shut down the worker, then the worker threw the exception, and ProcessSimulator failed to remove the worker from the map.  That way when the follow on code to kill anything registered with the process simulator that might have leaked is called it ends up trying to shoot the process yet again, which the code we found does not like.</p>

<p>Everything seems perfectly reasonable, except for the part where some of our data structures don't like to be shut down multiple times.  This seems against what most other software does.  Exactly once is hard so lets make sure at least once works.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thanks for the explanation. You're right, it's much easier if the structures can handle being closed repeatedly. So this issue should probably become about changing timer, executor, worker and DisruptorQueue (or really anything Shutdownable) so they can handle multiple calls to shutdown.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Yes, that is just what I am doing, and also making ProcessSimulator eat InterruptedExceptions (because a test shouldn't fail for an exception that we expect to happen and ignore in other parts of the code).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I put up two pull requests, one for master and another for 1.x.  I manually forced Interrupted exceptions for the test <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> posted and verified that this works.</p>

<p>I also found a number of leaked threads from nimbus and a few other possible places. I'll file a follow on JIRA for them, because they are not causing issues right now.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>I ran the 1.x version of the PR against our test set. It seems to solve this issue, but introduces a new one. One of our tests uses the storm-kafka-clients spout, which can't handle being closed multiple times, because the underlying KafkaConsumer can only be closed once, and the spout doesn't check if it's already been closed. We might want to add a note to ISpout and IBolt that close may be called repeatedly, and we should probably also make sure that the spouts/bolts shipping with Storm can handle repeated closes.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Actually I'm wondering if that's the right way to go about this. Bolt/spout closes would have to support both being closed multiple times, and being partially closed by the Slot, interrupted and closed again by ProcessSimulator. Maybe it would be better if local mode just gave the Slot significantly longer to close the components it's responsible for? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I am fine with giving them more time to shut down.  I am even OK with throwing an exception if it does not shut down within the desired amount of time.  We already limit the amount of time a worker has before it kills itself to 1 second, so I can see why something that normally is at most once needs to be at least once for local mode can be confusing.</p>

<p>I'll close the pull requests and update them accordingly.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>,</p>

<p>I updated the code with your suggestions.  If you could try again that would be great.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> <br/>
Thanks, this is a good change, and most of our tests now pass (though not entirely reliably). I'm running into the timeout for the test using the Kafka spout fairly consistently though. I've posted a small PR against the 1.x version of the branch to disable the timeout in local mode. Tests may fail spuriously due to a slow machine, or bolts/spouts being slow to close.</p>

<p>Raising the timeout in shutdownAllWorkers isn't guaranteed to work for everyone, and making it configurable is fiddly in tests and irrelevant for distributed mode, due to the 1 second limit on worker suicide. Giving up on shutting down the worker properly leads to leaking resources in local mode, since we can't just kill the JVM. I think removing the timeout for shutdownAllWorkers in local mode is a decent fix. It's still very visible if a Slot is hanging for some reason, since the warning about a slow Slot shutdown is still printed, and we avoid dealing with issues like Slots being slow to shutdown due to tests with a high fork count, or tests on slow machines, or optimistic bolt/spout close functions that don't time limit themselves.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a>, I merged into master, 1.x, 1.0.x branches respectively.</p>
