### ISSUE TITLE
[STORM-2194] ReportErrorAndDie doesn't always die

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5976]
<p>I've been trying to track down a cause of some of our issues with some exceptions leaving Storm workers in a zombified state for some time. I believe I've isolated the bug to the behaviour in :report-error-and-die/reportErrorAndDie in the executor. Essentially:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">     :report-error-and-die (fn [error]
     (<span class="code-keyword">try</span>
       ((:report-error <>) error)
       (<span class="code-keyword">catch</span> Exception e
 (log-message <span class="code-quote">"Error <span class="code-keyword">while</span> reporting error to cluster, proceeding with shutdown"</span>)))
     (<span class="code-keyword">if</span> (or
    (exception-cause? InterruptedException error)
    (exception-cause? java.io.InterruptedIOException error))
       (log-message <span class="code-quote">"Got interrupted excpetion shutting thread down..."</span>)
       ((:suicide-fn <>))))
</pre>
</div></div>

<p>has the grouping for the if statement slightly wrong. It shouldn't log OR die from InterruptedException/InterruptedIOException, but it should log under that condition, and ALWAYS die. </p>

<p>Basically:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">     :report-error-and-die (fn [error]
     (<span class="code-keyword">try</span>
       ((:report-error <>) error)
       (<span class="code-keyword">catch</span> Exception e
 (log-message <span class="code-quote">"Error <span class="code-keyword">while</span> reporting error to cluster, proceeding with shutdown"</span>)))
     (<span class="code-keyword">if</span> (or
    (exception-cause? InterruptedException error)
    (exception-cause? java.io.InterruptedIOException error))
       (log-message <span class="code-quote">"Got interrupted excpetion shutting thread down..."</span>))
     ((:suicide-fn <>)))
</pre>
</div></div>

<p>After digging into the Java port of this code, it looks like a different bug was introduced while porting:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">if</span> (Utils.exceptionCauseIsInstanceOf(InterruptedException.class, e)
|| Utils.exceptionCauseIsInstanceOf(java.io.InterruptedIOException.class, e)) {
    LOG.info(<span class="code-quote">"Got interrupted exception shutting thread down..."</span>);
    suicideFn.run();
}
</pre>
</div></div>

<p>Was how this was initially ported, and <a href="https://issues.apache.org/jira/browse/STORM-2142" title="ReportErrorAndDie runs suicide function only when InterruptedException or InterruptedIOException is thrown" class="issue-link" data-issue-key="STORM-2142"><del>STORM-2142</del></a> changed this to:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">if</span> (Utils.exceptionCauseIsInstanceOf(InterruptedException.class, e)
|| Utils.exceptionCauseIsInstanceOf(java.io.InterruptedIOException.class, e)) {
    LOG.info(<span class="code-quote">"Got interrupted exception shutting thread down..."</span>);
} <span class="code-keyword">else</span> {
    suicideFn.run();
}
</pre>
</div></div>

<p>However, I believe the correct port is as described above:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">if</span> (Utils.exceptionCauseIsInstanceOf(InterruptedException.class, e)
|| Utils.exceptionCauseIsInstanceOf(java.io.InterruptedIOException.class, e)) {
    LOG.info(<span class="code-quote">"Got interrupted exception shutting thread down..."</span>);
}
suicideFn.run();
</pre>
</div></div>

<p>I'll look into providing patches for the 1.x and 2.x branches shortly.</p>

---
<details><summary><i>Originally reported by <a title="Craig Hawco" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chawco">chawco</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2194" target="_blank">ReportErrorAndDie doesn't always die</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Paul Poulosky" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ppoulosk">ppoulosk</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-03-08T21:55:56+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chawco">chawco</a>:</i>
<p>This has PRs for 1.0.x-branch and master &#8211; I'm not sure what the procedure is for 1.x-branch is. Please let me know if I should open another PR for that branch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Could you attach thread dump when you got zombie Storm worker? That was introduced on <a href="https://issues.apache.org/jira/browse/STORM-773" title="backtype.storm.transactional-test fails periodically with timeout" class="issue-link" data-issue-key="STORM-773"><del>STORM-773</del></a> but haven't received similar report.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chawco">chawco</a>:</i>
<p>Will do, however after looking through <a href="https://issues.apache.org/jira/browse/STORM-772" title="Tasts fail periodically with InterruptedException or InterruptedIOException" class="issue-link" data-issue-key="STORM-772"><del>STORM-772</del></a> and <a href="https://issues.apache.org/jira/browse/STORM-773" title="backtype.storm.transactional-test fails periodically with timeout" class="issue-link" data-issue-key="STORM-773"><del>STORM-773</del></a>, it's not entirely clear what the intent was. </p>

<p>Basically, my understand is that the exception passed here is the exception from the worker &#8211; and <tt>exception-cause?</tt> walks the entire exception chain checking for <tt>InterruptedException</tt> or <tt>InterruptedIOException</tt> &#8211; which may have been due to a bolt talking to an external service (e.g. <tt>SocketTimeoutException</tt> is an <tt>InterruptedIOException</tt>). </p>

<p>So, some options:</p>

<ol>
	<li>My understanding is incorrect, and this error is NOT from the bolt itself</li>
	<li><tt>exception-cause?</tt> doesn't walk the entire exception tree as I thought</li>
	<li>This behaviour is mostly intentional, but should only be applied if error itself is <tt>InterruptedException</tt> or <tt>InterruptedIOException</tt>, but not if those appear anywhere in the chain</li>
</ol>


<p>I think #2 above is the case:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">user=> (def ex (<span class="code-keyword">new</span> RuntimeException (<span class="code-keyword">new</span> InterruptedException)))
#'user/ex
(defn exception-cause?
  [klass ^Throwable t]
 (->> (iterate #(.getCause ^Throwable %) t)
       (take-<span class="code-keyword">while</span> identity)
       (some (partial instance? klass))
       <span class="code-object">boolean</span>))
#'user/exception-cause?
user=> (exception-cause? InterruptedException ex)
<span class="code-keyword">true</span>
user=>
</pre>
</div></div>

<p>So, either the exception isn't the one raised by the bolt (I'll look for some evidence to support this next), the check should only be ignoring errors that are themselves <tt>InterruptedException</tt>/<tt>InterruptedIOException</tt> but not looking elsewhere in the chain, or this was intended as just a logging line, and <tt>sucide-fn</tt> should still get invoked after logging.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chawco">chawco</a>:</i>
<p>It does appear to me that the executor's <tt>report-error-and-die</tt> is the fn passed to the bolt creation multimethod <tt>mk-threads :bolt</tt>, via <tt>executor-data</tt>, and this is what gets invoked in the <tt>async-loop</tt> for the outer catch clause against <tt>Throwable</tt> if the exception is an <tt>InterruptedIOException</tt>, which then applies the above logic. </p>

<p>I don't see how this behaviour could possibly be correct now, unless there's some other mechanism for causing workers to exit &#8211; any bolt that throws an unhandled exception that has <tt>InterruptedIOException</tt> in the chain will invoke <tt>:report-error-and-die</tt>, which then happily logs and does nothing, leaving the process otherwise running.</p>

<p>I'm fairly certain there is at least SOME bug here, so now the question is:</p>

<ol>
	<li>Do we just log and always suicide? <a href="https://issues.apache.org/jira/browse/STORM-772" title="Tasts fail periodically with InterruptedException or InterruptedIOException" class="issue-link" data-issue-key="STORM-772"><del>STORM-772</del></a> and <a href="https://issues.apache.org/jira/browse/STORM-773" title="backtype.storm.transactional-test fails periodically with timeout" class="issue-link" data-issue-key="STORM-773"><del>STORM-773</del></a> indicate that we DID actually want to ignore SOME of these exceptions.</li>
	<li>Do we just log and ignore if and only if <tt>error</tt> is ITSELF an <tt>InterruptedException</tt>/<tt>InterruptedIOException</tt>? This now seems to be the most likely intent given the discussion in those two other tickets.</li>
	<li>There's some other mechanism for making workers exit that I'm not aware &#8211; entirely possible, but I'm not sure how I'd go about finding it if that's the case.</li>
</ol>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chawco">chawco</a>:</i>
<p>Just managed to snag a thread dump of a worker I think was exhibiting this behaviour. Will take a look at it tomorrow, and attach it here.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chawco">chawco</a>:</i>
<p>Checking internally to make sure it's OK to post stacks that contain some internal information, however the dump does confirm we have the expected 24 spout threads, but only 23 bolt threads &#8211; one of them has died but not shut down the process.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chawco">chawco</a>:</i>
<p>Showing 24 spout threads as expected, but only 23 b-0 threads </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chawco">chawco</a>:</i>
<p>I attached a scrubbed thread dump showing the issue.</p>

<p>This worker should have 24 spout threads, and 24 b-0 threads, however we can see that one of the b-0 threads has died, but left the worker running:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Sulla:Desktop chawco$ grep spout- scrubbed-thread-dump.txt | grep -v SendThread | grep -v EventThread | wc -l
      24
Sulla:Desktop chawco$ grep b-0- scrubbed-thread-dump.txt | wc -l
      23
Sulla:Desktop chawco$
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sathyafmt">sathyafmt</a>:</i>
<p>Thanks Craig ! We have two problems with 1.0.2 & your patch fixes them both.</p>

<p>1. when storm workers start & they are not able to bind to 56700 (the rmi port), they hang around and do not die. This is easy to reproduce, I started a nc -l 56700 & started the topology. With your patch, it dies & the supervisor restarts them back again.<br/>
2016-12-01 04:24:41.721 STDERR <span class="error">&#91;INFO&#93;</span> Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 56700; nested exception is: <br/>
2016-12-01 04:24:41.722 STDERR <span class="error">&#91;INFO&#93;</span>   java.net.BindException: Address already in use</p>

<p>2. the storm workers hit a SocketTimeoutException & they don't die. The log:<br/>
2016-11-30 15:21:29.004 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
java.lang.RuntimeException: org.apache.storm.kafka.FailedFetchException: java.net.SocketTimeoutException<br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:464) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:430) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>8058$fn</em><em>8071$fn</em>_8124.invoke(executor.clj:850) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_91&#93;</span><br/>
Caused by: org.apache.storm.kafka.FailedFetchException: java.net.SocketTimeoutException<br/>
at org.apache.storm.kafka.KafkaUtils.fetchMessages(KafkaUtils.java:199) ~<span class="error">&#91;stormjar.jar:1.0.0&#93;</span><br/>
at org.apache.storm.kafka.trident.TridentKafkaEmitter.fetchMessages(TridentKafkaEmitter.java:141) ~<span class="error">&#91;stormjar.jar:1.0.0&#93;</span><br/>
at org.apache.storm.kafka.trident.TridentKafkaEmitter.doEmitNewPartitionBatch(TridentKafkaEmitter.java:114) ~<span class="error">&#91;stormjar.jar:1.0.0&#93;</span><br/>
at org.apache.storm.kafka.trident.TridentKafkaEmitter.failFastEmitNewPartitionBatch(TridentKafkaEmitter.java:68) ~<span class="error">&#91;stormjar.jar:1.0.0&#93;</span><br/>
at org.apache.storm.kafka.trident.TridentKafkaEmitter.access$400(TridentKafkaEmitter.java:42) ~<span class="error">&#91;stormjar.jar:1.0.0&#93;</span><br/>
at org.apache.storm.kafka.trident.TridentKafkaEmitter$2.emitPartitionBatchNew(TridentKafkaEmitter.java:265) ~<span class="error">&#91;stormjar.jar:1.0.0&#93;</span><br/>
at org.apache.storm.kafka.trident.TridentKafkaEmitter$2.emitPartitionBatchNew(TridentKafkaEmitter.java:257) ~<span class="error">&#91;stormjar.jar:1.0.0&#93;</span><br/>
at org.apache.storm.trident.spout.PartitionedTridentSpoutExecutor$Emitter$1.init(PartitionedTridentSpoutExecutor.java:125) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.trident.topology.state.RotatingTransactionalState.getState(RotatingTransactionalState.java:83) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.trident.topology.state.RotatingTransactionalState.getStateOrCreate(RotatingTransactionalState.java:110) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.trident.spout.PartitionedTridentSpoutExecutor$Emitter.emitBatch(PartitionedTridentSpoutExecutor.java:121) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:82) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:383) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>8058$tuple_action_fn</em>_8060.invoke(executor.clj:731) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.daemon.executor$mk_task_receiver$fn__7979.invoke(executor.clj:464) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.disruptor$clojure_handler$reify__7492.onEvent(disruptor.clj:40) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:451) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
... 6 more<br/>
2016-11-30 15:21:29.028 o.a.s.d.executor <span class="error">&#91;INFO&#93;</span> Got interrupted excpetion shutting thread down...<br/>
2016-11-30 16:20:59.013 s.d.C.DBPoolDataSource-pool-ds <span class="error">&#91;INFO&#93;</span> DBPoolDataSource-pool-ds: Destroyed connection<br/>
2016-11-30 16:21:14.014 s.d.C.DBPoolDataSource-pool-ds <span class="error">&#91;INFO&#93;</span> DBPoolDataSource-pool-ds: Destroyed connection</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Miss porting back to 1.1.x-branch. Will do.</p>
