### ISSUE TITLE
[STORM-2207] Kafka Spout NullPointerException during ack

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5989]
<p>This occurs on startup of the topology.  There should be some null check safeguards, but i'm not sure what's causing it to occur in the first place...my guess is  the topic partition is not found in the ack map.</p>

<p>2016-11-17 23:11:05.366 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Async loop died!<br/>
java.lang.RuntimeException: java.lang.NullPointerException<br/>
    at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:464) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:430) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.utils.DisruptorQueue.consumeBatch(DisruptorQueue.java:420) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.disruptor$consume_batch.invoke(disruptor.clj:69) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.daemon.executor$fn_<em>7990$fn</em><em>8005$fn</em>_8036.invoke(executor.clj:628) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
    at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_91&#93;</span><br/>
Caused by: java.lang.NullPointerException<br/>
    at org.apache.storm.kafka.spout.KafkaSpout.ack(KafkaSpout.java:316) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at org.apache.storm.daemon.executor$ack_spout_msg.invoke(executor.clj:448) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.daemon.executor$fn_<em>7990$tuple_action_fn</em>_7996.invoke(executor.clj:536) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.daemon.executor$mk_task_receiver$fn__7979.invoke(executor.clj:464) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.disruptor$clojure_handler$reify__7492.onEvent(disruptor.clj:40) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:451) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    ... 7 more<br/>
2016-11-17 23:11:05.379 o.a.s.d.executor <span class="error">&#91;ERROR&#93;</span> <br/>
java.lang.RuntimeException: java.lang.NullPointerException<br/>
    at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:464) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:430) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.utils.DisruptorQueue.consumeBatch(DisruptorQueue.java:420) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.disruptor$consume_batch.invoke(disruptor.clj:69) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.daemon.executor$fn_<em>7990$fn</em><em>8005$fn</em>_8036.invoke(executor.clj:628) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
    at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_91&#93;</span><br/>
Caused by: java.lang.NullPointerException<br/>
    at org.apache.storm.kafka.spout.KafkaSpout.ack(KafkaSpout.java:316) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at org.apache.storm.daemon.executor$ack_spout_msg.invoke(executor.clj:448) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.daemon.executor$fn_<em>7990$tuple_action_fn</em>_7996.invoke(executor.clj:536) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.daemon.executor$mk_task_receiver$fn__7979.invoke(executor.clj:464) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.disruptor$clojure_handler$reify__7492.onEvent(disruptor.clj:40) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:451) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    ... 7 more<br/>
2016-11-17 23:11:05.473 o.a.s.util <span class="error">&#91;ERROR&#93;</span> Halting process: ("Worker died")<br/>
java.lang.RuntimeException: ("Worker died")<br/>
    at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at clojure.lang.RestFn.invoke(RestFn.java:423) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
    at org.apache.storm.daemon.worker$fn_<em>8663$fn</em>_8664.invoke(worker.clj:765) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.daemon.executor$mk_executor_data$fn_<em>7875$fn</em>_7876.invoke(executor.clj:274) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:494) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
    at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
    at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_91&#93;</span></p>

<p>The method and line number in question below:</p>

<p>@Override<br/>
    public void ack(Object messageId) {<br/>
final KafkaSpoutMessageId msgId = (KafkaSpoutMessageId) messageId;<br/>
if (!consumerAutoCommitMode) </p>
{  // Only need to keep track of acked tuples if commits are not done automatically
    acked.get(msgId.getTopicPartition()).add(msgId);
}
<p>emitted.remove(msgId);<br/>
}</p>

---
<details><summary><i>Originally reported by <a title="Nick Cuneo" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=logikz">logikz</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2207" target="_blank">Kafka Spout NullPointerException during ack</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2017-08-24T06:44:35+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=logikz">logikz</a>:</i>
<p>I believe this is a race condition between acking a message as soon as the topology comes online versus initialization of the kafka spout to insert the topic partitions in the ack topic map.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iryoung">iryoung</a>:</i>
<p>I also experienced the same error! And my topology in production failed to start because of many errors like this.<br/>
So I tested using small sets such as 2 worker or 5 spout, and it failed as well.<br/>
(FYI - The topic has almost hundred parittions)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wangliang938">wangliang938</a>:</i>
<p>strom1.0.2 ,"enable.auto.commit" default is false,you can change it .then retry.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=f1sherox">f1sherox</a>:</i>
<p>Fixed in <a href="https://issues.apache.org/jira/browse/STORM-2104" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-2104</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=qiozas">qiozas</a>:</i>
<p>This is still a problem in 1.0.3 release (try to migrate from 0.9.6).<br/>
This problem occurs when Kafka Coordinator decides to rebalance for some reason. Then KafkaSpout throw NPE because does not know what to do in acked Map for the incoming acked tuple.<br/>
<a href="https://issues.apache.org/jira/browse/STORM-2104" title="New Kafka spout crashes if partitions are reassigned while tuples are in-flight" class="issue-link" data-issue-key="STORM-2104"><del>STORM-2104</del></a> seems to handle that problem, but it is only available for 2.x and 1.1.x branches.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhiwei">zhiwei</a>:</i>
<p>This is still a problem in 0.10 release </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>This appears to be a duplicate of <a href="https://issues.apache.org/jira/browse/STORM-2104" title="New Kafka spout crashes if partitions are reassigned while tuples are in-flight" class="issue-link" data-issue-key="STORM-2104"><del>STORM-2104</del></a> as <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=f1sherox" class="user-hover" rel="f1sherox">Igor Kuzmenko</a> mentioned. The bug should be fixed in the fix versions listed there. Please let us know if the bug is still present in those versions or later.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wangliang938" class="user-hover" rel="wangliang938">wangliang</a> mentioned a temporary workaround. It is a fine fix in some cases, but please note that this workaround can lead to message loss, so you should prefer upgrading to a Storm version where this is fixed.</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2104">STORM-2104</a>]</i>
