### ISSUE TITLE
[STORM-2232] nimbus crash!  

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6014]
<p>storm cluster version:   apache-storm-1.0.2</p>

<p>2016-12-02 09:21:11.812 o.a.s.t.s.THsHaServer <span class="error">&#91;ERROR&#93;</span> run() exiting due to uncaught error<br/>
java.lang.OutOfMemoryError: Java heap space<br/>
at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)<br/>
at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)<br/>
at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.read(AbstractNonblockingServer.java:371)<br/>
at org.apache.storm.thrift.server.AbstractNonblockingServer$AbstractSelectThread.handleRead(AbstractNonblockingServer.java:203)<br/>
at org.apache.storm.thrift.server.TNonblockingServer$SelectAcceptThread.select(TNonblockingServer.java:203)<br/>
at org.apache.storm.thrift.server.TNonblockingServer$SelectAcceptThread.run(TNonblockingServer.java:154)</p>

<p>java-version : 1.8.0_60<br/>
niumbs info:<br/>
-Xmx2048m-XX:MetaspaceSize=96m-XX:MaxMetaspaceSize=256m-Xloggc:/tmp/nimbus.gc.log-XX:+PrintGCTimeStamps-XX:+PrintGCDetails-XX:+PrintGCDateStamps-XX:+HeapDumpOnOutOfMemoryError-XX:HeapDumpPath=/tmp/nimbus.heapdump-Dlogfile.name=nimbus.log-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector-Dlog4j.configurationFile=/home/data/soft/apache-storm-1.0.2/log4j2/cluster.xmlorg.apache.storm.daemon.nimbus</p>

---
<details><summary><i>Originally reported by <a title="gehaijiang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gehaijiang">gehaijiang</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2232" target="_blank">nimbus crash!  </a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:53+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
