### ISSUE TITLE
[STORM-2265] Incorrectly Serialized JSON in TransactionalState causes Worker to Die

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6047]
<p>TransactionalState uses JSONValue to serialize / deserialize objects. However, the object GlobalPartitionInformation is incorrectly serialized by default, causing the exception bellow. To get around this problem, GlobalPartitionInformation must implement JSONAware.</p>

<p>2016-12-23 14:37:26.980 o.a.s.e.e.ReportError Thread-21-$spoutcoord-spout-spout1-executor<span class="error">&#91;2, 2&#93;</span> <span class="error">&#91;ERROR&#93;</span> Error<br/>
java.lang.RuntimeException: java.lang.RuntimeException: Unexpected character (G) at position 1.<br/>
at org.apache.storm.utils.Utils$6.run(Utils.java:2190) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_112&#93;</span><br/>
Caused by: java.lang.RuntimeException: Unexpected character (G) at position 1.<br/>
at org.apache.storm.trident.topology.state.TransactionalState.getData(TransactionalState.java:174) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.trident.topology.state.RotatingTransactionalState.sync(RotatingTransactionalState.java:165) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.trident.topology.state.RotatingTransactionalState.<init>(RotatingTransactionalState.java:46) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.trident.spout.TridentSpoutCoordinator.prepare(TridentSpoutCoordinator.java:57) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.topology.BasicBoltExecutor.prepare(BasicBoltExecutor.java:43) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.executor.bolt.BoltExecutor.init(BoltExecutor.java:84) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.executor.bolt.BoltExecutor.call(BoltExecutor.java:93) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.executor.bolt.BoltExecutor.call(BoltExecutor.java:45) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.utils.Utils$6.run(Utils.java:2179) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
... 1 more<br/>
Caused by: org.apache.storm.shade.org.json.simple.parser.ParseException<br/>
at org.apache.storm.shade.org.json.simple.parser.Yylex.yylex(Unknown Source) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.shade.org.json.simple.parser.JSONParser.nextToken(Unknown Source) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.shade.org.json.simple.parser.JSONParser.parse(Unknown Source) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.shade.org.json.simple.parser.JSONParser.parse(Unknown Source) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.shade.org.json.simple.parser.JSONParser.parse(Unknown Source) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.shade.org.json.simple.JSONValue.parseWithException(Unknown Source) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.trident.topology.state.TransactionalState.getData(TransactionalState.java:167) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.trident.topology.state.RotatingTransactionalState.sync(RotatingTransactionalState.java:165) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.trident.topology.state.RotatingTransactionalState.<init>(RotatingTransactionalState.java:46) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.trident.spout.TridentSpoutCoordinator.prepare(TridentSpoutCoordinator.java:57) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.topology.BasicBoltExecutor.prepare(BasicBoltExecutor.java:43) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.executor.bolt.BoltExecutor.init(BoltExecutor.java:84) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.executor.bolt.BoltExecutor.call(BoltExecutor.java:93) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.executor.bolt.BoltExecutor.call(BoltExecutor.java:45) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.utils.Utils$6.run(Utils.java:2179) ~<span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
... 1 more<br/>
2016-12-23 14:37:26.987 o.a.s.u.Utils Thread-21-$spoutcoord-spout-spout1-executor<span class="error">&#91;2, 2&#93;</span> <span class="error">&#91;ERROR&#93;</span> Halting process: Worker died<br/>
java.lang.RuntimeException: Halting process: Worker died<br/>
at org.apache.storm.utils.Utils.exitProcess(Utils.java:1792) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.utils.Utils$4.run(Utils.java:1800) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at org.apache.storm.executor.error.ReportErrorAndDie.uncaughtException(ReportErrorAndDie.java:45) <span class="error">&#91;storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
at java.lang.Thread.dispatchUncaughtException(Thread.java:1956) <span class="error">&#91;?:1.8.0_112&#93;</span><br/>
2016-12-23 14:37:26.987 o.a.s.d.w.Worker Thread-38 <span class="error">&#91;INFO&#93;</span> Shutting down worker tkst-consumer-4-1482532570 556a1e7b-49f7-4dc2-a936-d17e5e4ba9de 6700<br/>
2016-12-23 14:37:26.988 o.a.s.d.w.Worker Thread-38 <span class="error">&#91;INFO&#93;</span> Terminating messaging context</p>

---
<details><summary><i>Originally reported by <a title="Hugo Da Cruz Louro" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmclouro">hmclouro</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2265" target="_blank">Incorrectly Serialized JSON in TransactionalState causes Worker to Die</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Hugo Da Cruz Louro" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmclouro">hmclouro</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2017-08-30T06:45:54+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>I just change the status to OPEN since there's no actual progress at all. Maybe we could close this for now if we don't have an idea for the fix.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Closing as we don't have any better approaches for now.</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2264">STORM-2264</a>]</i>
