### ISSUE TITLE
[STORM-2281] Running Multiple Kafka Spouts (Trident) Throws Illegal State Exception

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6063]
<p>For Kafka Spout New Consumer in Trident, if we increase the spout parallelism more than one then we can see that the below error happens</p>

<p>It is reproducible most of the times, it it does not then just kill and restart topology.  (if spout parallelism is 1 there is no problem, it only happens with multiple spouts)</p>

<p>Steps to Reproduce:<br/>
1. Create a Spout Only Trident Topology (or read write topology)<br/>
2. Create a topic with multiple partition (2 or more) <br/>
3. Pump some data and try to read with parallelism of 2 or more</p>

<p>No current assignment for partition input-1 <br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:464) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span> <br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:430) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span> <br/>
at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span> <br/>
at org.apache.storm.daemon.executor$fn_<em>8058$fn</em><em>8071$fn</em>_8124.invoke(executor.clj:850) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span> <br/>
at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span> <br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span> <br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_77&#93;</span> <br/>
Caused by: java.lang.IllegalStateException: No current assignment for partition input-1 <br/>
at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignedState(SubscriptionState.java:231) ~<span class="error">&#91;kafka-clients-0.10.0.0.jar:?&#93;</span> <br/>
at org.apache.kafka.clients.consumer.internals.SubscriptionState.seek(SubscriptionState.java:256) ~<span class="error">&#91;kafka-clients-0.10.0.0.jar:?&#93;</span> <br/>
at org.apache.kafka.clients.consumer.KafkaConsumer.seek(KafkaConsumer.java:1134) ~<span class="error">&#91;kafka-clients-0.10.0.0.jar:?&#93;</span> <br/>
at org.apache.storm.kafka.spout.trident.KafkaTridentSpoutEmitter.seek(KafkaTridentSpoutEmitter.java:139) ~<span class="error">&#91;storm-kafka-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span> <br/>
at org.apache.storm.kafka.spout.trident.KafkaTridentSpoutEmitter.emitPartitionBatch(KafkaTridentSpoutEmitter.java:88) ~<span class="error">&#91;storm-kafka-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span> <br/>
at org.apache.storm.kafka.spout.trident.KafkaTridentSpoutEmitter.emitPartitionBatch(KafkaTridentSpoutEmitter.java:47) ~<span class="error">&#91;storm-kafka-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span> <br/>
at org.apache.storm.trident.spout.OpaquePartitionedTridentSpoutExecutor$Emitter.emitBatch(OpaquePartitionedTridentSpoutExecutor.java:128) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span> <br/>
at org.apache.storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:82) ~<span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Narendra Bidari" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=supermonk">supermonk</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2281" target="_blank">Running Multiple Kafka Spouts (Trident) Throws Illegal State Exception</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Hugo Da Cruz Louro" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmclouro">hmclouro</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-02-08T02:15:03+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Trident implementation of storm-kafka-client is only applied to 1.x and master branch, and none of version line is released yet.</p>

<p>Did you build your own Storm with 1.x or master branch? If then please change Affects Version/s accordingly.</p>

<p>And could you reproduce this with Storm 1.0.2 or Storm 1.x branch? I'm not sure storm-kafka-client works with Storm 0.x version line.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=supermonk">supermonk</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> : Yes, We build our own branch. </p>

<p>I have updated the ticket with the error on storm 1.0 and latest storm-kaka-client.  The error still appears. It has more to do with Kafka Consumer Subscription</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha">sriharsha</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=supermonk" class="user-hover" rel="supermonk">Narendra Bidari</a> which version of kafka-clients are you using.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=supermonk">supermonk</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sriharsha" class="user-hover" rel="sriharsha">Harsha</a> : We are using 0.10.0.0</p>

<p><dependency><br/>
			<groupId>org.apache.kafka</groupId><br/>
			<artifactId>kafka-clients</artifactId><br/>
			<version>0.10.0.0</version><br/>
		</dependency></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmclouro">hmclouro</a>:</i>
<p>Quick update: I was able to reproduce this on my local machine.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmclouro" class="user-hover" rel="hmclouro">Hugo Da Cruz Louro</a>, I merged into master and 1.x branch.</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-1856%20label%3Aepic">STORM-1856</a>]</i>
