### ISSUE TITLE
[STORM-2290] Upgrading zookeeper to 3.4.9 for stability

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6072]
<p>We should upgrade zookeeper to 3.4.9 as it brings in a lot of stability improvements (<a href="http://zookeeper.apache.org/releases.html" class="external-link" target="_blank" rel="nofollow noopener">http://zookeeper.apache.org/releases.html</a>) and storm is still using 3.4.6 (<a href="https://github.com/apache/storm/blob/master/pom.xml" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/pom.xml</a>)</p>

<p>One serious issue affecting zookeeper 3.4.6 is <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1506" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-1506</a> which prohibits zookeeper from getting a quorum and hence affects storm's stability as well.</p>

---
<details><summary><i>Originally reported by <a title="Sachin Goyal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sachingoyal">sachingoyal</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2290" target="_blank">Upgrading zookeeper to 3.4.9 for stability</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:01+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amilbourne">amilbourne</a>:</i>
<p>We run a storm cluster (v.1.0.2) on AWS and have 3 Zookeepers supporting it.  Because AWS sometimes terminates VMs, we sometimes lose a Zookeeper instance.  When this happens, the hostname cannot be resolved for that zookeeper instance as AWS has taken the VM away.  We noticed that in this case storm fails to connect to zookeeper – even though there are still 2 Zookeeper instances running.  It fails with an exception something like:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.net.UnknownHostException: zookeeper3
  at java.net.InetAddress.getAllByName0(InetAddress.java:1280) 
  at java.net.InetAddress.getAllByName(InetAddress.java:1192) 
  at java.net.InetAddress.getAllByName(InetAddress.java:1126) 
  at org.apache.storm.shade.org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61) 
  at org.apache.storm.shade.org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) 
  at org.apache.storm.shade.org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29) 
  at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:150) 
  at org.apache.storm.shade.org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94) 
  at org.apache.storm.shade.org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55) 
  at org.apache.storm.shade.org.apache.curator.ConnectionState.reset(ConnectionState.java:218) 
  at org.apache.storm.shade.org.apache.curator.ConnectionState.start(ConnectionState.java:103) 
  at org.apache.storm.shade.org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:190) 
  at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:259) 
  at org.apache.storm.zookeeper$mk_client.doInvoke(zookeeper.clj:86) 
  at clojure.lang.RestFn.invoke(RestFn.java:494)
  at org.apache.storm.cluster_state.zookeeper_state_factory$_mkState.invoke(zookeeper_state_factory.clj:28) 
  at org.apache.storm.cluster_state.zookeeper_state_factory.mkState(Unknown Source) 
  <SNIP REST OF STACKTRACE>
</pre>
</div></div>

<p>Having done some research it looks like this error is caused by a bug in the Zookeeper client library.  There is an issue for it here:<br/>
<a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1576" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-1576</a><br/>
This issue has been resolved in the version 3.5.x branch of Zookeeper.  However, after 2.5 years and 3 releases the 3.5.x branch of Zookeeper is still in Alpha <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/>.</p>

<p>Despite the fact that it is in alpha, there is a branch of Curator (v.3.x.x) that uses it, but Storm uses Curator version 2.x.x – possibly because it doesn’t rely on alpha code.  So the bug is still unpatched in Storm.</p>

<p>I realise that an upgrade to alpha code may be too much of a risk, but this problem is a serious issue for those running Storm on AWS (and presumably other cloud providers) - so perhaps it may be worth considering?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1576" title="Zookeeper cluster - failed to connect to cluster if one of the provided IPs causes java.net.UnknownHostException" class="issue-link" data-issue-key="ZOOKEEPER-1576"><del>ZOOKEEPER-1576</del></a> fixed client side so worth to consider version bump, but <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1506" title="Re-try DNS hostname -> IP resolution if node connection fails" class="issue-link" data-issue-key="ZOOKEEPER-1506"><del>ZOOKEEPER-1506</del></a> fixed server side so might not need to bump if ZK 3.4.9 server is compatible with ZK 3.4.6 client. </p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sachingoyal" class="user-hover" rel="sachingoyal">Sachin Goyal</a><br/>
Could you only replace your ZK server to 3.4.9 and reproduce?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amilbourne">amilbourne</a>:</i>
<p>We are currently using Zookeeper server 3.4.8, which includes the <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1506" title="Re-try DNS hostname -> IP resolution if node connection fails" class="issue-link" data-issue-key="ZOOKEEPER-1506"><del>ZOOKEEPER-1506</del></a> fix.  However, the bug I am describing cannot be fixed on the server side as it happens when the server (and the host it runs on) are down.  The client fails to deal properly with the UnknownHostException and does not fall back to using the other Zookeeper servers in the cluster.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amilbourne" class="user-hover" rel="amilbourne">Anthony Milbourne</a><br/>
Yes that case requires update of Zookeeper client. Not 3.4.9 but equal or upper than 3.5.0, and it would be better to file another JIRA issue for that since it's just another case.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amilbourne">amilbourne</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a><br/>
Thanks, I have created a new issue (<a href="https://issues.apache.org/jira/browse/STORM-2415" title="Storm fails to properly handle Zookeeper hosts going down" class="issue-link" data-issue-key="STORM-2415"><del>STORM-2415</del></a>) for the <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1506" title="Re-try DNS hostname -> IP resolution if node connection fails" class="issue-link" data-issue-key="ZOOKEEPER-1506"><del>ZOOKEEPER-1506</del></a> related problems.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
