### ISSUE TITLE
[STORM-2314] Workers is dead or locked when netty connection is timeout

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6096]
<p>Storm is running ,but some workers can not emit data when throw the following exception,  the exception offen occurs in heigh pressure</p>

<p>2017-01-22 18:23:25.137 s.k.CollectorZkCoordinator <span class="error">&#91;INFO&#93;</span> Task <span class="error">&#91;3/3&#93;</span> Finished refreshing<br/>
2017-01-22 18:24:08.170 o.a.s.m.n.StormClientHandler <span class="error">&#91;INFO&#93;</span> Connection to xxxxxxx/192.168.175.25:6703 failed:<br/>
java.io.IOException: Connection timed out<br/>
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~<span class="error">&#91;?:1.7.0_80&#93;</span><br/>
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~<span class="error">&#91;?:1.7.0_80&#93;</span><br/>
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~<span class="error">&#91;?:1.7.0_80&#93;</span><br/>
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~<span class="error">&#91;?:1.7.0_80&#93;</span><br/>
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384) ~<span class="error">&#91;?:1.7.0_80&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at org.apache.storm.shade.org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) <span class="error">&#91;storm-core-1.0.2.jar:1.0.2&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_80&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_80&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_80&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="SeaAndHill" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=junmin.li">junmin.li</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2314" target="_blank">Workers is dead or locked when netty connection is timeout</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:04+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
