### ISSUE TITLE
[STORM-2364] Ensure kafka-monitor jar is included in classpath for UI process

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6146]
<p>The kafka-monitor jar has been moved into  toollib/ and not featuring in UI process's classpath. Leading to ClassNotFoundException for KafkaOffsetLagUtil class ... seen in the ui.log</p>

---
<details><summary><i>Originally reported by <a title="Roshan Naik" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2364" target="_blank">Ensure kafka-monitor jar is included in classpath for UI process</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Roshan Naik" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:06+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik" class="user-hover" rel="roshan_naik">Roshan Naik</a></p>

<p>It's from bin/storm-kafka-monitor which correctly specifies toollib directory.<br/>
<a href="https://github.com/apache/storm/blob/1.x-branch/bin/storm-kafka-monitor" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/1.x-branch/bin/storm-kafka-monitor</a></p>

<p>Could you post ui.log, and try running bin/storm-kafka-monitor manually?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> Here you go...</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2017-02-14 08:51:13.037 o.a.s.u.TopologySpoutLag [WARN] Exception thrown <span class="code-keyword">while</span> getting lag <span class="code-keyword">for</span> spout id: kafka-spout and spout class: org.apache.storm.kafka.KafkaSpout
2017-02-14 08:51:13.037 o.a.s.u.TopologySpoutLag [WARN] Exception message:Error: Could not find or load main <span class="code-keyword">class </span>org.apache.storm.kafka.monitor.KafkaOffsetLagUtil
org.apache.storm.utils.ShellUtils$ExitCodeException: Error: Could not find or load main <span class="code-keyword">class </span>org.apache.storm.kafka.monitor.KafkaOffsetLagUtil
at org.apache.storm.utils.ShellUtils.runCommand(ShellUtils.java:230)
at org.apache.storm.utils.ShellUtils.run(ShellUtils.java:160)
at org.apache.storm.utils.ShellUtils$ShellCommandExecutor.execute(ShellUtils.java:370)
at org.apache.storm.utils.ShellUtils.execCommand(ShellUtils.java:460)
at org.apache.storm.utils.ShellUtils.execCommand(ShellUtils.java:443)
at org.apache.storm.utils.TopologySpoutLag.getLagResultForKafka(TopologySpoutLag.java:153)
at org.apache.storm.utils.TopologySpoutLag.getLagResultForOldKafkaSpout(TopologySpoutLag.java:183)
at org.apache.storm.utils.TopologySpoutLag.lag(TopologySpoutLag.java:59)
at org.apache.storm.ui.core$topology_lag.invoke(core.clj:727)
at org.apache.storm.ui.core$fn__10090.invoke(core.clj:1073)
at org.apache.storm.shade.compojure.core$make_route$fn__1792.invoke(core.clj:93)
at org.apache.storm.shade.compojure.core$if_route$fn__1780.invoke(core.clj:39)
at org.apache.storm.shade.compojure.core$if_method$fn__1773.invoke(core.clj:24)
at org.apache.storm.shade.compojure.core$routing$fn__1798.invoke(core.clj:106)
at clojure.core$some.invoke(core.clj:2570)
at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:106)
at clojure.lang.RestFn.applyTo(RestFn.java:139)
at clojure.core$apply.invoke(core.clj:632)
at org.apache.storm.shade.compojure.core$routes$fn__1802.invoke(core.clj:111)
at org.apache.storm.shade.ring.middleware.cors$wrap_cors$fn__9443.invoke(cors.clj:149)
at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__9390.invoke(json.clj:56)
at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__2954.invoke(multipart_params.clj:103)
at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__8948.invoke(reload.clj:22)
at org.apache.storm.ui.helpers$requests_middleware$fn__3197.invoke(helpers.clj:46)
at org.apache.storm.ui.core$catch_errors$fn__10265.invoke(core.clj:1336)
at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__2885.invoke(keyword_params.clj:27)
at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__2925.invoke(nested_params.clj:65)
at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__2856.invoke(params.clj:55)
at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__2954.invoke(multipart_params.clj:103)
at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__3140.invoke(flash.clj:14)
at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__3128.invoke(session.clj:43)
at org.apache.storm.shade.ring.middleware.cookies$wrap_cookies$fn__3056.invoke(cookies.clj:160)
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik" class="user-hover" rel="roshan_naik">Roshan Naik</a><br/>
UI process just runs bin/storm-kafka-monitor instead of using kafka-monitor jar directly because of avoiding Kafka dependencies. The error message is from bin/storm-kafka-monitor, so I asked you to run bin/storm-kafka-monitor manually.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=qianmoq">qianmoq</a>:</i>
<p>i'm run ./bin/storm-kafka-monitor, but stop this page:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
log4j:WARN No appenders could be found <span class="code-keyword">for</span> logger (org.apache.kafka.shaded.clients.consumer.ConsumerConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http:<span class="code-comment">//logging.apache.org/log4j/1.2/faq.html#noconfig <span class="code-keyword">for</span> more info.
</span>








Unable to get offset lags <span class="code-keyword">for</span> kafka. Reason: org.apache.kafka.shaded.common.errors.TimeoutException: Timeout expired <span class="code-keyword">while</span> fetching topic metadata
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=qianmoq">qianmoq</a>:</i>
<p>�replace storm-kafka-monitor to your kafka version, solve the problem!!!</p>

<p>egg: <br/>
your kafka version:  0.10.0.0<br/>
replace storm-kafka-monitor version to 1.1.0<br/>
rm source toollib/storm-kafka-monitor-*.jar or rename this</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
