### ISSUE TITLE
[STORM-2379] [storm-elasticsearch] switch ES client to Java REST API

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6161]
<p>following documentation:<br/>
<a href="https://storm.apache.org/releases/1.0.1/storm-elasticsearch.html" class="external-link" target="_blank" rel="nofollow noopener">https://storm.apache.org/releases/1.0.1/storm-elasticsearch.html</a></p>

<p><a href="https://github.com/apache/storm/blob/master/external/storm-elasticsearch/pom.xml#L40" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/external/storm-elasticsearch/pom.xml#L40</a></p>

<p>this causes errors while writing to elastic 5.x</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NoClassDefFoundError: org/elasticsearch/common/base/Preconditions
	at org.apache.storm.elasticsearch.common.EsConfig.<init>(EsConfig.java:62) ~[storm-elasticsearch-1.0.2.jar:1.0.2]
	at org.apache.storm.elasticsearch.common.EsConfig.<init>(EsConfig.java:49) ~[storm-elasticsearch-1.0.2.jar:1.0.2]

Caused by: java.lang.ClassNotFoundException: org.elasticsearch.common.base.Preconditions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_112]
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:424) ~[?:1.8.0_112]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_112]
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:357) ~[?:1.8.0_112]

261538 [elasticsearch[Ringleader][<span class="code-keyword">generic</span>][T#2]] INFO  o.e.c.transport - [Ringleader] failed to get node info <span class="code-keyword">for</span> [#transport#-1][svaddi][inet[localhost/127.0.0.1:9200]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[localhost/127.0.0.1:9200]][cluster:monitor/nodes/info] request_id [26] timed out after [5005ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529) ~[elasticsearch-1.6.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_112]
</pre>
</div></div>

<p>elastic logs:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">[2017-02-23T15:47:04,487][WARN ][o.e.t.n.Netty4Transport  ] [Qt9qlNV] exception caught on transport layer [[id: 0x8f15e875, L:/127.0.0.1:9300 - R:/127.0.0.1:52031]], closing connection
java.lang.IllegalStateException: Received message from unsupported version: [1.0.0] minimal compatible version is: [5.0.0]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1199) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[transport-netty4-5.0.0.jar:5.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_121]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Sree Vaddi" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sreevaddi">sreevaddi</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2379" target="_blank">[storm-elasticsearch] switch ES client to Java REST API</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Heather McCartney" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmcc">hmcc</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-06-29T16:21:02+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmcc">hmcc</a>:</i>
<p>I've done some work on this over at <a href="https://github.com/hmcc/storm/tree/STORM-2379" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/hmcc/storm/tree/STORM-2379</a>. I've used the new Elasticsearch Java REST client so that we can (hopefully) support ES 2 and ES 5 simultaneously.</p>

<p>However, I'm wondering how best to test it. The existing integration tests use the old Java client to create an Elasticsearch node during test setup. However, Elasticsearch dropped support for running embedded nodes in this way in ES 5, and in any case, I think it would be better if we could run tests against all major versions of Elasticsearch in a single build.</p>

<p>I can't find anything "official" that allows us to do this. The elasticsearch-maven-plugin only supports launching a single Elasticsearch version, as does EsIntegTestCase.</p>

<p>However, there is an interesting blog post by someone at Elastic describing how to install and start Elasticsearch for testing using Maven Ant tasks: <a href="http://david.pilato.fr/blog/2016/10/18/elasticsearch-real-integration-tests-updated-for-ga/" class="external-link" target="_blank" rel="nofollow noopener">http://david.pilato.fr/blog/2016/10/18/elasticsearch-real-integration-tests-updated-for-ga/</a>. I think we could adapt this to start up multiple versions of Elasticsearch (on different ports) and then connect to these for testing using the REST client.</p>

<p>What do you think?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sreevaddi">sreevaddi</a>:</i>
<p>Last week, I was at elasticon and I had a chance to talk with James Baiera, who heads the elastic-hadoop.<br/>
Details at, <a href="https://discuss.elastic.co/t/storm-1-0-x-elastic-5-0-x-integration-issue/76337" class="external-link" target="_blank" rel="nofollow noopener">https://discuss.elastic.co/t/storm-1-0-x-elastic-5-0-x-integration-issue/76337</a>.</p>

<p>From other talks that I attended and talking to elastic.co employees, my understanding is that elastic.co, itself is pushing to use java REST client more over the Java Client.</p>

<p>This falls in line with our mind set here on this topic.<br/>
And REST client supports multiple versions of elastic, too.</p>

<p>How about using dockers for integration testing against multiple versions of elastic.<br/>
<a href="https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html" class="external-link" target="_blank" rel="nofollow noopener">https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html</a></p>

<p>java rest client:<br/>
<a href="https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/index.html" class="external-link" target="_blank" rel="nofollow noopener">https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/index.html</a></p>

<p>may be use this, docker-maven-plugin: </p>
{not sure, how reliable this is}
<p><a href="https://dmp.fabric8.io/" class="external-link" target="_blank" rel="nofollow noopener">https://dmp.fabric8.io/</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hmcc">hmcc</a>:</i>
<p>I hadn't seen the Docker Maven plugin, very nice!</p>

<p>My only concern is that that makes Docker an external dependency; anyone who wants to run the integration tests (including Travis) would have to have it installed already or the tests would fail. I'm new to Storm development so I'll ask on the mailing list to find out how much of a problem that is.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Also applied to 1.x-branch with some modification to ensure compatibility with JDK 7.</p>
