### ISSUE TITLE
[STORM-2400] Intermittent failure in nimbus because of errors from LeaderLatch#getLeader()

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6182]
<p>This issue is reported to Curator with <a href="https://issues.apache.org/jira/browse/CURATOR-358" title="Receiving KeeperException with NoNode when LeaderLatch#getLeader()" class="issue-link" data-issue-key="CURATOR-358"><del>CURATOR-358</del></a>. </p>

<p>org.apache.curator.framework.recipes.leader.LeaderLatch#getLeader() throws KeeperException with Code#NONODE intermittently as mentioned in the stack trace below. It may be possible participant's ephemeral ZK node is removed because its connection/session is closed.</p>

<p>You can see the below code at <a href="https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java#L451" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java#L451</a></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">public</span> Participant getLeader() <span class="code-keyword">throws</span> Exception
{ 
  Collection<<span class="code-object">String</span>> participantNodes = LockInternals.getParticipantNodes(client, latchPath, LOCK_NAME, sorter); 
  <span class="code-keyword">return</span> LeaderSelector.getLeader(client, participantNodes); 
}
</pre>
</div></div>

<p>I guess it hits a race condition where a participant node is retrieved but when it invokes LeaderSelector#getLeader() it would have been removed because of session timeout and it throws KeeperException with NoNode code. It does not retry as the RetryLoop retries only for connection/session timeouts. But in this case, NoNode should have been retried. I could not find any APIs on CuratorClient to configure the kind of KeeperException codes to be retried. It may be good to have a way to take what kind of errors should be retried in org.apache.curator.framework.CuratorFrameworkFactory.Builder APIs.<br/>
Intermittent Exception found with the stack trace:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2016-11-15 06:09:33.954 o.a.s.d.nimbus [ERROR] Error when processing event
org.apache.storm.shade.org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /storm/leader-lock/_c_97c09eed-5bba-4ac8-a05f-abdc4e8e95cf-latch-0000000002
at org.apache.storm.shade.org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
at org.apache.storm.shade.org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
at org.apache.storm.shade.org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:304)
at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:293)
at org.apache.storm.shade.org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:290)
at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:281)
at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:42)
at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderSelector.participantForPath(LeaderSelector.java:375)
at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderSelector.getLeader(LeaderSelector.java:346)
at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch.getLeader(LeaderLatch.java:454)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Satish Duggana" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2400" target="_blank">Intermittent failure in nimbus because of errors from LeaderLatch#getLeader()</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Satish Duggana" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-03-09T05:23:57+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana" class="user-hover" rel="satish.duggana">Satish Duggana</a><br/>
I think <a href="https://issues.apache.org/jira/browse/CURATOR-358" title="Receiving KeeperException with NoNode when LeaderLatch#getLeader()" class="issue-link" data-issue-key="CURATOR-358"><del>CURATOR-358</del></a> includes how Storm is affected. That means, we would be better to describe it to issue's description as well to help tracking.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana" class="user-hover" rel="satish.duggana">Satish Duggana</a>, I merged into master and 1.x branch.</p>
