### ISSUE TITLE
[STORM-2415] Storm fails to properly handle Zookeeper hosts going down

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6197]
<p>We run a storm cluster (v.1.0.3) on AWS and have 3 Zookeepers supporting it. Because AWS sometimes terminates VMs, we sometimes lose a Zookeeper instance. When this happens, the hostname cannot be resolved for that zookeeper instance as AWS has taken the VM away. We noticed that in this case storm fails to connect to zookeeper – even though there are still 2 Zookeeper instances running. It fails with an exception something like:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.net.UnknownHostException: zookeeper3
  at java.net.InetAddress.getAllByName0(InetAddress.java:1280) 
  at java.net.InetAddress.getAllByName(InetAddress.java:1192) 
  at java.net.InetAddress.getAllByName(InetAddress.java:1126) 
  at org.apache.storm.shade.org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61) 
  at org.apache.storm.shade.org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) 
  at org.apache.storm.shade.org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29) 
  at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:150) 
  at org.apache.storm.shade.org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94) 
  at org.apache.storm.shade.org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55) 
  at org.apache.storm.shade.org.apache.curator.ConnectionState.reset(ConnectionState.java:218) 
  at org.apache.storm.shade.org.apache.curator.ConnectionState.start(ConnectionState.java:103) 
  at org.apache.storm.shade.org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:190) 
  at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:259) 
  at org.apache.storm.zookeeper$mk_client.doInvoke(zookeeper.clj:86) 
  at clojure.lang.RestFn.invoke(RestFn.java:494)
  at org.apache.storm.cluster_state.zookeeper_state_factory$_mkState.invoke(zookeeper_state_factory.clj:28) 
  at org.apache.storm.cluster_state.zookeeper_state_factory.mkState(Unknown Source) 
  <SNIP REST OF STACKTRACE>
</pre>
</div></div>
<p>Having done some research it looks like this error is caused by a bug in the Zookeeper client library. There is an issue for it here:<br/>
<a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1576" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-1576</a><br/>
This issue has been resolved in the version 3.5.x branch of Zookeeper. However, after 2.5 years and 3 releases the 3.5.x branch of Zookeeper is still in Alpha .<br/>
Despite the fact that it is in alpha, there is a branch of Curator (v.3.x.x) that uses it, but Storm uses Curator version 2.x.x – possibly because it doesn’t rely on alpha code. So the bug is still unpatched in Storm.<br/>
I realise that an upgrade to alpha code may be too much of a risk, but this problem is a serious issue for those running Storm in a containerised or cloud environment - so perhaps it may be worth considering?</p>

---
<details><summary><i>Originally reported by <a title="Anthony Milbourne" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amilbourne">amilbourne</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2415" target="_blank">Storm fails to properly handle Zookeeper hosts going down</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:13+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amilbourne">amilbourne</a>:</i>
<p>This issue was created as a result of discussion on <a href="https://issues.apache.org/jira/browse/STORM-2290" title="Upgrading zookeeper to 3.4.9 for stability" class="issue-link" data-issue-key="STORM-2290"><del>STORM-2290</del></a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ramzi.jamal">ramzi.jamal</a>:</i>
<p>I appreciate you reporting this issue. We are facing this issue as well.</p>

<p>Our storm and zookeeper clusters are containerized and upon a restart of one of the zookeeper nodes with a new IP address, we noticed that nimbus still attempt to connect to the old ip address of that zk node.</p>

<p>We traced the issue to the zookeepr client 3.4.6 used by storm (currently shaded within the storm core jar).</p>

<p>We have seen the issue in storm 1.0.2, 1.0.3 and 1.0.6 and will be testing with 1.2.2, we expect it to fail as well as it also uses zk 3.4.6.</p>

<p>It is clearly an issue that we would appreciate help resolving this issue.  I wonder if we can consider updating the zookeeper dependency in storm to 3.4.13 which addressed that issue.</p>

<p>Many thanks</p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=antonpious@gmail.com">antonpious@gmail.com</a>:</i>
<p>This gets compounded when the topology spout also uses the same client to connect to zookeeper. So if a 3 node zookeeper is present and even if 1 node goes down, though logically the 2 node zookeeper can keep up, the spouts don't know about it leading to killing and restarting all the existing topologies.</p>

<p>Though with the new Kafka the offset management is now with Kafka the older spouts still rely on zookeeper to maintain the state for offset read.</p>

<p>If this is just a dependency change, any backward patches too is appreciated</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Storm (2.x and 1.x) was upgraded to 3.4.13 recently, but the change was rolled back due to a regression in Zookeeper. See <a href="https://issues.apache.org/jira/browse/STORM-3233" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-3233</a>. It looks like Zookeeper is currently running a 3.4.14 release vote, so once that is released we can upgrade.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ramzi.jamal" class="user-hover" rel="ramzi.jamal">Ramzi Jamal</a> Just for completeness, do you have a link to the Zookeeper issue causing this? The issue linked in the description for this issue only seems to apply to Zookeeper 3.5.x.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ramzi.jamal">ramzi.jamal</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> The main issue is related to zookeeper issue is: <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2184" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-2184</a>, which addresses that zookeeper client resolve the zk nodes at construction time and never attempt to re-resolve them later.</p>

<p>Fixed for zookeeper branch 3.4.13 through these commits PR: <a href="https://github.com/apache/zookeeper/commit/2e26c8836edc800c60b204a1d3da0285edb415d6#diff-25d902c24283ab8cfbac54dfa101ad31" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/zookeeper/commit/2e26c8836edc800c60b204a1d3da0285edb415d6#diff-25d902c24283ab8cfbac54dfa101ad31</a></p>

<p>Fixed for current zookeeper master branch (which in line for 3.5.5) through these commits: <a href="https://github.com/apache/zookeeper/commit/0a311873deb1847703c9b62716c626ce43d4ba48" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/zookeeper/commit/0a311873deb1847703c9b62716c626ce43d4ba48</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2290">STORM-2290</a>]</i>
