### ISSUE TITLE
[STORM-2418] add proper log message on metrics server fails/absent

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6200]
<p>my metrics consumer writes to opentsdb server.<br/>
when this server went down, i see the following error message in my storm jobs.<br/>
which is very misleading.<br/>
create a ticket, so we can address this in future versions better.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2017-03-16 01:22:43.648 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: java.lang.ClassCastException: java.lang.<span class="code-object">Object</span> cannot be <span class="code-keyword">cast</span> to java.lang.Iterable
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:135) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:106) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.executor$fn__5694$fn__5707$fn__5758.invoke(executor.clj:819) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.util$async_loop$fn__545.invoke(util.clj:479) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.6.0.jar:?]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassCastException: java.lang.<span class="code-object">Object</span> cannot be <span class="code-keyword">cast</span> to java.lang.Iterable
	at backtype.storm.util$get_iterator.invoke(util.clj:929) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.executor$mk_task_receiver$fn__5615.invoke(executor.clj:432) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.disruptor$clojure_handler$reify__5189.onEvent(disruptor.clj:58) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:127) ~[storm-core-0.10.0.jar:0.10.0]
	... 6 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Sree Vaddi" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sreevaddi">sreevaddi</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2418" target="_blank">add proper log message on metrics server fails/absent</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:11+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
