### ISSUE TITLE
[STORM-2429] non-string values in supervisor.scheduler.meta cause crash

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6211]
<p>The type of values in supervisor.scheduler.meta is not validated, but if one is not a string, supervisors crash during Thrift serialization with:</p>

<p>java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String<br/>
at org.apache.storm.generated.SupervisorInfo$SupervisorInfoStandardScheme.write(SupervisorInfo.java:1241)<br/>
at org.apache.storm.generated.SupervisorInfo$SupervisorInfoStandardScheme.write(SupervisorInfo.java:1049)<br/>
at org.apache.storm.generated.SupervisorInfo.write(SupervisorInfo.java:923)<br/>
at org.apache.storm.thrift.TSerializer.serialize(TSerializer.java:79)<br/>
at org.apache.storm.serialization.GzipThriftSerializationDelegate.serialize(GzipThriftSerializationDelegate.java:40)<br/>
at org.apache.storm.utils.Utils.serialize(Utils.java:210)<br/>
at org.apache.storm.cluster.StormClusterStateImpl.supervisorHeartbeat(StormClusterStateImpl.java:419)<br/>
at org.apache.storm.daemon.supervisor.timer.SupervisorHeartbeat.run(SupervisorHeartbeat.java:85)<br/>
at org.apache.storm.daemon.supervisor.Supervisor.launch(Supervisor.java:202)<br/>
at org.apache.storm.daemon.supervisor.Supervisor.launchDaemon(Supervisor.java:243)<br/>
at org.apache.storm.daemon.supervisor.Supervisor.main(Supervisor.java:362)</p>

<p>I will attach a PR with a simple fix</p>

---
<details><summary><i>Originally reported by <a title="David Judd" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=djudd1905">djudd1905</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2429" target="_blank">non-string values in supervisor.scheduler.meta cause crash</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="David Judd" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=djudd1905">djudd1905</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-04-05T01:40:44+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=djudd1905" class="user-hover" rel="djudd1905">David Judd</a>, I merged into master, 1.x, 1.0.x branches.</p>
