### ISSUE TITLE
[STORM-2456] Error when running Flux on Windows in non-elevated command prompt

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6238]
<p>Running:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">mvn compile exec:java -Dexec.args=<span class="code-quote">"--local -R /topology.yaml"</span>
</pre>
</div></div>

<p>I get the following errors.</p>

<p>It works if I run in an elevated command prompt though.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">17:22:48 [SLOT_1027] ERROR org.apache.storm.daemon.supervisor.Slot - Error when processing event
java.nio.file.FileSystemException: C:\Users\maurgi\AppData\Local\Temp\0924ce14-5d18-4da2-ab49-abfe37e59742\workers\c487e249-7225-4836-b7f0-b840f1a05732\artifacts: A required privilege is
 not held by the client.
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_121]
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_121]
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_121]
at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585) ~[?:1.8.0_121]
at java.nio.file.Files.createSymbolicLink(Files.java:1043) ~[?:1.8.0_121]
at org.apache.storm.daemon.supervisor.AdvancedFSOps.createSymlink(AdvancedFSOps.java:354) ~[storm-core-1.0.3.jar:1.0.3]
at org.apache.storm.daemon.supervisor.Container.createArtifactsLink(Container.java:383) ~[storm-core-1.0.3.jar:1.0.3]
at org.apache.storm.daemon.supervisor.Container.setup(Container.java:321) ~[storm-core-1.0.3.jar:1.0.3]
at org.apache.storm.daemon.supervisor.LocalContainerLauncher.launchContainer(LocalContainerLauncher.java:44) ~[storm-core-1.0.3.jar:1.0.3]
at org.apache.storm.daemon.supervisor.Slot.handleWaitingForBlobLocalization(Slot.java:387) ~[storm-core-1.0.3.jar:1.0.3]
at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:275) ~[storm-core-1.0.3.jar:1.0.3]
at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:741) [storm-core-1.0.3.jar:1.0.3]
17:22:48 [SLOT_1027] ERROR org.apache.storm.utils.Utils - Halting process: Error when processing an event
java.lang.RuntimeException: Halting process: Error when processing an event
at org.apache.storm.utils.Utils.exitProcess(Utils.java:1749) [storm-core-1.0.3.jar:1.0.3]
at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:774) [storm-core-1.0.3.jar:1.0.3]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Mauro Giusti" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=maurgi">maurgi</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2456" target="_blank">Error when running Flux on Windows in non-elevated command prompt</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:11+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
