### ISSUE TITLE
[STORM-2463] fix DRPCTest.testDequeueAfterTimeout test failure

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6245]
<p>Travis-ci build failure. The following is the error info:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">classname: org.apache.storm.daemon.drpc.DRPCTest / testname: testDequeueAfterTimeout

java.lang.AssertionError: <span class="code-keyword">null</span>
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.apache.storm.daemon.drpc.DRPCTest.testDequeueAfterTimeout(DRPCTest.java:129)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Xin Wang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vesense">vesense</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2463" target="_blank">fix DRPCTest.testDequeueAfterTimeout test failure</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Xin Wang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vesense">vesense</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-04-12T16:05:20+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vesense" class="user-hover" rel="vesense">Xin Wang</a>,</p>

<p>I merged this into master.</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2289">STORM-2289</a>]</i>
