### ISSUE TITLE
[STORM-2487] getting com.mongodb.MongoBulkWriteException while trying to save bulk messages using apache storm mongo

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6269]
<p>While trying to save bulk numbers of messages by using storm-mongo, we are getting below exception</p>

<p>com.mongodb.MongoBulkWriteException: Bulk write operation error on server mongoserver:27017. Write errors: [BulkWriteError{index=0, code=11000, message='E11000 duplicate key error collection: NextMDC.EMAIL index: <em>id</em> dup key: { : "22596<br/>
079-1260-44f1-b4df-a5857f48f22d" }', details={ }}].<br/>
at com.mongodb.connection.BulkWriteBatchCombiner.getError(BulkWriteBatchCombiner.java:176) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.connection.BulkWriteBatchCombiner.throwOnError(BulkWriteBatchCombiner.java:205) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.connection.BulkWriteBatchCombiner.getResult(BulkWriteBatchCombiner.java:146) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:190) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:230) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:221) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.Mongo.execute(Mongo.java:781) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.Mongo$2.execute(Mongo.java:764) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:323) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.mongodb.common.MongoDBClient.insert(MongoDBClient.java:61) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.mongodb.bolt.MongoInsertBolt.execute(MongoInsertBolt.java:85) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>7953$tuple_action_fn</em>_7955.invoke(executor.clj:728) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.daemon.executor$mk_task_receiver$fn__7874.invoke(executor.clj:464) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.disruptor$clojure_handler$reify__7390.onEvent(disruptor.clj:40) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:439) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:418) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>7953$fn</em><em>7966$fn</em>_8019.invoke(executor.clj:847) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at org.apache.storm.util$async_loop$fn__625.invoke(util.clj:484) <span class="error">&#91;storm-core-1.0.1.jar:1.0.1&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_121&#93;</span></p>

<p>But for less number of messages it is working fine.</p>

---
<details><summary><i>Originally reported by <a title="Krishnakanth" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krishnakanth23">krishnakanth23</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2487" target="_blank">getting com.mongodb.MongoBulkWriteException while trying to save bulk messages using apache storm mongo</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:15+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
