### ISSUE TITLE
[STORM-2511] Submitting a topology with name containing unicode getting failed.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6293]
<p>Below error occurs when a topology name contains  unicode characters.</p>

<blockquote>
<p>$ storm jar WordCountTopology-1.0-SNAPSHOT.jar examples.WordCountTopology "wordcount-中文topology"</p>

<p>2624 <span class="error">&#91;main&#93;</span> INFO  o.a.s.StormSubmitter - Submitting topology wordcount-中文topology in distributed mode with conf </p>
<div class="error"><span class="error">Unknown macro: {"storm.zookeeper.topology.auth.scheme"}</span> </div>
<p>Exception in thread "main" java.lang.RuntimeException: AuthorizationException(msg:wordcount-中文topology-4-1483689231-stormconf.ser does not appear to be a valid blob key)<br/>
at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:255)<br/>
at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:310)<br/>
at org.apache.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:346)<br/>
at org.apache.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:327)<br/>
at com.microsoft.example.KafkaReaderTop.main(KafkaReaderTop.java:39)<br/>
Caused by: AuthorizationException(msg:wordcount-中文topology-4-1483689231-stormconf.ser does not appear to be a valid blob key)<br/>
at org.apache.storm.generated.Nimbus$submitTopology_result$submitTopology_resultStandardScheme.read(Nimbus.java:7628)<br/>
at org.apache.storm.generated.Nimbus$submitTopology_result$submitTopology_resultStandardScheme.read(Nimbus.java:7596)<br/>
at org.apache.storm.generated.Nimbus$submitTopology_result.read(Nimbus.java:7530)<br/>
at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86)<br/>
at org.apache.storm.generated.Nimbus$Client.recv_submitTopology(Nimbus.java:294)<br/>
at org.apache.storm.generated.Nimbus$Client.submitTopology(Nimbus.java:278)<br/>
at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:243)<br/>
... 4 more</p></blockquote>

---
<details><summary><i>Originally reported by <a title="Satish Duggana" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2511" target="_blank">Submitting a topology with name containing unicode getting failed.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Satish Duggana" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-05-15T19:17:25+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana" class="user-hover" rel="satish.duggana">Satish Duggana</a>,</p>

<p>I merged this into master branch-1.x and branch-1.0.x</p>
