### ISSUE TITLE
[STORM-2547] Apache Metron stream: default not found

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6329]
<p>Hi together,<br/>
we tried to install Metron 0.4.0 accordingly to this tutorial: <a href="https://community.hortonworks.com/articles/88843/manually-installing-apache-metron-on-ubuntu-1404.html" class="external-link" target="_blank" rel="nofollow noopener">https://community.hortonworks.com/articles/88843/manually-installing-apache-metron-on-ubuntu-1404.html</a><br/>
The installation itself worked, but during step “Smoke Test Metron” two main problems aroused:<br/>
In the storm topology profiler the splitterBolt doesn’t work. The kafkaSpout receives data and forwards it to the splitterBolt which works but splitterBolt can’t handle the data.<br/>
We got the following exception:<br/>
Exception in thread "main" java.lang.IllegalArgumentException: stream: default not found<br/>
at org.apache.storm.utils.Monitor.metrics(Monitor.java:223)<br/>
at org.apache.storm.utils.Monitor.metrics(Monitor.java:159)<br/>
at org.apache.storm.command.monitor$_main.doInvoke(monitor.clj:36)<br/>
at clojure.lang.RestFn.applyTo(RestFn.java:137)<br/>
at org.apache.storm.command.monitor.main(Unknown Source)</p>

<p>The same exception occurs in the topology indexing at the indexingBolt.<br/>
All of the other topologies do work. Also, we receive data in HDFS but not in Elasticsearch. <br/>
We’d appreciate any tips!<br/>
Thanks in advance! <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/> </p>

---
<details><summary><i>Originally reported by <a title="Monika Dziuk" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=monimara">monimara</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2547" target="_blank">Apache Metron stream: default not found</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:26+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ottobackwards">ottobackwards</a>:</i>
<p>You may want to log this against the METRON project.  Metron has it's own implementation of the splitter and joiner.  It would be the better place to start looking at this, as opposed to at the storm level.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
