### ISSUE TITLE
[STORM-2560] Storm-Kafka on CDH 5.11 with kerberos security enabled.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6342]
<p>Hi,</p>

<p>I have installed Apache Storm 1.1.0 manually on CDH 5.11 cluster. This cluster is secured with kerberos. <br/>
I have storm sample written which ingest data from kafka topic and inserts into HDFS directory in real time. So, this sample uses storm-kafka as well as storm-hdfs. <br/>
When I run the storm topology it gives the following error in kafka-spout.</p>

<p> <font color="#d04437">2017-06-18 22:29:31.297 o.a.z.ClientCnxn Thread-14-kafka-spout-executor<span class="error">&#91;5 5&#93;</span>-SendThread(localhost:2181) <span class="error">&#91;INFO&#93;</span> Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)</font></p>

<p><font color="#d04437">2017-06-18 22:29:31.571 k.c.SimpleConsumer Thread-14-kafka-spout-executor<span class="error">&#91;5 5&#93;</span> <span class="error">&#91;INFO&#93;</span> Reconnect due to error:<br/>
java.nio.channels.ClosedChannelException: null<br/>
at kafka.network.BlockingChannel.send(BlockingChannel.scala:110) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:85) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:149) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at kafka.javaapi.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:79) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:75) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:65) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.PartitionManager.<init>(PartitionManager.java:94) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:98) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:69) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:129) <span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>4976$fn</em><em>4991$fn</em>_5022.invoke(executor.clj:644) <span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:484) <span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span></font></p>

<p>Kafka version: 2.1.1-1.2.1.1.p0.18</p>

<p>There is no storm-kafka*.jat present in - "/usr/local/storm"<br/>
But this sample was workin fine before kerberizing the cluster, even in this case.</p>

<p>I have tried the same example on Hortonworks and after adding the below code to set security protcol, the topology runs fine:<br/>
<b>spoutConfig.securityProtocol = "SASL_PLAINTEXT";</b><br/>
After Adding above code in case of cloudera it gives error: "Symbol not found"</p>

<p>Please let me know if you nedd any other information...<br/>
Thanks in advance..</p>

---
<details><summary><i>Originally reported by <a title="Niraj Parmar" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=niraj_parmar">niraj_parmar</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2560" target="_blank">Storm-Kafka on CDH 5.11 with kerberos security enabled.</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:03+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=huangjianan">huangjianan</a>:</i>
<p>I modified Storm-kafka and kafka_2.10_0.10.0.0 source code, and it work normally. But need to modify kafka_2.10 source code, how can I submit patch?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
