### ISSUE TITLE
[STORM-2599] BasicContainer.getWildcardDir tries to resolve the wildcard character with Paths.get, which prevents workers from booting on Windows

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6381]
<p><a href="https://issues.apache.org/jira/browse/STORM-2191" title="shorten classpaths in worker and LogWriter commands" class="issue-link" data-issue-key="STORM-2191"><del>STORM-2191</del></a> shortens the worker classpath by substituting in wildcards for the full list of jars. The path is constructed using Paths.get(dir, "*"), but this doesn't work on Windows. It seems like Windows checks that the path is valid. </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Paths.get(<span class="code-keyword">new</span> File(<span class="code-quote">"."</span>).toString(), <span class="code-quote">"*"</span>);

Exception in thread <span class="code-quote">"main"</span> java.nio.file.InvalidPathException: Illegal <span class="code-object">char</span> <*> at index 2: .\*
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
</pre>
</div></div>

<p>Paths doesn't guarantee support for globs, and we don't want the OS to examine the path in any case, since the wildcard isn't a "real" wildcard (including all files) but a special syntax for including jars in the Java classpath. The path should be constructed with String concatenation instead.</p>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2599" target="_blank">BasicContainer.getWildcardDir tries to resolve the wildcard character with Paths.get, which prevents workers from booting on Windows</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-06-29T06:34:43+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>, I merged into master and 1.x branch.</p>
