### ISSUE TITLE
[STORM-2612] Supervisor crashes when use the StormSubmitter.submitTopologyAs api to submit another user's topology.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6394]
<p>when use the StormSubmitter.submitTopologyAs api to impersonate another user , the supervisor crashes.<br/>
I used the user "nimbus" to start the supervisor, then I submit a topology as "Micheal", then I got this:<br/>
<font color="red">2017-07-03 17:47:11.340 o.a.s.u.Utils <span class="error">&#91;ERROR&#93;</span> An exception happened while downloading /home/Micheal/apache-storm-1.0.0/data/supervisor/tmp/5331e7d8-eb6f-403d-a2c5-45cecde9ca25/stormjar.jar from blob store.<br/>
AuthorizationException(msg:<span class="error">&#91;nimbus&#93;</span> does not have <span class="error">&#91;READ &#93;</span> access to topo3-8-1499073314-stormjar.jar)<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:25754)<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:25731)<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result.read(Nimbus.java:25662)<br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86)<br/>
	at org.apache.storm.generated.Nimbus$Client.recv_beginBlobDownload(Nimbus.java:825)<br/>
	at org.apache.storm.generated.Nimbus$Client.beginBlobDownload(Nimbus.java:812)<br/>
	at org.apache.storm.blobstore.NimbusBlobStore.getBlob(NimbusBlobStore.java:357)<br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorAttempt(Utils.java:516)<br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisor(Utils.java:497)<br/>
	at org.apache.storm.daemon.supervisor$fn__9590.invoke(supervisor.clj:948)<br/>
	at clojure.lang.MultiFn.invoke(MultiFn.java:243)<br/>
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this_<em>9351$fn</em>_9369.invoke(supervisor.clj:582)<br/>
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9351.invoke(supervisor.clj:581)<br/>
	at org.apache.storm.event$event_manager$fn__8903.invoke(event.clj:40)<br/>
	at clojure.lang.AFn.run(AFn.java:22)<br/>
	at java.lang.Thread.run(Thread.java:745)</font><br/>
I wonder if there is some parameter I can set to make this work.<br/>
Thanks in advance.</p>

---
<details><summary><i>Originally reported by <a title="MichealShin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=MichealShin">MichealShin</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2612" target="_blank">Supervisor crashes when use the StormSubmitter.submitTopologyAs api to submit another user's topology.</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2017-07-12T16:01:55+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>If you are using Storm 1.0.0, could you upgrade it to 1.0.3 and try it again? <br/>
(I recommend 1.1.0, but 1.0.3 is OK if you don't want to upgrade to next minor.)</p>

<p>I'd just like to avoid revisiting already-resolved issues.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michealshin">michealshin</a>:</i>
<p>Thanks. I'll try~</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michealshin">michealshin</a>:</i>
<p>It works when I use the 1.1.0 version.<br/>
But there is still a small problem.<br/>
When set the parameter "supervisor.run.worker.as.user" to true, the supervisor will crash , the log is :<br/>
<font color="red">java.io.IOException: Cannot run program "/usr/Micheal/apache-storm-1.1.0/bin/worker-launcher": error=2, No such file or directory<br/>
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) ~<span class="error">&#91;?:1.7.0_79&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.SupervisorUtils.launchProcess(SupervisorUtils.java:291) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.SupervisorUtils.processLauncher(SupervisorUtils.java:79) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.SupervisorUtils.processLauncherAndWait(SupervisorUtils.java:85) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.SupervisorUtils.setupStormCodeDir(SupervisorUtils.java:103) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.AdvancedFSOps$AdvancedRunAsUserFSOps.setupStormCodeDir(AdvancedFSOps.java:106) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:148) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:101) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~<span class="error">&#91;?:1.7.0_79&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_79&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_79&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_79&#93;</span><br/>
Caused by: java.io.IOException: error=2, No such file or directory<br/>
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~<span class="error">&#91;?:1.7.0_79&#93;</span><br/>
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186) ~<span class="error">&#91;?:1.7.0_79&#93;</span><br/>
	at java.lang.ProcessImpl.start(ProcessImpl.java:130) ~<span class="error">&#91;?:1.7.0_79&#93;</span><br/>
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028) ~<span class="error">&#91;?:1.7.0_79&#93;</span><br/>
	... 11 more</font><br/>
Is there something missing in the release tar.gz file ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Let's close this as 'invalid' and send a mail to user mailing list to ask help for newer issue.</p>
