### ISSUE TITLE
[STORM-2637] ClassCastException in logviewer get-log-user-group-whitelist function

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6419]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2017-07-17 18:12:42.073 o.e.j.s.ServletHandler qtp1452355939-21 [WARN] /log
java.lang.ClassCastException: java.io.File cannot be <span class="code-keyword">cast</span> to java.lang.<span class="code-object">String</span>
at org.apache.storm.daemon.logviewer$get_log_user_group_whitelist.invoke(logviewer.clj:314) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPS
HOT]
at org.apache.storm.daemon.logviewer$authorized_log_user_QMARK_.invoke(logviewer.clj:330) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHO
T]
at org.apache.storm.daemon.logviewer$log_page.invoke(logviewer.clj:419) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.logviewer$fn__4141.invoke(logviewer.clj:1038) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at compojure.core$make_route$fn__355.invoke(core.clj:100) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at compojure.core$if_route$fn__343.invoke(core.clj:46) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at compojure.core$if_method$fn__336.invoke(core.clj:31) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at compojure.core$routing$fn__361.invoke(core.clj:113) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at clojure.core$some.invoke(core.clj:2570) ~[clojure-1.7.0.jar:?]
at compojure.core$routing.doInvoke(core.clj:113) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at clojure.lang.RestFn.applyTo(RestFn.java:139) ~[clojure-1.7.0.jar:?]
at clojure.core$apply.invoke(core.clj:632) ~[clojure-1.7.0.jar:?]
at compojure.core$routes$fn__365.invoke(core.clj:118) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.ui.helpers$requests_middleware$fn__1810.invoke(helpers.clj:54) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at ring.middleware.keyword_params$wrap_keyword_params$fn__1502.invoke(keyword_params.clj:35) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAP
SHOT]
at ring.middleware.nested_params$wrap_nested_params$fn__1545.invoke(nested_params.clj:84) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHO
T]
at ring.middleware.params$wrap_params$fn__1474.invoke(params.clj:64) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.logviewer$conf_middleware$fn__4195.invoke(logviewer.clj:1202) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT
]
at ring.util.servlet$make_service_method$fn__1240.invoke(servlet.clj:127) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at ring.util.servlet$servlet$fn__1244.invoke(servlet.clj:136) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source) ~[storm-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSH
OT]
..
</pre>
</div></div>

<p>In get-log-user-group-whitelist function, the result returned by getLogMetaDataFile is a File; the readYamlFile function requires a String.</p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2637" target="_blank">ClassCastException in logviewer get-log-user-group-whitelist function</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2017-07-18T01:31:58+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>This bug happens in master branch. Since <a href="https://github.com/apache/storm/pull/2204/" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2204/</a> is going to replace logviewer clojure implementation, this issue is no longer needed.</p>

<p>1.x-branch works fine. </p>
