### ISSUE TITLE
[STORM-2652] Exception thrown in JmsSpout open method

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6434]
<p>Due to a bug, the message timeout configuration property is read as an integer even though it is of type long.</p>

<p>```<br/>
7317 [Thread-18-a-executor<span class="error">&#91;2 2&#93;</span>] ERROR o.a.s.util - Async loop died!<br/>
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer<br/>
	at org.apache.storm.jms.spout.JmsSpout.open(JmsSpout.java:175) ~<span class="error">&#91;storm-jms-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.daemon.executor$fn_<em>4976$fn</em>_4991.invoke(executor.clj:600) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) <span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_131&#93;</span><br/>
7320 [Thread-18-a-executor<span class="error">&#91;2 2&#93;</span>] ERROR o.a.s.d.executor - <br/>
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer<br/>
	at org.apache.storm.jms.spout.JmsSpout.open(JmsSpout.java:175) ~<span class="error">&#91;storm-jms-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.daemon.executor$fn_<em>4976$fn</em>_4991.invoke(executor.clj:600) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) <span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_131&#93;</span><br/>
```</p>

---
<details><summary><i>Originally reported by <a title="Omer Hadari" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=omerhadari">omerhadari</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2652" target="_blank">Exception thrown in JmsSpout open method</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Omer Hadari" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=omerhadari">omerhadari</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-07-23T20:38:00+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=omerhadari">omerhadari</a>:</i>
<p>For assigning to reporter </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vesense">vesense</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=omerhadari" class="user-hover" rel="omerhadari">Omer Hadari</a> I assigned the Jira to you and added you to the Jira contributors.</p>
