### ISSUE TITLE
[STORM-2674] NoNodeException when ZooKeeper tries to delete nodes

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6456]
<p>When <a href="https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/cluster/StormClusterStateImpl.java#L650-L660" class="external-link" target="_blank" rel="nofollow noopener">StormClusterStateImpl reportError function</a> is called, it will get all the children of </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">/storm/errors/<topo-id>/count/
</pre>
</div></div>
<p> and delete some znodes to keep latest 10 errors. NoNodeException could happen when any znode is already deleted by other executors.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode <span class="code-keyword">for</span> /errors/fastwc-halferrors-1-1501689263/count/e0000000562 at org.apache.storm.utils.Utils$2.run(Utils.java:345) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode <span class="code-keyword">for</span> /errors/fastwc-halferrors-1-1501689263/count/e0000000562 at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:489) at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:455) at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:98) at org.apache.storm.utils.Utils$2.run(Utils.java:335) ... 1 more Caused by: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode <span class="code-keyword">for</span> /errors/fastwc-halferrors-1-1501689263/count/e0000000562 at org.apache.storm.utils.Utils.wrapInRuntime(Utils.java:413) at org.apache.storm.zookeeper.ClientZookeeper.deleteNode(ClientZookeeper.java:165) at org.apache.storm.cluster.ZKStateStorage.delete_node(ZKStateStorage.java:139) at org.apache.storm.cluster.StormClusterStateImpl.reportError(StormClusterStateImpl.java:655) at org.apache.storm.executor.error.ReportError.report(ReportError.java:69) at org.apache.storm.executor.bolt.BoltOutputCollectorImpl.reportError(BoltOutputCollectorImpl.java:154) at org.apache.storm.task.OutputCollector.reportError(OutputCollector.java:234) at org.apache.storm.topology.BasicOutputCollector.reportError(BasicOutputCollector.java:70) at org.apache.storm.starter.FastWordCountTopology$WordCount.execute(FastWordCountTopology.java:113) at org.apache.storm.topology.BasicBoltExecutor.execute(BasicBoltExecutor.java:50) at org.apache.storm.executor.bolt.BoltExecutor.tupleActionFn(BoltExecutor.java:125) at org.apache.storm.executor.Executor.onEvent(Executor.java:255) at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:476) ... 4 more Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode <span class="code-keyword">for</span> /errors/fastwc-halferrors-1-1501689263/count/e0000000562 at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873) at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:250) at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:244) at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109) at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:241) at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:225) at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35) at org.apache.storm.zookeeper.ClientZookeeper.deleteNode(ClientZookeeper.java:158) ... 15 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2674" target="_blank">NoNodeException when ZooKeeper tries to delete nodes</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-08-09T13:10:30+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli" class="user-hover" rel="ethanli">Ethan Li</a>,</p>

<p>I merged this into master, but the issue also exists on 1.x-branch.  Could you back port your fix to that branch?  Sadly because the file was moved git is not making it a clean merge.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> Yes, sure. will do</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>On 1.x-branch: <a href="https://github.com/apache/storm/pull/2264" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2264</a></p>
