### ISSUE TITLE
[STORM-2681] Regarding Issue with Multi-Lang in Storm While Running Python (WordCountTopology )

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6463]
<p>I am trying to run the WordCountTopology in storm local mode before running my own application and I am unable to run it. I am continuously getting the following error. I have verified that the splitsentence.py file is kept at the multilang/resources directory which is in the examples/storm-starter directory.</p>

<p>5729 [Thread-22-split-executor<span class="error">&#91;7 7&#93;</span>] ERROR o.a.s.util - Async loop died!<br/>
java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.<br/>
Serializer Exception:<br/>
python: can't open file 'splitsentence.py': <span class="error">&#91;Errno 2&#93;</span> No such file or directory</p>

<p>at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:91) ~<span class="error">&#91;storm-core-1.0.3.jar:1.0.3&#93;</span><br/>
at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:131) ~<span class="error">&#91;storm-core-1.0.3.jar:1.0.3&#93;</span><br/>
at org.apache.storm.daemon.executor$fn_<em>4973$fn</em>_4986.invoke(executor.clj:791) ~<span class="error">&#91;storm-core-1.0.3.jar:1.0.3&#93;</span><br/>
at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) <span class="error">&#91;storm-core-1.0.3.jar:1.0.3&#93;</span><br/>
at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_51&#93;</span><br/>
5734 [Thread-30-spout-executor<span class="error">&#91;9 9&#93;</span>] INFO  o.a.s.d.executor - Opening spout spout:(9)<br/>
5734 [Thread-28-split-executor<span class="error">&#91;6 6&#93;</span>] ERROR o.a.s.util - Async loop died!</p>

<p>I have followed the instructions during installation and built my package successfully with maven. My storm version is 1.0.3 and my python version is 2.7.13. I ran the ExclamationTopology and some of my own code which does not need multi-language support and it works like a charm.</p>

<p>I am not able to understand why the multi-lang support in storm is not working. Any help with this is greatly appreciated.</p>

---
<details><summary><i>Originally reported by <a title="Sitakanta Mishra" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=skmishra5">skmishra5</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2681" target="_blank">Regarding Issue with Multi-Lang in Storm While Running Python (WordCountTopology )</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:50+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
