### ISSUE TITLE
[STORM-2682] Supervisor crashes with NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6464]
<p>When supervisor is started, it dies after about 30s like so:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">...
2017-08-07 17:12:04.606 o.a.s.d.s.Slot main [WARN] SLOT 192.168.10.21:6701 Starting in state EMPTY - assignment <span class="code-keyword">null</span>
2017-08-07 17:12:04.607 o.a.s.d.s.Slot main [WARN] SLOT 192.168.10.21:6702 Starting in state EMPTY - assignment <span class="code-keyword">null</span>
2017-08-07 17:12:04.607 o.a.s.l.AsyncLocalizer main [INFO] Cleaning up unused topologies in /home/storm/data/supervisor/stormdist
2017-08-07 17:12:04.617 o.a.s.d.s.Supervisor main [INFO] Starting supervisor with id 65a0f977-474c-4938-a4f5-bc99939e96ff at host 192.168.10.
21.
2017-08-07 17:12:04.619 o.a.s.d.m.MetricsUtils main [INFO] Using statistics reporter plugin:org.apache.storm.daemon.metrics.reporters.JmxPrep
arableReporter
2017-08-07 17:12:04.620 o.a.s.d.m.r.JmxPreparableReporter main [INFO] Preparing...
2017-08-07 17:12:04.624 o.a.s.m.StormMetricsRegistry main [INFO] Started statistics report plugin...
2017-08-07 17:12:34.620 o.a.s.e.EventManagerImp <span class="code-object">Thread</span>-4 [ERROR] {} Error when processing event
java.lang.NullPointerException: <span class="code-keyword">null</span>
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_121]
at org.apache.storm.localizer.Localizer.updateBlobs(Localizer.java:332) ~[storm-core-1.0.4.jar:1.0.4]
at org.apache.storm.daemon.supervisor.timer.UpdateBlobs.updateBlobsForTopology(UpdateBlobs.java:99) ~[storm-core-1.0.4.jar:1.0.4]
at org.apache.storm.daemon.supervisor.timer.UpdateBlobs.run(UpdateBlobs.java:72) ~[storm-core-1.0.4.jar:1.0.4]
at org.apache.storm.event.EventManagerImp$1.run(EventManagerImp.java:54) ~[storm-core-1.0.4.jar:1.0.4]
2017-08-07 17:12:34.620 o.a.s.u.Utils <span class="code-object">Thread</span>-4 [ERROR] Halting process: Error when processing an event
java.lang.RuntimeException: Halting process: Error when processing an event
at org.apache.storm.utils.Utils.exitProcess(Utils.java:1750) ~[storm-core-1.0.4.jar:1.0.4]
at org.apache.storm.event.EventManagerImp$1.run(EventManagerImp.java:63) ~[storm-core-1.0.4.jar:1.0.4]
2017-08-07 17:12:34.631 o.a.s.d.s.Supervisor <span class="code-object">Thread</span>-5 [INFO] Shutting down supervisor 65a0f977-474c-4938-a4f5-bc99939e96ff
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Martin Burian" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=buriama8">buriama8</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2682" target="_blank">Supervisor crashes with NullPointerException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-08-19T03:25:16+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Trying to reproduce this...</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=buriama8" class="user-hover" rel="buriama8">Martin Burian</a></p>

<p>Are you running a secure cluster or is it insecure?  </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=buriama8">buriama8</a>:</i>
<p>I have not set up any security (authentication or anything else), so I would think insecure.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>And you saw this while upgrading from 1.0.3 to 1.0.4?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I was able to reproduce it and it looks like some of the code that we put in to help with a rolling upgrade is either not working properly or is not being executed.  I'll do some more debugging and see what I can come up with.  Also see if I can come up with a work around for it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I figured out the issue.  I'm not sure why my tests didn't catch it to begin with.  I'll get a pull request up ASAP.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=smaldeniya">smaldeniya</a>:</i>
<p>I also get this issue. We are using 1.11 and it is not running in secure mode.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.blanchard">dan.blanchard</a>:</i>
<p>We started experiencing this immediately upon upgrading from 1.1.0 to 1.1.1 on one cluster and from 1.0.2 to 1.1.1 on another cluster. Oddly enough, the cluster seems to actually keep processing even with the supervisors dying repeatedly.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.blanchard" class="user-hover" rel="dan.blanchard">Dan Blanchard</a> <br/>
Could you help us confirming Bobby's patch resolve the issue? Patch is ready <a href="https://github.com/apache/storm/pull/2267" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2267</a> for 1.x version line. If you don't want to apply this manually I'll provide patched version of 1.1.2-SNAPSHOT storm-core jar.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.blanchard">dan.blanchard</a>:</i>
<p>Sure, if you can provide a 1.1.2-SNAPSHOT JAR I can test this out on our beta cluster.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.blanchard" class="user-hover" rel="dan.blanchard">Dan Blanchard</a>,</p>

<p>The supervisor only needs to be up to launch and kill workers.  This failure only happens about 30 seconds after the supervisor comes up (on a background thread)  so the supervisors get 30 seconds of real work done before it crashes.  That is enough time to kill/launch a lot of workers.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=smaldeniya">smaldeniya</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> I have replaced storm-core-1.1.1.jar with the attach jar and restarted our test cluster. for the last hour it works without supervisor restarts and workers getting killed (issue).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> for fixing critical issue so quickly. I merged into all 1.x version lines and master.<br/>
Let's discuss another bug fix releases sooner.</p>
