### ISSUE TITLE
[STORM-2707] Nimbus loops forever with getClusterInfo error if it looses storm.local.dir contents

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6489]
<p>Hello,</p>

<p>Short issue description:</p>
<ul>
	<li>Remove storm.local.dir directory</li>
	<li>Storm UI isn't anymore able to query anything from Nimbus</li>
	<li>Nimbus process prints getClusterInfo exceptions in its log whenever it gets a query from Nimbus UI or from "storm" command line</li>
	<li>To fix this issue, we have to stop all Storm processes, cleanup the content of Zookeeper nodes, then restart & redeploy our topologies</li>
</ul>

<p>Excepted behavior:</p>
<ul>
	<li>In such case, Storm should cleanup the content of Zookeeper and recover in a mode allowing to kill & restart all topologies</li>
</ul>

<p>More details:<br/>
===========<br/>
Sometimes we loose the content of storm.local.dir on our single-node Nimbus production cluster.</p>

<p>We haven't yet considered deploying Nimbus in HA because this is a relatively modest deployment with budget constrains on the number of the number of IaaS resources which can be used for this application. So far so good, because in our environment, Nimbus & Nimbus UI (hosted on same VM) are supervized, and we also have self-healing crons to automatically kill & restart topologies blocked in Kafka consumption or having too many failed tuples (because Storm back pressure has some fuzzy limits, so we use this by-pass, as approved by Roshan in a past discussion, but that's not the point here).</p>

<p>Our problem is that sometime, we loose the content of storm.local.dir.</p>

<p>When it happens, our supervision detects the issue because it cannot anymore query Nimbus REST services on Nimbus-UI process.</p>

<p>In such case it tries to restart Storm-UI but this doesn't help because queries to Storm-UI fails with the following stack trace when it tries to list all topologies:</p>

<p>org.apache.storm.thrift.TApplicationException: Internal error processing getClusterInfo<br/>
	at org.apache.storm.thrift.TApplicationException.read(TApplicationException.java:111)<br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:79)<br/>
	at org.apache.storm.generated.Nimbus$Client.recv_getClusterInfo(Nimbus.java:1168)<br/>
	at org.apache.storm.generated.Nimbus$Client.getClusterInfo(Nimbus.java:1156)<br/>
	at org.apache.storm.ui.core$cluster_summary.invoke(core.clj:356)<br/>
	at org.apache.storm.ui.core$fn__9556.invoke(core.clj:1113)<br/>
	at org.apache.storm.shade.compojure.core$make_route$fn__5976.invoke(core.clj:100)<br/>
	at org.apache.storm.shade.compojure.core$if_route$fn__5964.invoke(core.clj:46)<br/>
	at org.apache.storm.shade.compojure.core$if_method$fn__5957.invoke(core.clj:31)<br/>
	at org.apache.storm.shade.compojure.core$routing$fn__5982.invoke(core.clj:113)<br/>
	at clojure.core$some.invoke(core.clj:2570)<br/>
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:113)<br/>
	at clojure.lang.RestFn.applyTo(RestFn.java:139)<br/>
	at clojure.core$apply.invoke(core.clj:632)<br/>
	at org.apache.storm.shade.compojure.core$routes$fn__5986.invoke(core.clj:118)<br/>
	at org.apache.storm.shade.ring.middleware.cors$wrap_cors$fn__8891.invoke(cors.clj:149)<br/>
	at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__8838.invoke(json.clj:56)<br/>
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__6618.invoke(multipart_params.clj:118)<br/>
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__7901.invoke(reload.clj:22)<br/>
	at org.apache.storm.ui.helpers$requests_middleware$fn__6871.invoke(helpers.clj:50)<br/>
	at org.apache.storm.ui.core$catch_errors$fn__9758.invoke(core.clj:1428)<br/>
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__6538.invoke(keyword_params.clj:35)<br/>
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__6581.invoke(nested_params.clj:84)<br/>
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__6510.invoke(params.clj:64)<br/>
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__6618.invoke(multipart_params.clj:118)<br/>
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__6833.invoke(flash.clj:35)<br/>
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__6819.invoke(session.clj:98)<br/>
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__6368.invoke(servlet.clj:127)<br/>
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__6372.invoke(servlet.clj:136)<br/>
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)<br/>
	at org.apache.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:47)<br/>
	at org.apache.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:39)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)<br/>
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
	at java.lang.reflect.Method.invoke(Method.java:498)<br/>
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)<br/>
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)<br/>
	at org.apache.storm.ui.helpers$x_frame_options_filter_handler$fn__6964.invoke(helpers.clj:189)<br/>
	at org.apache.storm.ui.helpers.proxy$java.lang.Object$Filter$abec9a8f.doFilter(Unknown Source)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)<br/>
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)<br/>
	at java.lang.Thread.run(Thread.java:748)</p>

<p>In Nimbus.log, we also have this kind of exception each time Nimbus UI is queried:</p>

<p>org.apache.storm.generated.KeyNotFoundException: null<br/>
at org.apache.storm.blobstore.LocalFsBlobStore.getStoredBlobMeta(LocalFsBlobStore.java:147) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
at org.apache.storm.blobstore.LocalFsBlobStore.getBlobReplication(LocalFsBlobStore.java:299) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~<span class="error">&#91;?:1.8.0_144&#93;</span><br/>
at java.lang.reflect.Method.invoke(Method.java:498) ~<span class="error">&#91;?:1.8.0_144&#93;</span><br/>
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at org.apache.storm.daemon.nimbus$get_blob_replication_count.invoke(nimbus.clj:489) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
at org.apache.storm.daemon.nimbus$get_cluster_info$iter_<em>10687</em><em>10691$fn</em>_10692.invoke(nimbus.clj:1550) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
at clojure.lang.LazySeq.sval(LazySeq.java:40) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at clojure.lang.LazySeq.seq(LazySeq.java:49) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at clojure.lang.RT.seq(RT.java:507) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at clojure.core$seq__4128.invoke(core.clj:137) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at clojure.core$dorun.invoke(core.clj:3009) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at clojure.core$doall.invoke(core.clj:3025) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
at org.apache.storm.daemon.nimbus$get_cluster_info.invoke(nimbus.clj:1524) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10782.getClusterInfo(nimbus.clj:1971) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
at org.apache.storm.generated.Nimbus$Processor$getClusterInfo.getResult(Nimbus.java:3920) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span><br/>
at org.apache.storm.generated.Nimbus$Processor$getClusterInfo.getResult(Nimbus.java:3904) ~<span class="error">&#91;storm-core-1.1.0.jar:1.1.0&#93;</span></p>

<p>Even if Storm was shutting down in such case, this wouldn't help because we have to cleanup all Zookeepers to put our Storm cluster back to life.</p>

<p>Ideally, we would like that when storm.local.dir is lost, Nimbus will re-create it "blank" and cleanups Zookeeper nodes (that's the tricky part); then we expect that Supervisors (which are unaffected by this issue when it occurs) will re-register themselves to make Nimbus aware that topologies are Running. </p>

<p>Also, Topologies restart from UI should consistently fail until topologies JARs are re-submitted (please make the error message very clear and easy to "grep" when such case occurs);</p>

<p>This is my first JIRA, I hope I provided everything to let Storm developers dig this issue ; otherwise please let me know if more information is required: I will be glad to help as much as I can... Storm rocks!</p>

<p>Best regards,<br/>
Alexandre Vermeerbergen</p>

---
<details><summary><i>Originally reported by <a title="Alexandre Vermeerbergen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2707" target="_blank">Nimbus loops forever with getClusterInfo error if it looses storm.local.dir contents</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:10+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
