### ISSUE TITLE
[STORM-2766] java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 349, Size: 349 at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:495) at org.apache.storm.util

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6548]
<p>java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 349, Size: 349 at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:495) at org.apache.storm.util</p>

---
<details><summary><i>Originally reported by <a title="xmaszh" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xmaszh">xmaszh</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2766" target="_blank">java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 349, Size: 349 at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:495) at org.apache.storm.util</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:42+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
