### ISSUE TITLE
[STORM-2774] Workers get killed with FileNotFoundException on stormjar.jar

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6556]
<p>Hi,</p>

<p> Worker processes sometimes get killed unable to find stormjar.jar in tmp directory. The stacktrace looks as below. </p>

<p>10.0.0.113 2017-10-12 10:28:33.657 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span> Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be c<br/>
reated<br/>
10.0.0.113 2017-10-12 10:28:33.657 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:308)<br/>
10.0.0.113 2017-10-12 10:28:33.657 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       ... 85 more<br/>
10.0.0.113 2017-10-12 10:28:33.657 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span> Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.DocumentBuilderFactory: Error reading config<br/>
uration file<br/>
10.0.0.113 2017-10-12 10:28:33.658 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.ServiceLoader.fail(ServiceLoader.java:232)<br/>
10.0.0.113 2017-10-12 10:28:33.658 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.ServiceLoader.parse(ServiceLoader.java:309)<br/>
10.0.0.113 2017-10-12 10:28:33.658 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.ServiceLoader.access$200(ServiceLoader.java:185)<br/>
10.0.0.113 2017-10-12 10:28:33.658 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)<br/>
10.0.0.113 2017-10-12 10:28:33.658 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)<br/>
10.0.0.113 2017-10-12 10:28:33.658 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)<br/>
10.0.0.113 2017-10-12 10:28:33.658 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)<br/>
10.0.0.113 2017-10-12 10:28:33.658 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.security.AccessController.doPrivileged(Native Method)<br/>
10.0.0.113 2017-10-12 10:28:33.659 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)<br/>
10.0.0.113 2017-10-12 10:28:33.659 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       ... 85 more<br/>
10.0.0.113 2017-10-12 10:28:33.659 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span> Caused by: java.io.FileNotFoundException: /var/log/storm/tmp/supervisor/stormdist/R2Topology-80-1507783551/stormjar.jar (No such file or directory)<br/>
10.0.0.113 2017-10-12 10:28:33.659 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.zip.ZipFile.open(Native Method)<br/>
10.0.0.113 2017-10-12 10:28:33.659 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.zip.ZipFile.<init>(ZipFile.java:219)<br/>
10.0.0.113 2017-10-12 10:28:33.660 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.zip.ZipFile.<init>(ZipFile.java:149)<br/>
10.0.0.113 2017-10-12 10:28:33.660 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.jar.JarFile.<init>(JarFile.java:166)<br/>
10.0.0.113 2017-10-12 10:28:33.660 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.jar.JarFile.<init>(JarFile.java:103)<br/>
10.0.0.113 2017-10-12 10:28:33.660 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)<br/>
10.0.0.113 2017-10-12 10:28:33.660 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)<br/>
10.0.0.113 2017-10-12 10:28:33.660 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)<br/>
10.0.0.113 2017-10-12 10:28:33.660 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)<br/>
10.0.0.113 2017-10-12 10:28:33.661 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)<br/>
10.0.0.113 2017-10-12 10:28:33.661 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.net.URL.openStream(URL.java:1045)<br/>
10.0.0.113 2017-10-12 10:28:33.661 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       at java.util.ServiceLoader.parse(ServiceLoader.java:304)<br/>
10.0.0.113 2017-10-12 10:28:33.661 STDERR Thread-1 <span class="error">&#91;INFO&#93;</span>       ... 92 more</p>

---
<details><summary><i>Originally reported by <a title="Sreeram Venkatasubramanian" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Sreeram">Sreeram</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2774" target="_blank">Workers get killed with FileNotFoundException on stormjar.jar</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:04+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
