### ISSUE TITLE
[STORM-2802] Storm-cassandra tests don't run on JDK 9

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6584]
<p>The storm-cassandra tests don't run on JDK 9. </p>

<blockquote>
<p>opaqueStateTest(org.apache.storm.cassandra.trident.MapStateTest)  Time elapsed: 0.627 sec  <<< ERROR!<br/>
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: <span class="error">&#91;localhost/127.0.0.1:9042&#93;</span> Error writing))<br/>
at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)<br/>
at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)<br/>
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1473)<br/>
at com.datastax.driver.core.Cluster.init(Cluster.java:159)<br/>
at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)<br/>
at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)<br/>
at com.datastax.driver.core.Cluster.connect(Cluster.java:247)<br/>
at org.apache.storm.cassandra.trident.MapStateTest.setUp(MapStateTest.java:163)<br/>
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
at java.base/java.lang.reflect.Method.invoke(Method.java:564)<br/>
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)<br/>
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)<br/>
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)<br/>
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)<br/>
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)<br/>
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)<br/>
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)<br/>
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)<br/>
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)<br/>
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)<br/>
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)<br/>
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)<br/>
at org.junit.rules.RunRules.evaluate(RunRules.java:20)<br/>
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)<br/>
at org.junit.runners.Suite.runChild(Suite.java:127)<br/>
at org.junit.runners.Suite.runChild(Suite.java:26)<br/>
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)<br/>
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)<br/>
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)<br/>
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)<br/>
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)<br/>
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)<br/>
at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)<br/>
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)<br/>
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)<br/>
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)<br/>
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)<br/>
at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:161)<br/>
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)<br/>
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)<br/>
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)</p>
</blockquote>

<p>Java 9 support for Cassandra is tracked at <a href="https://issues.apache.org/jira/browse/CASSANDRA-9608" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CASSANDRA-9608</a></p>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2802" target="_blank">Storm-cassandra tests don't run on JDK 9</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:50+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtask of parent task STORM-2798

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
