### ISSUE TITLE
[STORM-2808] Main UI gets some errors.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6590]
<p>I noticed that the UI is throwing exceptions...</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.NullPointerException
	at clojure.lang.Numbers.minus(Numbers.java:3708)
	at org.apache.storm.ui.core$cluster_summary$iter__3372__3376$fn__3377.invoke(core.clj:430)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:26)
	at clojure.core.protocols$fn__6506.invoke(protocols.clj:100)
	at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6515)
	at org.apache.storm.ui.core$cluster_summary.invoke(core.clj:426)
	at org.apache.storm.ui.core$cluster_summary.invoke(core.clj:412)
	at org.apache.storm.ui.core$fn__3865.invoke(core.clj:1258)
	at compojure.core$make_route$fn__382.invoke(core.clj:100)
	at compojure.core$if_route$fn__370.invoke(core.clj:46)
	at compojure.core$if_method$fn__363.invoke(core.clj:31)
	at compojure.core$routing$fn__388.invoke(core.clj:113)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:113)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at compojure.core$routes$fn__392.invoke(core.clj:118)
	at ring.middleware.json$wrap_json_params$fn__1800.invoke(json.clj:74)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__1038.invoke(multipart_params.clj:172)
	at ring.middleware.reload$wrap_reload$fn__844.invoke(reload.clj:39)
	at org.apache.storm.ui.helpers$requests_middleware$fn__3110.invoke(helpers.clj:46)
	at org.apache.storm.ui.core$catch_errors$fn__4073.invoke(core.clj:1587)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__2851.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__2891.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__2823.invoke(params.clj:67)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__1038.invoke(multipart_params.clj:172)
	at ring.middleware.flash$wrap_flash$fn__3096.invoke(flash.clj:39)
	at ring.middleware.session$wrap_session$fn__3081.invoke(session.clj:108)
	at ring.util.servlet$make_blocking_service_method$fn__2718.invoke(servlet.clj:113)
	at ring.util.servlet$servlet$fn__2729.invoke(servlet.clj:147)
	at ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.apache.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:51)
	at org.apache.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:43)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:561)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2808" target="_blank">Main UI gets some errors.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Govind Menon" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gmenon">gmenon</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-11-12T22:21:04+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <span class="error">&#91;~govindmenon&#93;</span>, I merged into master.</p>
