### ISSUE TITLE
[STORM-2809] Integration test is failing consistently and topologies sometimes fail to start workers

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6591]
<p>The integration test has been failing fairly consistently since <a href="https://github.com/apache/storm/pull/2363" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2363</a>. I tried running the test outside a VM with a locally installed Storm setup, and it has failed every time for me.</p>

<p>Most runs seem to fail in ways that make it look like the integration test is just flaky (e.g. tuple windows not matching the calculated window), but in at least a few tests I saw the topology get submitted to Nimbus followed by about 3 minutes of nothing happening. The workers never started and the supervisor didn't seem aware of the scheduling. The only evidence that the topology was submitted was in the Nimbus log. This still happens even if the test topologies are killed with a timeout of 0, so there should be slots free for the next test immediately.</p>

<p>I tried reverting <a href="https://github.com/apache/storm/pull/2363" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2363</a> and it seems to make the integration test pass much more often. Over 5 runs there was still an instance of a supervisor failing to start the workers, but the other 4 passed.</p>

<p>We should try to fix whatever is causing the supervisor to fail to start workers, and get the integration test more stable.</p>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2809" target="_blank">Integration test is failing consistently and topologies sometimes fail to start workers</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Robert Joseph Evans" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-11-14T21:54:24+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I think I was able to reproduce it on my laptop, and will start trying to dig into it, but I have jury duty this week so I have no idea what my schedule is going to be like.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>This might be related.  In my supervisor logs I see for a specific topology that it failed to download the jar, etc for it.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
AsyncLocalizer Executor - 2 [WARN] Failed to download blob LOCAL TOPO BLOB TOPO_CONF TumblingWindowTestt2-20-1510353392 will <span class="code-keyword">try</span> again in 100 ms
</pre>
</div></div>

<p>Looking at nimbus for it I see.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2017-11-10 16:36:32.412 o.a.s.d.n.Nimbus pool-14-thread-28 [INFO] Received topology submission <span class="code-keyword">for</span> TumblingWindowTestt2
...
2017-11-10 16:36:41.834 o.a.s.d.n.Nimbus timer [INFO] Setting <span class="code-keyword">new</span> assignment <span class="code-keyword">for</span> topology id TumblingWindowTestt2-20-1510353392
...
2017-11-10 16:38:12.529 o.a.s.d.n.Nimbus pool-14-thread-51 [INFO] Delaying event REMOVE <span class="code-keyword">for</span> 30 secs <span class="code-keyword">for</span> TumblingWindowTestt2-20-1510353392
2017-11-10 16:38:12.529 o.a.s.d.n.Nimbus pool-14-thread-51 [INFO] TRANSITION: TumblingWindowTestt2-20-1510353392 KILL <span class="code-keyword">null</span> <span class="code-keyword">true</span>
2017-11-10 16:38:12.531 o.a.s.d.n.Nimbus pool-14-thread-51 [INFO] Adding topo to history log: TumblingWindowTestt2-20-1510353392
...
2017-11-10 16:38:42.019 o.a.s.d.n.Nimbus timer [INFO] Executor TumblingWindowTestt2-20-1510353392:[1, 1] not alive
...
2017-11-10 16:38:42.020 o.a.s.d.n.Nimbus timer [INFO] Setting <span class="code-keyword">new</span> assignment <span class="code-keyword">for</span> topology id TumblingWindowTestt2-20-1510353392 <span class="code-comment">//No assignments
</span>...
2017-11-10 16:38:42.533 o.a.s.d.n.Nimbus timer [INFO] Killing topology: TumblingWindowTestt2-20-1510353392
...
</pre>
</div></div>

<p>Only after the topology was totally killed did the supervisor start doing anything about it.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2017-11-10 16:39:36.639 o.a.s.l.AsyncLocalizer AsyncLocalizer Executor - 2 [WARN] Failed to download blob LOCAL TOPO BLOB TOPO_CONF TumblingWindowTestt2-20-1510353392 will <span class="code-keyword">try</span> again in 100 ms
</pre>
</div></div>

<p>It was just under 3 mins from the time the worker was scheduled that the supervisor started to look at it.</p>

<p>I will try to see what the supervisor was doing at that time.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>So the supervisor was in waiting for blob localization on the slots it needed.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2017-11-10 16:39:36.629 o.a.s.d.s.Slot SLOT_6701 [INFO] STATE EMPTY msInState: 181025 -> WAITING_FOR_BLOB_LOCALIZATION msInState: 0
2017-11-10 16:39:36.629 o.a.s.d.s.Slot SLOT_6702 [INFO] STATE EMPTY msInState: 181026 -> WAITING_FOR_BLOB_LOCALIZATION msInState: 0
2017-11-10 16:39:36.633 o.a.s.d.s.Slot SLOT_6700 [INFO] STATE EMPTY msInState: 53 -> WAITING_FOR_BLOB_LOCALIZATION msInState: 0
</pre>
</div></div>

<p>Looks like 6700 was the bottleneck (as it was only in that state for 53 ms, not the 3 mins of the others).</p>

<p>It was waiting for 3 mins to kill another worker.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2017-11-10 16:39:36.580 o.a.s.d.s.Slot SLOT_6700 [INFO] STATE KILL msInState: 179992 topo:TumblingWindowTestt500-18-1510353319 worker:<span class="code-keyword">null</span> -> EMPTY msInState: 0
</pre>
</div></div>

<p>Which looks a bit like turtles all they way down.  It appears that the 3 min timeout for both is causing them to just miss each other.  Where the supervisor gets in a bad state that takes 3 mins to recover from, but then the test times out after 3 mins and kills the topology which causes the next topology to wait 3 mins to be launched....</p>

<p>I'll see if I can find the first one with issues. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I am seeing a lot of transitions in there to updating the blob.  My guess is that the blob changes right before it is killed (a.k.a it is deleted).  This is causing extra transitions to happen and slowing everything down.  Possibly even confusing the slot so it is stuck waiting for some timeout to happen.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>I also found the following killing off the supervisor that needs to be fixed, but I have to go so I may not be able to work on this more until tonight.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2017-11-13 08:54:22.597 o.a.s.d.s.Slot SLOT_6703 [ERROR] Error when processing event
java.io.FileNotFoundException: File <span class="code-quote">'/.../storm-local/supervisor/stormdist/SlidingWindowTestw2s5-4-1510584685/stormconf.ser'</span> does no
t exist
at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:292) ~[commons-io-2.5.jar:2.5]
at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1815) ~[commons-io-2.5.jar:2.5]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfGivenPath(ConfigUtils.java:269) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfImpl(ConfigUtils.java:425) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConf(ConfigUtils.java:264) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.localizer.AsyncLocalizer.getLocalResources(AsyncLocalizer.java:332) ~[storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.localizer.AsyncLocalizer.releaseSlotFor(AsyncLocalizer.java:496) ~[storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.supervisor.Slot.handleWaitingForBlobLocalization(Slot.java:632) ~[storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:391) ~[storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:1120) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>So it appears to be something related to the AsyncLocallizer checking if a blob is fully downloaded as part of the periodic check to see if it has changed.  When I comment out that part everything works fine, except if the files get deleted part way through the supervisor will not recover.  I am not totally sure why this is the case, but I am going to try to dig into it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>OK I found it, and what a bug it is.  When checking to see if the topology jar was fully downloaded it was verifying that the resources subdirectory was created and exists.  But for this particular jar there is no resources subdirectory within the jar.  So it is never extracted.  So every 30 seconds the worker processes are killed and restarted.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>,</p>

<p>I just put up a pull request that I think fixes this.  Thanks for helping to debug it.</p>
