### ISSUE TITLE
[STORM-2811] Nimbus may throw NPE if the same topology is killed multiple times, and the integration test kills the same topology multiple times

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6593]
<blockquote>
<p>2017-11-12 08:45:50.353 o.a.s.d.n.Nimbus pool-14-thread-47 <span class="error">&#91;WARN&#93;</span> Kill topology exception. (topology name='SlidingWindowTest-window20-slide10')<br/>
java.lang.NullPointerException: null<br/>
	at org.apache.storm.cluster.IStormClusterState.getTopoId(IStormClusterState.java:171) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.daemon.nimbus.Nimbus.tryReadTopoConfFromName(Nimbus.java:1970) ~<span class="error">&#91;storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.daemon.nimbus.Nimbus.killTopologyWithOpts(Nimbus.java:2760) ~<span class="error">&#91;storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Processor$killTopologyWithOpts.getResult(Nimbus.java:3226) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Processor$killTopologyWithOpts.getResult(Nimbus.java:3210) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~<span class="error">&#91;libthrift-0.10.0.jar:0.10.0&#93;</span><br/>
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~<span class="error">&#91;libthrift-0.10.0.jar:0.10.0&#93;</span><br/>
	at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:167) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) ~<span class="error">&#91;libthrift-0.10.0.jar:0.10.0&#93;</span><br/>
	at org.apache.thrift.server.Invocation.run(Invocation.java:18) ~<span class="error">&#91;libthrift-0.10.0.jar:0.10.0&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_144&#93;</span></p></blockquote>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2811" target="_blank">Nimbus may throw NPE if the same topology is killed multiple times, and the integration test kills the same topology multiple times</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-11-13T23:28:24+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>, I also merged into 1.x and 1.1.x branches.</p>
