### ISSUE TITLE
[STORM-2847] Exception thrown after rebalance IllegalArgumentException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6629]
<p>After rebalance the storm-kafka-client spout attempts to check the current position of partitions that are no longer assigned to the current spout. This occurs in a topology with multiple spout instances.</p>

<p>java.lang.IllegalArgumentException: You can only check the position for partitions assigned to this consumer. at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1262) at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:473)</p>

---
<details><summary><i>Originally reported by <a title="Evan Rosebrook" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2847" target="_blank">Exception thrown after rebalance IllegalArgumentException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-12-21T17:29:04+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> This is all I have at the moment. If you need more I can get that for you tomorrow. It was on the latest commit as of this morning.</p>

<p>java.lang.IllegalArgumentException: You can only check the position for partitions assigned to this consumer. at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1262) at org.apache.storm.kafka.spout.KafkaSpout.emitTupleIfNotEmitted(KafkaSpout.java:328) at org.apache.storm.kafka.spout.KafkaSpout.emit(KafkaSpout.java:309) at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:233) at org.apache.storm.daemon.executor$fn_<em>4976$fn</em><em>4991$fn</em><em>5022.invoke(executor.clj:644) at org.apache.storm.util$async_loop$fn</em>_557.invoke(util.clj:484) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a> Those line numbers don't match up with the line numbers from 1.x-branch (the 1.2.0 branch). See for example <a href="https://github.com/apache/storm/blob/1.x-branch/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L328" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/1.x-branch/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L328</a> which is supposed to be where emitTupleIfNotEmitted starts according to the stack trace. We haven't merged anything to storm-kafka-client since a few days ago as far as I know. I checked 1.1.x-branch, 1.0.x-branch and master as well (1.0.6, 1.1.2 and 2.0.0 respectively) and the line numbers don't match up to your stack trace either.</p>

<p>I'm assuming the new stack trace is unrelated to the original, since the new trace doesn't contain org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:473)?</p>

<p>It would be good if you could find the commit hash you built from.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a> I believe I have a fix ready for this. Would you be willing to try it out? You can get it from <a href="https://github.com/srdo/storm/tree/STORM-2847-1.x" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/srdo/storm/tree/STORM-2847-1.x</a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> I Tried your branch and got an error. Apparently the partitions provided to onPartitionsRevoked can be empty. I was able to resolve this by adding " && partitions.size() > 0" to line 152.</p>

<p>Partitions revoked. [consumer-group=MyStormTopology, consumer=org.apache.kafka.clients.consumer.KafkaConsumer@2ada06e4, topic-partitions=[]]<br/>
2017-12-11 15:21:19.908 o.a.s.k.s.KafkaSpout Thread-34-uisspout-executor<span class="error">&#91;703 703&#93;</span> <span class="error">&#91;DEBUG&#93;</span> Offsets successfully committed to Kafka [{uis-12=OffsetAndMetadata{offset=6606783674, metadata='</p>
{topic-partition=uis-12, offset=6606783673, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-28=OffsetAndMetadata{offset=4262625500, metadata='</p>
{topic-partition=uis-28, offset=4262625499, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-44=OffsetAndMetadata{offset=4263152272, metadata='</p>
{topic-partition=uis-44, offset=4263152271, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-60=OffsetAndMetadata{offset=3855749917, metadata='</p>
{topic-partition=uis-60, offset=3855749916, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-76=OffsetAndMetadata{offset=3196437627, metadata='</p>
{topic-partition=uis-76, offset=3196437626, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-92=OffsetAndMetadata{offset=3209173441, metadata='</p>
{topic-partition=uis-92, offset=3209173440, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}}]<br/>
	at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:467) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.access$400(KafkaSpout.java:59) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout$KafkaSpoutConsumerRebalanceListener.onPartitionsRevoked(KafkaSpout.java:154) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.subscribeKafkaConsumer(KafkaSpout.java:564) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.activate(KafkaSpout.java:555) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:467) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.access$400(KafkaSpout.java:59) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout$KafkaSpoutConsumerRebalanceListener.onPartitionsRevoked(KafkaSpout.java:154) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.subscribeKafkaConsumer(KafkaSpout.java:564) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.activate(KafkaSpout.java:555) ~<span class="error">&#91;stormjar.jar:local&#93;</span></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a> Thanks for testing it. I've updated the branch I linked earlier, please try again if you can. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p>Looks good <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>. I am no longer seeing any exception when manually triggering a rebalance. Nice work!</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2710%20label%3Aepic">STORM-2710</a>]</i>
