### ISSUE TITLE
[STORM-2851] org.apache.storm.kafka.spout.KafkaSpout.doSeekRetriableTopicPartitions sometimes throws ConcurrentModificationException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6633]
<p>Hello,</p>

<p>We have been running Storm 1.2.0 preview on our pre-production supervision system.<br/>
We noticed that in the logs of our topology to logs persistency in Hbase, we got the following exceptions (about 4 times in a 48 hours period):</p>

<p>java.util.ConcurrentModificationException at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) <br/>
at java.util.HashMap$KeyIterator.next(HashMap.java:1466) <br/>
at org.apache.storm.kafka.spout.KafkaSpout.doSeekRetriableTopicPartitions(KafkaSpout.java:347) <br/>
at org.apache.storm.kafka.spout.KafkaSpout.pollKafkaBroker(KafkaSpout.java:320) <br/>
at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:245) <br/>
at org.apache.storm.daemon.executor$fn_<em>4963$fn</em><em>4978$fn</em>_5009.invoke(executor.clj:647) <br/>
at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:484) <br/>
at clojure.lang.AFn.run(AFn.java:22) <br/>
at java.lang.Thread.run(Thread.java:748) </p>

<p>It looks like there's something to fix here, such as making the map thread-safe, or managing the exclusivity of modification of this map at a caller level.</p>

<p>Note: this topology is using Storm Kafka Client spout with default properties (unlike other topologies we have based on autocommit). However, it's the one which deals with highest rate of messages (line of logs coming from about 10000 VMs, a nice scale test for Storm <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/>)</p>

<p>Could it be fixed in Storm 1.2.0 final version?</p>

<p>Best regards,<br/>
Alexandre Vermeerbergen</p>

---
<details><summary><i>Originally reported by <a title="Alexandre Vermeerbergen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2851" target="_blank">org.apache.storm.kafka.spout.KafkaSpout.doSeekRetriableTopicPartitions sometimes throws ConcurrentModificationException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-12-16T08:38:02+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2710%20label%3Aepic">STORM-2710</a>]</i>
