### ISSUE TITLE
[STORM-2878] Supervisor collapse continuously when there is a expired assignment for overdue storm

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6660]
<p>For now, when a topology is reassigned or killed for a cluster, supervisor will delete 4 files for an overdue storm:</p>
<ul class="alternate" type="square">
	<li>storm-code</li>
	<li>storm-ser</li>
	<li>storm-jar</li>
	<li>LocalAssignment</li>
</ul>

<p>Slot.java<br/>
static DynamicState cleanupCurrentContainer(DynamicState dynamicState, StaticState staticState, MachineState nextState) throws Exception {<br/>
assert(dynamicState.container != null);<br/>
assert(dynamicState.currentAssignment != null);<br/>
assert(dynamicState.container.areAllProcessesDead());</p>

<p>dynamicState.container.cleanUp();<br/>
staticState.localizer.releaseSlotFor(dynamicState.currentAssignment, staticState.port);<br/>
DynamicState ret = dynamicState.withCurrentAssignment(null, null);<br/>
if (nextState != null) </p>
{
    ret = ret.withState(nextState);
}
<p>return ret;<br/>
    }</p>

<p>But we do not make a transaction to do this, if an exception occurred during deleting storm-code/ser/jar, an overdue local assignment will be left on disk.</p>

<p>Then when supervisor restart from the exception above, the slots will be initial and container will be recovered from LocalAssignments, the blob store will fetch the files from Nimbus/Master, but will get a KeyNotFoundException, and supervisor collapses again.</p>

<p>This will happens continuously and supervisor will never recover until we clean up all the local assignments manually.</p>

<p>This is the stack:<br/>
2017-12-27 14:15:04.434 o.a.s.l.AsyncLocalizer <span class="error">&#91;INFO&#93;</span> Cleaning up unused topologies in /opt/meituan/storm/data/supervisor/stormdist<br/>
2017-12-27 14:15:04.434 o.a.s.d.s.AdvancedFSOps <span class="error">&#91;INFO&#93;</span> Deleting path /opt/meituan/storm/data/supervisor/stormdist/app_dpsr_realtime_shop_vane_allcates-14-1513685785<br/>
2017-12-27 14:15:04.445 o.a.s.d.s.Slot <span class="error">&#91;INFO&#93;</span> STATE EMPTY msInState: 109 -> WAITING_FOR_BASIC_LOCALIZATION msInState: 1<br/>
2017-12-27 14:15:04.471 o.a.s.d.s.Supervisor <span class="error">&#91;INFO&#93;</span> Starting supervisor with id 255d3fed-f3ee-4c7e-8a08-b693c9a6a072 at host gq-data-rt48.gq.sankuai.com.<br/>
2017-12-27 14:15:04.502 o.a.s.u.Utils <span class="error">&#91;ERROR&#93;</span> An exception happened while downloading /opt/meituan/storm/data/supervisor/tmp/ca4f8174-59be-40a4-b431-dbc8b697f063/stormjar.jar from blob store.<br/>
org.apache.storm.generated.KeyNotFoundException: null<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26656) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26624) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result.read(Nimbus.java:26555) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.recv_beginBlobDownload(Nimbus.java:864) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.beginBlobDownload(Nimbus.java:851) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.blobstore.NimbusBlobStore.getBlob(NimbusBlobStore.java:357) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorAttempt(Utils.java:598) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorImpl(Utils.java:582) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisor(Utils.java:574) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.downloadBaseBlobs(AsyncLocalizer.java:123) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:148) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:101) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~<span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
2017-12-27 14:15:04.611 o.a.s.u.Utils <span class="error">&#91;ERROR&#93;</span> An exception happened while downloading /opt/meituan/storm/data/supervisor/tmp/ca4f8174-59be-40a4-b431-dbc8b697f063/stormjar.jar from blob store.<br/>
org.apache.storm.generated.KeyNotFoundException: null<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26656) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26624) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result.read(Nimbus.java:26555) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.recv_beginBlobDownload(Nimbus.java:864) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.beginBlobDownload(Nimbus.java:851) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.blobstore.NimbusBlobStore.getBlob(NimbusBlobStore.java:357) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorAttempt(Utils.java:598) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorImpl(Utils.java:582) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisor(Utils.java:574) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.downloadBaseBlobs(AsyncLocalizer.java:123) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:148) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:101) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~<span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
2017-12-27 14:15:04.718 o.a.s.u.Utils <span class="error">&#91;ERROR&#93;</span> An exception happened while downloading /opt/meituan/storm/data/supervisor/tmp/ca4f8174-59be-40a4-b431-dbc8b697f063/stormcode.ser from blob store.<br/>
org.apache.storm.generated.KeyNotFoundException: null<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26656) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26624) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result.read(Nimbus.java:26555) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.recv_beginBlobDownload(Nimbus.java:864) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.beginBlobDownload(Nimbus.java:851) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.blobstore.NimbusBlobStore.getBlob(NimbusBlobStore.java:357) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorAttempt(Utils.java:598) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorImpl(Utils.java:582) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisor(Utils.java:574) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.downloadBaseBlobs(AsyncLocalizer.java:124) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:148) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:101) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~<span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
2017-12-27 14:15:04.825 o.a.s.u.Utils <span class="error">&#91;ERROR&#93;</span> An exception happened while downloading /opt/meituan/storm/data/supervisor/tmp/ca4f8174-59be-40a4-b431-dbc8b697f063/stormcode.ser from blob store.<br/>
org.apache.storm.generated.KeyNotFoundException: null<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26656) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26624) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result.read(Nimbus.java:26555) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.recv_beginBlobDownload(Nimbus.java:864) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.beginBlobDownload(Nimbus.java:851) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.blobstore.NimbusBlobStore.getBlob(NimbusBlobStore.java:357) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorAttempt(Utils.java:598) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorImpl(Utils.java:582) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisor(Utils.java:574) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.downloadBaseBlobs(AsyncLocalizer.java:124) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:148) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:101) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~<span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
2017-12-27 14:15:04.932 o.a.s.u.Utils <span class="error">&#91;ERROR&#93;</span> An exception happened while downloading /opt/meituan/storm/data/supervisor/tmp/ca4f8174-59be-40a4-b431-dbc8b697f063/stormconf.ser from blob store.<br/>
org.apache.storm.generated.KeyNotFoundException: null<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26656) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26624) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result.read(Nimbus.java:26555) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.recv_beginBlobDownload(Nimbus.java:864) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.beginBlobDownload(Nimbus.java:851) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.blobstore.NimbusBlobStore.getBlob(NimbusBlobStore.java:357) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorAttempt(Utils.java:598) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorImpl(Utils.java:582) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisor(Utils.java:574) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.downloadBaseBlobs(AsyncLocalizer.java:125) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:148) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:101) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~<span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
2017-12-27 14:15:05.039 o.a.s.u.Utils <span class="error">&#91;ERROR&#93;</span> An exception happened while downloading /opt/meituan/storm/data/supervisor/tmp/ca4f8174-59be-40a4-b431-dbc8b697f063/stormconf.ser from blob store.<br/>
org.apache.storm.generated.KeyNotFoundException: null<br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26656) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result$beginBlobDownload_resultStandardScheme.read(Nimbus.java:26624) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$beginBlobDownload_result.read(Nimbus.java:26555) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.recv_beginBlobDownload(Nimbus.java:864) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.beginBlobDownload(Nimbus.java:851) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.blobstore.NimbusBlobStore.getBlob(NimbusBlobStore.java:357) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorAttempt(Utils.java:598) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisorImpl(Utils.java:582) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.Utils.downloadResourcesAsSupervisor(Utils.java:574) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.downloadBaseBlobs(AsyncLocalizer.java:125) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:148) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBaseBlobsDistributed.call(AsyncLocalizer.java:101) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~<span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
2017-12-27 14:15:05.140 o.a.s.u.Utils <span class="error">&#91;INFO&#93;</span> Could not extract resources from /opt/meituan/storm/data/supervisor/tmp/ca4f8174-59be-40a4-b431-dbc8b697f063/stormjar.jar<br/>
2017-12-27 14:15:05.142 o.a.s.d.s.Slot <span class="error">&#91;INFO&#93;</span> STATE WAITING_FOR_BASIC_LOCALIZATION msInState: 697 -> WAITING_FOR_BLOB_LOCALIZATION msInState: 0<br/>
2017-12-27 14:15:05.142 o.a.s.l.AsyncLocalizer <span class="error">&#91;WARN&#93;</span> Caught Exception While Downloading (rethrowing)... <br/>
java.io.FileNotFoundException: File '/opt/meituan/storm/data/supervisor/stormdist/app_dpsr_realtime_shop_vane_allcates-14-1513685785/stormconf.ser' does not exist<br/>
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:292) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1815) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfGivenPath(ConfigUtils.java:264) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfImpl(ConfigUtils.java:376) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.utils.ConfigUtils.readSupervisorStormConf(ConfigUtils.java:370) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBlobs.call(AsyncLocalizer.java:226) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer$DownloadBlobs.call(AsyncLocalizer.java:213) ~<span class="error">&#91;storm-core-1.1.2-mt001.jar:?&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~<span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.7.0_76&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.7.0_76&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Danny Chen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=danny0405">danny0405</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2878" target="_blank">Supervisor collapse continuously when there is a expired assignment for overdue storm</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Danny Chen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=danny0405">danny0405</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2018-02-19T22:49:36+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2879">STORM-2879</a>]</i>
