### ISSUE TITLE
[STORM-2881] Storm-druid topologies fail with NoSuchMethodError

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6663]
<p>Deploy a sample topology with storm-druid (E.g. the SampleDruidBoltTopology available in the storm git repo). The worker crashes with below error:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>
2017-12-28 15:47:36.382 o.a.s.util Thread-11-113-Violation-Events-Cube-executor9 9 ERROR Async loop died!
java.lang.NoSuchMethodError: org.apache.curator.framework.api.CreateBuilder.creatingParentsIfNeeded()Lorg/apache/curator/framework/api/ProtectACLCreateModePathAndBytesable;
at com.metamx.tranquility.beam.ClusteredBeam$$anonfun$com$metamx$tranquility$beam$ClusteredBeam$$zpathWithDefault$1.apply(ClusteredBeam.scala:125) ~dep-org.apache.storm-storm-druid-jar-1.2.0.3.1.0.0-420.jar.1514384427000:1.2.0.3.1.0.0-420
at com.metamx.tranquility.beam.ClusteredBeam$$anonfun$com$metamx$tranquility$beam$ClusteredBeam$$zpathWithDefault$1.apply(ClusteredBeam.scala:122) ~dep-org.apache.storm-storm-druid-jar-1.2.0.3.1.0.0-420.jar.1514384427000:1.2.0.3.1.0.0-420
at com.metamx.common.scala.Predef$EffectOps.withEffect(Predef.scala:44) ~dep-org.apache.storm-storm-druid-jar-1.2.0.3.1.0.0-420.jar.1514384427000:1.2.0.3.1.0.0-420
at 
</pre>
</div></div>

<p>storm-druid has dependency on curator 2.6.0, but the storm parent pom has defined 4.0.0 version in the dependency Management.</p>

<p>Due to this storm-druid is inheriting the 4.0.0 version of curator and including that version in the jar.</p>

<p>If we explicitly mention the curator dependency in the storm-druid pom.xml, this can be addressed.</p>

---
<details><summary><i>Originally reported by <a title="Arun Mahadevan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan">arunmahadevan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2881" target="_blank">Storm-druid topologies fail with NoSuchMethodError</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Arun Mahadevan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan">arunmahadevan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-01-05T15:51:35+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>I merged this into 1.x-branch first.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan" class="user-hover" rel="arunmahadevan">Arun Mahadevan</a><br/>
Assuming we may not resolve this for master branch soon for better fix, it might be better to clone the issue for master branch and mark this as resolved. Because when we're releasing Storm 1.2.0 having opened issue for 1.2.0 will not make sense. WDYT?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan">arunmahadevan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a>, clone for 2.0 - <a href="https://issues.apache.org/jira/browse/STORM-2884" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-2884</a> so that we can resolve this bug.</p>
