### ISSUE TITLE
[STORM-2892] Flux test fails to parse valid PATH environment variable

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6674]
<p>The flux tests rely on substituting the <tt>PATH</tt> environment variable into the <a href="https://github.com/apache/storm/blob/466a7ad74da27c1250eedf412a487db409e42c19/flux/flux-core/src/test/resources/configs/substitution-test.yaml#L44-L45" class="external-link" target="_blank" rel="nofollow noopener"><tt>substitution-test.yaml</tt></a> file.</p>

<p>I noticed that the tests were failing when my <tt>PATH</tt> had a trailing colon, despite that being a valid <tt>PATH</tt> [1].</p>

<h2><a name="Existingerror"></a>Existing error</h2>

<div class="code panel" style="border-width: 1px;"><div class="codeHeader panelHeader" style="border-bottom-width: 1px;"><b>mvn test output</b></div><div class="codeContent panelContent">
<pre class="code-java">
Running org.apache.storm.flux.TCKTest
Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.852 sec <<< FAILURE! - in org.apache.storm.flux.TCKTest
testVariableSubstitution(org.apache.storm.flux.TCKTest)  Time elapsed: 0.012 sec  <<< ERROR!
org.yaml.snakeyaml.scanner.ScannerException: <span class="code-keyword">null</span>; mapping values are not allowed here;  in <span class="code-quote">'string'</span>, line 45, column 890:
     ... /usr/local/bin:/usr/bin:
^
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:866)
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
at org.yaml.snakeyaml.Yaml.load(Yaml.java:400)
at org.apache.storm.flux.parser.FluxParser.loadYaml(FluxParser.java:121)
at org.apache.storm.flux.parser.FluxParser.parseInputStream(FluxParser.java:75)
at org.apache.storm.flux.parser.FluxParser.parseResource(FluxParser.java:59)
at org.apache.storm.flux.TCKTest.testVariableSubstitution(TCKTest.java:224)

Results :

Tests in error: 
  TCKTest.testVariableSubstitution:224 » Scanner <span class="code-keyword">null</span>; mapping values are not al...
</pre>
</div></div>

<h2><a name="Proposedsolution"></a>Proposed solution</h2>

<p>Just wrap the <tt>PATH</tt> variable's contents in the yaml file.</p>

<h3><a name="%5C1PATHvalidity"></a>[1] PATH validity</h3>

<div class="code panel" style="border-width: 1px;"><div class="codeHeader panelHeader" style="border-bottom-width: 1px;"><b>man bash</b></div><div class="codeContent panelContent">
<pre class="code-java">
...

       PATH   The  search  path  <span class="code-keyword">for</span>  commands.  It is a colon-separated
      list of directories in which the shell looks <span class="code-keyword">for</span>  commands
      (see  COMMAND  EXECUTION  below).   A  zero-length  (<span class="code-keyword">null</span>)
      directory name in the value of PATH indicates the  current
      directory.   A <span class="code-keyword">null</span> directory name may appear as two adja-
      cent colons, or as an  initial  or  trailing  colon.   The
      <span class="code-keyword">default</span> path is system-dependent, and is set by the admin-
      istrator  who  installs   bash.    A   common   value   is
      ``/usr/gnu/bin:/usr/local/bin:/usr/ucb:/bin:/usr/bin''.
...
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Erik Weathers" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erikdw">erikdw</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2892" target="_blank">Flux test fails to parse valid PATH environment variable</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Erik Weathers" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erikdw">erikdw</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Trivial
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-01-12T20:01:56+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erikdw">erikdw</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>: sorry, missed this comment to the ticket.  I'm fine with whatever you had to do for merging it back, thanks!</p>
