### ISSUE TITLE
[STORM-2903] Fix possible NullPointerException in AbstractAutoCreds

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6685]
<p>Observed below exception while testing Hive token mechanism.</p>

<p>    ```<br/>
    Caused by: java.lang.NullPointerException<br/>
            at org.apache.storm.common.AbstractAutoCreds.addTokensToUGI(AbstractAutoCreds.java:219) ~<span class="error">&#91;storm-autocreds-1.2.0.3.1.0.0-526.jar:1.2.0.3.1.0.0-526&#93;</span><br/>
            at org.apache.storm.common.AbstractAutoCreds.populateSubject(AbstractAutoCreds.java:118) ~<span class="error">&#91;storm-autocreds-1.2.0.3.1.0.0-526.jar:1.2.0.3.1.0.0-526&#93;</span><br/>
            at org.apache.storm.security.auth.AuthUtils.populateSubject(AuthUtils.java:228) ~<span class="error">&#91;storm-core-1.2.0.3.1.0.0-526.jar:1.2.0.3.1.0.0-526&#93;</span><br/>
            ... 10 more<br/>
    2018-01-19 16:23:26.157 o.a.s.util main <span class="error">&#91;ERROR&#93;</span> Halting process: ("Error on initialization")<br/>
    ```</p>

---
<details><summary><i>Originally reported by <a title="Manikumar" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=omkreddy">omkreddy</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2903" target="_blank">Fix possible NullPointerException in AbstractAutoCreds</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Manikumar" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=omkreddy">omkreddy</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-01-21T23:43:00+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=omkreddy" class="user-hover" rel="omkreddy">Manikumar</a>, I merged into master and 1.x-branch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Also merged follow up patches.</p>
