### ISSUE TITLE
[STORM-2905] Supervisor still downloads storm blob files when the topology was killed.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6687]
<p>When we kill a topology, at the moment of topology blob-files be removed, Supervisor executor still request blob-files and get an KeyNotFoundException.</p>

<p>I stepped in and found the reason:<br/>
1. We do not add a guarded lock on `topologyBlobs` of AsyncLocalizer which is singleton to a supervisor node.<br/>
2. And we remove jar/code/conf blob keys in `topologyBlobs` of killed storm only in a timer task: cleanUp() method of AsyncLocalizer, the remove condition is :<span class="error">&#91;no one reference the blobs&#93;</span> AND [ blobs removed by master OR exceeds the max configured size ], the default scheduling interval is 30 seconds.<br/>
3. When we kill a storm on a node[ which means that the slot container are empty], the AsyncLocalizer will do: releaseSlotFor, which only remove reference on the blobs <span class="error">&#91;topologyBlobs keys are still there.&#93;</span><br/>
4. Then the container is empty, and Slot.java will do: cleanupCurrentContainer, which will invoke AsyncLocalizer #releaseSlotFor to release the slot.<br/>
5. AsyncLocalizer have a timer task: updateBlobs to update base/user blobs every 30 seconds, which based on the AsyncLocalizer#`topologyBlobs`<br/>
6. We know that AsyncLocalizer#`topologyBlobs` overdue keys are only removed by its AsyncLocalizer#cleanUp which is also a timer task.<br/>
7. So when we kill a storm, AsyncLocalizer#updateBlobs will update based on a removed jar/code/conf blob-key and fire a exception, then retried until the configured max times to end.</p>

<p>Here is how i fixed it:<br/>
1. just remove the base blob keys eagerly when we do AsyncLocalizer #releaseSlotFor when there is no reference <span class="error">&#91;no one used&#93;</span> on the blobs, and remove the overdue keys in AsyncLocalizer#`topologyBlobs`<br/>
2. Guard the AsyncLocalizer#updateBlobs and AsyncLocalizer #releaseSlotFor on the same lock.<br/>
3. When container is empty, we do not need to exec AsyncLocalizer #releaseSlotFor<span class="error">&#91;because we have already deleted them&#93;</span>.<br/>
4. I also add a new RPC api for decide if there exists a remote blob, we can use it to decide it the blob could be removed instead of use getBlobMeta and catch an confusing KeyNotFoundException <span class="error">&#91;both on supervisors and master log for every base blobs&#93;</span>.</p>

<p>This is the partial of Supervisor log:</p>

<p>2018-03-31 13:41:17.089 o.a.s.d.s.AdvancedFSOps SLOT_6700 <span class="error">&#91;INFO&#93;</span> Deleting path /Users/danny0405/workspace/storm-2.x-test/supervisor1/apache-storm-2.0.0-SNAPSHOT/storm-local/workers/b50aa089-6584-498e-a5cc-85cba13e4cb0/pids/1115<br/>
 2018-03-31 13:41:17.090 o.a.s.d.s.AdvancedFSOps SLOT_6700 <span class="error">&#91;INFO&#93;</span> Deleting path /Users/danny0405/workspace/storm-2.x-test/supervisor1/apache-storm-2.0.0-SNAPSHOT/storm-local/workers/b50aa089-6584-498e-a5cc-85cba13e4cb0/heartbeats<br/>
 2018-03-31 13:41:17.102 o.a.s.d.s.AdvancedFSOps SLOT_6700 <span class="error">&#91;INFO&#93;</span> Deleting path /Users/danny0405/workspace/storm-2.x-test/supervisor1/apache-storm-2.0.0-SNAPSHOT/storm-local/workers/b50aa089-6584-498e-a5cc-85cba13e4cb0/pids<br/>
 2018-03-31 13:41:17.102 o.a.s.d.s.AdvancedFSOps SLOT_6700 <span class="error">&#91;INFO&#93;</span> Deleting path /Users/danny0405/workspace/storm-2.x-test/supervisor1/apache-storm-2.0.0-SNAPSHOT/storm-local/workers/b50aa089-6584-498e-a5cc-85cba13e4cb0/tmp<br/>
 2018-03-31 13:41:17.102 o.a.s.d.s.AdvancedFSOps SLOT_6700 <span class="error">&#91;INFO&#93;</span> Deleting path /Users/danny0405/workspace/storm-2.x-test/supervisor1/apache-storm-2.0.0-SNAPSHOT/storm-local/workers/b50aa089-6584-498e-a5cc-85cba13e4cb0<br/>
 2018-03-31 13:41:17.103 o.a.s.d.s.Container SLOT_6700 <span class="error">&#91;INFO&#93;</span> REMOVE worker-user b50aa089-6584-498e-a5cc-85cba13e4cb0<br/>
 2018-03-31 13:41:17.103 o.a.s.d.s.AdvancedFSOps SLOT_6700 <span class="error">&#91;INFO&#93;</span> Deleting path /Users/danny0405/workspace/storm-2.x-test/supervisor1/apache-storm-2.0.0-SNAPSHOT/storm-local/workers-users/b50aa089-6584-498e-a5cc-85cba13e4cb0<br/>
 2018-03-31 13:41:17.104 o.a.s.d.s.BasicContainer SLOT_6700 <span class="error">&#91;INFO&#93;</span> Removed Worker ID b50aa089-6584-498e-a5cc-85cba13e4cb0<br/>
 2018-03-31 13:41:17.105 o.a.s.d.s.Slot SLOT_6700 <span class="error">&#91;INFO&#93;</span> STATE KILL msInState: 25 topo:word_count_fk_11-2-1522472558 worker:null -> EMPTY msInState: 0<br/>
 2018-03-31 13:41:17.105 o.a.s.d.s.Slot SLOT_6700 <span class="error">&#91;INFO&#93;</span> SLOT 6700: Changing current assignment from LocalAssignment(topology_id:word_count_fk_11-2-1522472558, executors:<span class="error">&#91;ExecutorInfo(task_start:7, task_end:7), ExecutorInfo(task_start:6, task_end:6), ExecutorInfo(task_start:5, task_end:5), ExecutorInfo(task_start:4, task_end:4), ExecutorInfo(task_start:3, task_end:3), ExecutorInfo(task_start:2, task_end:2), ExecutorInfo(task_start:1, task_end:1)&#93;</span>, resources:WorkerResources(mem_on_heap:896.0, mem_off_heap:0.0, cpu:70.0, shared_mem_on_heap:0.0, shared_mem_off_heap:0.0, resources:</p>
{offheap.memory.mb=0.0, onheap.memory.mb=896.0, cpu.pcore.percent=70.0}
<p>, shared_resources:{}), owner:danny0405) to null<br/>
 2018-03-31 13:41:18.001 o.a.s.d.s.t.SupervisorHealthCheck timer <span class="error">&#91;INFO&#93;</span> Running supervisor healthchecks...<br/>
 2018-03-31 13:41:18.002 o.a.s.h.HealthChecker timer <span class="error">&#91;INFO&#93;</span> The supervisor healthchecks succeeded.<br/>
 2018-03-31 13:41:36.837 o.a.s.l.AsyncLocalizer AsyncLocalizer Executor - 1 <span class="error">&#91;WARN&#93;</span> Failed to download blob LOCAL TOPO BLOB TOPO_JAR word_count_fk_11-2-1522472558 will try again in 100 ms<br/>
 org.apache.storm.generated.KeyNotFoundException: null<br/>
         at org.apache.storm.generated.Nimbus$getBlobMeta_result$getBlobMeta_resultStandardScheme.read(Nimbus.java:25225) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.generated.Nimbus$getBlobMeta_result$getBlobMeta_resultStandardScheme.read(Nimbus.java:25193) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.generated.Nimbus$getBlobMeta_result.read(Nimbus.java:25124) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
         at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~<span class="error">&#91;libthrift-0.9.3.jar:0.9.3&#93;</span><br/>
         at org.apache.storm.generated.Nimbus$Client.recv_getBlobMeta(Nimbus.java:825) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.generated.Nimbus$Client.getBlobMeta(Nimbus.java:812) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.blobstore.NimbusBlobStore.getBlobMeta(NimbusBlobStore.java:318) ~<span class="error">&#91;storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.localizer.LocallyCachedTopologyBlob.getRemoteVersion(LocallyCachedTopologyBlob.java:176) ~<span class="error">&#91;storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.localizer.AsyncLocalizer.lambda$downloadOrUpdate$5(AsyncLocalizer.java:249) ~<span class="error">&#91;storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT&#93;</span><br/>
         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) <span class="error">&#91;?:1.8.0_151&#93;</span><br/>
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) <span class="error">&#91;?:1.8.0_151&#93;</span><br/>
         at java.util.concurrent.FutureTask.run(FutureTask.java:266) <span class="error">&#91;?:1.8.0_151&#93;</span><br/>
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) <span class="error">&#91;?:1.8.0_151&#93;</span><br/>
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) <span class="error">&#91;?:1.8.0_151&#93;</span><br/>
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) <span class="error">&#91;?:1.8.0_151&#93;</span><br/>
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) <span class="error">&#91;?:1.8.0_151&#93;</span><br/>
         at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_151&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Danny Chen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=danny0405">danny0405</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2905" target="_blank">Supervisor still downloads storm blob files when the topology was killed.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Danny Chen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=danny0405">danny0405</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:53:55+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
