### ISSUE TITLE
[STORM-2934] Logviewer ClassNotFoundException validating configs

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6716]
<p>Caused by: java.lang.ClassNotFoundException: org.rocksdb.RocksDBException<br/>
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
at java.lang.Class.forName0(Native Method) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
at java.lang.Class.forName(Class.java:264) ~<span class="error">&#91;?:1.8.0_131&#93;</span><br/>
at org.apache.storm.validation.ConfigValidation$ImplementsClassValidator.validateField(ConfigValidation.java:587) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.validation.ConfigValidation.validateField(ConfigValidation.java:758) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.validation.ConfigValidation.validateFields(ConfigValidation.java:811) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.validation.ConfigValidation.validateFields(ConfigValidation.java:772) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.utils.ConfigUtils.readStormConfigImpl(ConfigUtils.java:397) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.utils.ConfigUtils.readStormConfig(ConfigUtils.java:136) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.daemon.logviewer.LogviewerServer.main(LogviewerServer.java:158) ~<span class="error">&#91;storm-webapp-2.0.0.y.jar:2.0.0.y&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2934" target="_blank">Logviewer ClassNotFoundException validating configs</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-02-07T20:26:49+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">Aaron Gresch</a>,</p>

<p>I merged this into master</p>
