### ISSUE TITLE
[STORM-2943] Binary distribution includes storm-kafka-monitor source/javadoc in toollib directory

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6725]
<p>Quoting Alexandre's RC3 vote:</p>

<p> </p>
<blockquote><p>I hate to be the one who always give bad news, but as a matter of<br/>
 facts, Storm 1.2.0 RC3 installation from binary artifacts (both<br/>
 apache-storm-1.2.0-src.tar.gz and apache-storm-1.2.0.zip) leads to "by<br/>
 default KO Kafka monitor" in Nimbus UI (which dirty exceptions in<br/>
 ui.log)</p>

<p>Here's for example what I get from apache-storm-1.2.0-src.tar.gz<br/>
 downloaded from<br/>
<a href="https://dist.apache.org/repos/dist/dev/storm/apache-storm-1.2.0-rc3/apache-storm-1.2.0-src.tar.gz" class="external-link" target="_blank" rel="nofollow noopener">https://dist.apache.org/repos/dist/dev/storm/apache-storm-1.2.0-rc3/apache-storm-1.2.0-src.tar.gz</a>:</p>

<p>$ tar ztvf apache-storm-1.2.0.tar.gz apache-storm-1.2.0/toollib<br/>
 -rwxrwxrwx ptgoetz/staff 16999 2018-02-06 21:22<br/>
 apache-storm-1.2.0/toollib/storm-kafka-monitor-1.2.0-sources.jar<br/>
 -rwxrwxrwx ptgoetz/staff 93461 2018-02-06 21:22<br/>
 apache-storm-1.2.0/toollib/storm-kafka-monitor-1.2.0-javadoc.jar<br/>
 -rwxrwxrwx ptgoetz/staff 21591320 2018-02-06 21:22<br/>
 apache-storm-1.2.0/toollib/storm-kafka-monitor-1.2.0.jar</p>

<p>And here's what I see in ui.log:</p>

<p> org.apache.storm.kafka.spout.KafkaSpout<br/>
 2018-02-07 16:49:57.153 o.a.s.u.TopologySpoutLag qtp1997623038-18<br/>
<span class="error">&#91;WARN&#93;</span> Exception message:Error: Could not find or load main class<br/>
 .usr.local.Storm.storm-stable.toollib.storm-kafka-monitor-1.2.0-javadoc.jar</p>

<p>org.apache.storm.utils.ShellUtils$ExitCodeException: Error: Could not<br/>
 find or load main class<br/>
 .usr.local.Storm.storm-stable.toollib.storm-kafka-monitor-1.2.0-javadoc.jar</p>

<p>        at org.apache.storm.utils.ShellUtils.runCommand(ShellUtils.java:231)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.utils.ShellUtils.run(ShellUtils.java:161)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.utils.ShellUtils$ShellCommandExecutor.execute(ShellUtils.java:371)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.utils.ShellUtils.execCommand(ShellUtils.java:461)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.utils.ShellUtils.execCommand(ShellUtils.java:444)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.utils.TopologySpoutLag.getLagResultForKafka(TopologySpoutLag.java:163)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.utils.TopologySpoutLag.getLagResultForNewKafkaSpout(TopologySpoutLag.java:189)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.utils.TopologySpoutLag.lag(TopologySpoutLag.java:57)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.ui.core$topology_lag.invoke(core.clj:805)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.ui.core$fn__9586.invoke(core.clj:1165)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.shade.compojure.core$make_route$fn__5979.invoke(core.clj:100)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.shade.compojure.core$if_route$fn__5967.invoke(core.clj:46)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.shade.compojure.core$if_method$fn__5960.invoke(core.clj:31)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.shade.compojure.core$routing$fn__5985.invoke(core.clj:113)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at clojure.core$some.invoke(core.clj:2570) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
         at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:113)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at clojure.lang.RestFn.applyTo(RestFn.java:139) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
         at clojure.core$apply.invoke(core.clj:632) ~<span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
         at org.apache.storm.shade.compojure.core$routes$fn__5989.invoke(core.clj:118)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.shade.ring.middleware.cors$wrap_cors$fn__8894.invoke(cors.clj:149)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__8841.invoke(json.clj:56)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__6621.invoke(multipart_params.clj:118)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__7904.invoke(reload.clj:22)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span><br/>
         at org.apache.storm.ui.helpers$requests_middleware$fn__6874.invoke(helpers.clj:52)<br/>
 ~<span class="error">&#91;storm-core-1.2.0.jar:1.2.0&#93;</span></p>

<p>Deleting the extraneous storm-kafka-monitor-1.2.0-sources.jar and<br/>
 storm-kafka-monitor-1.2.0-javadoc.jar file, then restarting Nimbus<br/>
 solves the issue.</p>

<p>However, binaries artifacts should be as clean as possible, isn't it ?</p></blockquote>
<p> </p>

---
<details><summary><i>Originally reported by <a title="Alexandre Vermeerbergen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2943" target="_blank">Binary distribution includes storm-kafka-monitor source/javadoc in toollib directory</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="P. Taylor Goetz" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2018-02-07T20:41:02+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptgoetz">ptgoetz</a>:</i>
<p>Duplicate of <a href="https://issues.apache.org/jira/browse/STORM-2942" title="Remove javadoc and source jars from toollib directory in binary distribution" class="issue-link" data-issue-key="STORM-2942"><del>STORM-2942</del></a></p>
