### ISSUE TITLE
[STORM-2979] WorkerHooks EOFException during run_worker_shutdown_hooks

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6761]
<p>Hi,</p>

<p>I'm trying to use the BaseWorkerHook but an exception is thrown after I killed the topology.</p>

<p>The issue is exactly the same as : <a href="http://user.storm.apache.narkive.com/uchOrwlH/workerhook-deserialization-problem" class="external-link" target="_blank" rel="nofollow noopener">http://user.storm.apache.narkive.com/uchOrwlH/workerhook-deserialization-problem</a></p>

<p>An extract of my code :</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-comment">// topology
</span><span class="code-keyword">final</span> TridentTopology topology = <span class="code-keyword">new</span> TridentTopology();
<span class="code-comment">// ... I skip all the topology configuration part
</span><span class="code-keyword">final</span> StormTopology topo = topology.build();

<span class="code-comment">// hook
</span><span class="code-keyword">final</span> BaseWorkerHook hook = <span class="code-keyword">new</span> BaseWorkerHook();
<span class="code-keyword">final</span> ByteBuffer serializedHook = ByteBuffer.wrap(Utils.javaSerialize(hook ));
topo.add_to_worker_hooks(hook);

<span class="code-comment">// submit topology
</span>LocalCluster cluster = <span class="code-keyword">new</span> LocalCluster();
cluster.submitTopology(name,config,topo);
Utils.sleep(60000);

<span class="code-comment">// kill topology
</span><span class="code-keyword">final</span> KillOptions killOptions = <span class="code-keyword">new</span> KillOptions();
killOptions.set_wait_secs(0);
cluster.killTopologyWithOpts(name, killOptions);
Utils.sleep(10000);
cluster.shutdown();
</pre>
</div></div>
<p> </p>

<p>I have the following error :</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.RuntimeException: java.io.EOFException
    at org.apache.storm.utils.Utils.javaDeserialize(Utils.java:254)
    at org.apache.storm.daemon.worker$run_worker_shutdown_hooks$iter__5456__5460$fn__5461.invoke(worker.clj:578)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:507)
    at clojure.core$seq__4128.invoke(core.clj:137)
    at clojure.core$dorun.invoke(core.clj:3009)
    at clojure.core$doall.invoke(core.clj:3025)
    at org.apache.storm.daemon.worker$run_worker_shutdown_hooks.invoke(worker.clj:576)
    at org.apache.storm.daemon.worker$fn__5471$exec_fn__1371__auto__$reify__5473$shutdown_STAR___5493.invoke(worker.clj:693)
    at org.apache.storm.daemon.worker$fn__5471$exec_fn__1371__auto__$reify$reify__5519.shutdown(worker.clj:706)
    at org.apache.storm.ProcessSimulator.killProcess(ProcessSimulator.java:67)
    at org.apache.storm.daemon.supervisor.LocalContainer.kill(LocalContainer.java:59)
    at org.apache.storm.daemon.supervisor.Slot.killContainerForChangedAssignment(Slot.java:311)
    at org.apache.storm.daemon.supervisor.Slot.handleRunning(Slot.java:527)
    at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:265)
    at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:741)
Caused by: java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:864)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:360)
    at org.apache.storm.utils.Utils.javaDeserialize(Utils.java:245)
    ... 16 more
</pre>
</div></div>
<p> </p>

<p>Maybe it is related to log4j shutdown hooks (<a href="https://issues.apache.org/jira/browse/STORM-2176" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-2176</a>) so I tried to disable the hook in my src/test/resources/log4j2.xml.</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<Configuration monitorInterval=<span class="code-quote">"60"</span> shutdownHook=<span class="code-quote">"disable"</span>>
    <Appenders>
        <Console name=<span class="code-quote">"Console"</span> target=<span class="code-quote">"SYSTEM_OUT"</span>>
            <PatternLayout pattern=<span class="code-quote">"%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"</span> />
        </Console>
    </Appenders>

    <Loggers>
        <Root level=<span class="code-quote">"debug"</span>>
            <AppenderRef ref=<span class="code-quote">"Console"</span> />
        </Root>
    </Loggers>
</Configuration>
</pre>
</div></div>
<p>But it does not change anything.</p>

<p> </p>

<p>Of course the purpose of my work is to use my own worker hook extending the BaseWorkerHook.</p>

<p> </p>

<p> </p>

<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Robin Perice" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robin.perice">robin.perice</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2979" target="_blank">WorkerHooks EOFException during run_worker_shutdown_hooks</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Michel hummel" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hummelm">hummelm</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-04-11T13:51:21+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hummel.michel@gmail.com">hummel.michel@gmail.com</a>:</i>
<p>The issue seems to be related with the use if a ByteBuffer to store the serialized workerhook.<br/>
 The byteBuffer is deserialized two time:</p>
<ul>
	<li>On start</li>
	<li>On Stop</li>
</ul>


<p>On worker start, the worker retrieves the byte array of the ByteBuffer and the position on the ByteBuffer is then at the end of the ByteBuffer.<br/>
 On worker stop, the worker retrieves the byte array of the ByteBuffer but its position is at the end of the bytebuffer.</p>

<p>There multiple way to fix this issue:</p>
<ul>
	<li>in worker.clj run-worker-start-hooks, store and reset the Bytebuffer position after the workerhook start.</li>
</ul>


<p>This is the purpose of my commit: <a href="https://github.com/hummelm/storm/commit/7afeff6d8db4a78250ff8827207e80247b0acd25" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/hummelm/storm/commit/7afeff6d8db4a78250ff8827207e80247b0acd25</a></p>

<p> </p>
<ul>
	<li>Add a method to the Utils class to allow the retreiving of a byteArray from byteBuffer without changing the internal position of the byteBuffer and use it in the worker.clj</li>
</ul>


<p>May be a storm developer can give us an advice on the better way to fix the issue, it is a blocking issue for us and we will be happy to contibute to storm.</p>

<p> </p>

<p>One thing is strange, the ByteBuffer seems to contain more data than expected, I mean the serialized workerhook is about 106 Bytes and the buffer position is more than 2800.</p>

<p>In any case, the submitted fix is not impacted by this question.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hummelm" class="user-hover" rel="hummelm">Michel hummel</a>, I merged into master, 1.x for 1.2.2, 1.1.x for 1.1.3, 1.0.x for 1.0.7.</p>
