### ISSUE TITLE
[STORM-2986] NPE from LogCleaner

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6768]
<p>So I set</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
logviewer.cleanup.interval.secs: 10
</pre>
</div></div>
<p>to start LogCleaner thread. But from logviewer.log:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2018-03-05 21:31:17.629 o.a.s.v.ConfigValidation main [WARN] storm.messaging.netty.max_retries is a deprecated config please see <span class="code-keyword">class </span>org.apache.storm.Config.STORM_MESSAGING_NETTY_MAX_RETRIES <span class="code-keyword">for</span> more information.
2018-03-05 21:31:17.650 o.a.s.d.l.LogviewerServer main [INFO] Starting Logviewer HTTP servers...
2018-03-05 21:31:17.684 o.e.j.u.log main [INFO] Logging initialized @2455ms to org.eclipse.jetty.util.log.Slf4jLog
2018-03-05 21:31:17.877 o.a.s.d.l.u.LogCleaner main [INFO] configured max total size of worker logs: 2 MB, max total size of worker logs per directory: 1 MB
2018-03-05 21:31:18.017 o.a.s.d.m.MetricsUtils main [INFO] Using statistics reporter plugin:org.apache.storm.daemon.metrics.reporters.JmxPreparableReporter
2018-03-05 21:31:18.022 o.a.s.d.l.u.LogCleaner logviewer-cleanup [ERROR] Exception <span class="code-keyword">while</span> cleaning up old log.
java.lang.NullPointerException: <span class="code-keyword">null</span>
at java.util.Arrays.stream(Arrays.java:5004) ~[?:1.8.0_131]
at org.apache.storm.daemon.logviewer.utils.LogCleaner.selectDirsForCleanup(LogCleaner.java:217) ~[storm-webapp-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.logviewer.utils.LogCleaner.run(LogCleaner.java:135) ~[storm-webapp-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.StormTimer$1.run(StormTimer.java:207) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:81) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
2018-03-05 21:31:18.024 o.a.s.d.m.r.JmxPreparableReporter main [INFO] Preparing...
2018-03-05 21:31:18.031 o.a.s.m.StormMetricsRegistry main [INFO] Started statistics report plugin...
2018-03-05 21:31:18.031 o.a.s.d.l.LogviewerServer main [INFO] Starting Logviewer...
2018-03-05 21:31:18.041 o.e.j.s.Server main [INFO] jetty-9.4.7.v20170914
2018-03-05 21:31:18.215 o.a.h.s.a.s.KerberosAuthenticationHandler main [INFO] Login using keytab /keytabs/HTTP.keytab, <span class="code-keyword">for</span> principal HTTP/persistmist.corp.ne1.yahoo.com
2018-03-05 21:31:20.832 o.h.v.i.u.Version main [INFO] HV000001: Hibernate Validator 5.3.4.Final
2018-03-05 21:31:21.215 o.e.j.s.h.ContextHandler main [INFO] Started o.e.j.s.ServletContextHandler@65bb9029{/,file:<span class="code-comment">///tmp/apache-storm-2.0.0-SNAPSHOT/<span class="code-keyword">public</span>/,AVAILABLE}
</span>2018-03-05 21:31:21.287 o.e.j.s.AbstractConnector main [INFO] Started ServerConnector@30506c0d{HTTP/1.1,[http/1.1]}{0.0.0.0:8000}
2018-03-05 21:31:21.288 o.e.j.s.Server main [INFO] Started @6060ms
2018-03-05 21:31:28.038 o.a.s.d.l.u.LogCleaner logviewer-cleanup [ERROR] Exception <span class="code-keyword">while</span> cleaning up old log.
java.lang.NullPointerException: <span class="code-keyword">null</span>
at java.util.Arrays.stream(Arrays.java:5004) ~[?:1.8.0_131]
at org.apache.storm.daemon.logviewer.utils.LogCleaner.selectDirsForCleanup(LogCleaner.java:217) ~[storm-webapp-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.daemon.logviewer.utils.LogCleaner.run(LogCleaner.java:135) ~[storm-webapp-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.StormTimer$1.run(StormTimer.java:207) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:81) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]</pre>
</div></div>
<p> </p>

<p>It's because there is no workers-artifacts directory at the very beginning before submitting any topologies.  Users can fix it by manually creating the directory. But it's better to have it solve fixed. </p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2986" target="_blank">NPE from LogCleaner</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-03-07T15:06:59+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks Ethan,</p>

<p> </p>

<p>I merged this into master.</p>
