### ISSUE TITLE
[STORM-2988] "Error on initialization of server mk-worker" when using org.apache.storm.metrics2.reporters.JmxStormReporter on worker

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6770]
<p>As per documentation, I configured metrics v2 in my storm.yaml using the following configuration:<br/>
 </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-yaml">
storm.metrics.<span class="code-keyword">reporters: </span>

  - <span class="code-keyword">class: </span><span class="code-quote">"org.apache.storm.metrics<span class="code-object">2</span>.reporters.JmxStormReporter"</span>
    <span class="code-keyword">daemons: </span>
- <span class="code-quote">"supervisor"</span>
- <span class="code-quote">"nimbus"</span>
- <span class="code-quote">"worker"</span>
    report.<span class="code-keyword">period: </span><span class="code-object">10</span>
    report.period.<span class="code-keyword">units: </span><span class="code-quote">"SECONDS"</span>
</pre>
</div></div>

<p>When I start nimbus and supervisors everything works properly, I can see metrics reported to JMX, and logs (for nimbus in this example) report:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2018-03-07 15:35:22.201 o.a.s.d.m.MetricsUtils main [INFO] Using statistics reporter plugin:org.apache.storm.daemon.metrics.reporters.JmxPreparableReporter
2018-03-07 15:35:22.203 o.a.s.d.m.r.JmxPreparableReporter main [INFO] Preparing...
2018-03-07 15:35:22.221 o.a.s.d.common main [INFO] Started statistics report plugin...
</pre>
</div></div>

<p>When I submit a topology, workers cannot initialize and report this error</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2018-03-07 15:39:19.136 o.a.s.d.worker main [INFO] Launching worker <span class="code-keyword">for</span> stp_topology-1-1520433551 on [... cut ...]
2018-03-07 15:39:19.169 o.a.s.m.StormMetricRegistry main [INFO] Starting metrics reporters...
2018-03-07 15:39:19.172 o.a.s.m.StormMetricRegistry main [INFO] Attempting to instantiate reporter class: org.apache.storm.metrics2.reporters.JmxStormReporter
2018-03-07 15:39:19.175 o.a.s.m.r.JmxStormReporter main [INFO] Preparing...
2018-03-07 15:39:19.182 o.a.s.d.worker main [ERROR] Error on initialization of server mk-worker
java.lang.IllegalArgumentException: Don't know how to convert {<span class="code-quote">"class"</span> <span class="code-quote">"org.apache.storm.metrics2.reporters.JmxStormReporter"</span>, <span class="code-quote">"daemons"</span> [<span class="code-quote">"supervisor"</span> <span class="code-quote">"nimbus"</span> <span class="code-quote">"worker"</span>], <span class="code-quote">"report.period"</span> 10, <span class="code-quote">"report.period.units"</span> <span class="code-quote">"SECONDS"</span>} + to <span class="code-object">String</span>
	at org.apache.storm.utils.Utils.getString(Utils.java:848) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.metrics2.reporters.JmxStormReporter.getMetricsJMXDomain(JmxStormReporter.java:70) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.metrics2.reporters.JmxStormReporter.prepare(JmxStormReporter.java:51) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.metrics2.StormMetricRegistry.startReporter(StormMetricRegistry.java:119) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.metrics2.StormMetricRegistry.start(StormMetricRegistry.java:102) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.daemon.worker$fn__5545$exec_fn__1369__auto____5546.invoke(worker.clj:611) ~[storm-core-1.2.1.jar:1.2.1]
	at clojure.lang.AFn.applyToHelper(AFn.java:178) ~[clojure-1.7.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:630) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.worker$fn__5545$mk_worker__5636.doInvoke(worker.clj:598) [storm-core-1.2.1.jar:1.2.1]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.worker$_main.invoke(worker.clj:787) [storm-core-1.2.1.jar:1.2.1]
	at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.7.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.worker.main(Unknown Source) [storm-core-1.2.1.jar:1.2.1]
2018-03-07 15:39:19.195 o.a.s.util main [ERROR] Halting process: (<span class="code-quote">"Error on initialization"</span>)
java.lang.RuntimeException: (<span class="code-quote">"Error on initialization"</span>)
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) [storm-core-1.2.1.jar:1.2.1]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.worker$fn__5545$mk_worker__5636.doInvoke(worker.clj:598) [storm-core-1.2.1.jar:1.2.1]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.worker$_main.invoke(worker.clj:787) [storm-core-1.2.1.jar:1.2.1]
	at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.7.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.worker.main(Unknown Source) [storm-core-1.2.1.jar:1.2.1]
</pre>
</div></div>

<p>Looking at org.apache.storm.metrics2.reporters.JmxStormReporter.getMetricsJMXDomain() I found that it passes "reporterConf" map to Utils.getString() instead of a string:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
    <span class="code-keyword">public</span> <span class="code-keyword">static</span> <span class="code-object">String</span> getMetricsJMXDomain(Map reporterConf) {
<span class="code-keyword">return</span> Utils.getString(reporterConf, JMX_DOMAIN);
}
</pre>
</div></div>

<p>The "prepare" method in org.apache.storm.daemon.metrics.reporters.JmxPreparableReporter used by nimbus and supervisor correctly passes a string to Utils.getString():</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> void prepare(MetricRegistry metricsRegistry, Map stormConf) {
LOG.info(<span class="code-quote">"Preparing..."</span>);
JmxReporter.Builder builder = JmxReporter.forRegistry(metricsRegistry);
<span class="code-object">String</span> domain = Utils.getString(stormConf.get(Config.STORM_DAEMON_METRICS_REPORTER_PLUGIN_DOMAIN), <span class="code-keyword">null</span>);
<span class="code-keyword">if</span> (domain != <span class="code-keyword">null</span>) {
    builder.inDomain(domain);
}
[...]
</pre>
</div></div>

<p>Is this a bug or am I missing something in configuration?</p>

<p>Regards,<br/>
Federico Chiacchiaretta</p>

---
<details><summary><i>Originally reported by <a title="Federico Chiacchiaretta" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fchiacchiaretta">fchiacchiaretta</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2988" target="_blank">"Error on initialization of server mk-worker" when using org.apache.storm.metrics2.reporters.JmxStormReporter on worker</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Artem Ervits" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dbist13">dbist13</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-05-14T05:39:53+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dbist13" class="user-hover" rel="dbist13">Artem Ervits</a>, I merged into master and 1.x-branch.</p>
