### ISSUE TITLE
[STORM-2993] Storm HDFS bolt throws ClosedChannelException when Time rotation policy is used

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6775]
<p>Storm connector throws below error in the worker logs.</p>

<p> </p>

<p>2018-03-12 18:14:58.123 o.a.s.h.c.r.MoveFileAction Timer-3 <span class="error">&#91;INFO&#93;</span> Moving file hdfs://ctr-e138-1518143905142-85179-01-000004.hwx.site:8020/tmp/foo/my-bolt-3-0-1520878438104.txt to /tmp/dest2/my-bolt-3-0-15 20878438104.txt 2018-03-12 18:14:58.123 o.a.s.h.c.r.MoveFileAction Timer-0 <span class="error">&#91;INFO&#93;</span> Moving file hdfs://ctr-e138-1518143905142-85179-01-000004.hwx.site:8020/tmp/foo/my-bolt-6-0-1520878438104.txt to /tmp/dest2/my-bolt-6-0-15 20878438104.txt 2018-03-12 18:14:58.123 o.a.s.h.c.r.MoveFileAction Timer-1 <span class="error">&#91;INFO&#93;</span> Moving file hdfs://ctr-e138-1518143905142-85179-01-000004.hwx.site:8020/tmp/foo/my-bolt-5-0-1520878438104.txt to /tmp/dest2/my-bolt-5-0-15 20878438104.txt 2018-03-12 18:14:58.124 o.a.s.h.c.r.MoveFileAction Timer-2 <span class="error">&#91;INFO&#93;</span> Moving file hdfs://ctr-e138-1518143905142-85179-01-000004.hwx.site:8020/tmp/foo/my-bolt-4-0-1520878438104.txt to /tmp/dest2/my-bolt-4-0-15 20878438104.txt 2018-03-12 18:14:58.132 o.a.s.h.b.AbstractHdfsBolt Timer-2 <span class="error">&#91;INFO&#93;</span> File rotation took 28 ms. 2018-03-12 18:14:58.132 o.a.s.h.b.AbstractHdfsBolt Timer-0 <span class="error">&#91;INFO&#93;</span> File rotation took 29 ms. 2018-03-12 18:14:58.132 o.a.s.h.b.AbstractHdfsBolt Timer-3 <span class="error">&#91;INFO&#93;</span> File rotation took 28 ms. 2018-03-12 18:14:58.132 o.a.s.h.b.AbstractHdfsBolt Timer-1 <span class="error">&#91;INFO&#93;</span> File rotation took 28 ms. 2018-03-12 18:14:58.132 o.a.s.h.b.AbstractHdfsBolt Thread-12-my-bolt-executor<span class="error">&#91;6 6&#93;</span> <span class="error">&#91;INFO&#93;</span> Tuple failed to write, forcing a flush of existing data. 2018-03-12 18:14:58.132 o.a.s.h.b.AbstractHdfsBolt Thread-8-my-bolt-executor<span class="error">&#91;3 3&#93;</span> <span class="error">&#91;INFO&#93;</span> Tuple failed to write, forcing a flush of existing data. 2018-03-12 18:14:58.132 o.a.s.h.b.AbstractHdfsBolt Thread-16-my-bolt-executor<span class="error">&#91;5 5&#93;</span> <span class="error">&#91;INFO&#93;</span> Tuple failed to write, forcing a flush of existing data. 2018-03-12 18:14:58.132 o.a.s.d.executor Thread-8-my-bolt-executor<span class="error">&#91;3 3&#93;</span> <span class="error">&#91;ERROR&#93;</span> java.nio.channels.ClosedChannelException: null at org.apache.hadoop.hdfs.ExceptionLastSeen.throwException4Close(ExceptionLastSeen.java:73) ~<span class="error">&#91;stormjar.jar:?&#93;</span> at org.apache.hadoop.hdfs.DFSOutputStream.checkClosed(DFSOutputStream.java:153) ~<span class="error">&#91;stormjar.jar:?&#93;</span> at org.apache.hadoop.fs.FSOutputSummer.write(FSOutputSummer.java:105) ~<span class="error">&#91;stormjar.jar:?&#93;</span> at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:57) ~<span class="error">&#91;stormjar.jar:?&#93;</span> at java.io.DataOutputStream.write(DataOutputStream.java:107) ~<span class="error">&#91;?:1.8.0_161&#93;</span> at java.io.FilterOutputStream.write(FilterOutputStream.java:97) ~<span class="error">&#91;?:1.8.0_161&#93;</span> at org.apache.storm.hdfs.common.HDFSWriter.doWrite(HDFSWriter.java:48) ~<span class="error">&#91;stormjar.jar:?&#93;</span> at org.apache.storm.hdfs.common.AbstractHDFSWriter.write(AbstractHDFSWriter.java:40) ~<span class="error">&#91;stormjar.jar:?&#93;</span> at org.apache.storm.hdfs.bolt.AbstractHdfsBolt.execute(AbstractHdfsBolt.java:158) <span class="error">&#91;stormjar.jar:?&#93;</span> at org.apache.storm.daemon.executor$fn_<em>10189$tuple_action_fn</em><em>10191.invoke(executor.clj:745) <span class="error">&#91;storm-core-1.2.1.3.0.0.0-1013.jar:1.2.1.3.0.0.0-1013&#93;</span> at org.apache.storm.daemon.executor$mk_task_receiver$fn</em><em>10108.invoke(executor.clj:473) <span class="error">&#91;storm-core-1.2.1.3.0.0.0-1013.jar:1.2.1.3.0.0.0-1013&#93;</span> at org.apache.storm.disruptor$clojure_handler$reify</em><em>4115.onEvent(disruptor.clj:41) <span class="error">&#91;storm-core-1.2.1.3.0.0.0-1013.jar:1.2.1.3.0.0.0-1013&#93;</span> at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:509) <span class="error">&#91;storm-core-1.2.1.3.0.0.0-1013.jar:1.2.1.3.0.0.0-1013&#93;</span> at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:487) <span class="error">&#91;storm-core-1.2.1.3.0.0.0-1013.jar:1.2.1.3.0.0.0-1013&#93;</span> at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:74) <span class="error">&#91;storm-core-1.2.1.3.0.0.0-1013.jar:1.2.1.3.0.0.0-1013&#93;</span> at org.apache.storm.daemon.executor$fn</em><em>10189$fn</em><em>10202$fn</em><em>10257.invoke(executor.clj:868) <span class="error">&#91;storm-core-1.2.1.3.0.0.0-1013.jar:1.2.1.3.0.0.0-1013&#93;</span> at org.apache.storm.util$async_loop$fn</em>_1221.invoke(util.clj:484) <span class="error">&#91;storm-core-1.2.1.3.0.0.0-1013.jar:1.2.1.3.0.0.0-1013&#93;</span> at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span> at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_161&#93;</span> 2018-03-12 18:14:58.133 o.a.s.d.executor Thread-16-my-bolt-executor<span class="error">&#91;5 5&#93;</span> </p>

<p> </p>
<hr />
<p> </p>

<p>Apparently the Timed rotation policy does not synchronize properly so its possible that the HDFS bolt code can attempt to write to a closed writer.</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Arun Mahadevan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan">arunmahadevan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2993" target="_blank">Storm HDFS bolt throws ClosedChannelException when Time rotation policy is used</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Arun Mahadevan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan">arunmahadevan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-03-30T16:10:11+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan" class="user-hover" rel="arunmahadevan">Arun Mahadevan</a>,</p>

<p>I merged this into master and branch-1.x.  there were merge conflicts, but appeared to be minor ones, for 1.1.x so I didn't pull it in there.  If you want it pulled back please file another pull request for that.</p>

<p> </p>
