### ISSUE TITLE
[STORM-2995] Topology runtime exception - Error on initialization

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6777]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2018-03-14 13:28:41.399 o.a.s.d.worker main [INFO] Reading Assignments. 2018-03-14 13:28:41.511 o.a.s.m.TransportFactory main [INFO] Storm peer transport plugin:org.apache.storm.messaging.netty.Context 2018-03-14 13:28:41.935 o.a.s.m.n.Server main [INFO] Create Netty Server Netty-server-localhost-6712, buffer_size: 5242880, maxWorkers: 1 2018-03-14 13:28:41.980 o.a.s.d.worker main [ERROR] Error on initialization of server mk-worker org.apache.storm.shade.org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:6712 at org.apache.storm.shade.org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.messaging.netty.Server.<init>(Server.java:101) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.messaging.netty.Context.bind(Context.java:67) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.daemon.worker$worker_data$fn__5244.invoke(worker.clj:272) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.util$assoc_apply_self.invoke(util.clj:931) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.daemon.worker$worker_data.invoke(worker.clj:269) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.daemon.worker$fn__5542$exec_fn__1364__auto__$reify__5544.run(worker.clj:613) ~[storm-core-1.1.0.jar:1.1.0] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_51] at javax.security.auth.Subject.doAs(Subject.java:415) ~[?:1.7.0_51] at org.apache.storm.daemon.worker$fn__5542$exec_fn__1364__auto____5543.invoke(worker.clj:611) ~[storm-core-1.1.0.jar:1.1.0] at clojure.lang.AFn.applyToHelper(AFn.java:178) ~[clojure-1.7.0.jar:?] at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.7.0.jar:?] at clojure.core$apply.invoke(core.clj:630) ~[clojure-1.7.0.jar:?] at org.apache.storm.daemon.worker$fn__5542$mk_worker__5633.doInvoke(worker.clj:585) [storm-core-1.1.0.jar:1.1.0] at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.7.0.jar:?] at org.apache.storm.daemon.worker$_main.invoke(worker.clj:769) [storm-core-1.1.0.jar:1.1.0] at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.7.0.jar:?] at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:?] at org.apache.storm.daemon.worker.main(Unknown Source) [storm-core-1.1.0.jar:1.1.0] Caused by: java.net.BindException: Address already in use at sun.nio.ch.Net.bind0(Native Method) ~[?:1.7.0_51] at sun.nio.ch.Net.bind(Net.java:444) ~[?:1.7.0_51] at sun.nio.ch.Net.bind(Net.java:436) ~[?:1.7.0_51] at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[?:1.7.0_51] at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.7.0_51] at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.shade.org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.shade.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[storm-core-1.1.0.jar:1.1.0] at org.apache.storm.shade.org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[storm-core-1.1.0.jar:1.1.0] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_51] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_51] at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:744) ~[?:1.7.0_51] 2018-03-14 13:28:42.004 o.a.s.util main [ERROR] Halting process: (<span class="code-quote">"Error on initialization"</span>) java.lang.RuntimeException: (<span class="code-quote">"Error on initialization"</span>) at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) [storm-core-1.1.0.jar:1.1.0] at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.7.0.jar:?] at org.apache.storm.daemon.worker$fn__5542$mk_worker__5633.doInvoke(worker.clj:585) [storm-core-1.1.0.jar:1.1.0] at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.7.0.jar:?] at org.apache.storm.daemon.worker$_main.invoke(worker.clj:769) [storm-core-1.1.0.jar:1.1.0] at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.7.0.jar:?] at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:?] at org.apache.storm.daemon.worker.main(Unknown Source) [storm-core-1.1.0.jar:1.1.0]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="zhipcui" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhipcui">zhipcui</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2995" target="_blank">Topology runtime exception - Error on initialization</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:05+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhipcui">zhipcui</a>:</i>
<p>seem like related to this issue : <a href="https://issues.apache.org/jira/browse/STORM-1516" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-1516</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
