### ISSUE TITLE
[STORM-3032] NullPointerException in KafkaSpout emitOrRetryTuple

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6814]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.NullPointerException: <span class="code-keyword">null</span>
at clojure.lang.Numbers.ops(Numbers.java:1013) ~[clojure-1.7.0.jar:?]
at clojure.lang.Numbers.multiply(Numbers.java:148) ~[clojure-1.7.0.jar:?]
at org.apache.storm.stats$transferred_tuples_BANG_.invoke(stats.clj:131) ~[storm-core-1.2.1.jar:1.2.1]
at org.apache.storm.daemon.task$mk_tasks_fn$fn__4656.invoke(task.clj:167) ~[storm-core-1.2.1.jar:1.2.1]
at org.apache.storm.daemon.task$send_unanchored.invoke(task.clj:119) ~[storm-core-1.2.1.jar:1.2.1]
at org.apache.storm.daemon.executor$fn__4975$fn__4990$send_spout_msg__4996.invoke(executor.clj:594) ~[storm-core-1.2.1.jar:1.2.1]
at org.apache.storm.daemon.executor$fn__4975$fn$reify__5006.emit(executor.clj:618) ~[storm-core-1.2.1.jar:1.2.1]
at org.apache.storm.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:50) ~[storm-core-1.2.1.jar:1.2.1]
at org.apache.storm.kafka.spout.KafkaSpout.emitOrRetryTuple(KafkaSpout.java:496) ~[stormjar.jar:?]
at org.apache.storm.kafka.spout.KafkaSpout.emitIfWaitingNotEmitted(KafkaSpout.java:440) ~[stormjar.jar:?]
at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:308) ~[stormjar.jar:?]
at org.apache.storm.daemon.executor$fn__4975$fn__4990$fn__5021.invoke(executor.clj:654) ~[storm-core-1.2.1.jar:1.2.1]
at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:484) [storm-core-1.2.1.jar:1.2.1]
at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:785) [?:?]
</pre>
</div></div>
<p>Error in KafkaSpout emitOrRetry method</p>

---
<details><summary><i>Originally reported by <a title="Ajeesh B" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Ajeesh">Ajeesh</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3032" target="_blank">NullPointerException in KafkaSpout emitOrRetryTuple</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:07+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>:</i>
<p>Hello,</p>


<p>We are getting the same exception with Storm 1.2.3, using Kafka client at version 2.0.1, against Kafka Brokers at version 2.1.1.</p>

<p>Since this is a NullPointerException that seems to be related to some statistics computation, isn't there a way to catch it so as to limit noise in Storm logs, unless that hint about a severe issue and thus some guidance to understand the issue & recommendations to solve it would be welcomed ?</p>

<p> </p>

<p>Kind regards,</p>

<p>Alexandre Vermeerbergen</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sdd">sdd</a>:</i>
<p>Hello,</p>

<p>We are also getting the exception in KafkaSpout's emitOrRetry method with Storm 1.2.3 and Kafka client at version 2.0.1.</p>

<p>Any suggestion or guidance ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>This does not seem to be an issue as of 2.x. Could you try upgrading to that?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>:</i>
<p>Important detail : we reproduce this issue using Storm 1.2.3 with OpenJ9 flavor of AdoptOpenJDK 8 update 222 to run Supervisor (supervisor, worker, log analyzer) processes.</p>

<p>We do not reproduce this issue using Storm 1.2.3 with HotSpot flavor of AdoptOpenJDK8 update 222 run Supervisor processes.</p>

<p>Hope it helps,<br/>
Alexandre Vermeerbergen</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mampf86">mampf86</a>:</i>
<p>This is a known issue:</p>

<ul>
	<li><a href="https://ask.clojure.org/index.php/10184/clojure-throws-various-exceptions-immediately-adoptopenjdk" class="external-link" target="_blank" rel="nofollow noopener">https://ask.clojure.org/index.php/10184/clojure-throws-various-exceptions-immediately-adoptopenjdk</a></li>
	<li><a href="https://clojure.atlassian.net/browse/CLJ-2609" class="external-link" target="_blank" rel="nofollow noopener">https://clojure.atlassian.net/browse/CLJ-2609</a></li>
</ul>


<p>Reported to IBM. I will report back when/if there is a fix available.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
