### ISSUE TITLE
[STORM-3046] Getting a NPE leading worker to die when starting a topology.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6828]
<p>I am using storm-core and storm-kafka-client version 1.2.1 and kafka clients version 1.1.0.</p>

<p>We have an external kafka from where we get the messages.<br/>
 Whenever I try to run the topology, I get a NPE, which leads to the worker getting died.<br/>
If I set poll strategy to earliest and the topic already contains some messages, it works fine.<br/>
 I have used a custom record translator which is working fine.</p>

<p> Can someone please help me fix the issue?</p>

<p>Thanks.</p>

<p> </p>

<p>Error - </p>

<p>10665 [Thread-58-spout-handle-rule-local-kafka-spout-executor<span class="error">&#91;26 26&#93;</span>] ERROR o.a.s.util - Async loop died!<br/>
 java.lang.RuntimeException: java.lang.NullPointerException<br/>
 at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:522) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:487) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:74) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.daemon.executor$fn_<em>5043$fn</em><em>5056$fn</em>_5109.invoke(executor.clj:861) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:484) <span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
 at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_131&#93;</span><br/>
 Caused by: java.lang.NullPointerException<br/>
 at org.apache.storm.kafka.spout.trident.KafkaTridentSpoutEmitter.seek(KafkaTridentSpoutEmitter.java:193) ~<span class="error">&#91;storm-kafka-client-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.kafka.spout.trident.KafkaTridentSpoutEmitter.emitPartitionBatch(KafkaTridentSpoutEmitter.java:127) ~<span class="error">&#91;storm-kafka-client-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.kafka.spout.trident.KafkaTridentSpoutEmitter.emitPartitionBatch(KafkaTridentSpoutEmitter.java:51) ~<span class="error">&#91;storm-kafka-client-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.trident.spout.OpaquePartitionedTridentSpoutExecutor$Emitter.emitBatch(OpaquePartitionedTridentSpoutExecutor.java:141) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:82) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:383) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.daemon.executor$fn_<em>5043$tuple_action_fn</em>_5045.invoke(executor.clj:739) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.daemon.executor$mk_task_receiver$fn__4964.invoke(executor.clj:468) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.disruptor$clojure_handler$reify__4475.onEvent(disruptor.clj:41) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:509) ~<span class="error">&#91;storm-core-1.2.1.jar:1.2.1&#93;</span><br/>
 ... 6 more</p>

<p> </p>

<p> </p>

<p>Topology class - </p>

<p> </p>

<p> </p>

<p> </p>

<p> </p>

<p>import org.apache.storm.Config;<br/>
import org.apache.storm.LocalCluster;<br/>
import org.apache.storm.StormSubmitter;<br/>
import org.apache.storm.generated.*;<br/>
import org.apache.storm.kafka.spout.KafkaSpoutConfig;<br/>
import org.apache.storm.kafka.spout.trident.KafkaTridentSpoutOpaque;<br/>
import org.apache.storm.trident.Stream;<br/>
import org.apache.storm.trident.TridentState;<br/>
import org.apache.storm.trident.TridentTopology;<br/>
import org.apache.storm.tuple.Fields;</p>

<p>import java.util.Properties;</p>

<p> </p>

<p>public class TestTopology {</p>

<p> </p>

<p>private static StormTopology buildTopology(Properties stormProperties) </p>
{
 

Properties kafkaProperties = getProperties("/kafka.properties");
 TridentTopology topology = new TridentTopology();

Fields stageArguments = new Fields("test", "issue");

KafkaSpoutConfig<String, String> kafkaSpoutConfig = KafkaSpoutConfig.builder(kafkaProperties.getProperty("bootstrap.servers"), "test")
 .setFirstPollOffsetStrategy(KafkaSpoutConfig.FirstPollOffsetStrategy.LATEST)
 .setProcessingGuarantee(KafkaSpoutConfig.ProcessingGuarantee.AT_MOST_ONCE)
 .setRecordTranslator(new RecordTranslator(), stageArguments)
 .build();

KafkaTridentSpoutOpaque kafkaTridentSpoutOpaque = new KafkaTridentSpoutOpaque(kafkaSpoutConfig);

Grouping partitionGroup = getPartitionGroup("test");

log.info("Creating Opaque-Trident-Kafka-Spout");

final Stream kafkaSpout = topology.newStream(stormProperties.getProperty("SPOUT_NAME"), kafkaTridentSpoutOpaque).name("kafkaSpout").parallelismHint(1);
 
TridentState testUpdate = kafkaSpout.partition(partitionGroup).name("testUpdate").partitionPersist(new MainMemoryStateFactory(), stageArguments, new 
MainMemoryStateUpdater(), stageArguments).parallelismHint(1);
 

Stream viewUpdate = ruleUpdate.newValuesStream().name("viewUpdate").partition(partitionGroup).each(stageArguments, new UpdateView(), new Fields()).parallelismHint(2);

return topology.build();
 }

<p>public static void main(String[] args) {<br/>
 Config conf = new Config();<br/>
 log.info("Topology config: " + conf);<br/>
 Properties properties = getProperties("/storm-cluster.properties");</p>

<p>conf.setMessageTimeoutSecs(600);</p>

<p>log.info("Building Topology");<br/>
 StormTopology topology = buildTopology(properties);<br/>
 log.info(topology.toString());</p>

<p>log.info("Submitting handle-rule Topology");<br/>
 try </p>
{
 LocalCluster cluster = new LocalCluster();
 cluster.submitTopology("handle-rule", conf, topology);
 }
<p> catch (Exception e) </p>
{
 e.printStackTrace();
 }
<p> }</p>

<p>}</p>

---
<details><summary><i>Originally reported by <a title="Kush Khandelwal" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kush.kh">kush.kh</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3046" target="_blank">Getting a NPE leading worker to die when starting a topology.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-07-09T10:01:03+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>This is caused by a bad assumption I made here <a href="https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java#L161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java#L161</a>.</p>

<p>I assumed that the last batch metadata would only be null for the first batch, or reemits of the first batch. I forgot to account for cases where the first batch contains no tuples, because in that case we'll set the metadata for the first batch to null (see <a href="https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java#L125" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java#L125</a>). In the following call to emitBatch, we're going to hit this line with a null lastBatchMeta <a href="https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java#L181" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java#L181</a>. This is very likely going to happen if you use e.g. LATEST as the FirstPollOffsetStrategy, and as you observe it doesn't happen if you start at the beginning of a partition and there are messages to emit.</p>

<p>Let me know if you'd like to try to fix it. If not I'll be happy to give it a shot, and would appreciate if you would try out the potential fix.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=moroseking">moroseking</a>:</i>
<p>if you use opaquetrident, you must change some code that handle the condition when the lastbatch is null</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shaikasifullah">shaikasifullah</a>:</i>
<p>I configured firstPollOffsetStrategy as FirstPollOffsetStrategy.UNCOMMITTED_EARLIEST, but the error still persists. Any suggestions to quickly fix this while creating Trident topology ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>I'm happy to provide a patched 1.x branch, you could check that out and see if the patch fixes the issue?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Here is the patched 1.x <a href="https://github.com/srdo/storm/tree/STORM-3046-1.x" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/srdo/storm/tree/STORM-3046-1.x</a>. You should be able to check out and build storm-kafka-client from there.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aniket.alhat">aniket.alhat</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> any plans on merging and release of this to 1.2.x?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aniket.alhat" class="user-hover" rel="aniket.alhat">Aniket Alhat</a> I'll put up a 1.x version as soon as the PR targeting master has been reviewed and merged.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>, I merged into master.</p>

<p>The patch wasn't applied to 1.x-branch cleanly. Could you please raise a PR for 1.x-branch as well? Thanks in advance!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Also merged into 1.x-branch as well.</p>
