### ISSUE TITLE
[STORM-3057] ERROR An exception occurred processing Appender syslog

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6839]
<p><b>ERROR An exception occurred processing Appender syslog</b></p>

<p>2018-05-04 14:44:43,721 ERROR An exception occurred processing Appender syslog org.apache.logging.log4j.core.appender.AppenderLoggingException: Error flushing stream UDP:localhost:514<br/>
 at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:159)<br/>
 at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:112)<br/>
 at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)<br/>
 at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)<br/>
 at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)<br/>
 at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)<br/>
 at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)<br/>
 at org.apache.logging.slf4j.Log4jLogger.log(Log4jLogger.java:375)<br/>
 at org.apache.log4j.Category.differentiatedLog(Category.java:186)<br/>
 at org.apache.log4j.Category.error(Category.java:272)<br/>
 at com.surfilter.analyse.es.common.service.impl.EsIndexServiceImpl.insertEs(EsIndexServiceImpl.java:141)<br/>
 at com.surfilter.analyse.es.common.service.impl.EsIndexServiceImpl.bulkIndex(EsIndexServiceImpl.java:97)<br/>
 at com.surfilter.analyse.es.service.RecordESService.saveDnsObjectToES(RecordESService.java:122)<br/>
 at com.surfilter.analyse.dns.dao.illegalWeb.IllegalWebESDAO.batchSave(IllegalWebESDAO.java:128)<br/>
 at com.surfilter.analyse.dns.service.illegalWeb.IllegalWebService.dowork(IllegalWebService.java:71)<br/>
 at com.surfilter.analyse.dns.storm.bolt.DataStoreHandler.storeData(DataStoreHandler.java:28)<br/>
 at com.surfilter.analyse.dns.storm.bolt.DnsCheckBolt.execute(DnsCheckBolt.java:168)<br/>
 at backtype.storm.daemon.executor$fn_<em>5694$tuple_action_fn</em>_5696.invoke(executor.clj:690)<br/>
 at backtype.storm.daemon.executor$mk_task_receiver$fn__5615.invoke(executor.clj:435)<br/>
 at backtype.storm.disruptor$clojure_handler$reify__5189.onEvent(disruptor.clj:58)<br/>
 at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:132)<br/>
 at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:106)<br/>
 at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80)<br/>
 at backtype.storm.daemon.executor$fn_<em>5694$fn</em><em>5707$fn</em>_5758.invoke(executor.clj:818)<br/>
 at backtype.storm.util$async_loop$fn__545.invoke(util.clj:479)<br/>
 at clojure.lang.AFn.run(AFn.java:22)<br/>
 at java.lang.Thread.run(Thread.java:744)<br/>
Caused by: java.io.IOException: 消息过长<br/>
 at java.net.PlainDatagramSocketImpl.send(Native Method)<br/>
 at java.net.DatagramSocket.send(DatagramSocket.java:676)<br/>
 at org.apache.logging.log4j.core.net.DatagramOutputStream.flush(DatagramOutputStream.java:103)<br/>
 at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:156)<br/>
 ... 26 more</p>

<p>2018-05-04 14:56:27,877 ERROR Unable to write to stream UDP:localhost:514 for appender syslog<br/>
2018-05-04 15:27:45,512 ERROR Logger contains an invalid element or attribute "appender"<br/>
2018-05-04 16:18:08,456 ERROR Logger contains an invalid element or attribute "appender"</p>

<p> </p>

<p><b>but storm  worker  often auto shutdown 。</b></p>

---
<details><summary><i>Originally reported by <a title="babymm" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baby慕慕">baby慕慕</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3057" target="_blank">ERROR An exception occurred processing Appender syslog</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:59+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vknayanar">vknayanar</a>:</i>
<p>We are also experiencing the same issue ? Any solution for this ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carojasq">carojasq</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vknayanar" class="user-hover" rel="vknayanar">Krishnaram Nayanar</a> under which version are you experiencing this issue? </p>

<p>We are on 2.2.0 and are experiencing this issue.</p>

<p>Any know work around <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baby%E6%85%95%E6%85%95" class="user-hover" rel="baby慕慕">babymm</a> ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carojasq">carojasq</a>:</i>
<p><tt>I tried this work around on log4j that basically will trim to 5000 chars the logged message. Seems to have good results for me:</tt></p>

<p><tt><property name="pattern">%d{yyyy-MM-dd HH:mm:ss.SSS} %c{1.} %t <span class="error">&#91;%p&#93;</span> %.-5000msg%n</property></tt></p>

<p> </p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
