### ISSUE TITLE
[STORM-3059] KafkaSpout throws NPE when hitting a null tuple if the processing guarantee is not AT_LEAST_ONCE

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6841]
<p>Introduced with <a href="https://issues.apache.org/jira/browse/STORM-2994" title="KafkaSpout consumes messages but doesn&#39;t commit offsets" class="issue-link" data-issue-key="STORM-2994"><del>STORM-2994</del></a></p>

<blockquote>
<p>java.lang.NullPointerException: null<br/>
at org.apache.storm.kafka.spout.KafkaSpout.emitOrRetryTuple(KafkaSpout.java:507)<br/>
~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.spout.KafkaSpout.emitIfWaitingNotEmitted(KafkaSpout.java:440)<br/>
~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:308)<br/>
~<span class="error">&#91;stormjar.jar:?&#93;</span></p></blockquote>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3059" target="_blank">KafkaSpout throws NPE when hitting a null tuple if the processing guarantee is not AT_LEAST_ONCE</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-05-07T14:10:23+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>The issue is <a href="https://github.com/apache/storm/blob/v1.2.2/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L507" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v1.2.2/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L507</a>. If the processing guarantee is not AT_LEAST_ONCE, the offset managers map is empty.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>, I merged into master, 1.x, 1.1.x, 1.0.x branches.</p>

<p>This assumes we will cancel the ongoing votes (1.2.2 RC2, 1.1.3 RC1). If we just decide to pass the votes, I'll modify the fix versions accordingly.</p>
