### ISSUE TITLE
[STORM-3079] improve getMessage support for ThriftExceptions

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6861]
<p>I've seen error callstacks similar to this and been confused as to the null message.  The generated thrift code does not support getMessage().  We should try and improve the log messages.</p>

<p> <br/>
2018-05-16 21:15:04.596 o.a.s.d.n.Nimbus timer <span class="error">&#91;INFO&#93;</span> Exception {}<br/>
org.apache.storm.generated.KeyNotFoundException: nullat org.apache.storm.blobstore.LocalFsBlobStore.getStoredBlobMeta(LocalFsBlobStore.java:258) ~<span class="error">&#91;storm-server-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.blobstore.LocalFsBlobStore.getBlob(LocalFsBlobStore.java:393) ~<span class="error">&#91;storm-server-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.blobstore.BlobStore.readBlobTo(BlobStore.java:310) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.blobstore.BlobStore.readBlob(BlobStore.java:339) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.daemon.nimbus.TopoCache.readTopology(TopoCache.java:67) ~<span class="error">&#91;storm-server-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.daemon.nimbus.Nimbus.readStormTopologyAsNimbus(Nimbus.java:670) ~<span class="error">&#91;storm-server-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.daemon.nimbus.Nimbus.rmDependencyJarsInTopology(Nimbus.java:2333) ~<span class="error">&#91;storm-server-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.daemon.nimbus.Nimbus.doCleanup(Nimbus.java:2387) ~<span class="error">&#91;storm-server-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.daemon.nimbus.Nimbus.lambda$launchServer$37(Nimbus.java:2674) ~<span class="error">&#91;storm-server-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.StormTimer$1.run(StormTimer.java:111) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span><br/>
at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:227) ~<span class="error">&#91;storm-client-2.0.0.y.jar:2.0.0.y&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3079" target="_blank">improve getMessage support for ThriftExceptions</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-05-22T10:20:47+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">Aaron Gresch</a>, I merged into master.</p>
