### ISSUE TITLE
[STORM-3084] 2.x NPE on Nimbus startup

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6866]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2018-05-24 09:27:05.636 o.a.s.d.n.Nimbus main [INFO] Starting nimbus server <span class="code-keyword">for</span> storm version <span class="code-quote">'2.0.0.y'</span> 2018-05-24 09:27:06.012 o.a.s.d.n.Nimbus timer [ERROR] Error <span class="code-keyword">while</span> processing event java.lang.RuntimeException: java.lang.NullPointerException at org.apache.storm.daemon.nimbus.Nimbus.lambda$launchServer$37(Nimbus.java:2685) ~[storm-server-2.0.0.y.jar:2.0.0.y] at org.apache.storm.StormTimer$1.run(StormTimer.java:111) ~[storm-client-2.0.0.y.jar:2.0.0.y] at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:227) ~[storm-client-2.0.0.y.jar:2.0.0.y] Caused by: java.lang.NullPointerException at org.apache.storm.daemon.nimbus.Nimbus.readAllSupervisorDetails(Nimbus.java:1814) ~[storm-server-2.0.0.y.jar:2.0.0.y] at org.apache.storm.daemon.nimbus.Nimbus.computeNewSchedulerAssignments(Nimbus.java:1906) ~[storm-server-2.0.0.y.jar:2.0.0.y] at org.apache.storm.daemon.nimbus.Nimbus.mkAssignments(Nimbus.java:2057) ~[storm-server-2.0.0.y.jar:2.0.0.y] at org.apache.storm.daemon.nimbus.Nimbus.mkAssignments(Nimbus.java:2003) ~[storm-server-2.0.0.y.jar:2.0.0.y] at org.apache.storm.daemon.nimbus.Nimbus.lambda$launchServer$37(Nimbus.java:2681) ~[storm-server-2.0.0.y.jar:2.0.0.y] ... 2 more 2018-05-24 09:27:06.023 o.a.s.u.Utils timer [ERROR] Halting process: Error <span class="code-keyword">while</span> processing event java.lang.RuntimeException: Halting process: Error <span class="code-keyword">while</span> processing event at org.apache.storm.utils.Utils.exitProcess(Utils.java:469) ~[storm-client-2.0.0.y.jar:2.0.0.y] at org.apache.storm.daemon.nimbus.Nimbus.lambda$<span class="code-keyword">new</span>$17(Nimbus.java:484) ~[storm-server-2.0.0.y.jar:2.0.0.y] at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:252) ~[storm-client-2.0.0.y.jar:2.0.0.y] 2018-05-24 09:27:06.032 o.a.s.d.n.Nimbus <span class="code-object">Thread</span>-12 [INFO] Shutting down master 2018-05-24 09:27:06.032 o.a.s.u.Utils <span class="code-object">Thread</span>-13 [INFO] Halting after 5 seconds
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3084" target="_blank">2.x NPE on Nimbus startup</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-06-01T16:36:27+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">Aaron Gresch</a> I merged this into master.</p>
