### ISSUE TITLE
[STORM-3137] Flaky test in nimbus_test

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6919]
<p>Saw a test failure in storm-core</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
313081 [main] INFO  o.a.s.d.n.Nimbus - Cleaning up topo3
313081 [main] INFO  o.a.s.d.n.Nimbus - Exception {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.storm.serialization.GzipThriftSerializationDelegate.deserialize(GzipThriftSerializationDelegate.java:54) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.utils.Utils.deserialize(Utils.java:717) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.daemon.nimbus.TopoCache.readTopology(TopoCache.java:67) ~[storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.daemon.nimbus.Nimbus.readStormTopologyAsNimbus(Nimbus.java:684) ~[storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.daemon.nimbus.Nimbus.rmDependencyJarsInTopology(Nimbus.java:2424) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.daemon.nimbus.Nimbus$MockitoMock$2109251824.rmDependencyJarsInTopology$accessor$ivuy1xAW(Unknown Source) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.daemon.nimbus.Nimbus$MockitoMock$2109251824$auxiliary$0HJjHtWw.call(Unknown Source) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:127) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:43) [mockito-core-2.19.0.jar:?]
	at org.mockito.Answers.answer(Answers.java:100) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:104) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:110) [mockito-core-2.19.0.jar:?]
	at org.apache.storm.daemon.nimbus.Nimbus$MockitoMock$2109251824.rmDependencyJarsInTopology(Unknown Source) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.daemon.nimbus.Nimbus.doCleanup(Nimbus.java:2478) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.daemon.nimbus.Nimbus$MockitoMock$2109251824.doCleanup$accessor$ivuy1xAW(Unknown Source) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.daemon.nimbus.Nimbus$MockitoMock$2109251824$auxiliary$g48aKOaZ.call(Unknown Source) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:127) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:43) [mockito-core-2.19.0.jar:?]
	at org.mockito.Answers.answer(Answers.java:100) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:104) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49) [mockito-core-2.19.0.jar:?]
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:110) [mockito-core-2.19.0.jar:?]
	at org.apache.storm.daemon.nimbus.Nimbus$MockitoMock$2109251824.doCleanup(Unknown Source) [storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) [clojure-1.7.0.jar:?]
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313) [clojure-1.7.0.jar:?]
	at org.apache.storm.nimbus_test$fn__4768$fn__4771.invoke(nimbus_test.clj:1899) [?:2.0.0-SNAPSHOT]
	at clojure.core$with_redefs_fn.invoke(core.clj:7209) [clojure-1.7.0.jar:?]
	at org.apache.storm.nimbus_test$fn__4768.invoke(nimbus_test.clj:1895) [?:2.0.0-SNAPSHOT]
	at clojure.test$test_var$fn__7670.invoke(test.clj:704) [clojure-1.7.0.jar:?]
	at clojure.test$test_var.invoke(test.clj:704) [clojure-1.7.0.jar:?]
	at clojure.test$test_vars$fn__7692$fn__7697.invoke(test.clj:722) [clojure-1.7.0.jar:?]
	at clojure.test$default_fixture.invoke(test.clj:674) [clojure-1.7.0.jar:?]
	at clojure.test$test_vars$fn__7692.invoke(test.clj:722) [clojure-1.7.0.jar:?]
	at clojure.test$default_fixture.invoke(test.clj:674) [clojure-1.7.0.jar:?]
	at clojure.test$test_vars.invoke(test.clj:718) [clojure-1.7.0.jar:?]
	at clojure.test$test_all_vars.invoke(test.clj:728) [clojure-1.7.0.jar:?]
	at clojure.test$test_ns.invoke(test.clj:747) [clojure-1.7.0.jar:?]
	at clojure.core$map$fn__4553.invoke(core.clj:2624) [clojure-1.7.0.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) [clojure-1.7.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) [clojure-1.7.0.jar:?]
	at clojure.lang.Cons.next(Cons.java:39) [clojure-1.7.0.jar:?]
	at clojure.lang.RT.boundedLength(RT.java:1735) [clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:130) [clojure-1.7.0.jar:?]
	at clojure.core$apply.invoke(core.clj:632) [clojure-1.7.0.jar:?]
	at clojure.test$run_tests.doInvoke(test.clj:762) [clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.7.0.jar:?]
	at org.apache.storm.testrunner$eval5473$iter__5474__5478$fn__5479$fn__5480$fn__5481.invoke(test_runner.clj:107) [?:2.0.0-SNAPSHOT]
	at org.apache.storm.testrunner$eval5473$iter__5474__5478$fn__5479$fn__5480.invoke(test_runner.clj:53) [?:2.0.0-SNAPSHOT]
	at org.apache.storm.testrunner$eval5473$iter__5474__5478$fn__5479.invoke(test_runner.clj:52) [?:2.0.0-SNAPSHOT]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) [clojure-1.7.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) [clojure-1.7.0.jar:?]
	at clojure.lang.RT.seq(RT.java:507) [clojure-1.7.0.jar:?]
	at clojure.core$seq__4128.invoke(core.clj:137) [clojure-1.7.0.jar:?]
	at clojure.core$dorun.invoke(core.clj:3009) [clojure-1.7.0.jar:?]
	at org.apache.storm.testrunner$eval5473.invoke(test_runner.clj:52) [?:2.0.0-SNAPSHOT]
	at clojure.lang.<span class="code-object">Compiler</span>.eval(<span class="code-object">Compiler</span>.java:6782) [clojure-1.7.0.jar:?]
	at clojure.lang.<span class="code-object">Compiler</span>.load(<span class="code-object">Compiler</span>.java:7227) [clojure-1.7.0.jar:?]
	at clojure.lang.<span class="code-object">Compiler</span>.loadFile(<span class="code-object">Compiler</span>.java:7165) [clojure-1.7.0.jar:?]
	at clojure.main$load_script.invoke(main.clj:275) [clojure-1.7.0.jar:?]
	at clojure.main$script_opt.invoke(main.clj:337) [clojure-1.7.0.jar:?]
	at clojure.main$main.doInvoke(main.clj:421) [clojure-1.7.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.7.0.jar:?]
	at clojure.lang.Var.invoke(Var.java:383) [clojure-1.7.0.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.7.0.jar:?]
	at clojure.lang.Var.applyTo(Var.java:700) [clojure-1.7.0.jar:?]
	at clojure.main.main(main.java:37) [clojure-1.7.0.jar:?]
Caused by: java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106) ~[?:1.8.0_151]
	at org.apache.storm.utils.Utils.gunzip(Utils.java:826) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.apache.storm.serialization.GzipThriftSerializationDelegate.deserialize(GzipThriftSerializationDelegate.java:51) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	... 80 more
</pre>
</div></div>

<p>Full run is here <a href="https://travis-ci.org/apache/storm/jobs/398415336" class="external-link" target="_blank" rel="nofollow noopener">https://travis-ci.org/apache/storm/jobs/398415336</a>.</p>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3137" target="_blank">Flaky test in nimbus_test</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-07-11T00:01:22+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>The exception in the description is misleading, and happens on every test run. It's not the cause of the failure.</p>

<p>The failure is because the test asserts that when Nimbus tries to clean up "topo2" and "topo3", it calls first IStormClusterState.teardownHeartbeats("topo2"), then IStormClusterState.teardownHeartbeats("topo3"). Nimbus iterates over a Set of topo ids, so the order is nondeterministic. We should just replace the mocking/verification with Mockito, so we can assert that the calls happen without asserting the order they happen in.</p>
