### ISSUE TITLE
[STORM-3171] java.lang.NoSuchMethodError in org.apache.storm:storm-kafka-monitor:jar:1.1.2 caused by dependency conflict issue

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6953]
<p>Hi, we found a dependency conflict issue in <b>org.apache.storm:storm-kafka-monitor:jar:1.1.2</b>, <b>caused by org.apache.zookeeper:zookeeper:jar</b>. As shown in the following dependency tree, due to Maven version management, <b>org.apache.zookeeper:zookeeper:jar:3.4.6</b> will be loaded, during the packaging process.</p>

<p> </p>

<p>However, method <b><org.apache.zookeeper.server.quorum.flexible.QuorumMaj: void <init>(java.util.Map)></b> only defined in <b>org.apache.zookeeper:zookeeper:jar 3.5.3-beta</b>, so that there is a crash with the following stack trace when your project referencing the missing method.</p>

<p> </p>

<p><b>Stack trace:</b></p>

<p>Exception in thread "main" java.lang.NoSuchMethodError: org.apache.zookeeper.server.quorum.flexible.QuorumMaj.<init>(Ljava/util/Map;)V</p>

<p>         at org.apache.curator.framework.imps.EnsembleTracker.<init>(EnsembleTracker.java:57)</p>

<p>         at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:159)</p>

<p>         at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:158)</p>

<p>         at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:109)</p>

<p> </p>

<p><b>Dependency tree:</b></p>

<p>org.apache.storm:storm-kafka-monitor:jar:1.1.2</p>

<p>+- org.apache.kafka:kafka-clients:jar:0.10.1.0:compile</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<td class='confluenceTd'>  +- net.jpountz.lz4:lz4:jar:1.3.0:compile</td>
</tr>
<tr>
<td class='confluenceTd'>  +- org.xerial.snappy:snappy-java:jar:1.1.2.6:compile</td>
</tr>
<tr>
<td class='confluenceTd'>  - org.slf4j:slf4j-api:jar:1.7.21:compile</td>
</tr>
</tbody></table>
</div>

<p>+- org.apache.curator:curator-framework:jar:4.0.0:compile</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<td class='confluenceTd'>  - org.apache.curator:curator-client:jar:4.0.0:compile</td>
</tr>
<tr>
<td class='confluenceTd'>     +- <b>org.apache.zookeeper:zookeeper:jar:3.4.6:compile (version managed from 3.5.3-beta)</b></td>
</tr>
<tr>
<td class='confluenceTd'>     +- jline:jline:jar:0.9.94:compile</td>
<td class='confluenceTd'> </td>
</tr>
<tr>
<td class='confluenceTd'>      - io.netty:netty:jar:3.9.9.Final:compile (version managed from 3.7.0.Final)</td>
<td class='confluenceTd'> </td>
</tr>
<tr>
<td class='confluenceTd'>     +- com.google.guava:guava:jar:16.0.1:compile (version managed from 20.0)</td>
</tr>
<tr>
<td class='confluenceTd'>     - (org.slf4j:slf4j-api:jar:1.7.21:compile - version managed from 1.7.6; omitted for duplicate)</td>
</tr>
</tbody></table>
</div>

<p>+- com.googlecode.json-simple:json-simple:jar:1.1:compile</p>

<p>+- commons-cli:commons-cli:jar:1.3.1:compile</p>
<ul class="alternate" type="square">
	<li>junit:junit:jar:4.11:test</li>
</ul>

<p>   - org.hamcrest:hamcrest-core:jar:1.3:test</p>

<p> </p>

<p><b>Solution:</b></p>

<p>One choice is to upgrade <b>org.apache.zookeeper:zookeeper:jar to 3.5.3-beta,</b> but it is not the best solution, as 3.5.3-beta is not a release version.**</p>

<p> </p>

<p>Thanks a lot!</p>

<p>Regards,</p>

<p>Leo</p>

---
<details><summary><i>Originally reported by <a title="LeoAugust19 " href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=LeoAugust19">LeoAugust19</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3171" target="_blank">java.lang.NoSuchMethodError in org.apache.storm:storm-kafka-monitor:jar:1.1.2 caused by dependency conflict issue</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-08-05T02:28:51+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=LeoAugust19" class="user-hover" rel="LeoAugust19">LeoAugust19 </a>. Could you try upgrading to one of the fix versions for <a href="https://issues.apache.org/jira/browse/STORM-2978?" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-2978?</a> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=leoaugust19">leoaugust19</a>:</i>
<p>Hi, <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>, I saw this bug had been fixed by <a href="https://github.com/apache/storm/pull/2579" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2579</a> , thank you.</p>
