### ISSUE TITLE
[STORM-3176] KafkaSpout commit offset occurs CommitFailedException which leads to worker dead

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6958]
<p>KafkaSpout use the commitAsync api of Consumer, if the interval time between the call of consumer.poll() more than <em>max.poll.interval.ms</em> or the heartbeat of consumer timeout, that will occur CommitFailedException,  and then the worker will die, the log like this: </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-comment">// 2018-07-31 19:19:03.341 o.a.s.util [ERROR] Async loop died!
</span>org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer th
an the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address <span class="code-keyword">this</span> either by increasing the session timeout or by reducing the maximum size of batches returned in
poll() with max.poll.records.
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:698) ~[stormjar.jar:?]
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:577) ~[stormjar.jar:?]
at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1126) ~[stormjar.jar:?]
at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:XXX) ~[stormjar.jar:?]
at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:430) ~[stormjar.jar:?]
at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:264) ~[stormjar.jar:?]
at org.apache.storm.daemon.executor$fn__10936$fn__10951$fn__10982.invoke(executor.clj:647) ~[XXX.jar:?]
at org.apache.storm.util$async_loop$fn__553.invoke(util.clj:484) [XXX.jar:?]
at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_112]
2018-07-31 19:19:03.342 o.a.s.d.executor [ERROR]
</pre>
</div></div>
<p>I find it will catch the Exception in auto-commit mode of consumer, the source code is:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-comment">// <span class="code-keyword">private</span> void maybeAutoCommitOffsetsSync(<span class="code-object">long</span> timeoutMs) {
</span>    <span class="code-keyword">if</span> (autoCommitEnabled) {
Map<TopicPartition, OffsetAndMetadata> allConsumedOffsets = subscriptions.allConsumed();
<span class="code-keyword">try</span> {
    log.debug(<span class="code-quote">"Sending synchronous auto-commit of offsets {} <span class="code-keyword">for</span> group {}"</span>, allConsumedOffsets, groupId);
    <span class="code-keyword">if</span> (!commitOffsetsSync(allConsumedOffsets, timeoutMs))
log.debug(<span class="code-quote">"Auto-commit of offsets {} <span class="code-keyword">for</span> group {} timed out before completion"</span>,
allConsumedOffsets, groupId);
} <span class="code-keyword">catch</span> (WakeupException | InterruptException e) {
    log.debug(<span class="code-quote">"Auto-commit of offsets {} <span class="code-keyword">for</span> group {} was interrupted before completion"</span>,
    allConsumedOffsets, groupId);
    <span class="code-comment">// rethrow wakeups since they are triggered by the user
</span>    <span class="code-keyword">throw</span> e;
} <span class="code-keyword">catch</span> (Exception e) {
    <span class="code-comment">// consistent with async auto-commit failures, we <span class="code-keyword">do</span> not propagate the exception
</span>    log.warn(<span class="code-quote">"Auto-commit of offsets {} failed <span class="code-keyword">for</span> group {}: {}"</span>, allConsumedOffsets, groupId,
    e.getMessage());
}
    }
}
</pre>
</div></div>
<p>I think KafkaSpout should do like this, catch the Exception avoid to worker die. And when the msg ack failed, Spout should judge the offset of the msgID is larger than the last commit offset(Spout can guarantee that these msgs which offset less than the last commit offset are all ack), if not, the msg should not retry.</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Matt Wang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wangzzu">wangzzu</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3176" target="_blank">KafkaSpout commit offset occurs CommitFailedException which leads to worker dead</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-08-03T14:20:28+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>I think this is a symptom of using the KafkaConsumer.subscribe API. We've deprecated this use on 1.x and removed the classes on 2.x.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wangzzu">wangzzu</a>:</i>
<p>modify some log</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wangzzu">wangzzu</a>:</i>
<p>the log has been modified</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2542">STORM-2542</a>]</i>
