### ISSUE TITLE
[STORM-3182] Owner summary page in non-secured cluster shows 500 server error because of NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6964]
<p>When opening owner summary page in non-secured cluster, all contents become empty except html template, and shows 500 error with below stack trace:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.NullPointerException
	at org.apache.storm.daemon.ui.filters.AuthorizedUserFilter.makeResponse(AuthorizedUserFilter.java:83)
	at org.apache.storm.daemon.ui.filters.AuthorizedUserFilter.filter(AuthorizedUserFilter.java:121)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
</pre>
</div></div>

<p>I'll attach the screenshot.</p>

<p>I'm not sure it would work normally in secured cluster, since I don't have secured cluster.</p>

<p>cc. <span class="error">&#91;~govindmenon&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3182" target="_blank">Owner summary page in non-secured cluster shows 500 server error because of NullPointerException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Govind Menon" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gmenon">gmenon</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-08-10T11:33:58+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <span class="error">&#91;~govindmenon&#93;</span> for providing quick fix, I merged into master.</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-2714%20label%3Aepic">STORM-2714</a>]</i>
