### ISSUE TITLE
[STORM-3195] IllegalArgumentException when rolling upgrade nimbus from 1.x to 2.x

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6977]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2018-08-15 15:49:06.550 o.a.s.d.n.Nimbus timer [ERROR] Error <span class="code-keyword">while</span> processing event
java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to convert 1.7604166666666667 to <span class="code-object">int</span>
at org.apache.storm.daemon.nimbus.Nimbus.lambda$launchServer$48(Nimbus.java:2837) ~[storm-server-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.StormTimer$1.run(StormTimer.java:110) ~[storm-client-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:226) [storm-client-2.0.0.y.jar:2.0.0.y]
Caused by: java.lang.IllegalArgumentException: Don't know how to convert 1.7604166666666667 to <span class="code-object">int</span>
at org.apache.storm.utils.ObjectReader.getInt(ObjectReader.java:78) ~[storm-client-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.StormCommon.addAcker(StormCommon.java:256) ~[storm-client-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.StormCommon.systemTopologyImpl(StormCommon.java:523) ~[storm-client-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.StormCommon.systemTopology(StormCommon.java:440) ~[storm-client-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.StormCommon.stormTaskInfoImpl(StormCommon.java:544) ~[storm-client-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.StormCommon.stormTaskInfo(StormCommon.java:460) ~[storm-client-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.computeExecutors(Nimbus.java:1732) ~[storm-server-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.getOrUpdateExecutors(Nimbus.java:1357) ~[storm-server-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.computeExecutorToComponent(Nimbus.java:1752) ~[storm-server-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.readTopologyDetails(Nimbus.java:1582) ~[storm-server-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.getResourcesForTopology(Nimbus.java:2034) ~[storm-server-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.getClusterInfoImpl(Nimbus.java:2676) ~[storm-server-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.sendClusterMetricsToExecutors(Nimbus.java:2701) ~[storm-server-2.0.0.y.jar:2.0.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.lambda$launchServer$48(Nimbus.java:2834) ~[storm-server-2.0.0.y.jar:2.0.0.y]
... 2 more
</pre>
</div></div>

<p>We were rolling upgrading our storm cluster to 2.x and we found this error from nimbus.log. It's not necessary to do rolling upgrade but good news is we basically made it work. </p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3195" target="_blank">IllegalArgumentException when rolling upgrade nimbus from 1.x to 2.x</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2018-08-15T18:28:16+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Community 1.x will not have this issue because <a href="https://github.com/apache/storm/pull/2325" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2325</a> wasn't merged into 1.x. The worker count will always be int and acker executer number will always be int. </p>

<p>Our internal version 1.x has <a href="https://github.com/apache/storm/pull/2325" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2325</a> feature. And that's why it happened. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli" class="user-hover" rel="ethanli">Ethan Li</a><br/>
I'm wondering the symptom itself: shouldn't worker count as well as acker executor number be integer? No one would say worker count is 1.66 and acker executor count is 2.33, so the value itself looks somewhat incorrect to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Yeah this is our internal code. We have a piece of code in nimbu.clj similar to <a href="https://github.com/apache/storm/pull/2325" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/2325</a> but it's in clojure: </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
(defn estimated-worker-count-<span class="code-keyword">for</span>-ras-topo [storm-conf topology]
  (let [component-parallelism-mp (into {} (map #(vector (first %) (component-parallelism storm-conf (second %))) (all-components topology)))
bolt-memory-requirement (into {} (map #(vector (first %) (.getOnHeapMemoryMb (second %))) (into {} (ResourceUtils/getBoltsResources topology storm-conf))))
spout-memory-requirement (into {} (map #(vector (first %) (.getOnHeapMemoryMb (second %))) (into {} (ResourceUtils/getSpoutsResources topology storm-conf))))
component-memory-requirement (merge bolt-memory-requirement spout-memory-requirement)
total-memory-required (reduce + (vals (merge-with * component-memory-requirement component-parallelism-mp)))
worker-heap-memory (get storm-conf WORKER-HEAP-MEMORY-MB)
]
    (/ total-memory-required worker-heap-memory)))
</pre>
</div></div>
<p>This returns a double value. </p>

<p>We don't need to worry about it in the community code.</p>
