### ISSUE TITLE
[STORM-3211] WindowedBoltExecutor NPE if wrapped bolt returns null from getComponentConfiguration

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6993]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Exception in thread <span class="code-quote">"main"</span> java.lang.NullPointerException
    at org.apache.storm.topology.WindowedBoltExecutor.declareOutputFields(WindowedBoltExecutor.java:309)
    at org.apache.storm.topology.TopologyBuilder.getComponentCommon(TopologyBuilder.java:432)
    at org.apache.storm.topology.TopologyBuilder.createTopology(TopologyBuilder.java:120)
    at Main.main(Main.java:23)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3211" target="_blank">WindowedBoltExecutor NPE if wrapped bolt returns null from getComponentConfiguration</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Eduardo Pinto" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=epinto">epinto</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-11-02T09:25:47+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Most likely the right thing to do here is to check for null, and return an empty configuration instead.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=epinto">epinto</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>, this does not seem to apply anymore, does it?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>It still looks like an issue to me. Take a look at <a href="https://github.com/apache/storm/blob/925422a5b5ad1c3329a2c2b44db460ae94f70806/storm-client/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java#L339" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/925422a5b5ad1c3329a2c2b44db460ae94f70806/storm-client/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java#L339</a>. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=epinto">epinto</a>:</i>
<p>Thanks for the help <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>. I just opened a MR to fix this. I'm starting with these smaller issues to get more comfortable with the codebase.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=epinto" class="user-hover" rel="epinto">Eduardo Pinto</a>, merged to master</p>
