### ISSUE TITLE
[STORM-3281] ZK ACL checks breaks nimbus HA with LocalFsBlobStore

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7063]
<p>A new check <span class="error">&#91;1&#93;</span> is introduced to check the ZK ACLs before nimbus starts up. However this can fail with Nimbus HA enabled with LocalFsBlobStore causing nimbus to not start up.</p>

<p>1. Set up a cluster with 3 Nimbus (blobstore replication factor = 2). It might be reproducible with two nimbus but I havent checked.<br/>
2. Deploy topology<br/>
3. Once the topology is activated and running, Kill the leader nimbus.<br/>
4. The nimbus becomes offline and one of the other two is elected as a leader<br/>
5. Now try to bring up the killed nimbus.</p>

<p>It will fail with following exception</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2018-11-06 10:22:05.195 o.a.s.t.t.TSaslTransport main [DEBUG] CLIENT: reading data length: 37
2018-11-06 10:22:05.204 o.a.s.b.BlobStoreUtils main [DEBUG] Updating state inside zookeeper for an update
2018-11-06 10:22:05.209 o.a.s.u.StormBoundedExponentialBackoffRetry main [DEBUG] The baseSleepTimeMs [2000] the maxSleepTimeMs [60000] the maxRetries [5]
2018-11-06 10:22:05.224 o.a.s.m.n.Login main [INFO] successfully logged in.
2018-11-06 10:22:05.224 o.a.s.s.a.k.KerberosSaslTransportPlugin main [DEBUG] SASL GSSAPI client transport is being established
2018-11-06 10:22:05.238 o.a.s.s.a.k.KerberosSaslTransportPlugin main [DEBUG] do as:storm_componentsrandYPTkmQBYmmTRvE@EXAMPLE.COM
2018-11-06 10:22:05.240 o.a.s.t.t.TSaslTransport main [DEBUG] opening transport org.apache.storm.thrift.transport.TSaslClientTransport@75dc1c1c
2018-11-06 10:22:05.241 o.a.s.s.a.k.KerberosSaslTransportPlugin main [ERROR] Client failed to open SaslClientTransport to interact with a server during session initiation: org.apache.storm.thrift.transport.TT
ransportException: java.net.ConnectException: Connection refused (Connection refused)
org.apache.storm.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
at org.apache.storm.thrift.transport.TSocket.open(TSocket.java:226) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.thrift.transport.TSaslTransport.open(TSaslTransport.java:266) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.security.auth.kerberos.KerberosSaslTransportPlugin$1.run(KerberosSaslTransportPlugin.java:145) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.security.auth.kerberos.KerberosSaslTransportPlugin$1.run(KerberosSaslTransportPlugin.java:141) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_151]
at org.apache.storm.security.auth.kerberos.KerberosSaslTransportPlugin.connect(KerberosSaslTransportPlugin.java:140) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.security.auth.TBackoffConnect.doConnectWithRetry(TBackoffConnect.java:53) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.security.auth.ThriftClient.reconnect(ThriftClient.java:104) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.security.auth.ThriftClient.<init>(ThriftClient.java:73) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.utils.NimbusClient.<init>(NimbusClient.java:131) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.blobstore.BlobStoreUtils.createStateInZookeeper(BlobStoreUtils.java:233) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.blobstore.BlobStoreUtils.updateKeyForBlobStore(BlobStoreUtils.java:269) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.blobstore.LocalFsBlobStore.checkForBlobUpdate(LocalFsBlobStore.java:344) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.blobstore.LocalFsBlobStore.getBlob(LocalFsBlobStore.java:274) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.blobstore.BlobStore.readBlobTo(BlobStore.java:271) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.blobstore.BlobStore.readBlob(BlobStore.java:300) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.zookeeper.AclEnforcement.verifyAcls(AclEnforcement.java:111) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.daemon.nimbus$_launch.invoke(nimbus.clj:2588) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at org.apache.storm.daemon.nimbus$_main.invoke(nimbus.clj:2612) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
at clojure.lang.AFn.applyToHelper(AFn.java:152) ~[clojure-1.7.0.jar:?]
at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.7.0.jar:?]
at org.apache.storm.daemon.nimbus.main(Unknown Source) ~[storm-core-1.2.1.3.3.0.0-154.jar:1.2.1.3.3.0.0-154]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_151]
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_151]
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_151]
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_151]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_151]
at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_151]
</pre>
</div></div>

<p>The ACL check tries to download the topology conf from blobstore <span class="error">&#91;2&#93;</span> and in that process tries to update the nimbus state in ZK via itself <span class="error">&#91;3&#93;</span> causing the connection failure.</p>

<p>To fix it I think we should wait until nimbus comes up before doing ACL checks.</p>

<p>cc <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2" class="user-hover" rel="revans2">Robert Joseph Evans</a> to suggest the right fix since you may have more context.</p>

<p><span class="error">&#91;1&#93;</span> <a href="https://github.com/apache/storm/blob/1.x-branch/storm-core/src/clj/org/apache/storm/daemon/nimbus.clj#L2588" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/1.x-branch/storm-core/src/clj/org/apache/storm/daemon/nimbus.clj#L2588</a><br/>
<span class="error">&#91;2&#93;</span> <a href="https://github.com/apache/storm/blob/1.x-branch/storm-core/src/jvm/org/apache/storm/zookeeper/AclEnforcement.java#L111" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/1.x-branch/storm-core/src/jvm/org/apache/storm/zookeeper/AclEnforcement.java#L111</a><br/>
<span class="error">&#91;3&#93;</span> <a href="https://github.com/apache/storm/blob/1.x-branch/storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java#L269" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/1.x-branch/storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java#L269</a></p>

---
<details><summary><i>Originally reported by <a title="Arun Mahadevan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunmahadevan">arunmahadevan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3281" target="_blank">ZK ACL checks breaks nimbus HA with LocalFsBlobStore</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:00+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>If you really want to bring the thrift server up first you can. I was mostly concerned about bringing up a nimbus that could be in a bad state, because of zookeeper ACLs, but with HA that is really less important.  Looking at the code, in my opinion the bug is that while we are a part of nimbus we are creating a connection back to ourselves, which is really always a bad idea.</p>

<p> </p>

<p><a href="https://github.com/apache/storm/blob/d2d6f40344e6cc92ab07f3a462d577ef6b61f8b1/storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java#L231-L235" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/d2d6f40344e6cc92ab07f3a462d577ef6b61f8b1/storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java#L231-L235</a></p>

<p> </p>

<p>I would have to take some time to try and unwind BlobStoreUtils to see exactly where any why some of these functions are called to see what refactoring might be allowed.  But if it is simpler to just wait for nimbus to be up, we can do that too.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
