### ISSUE TITLE
[STORM-3283] Can not connect to kerberized hdfs with HdfsSpout

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7065]
<p>In HdfsSpout hdfs FileSystem object is <a href="https://github.com/apache/storm/blob/master/external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java#L407" class="external-link" target="_blank" rel="nofollow noopener">first created</a> and then <a href="https://github.com/apache/storm/blob/master/external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java#L418" class="external-link" target="_blank" rel="nofollow noopener">additional settings are read</a>.</p>

<p>As a result config parameters like:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
conf.set(<span class="code-quote">"hadoop.security.authentication"</span>, <span class="code-quote">"kerberos"</span>);
</pre>
</div></div>
<p>can not be set and HdfsSpout fails with the following exception:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled. Available:[TOKEN, KERBEROS]
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
 at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1656) ~[hadoop-hdfs-client-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1583) ~[hadoop-hdfs-client-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1580) ~[hadoop-hdfs-client-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1595) ~[hadoop-hdfs-client-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1734) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.storm.hdfs.spout.HdfsSpout.validateOrMakeDir(HdfsSpout.java:518) [stormjar.jar:?]
 at org.apache.storm.hdfs.spout.HdfsSpout.open(HdfsSpout.java:435) [stormjar.jar:?]
 at org.apache.storm.daemon.executor$fn__9593$fn__9608.invoke(executor.clj:615) [storm-core-1.2.1.3.3.0.0-157.jar:1.2.1.3.3.0.0-157]
 at org.apache.storm.util$async_loop$fn__555.invoke(util.clj:482) [storm-core-1.2.1.3.3.0.0-157.jar:1.2.1.3.3.0.0-157]
 at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
 at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_171]
Caused by: org.apache.hadoop.ipc.RemoteException: SIMPLE authentication is not enabled. Available:[TOKEN, KERBEROS]
 at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1497) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.ipc.Client.call(Client.java:1443) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.ipc.Client.call(Client.java:1353) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at com.sun.proxy.$Proxy47.getFileInfo(Unknown Source) ~[?:?]
 at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:900) ~[hadoop-hdfs-client-3.1.1.3.0.1.0-187.jar:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
 at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-3.1.1.3.0.1.0-187.jar:?]
 at com.sun.proxy.$Proxy48.getFileInfo(Unknown Source) ~[?:?]
 at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1654) ~[hadoop-hdfs-client-3.1.1.3.0.1.0-187.jar:?]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Gergely Hajós" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ghajos">ghajos</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3283" target="_blank">Can not connect to kerberized hdfs with HdfsSpout</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Gergely Hajós" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ghajos">ghajos</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:47:00+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
