### ISSUE TITLE
[STORM-3319] Slot can fail assertions in some cases

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7101]
<blockquote>
<p>2019-01-19 22:47:03.045 <span class="error">&#91;SLOT_1024&#93;</span> ERROR org.apache.storm.daemon.supervisor.Slot - Error when processing event<br/>
java.lang.AssertionError: null<br/>
	at org.apache.storm.daemon.supervisor.Slot.handleEmpty(Slot.java:781) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:217) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:900) <span class="error">&#91;classes/:?&#93;</span><br/>
2019-01-19 22:47:03.045 <span class="error">&#91;SLOT_1025&#93;</span> ERROR org.apache.storm.daemon.supervisor.Slot - Error when processing event<br/>
java.lang.AssertionError: null<br/>
	at org.apache.storm.daemon.supervisor.Slot.handleEmpty(Slot.java:781) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:217) ~<span class="error">&#91;classes/:?&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:900) <span class="error">&#91;classes/:?&#93;</span></p></blockquote>

<p>The issue is that Slot tries to go from WAITING_FOR_LOCALIZATION to EMPTY when there's an exception downloading a blob. It then fails one of the assertions in EMPTY because it doesn't clear its pendingChangingBlobsAssignment field.</p>

<p>There's no reason to go back to EMPTY. The Slot still wants to download some blobs, so it should just restart the downloads and go back to WAITING_FOR_LOCALIZATION.</p>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3319" target="_blank">Slot can fail assertions in some cases</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-03-15T18:44:28+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> to the great effort on fixing instability of tests, and sorry to let you wait too long. I merged into master.</p>
