### ISSUE TITLE
[STORM-3333] storm-kafka-monitor - NoClassDefFoundError: org/apache/kafka/shaded/clients/consumer/KafkaConsumer

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7115]
<p> </p>

<p>ui log contains errors trying to run storm-kafka-monitor.  I see a similar callstack when running from the command line:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
org.apache.storm.utils.ShellUtils$ExitCodeException: Exception in thread <span class="code-quote">"main"</span> java.lang.NoClassDefFoundError: org/apache/kafka/shaded/clients/consumer/KafkaConsumer
	at org.apache.storm.kafka.monitor.KafkaOffsetLagUtil.getOffsetLags(KafkaOffsetLagUtil.java:145)
	at org.apache.storm.kafka.monitor.KafkaOffsetLagUtil.main(KafkaOffsetLagUtil.java:71)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.shaded.clients.consumer.KafkaConsumer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.<span class="code-object">ClassLoader</span>.loadClass(<span class="code-object">ClassLoader</span>.java:357)
	... 2 more

	at org.apache.storm.utils.ShellUtils.runCommand(ShellUtils.java:271) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.ShellUtils.run(ShellUtils.java:194) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.ShellUtils$ShellCommandExecutor.execute(ShellUtils.java:428) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.ShellCommandRunnerImpl.execCommand(ShellCommandRunnerImpl.java:33) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.ShellCommandRunnerImpl.execCommand(ShellCommandRunnerImpl.java:26) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.TopologySpoutLag.getLagResultForKafka(TopologySpoutLag.java:162) ~[storm-core-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.TopologySpoutLag.getLagResultForNewKafkaSpout(TopologySpoutLag.java:193) ~[storm-core-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.TopologySpoutLag.addLagResultForKafkaSpout(TopologySpoutLag.java:127) ~[storm-core-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.TopologySpoutLag.lag(TopologySpoutLag.java:61) ~[storm-core-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.daemon.ui.UIHelpers.getTopologyLag(UIHelpers.java:1620) ~[storm-webapp-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.daemon.ui.resources.StormApiResource.getTopologyLag(StormApiResource.java:359) ~[storm-webapp-2.0.1.y.jar:2.0.1.y]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3333" target="_blank">storm-kafka-monitor - NoClassDefFoundError: org/apache/kafka/shaded/clients/consumer/KafkaConsumer</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-02-08T09:25:07+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">Aaron Gresch</a>, merged to master.</p>
