### ISSUE TITLE
[STORM-3343] JCQueueTest can still be flaky

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7125]
<p>Made a mistake in the fix for <a href="https://issues.apache.org/jira/browse/STORM-3310" title="JCQueueTest is flaky" class="issue-link" data-issue-key="STORM-3310"><del>STORM-3310</del></a>. The consumer in one of the tests check for interrupt in a place it shouldn't. </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
[ERROR] Failures:
[ERROR]   JCQueueTest.lambda$testFirstMessageFirst$0:63 We expect to receive first published message first, but received <span class="code-keyword">null</span> expected:<FIRST> but was:<<span class="code-keyword">null</span>>

Exception in thread <span class="code-quote">"<span class="code-object">Thread</span>-125"</span> java.lang.RuntimeException: java.lang.InterruptedException: ConsumerThd interrupted
	at org.apache.storm.utils.JCQueueTest$1.accept(JCQueueTest.java:48)
	at org.apache.storm.utils.JCQueue.consumeImpl(JCQueue.java:133)
	at org.apache.storm.utils.JCQueue.consume(JCQueue.java:110)
	at org.apache.storm.utils.JCQueue.consume(JCQueue.java:101)
	at org.apache.storm.utils.JCQueueTest$ConsumerThd.run(JCQueueTest.java:207)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)
Caused by: java.lang.InterruptedException: ConsumerThd interrupted
	... 6 more
</pre>
</div></div>

<p>The consumer accept method shouldn't check for interrupt, as that is handled by the ConsumerThd.run method. When the accept check for interrupt is hit, the consumer exits without draining the JCQueue, and the test may fail.</p>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3343" target="_blank">JCQueueTest can still be flaky</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-02-26T19:54:23+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>, I merged into master.</p>
