### ISSUE TITLE
[STORM-3344] blacklist scheduler causing nimbus restart

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7126]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2019-02-22 10:48:41.460 o.a.s.d.n.Nimbus timer [ERROR] Error <span class="code-keyword">while</span> processing event
java.lang.RuntimeException: java.lang.UnsupportedOperationException
at org.apache.storm.daemon.nimbus.Nimbus.lambda$launchServer$27(Nimbus.java:2872) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.StormTimer$1.run(StormTimer.java:110) ~[storm-client-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:226) [storm-client-2.0.1.y.jar:2.0.1.y]
Caused by: java.lang.UnsupportedOperationException
at org.apache.storm.shade.com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:43) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at java.util.AbstractCollection.remove(AbstractCollection.java:293) ~[?:1.8.0_102]
at org.apache.storm.scheduler.blacklist.BlacklistScheduler.removeLongTimeDisappearFromCache(BlacklistScheduler.java:216) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.scheduler.blacklist.BlacklistScheduler.schedule(BlacklistScheduler.java:110) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.nimbus.Nimbus.computeNewSchedulerAssignments(Nimbus.java:2070) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.nimbus.Nimbus.lockingMkAssignments(Nimbus.java:2234) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.nimbus.Nimbus.mkAssignments(Nimbus.java:2220) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.nimbus.Nimbus.mkAssignments(Nimbus.java:2165) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.nimbus.Nimbus.lambda$launchServer$27(Nimbus.java:2868) ~[storm-server-2.0.1.y.jar:2.0.1.y]
... 2 more
2019-02-22 10:48:41.461 o.a.s.u.Utils timer [ERROR] Halting process: Error <span class="code-keyword">while</span> processing event
java.lang.RuntimeException: Halting process: Error <span class="code-keyword">while</span> processing event
at org.apache.storm.utils.Utils.exitProcess(Utils.java:520) ~[storm-client-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.nimbus.Nimbus.lambda$<span class="code-keyword">new</span>$9(Nimbus.java:564) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:253) [storm-client-2.0.1.y.jar:2.0.1.y]
2019-02-22 10:48:41.462 o.a.s.u.Utils <span class="code-object">Thread</span>-19 [INFO] Halting after 10 seconds
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3344" target="_blank">blacklist scheduler causing nimbus restart</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-03-15T18:46:44+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">Aaron Gresch</a>, I merged into master.</p>
