### ISSUE TITLE
[STORM-3346] ClassNotFoundException: clojure.lang.persistentList whiile submitting topology to local cluster in storm

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7128]
<p>Getting below exceptions while submitting storm topology to local cluster </p>

<p>Exception in thread "main" java.lang.ExceptionInInitializerError<br/>
 at clojure.lang.Namespace.<init>(Namespace.java:34)<br/>
 at clojure.lang.Namespace.findOrCreate(Namespace.java:176)<br/>
 at clojure.lang.Var.internPrivate(Var.java:156)<br/>
 at org.apache.storm.LocalCluster.<clinit>(Unknown Source)<br/>
 at KafkaCEPTopology.main(KafkaCEPTopology.java:53)<br/>
Caused by: Syntax error compiling . at (clojure/core.clj:20:8).<br/>
 at clojure.lang.Compiler.analyzeSeq(Compiler.java:7114)<br/>
 at clojure.lang.Compiler.analyze(Compiler.java:6789)<br/>
 at clojure.lang.Compiler.access$300(Compiler.java:38)<br/>
 at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:596)<br/>
 at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)<br/>
 at clojure.lang.Compiler.analyze(Compiler.java:6789)<br/>
 at clojure.lang.Compiler.analyze(Compiler.java:6745)<br/>
 at clojure.lang.Compiler.eval(Compiler.java:7180)<br/>
 at clojure.lang.Compiler.load(Compiler.java:7635)<br/>
 at clojure.lang.RT.loadResourceScript(RT.java:381)<br/>
 at clojure.lang.RT.loadResourceScript(RT.java:372)<br/>
 at clojure.lang.RT.load(RT.java:463)<br/>
 at clojure.lang.RT.load(RT.java:428)<br/>
 at clojure.lang.RT.doInit(RT.java:471)<br/>
 at clojure.lang.RT.<clinit>(RT.java:338)<br/>
 ... 5 more<br/>
Caused by: java.lang.ClassNotFoundException: clojure.lang.PersistentList<br/>
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)<br/>
 at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)<br/>
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)<br/>
 at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)<br/>
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)<br/>
 at java.lang.Class.forName0(Native Method)<br/>
 at java.lang.Class.forName(Class.java:348)<br/>
 at clojure.lang.RT.classForName(RT.java:2207)<br/>
 at clojure.lang.RT.classForNameNonLoading(RT.java:2220)<br/>
 at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:1041)<br/>
 at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:982)<br/>
 at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Tanuj Kulshrestha" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tank21">tank21</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3346" target="_blank">ClassNotFoundException: clojure.lang.persistentList whiile submitting topology to local cluster in storm</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:44:56+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Do you have a Clojure dependency in your topology? Storm 1.2.2 depends on Clojure 1.7.0, maybe there's a version conflict with your jar?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tank21">tank21</a>:</i>
<p>No I don't have any clojure dependency in topology.</p>

<p>This issue occurs when I call the Kafka Producer code before my</p>

<p>TopologyBuilder builder = new TopologyBuilder();</p>

<p>When I don't topology works fine.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Could you post the output of "mvn dependency:tree" from your topology, as well as the topology wiring code (the part with the TopologyBuilder and Kafka producer)?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore.</p>
