### ISSUE TITLE
[STORM-3352] Use Netty BOM to lock all Netty artifacts to same version

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7134]
<p>We are not properly ensuring that Netty artifacts are the same version. I got a test failure in storm-cassandra, because netty-all is version 4.1.30, but cassandra pulls in Netty in version 4.0.37.</p>

<blockquote>

<p>java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.normalizedArch()Ljava/lang/String;<br/>
    at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:180) ~<span class="error">&#91;netty-all-4.1.30.Final.jar:4.1.30.Final&#93;</span><br/>
    at io.netty.channel.epoll.Native.<clinit>(Native.java:61) ~<span class="error">&#91;netty-all-4.1.30.Final.jar:4.1.30.Final&#93;</span><br/>
    at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38) ~<span class="error">&#91;netty-all-4.1.30.Final.jar:4.1.30.Final&#93;</span><br/>
    at org.apache.cassandra.transport.Server.run(Server.java:147) ~<span class="error">&#91;cassandra-all-2.1.7.jar:2.1.7&#93;</span></p>
</blockquote>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3352" target="_blank">Use Netty BOM to lock all Netty artifacts to same version</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-03-16T03:24:57+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> I merged into master.</p>
