### ISSUE TITLE
[STORM-3354] LeaderElector is not shut down properly

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7136]
<p>Nimbus' LeaderElector is not shut down when Nimbus shuts down. This can cause test flakiness because the elector callback may be called after the Zookeeper client is closed.</p>

<p>Additionally the LeaderListenerCallback may in some cases quit the leadership election if Nimbus isn't ready to become master, but I don't see any code to re-enter the election.<br/>
 </p>
<blockquote><p>java.lang.IllegalStateException: Client is not started<br/>
         at org.apache.storm.shade.org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:139) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:602) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1191) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1158) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1155) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CreateBuilderImpl$3.forPath(CreateBuilderImpl.java:360) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CreateBuilderImpl$3.forPath(CreateBuilderImpl.java:308) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.zookeeper.ClientZookeeper.createNode(ClientZookeeper.java:98) ~<span class="error">&#91;storm-client-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.nimbus.LeaderListenerCallback.setUpNimbusInfo(LeaderListenerCallback.java:154) ~<span class="error">&#91;storm-server-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.nimbus.LeaderListenerCallback.leaderCallBack(LeaderListenerCallback.java:96) ~<span class="error">&#91;storm-server-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.zookeeper.Zookeeper$1.isLeader(Zookeeper.java:123) ~<span class="error">&#91;storm-server-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch$9.apply(LeaderLatch.java:665) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch$9.apply(LeaderLatch.java:661) ~<span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.shaded.com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch.setLeadership(LeaderLatch.java:660) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch.checkLeadership(LeaderLatch.java:539) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch.access$700(LeaderLatch.java:65) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch$7.processResult(LeaderLatch.java:590) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:187) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span><br/>
         at org.apache.storm.shade.org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) <span class="error">&#91;shaded-deps-2.0.1-SNAPSHOT.jar:2.0.1-SNAPSHOT&#93;</span> </p></blockquote>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3354" target="_blank">LeaderElector is not shut down properly</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-03-29T03:43:59+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>, I merged into master.</p>
