### ISSUE TITLE
[STORM-3384] storm set-log-level command throws wrong exception when the topology is not running

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7166]
<p><a href="https://github.com/apache/storm/blob/1.1.x-branch/storm-core/src/clj/org/apache/storm/command/set_log_level.clj#L31" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/1.1.x-branch/storm-core/src/clj/org/apache/storm/command/set_log_level.clj#L31</a><br/>
will throw an exception like the following if the topology is not running</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
3396 [main] INFO  b.s.c.set-log-level - Sent log config LogConfig(named_logger_level:{ROOT=LogLevel(action:UPDATE, target_log_level:DEBUG, reset_log_level_timeout_secs:30)}) <span class="code-keyword">for</span> topology w
Exception in thread <span class="code-quote">"main"</span> java.lang.IllegalArgumentException: No matching field found: IllegalArgumentException <span class="code-keyword">for</span> <span class="code-keyword">class </span>java.lang.<span class="code-object">String</span>
	at clojure.lang.Reflector.getInstanceField(Reflector.java:271)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:315)
	at backtype.storm.command.set_log_level$get_storm_id.invoke(set_log_level.clj:31)
	at backtype.storm.command.set_log_level$_main.doInvoke(set_log_level.clj:75)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at backtype.storm.command.set_log_level.main(Unknown Source)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3384" target="_blank">storm set-log-level command throws wrong exception when the topology is not running</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Trivial
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-04-26T15:33:55+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli" class="user-hover" rel="ethanli">Ethan Li</a>, merged the PRs</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>In case someone looks at this later: The command has been ported to Java in master, so this is not an issue there.</p>
