### ISSUE TITLE
[STORM-3398] Closing socket for xxx because of error (kafka.network.Processor) kafka.network.InvalidRequestException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7180]
<p>deploy a topology on storm cluster, storm start a <b>org.apache.storm.kafka.monitor.KafkaOffsetLagUtil</b> process, this process error:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
[2019-05-31 11:24:54,425] ERROR Closing socket <span class="code-keyword">for</span> xxxx:9092-xxxxx:17547 because of error (kafka.network.Processor)
kafka.network.InvalidRequestException: Error getting request <span class="code-keyword">for</span> apiKey: 3 and apiVersion: 2
at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:95)
at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:87)
at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:488)
at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:483)
at scala.collection.Iterator$<span class="code-keyword">class.</span>foreach(Iterator.scala:893)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
at scala.collection.IterableLike$<span class="code-keyword">class.</span>foreach(IterableLike.scala:72)
at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
at kafka.network.Processor.processCompletedReceives(SocketServer.scala:483)
at kafka.network.Processor.run(SocketServer.scala:413)
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid version <span class="code-keyword">for</span> API key 3: 2
at org.apache.kafka.common.protocol.ProtoUtils.schemaFor(ProtoUtils.java:31)
at org.apache.kafka.common.protocol.ProtoUtils.requestSchema(ProtoUtils.java:44)
at org.apache.kafka.common.protocol.ProtoUtils.parseRequest(ProtoUtils.java:60)
at org.apache.kafka.common.requests.MetadataRequest.parse(MetadataRequest.java:96)
at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:48)
at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:92)
</pre>
</div></div>
<p>Too many kafka sockets lead to delayed consumption and production of kafka services</p>

---
<details><summary><i>Originally reported by <a title="qianmoQ" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=qianmoQ">qianmoQ</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3398" target="_blank">Closing socket for xxx because of error (kafka.network.Processor) kafka.network.InvalidRequestException</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-06-01T04:30:11+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=qianmoq">qianmoq</a>:</i>
<p>�replace storm-kafka-monitor to your kafka version, solve the problem!!!</p>

<p>egg: <br/>
your kafka version:  0.10.0.0<br/>
replace storm-kafka-monitor version to 1.1.0<br/>
rm source toollib/storm-kafka-monitor-*.jar or rename this</p>
