### ISSUE TITLE
[STORM-3408] Rocks version shipped with Storm2 doesn't work on Windows 10

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7190]
<p>The version of rocks referenced by storm 2 cannot be used on windows 10 due to <a href="https://github.com/facebook/rocksdb/issues/2531" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/facebook/rocksdb/issues/2531</a> - this means `LocalClusterRunner` cannot be instantiated.</p>

<p>The stack trace is</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.UnsatisfiedLinkError: C:\Users\...\AppData\Local\Temp\librocksdbjni5428427063666929934.dll: A dynamic link library (DLL) initialization routine failed

	at java.lang.<span class="code-object">ClassLoader</span>$NativeLibrary.load(Native Method)
	at java.lang.<span class="code-object">ClassLoader</span>.loadLibrary0(<span class="code-object">ClassLoader</span>.java:1941)
	at java.lang.<span class="code-object">ClassLoader</span>.loadLibrary(<span class="code-object">ClassLoader</span>.java:1824)
	at java.lang.<span class="code-object">Runtime</span>.load0(<span class="code-object">Runtime</span>.java:809)
	at java.lang.<span class="code-object">System</span>.load(<span class="code-object">System</span>.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.apache.storm.metricstore.rocksdb.RocksDbStore.prepare(RocksDbStore.java:67)
	at org.apache.storm.metricstore.MetricStoreConfig.configure(MetricStoreConfig.java:33)
	at org.apache.storm.daemon.nimbus.Nimbus.<init>(Nimbus.java:528)
	at org.apache.storm.LocalCluster.<init>(LocalCluster.java:244)
	at org.apache.storm.LocalCluster.<init>(LocalCluster.java:159)
	...</pre>
</div></div>

<p>This issue is fixed by at least rocks version 5.17.2. I also note rocks v6 is out.</p>

<p>This is a blocker for us - we cannot upgrade to storm 2 as-is, as we cannot run our local unit tests using a local cluster runner on our Windows-based development machines.</p>

---
<details><summary><i>Originally reported by <a title="Simon Cooper" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3408" target="_blank">Rocks version shipped with Storm2 doesn't work on Windows 10</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Simon Cooper" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-06-25T18:41:17+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>I don't think this affects all Windows 10 installs, at least I'm not having an issue. That said, I don't see why we couldn't upgrade. I think we'd be happy to see a PR bumping the version number <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>Opened PR <a href="https://github.com/apache/storm/pull/3024" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/3024</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thanks for the fix <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984" class="user-hover" rel="thecoop1984">Simon Cooper</a>, merged to master.</p>
