### ISSUE TITLE
[STORM-3422] TupleCaptureBolt is not thread-safe

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7204]
<p>Marking this as Major because it's a crash. That said, the problem lies in testing code. This makes integration testing hard, but the issue does not affect any production code.</p>

<p> </p>

<p>First, let me show you a stack trace for Storm 2.0.0:</p>

<p><tt>java.lang.RuntimeException: java.lang.NullPointerException</tt><br/>
<tt>at org.apache.storm.executor.Executor.accept(Executor.java:282) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>at org.apache.storm.utils.JCQueue.consumeImpl(JCQueue.java:133) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>at org.apache.storm.utils.JCQueue.consume(JCQueue.java:110) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:171) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:158) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>at org.apache.storm.utils.Utils$1.run(Utils.java:388) <span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_121&#93;</span></tt><br/>
<tt>Caused by: java.lang.NullPointerException</tt><br/>
<tt>at org.apache.storm.testing.TupleCaptureBolt.execute(TupleCaptureBolt.java:45) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>at org.apache.storm.executor.bolt.BoltExecutor.tupleActionFn(BoltExecutor.java:234) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>at org.apache.storm.executor.Executor.accept(Executor.java:275) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span></tt><br/>
<tt>... 6 more</tt></p>

<p> </p>

<p> Here's the same for Storm 1.2.2:</p>

<p><tt>java.lang.RuntimeException: java.lang.NullPointerException</tt><br/>
<tt>at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:522) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:487) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:74) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at org.apache.storm.daemon.executor$fn_<em>10795$fn</em><em>10808$fn</em>_10861.invoke(executor.clj:861) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at org.apache.storm.util$async_loop$fn__553.invoke(util.clj:484) <span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span></tt><br/>
<tt>at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_121&#93;</span></tt><br/>
<tt>Caused by: java.lang.NullPointerException</tt><br/>
<tt>at org.apache.storm.testing.TupleCaptureBolt.execute(TupleCaptureBolt.java:50) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at org.apache.storm.daemon.executor$fn_<em>10795$tuple_action_fn</em>_10797.invoke(executor.clj:739) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at org.apache.storm.daemon.executor$mk_task_receiver$fn__10716.invoke(executor.clj:468) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at org.apache.storm.disruptor$clojure_handler$reify__10135.onEvent(disruptor.clj:41) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:509) ~<span class="error">&#91;storm-core-1.2.2.jar:1.2.2&#93;</span></tt><br/>
<tt>... 6 more</tt></p>

<p> </p>

<p>This is a topology running as our integration test using <tt>Testing.completeTopology()</tt>. Both the stack traces point to the same code in the <tt>TupleCaptureBolt</tt> - its <tt>name</tt> field is not safely published (it should be marked <tt>final</tt>), and the internal <tt>HashMap</tt> does not safely store the data put in it. Perhaps it should be a <tt>ConcurrentHashMap</tt>?</p>

<p>Would you accept a PR with a more detailed analysis, or are you going to investigate on your side?</p>

---
<details><summary><i>Originally reported by <a title="Petr Janeček" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JanecekPetr">JanecekPetr</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3422" target="_blank">TupleCaptureBolt is not thread-safe</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Petr Janeček" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JanecekPetr">JanecekPetr</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-07-08T19:01:53+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Good catch. We'd be happy to see a PR to fix this. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JanecekPetr" class="user-hover" rel="JanecekPetr">Petr Janeček</a>, great job. Merged to master.</p>
