### ISSUE TITLE
[STORM-3466] storm-kafka-monitor not found jar

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7248]
<p>Hi, i'm a beginner to the storm. in order words, i'm a newbie.</p>

<p> </p>

<p>I have tried to upgrade from Storm 1.2.2 to 2.0.0. and confirmed that kafka spout lag does not work. changed the value of ui.disable.spout.lag.monitoring to false, but it did not work.</p>

<p>So I checked the log of storm ui and got the following error message.</p>

<p> </p>

<p>org.apache.storm.utils.ShellUtils$ExitCodeException: Error: Could not find or load main class .apache-storm-2.0.0.lib-tools.storm-kafka-monitor.audience-annotations-0.5.0.jar</p>

<p>at org.apache.storm.utils.ShellUtils.runCommand(ShellUtils.java:271) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span><br/>
 at org.apache.storm.utils.ShellUtils.run(ShellUtils.java:194) ~<span class="error">&#91;storm-client-2.0.0.jar:2.0.0&#93;</span>...</p>

<p> </p>

<p>In version 1.2.2, the storm-kafka-monitor works fine. However, version 2.0.0 throws an error.</p>

---
<details><summary><i>Originally reported by <a title="jongho lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=larry lim">larry lim</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3466" target="_blank">storm-kafka-monitor not found jar</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="jongho lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=larry lim">larry lim</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-08-10T23:16:06+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=larry lim">larry lim</a>:</i>
<p>I think it is a shell path expansion problem. </p>

<p>[reference|<a href="https://stackoverflow.com/questions/38757649/why-do-i-use-double-quotes-in-shell-scripts" class="external-link" target="_blank" rel="nofollow noopener">https://stackoverflow.com/questions/38757649/why-do-i-use-double-quotes-in-shell-scripts</a>]</p>

<p> </p>

<p>In storm 2.0.0, java classpath of storm-kafka-monitor used wildcard " * ". It is interpreted as "a.jar b.jar c.jar" (separator is white space). </p>

<p>but the classpath option of the java command has to be passed "a.jar:b.jar:c.jar" for multiple paths. (in linux, separator is colon). therefore java commands do not understand this and throw an error.</p>

<p> </p>

<p>in storm 1.2.2, java classpath wildcard of storm-kafka-monitor is interpreted as a single jar file. so it worked.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=larry+lim" class="user-hover" rel="larry lim">jongho lim</a>. I merged it to master</p>
