### ISSUE TITLE
[STORM-3476] LocalizedResourceRetentionSet cleanup causing excessive load on Hadoop namenode

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7258]
<p>One of our local dev Hadoop devs noticed our storm user was by far creating the heaviest load on our production Hadoop cluster.  Looking at one of the heaviest supervisor nodes, and comparing debug logs to the Hadoop audit log, it looks like LocalizedResourceRetentionSet cleanup was constantly doing opens and never deleting any files.</p>

<p> </p>

<p>The frequency can be addressed by supervisor.localizer.cleanup.interval.ms, but even so, it seems we will continually look for files to delete even when the target size is acceptable, resulting in unnecessary calls to Hadoop.</p>

<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3476" target="_blank">LocalizedResourceRetentionSet cleanup causing excessive load on Hadoop namenode</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:23+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">Aaron Gresch</a>, merged to master</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>I think this is causing the supervisor to keep trying to download blobs, even after they're removed from Nimbus. This is e.g. the case when you kill a topology. The supervisor loops logs like </p>

<p>	at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
2019-08-27 22:25:31.509 o.a.s.l.AsyncLocalizer AsyncLocalizer Executor - 0 <span class="error">&#91;WARN&#93;</span> Failed to download blob LOCAL TOPO BLOB TOPO_CODE test-1-1566937202 will try again in 100 ms<br/>
org.apache.storm.generated.KeyNotFoundException: null<br/>
	at org.apache.storm.generated.Nimbus$getBlobMeta_result$getBlobMeta_resultStandardScheme.read(Nimbus.java:25919) ~<span class="error">&#91;storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$getBlobMeta_result$getBlobMeta_resultStandardScheme.read(Nimbus.java:25887) ~<span class="error">&#91;storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$getBlobMeta_result.read(Nimbus.java:25818) ~<span class="error">&#91;storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:88) ~<span class="error">&#91;storm-shaded-deps-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.recv_getBlobMeta(Nimbus.java:794) ~<span class="error">&#91;storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Client.getBlobMeta(Nimbus.java:781) ~<span class="error">&#91;storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.blobstore.NimbusBlobStore.getBlobMeta(NimbusBlobStore.java:85) ~<span class="error">&#91;storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.localizer.LocallyCachedTopologyBlob.getRemoteVersion(LocallyCachedTopologyBlob.java:127) ~<span class="error">&#91;storm-server-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at org.apache.storm.localizer.AsyncLocalizer.lambda$downloadOrUpdate$10(AsyncLocalizer.java:265) ~<span class="error">&#91;storm-server-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT&#93;</span><br/>
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) <span class="error">&#91;?:1.8.0_144&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_144&#93;</span></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>I'll put up a PR to revert the change, we should find a fix that doesn't have this issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
