### ISSUE TITLE
[STORM-3511] Nimbus logs got flood with TTransportException Error messages (because of thrift 0.12.0)

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7293]
<p>Submitting a wordCountTopology works in secure cluster. But the following</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2019-09-25 13:53:46.560 o.a.s.t.s.TThreadPoolServer pool-15-thread-1 [ERROR] Thrift error occurred during processing of message.
org.apache.storm.thrift.transport.TTransportException: <span class="code-keyword">null</span>
at org.apache.storm.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.transport.TTransport.readAll(TTransport.java:86) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.transport.TSaslTransport.readLength(TSaslTransport.java:374) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:451) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.transport.TSaslTransport.read(TSaslTransport.java:433) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.transport.TSaslServerTransport.read(TSaslServerTransport.java:43) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.transport.TTransport.readAll(TTransport.java:86) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:27) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.security.auth.sasl.SaslTransportPlugin$TUGIWrapProcessor.process(SaslTransportPlugin.java:147) ~[storm-client-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:310) [shaded-deps-2.0.1.y.jar:2.0.1.y]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_181]
</pre>
</div></div>
<p>flood the nimbus log. (2.0.1.y is our internal version. The code is basically community 2.0.0)</p>

<p>This is similar to the issue found in Thrift community and got fixed in 0.13.0 but it's not released yet <a href="https://issues.apache.org/jira/browse/THRIFT-4805" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/THRIFT-4805</a></p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3511" target="_blank">Nimbus logs got flood with TTransportException Error messages (because of thrift 0.12.0)</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Luke Marjoram" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Marjoral">Marjoral</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-01-03T15:59:06+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>This is also present in the supervisor logs, logged every second</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thrift 0.13 appears to be out, so you could try bumping the version in Storm to see if this fixes the issue?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marjoral">marjoral</a>:</i>
<p>I updated to Thrift 0.13 on v2.1.X, and it resolved all stacks of this nature in both the nimbus and supervisor logs.</p>

<p>Would it be possible for someone to include this fix in the next patch?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Marjoral" class="user-hover" rel="Marjoral">Marjoral</a> Can you file a pull request against master and 2.1.x-branch to upgrade thrift to 0.13? Thanks</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Marjoral" class="user-hover" rel="Marjoral">Marjoral</a> I merged this to master and 2.1.x-branch</p>
