### ISSUE TITLE
[STORM-3512] Nimbus failing on startup with `GLIBC_2.12' not found

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7294]
<p>Nimbus failing to start with and exception (see below).</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2019-09-25 17:21:56.013 o.a.s.u.Utils main [ERROR] Received error in thread main.. terminating server...
java.lang.Error: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni3787537456845796855.so: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by /tmp/librocksdbjni3787537456845796855.so)
at org.apache.storm.utils.Utils.handleUncaughtException(Utils.java:647) ~[storm-client-2.0.0.jar:2.0.0]
at org.apache.storm.utils.Utils.handleUncaughtException(Utils.java:626) ~[storm-client-2.0.0.jar:2.0.0]
at org.apache.storm.utils.Utils.lambda$createDefaultUncaughtExceptionHandler$2(Utils.java:982) ~[storm-client-2.0.0.jar:2.0.0]
at java.lang.<span class="code-object">ThreadGroup</span>.uncaughtException(<span class="code-object">ThreadGroup</span>.java:1057) [?:1.8.0_211]
at java.lang.<span class="code-object">ThreadGroup</span>.uncaughtException(<span class="code-object">ThreadGroup</span>.java:1052) [?:1.8.0_211]
at java.lang.<span class="code-object">Thread</span>.dispatchUncaughtException(<span class="code-object">Thread</span>.java:1959) [?:1.8.0_211]
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni3787537456845796855.so: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by /tmp/librocksdbjni3787537456845796855.so)
at java.lang.<span class="code-object">ClassLoader</span>$NativeLibrary.load(Native Method) ~[?:1.8.0_211]
at java.lang.<span class="code-object">ClassLoader</span>.loadLibrary0(<span class="code-object">ClassLoader</span>.java:1941) ~[?:1.8.0_211]
at java.lang.<span class="code-object">ClassLoader</span>.loadLibrary(<span class="code-object">ClassLoader</span>.java:1824) ~[?:1.8.0_211]
at java.lang.<span class="code-object">Runtime</span>.load0(<span class="code-object">Runtime</span>.java:809) ~[?:1.8.0_211]
at java.lang.<span class="code-object">System</span>.load(<span class="code-object">System</span>.java:1086) ~[?:1.8.0_211]
at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78) ~[rocksdbjni-5.8.6.jar:?]
at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56) ~[rocksdbjni-5.8.6.jar:?]
at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64) ~[rocksdbjni-5.8.6.jar:?]
at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35) ~[rocksdbjni-5.8.6.jar:?]
at org.apache.storm.metricstore.rocksdb.RocksDbStore.prepare(RocksDbStore.java:67) ~[storm-server-2.0.0.jar:2.0.0]
at org.apache.storm.metricstore.MetricStoreConfig.configure(MetricStoreConfig.java:33) ~[storm-server-2.0.0.jar:2.0.0]
at org.apache.storm.daemon.nimbus.Nimbus.<init>(Nimbus.java:528) ~[storm-server-2.0.0.jar:2.0.0]
at org.apache.storm.daemon.nimbus.Nimbus.<init>(Nimbus.java:471) ~[storm-server-2.0.0.jar:2.0.0]
at org.apache.storm.daemon.nimbus.Nimbus.<init>(Nimbus.java:465) ~[storm-server-2.0.0.jar:2.0.0]
at org.apache.storm.daemon.nimbus.Nimbus.launchServer(Nimbus.java:1282) ~[storm-server-2.0.0.jar:2.0.0]
at org.apache.storm.daemon.nimbus.Nimbus.launch(Nimbus.java:1307) ~[storm-server-2.0.0.jar:2.0.0]
at org.apache.storm.daemon.nimbus.Nimbus.main(Nimbus.java:1312) ~[storm-server-2.0.0.jar:2.0.0]
 </pre>
</div></div>
<p> </p>

<p>Environment:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
>>> uname -a
Linux gctdwp03 3.0.101-108.98-<span class="code-keyword">default</span> #1 SMP Mon Jul 15 13:58:06 UTC 2019 (262a94d) x86_64 x86_64 x86_64 GNU/Linux
 
>>> cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4</pre>
</div></div>
<p> </p>

---
<details><summary><i>Originally reported by <a title="Sergey Titov" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=titoserr">titoserr</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3512" target="_blank">Nimbus failing on startup with `GLIBC_2.12' not found</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Sergey Titov" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=titoserr">titoserr</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-01-24T11:39:49+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=titoserr">titoserr</a>:</i>
<p>Seems its related to metrics store RocksDB. Is there a way I can disable it in config to bypass this initialization error?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>We intended to allow Storm to start without it <a href="https://github.com/apache/storm/blob/822a4685c0278aba9d4e0f43104bc4f86a462222/storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java#L533" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/822a4685c0278aba9d4e0f43104bc4f86a462222/storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java#L533</a>. Since you are getting an Error and not an Exception, Nimbus fails to start.</p>

<p>You can replace the MetricStore by setting the storm.metricstore.class setting, see <a href="https://github.com/apache/storm/blob/822a4685c0278aba9d4e0f43104bc4f86a462222/storm-server/src/main/java/org/apache/storm/metricstore/MetricStoreConfig.java#L31" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/822a4685c0278aba9d4e0f43104bc4f86a462222/storm-server/src/main/java/org/apache/storm/metricstore/MetricStoreConfig.java#L31</a>. I think you could e.g. point it to an empty implementation. You probably need to make an empty implementation and put it in Storm's /lib directory in order for Nimbus to pick it up.</p>

<p>Edit: You could probably also install glibc to make rocksdb work instead.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=titoserr">titoserr</a>:</i>
<p>Thanks,</p>

<p>do you think it make sense to raise a PR with an empty implementation so it is available in Storm?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Sure, sounds good. I think people should probably try to get RocksDB running as it will be hard to monitor Storm without it, but allowing people to opt out would be fine.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>There is now a "NoOpMetricStore" class that can be used as an empty metric store implementation for platforms that can't run RocksDB. Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=titoserr" class="user-hover" rel="titoserr">titoserr</a>.</p>
