### ISSUE TITLE
[STORM-3523] supervisor restarts when releasing slot with missing file

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7305]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2019-10-03 16:25:32.809 o.a.s.d.s.Slot SLOT_6719 [ERROR] Error when processing event
java.io.FileNotFoundException: File <span class="code-quote">'x/storm/supervisor/stormdist/xxx-190213-004131-001-209-1550018519/stormconf.ser'</span> does not exist
at org.apache.storm.shade.org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:297) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.shade.org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1851) ~[shaded-deps-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfGivenPath(ConfigUtils.java:308) ~[storm-client-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfImpl(ConfigUtils.java:469) ~[storm-client-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.utils.ConfigUtils.readSupervisorStormConf(ConfigUtils.java:303) ~[storm-client-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.localizer.AsyncLocalizer.getLocalResources(AsyncLocalizer.java:359) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.localizer.AsyncLocalizer.releaseSlotFor(AsyncLocalizer.java:460) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.supervisor.Slot.handleWaitingForBlobLocalization(Slot.java:435) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:229) ~[storm-server-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:900) [storm-server-2.0.1.y.jar:2.0.1.y]
2019-10-03 16:25:32.810 o.a.s.u.Utils SLOT_6719 [ERROR] Halting process: Error when processing an event
java.lang.RuntimeException: Halting process: Error when processing an event
at org.apache.storm.utils.Utils.exitProcess(Utils.java:550) [storm-client-2.0.1.y.jar:2.0.1.y]
at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:947) [storm-server-2.0.1.y.jar:2.0.1.y]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3523" target="_blank">supervisor restarts when releasing slot with missing file</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-10-31T18:05:00+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Changed the fixed version to 2.2.0 since it's only merged into master</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>:</i>
<p>It turns out that handling this exception exposed the root cause for us.... </p>

<p> </p>

<p>With the exception, the supervisor would restart and fix itself. </p>

<p>Handling the exception, we sometimes would see workers failing to start.  Investigating further, we found deadlocks in the AsyncLocalizer due to running with only 3 threads.  This was just a setting we carried forward from our older pre-2.x clusters.</p>

<p> </p>

<p>I think it would be best to revert this change and add a comment regarding deadlock possibilities.</p>

<p> </p>

<p>It also appears that running the localizer this way was the actual root cause for <a href="https://issues.apache.org/jira/browse/STORM-3168" title="AsyncLocalizer cleanup appears to crash" class="issue-link" data-issue-key="STORM-3168"><del>STORM-3168</del></a>.  However, the change I made there still seems valid.</p>

<p> </p>

<p> </p>

<p> </p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">agresch</a> I merged it to master</p>
