### ISSUE TITLE
[STORM-3537] Ports configed in storm.yaml file can be used by other application.

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7319]
<p>When submit a storm topology, it fail if the port is used by other application, for example a python Flask application.  </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-comment">//代码占位符
</span><span class="code-comment">// storm.yaml
</span>supervisor.slots.ports:
 - 6720orc@bj2904:

<span class="code-comment">// start storm nibums ans Supervisor
</span>
<span class="code-comment">// start python flask 
</span>~/program/simhash_doc_title$ ./start.sh 
 * Serving Flask app <span class="code-quote">"/home/orc/program/simhash_doc_title/simhash.py"</span>
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http:<span class="code-comment">//0.0.0.0:6720/ (Press CTRL+C to quit)
</span>

<span class="code-comment">// submit storm topology
</span>2019-11-15 18:16:12.310 o.a.s.u.Utils main [ERROR] Received error in thread main.. terminating server...
java.lang.Error: java.security.PrivilegedActionException: java.net.BindException: Address already in use
    at org.apache.storm.utils.Utils.handleUncaughtException(Utils.java:653) ~[storm-client-2.1.0.jar:2.1.0]
    at org.apache.storm.utils.Utils.handleUncaughtException(Utils.java:632) ~[storm-client-2.1.0.jar:2.1.0]
    at org.apache.storm.utils.Utils.lambda$createDefaultUncaughtExceptionHandler$2(Utils.java:1014) ~[storm-client-2.1.0.jar:2.1.0]
    at java.lang.<span class="code-object">ThreadGroup</span>.uncaughtException(<span class="code-object">ThreadGroup</span>.java:1057) [?:1.8.0_191]
    at java.lang.<span class="code-object">ThreadGroup</span>.uncaughtException(<span class="code-object">ThreadGroup</span>.java:1052) [?:1.8.0_191]
    at java.lang.<span class="code-object">Thread</span>.dispatchUncaughtException(<span class="code-object">Thread</span>.java:1959) [?:1.8.0_191]
Caused by: java.security.PrivilegedActionException
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
    at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_191]
    at org.apache.storm.daemon.worker.Worker.start(Worker.java:180) ~[storm-client-2.1.0.jar:2.1.0]
    at org.apache.storm.daemon.worker.Worker.main(Worker.java:144) ~[storm-client-2.1.0.jar:2.1.0]
Caused by: java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_191]
    at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_191]
    at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_191]
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_191]
    at org.apache.storm.shade.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:130) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at org.apache.storm.shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[storm-shaded-deps-2.1.0.jar:2.1.0]
    at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) ~[?:1.8.0_191]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Wu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Janze">Janze</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3537" target="_blank">Ports configed in storm.yaml file can be used by other application.</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Bug
<li><b>resolved</b>: 2019-11-15T15:30:27+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Yes, you can restart the supervisor, and it will restart the workers on the new set of ports you've specified.</p>

<p>There is no way that I know of to reserve the ports in a safe way. If we make the supervisor hold on to the ports until the workers start, there's still going to be a gap between the supervisor releasing the port, and the worker acquiring the port, where some other application could acquire it. Additionally I believe ports often have a timeout on them before they can be acquired by other applications, and we'd have to deal with that before we could start the workers. </p>
