### ISSUE TITLE
[STORM-3549] use of topology specific jaas conf doesn't work with kafka

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7331]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2019-09-17 19:22:23.006 o.a.s.u.Utils <span class="code-object">Thread</span>-22-line-reader-spout-executor[4, 4] [ERROR] Async loop died!
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:702) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:557) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:540) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.internal.ConsumerFactoryDefault.createConsumer(ConsumerFactoryDefault.java:26) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.internal.ConsumerFactoryDefault.createConsumer(ConsumerFactoryDefault.java:22) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.KafkaSpout.open(KafkaSpout.java:147) ~[stormjar.jar:?]
	at org.apache.storm.executor.spout.SpoutExecutor.init(SpoutExecutor.java:148) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.spout.SpoutExecutor.call(SpoutExecutor.java:158) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.spout.SpoutExecutor.call(SpoutExecutor.java:55) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.Utils$1.run(Utils.java:425) [storm-client-2.0.1.y.jar:2.0.1.y]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_181]
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Could not login: the client is being asked <span class="code-keyword">for</span> a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:86) ~[stormjar.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:70) ~[stormjar.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:83) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:623) ~[stormjar.jar:?]
	... 10 more
Caused by: javax.security.auth.login.LoginException: Could not login: the client is being asked <span class="code-keyword">for</span> a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
	at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:940) ~[?:1.8.0_181]
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760) ~[?:1.8.0_181]
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_181]
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:69) ~[stormjar.jar:?]
	at org.apache.kafka.common.security.kerberos.KerberosLogin.login(KerberosLogin.java:110) ~[stormjar.jar:?]
	at org.apache.kafka.common.security.authenticator.LoginManager.&lt;init&gt;(LoginManager.java:46) ~[stormjar.jar:?]
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:68) ~[stormjar.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:78) ~[stormjar.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:70) ~[stormjar.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:83) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:623) ~[stormjar.jar:?]
	... 10 more
2019-09-17 19:22:23.196 o.a.s.e.e.ReportError <span class="code-object">Thread</span>-22-line-reader-spout-executor[4, 4] [ERROR] Error
java.lang.RuntimeException: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.storm.utils.Utils$1.run(Utils.java:445) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_181]
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:702) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:557) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:540) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.internal.ConsumerFactoryDefault.createConsumer(ConsumerFactoryDefault.java:26) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.internal.ConsumerFactoryDefault.createConsumer(ConsumerFactoryDefault.java:22) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.KafkaSpout.open(KafkaSpout.java:147) ~[stormjar.jar:?]
	at org.apache.storm.executor.spout.SpoutExecutor.init(SpoutExecutor.java:148) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.spout.SpoutExecutor.call(SpoutExecutor.java:158) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.spout.SpoutExecutor.call(SpoutExecutor.java:55) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.Utils$1.run(Utils.java:425) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	... 1 more
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Could not login: the client is being asked <span class="code-keyword">for</span> a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:86) ~[stormjar.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:70) ~[stormjar.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:83) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:623) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:557) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:540) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.internal.ConsumerFactoryDefault.createConsumer(ConsumerFactoryDefault.java:26) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.internal.ConsumerFactoryDefault.createConsumer(ConsumerFactoryDefault.java:22) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.KafkaSpout.open(KafkaSpout.java:147) ~[stormjar.jar:?]
	at org.apache.storm.executor.spout.SpoutExecutor.init(SpoutExecutor.java:148) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.spout.SpoutExecutor.call(SpoutExecutor.java:158) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.spout.SpoutExecutor.call(SpoutExecutor.java:55) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.Utils$1.run(Utils.java:425) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	... 1 more
Caused by: javax.security.auth.login.LoginException: Could not login: the client is being asked <span class="code-keyword">for</span> a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
	at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:940) ~[?:1.8.0_181]
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760) ~[?:1.8.0_181]
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_181]
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_181]
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:69) ~[stormjar.jar:?]
	at org.apache.kafka.common.security.kerberos.KerberosLogin.login(KerberosLogin.java:110) ~[stormjar.jar:?]
	at org.apache.kafka.common.security.authenticator.LoginManager.&lt;init&gt;(LoginManager.java:46) ~[stormjar.jar:?]
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:68) ~[stormjar.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:78) ~[stormjar.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:70) ~[stormjar.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:83) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:623) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:557) ~[stormjar.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.&lt;init&gt;(KafkaConsumer.java:540) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.internal.ConsumerFactoryDefault.createConsumer(ConsumerFactoryDefault.java:26) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.internal.ConsumerFactoryDefault.createConsumer(ConsumerFactoryDefault.java:22) ~[stormjar.jar:?]
	at org.apache.storm.kafka.spout.KafkaSpout.open(KafkaSpout.java:147) ~[stormjar.jar:?]
	at org.apache.storm.executor.spout.SpoutExecutor.init(SpoutExecutor.java:148) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.spout.SpoutExecutor.call(SpoutExecutor.java:158) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.spout.SpoutExecutor.call(SpoutExecutor.java:55) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.Utils$1.run(Utils.java:425) ~[storm-client-2.0.1.y.jar:2.0.1.y]
	... 1 more
2019-09-17 19:22:23.277 o.a.s.u.Utils <span class="code-object">Thread</span>-22-line-reader-spout-executor[4, 4] [ERROR] Halting process: Worker died
java.lang.RuntimeException: Halting process: Worker died
	at org.apache.storm.utils.Utils.exitProcess(Utils.java:550) [storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.utils.Utils$3.run(Utils.java:846) [storm-client-2.0.1.y.jar:2.0.1.y]
	at org.apache.storm.executor.error.ReportErrorAndDie.uncaughtException(ReportErrorAndDie.java:41) [storm-client-2.0.1.y.jar:2.0.1.y]
	at java.lang.<span class="code-object">Thread</span>.dispatchUncaughtException(<span class="code-object">Thread</span>.java:1959) [?:1.8.0_181]
2019-09-17 19:22:23.281 o.a.s.u.Utils <span class="code-object">Thread</span>-26 [INFO] Halting after 1 seconds
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3549" target="_blank">use of topology specific jaas conf doesn't work with kafka</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-01-08T15:26:35+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=govind">govind</a>:</i>
<p>Thank you <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">agresch</a></p>
