### ISSUE TITLE
[STORM-3552] Storm CLI set_log_level no longer updates the log level

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7334]
<p>Using the example StatefulWindowingTopology, when trying to update the log level via command line with the following command a NullPointer is thrown in the worker log and the log level is not updated.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
storm set_log_level -l ROOT=DEBUG:0 test</pre>
</div></div>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2019-12-09 17:16:02.600+0100 o.a.s.s.o.a.c.f.i.CuratorFrameworkImpl main-EventThread [ERROR] Event listener threw exception
java.lang.NullPointerException: <span class="code-keyword">null</span>
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_131]
at org.apache.logging.log4j.Level.getLevel(Level.java:261) ~[log4j-api-2.11.2.jar:2.11.2]
at org.apache.storm.daemon.worker.LogConfigManager.setLoggerLevel(LogConfigManager.java:145) ~[storm-client-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.daemon.worker.LogConfigManager.processLogConfigChange(LogConfigManager.java:98) ~[storm-client-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.daemon.worker.Worker.checkLogConfigChanged(Worker.java:422) ~[storm-client-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.cluster.StormClusterStateImpl.issueMapCallback(StormClusterStateImpl.java:177) ~[storm-client-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.cluster.StormClusterStateImpl$1.changed(StormClusterStateImpl.java:122) ~[storm-client-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.cluster.ZKStateStorage$ZkWatcherCallBack.execute(ZKStateStorage.java:243) ~[storm-client-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.zookeeper.ClientZookeeper.lambda$mkClientImpl$0(ClientZookeeper.java:314) ~[storm-client-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl$7.apply(CuratorFrameworkImpl.java:1048) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl$7.apply(CuratorFrameworkImpl.java:1041) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.shaded.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:92) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.processEvent(CuratorFrameworkImpl.java:1040) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.access$000(CuratorFrameworkImpl.java:66) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl$1.process(CuratorFrameworkImpl.java:126) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.curator.ConnectionState.process(ConnectionState.java:185) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:533) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]
at org.apache.storm.shade.org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508) [storm-shaded-deps-2.1.0.jar:2.1.1-SNAPSHOT]</pre>
</div></div>
<p>This appears to be a regression from the migration from clojure to java in <a href="https://issues.apache.org/jira/browse/STORM-1267" title="port backtype.storm.command.set-log-level to java" class="issue-link" data-issue-key="STORM-1267"><del>STORM-1267</del></a></p>

---
<details><summary><i>Originally reported by <a title="Luke Marjoram" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Marjoral">Marjoral</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3552" target="_blank">Storm CLI set_log_level no longer updates the log level</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Luke Marjoram" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Marjoral">Marjoral</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-01-03T06:24:10+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Marjoral" class="user-hover" rel="Marjoral">Marjoral</a>. I merged this to master and 2.1.x-branch.  Also I added you to "Contributor" role and assigned this jira to you.</p>
