### ISSUE TITLE
[STORM-3556] blob meta exception in Nimbus log

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7338]
<p>Hi team,</p>

<p>When I kill topology on the UI, <span class="error">&#91;WARN&#93;</span> get blob meta exception will be thrown in the Nimbus log. Is it a bug?</p>

<p>2019-12-18 02:14:16.782 o.a.s.d.n.Nimbus pool-29-thread-46 <span class="error">&#91;INFO&#93;</span> Created download session ec557d66-96d9-4071-b99f-3122fa50f61c for word-count-9-1576653249-stormjar.jar<br/>
2019-12-18 02:14:16.794 o.a.s.d.n.Nimbus pool-29-thread-50 <span class="error">&#91;INFO&#93;</span> Created download session 1bbae64e-89c6-4337-b87b-634dbb78f61c for word-count-9-1576653249-stormconf.ser<br/>
2019-12-18 02:14:16.807 o.a.s.d.n.Nimbus pool-29-thread-40 <span class="error">&#91;INFO&#93;</span> Created download session a3f78bd3-673f-4780-a402-90708bd754f7 for word-count-9-1576653249-stormcode.ser<br/>
2019-12-18 02:14:17.472 o.a.s.d.n.Nimbus pool-29-thread-18 <span class="error">&#91;INFO&#93;</span> Created download session a05848fa-e83e-4c13-b025-f14a468acf14 for word-count-9-1576653249-stormjar.jar<br/>
2019-12-18 02:14:17.483 o.a.s.d.n.Nimbus pool-29-thread-58 <span class="error">&#91;INFO&#93;</span> Created download session 9119de95-cd34-48a4-b7ef-ae0f84de5689 for word-count-9-1576653249-stormcode.ser<br/>
2019-12-18 02:14:17.495 o.a.s.d.n.Nimbus pool-29-thread-29 <span class="error">&#91;INFO&#93;</span> Created download session d8d06e2e-e82c-46a8-beee-ee8bf313e584 for word-count-9-1576653249-stormconf.ser<br/>
2019-12-18 02:14:17.538 o.a.s.d.n.Nimbus pool-29-thread-21 <span class="error">&#91;INFO&#93;</span> Created download session f634e74b-a161-4295-bf17-bd631b3d6e6d for word-count-9-1576653249-stormjar.jar<br/>
2019-12-18 02:14:17.546 o.a.s.d.n.Nimbus pool-29-thread-18 <span class="error">&#91;INFO&#93;</span> Created download session 29e1592a-136a-4ff6-a4de-9c4420d55849 for word-count-9-1576653249-stormcode.ser<br/>
2019-12-18 02:14:17.557 o.a.s.d.n.Nimbus pool-29-thread-48 <span class="error">&#91;INFO&#93;</span> Created download session ca75e5b0-e855-4b5f-962f-f7accefdc260 for word-count-9-1576653249-stormconf.ser<br/>
2019-12-18 02:23:42.461 o.a.s.d.n.Nimbus pool-29-thread-36 <span class="error">&#91;INFO&#93;</span> TRANSITION: word-count-9-1576653249 KILL 5 true<br/>
2019-12-18 02:23:42.463 o.a.s.d.n.Nimbus pool-29-thread-36 <span class="error">&#91;INFO&#93;</span> Delaying event REMOVE for 5 secs for word-count-9-1576653249<br/>
2019-12-18 02:23:42.471 o.a.s.d.n.Nimbus pool-29-thread-36 <span class="error">&#91;INFO&#93;</span> Adding topo to history log: word-count-9-1576653249<br/>
2019-12-18 02:23:47.464 o.a.s.d.n.Nimbus timer <span class="error">&#91;INFO&#93;</span> TRANSITION: word-count-9-1576653249 REMOVE null false<br/>
2019-12-18 02:23:47.467 o.a.s.d.n.Nimbus timer <span class="error">&#91;INFO&#93;</span> Killing topology: word-count-9-1576653249<br/>
2019-12-18 02:25:58.331 o.a.s.d.n.Nimbus timer <span class="error">&#91;INFO&#93;</span> Cleaning up word-count-9-1576653249<br/>
2019-12-18 02:25:58.338 o.a.s.c.StormClusterStateImpl timer <span class="error">&#91;INFO&#93;</span> Removing worker keys under /secretkeys/NIMBUS/word-count-9-1576653249<br/>
2019-12-18 02:25:58.339 o.a.s.c.StormClusterStateImpl timer <span class="error">&#91;INFO&#93;</span> Removing worker keys under /secretkeys/DRPC/word-count-9-1576653249<br/>
2019-12-18 02:25:58.340 o.a.s.c.StormClusterStateImpl timer <span class="error">&#91;INFO&#93;</span> Removing worker keys under /secretkeys/SUPERVISOR/word-count-9-1576653249<br/>
2019-12-18 02:25:58.341 o.a.s.d.n.Nimbus timer <span class="error">&#91;INFO&#93;</span> Removing dependency jars from blobs - []<br/>
2019-12-18 02:26:04.774 o.a.s.d.n.Nimbus pool-29-thread-61 <span class="error">&#91;WARN&#93;</span> get blob meta exception.<br/>
org.apache.storm.utils.WrappedKeyNotFoundException: word-count-9-1576653249-stormcode.ser<br/>
	at org.apache.storm.blobstore.LocalFsBlobStore.getStoredBlobMeta(LocalFsBlobStore.java:257) ~<span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.blobstore.LocalFsBlobStore.getBlobMeta(LocalFsBlobStore.java:287) ~<span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.daemon.nimbus.Nimbus.getBlobMeta(Nimbus.java:3651) <span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Processor$getBlobMeta.getResult(Nimbus.java:3951) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Processor$getBlobMeta.getResult(Nimbus.java:3930) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:38) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:174) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) <span class="error">&#91;?:1.8.0_45&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) <span class="error">&#91;?:1.8.0_45&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_45&#93;</span><br/>
2019-12-18 02:26:04.784 o.a.s.d.n.Nimbus pool-29-thread-5 <span class="error">&#91;WARN&#93;</span> get blob meta exception.<br/>
org.apache.storm.utils.WrappedKeyNotFoundException: word-count-9-1576653249-stormjar.jar<br/>
	at org.apache.storm.blobstore.LocalFsBlobStore.getStoredBlobMeta(LocalFsBlobStore.java:257) ~<span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.blobstore.LocalFsBlobStore.getBlobMeta(LocalFsBlobStore.java:287) ~<span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.daemon.nimbus.Nimbus.getBlobMeta(Nimbus.java:3651) <span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Processor$getBlobMeta.getResult(Nimbus.java:3951) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.generated.Nimbus$Processor$getBlobMeta.getResult(Nimbus.java:3930) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:38) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:174) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
	at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) <span class="error">&#91;?:1.8.0_45&#93;</span><br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) <span class="error">&#91;?:1.8.0_45&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:745) <span class="error">&#91;?:1.8.0_45&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="AK47Sonic" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=AK47Sonic">AK47Sonic</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3556" target="_blank">blob meta exception in Nimbus log</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T09:54:05+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
