### ISSUE TITLE
[STORM-3561] java.lang.RuntimeException: java.io.UTFDataFormatException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7343]
<p>My application encountered the following problems online, which caused my worker to exit unexpectedly. Does anyone know why this is? I am considering whether to use the  java native serialization instead of Kryo</p>

<p> </p>

<p>2019-12-29 21:35:41.669 o.a.s.m.n.StormServerHandler Netty-server-localhost-1800-worker-1 <span class="error">&#91;ERROR&#93;</span> server errors in handling the request<br/>
java.lang.RuntimeException: java.io.eTFDataFormatException<br/>
 at org.apache.storm.serialization.SerializableSerializer.read(SerializableSerializer.java:53) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:793) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
 at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
 at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
 at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:689) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
 at org.apache.storm.serialization.KryoValuesDeserializer.deserializeFrom(KryoValuesDeserializer.java:31) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.serialization.KryoTupleDeserializer.deserialize(KryoTupleDeserializer.java:45) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.messaging.DeserializingConnectionCallback.recv(DeserializingConnectionCallback.java:66) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.messaging.netty.Server.enqueue(Server.java:146) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.messaging.netty.Server.received(Server.java:264) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.messaging.netty.StormServerHandler.channelRead(StormServerHandler.java:51) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span><br/>
 at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_231&#93;</span><br/>
Caused by: java.io.UTFDataFormatException<br/>
 at java.io.ObjectInputStream$BlockDataInputStream.readUTFSpan(ObjectInputStream.java:3470) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3414) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream$BlockDataInputStream.readUTF(ObjectInputStream.java:3226) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readUTF(ObjectInputStream.java:1133) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:768) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:891) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1857) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) ~<span class="error">&#91;?:1.8.0_231&#93;</span><br/>
 at org.apache.storm.serialization.SerializableSerializer.read(SerializableSerializer.java:51) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 ... 31 more<br/>
2019-12-29 21:35:41.673 o.a.s.m.n.StormServerHandler Netty-server-localhost-1800-worker-1 <span class="error">&#91;INFO&#93;</span> Received error in netty thread.. terminating server...<br/>
2019-12-29 21:35:41.674 o.a.s.d.w.Worker Thread-43 <span class="error">&#91;INFO&#93;</span> Shutting down worker owl_analyze_1228_0-16-1577543204 f611fb0f-3a97-4043-bb42-8f74190926ff-10.16.20.6 1800<br/>
2019-12-29 21:35:41.675 o.a.s.u.Utils Thread-42 <span class="error">&#91;INFO&#93;</span> Halting after 3 seconds</p>

---
<details><summary><i>Originally reported by <a title="Ryan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Ryanx">Ryanx</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3561" target="_blank">java.lang.RuntimeException: java.io.UTFDataFormatException</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2023-11-23T11:55:25+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>Could be related to ARIC-3582, could be caused by data corruption between workers?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are now using Kyro 5 in Storm 2.6.0 - this issue is most likely outdated. If it still happens with Storm 2.6.0, feel free to re-open</p>
