### ISSUE TITLE
[STORM-3582] Kryo errors when using custom serialization

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7364]
<p>(this has been reported on the user list in January and previously by a different user)<br/>
 <br/>
------------------------------------------------------------------------------------<br/>
 <br/>
My code works fine with Storm 1.x but the workers crash constantly with Storm 2.x <br/>
 <br/>
Some exceptions look like <br/>
 <br/>
<tt><em>com.esotericsoftware.kryo.KryoException: Buffer underflow.</em></tt><br/>
<tt><em>at com.esotericsoftware.kryo.io.Input.require(Input.java:199) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span></em></tt><br/>
<tt><em>at com.esotericsoftware.kryo.io.Input.readUtf8_slow(Input.java:575) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span></em></tt><br/>
<tt><em>at com.esotericsoftware.kryo.io.Input.readUtf8(Input.java:553) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span></em></tt><br/>
<tt><em>at com.esotericsoftware.kryo.io.Input.readString(Input.java:483) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span></em></tt></p>

<p><tt>whereas others are</tt><br/>
 <br/>
<tt><em>2020-01-21 11:13:39.368 o.a.s.m.n.StormServerHandler Netty-server-localhost-6701-worker-1 <span class="error">&#91;ERROR&#93;</span> server errors in handling the request</em></tt><br/>
{{_com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: <b>95</b><br/>
at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:137) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:670) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:781) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:153) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:793) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:689) ~<span class="error">&#91;kryo-3.0.3.jar:?&#93;</span><br/>
at org.apache.storm.serialization.KryoValuesDeserializer.deserializeFrom(KryoValuesDeserializer.java:31) ~<span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span>_}}</p>

<p><tt>the class ID values are random integers. </tt></p>

<p>{{}}<br/>
The tuples in my topologies contain mostly standard classes like String; the only exception is the following class <br/>
 <br/>
<a href="https://github.com/DigitalPebble/storm-crawler/blob/2.x/core/src/main/java/com/digitalpebble/stormcrawler/Metadata.java#L41" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DigitalPebble/storm-crawler/blob/2.x/core/src/main/java/com/digitalpebble/stormcrawler/Metadata.java#L41</a><br/>
 <br/>
for which we specify a custom serialization for Kryo.<br/>
 <br/>
My configurations contain<br/>
 </p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<td class='confluenceTd'> topology.kryo.register:</td>
<td class='confluenceTd'><ul class="alternate" type="square">
	<li>com.digitalpebble.stormcrawler.Metadata</li>
</ul>
</td>
</tr>
</tbody></table>
</div>

<p>to register the custom class.<br/>
 <br/>
The user who had reported the problem first also used custom serialization.<br/>
 <br/>
 <br/>
 </p>

---
<details><summary><i>Originally reported by <a title="Julien Nioche" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jnioche">jnioche</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3582" target="_blank">Kryo errors when using custom serialization</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2020-06-04T17:16:01+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>We've also come across this issue. We first encountered it by mismatch/decompression exceptions thrown by our custom Snappy `ListDelegateSerializer` implementation. This implies it may be an issue with a buffer being flushed on the sending worker.</p>

<p>Maybe it's to do with the size of the tuple?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>Another exception which may indicate it's a problem in kryo (this is when serializing an ack tuple):</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 32 out of bounds <span class="code-keyword">for</span> <span class="code-object">byte</span>[31]
 	at java.lang.<span class="code-object">System</span>.arraycopy(Native Method) ~[?:?]
 	at com.esotericsoftware.kryo.io.Output.toBytes(Output.java:130) ~[kryo-shaded-3.0.3.jar:?]
 	at org.apache.storm.serialization.KryoTupleSerializer.serialize(KryoTupleSerializer.java:41) ~[storm-client-2.1.0.jar:2.1.0]
 	at org.apache.storm.daemon.worker.WorkerState.checkSerialize(WorkerState.java:580) ~[storm-client-2.1.0.jar:2.1.0]
 	at org.apache.storm.executor.ExecutorTransfer.tryTransferLocal(ExecutorTransfer.java:99) ~[storm-client-2.1.0.jar:2.1.0]
 	at org.apache.storm.executor.ExecutorTransfer.tryTransfer(ExecutorTransfer.java:64) ~[storm-client-2.1.0.jar:2.1.0]
 	at org.apache.storm.executor.LocalExecutor$1.tryTransfer(LocalExecutor.java:36) ~[storm-client-2.1.0.jar:2.1.0]
 	at org.apache.storm.daemon.Task.sendUnanchored(Task.java:211) ~[storm-client-2.1.0.jar:2.1.0]
 	at org.apache.storm.executor.bolt.BoltOutputCollectorImpl.ack(BoltOutputCollectorImpl.java:128) ~[storm-client-2.1.0.jar:2.1.0]
 	at org.apache.storm.task.OutputCollector.ack(OutputCollector.java:181) ~[storm-client-2.1.0.jar:2.1.0]</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>Looking at the kryo code, this actually points towards it being a threading issue - could the same <tt>KryoValuesSerializer</tt> be accessed by more than one thread at once?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>I am interested to see what's going on. We have been using storm 2.x without any serious problem. Can you let me know how to reproduce this by providing a simple example so I can look into it? Thanks</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984">thecoop1984</a>:</i>
<p>We have found the issue that was causing our exceptions - in our bolts we have multiple threads that were accessing OutputCollectors concurrently. In storm 1, it seems that collectors are thread-safe, but in storm 2 they are not. This meant the serialization buffer was being written to by multiple threads at the same time, causing data corruption which was only spotted when it was deserialized on the target worker, resulting in seemingly random exceptions as the system tried to interpret the random data.</p>

<p>Adding a mutex to all calls to output collectors has fixed this problem for us.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thecoop1984" class="user-hover" rel="thecoop1984">thecoop1984</a> Thanks. You are right. OutputCollector is not thread-safe. I filed <a href="https://issues.apache.org/jira/browse/STORM-3620" title="Data corruption can happen when components are multi-threaded because of non thread-safe serializer" class="issue-link" data-issue-key="STORM-3620"><del>STORM-3620</del></a> for that issue.</p>

<p>I guess Kyro issue in this JIRA might still exist. <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jnioche" class="user-hover" rel="jnioche">jnioche</a> Could you help me reproduce it? Thanks</p>
