### ISSUE TITLE
[STORM-3598] Storm UI visualization throws NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7380]
<p>We encountered an issue with visualization on UI. </p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2020-03-09 19:59:01.756 o.a.s.d.u.r.StormApiResource qtp1919834117-167291 [ERROR] Failure getting topology visualization
java.lang.NullPointerException: <span class="code-keyword">null</span>
at org.apache.storm.stats.StatsUtil.mergeWithAddPair(StatsUtil.java:1855) ~[storm-server-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.stats.StatsUtil.expandAveragesSeq(StatsUtil.java:2308) ~[storm-server-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.stats.StatsUtil.aggregateAverages(StatsUtil.java:832) ~[storm-server-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.stats.StatsUtil.aggregateBoltStats(StatsUtil.java:731) ~[storm-server-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.stats.StatsUtil.boltStreamsStats(StatsUtil.java:900) ~[storm-server-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.daemon.ui.UIHelpers.getVisualizationData(UIHelpers.java:1939) ~[storm-webapp-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.daemon.ui.resources.StormApiResource.getTopologyVisualization(StormApiResource.java:423) ~[storm-webapp-2.2.0.y.jar:2.2.0.y]
</pre>
</div></div>
<p>This is a bug in the code. <a href="https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/stats/StatsUtil.java#L1846-L1858" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/stats/StatsUtil.java#L1846-L1858</a></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">for</span> (K kk : mm1.keySet()) {
    List seq1 = mm1.get(kk);
    List seq2 = mm2.get(kk);
    List sums = <span class="code-keyword">new</span> ArrayList();
    <span class="code-keyword">for</span> (<span class="code-object">int</span> i = 0; i < seq1.size(); i++) {
<span class="code-keyword">if</span> (seq1.get(i) <span class="code-keyword">instanceof</span> <span class="code-object">Long</span>) {
    sums.add(((<span class="code-object">Number</span>) seq1.get(i)).longValue() + ((<span class="code-object">Number</span>) seq2.get(i)).longValue());
} <span class="code-keyword">else</span> {
    sums.add(((<span class="code-object">Number</span>) seq1.get(i)).doubleValue() + ((<span class="code-object">Number</span>) seq2.get(i)).doubleValue());
}
    }
    tmp.put(kk, sums);
}
</pre>
</div></div>
<p>It assume mm1 and mm2 always have the same key, which is not true. </p>

<p>And it can be reproduced by my example code: </p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> class  WordCountTopology <span class="code-keyword">extends</span> ConfigurableTopology {
    <span class="code-keyword">private</span> <span class="code-keyword">static</span> <span class="code-keyword">final</span> Logger LOG = LoggerFactory.getLogger(WordCountTopology.class);

    <span class="code-keyword">public</span> <span class="code-keyword">static</span> void main(<span class="code-object">String</span>[] args) {
ConfigurableTopology.start(<span class="code-keyword">new</span> WordCountTopology(), args);
    }

    <span class="code-keyword">protected</span> <span class="code-object">int</span> run(<span class="code-object">String</span>[] args) {
TopologyBuilder builder = <span class="code-keyword">new</span> TopologyBuilder();

builder.setSpout(<span class="code-quote">"spout1"</span>, <span class="code-keyword">new</span> RandomSpout(1), 1);
builder.setSpout(<span class="code-quote">"spout2"</span>, <span class="code-keyword">new</span> RandomSpout(2), 1);
builder.setBolt(<span class="code-quote">"bolt"</span>, <span class="code-keyword">new</span> RandomBolt(), 2).directGrouping(<span class="code-quote">"spout1"</span>, <span class="code-quote">"stream1"</span>)
.directGrouping(<span class="code-quote">"spout2"</span>, <span class="code-quote">"stream2"</span>);

<span class="code-object">String</span> topologyName = <span class="code-quote">"word-count"</span>;

conf.setNumWorkers(3);

<span class="code-keyword">if</span> (args != <span class="code-keyword">null</span> && args.length > 0) {
    topologyName = args[0];
}
<span class="code-keyword">return</span> submit(topologyName, conf, builder);
    }

    <span class="code-keyword">static</span> <span class="code-keyword">class </span>RandomSpout <span class="code-keyword">extends</span> BaseRichSpout {
<span class="code-object">String</span> stream;
<span class="code-object">int</span> id;

<span class="code-keyword">public</span> RandomSpout(<span class="code-object">int</span> id) {
    <span class="code-keyword">this</span>.id = id;
    stream = <span class="code-quote">"stream"</span> + id;
}

<span class="code-object">int</span> taskId = 0;
SpoutOutputCollector collector;
<span class="code-keyword">public</span> void open(Map<<span class="code-object">String</span>, <span class="code-object">Object</span>> conf, TopologyContext context, SpoutOutputCollector collector) {
    taskId = context.getThisTaskId();
    <span class="code-keyword">this</span>.collector = collector;
}

/**
 * Different spout send tuples to different bolt via different stream.
 */
<span class="code-keyword">public</span> void nextTuple() {
    LOG.info(<span class="code-quote">"emitting {}"</span>, id);
    <span class="code-keyword">if</span> (id == 1) {
Values val = <span class="code-keyword">new</span> Values(<span class="code-quote">"test a sentence"</span>);
collector.emitDirect(2, stream, val, val);
    } <span class="code-keyword">else</span> {
Values val = <span class="code-keyword">new</span> Values(<span class="code-quote">"test 2 sentence"</span>);
collector.emitDirect(3, stream, val, val);
    }
    <span class="code-keyword">try</span> {
<span class="code-object">Thread</span>.sleep(1000);
    } <span class="code-keyword">catch</span> (InterruptedException e) {
e.printStackTrace();
    }
}

<span class="code-keyword">public</span> void declareOutputFields(OutputFieldsDeclarer declarer) {
    declarer.declareStream(stream, <span class="code-keyword">new</span> Fields(<span class="code-quote">"word"</span>));
}
    }

    <span class="code-keyword">static</span> <span class="code-keyword">class </span>RandomBolt <span class="code-keyword">extends</span> BaseBasicBolt {

<span class="code-keyword">public</span> void execute(Tuple input, BasicOutputCollector collector) {
    LOG.info(<span class="code-quote">"executing:"</span> + input.getSourceComponent());
}

<span class="code-keyword">public</span> void declareOutputFields(OutputFieldsDeclarer declarer) {

}
    }
}
</pre>
</div></div>

<p> In this example, one of the bolt will only receive data from stream1 and another bolt will only receive data from stream2. So in the map, </p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
    List seq1 = mm1.get(kk);
    List seq2 = mm2.get(kk);
</pre>
</div></div>
<p>seq1 is null if kk is stream1, seq2 is null if kk is stream2.</p>

<p> </p>

<p> We have other places aggregating executor stats without this problem because it's using different code <a href="https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/stats/StatsUtil.java#L502-L513" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/stats/StatsUtil.java#L502-L513</a> and this problem has been taken cared of.</p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3598" target="_blank">Storm UI visualization throws NullPointerException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-03-13T14:26:24+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Merged to master and 2.1.x-branch</p>
