### ISSUE TITLE
[STORM-3606] AutoTGT shouldn't invoke TGT renewal thread (from UserGroupInformation.loginUserFromSubject)

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7388]
<p>When hadoop security is enabled, <br/>
<a href="https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java#L199-L209" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java#L199-L209</a></p>

<p>AutoTGT will invoke "loginUserFromSubject", and it will spawn a TGT renewal thread ("TGT Renewer for <username>"). <br/>
<a href="https://github.com/apache/hadoop/blob/branch-2.8.5/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L928-L957" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/hadoop/blob/branch-2.8.5/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L928-L957</a></p>

<p>which will eventually invoke system command "kinit -R", and then fail with the exception</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
org.apache.hadoop.util.Shell$ExitCodeException: kinit: Credentials cache file <span class="code-quote">'/tmp/krb5cc_xxx'</span> not found <span class="code-keyword">while</span> renewing credentials

	at org.apache.hadoop.util.Shell.runCommand(Shell.java:1004) ~[stormjar.jar:?]
	at org.apache.hadoop.util.Shell.run(Shell.java:898) ~[stormjar.jar:?]
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1213) ~[stormjar.jar:?]
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:1307) ~[stormjar.jar:?]
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:1289) ~[stormjar.jar:?]
	at org.apache.hadoop.security.UserGroupInformation$1.run(UserGroupInformation.java:1011) [stormjar.jar:?]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_181]
</pre>
</div></div>

<p>"kinit" will never work from worker process since Storm don't keep TGT in local cache. Instead, TGT is saved in zookeeper and in memory of Worker process. </p>

<p>This exception is confusing but not harmful to topologies. And the TGT renewal thread will eventually abort. </p>

<p>It's better to find a real solution for it. But for now we can document what might happen in AutoTGT code.</p>

<p>To be clear, we still need loginUserFromSubject or some sort but we don't want to spawn TGT renewal thread.  This is found with hadoop-2.8.5. Other versions are similar. But it can also change in the future release.</p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3606" target="_blank">AutoTGT shouldn't invoke TGT renewal thread (from UserGroupInformation.loginUserFromSubject)</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-04-08T21:19:53+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtasks:

- STORM-3607

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>:</i>
<p>user will see workers restart due to a NPE if they upload credentials before the TGT renewal thread runs the kinit -R command.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
020-04-01 14:36:53.005 o.a.s.u.Utils TGT Renewer <span class="code-keyword">for</span> XXX [ERROR] Received error in thread TGT Renewer <span class="code-keyword">for</span> XXX.. terminating server... java.lang.Error: java.lang.NullPointerException         at org.apache.storm.utils.Utils.handleUncaughtException(Utils.java:694) ~[storm-client-2.2.0.y.jar:2.2.0.y]         at org.apache.storm.utils.Utils.handleUncaughtException(Utils.java:673) ~[storm-client-2.2.0.y.jar:2.2.0.y]         at org.apache.storm.utils.Utils.lambda$createDefaultUncaughtExceptionHandler$2(Utils.java:1055) ~[storm-client-2.2.0.y.jar:2.2.0.y]         at java.lang.<span class="code-object">ThreadGroup</span>.uncaughtException(<span class="code-object">ThreadGroup</span>.java)         at java.lang.<span class="code-object">ThreadGroup</span>.uncaughtException(<span class="code-object">ThreadGroup</span>.java)         at java.lang.<span class="code-object">Thread</span>.dispatchUncaughtException(<span class="code-object">Thread</span>.java) Caused by: java.lang.NullPointerException         at org.apache.hadoop.security.UserGroupInformation$1.run(UserGroupInformation.java:1031) ~[stormjar.jar: ?]         at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java) 2020-04-01 14:36:53.018 o.a.s.u.Utils <span class="code-object">Thread</span>-23 [INFO] Halting after 3 seconds 2020-04-01 14:36:53.019 o.a.s.d.w.Worker <span class="code-object">Thread</span>-24 [INFO] Shutting down worker XXX
</pre>
</div></div>
<p>Sequence:</p>

<p>1) Hadoop thread grabs the initial TGT:</p>

<p><a href="https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L978" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L978</a></p>

<p>2) Hadoop then sleeps:</p>

<p><a href="https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L992" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L992</a></p>

<p>3) kinit -R runs:</p>

<p><a href="https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L994" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L994</a></p>

<p> </p>

<p>The kinit will fail and generate an IOException. Then we get to this line that accesses the original TGT:</p>

<p><a href="https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L1014" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L1014</a></p>

<p> </p>

<p>But since we cleared credentials on an upload credentials this will cause the NPE, which then restarts the worker.</p>

<p> </p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">agresch</a> Merged to master and 2.1.x-branch</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-3656">STORM-3656</a>]</i>
