### ISSUE TITLE
[STORM-3609] ClassCastException when credentials are updated for ICredentialsListener spout/bolt instances

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7391]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2020-03-26 21:04:38.526 o.a.s.u.Utils <span class="code-object">Thread</span>-14-spout-executor[2, 2] [ERROR] Async loop died!
java.lang.RuntimeException: java.lang.ClassCastException: org.apache.storm.generated.Credentials cannot be <span class="code-keyword">cast</span> to java.util.Map
	at org.apache.storm.executor.Executor.accept(Executor.java:291) ~[storm-client-2.2.0.y.jar:2.2.0.y]
	at org.apache.storm.utils.JCQueue.consumeImpl(JCQueue.java:131) ~[storm-client-2.2.0.y.jar:2.2.0.y]
	at org.apache.storm.utils.JCQueue.consume(JCQueue.java:111) ~[storm-client-2.2.0.y.jar:2.2.0.y]
	at org.apache.storm.utils.JCQueue.consume(JCQueue.java:102) ~[storm-client-2.2.0.y.jar:2.2.0.y]
	at org.apache.storm.executor.spout.SpoutExecutor$2.call(SpoutExecutor.java:170) ~[storm-client-2.2.0.y.jar:2.2.0.y]
	at org.apache.storm.executor.spout.SpoutExecutor$2.call(SpoutExecutor.java:159) ~[storm-client-2.2.0.y.jar:2.2.0.y]
	at org.apache.storm.utils.Utils$1.run(Utils.java:433) [storm-client-2.2.0.y.jar:2.2.0.y]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassCastException: org.apache.storm.generated.Credentials cannot be <span class="code-keyword">cast</span> to java.util.Map
	at org.apache.storm.executor.spout.SpoutExecutor.tupleActionFn(SpoutExecutor.java:303) ~[storm-client-2.2.0.y.jar:2.2.0.y]
	at org.apache.storm.executor.Executor.accept(Executor.java:287) ~[storm-client-2.2.0.y.jar:2.2.0.y]
	... 7 more
</pre>
</div></div>

<p>note: "2.2.0.y" is our internal version, which is master branch.</p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3609" target="_blank">ClassCastException when credentials are updated for ICredentialsListener spout/bolt instances</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-03-30T15:05:42+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Merged to master and cherry-picked to 2.1.x-branch</p>

<p>commit: 04b753ef512f1d5915926a09ed12d8ed006fbd1f</p>
