### ISSUE TITLE
[STORM-3611] IllegalArgumentException thrown on windowed bolt

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7393]
<p>The following topology with a single `BasicWindowedBolt`. The following topology:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> <span class="code-keyword">class </span>GroupMean <span class="code-keyword">extends</span> ConfigurableTopology {
  
  <span class="code-keyword">public</span> <span class="code-keyword">static</span> void main(<span class="code-object">String</span>[] args) <span class="code-keyword">throws</span> Exception {
    ConfigurableTopology.start(<span class="code-keyword">new</span> GroupMean(), args);
  }
  
  @Override
  <span class="code-keyword">protected</span> <span class="code-object">int</span> run(<span class="code-object">String</span>[] args) <span class="code-keyword">throws</span> Exception {
    BaseWindowedBolt bolt = <span class="code-keyword">new</span> GroupMeanBolt()
.withTimestampExtractor(x -> x.getLong(0))
.withTumblingWindow(BaseWindowedBolt.Duration.of(100));
    
    TopologyBuilder builder = <span class="code-keyword">new</span> TopologyBuilder();
    builder.setSpout(<span class="code-quote">"groups"</span>, <span class="code-keyword">new</span> RandomGroupNumberSpout(), 1);
    builder.setBolt(<span class="code-quote">"mean"</span>, bolt, 1).shuffleGrouping(<span class="code-quote">"groups"</span>);
   
    Config config = <span class="code-keyword">new</span> Config();
    config.put(<span class="code-quote">"topology.name"</span>, <span class="code-quote">"group-mean-topo"</span>);
    <span class="code-keyword">return</span> submit(<span class="code-quote">"group-mean-topo"</span>, config, builder);
  }
}
</pre>
</div></div>
<p> with the GroupMeanBolt being like:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> <span class="code-keyword">class </span>GroupMeanBolt <span class="code-keyword">extends</span> BaseWindowedBolt {
  <span class="code-keyword">private</span> OutputCollector collector;
  
  @Override
  <span class="code-keyword">public</span> void prepare(Map<<span class="code-object">String</span>, <span class="code-object">Object</span>> conf, TopologyContext context,
      OutputCollector collector) {
    <span class="code-keyword">this</span>.collector = collector;
  }
  @Override
  <span class="code-keyword">public</span> void execute(TupleWindow inputWindow) {
    <span class="code-keyword">if</span> (inputWindow.get().size() > 0) {
      Map<<span class="code-object">Integer</span>, <span class="code-object">Double</span>> sum = <span class="code-keyword">new</span> HashMap<>();
      Map<<span class="code-object">Integer</span>, <span class="code-object">Integer</span>> histogram = <span class="code-keyword">new</span> HashMap<>();
      <span class="code-keyword">for</span> (Tuple t : inputWindow.get()) {
<span class="code-object">Integer</span> key = t.getIntegerByField(<span class="code-quote">"key"</span>);
<span class="code-object">Double</span> value = t.getDoubleByField(<span class="code-quote">"value"</span>);
sum.compute(key, (k, v) -> v == <span class="code-keyword">null</span> ? value : v + value);
histogram.compute(key, (k, v) -> v == <span class="code-keyword">null</span> ? 1 : v + 1);
      }
      Map<<span class="code-object">Integer</span>, <span class="code-object">Number</span>> result = <span class="code-keyword">new</span> HashMap<>(sum.size());
      <span class="code-keyword">for</span> (Map.Entry<<span class="code-object">Integer</span>, <span class="code-object">Double</span>> e : sum.entrySet()) {
result.put(e.getKey(), e.getValue() / histogram.get(e.getKey()));
      }
      ArrayList<<span class="code-object">Object</span>> out = <span class="code-keyword">new</span> ArrayList<>(3);
      out.add(inputWindow.getStartTimestamp());
      out.add(inputWindow.getEndTimestamp());
      ArrayList<<span class="code-object">String</span>> tokens = <span class="code-keyword">new</span> ArrayList<>(result.size());
      <span class="code-keyword">for</span> (Map.Entry<<span class="code-object">Integer</span>, <span class="code-object">Number</span>> e : result.entrySet()) {
<span class="code-object">String</span> token = <span class="code-object">String</span>.join(<span class="code-quote">":"</span>, e.getKey().toString(), e.getValue().toString());
tokens.add(token);
      }
      out.add(<span class="code-object">String</span>.join(<span class="code-quote">","</span>, tokens));
      collector.emit(out);
    }
  }
}
</pre>
</div></div>
<p>At runtime, an IllegalArgumentException is thrown because the "default" stream is not recognized. Stack trace:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2020-03-27 15:42:42.705 o.a.s.w.WaterMarkEventGenerator watermark-event-generator-0 [ERROR] Failed <span class="code-keyword">while</span> processing watermark event
java.lang.IllegalArgumentException: Unknown stream ID: <span class="code-keyword">default</span>
at org.apache.storm.daemon.Task.getOutgoingTasks(Task.java:164) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.executor.bolt.BoltOutputCollectorImpl.boltEmit(BoltOutputCollectorImpl.java:88) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.executor.bolt.BoltOutputCollectorImpl.emit(BoltOutputCollectorImpl.java:65) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:93) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:93) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.topology.WindowedBoltExecutor$WindowedOutputCollector.emit(WindowedBoltExecutor.java:403) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:88) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at gr.katsip.spear.GroupMeanBolt.execute(GroupMeanBolt.java:51) ~[stormjar.jar:2.1.1-SNAPSHOT]
at org.apache.storm.topology.WindowedBoltExecutor.boltExecute(WindowedBoltExecutor.java:370) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.topology.WindowedBoltExecutor$1.onActivation(WindowedBoltExecutor.java:363) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WindowManager.onTrigger(WindowManager.java:156) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WatermarkTimeTriggerPolicy.handleWaterMarkEvent(WatermarkTimeTriggerPolicy.java:73) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WatermarkTimeTriggerPolicy.track(WatermarkTimeTriggerPolicy.java:43) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WindowManager.track(WindowManager.java:185) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WindowManager.add(WindowManager.java:121) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WaterMarkEventGenerator.run(WaterMarkEventGenerator.java:88) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_242]
2020-03-27 15:42:42.715 o.a.s.w.WaterMarkEventGenerator <span class="code-object">Thread</span>-14-mean-executor[3, 3] [ERROR] Got exception
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unknown stream ID: <span class="code-keyword">default</span>
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_242]
at org.apache.storm.windowing.WaterMarkEventGenerator.checkFailures(WaterMarkEventGenerator.java:115) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WaterMarkEventGenerator.track(WaterMarkEventGenerator.java:79) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.topology.WindowedBoltExecutor.execute(WindowedBoltExecutor.java:308) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.executor.bolt.BoltExecutor.tupleActionFn(BoltExecutor.java:234) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.executor.Executor.accept(Executor.java:275) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.utils.JCQueue.consumeImpl(JCQueue.java:131) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.utils.JCQueue.consume(JCQueue.java:111) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:171) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:158) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.utils.Utils$1.run(Utils.java:392) [storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: Unknown stream ID: <span class="code-keyword">default</span>
at org.apache.storm.daemon.Task.getOutgoingTasks(Task.java:164) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.executor.bolt.BoltOutputCollectorImpl.boltEmit(BoltOutputCollectorImpl.java:88) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.executor.bolt.BoltOutputCollectorImpl.emit(BoltOutputCollectorImpl.java:65) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:93) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:93) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.topology.WindowedBoltExecutor$WindowedOutputCollector.emit(WindowedBoltExecutor.java:403) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:88) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at gr.katsip.spear.GroupMeanBolt.execute(GroupMeanBolt.java:51) ~[stormjar.jar:2.1.1-SNAPSHOT]
at org.apache.storm.topology.WindowedBoltExecutor.boltExecute(WindowedBoltExecutor.java:370) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.topology.WindowedBoltExecutor$1.onActivation(WindowedBoltExecutor.java:363) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WindowManager.onTrigger(WindowManager.java:156) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WatermarkTimeTriggerPolicy.handleWaterMarkEvent(WatermarkTimeTriggerPolicy.java:73) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WatermarkTimeTriggerPolicy.track(WatermarkTimeTriggerPolicy.java:43) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WindowManager.track(WindowManager.java:185) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WindowManager.add(WindowManager.java:121) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at org.apache.storm.windowing.WaterMarkEventGenerator.run(WaterMarkEventGenerator.java:88) ~[storm-client-2.1.1-SNAPSHOT.jar:2.1.1-SNAPSHOT]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
... 1 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Nikos Katsipoulakis" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nikos.katsip">nikos.katsip</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3611" target="_blank">IllegalArgumentException thrown on windowed bolt</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2020-03-30T10:59:32+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nikos.katsip">nikos.katsip</a>:</i>
<p>The exception was caused because the output fields of GroupMeanBolt were not declared. The problem disappeared when the following method was added for GroupMeanBolt:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
@Override
<span class="code-keyword">public</span> void declareOutputFields(OutputFieldsDeclarer declarer) {
  declarer.declare(<span class="code-keyword">new</span> Fields(<span class="code-quote">"start"</span>, <span class="code-quote">"end"</span>, <span class="code-quote">"result"</span>));
}
</pre>
</div></div>
