### ISSUE TITLE
[STORM-3619] Add null check for the topology name

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7401]
<p>Currently with </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
StormSubmitter.submitTopology(<span class="code-keyword">null</span>, ...)
</pre>
</div></div>
<p> <br/>
submission will fail:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Exception in thread <span class="code-quote">"main"</span> java.lang.RuntimeException: org.apache.storm.thrift.TApplicationException: Internal error processing isTopologyNameAllowed
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:438)
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:247)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:206)
	at org.apache.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:411)
	at org.apache.storm.StormSubmitter.submitTopologyWithProgressBar(StormSubmitter.java:392)
	at com.example.SimplifiedTwoCompTopology.main(SimplifiedTwoCompTopology.java:49)
Caused by: org.apache.storm.thrift.TApplicationException: Internal error processing isTopologyNameAllowed
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at org.apache.storm.generated.Nimbus$Client.recv_isTopologyNameAllowed(Nimbus.java:1209)
	at org.apache.storm.generated.Nimbus$Client.isTopologyNameAllowed(Nimbus.java:1196)
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:436)
	... 5 more
</pre>
</div></div>

<p>And on nimbus:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2020-04-08 18:38:46.356 o.a.s.t.ProcessFunction pool-34-thread-475 [ERROR] Internal error processing isTopologyNameAllowed
java.lang.NullPointerException: <span class="code-keyword">null</span>
at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_242]
at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_242]
at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_242]
at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_242]
at org.apache.storm.daemon.nimbus.Nimbus.validateTopologyName(Nimbus.java:1189) ~[storm-server-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.daemon.nimbus.Nimbus.isTopologyNameAllowed(Nimbus.java:4667) ~[storm-server-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.generated.Nimbus$Processor$isTopologyNameAllowed.getResult(Nimbus.java:4423) ~[storm-client-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.generated.Nimbus$Processor$isTopologyNameAllowed.getResult(Nimbus.java:4402) ~[storm-client-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:38) [storm-shaded-deps-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [storm-shaded-deps-2.2.0.y.jar:2.2.0.y]
at org.apache.storm.security.auth.sasl.SaslTransportPlugin$TUGIWrapProcessor.process(SaslTransportPlugin.java:152) [storm-client-2.2.0.y
.jar:2.2.0.y]
at org.apache.storm.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:291) [storm-shaded-deps-2.2.0.y.jar:2.2.0.y
]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_242]
</pre>
</div></div>

<p>This is because <a href="https://github.com/apache/storm/blob/v2.1.0/storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java#L1175-L1180" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v2.1.0/storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java#L1175-L1180</a></p>

<p>the topology name is null so NullPointerException </p>

<p>But the error message is not obvious. We should add null check when validating topology name and report the error indicating the topology name being null.</p>

<p> </p>

<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3619" target="_blank">Add null check for the topology name</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-04-09T20:32:55+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Merged to master</p>
