### ISSUE TITLE
[STORM-3622] Race Condition in CachedThreadStatesGaugeSet registered at SystemBolt

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7404]
<p>We noticed that with the change in <a href="https://github.com/apache/storm/pull/3242" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/3242</a>, there is a race condition causing NPE.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2020-04-14 18:22:12.997 o.a.s.u.Utils <span class="code-object">Thread</span>-17-__acker-executor[16, 16] [ERROR] Async loop died!
java.lang.RuntimeException: java.lang.NullPointerException
 at org.apache.storm.executor.Executor.accept(Executor.java:291) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 at org.apache.storm.utils.JCQueue.consumeImpl(JCQueue.java:131) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 at org.apache.storm.utils.JCQueue.consume(JCQueue.java:111) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:172) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:159) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 at org.apache.storm.utils.Utils$1.run(Utils.java:434) [storm-client-2.2.0.y.jar:2.2.0.y]
 at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
 at com.codahale.metrics.jvm.ThreadStatesGaugeSet.getThreadCount(ThreadStatesGaugeSet.java:95) ~[metrics-jvm-3.2.6.jar:3.2.6]
 at com.codahale.metrics.jvm.ThreadStatesGaugeSet.access$000(ThreadStatesGaugeSet.java:20) ~[metrics-jvm-3.2.6.jar:3.2.6]
 at com.codahale.metrics.jvm.ThreadStatesGaugeSet$1.getValue(ThreadStatesGaugeSet.java:56) ~[metrics-jvm-3.2.6.jar:3.2.6]
 at org.apache.storm.executor.Executor.addV2Metrics(Executor.java:344) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 at org.apache.storm.executor.Executor.metricsTick(Executor.java:320) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 at org.apache.storm.executor.bolt.BoltExecutor.tupleActionFn(BoltExecutor.java:218) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 at org.apache.storm.executor.Executor.accept(Executor.java:287) ~[storm-client-2.2.0.y.jar:2.2.0.y]
 ... 6 more
</pre>
</div></div>

<p>This is due to a race condition in CachedGauge <a href="https://github.com/dropwizard/metrics/blob/v3.2.6/metrics-core/src/main/java/com/codahale/metrics/CachedGauge.java#L49-L53" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/dropwizard/metrics/blob/v3.2.6/metrics-core/src/main/java/com/codahale/metrics/CachedGauge.java#L49-L53</a></p>

<p>There are two issues here.<br/>
The first one is <a href="https://issues.apache.org/jira/browse/STORM-3623" title="v2 metrics tick reports all worker metrics within each executor" class="issue-link" data-issue-key="STORM-3623"><del>STORM-3623</del></a>. <br/>
This makes all the executors to get values for all the metrics. So multiple threads will access the same metric.</p>

<p>So the threads gauges are now accessed by multiple threads. But in CachedGauge,</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
 @Override
    <span class="code-keyword">public</span> T getValue() {
<span class="code-keyword">if</span> (shouldLoad()) {
    <span class="code-keyword">this</span>.value = loadValue();
}
<span class="code-keyword">return</span> value;
    }
</pre>
</div></div>

<p>this method is not thread-safe. Two threads can reach to getValue at the same time.<br/>
The first thread reaching shouldLoad knows it needs to reload, so it calls the next line this.value=loadValue()<br/>
The second thread is a little bit late so shouldLoad returns false. Then it returns the value directly.</p>

<p>There is a race condition between first thread calling loadValue() and the second thread returning value.</p>

<p>If the first thread finishes loadValue() first, both values returned to the threads are the same value (and current value). But if the second thread returns earlier, the second thread gets the original value (which is null ), hence NPE.</p>

<p>To summarize, the second issue is CachedThreadStatesGaugeSet is not thread-safe</p>

<p>To fix this NPE, we should avoid using CachedThreadStatesGaugeSet. </p>

<p>But we still need to fix <a href="https://issues.apache.org/jira/browse/STORM-3623" title="v2 metrics tick reports all worker metrics within each executor" class="issue-link" data-issue-key="STORM-3623"><del>STORM-3623</del></a>  to avoid unnecessary computations and redundant metrics.</p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3622" target="_blank">Race Condition in CachedThreadStatesGaugeSet registered at SystemBolt</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-04-16T13:39:50+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Merged into master</p>
