### ISSUE TITLE
[STORM-3628] Nimbus tries Worker HB on non un-deployed topologies

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7410]
<p>I am running Storm 2.1.0 version.</p>

<p>After I undeploy topologies and later deploy new topologies, Nimbus log repeats the exception:</p>

<p>Please note: <b>fetch-inbox-16-1587324922</b>  is artifact id that does not exist anymore.</p>

<p>The Nimbus log is full of this HBs Exceptions.</p>

<p>org.apache.storm.utils.WrappedNotAliveException: <b>fetch-inbox-16-1587324922</b><br/>
 at org.apache.storm.daemon.nimbus.Nimbus.tryReadTopoConf(Nimbus.java:987) ~<span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.daemon.nimbus.Nimbus.sendSupervisorWorkerHeartbeat(Nimbus.java:4727) <span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.generated.Nimbus$Processor$sendSupervisorWorkerHeartbeat.getResult(Nimbus.java:4817) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.generated.Nimbus$Processor$sendSupervisorWorkerHeartbeat.getResult(Nimbus.java:4796) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span><br/>
 at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:38) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Yoav Naaman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yoavNaaman">yoavNaaman</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3628" target="_blank">Nimbus tries Worker HB on non un-deployed topologies</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T09:53:41+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yuval.lieberman@2bprecisehealth.com">yuval.lieberman@2bprecisehealth.com</a>:</i>
<p>Also seeing exceptions:</p>

<p>2020-04-28 10:51:09.713 o.a.s.d.n.Nimbus pool-29-thread-64 <span class="error">&#91;WARN&#93;</span> get blob meta exception.</p>

<p>org.apache.storm.utils.WrappedKeyNotFoundException: record-ingestor-12-1587988324-stormcode.ser</p>

<p> at org.apache.storm.blobstore.LocalFsBlobStore.getStoredBlobMeta(LocalFsBlobStore.java:257) ~<span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.blobstore.LocalFsBlobStore.getBlobMeta(LocalFsBlobStore.java:287) ~<span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.daemon.nimbus.Nimbus.getBlobMeta(Nimbus.java:3651) <span class="error">&#91;storm-server-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.generated.Nimbus$Processor$getBlobMeta.getResult(Nimbus.java:3951) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.generated.Nimbus$Processor$getBlobMeta.getResult(Nimbus.java:3930) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:38) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:174) <span class="error">&#91;storm-client-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span></p>

<p> at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18) <span class="error">&#91;storm-shaded-deps-2.1.0.jar:2.1.0&#93;</span></p>

<p> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) <span class="error">&#91;?:1.8.0_252&#93;</span></p>

<p> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) <span class="error">&#91;?:1.8.0_252&#93;</span></p>

<p> at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_252&#93;</span></p>

<p> </p>

<p> </p>

<p>after the topology is undeployed.</p>

<p>The data remains in supervisor/stormdist, but is removed from blobs</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
