### ISSUE TITLE
[STORM-3663] Topology with Mockito 1.x fails to run unit tests 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7445]
<p>We are observing problems building topologies with latest snapshot storm version. It used to work fine. After debugging, we have identified that the problem comes from </p>

<p><a href="https://github.com/apache/storm/blob/master/storm-client/src/resources/mockito-extensions/org.mockito.plugins.MockMaker" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-client/src/resources/mockito-extensions/org.mockito.plugins.MockMaker</a></p>

<p>This break topology if Mockito was used. This file should be a test level resource.</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Configuring TestNG with: TestNG652ConfiguratorConfiguring TestNG with: TestNG652ConfiguratorSLF4J: <span class="code-object">Class</span> path contains multiple SLF4J bindings.SLF4J: Found binding in [jar:file:/Users/rli01/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.<span class="code-keyword">class]</span>SLF4J: Found binding in [jar:file:/Users/rli01/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.11.2/log4j-slf4j-impl-2.11.2.jar!/org/slf4j/impl/StaticLoggerBinder.<span class="code-keyword">class]</span>SLF4J: See http:<span class="code-comment">//www.slf4j.org/codes.html#multiple_bindings <span class="code-keyword">for</span> an explanation.SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]Tests run: 37, Failures: 12, Errors: 0, Skipped: 0, Time elapsed: 1.135 sec <<< FAILURE! - in TestSuitetestCycling(fetl.bullet.propane.PropaneSpoutTest)  Time elapsed: 0.147 sec  <<< FAILURE!java.lang.ExceptionInInitializerError: <span class="code-keyword">null</span> at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:17) at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21) at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17) at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41) at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:30) at org.mockito.exceptions.misusing.MockitoConfigurationException.<init>(MockitoConfigurationException.java:18) at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:66) at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:24) at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12) at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11) at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24) at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:44) at org.mockito.Mockito.<clinit>(Mockito.java:975) at fetl.bullet.propane.PropaneSpoutTest.createKafkaConsumer(PropaneSpoutTest.java:71) at fetl.bullet.propane.PropaneSpoutTest.createKafkaConsumer(PropaneSpoutTest.java:87) at fetl.bullet.propane.PropaneSpoutTest.testCycling(PropaneSpoutTest.java:170)
</span>
 </pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Rui Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=li530">li530</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3663" target="_blank">Topology with Mockito 1.x fails to run unit tests </a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Rui Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=li530">li530</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-07-07T21:02:58+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=li530" class="user-hover" rel="li530">li530</a>. Merged to master. Will cherry-pick it to 2.2.x-branch</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Merged to<br/>
master: dd65dd7f6b931bf5eb8338da35e234d9eabfda65<br/>
2.2.x-branch: 10578cce720d2852cf92f9ee37b61dd2726a049e</p>
