### ISSUE TITLE
[STORM-3667] Exception message on submitting topology due to incorrect worker max heap size should be more straightforward 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7449]
<p>Submitting a topology can fail when the largest component heap size is larger than </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
topology.worker.max.heap.size.mb
</pre>
</div></div>

<p>For example, when you submit a topology with the following command</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
  bin/storm jar /home/y/lib64/jars/storm-starter.jar  org.apache.storm.starter.WordCountTopology -c topology.worker.max.heap.size.mb=100  -c topology.component.resources.onheap.memory.mb=120 wc
</pre>
</div></div>

<p>While the nimbus log shows</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
 2020-07-06 21:51:12.026 o.a.s.d.n.Nimbus pool-29-thread-45 [WARN] Topology submission exception. (topology name=<span class="code-quote">'wc'</span>)
java.lang.IllegalArgumentException: Topology will not be able to be successfully scheduled: Config TOPOLOGY_WORKER_MAX_HEAP_SIZE_MB=100.0 < 120.0 (Largest memory requirement of a component in the topology). Perhaps set TOPOLOGY_WORKER_MAX_HEAP_SIZE_MB to a larger amount
at org.apache.storm.daemon.nimbus.Nimbus.validateTopologyWorkerMaxHeapSizeConfigs(Nimbus.java:1650) ~[storm-server-2.3.0-SNAPSHOT.jar:2.3.0-SNAPSHOT]
at org.apache.storm.daemon.nimbus.Nimbus.submitTopologyWithOpts(Nimbus.java:3145) [storm-server-2.3.0-SNAPSHOT.jar:2.3.0-SNAPSHOT]
at org.apache.storm.daemon.nimbus.Nimbus.submitTopology(Nimbus.java:3107) [storm-server-2.3.0-SNAPSHOT.jar:2.3.0-SNAPSHOT]
</pre>
</div></div>
<p>the exception returned to users is </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
 21:51:12.012 [main] INFO  o.a.s.StormSubmitter - Submitting topology wc in distributed mode with conf {<span class="code-quote">"storm.zookeeper.topology.auth.scheme"</span>:<span class="code-quote">"digest"</span>,<span class="code-quote">"storm.zookeeper.topology.auth.payload"</span>:<span class="code-quote">"-8967725949793348049:-5020411463316947973"</span>,<span class="code-quote">"topology.workers"</span>:3,<span class="code-quote">"topology.component.resources.onheap.memory.mb"</span>:120,<span class="code-quote">"topology.worker.max.heap.size.mb"</span>:100,<span class="code-quote">"topology.debug"</span>:<span class="code-keyword">true</span>}
java.lang.RuntimeException: org.apache.storm.thrift.TApplicationException: Internal error processing submitTopology
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:291)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:210)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:173)
	at org.apache.storm.topology.ConfigurableTopology.submit(ConfigurableTopology.java:119)
	at org.apache.storm.starter.WordCountTopology.run(WordCountTopology.java:58)
	at org.apache.storm.topology.ConfigurableTopology.start(ConfigurableTopology.java:68)
	at org.apache.storm.starter.WordCountTopology.main(WordCountTopology.java:36)
Caused by: org.apache.storm.thrift.TApplicationException: Internal error processing submitTopology
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at org.apache.storm.generated.Nimbus$Client.recv_submitTopology(Nimbus.java:319)
	at org.apache.storm.generated.Nimbus$Client.submitTopology(Nimbus.java:303)
	at org.apache.storm.StormSubmitter.submitTopologyInDistributeMode(StormSubmitter.java:344)
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:279)
	... 6 more
</pre>
</div></div>

<p>which is not very helpful.</p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3667" target="_blank">Exception message on submitting topology due to incorrect worker max heap size should be more straightforward </a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-07-15T14:17:54+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Merged to master (9076d32ac1b0a6f95f25a4f4c7266e83c4cea80d)</p>
