### ISSUE TITLE
[STORM-3687] Add a warning about possible issues on a mixed cluster if the StormCommon.systemTopology implementation is changed

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7469]
<p>During rolling upgrade, some supervisors are still at 2.2, and others are running on 2.3. So some workers are running with storm-client-2.2.jar and others are on 2.3.</p>

<p>Because of <a href="https://github.com/apache/storm/commit/93a7f770d508668bc7af183e08535813fff6f805" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/commit/93a7f770d508668bc7af183e08535813fff6f805</a> (<a href="https://issues.apache.org/jira/browse/STORM-3660" title="Remove messaging queue for updating Executor credentials" class="issue-link" data-issue-key="STORM-3660"><del>STORM-3660</del></a>)</p>

<p>the "_credentials" stream is removed.<br/>
So the map of streamId to streamName for system component is changed <br/>
refer to the code at:<br/>
<a href="https://github.com/apache/storm/blob/v2.2.0/storm-client/src/jvm/org/apache/storm/serialization/SerializationFactory.java#L218-L222" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/v2.2.0/storm-client/src/jvm/org/apache/storm/serialization/SerializationFactory.java#L218-L222</a></p>

<p>So a worker running on storm-client-2.2 might send out _<em>metrics from its systembolt, while the MetricsConsumer running with storm-client-2.3 interprets it as "</em>_metrics_tick" because the mapping is different:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
o.a.s.s.SerializationFactory <span class="code-object">Thread</span>-15-__system-executor[-1, -1] [INFO] idmap <span class="code-keyword">for</span> system comp {__tick=6, __system=5, __metrics_tick=4, __credentials=1, __flush=2, __metrics=3}
</pre>
</div></div>
<p>vs</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
o.a.s.s.SerializationFactory Netty-server-localhost-6703-worker-1 [INFO] idmap <span class="code-keyword">for</span> system comp {__tick=5, __system=4, __metrics_tick=3, __flush=1, __metrics=2}
</pre>
</div></div>

<p>Hence we see</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.storm.metric.api.IMetricsConsumer$TaskInfo cannot be <span class="code-keyword">cast</span> to java.lang.<span class="code-object">Integer</span>
at org.apache.storm.executor.Executor.accept(Executor.java:293) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.JCQueue.consumeImpl(JCQueue.java:113) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.JCQueue.consume(JCQueue.java:89) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:167) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:153) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.Utils$1.run(Utils.java:398) ~[storm-client-2.3.0.y.jar:2.3.0.y]
... 1 more
Caused by: java.lang.ClassCastException: org.apache.storm.metric.api.IMetricsConsumer$TaskInfo cannot be <span class="code-keyword">cast</span> to java.lang.<span class="code-object">Integer</span>
at org.apache.storm.tuple.TupleImpl.getInteger(TupleImpl.java:121) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.Executor.metricsTick(Executor.java:320) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.bolt.BoltExecutor.tupleActionFn(BoltExecutor.java:213) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.Executor.accept(Executor.java:286) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.JCQueue.consumeImpl(JCQueue.java:113) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.JCQueue.consume(JCQueue.java:89) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:167) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.bolt.BoltExecutor$1.call(BoltExecutor.java:153) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.Utils$1.run(Utils.java:398) ~[storm-client-2.3.0.y.jar:2.3.0.y]
... 1 more
2020-08-04 18:26:08.017 o.a.s.m.c

2020-08-04 18:26:08.027 o.a.s.u.Utils <span class="code-object">Thread</span>-19-__metrics_org.apache.storm.metric.LoggingMetricsConsumer-executor[1555, 1555] [ERROR] Halting process: Worker died
java.lang.RuntimeException: Halting process: Worker died
at org.apache.storm.utils.Utils.exitProcess(Utils.java:518) [storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.Utils$3.run(Utils.java:870) [storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.error.ReportErrorAndDie.uncaughtException(ReportErrorAndDie.java:41) [storm-client-2.3.0.y.jar:2.3.0.y]
at java.lang.<span class="code-object">Thread</span>.dispatchUncaughtException(<span class="code-object">Thread</span>.java:1959) [?:1.8.0_242]
2020-08-04 18:26:08.027 o.a.s.u.Utils <span class="code-object">Thread</span>-18-__metrics_org.apache.storm.metric.LoggingMetricsConsumer-executor[1553, 1553] [ERROR] Halting process: Worker died
java.lang.RuntimeException: Halting process: Worker died
at org.apache.storm.utils.Utils.exitProcess(Utils.java:518) [storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.Utils$3.run(Utils.java:870) [storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.executor.error.ReportErrorAndDie.uncaughtException(ReportErrorAndDie.java:41) [storm-client-2.3.0.y.jar:2.3.0.y]
at java.lang.<span class="code-object">Thread</span>.dispatchUncaughtException(<span class="code-object">Thread</span>.java:1959) [?:1.8.0_242]
2020-08-04 18:26:08.028 o.a.s.u.Utils ShutdownHook-sleepKill-3s [INFO] Halting after 3 seconds
</pre>
</div></div>

<p>Since mixed cluster is not guaranteed to work, I am not going to fix this for now. But will add some warnings in the code so people can be aware of it.</p>

---
<details><summary><i>Originally reported by <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3687" target="_blank">Add a warning about possible issues on a mixed cluster if the StormCommon.systemTopology implementation is changed</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ethan Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-08-06T04:36:17+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Merged to master (c9276d228426ba076e9a4690998ab9c4570e16f2)</p>
