### ISSUE TITLE
[STORM-3690] UI has NullPointerException when the scheduler is not ResourceAwareScheduler

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7472]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.NullPointerException at org.apache.storm.scheduler.resource.normalization.NormalizedResourceRequest.addResourceMap(NormalizedResourceRequest.java:195) at org.apache.storm.daemon.ui.UIHelpers.getClusterSummary(UIHelpers.java:644) at org.apache.storm.daemon.ui.resources.StormApiResource.getClusterSummary(StormApiResource.java:136) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$<span class="code-keyword">static</span>$0(ResourceMethodInvocationHandlerFactory.java:52) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)

</pre>
</div></div>
<p><a href="https://github.com/apache/storm/blob/master/storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java#L644" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java#L644</a><br/>
 because only </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">if</span> (resources != <span class="code-keyword">null</span> && underlyingScheduler <span class="code-keyword">instanceof</span> ResourceAwareScheduler)
</pre>
</div></div>
<p><a href="https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java#L2941" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java#L2941</a><br/>
 supervisor used_generic_resources will not be null.</p>

<p>    </p>

---
<details><summary><i>Originally reported by <a title="Rui Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=li530">li530</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3690" target="_blank">UI has NullPointerException when the scheduler is not ResourceAwareScheduler</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Rui Li" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=li530">li530</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-08-26T14:55:27+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=li530" class="user-hover" rel="li530">li530</a></p>

<p>Merged to master (1ab888a2aed84537f6300c20a43387a56fa92f4a)</p>
