### ISSUE TITLE
[STORM-3727] SUPERVISOR_SLOTS_PORTS could be list of Longs

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7509]
<p> </p>

<p>A user reported:</p>

<p>There's no guarantee that the <tt>supervisorConf.getOrDefault</tt> will be a List of Integers.<br/>
Additionally, in ReadClusterState.java, <tt>.intValue()</tt> conversion is removed. Overall result</p>

<p> </p>

<p>{{java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer<br/>
	at org.apache.storm.daemon.supervisor.ReadClusterState.<init>(ReadClusterState.java:101) ~<span class="error">&#91;storm-server-2.2.0.jar:2.2.0&#93;</span><br/>
	at org.apache.storm.daemon.supervisor.Supervisor.launch(Supervisor.java:310) ~<span class="error">&#91;storm-server-2.2.0.jar:2.2.0&#93;</span>}}</p>

---
<details><summary><i>Originally reported by <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3727" target="_blank">SUPERVISOR_SLOTS_PORTS could be list of Longs</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Aaron Gresch" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2021-01-05T17:34:53+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli">ethanli</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">agresch</a>. I merged this to master (ba7f969a3a046c5a312a394026d5d9dd755e04a0)</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/storm/issues?q=in%3Atitle%20STORM-3734">STORM-3734</a>]</i>
