### ISSUE TITLE
[STORM-3770] Workaround for Issue STORM-3677 (assignment was null) in version 2.2.0

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7552]
<p>Please suggest workaround for the issue <a href="https://issues.apache.org/jira/browse/STORM-3677" title="Fix Worker Suicide Function if assignment is null" class="issue-link" data-issue-key="STORM-3677"><del>STORM-3677</del></a> in version 2.2.0.</p>

<p><a href="https://issues.apache.org/jira/browse/STORM-3677" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-3677</a></p>

<p> </p>

<p>Is there any other way to kill stale/orphan worker?</p>

<p>We are getting below exception-<br/>
2021-05-10 10:42:36.369 o.a.s.d.w.WorkerState refresh-connections-timer <span class="error">&#91;WARN&#93;</span> Failed to read assignment. This should only happen when topology is shutting down.<br/>
 java.lang.RuntimeException: Failed to read worker assignment. Supervisor client threw exception, and <b>assignment in Zookeeper was null</b><br/>
 at org.apache.storm.daemon.worker.WorkerState.getLocalAssignment(WorkerState.java:665) ~<span class="error">&#91;storm-client-2.2.0.jar:2.2.0&#93;</span><br/>
 at org.apache.storm.daemon.worker.WorkerState.refreshConnections(WorkerState.java:389) ~<span class="error">&#91;storm-client-2.2.0.jar:2.2.0&#93;</span><br/>
 <br/>
Worker is not listed in Storm UI, hence we are doing manual intervention every time to kill the process. <br/>
As process is not releasing port, there is topology imbalance happening and load is going to only few supervisors. Attached screenshot.</p>

---
<details><summary><i>Originally reported by <a title="Nikhil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nikhilonly13@gmail.com">nikhilonly13@gmail.com</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3770" target="_blank">Workaround for Issue STORM-3677 (assignment was null) in version 2.2.0</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T09:53:40+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>
