### ISSUE TITLE
[STORM-3773] Worker Reassignment - Difference between Storm 2.x  and Storm 1.x

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7555]
<p>We are currently on Storm 1.2.1 and was in the process of upgrading it to Storm 2.2.0<br/>
 Observed the below while upgrading it to 2.2.0:</p>

<p>1) In a storm cluster (4 nodes) with 8 topologies running  ( with a mapping of 1-1 between worker and topologies), when i bring down nimbus,supervisor in one of the node (let's say Node 1, which is not nimbus leader) the workers running on that node gets reassigned to other 3, even though it is running on that node (Node 1). So i have 2 worker process for the same topology running at the same time ( saw the behaviour with or without using pacemaker). The worker process does get killed when nimbus and supervisor is brought up in Node 1</p>

<p>2) Observed from worker logs that it sends heartbeat to local supervisor and nimbus leader , which with 1.2.1 used to happen using Zookeeper ( i saw this behaviour in 2.2.0 with or without using Pacemaker). <br/>
 If i bring down nimbus and supervisor on node where nimbus is a leader, it reassigns worker processes and in some cases leads to zombie worker processess ( is not killed when storm kill is executed)</p>

<p>These above behaviour (reassignment of worker) doesn't happen with Storm 1.2.1</p>

<p>Since this is a fundamental design change between 1.x and 2.x , are there any documentation which describes it in detail? ( couldn't find from Release Notes)</p>

<p>(I am raising this as a bug because its preventing us from moving to 2.2.0 due to the issue mentioned in 2) )</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Surajeet" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=surajeet">surajeet</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3773" target="_blank">Worker Reassignment - Difference between Storm 2.x  and Storm 1.x</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T09:53:57+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>:</i>
<p>This sounds like it could be a dupe of <a href="https://issues.apache.org/jira/browse/STORM-3677" title="Fix Worker Suicide Function if assignment is null" class="issue-link" data-issue-key="STORM-3677"><del>STORM-3677</del></a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=surajeet">surajeet</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch" class="user-hover" rel="agresch">agresch</a> The reassignment leading to zombie process looks to be a dupe of <a href="https://issues.apache.org/jira/browse/STORM-3677" title="Fix Worker Suicide Function if assignment is null" class="issue-link" data-issue-key="STORM-3677"><del>STORM-3677</del></a>.<br/>
However, the point is, there is no need of reassignment as the workers didn't die ( as was the behaviour in 1.2.1). Our system is  based on the behaviour of 1.2.1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER306724">JIRAUSER306724</a>:</i>
<p>Hey guys, I'm using Storm v2.6.1 and every time I restart the nimbus leader (currently I have 3 for high availability) the workers get reassigned. I'm using Zookeeper instead of Pacemaker.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER306724">JIRAUSER306724</a>:</i>
<p>On another note, I've seen this error when shutting down my nimbus.</p>


<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2024-08-21T15:09:46.647Z Nimbus [INFO] Shutting down master 2024-08-21T15:09:46.648Z CuratorFrameworkImpl [INFO] backgroundOperationsLoop exiting 2024-08-21T15:09:46.752Z ClientCnxn [INFO] EventThread shut down <span class="code-keyword">for</span> session: 0x4000010be7caa5d 2024-08-21T15:09:46.752Z ZooKeeper [INFO] Session: 0x4000010be7caa5d closed 2024-08-21T15:09:46.752Z CuratorFrameworkImpl [INFO] backgroundOperationsLoop exiting 2024-08-21T15:09:46.812Z ProcessFunction [ERROR] Internal error processing getLeader java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED] at org.apache.storm.shade.org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:835) ~[storm-shaded-deps-2.6.1.jar:2.6.1] at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:462) ~[storm-shaded-deps-2.6.1.jar:2.6.1] at org.apache.storm.shade.org.apache.curator.framework.imps.CuratorFrameworkImpl.getChildren(CuratorFrameworkImpl.java:507) ~[storm-shaded-deps-2.6.1.jar:2.6.1] at org.apache.storm.zookeeper.ClientZookeeper.getChildren(ClientZookeeper.java:209) ~[storm-client-2.6.1.jar:2.6.1] at org.apache.storm.cluster.ZKStateStorage.get_children(ZKStateStorage.java:155) ~[storm-client-2.6.1.jar:2.6.1] at org.apache.storm.cluster.StormClusterStateImpl.nimbuses(StormClusterStateImpl.java:279) ~[storm-client-2.6.1.jar:2.6.1] at org.apache.storm.daemon.nimbus.Nimbus.getLeader(Nimbus.java:4907) ~[storm-server-2.6.1.jar:2.6.1] at org.apache.storm.generated.Nimbus$Processor$getLeader.getResult(Nimbus.java:5168) ~[storm-client-2.6.1.jar:2.6.1] at org.apache.storm.generated.Nimbus$Processor$getLeader.getResult(Nimbus.java:5144) ~[storm-client-2.6.1.jar:2.6.1] at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:40) [storm-shaded-deps-2.6.1.jar:2.6.1] at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:40) [storm-shaded-deps-2.6.1.jar:2.6.1] at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:171) [storm-client-2.6.1.jar:2.6.1] at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:492) [storm-shaded-deps-2.6.1.jar:2.6.1] at org.apache.storm.thrift.server.Invocation.run(Invocation.java:19) [storm-shaded-deps-2.6.1.jar:2.6.1] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:829) [?:?]</pre>
</div></div>
