### ISSUE TITLE
[STORM-3783] 500 Server Error - Internal error processing getComponentPageInfo

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7565]
<p>I'm still facing this issue in 2.2.0 storm ui.</p>

<p>org.apache.storm.thrift.TApplicationException: Internal error processing getComponentPageInfo<br/>
 at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:79)<br/>
 at org.apache.storm.generated.Nimbus$Client.recv_getComponentPageInfo(Nimbus.java:1359)<br/>
 at org.apache.storm.generated.Nimbus$Client.getComponentPageInfo(Nimbus.java:1343)<br/>
 at org.apache.storm.daemon.ui.UIHelpers.getComponentPage(UIHelpers.java:2050)<br/>
 at org.apache.storm.daemon.ui.resources.StormApiResource.getTopologyComponent(StormApiResource.java:428)<br/>
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
 at java.lang.reflect.Method.invoke(Method.java:498)<br/>
 at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)<br/>
 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)<br/>
 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)<br/>
 at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)<br/>
 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)<br/>
 at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)<br/>
 at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)<br/>
 at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)<br/>
 at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)<br/>
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)<br/>
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)<br/>
 at org.glassfish.jersey.internal.Errors.process(Errors.java:292)<br/>
 at org.glassfish.jersey.internal.Errors.process(Errors.java:274)<br/>
 at org.glassfish.jersey.internal.Errors.process(Errors.java:244)<br/>
 at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)<br/>
 at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)<br/>
 at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)<br/>
 at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)<br/>
 at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)<br/>
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)<br/>
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)<br/>
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)<br/>
 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)<br/>
 at org.apache.storm.daemon.ui.filters.HeaderResponseServletFilter.doFilter(HeaderResponseServletFilter.java:62)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br/>
 at org.apache.storm.daemon.drpc.webapp.ReqContextFilter.handle(ReqContextFilter.java:83)<br/>
 at org.apache.storm.daemon.drpc.webapp.ReqContextFilter.doFilter(ReqContextFilter.java:70)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br/>
 at org.apache.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:46)<br/>
 at org.apache.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:38)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br/>
 at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)<br/>
 at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br/>
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)<br/>
 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)<br/>
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)<br/>
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)<br/>
 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)<br/>
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)<br/>
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)<br/>
 at org.eclipse.jetty.server.Server.handle(Server.java:502)<br/>
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)<br/>
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)<br/>
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)<br/>
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)<br/>
 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)<br/>
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)<br/>
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)<br/>
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)<br/>
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)<br/>
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)<br/>
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)<br/>
 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)<br/>
 at java.lang.Thread.run(Thread.java:748)</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Elvis Zhang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Elvis Zhang">Elvis Zhang</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3783" target="_blank">500 Server Error - Internal error processing getComponentPageInfo</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elvis zhang">elvis zhang</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ethanli" class="user-hover" rel="ethanli">ethanli</a> hi Ethan, do you know how to avoid this issue? thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER306724">JIRAUSER306724</a>:</i>
<p><a href="https://issues.apache.org/jira/browse/STORM-4148" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-4148</a> Not sure if the problem is the same, but we let a fix for the same issue </p>

**Comment by rzo1** [comment]
If this is still an issue, feel free to re-open. I think, that our latest UI fixes should have fixes it since 2.2.20
