### ISSUE TITLE
[STORM-3784] my supervisor will shut down on 2:00 am everyday

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7566]
<p>The cluster has one nimbus and two supervisors.one of the supervisors is alone with nimbus.</p>

<p>I deployed two topology that PradarLinkTopology and PradarLogTopology.</p>

<p>PradarLogTopology run with 4 workers.PradarLinkTopology run with 1 workers.</p>

<p>on 2:00 am everyday, all supervisors will shut down,i havn't find out the reason.</p>

<p>I try to clean up the status directory,but the problem still exsit.</p>

<p>this is my supervisor.log</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-comment">//代码占位符
</span>2021-07-21 02:03:42.070 o.a.s.u.Utils <span class="code-object">Thread</span>-17 [INFO] Worker <span class="code-object">Process</span> dcae9231-4be4-4842-9ed0-988e1b8a2b28:Error occurred during initialization of VM2021-07-21 02:03:42.070 o.a.s.u.Utils <span class="code-object">Thread</span>-17 [INFO] Worker <span class="code-object">Process</span> dcae9231-4be4-4842-9ed0-988e1b8a2b28:Error occurred during initialization of VM2021-07-21 02:03:42.071 o.a.s.u.Utils <span class="code-object">Thread</span>-17 [INFO] Worker <span class="code-object">Process</span> dcae9231-4be4-4842-9ed0-988e1b8a2b28:java.lang.Error: Properties init: Could not determine current working directory.2021-07-21 02:03:42.071 o.a.s.u.Utils <span class="code-object">Thread</span>-17 [INFO] Worker <span class="code-object">Process</span> dcae9231-4be4-4842-9ed0-988e1b8a2b28: at java.lang.<span class="code-object">System</span>.initProperties(Native Method)2021-07-21 02:03:42.071 o.a.s.u.Utils <span class="code-object">Thread</span>-17 [INFO] Worker <span class="code-object">Process</span> dcae9231-4be4-4842-9ed0-988e1b8a2b28: at java.lang.<span class="code-object">System</span>.initializeSystemClass(<span class="code-object">System</span>.java:1166)2021-07-21 02:03:42.071 o.a.s.u.Utils <span class="code-object">Thread</span>-17 [INFO] Worker <span class="code-object">Process</span> dcae9231-4be4-4842-9ed0-988e1b8a2b28:2021-07-21 02:03:42.323 o.a.s.d.s.BasicContainer SLOT_6702 [INFO] Removed Worker ID dcae9231-4be4-4842-9ed0-988e1b8a2b282021-07-21 02:03:42.329 o.a.s.d.s.Slot SLOT_6702 [INFO] STATE kill msInState: 68588 topo:PradarLogTopology-3-1626751922 worker:<span class="code-keyword">null</span> -> empty msInState: 32021-07-21 02:03:42.329 o.a.s.d.s.Slot SLOT_6702 [INFO] SLOT 6702: Changing current assignment from LocalAssignment(topology_id:PradarLogTopology-3-1626751922, executors:[ExecutorInfo(task_start:4, task_end:4), ExecutorInfo(task_start:1, task_end:1)], resources:WorkerResources(mem_on_heap:256.0, mem_off_heap:0.0, cpu:20.0, shared_mem_on_heap:0.0, shared_mem_off_heap:0.0, resources:{offheap.memory.mb=0.0, onheap.memory.mb=256.0, cpu.pcore.percent=20.0}, shared_resources:{}), owner:root) to null2021-07-21 02:03:42.353 o.a.s.d.s.Supervisor pool-10-thread-1 [WARN] Topology config is not localized yet...2021-07-21 02:03:42.449 o.a.s.d.s.Slot SLOT_6700 [INFO] SLOT 6700 all processes are dead...2021-07-21 02:03:42.449 o.a.s.d.s.Container SLOT_6700 [INFO] Cleaning up 8cbbfd6c-961b-482d-9175-cf9b79473808-172.26.137.86:b7963273-452a-43af-bc00-d814e0629f962021-07-21 02:03:42.450 o.a.s.d.s.Container SLOT_6700 [INFO] GET worker-user <span class="code-keyword">for</span> b7963273-452a-43af-bc00-d814e0629f962021-07-21 02:03:42.450 o.a.s.d.s.AdvancedFSOps SLOT_6700 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers/b7963273-452a-43af-bc00-d814e0629f96/pids/163262021-07-21 02:03:43.322 o.a.s.d.s.AdvancedFSOps SLOT_6701 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers/26b5ffbd-08b6-46df-aa04-6b86f78b8ad8/pids2021-07-21 02:03:43.322 o.a.s.d.s.AdvancedFSOps SLOT_6701 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers/26b5ffbd-08b6-46df-aa04-6b86f78b8ad8/tmp2021-07-21 02:03:45.209 o.a.s.d.s.BasicContainer <span class="code-object">Thread</span>-17 [INFO] Worker <span class="code-object">Process</span> dcae9231-4be4-4842-9ed0-988e1b8a2b28 exited with code: 12021-07-21 02:03:45.224 o.a.s.d.s.AdvancedFSOps SLOT_6701 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers/26b5ffbd-08b6-46df-aa04-6b86f78b8ad82021-07-21 02:03:45.224 o.a.s.d.s.Supervisor pool-10-thread-7 [WARN] Topology config is not localized yet...2021-07-21 02:03:45.224 o.a.s.d.s.Container SLOT_6701 [INFO] REMOVE worker-user 26b5ffbd-08b6-46df-aa04-6b86f78b8ad82021-07-21 02:03:45.224 o.a.s.d.s.AdvancedFSOps SLOT_6700 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers/b7963273-452a-43af-bc00-d814e0629f96/heartbeats2021-07-21 02:03:45.224 o.a.s.d.s.AdvancedFSOps SLOT_6701 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers-users/26b5ffbd-08b6-46df-aa04-6b86f78b8ad82021-07-21 02:03:45.224 o.a.s.t.ProcessFunction pool-10-thread-7 [ERROR] Internal error processing sendSupervisorWorkerHeartbeatorg.apache.storm.utils.WrappedNotAliveException: PradarLinkTopology-2-1626337413 does not appear to be alive, you should probably exit at org.apache.storm.daemon.supervisor.Supervisor$1.sendSupervisorWorkerHeartbeat(Supervisor.java:442) ~[storm-server-2.1.0.jar:2.1.0] at org.apache.storm.generated.Supervisor$Processor$sendSupervisorWorkerHeartbeat.getResult(Supervisor.java:374) ~[storm-client-2.1.0.jar:2.1.0] at org.apache.storm.generated.Supervisor$Processor$sendSupervisorWorkerHeartbeat.getResult(Supervisor.java:353) ~[storm-client-2.1.0.jar:2.1.0] at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:38) [storm-shaded-deps-2.1.0.jar:2.1.0] at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [storm-shaded-deps-2.1.0.jar:2.1.0] at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:174) [storm-client-2.1.0.jar:2.1.0] at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) [storm-shaded-deps-2.1.0.jar:2.1.0] at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18) [storm-shaded-deps-2.1.0.jar:2.1.0] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201] at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_201]2021-07-21 02:03:45.225 o.a.s.d.s.AdvancedFSOps SLOT_6700 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers/b7963273-452a-43af-bc00-d814e0629f96/pids2021-07-21 02:03:45.225 o.a.s.d.s.BasicContainer <span class="code-object">Thread</span>-16 [INFO] Worker <span class="code-object">Process</span> b7963273-452a-43af-bc00-d814e0629f96 exited with code: 2542021-07-21 02:03:45.225 o.a.s.d.s.AdvancedFSOps SLOT_6700 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers/b7963273-452a-43af-bc00-d814e0629f96/tmp2021-07-21 02:03:45.226 o.a.s.d.s.AdvancedFSOps SLOT_6700 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers/b7963273-452a-43af-bc00-d814e0629f962021-07-21 02:03:45.226 o.a.s.d.s.Container SLOT_6700 [INFO] REMOVE worker-user b7963273-452a-43af-bc00-d814e0629f962021-07-21 02:03:45.226 o.a.s.d.s.AdvancedFSOps SLOT_6700 [INFO] Deleting path /data/apache-storm-2.1.0/status/workers-users/b7963273-452a-43af-bc00-d814e0629f962021-07-21 02:03:45.227 o.a.s.d.s.BasicContainer SLOT_6701 [INFO] Removed Worker ID 26b5ffbd-08b6-46df-aa04-6b86f78b8ad82021-07-21 02:03:45.228 o.a.s.d.s.BasicContainer SLOT_6700 [INFO] Removed Worker ID b7963273-452a-43af-bc00-d814e0629f962021-07-21 02:03:45.229 o.a.s.d.s.Slot SLOT_6700 [INFO] STATE kill msInState: 81385 topo:PradarLogTopology-3-1626751922 worker:<span class="code-keyword">null</span> -> empty msInState: 02021-07-21 02:03:45.229 o.a.s.d.s.Slot SLOT_6700 [INFO] SLOT 6700: Changing current assignment from LocalAssignment(topology_id:PradarLogTopology-3-1626751922, executors:[ExecutorInfo(task_start:3, task_end:3)], resources:WorkerResources(mem_on_heap:128.0, mem_off_heap:0.0, cpu:10.0, shared_mem_on_heap:0.0, shared_mem_off_heap:0.0, resources:{offheap.memory.mb=0.0, onheap.memory.mb=128.0, cpu.pcore.percent=10.0}, shared_resources:{}), owner:root) to null2021-07-21 02:03:45.230 o.a.s.d.s.Slot SLOT_6701 [INFO] STATE kill-and-relaunch msInState: 95356 topo:PradarLogTopology-3-1626751922 worker:<span class="code-keyword">null</span> -> waiting-<span class="code-keyword">for</span>-blob-localization msInState: 12021-07-21 02:03:45.231 o.a.s.d.s.Slot SLOT_6701 [INFO] SLOT 6701: Changing current assignment from LocalAssignment(topology_id:PradarLogTopology-3-1626751922, executors:[ExecutorInfo(task_start:3, task_end:3)], resources:WorkerResources(mem_on_heap:128.0, mem_off_heap:0.0, cpu:10.0, shared_mem_on_heap:0.0, shared_mem_off_heap:0.0, resources:{offheap.memory.mb=0.0, onheap.memory.mb=128.0, cpu.pcore.percent=10.0}, shared_resources:{}), owner:root) to null2021-07-21 02:03:45.231 o.a.s.d.s.Slot SLOT_6700 [INFO] STATE empty msInState: 2 -> waiting-<span class="code-keyword">for</span>-blob-localization msInState: 02021-07-21 02:03:45.232 o.a.s.d.s.Slot SLOT_6701 [ERROR] Error when processing eventjava.io.FileNotFoundException: File <span class="code-quote">'/data/apache-storm-2.1.0/status/supervisor/stormdist/PradarLinkTopology-4-1626751925/stormconf.ser'</span> does not exist at org.apache.storm.shade.org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:297) ~[storm-shaded-deps-2.1.0.jar:2.1.0] at org.apache.storm.shade.org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1851) ~[storm-shaded-deps-2.1.0.jar:2.1.0] at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfGivenPath(ConfigUtils.java:303) ~[storm-client-2.1.0.jar:2.1.0] at org.apache.storm.utils.ConfigUtils.readSupervisorStormConfImpl(ConfigUtils.java:464) ~[storm-client-2.1.0.jar:2.1.0] at org.apache.storm.utils.ConfigUtils.readSupervisorStormConf(ConfigUtils.java:298) ~[storm-client-2.1.0.jar:2.1.0] at org.apache.storm.localizer.AsyncLocalizer.getLocalResources(AsyncLocalizer.java:351) ~[storm-server-2.1.0.jar:2.1.0] at org.apache.storm.localizer.AsyncLocalizer.releaseSlotFor(AsyncLocalizer.java:452) ~[storm-server-2.1.0.jar:2.1.0] at org.apache.storm.daemon.supervisor.Slot.handleWaitingForBlobLocalization(Slot.java:440) ~[storm-server-2.1.0.jar:2.1.0] at org.apache.storm.daemon.supervisor.Slot.stateMachineStep(Slot.java:228) ~[storm-server-2.1.0.jar:2.1.0] at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:931) [storm-server-2.1.0.jar:2.1.0]2021-07-21 02:03:45.234 o.a.s.u.Utils SLOT_6701 [ERROR] Halting process: Error when processing an eventjava.lang.RuntimeException: Halting process: Error when processing an event at org.apache.storm.utils.Utils.exitProcess(Utils.java:512) [storm-client-2.1.0.jar:2.1.0] at org.apache.storm.daemon.supervisor.Slot.run(Slot.java:978) [storm-server-2.1.0.jar:2.1.0]2021-07-21 02:03:45.235 o.a.s.d.s.BasicContainer SLOT_6700 [INFO] Created Worker ID 68102ac7-a341-4d84-b1aa-db0f72934f992021-07-21 02:03:45.236 o.a.s.d.s.Container SLOT_6700 [INFO] Setting up 8cbbfd6c-961b-482d-9175-cf9b79473808-172.26.137.86:68102ac7-a341-4d84-b1aa-db0f72934f992021-07-21 02:03:45.236 o.a.s.d.s.Container SLOT_6700 [INFO] GET worker-user <span class="code-keyword">for</span> 68102ac7-a341-4d84-b1aa-db0f72934f992021-07-21 02:03:45.240 o.a.s.d.s.Container SLOT_6700 [INFO] SET worker-user 68102ac7-a341-4d84-b1aa-db0f72934f99 root2021-07-21 02:03:45.241 o.a.s.d.s.Container SLOT_6700 [INFO] Creating symlinks <span class="code-keyword">for</span> worker-id: 68102ac7-a341-4d84-b1aa-db0f72934f99 storm-id: PradarLogTopology-3-1626751922 <span class="code-keyword">for</span> files(1): [resources]2021-07-21 02:03:45.241 o.a.s.d.s.BasicContainer SLOT_6700 [INFO] Launching worker with assignment LocalAssignment(topology_id:PradarLogTopology-3-1626751922, executors:[ExecutorInfo(task_start:4, task_end:4), ExecutorInfo(task_start:1, task_end:1)], resources:WorkerResources(mem_on_heap:256.0, mem_off_heap:0.0, cpu:20.0, shared_mem_on_heap:0.0, shared_mem_off_heap:0.0, resources:{offheap.memory.mb=0.0, onheap.memory.mb=256.0, cpu.pcore.percent=20.0}, shared_resources:{}), owner:root) <span class="code-keyword">for</span> <span class="code-keyword">this</span> supervisor 8cbbfd6c-961b-482d-9175-cf9b79473808-172.26.137.86 on port 6700 with id 68102ac7-a341-4d84-b1aa-db0f72934f992021-07-21 02:03:45.243 o.a.s.d.s.BasicContainer SLOT_6700 [INFO] Launching worker with command: <span class="code-quote">'/usr/local/java/bin/java'</span> <span class="code-quote">'-cp'</span> <span class="code-quote">'/data/apache-storm-2.1.0/lib-worker/*:/data/apache-storm-2.1.0/extlib/*:/data/apache-storm-2.1.0/conf:/data/apache-storm-2.1.0/status/supervisor/stormdist/PradarLogTopology-3-1626751922/stormjar.jar'</span> <span class="code-quote">'-Xmx64m'</span> <span class="code-quote">'-Dlogging.sensitivity=S3'</span> <span class="code-quote">'-Dlogfile.name=worker.log'</span> <span class="code-quote">'-Dstorm.home=/data/apache-storm-2.1.0'</span> <span class="code-quote">'-Dworkers.artifacts=/data/apache-storm-2.1.0/logs/workers-artifacts'</span> <span class="code-quote">'-Dstorm.id=PradarLogTopology-3-1626751922'</span> <span class="code-quote">'-Dworker.id=68102ac7-a341-4d84-b1aa-db0f72934f99'</span> <span class="code-quote">'-Dworker.port=6700'</span> <span class="code-quote">'-Dstorm.log.dir=/data/apache-storm-2.1.0/logs'</span> <span class="code-quote">'-DLog4jContextSelector=org.apache.logging.log4j.core.selector.BasicContextSelector'</span> <span class="code-quote">'-Dstorm.local.dir=/data/apache-storm-2.1.0/status'</span> <span class="code-quote">'-Dworker.memory_limit_mb=256'</span> <span class="code-quote">'-Dlog4j.configurationFile=/data/apache-storm-2.1.0/log4j2/worker.xml'</span> <span class="code-quote">'org.apache.storm.LogWriter'</span> <span class="code-quote">'/usr/local/java/bin/java'</span> <span class="code-quote">'-server'</span> <span class="code-quote">'-Dlogging.sensitivity=S3'</span> <span class="code-quote">'-Dlogfile.name=worker.log'</span> <span class="code-quote">'-Dstorm.home=/data/apache-storm-2.1.0'</span> <span class="code-quote">'-Dworkers.artifacts=/data/apache-storm-2.1.0/logs/workers-artifacts'</span> <span class="code-quote">'-Dstorm.id=PradarLogTopology-3-1626751922'</span> <span class="code-quote">'-Dworker.id=68102ac7-a341-4d84-b1aa-db0f72934f99'</span> <span class="code-quote">'-Dworker.port=6700'</span> <span class="code-quote">'-Dstorm.log.dir=/data/apache-storm-2.1.0/logs'</span> <span class="code-quote">'-DLog4jContextSelector=org.apache.logging.log4j.core.selector.BasicContextSelector'</span> <span class="code-quote">'-Dstorm.local.dir=/data/apache-storm-2.1.0/status'</span> <span class="code-quote">'-Dworker.memory_limit_mb=256'</span> <span class="code-quote">'-Dlog4j.configurationFile=/data/apache-storm-2.1.0/log4j2/worker.xml'</span> <span class="code-quote">'-Xmx256m'</span> <span class="code-quote">'-XX:+PrintGCDetails'</span> <span class="code-quote">'-Xloggc:artifacts/gc.log'</span> <span class="code-quote">'-XX:+PrintGCDateStamps'</span> <span class="code-quote">'-XX:+PrintGCTimeStamps'</span> <span class="code-quote">'-XX:+UseGCLogFileRotation'</span> <span class="code-quote">'-XX:NumberOfGCLogFiles=10'</span> <span class="code-quote">'-XX:GCLogFileSize=1M'</span> <span class="code-quote">'-XX:+HeapDumpOnOutOfMemoryError'</span> <span class="code-quote">'-XX:HeapDumpPath=artifacts/heapdump'</span> <span class="code-quote">'-Xms2g'</span> <span class="code-quote">'-Xmx2g'</span> <span class="code-quote">'-XX:MaxDirectMemorySize=512m'</span> <span class="code-quote">'-XX:+HeapDumpOnOutOfMemoryError'</span> <span class="code-quote">'-XX:HeapDumpPath=java.hprof'</span> <span class="code-quote">'-XX:MetaspaceSize=256m'</span> <span class="code-quote">'-XX:MaxMetaspaceSize=256m'</span> <span class="code-quote">'-XX:-OmitStackTraceInFastThrow'</span> <span class="code-quote">'-Djava.library.path=/data/apache-storm-2.1.0/status/supervisor/stormdist/PradarLogTopology-3-1626751922/resources/Linux-amd64:/data/apache-storm-2.1.0/status/supervisor/stormdist/PradarLogTopology-3-1626751922/resources:/usr/local/lib:/opt/local/lib:/usr/lib:/usr/lib64'</span> <span class="code-quote">'-Dstorm.conf.file='</span> <span class="code-quote">'-Dstorm.options='</span> <span class="code-quote">'-Djava.io.tmpdir=/data/apache-storm-2.1.0/status/workers/68102ac7-a341-4d84-b1aa-db0f72934f99/tmp'</span> <span class="code-quote">'-cp'</span> <span class="code-quote">'/data/apache-storm-2.1.0/lib-worker/*:/data/apache-storm-2.1.0/extlib/*:/data/apache-storm-2.1.0/conf:/data/apache-storm-2.1.0/status/supervisor/stormdist/PradarLogTopology-3-1626751922/stormjar.jar'</span> <span class="code-quote">'org.apache.storm.daemon.worker.Worker'</span> <span class="code-quote">'PradarLogTopology-3-1626751922'</span> <span class="code-quote">'8cbbfd6c-961b-482d-9175-cf9b79473808-172.26.137.86'</span> <span class="code-quote">'6628'</span> <span class="code-quote">'6700'</span> <span class="code-quote">'68102ac7-a341-4d84-b1aa-db0f72934f99'</span>. 2021-07-21 02:03:45.243 o.a.s.u.Utils <span class="code-object">Thread</span>-5 [INFO] Halting after 1 seconds2021-07-21 02:03:45.244 o.a.s.d.s.Supervisor <span class="code-object">Thread</span>-6 [INFO] Shutting down supervisor 8cbbfd6c-961b-482d-9175-cf9b79473808-172.26.137.86
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Sunsy Sun" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Sunsy">Sunsy</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3784" target="_blank">my supervisor will shut down on 2:00 am everyday</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2023-11-09T12:42:37+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=agresch">agresch</a>:</i>
<p>Something is deleting the file <br/>
/data/apache-storm-2.1.0/status/supervisor/stormdist/PradarLinkTopology-4-1626751925/stormconf.ser</p>
