### ISSUE TITLE
[STORM-3822] Colon in streamId breaks topology visualization

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7604]
<p>If a streamId contains a colon (":"), the Topology Visualization will be empty in the storm UI.</p>

<p>The cause is a JavaScript error like the following (captured from storm-2.2.0 though the issue looks like it wouldn't be resolved in 2.3.1).  The last bit after "unsupported pseudo" depends on the actual streamId.  In the case that generated this, the streamId was "my:stream".</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: stream
    at Function.fb.error (jquery-1.11.1.min.js:2:12720)
    at PSEUDO (jquery-1.11.1.min.js:2:15641)
    at wb (jquery-1.11.1.min.js:2:20274)
    at fb.compile (jquery-1.11.1.min.js:2:21173)
    at fb.select (jquery-1.11.1.min.js:2:21853)
    at Function.fb [as find] (jquery-1.11.1.min.js:2:7352)
    at m.fn.init.find (jquery-1.11.1.min.js:2:23595)
    at <span class="code-object">String</span>.<anonymous> (visualization.js:288:39)
    at Function.each (jquery-1.11.1.min.js:2:3027)
    at updateAvailableStreams (visualization.js:287:7)
</pre>
</div></div>

<p>It looks like UIHelpers.sanitizeStreamName(String streamName) is intended to replace some characters (that presumably would break the visualization) with underscore ("_").  However, it allows the colons through even though they also break the visualization.  It seems an easy fix might be to adjust that method so that it also replaces colons with underscores.</p>

---
<details><summary><i>Originally reported by <a title="Ben Roling" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ben.roling">ben.roling</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3822" target="_blank">Colon in streamId breaks topology visualization</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2022-04-08T06:00:42+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ben.roling">ben.roling</a>:</i>
<p>PR:<br/>
<a href="https://github.com/apache/storm/pull/3441" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/3441</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bipinprasad">bipinprasad</a>:</i>
<p>Merged PR <a href="https://github.com/apache/storm/pull/3441" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/3441</a></p>
