### ISSUE TITLE
[STORM-3871] Storm blobstore leak space

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7653]
<p>We observe after 5 days, with 3 nimbus deployed in HA, that the blostore keeps growing.</p>

<p> </p>

<p>Usually we submit topologies each 10min  and it ends in around 10 min. The expected result is that the blobstore cleans itself so that topologies older than days are removed. But this is not the case, as seen below (done the 2022-06-03, expected result: only blob from the current day should appear. current behavior: blobs from 2 days ago are still here)</p>

<p> </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>/space/StormApp/current/bin/storm blobstore list 2>&1 | grep o.a.s.c.Blobstore | sort -k7 | perl -anE '$date=localtime($F[6]/1000);shift @F;say join " ", $date, @F'
Wed Jun  1 14:12:43 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-8f132aef-b401-4fa6-b07e-3588073da824.jar 1654092763312 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Wed Jun  1 14:13:43 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-ae74967a-0def-44a1-8d1b-53a255900239.jar 1654092823330 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Wed Jun  1 14:33:00 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-8fa7edcb-5f8a-4a79-8f8d-8c8fd50dbc9e.jar 1654093980305 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Wed Jun  1 15:14:19 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-9168e429-2cd6-433c-90d9-6db19d564824.jar 1654096459069 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Wed Jun  1 16:13:49 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-9ed7a9fd-2819-4784-a953-c04a65981c59.jar 1654100029294 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Wed Jun  1 22:53:29 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-124b606a-0d2b-44a1-9885-4bb1152a98e7.jar 1654124009759 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Wed Jun  1 23:23:59 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-be7e85b7-3cf1-495a-83a7-6a28da33af57.jar 1654125839685 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Wed Jun  1 23:33:43 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-f799a103-d544-4a31-a680-1d0625fab2b9.jar 1654126423302 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 01:13:49 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-3edcef03-f7d6-400e-8076-30dc0e5c4bff.jar 1654132429251 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 02:03:29 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-807000a6-0416-4821-b67d-a1e5e433edce.jar 1654135409776 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 02:13:30 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-4f7e7439-7788-4b74-81a2-4d6433caed4b.jar 1654136010028 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 03:03:59 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-038e17f3-7acd-4c19-a212-a095e6c7adba.jar 1654139039870 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 07:43:30 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-b4fb1761-4f97-4ac7-8785-85e2aefbb66c.jar 1654155810868 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 08:33:49 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-ac2c4004-d561-44ad-beca-0883ad8980c5.jar 1654158829119 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 09:44:00 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-31f8b9b4-8f79-47ef-8728-46127baf04a2.jar 1654163040830 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 09:53:00 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-e373b50f-6282-4eaa-a702-57c8f4d0be55.jar 1654163580973 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 10:03:29 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-9b0ac8d3-b446-4ce5-89c1-2591cdeb80e6.jar 1654164209828 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 11:43:43 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-638cbabd-b3ba-46c3-821c-5eb45578c542.jar 1654170223374 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 12:13:43 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-d8fb8058-d3d6-42eb-9e15-5d3682fcc2c7.jar 1654172023366 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 13:02:59 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-46e1ff96-da4d-4936-913a-d477d743027a.jar 1654174979704 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 16:52:43 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-b1b010ee-48d3-4fa5-b6dc-b136a4d54c59.jar 1654188763365 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 17:02:59 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-d11859ec-7750-434b-a7d1-da5ddd2d68c3.jar 1654189379774 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 18:03:00 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-22b34179-5dbd-4bf0-aa5d-c21a978fb8c7.jar 1654192980944 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Thu Jun  2 23:43:43 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-2b564b9c-1727-404e-9e92-edff6b4799a6.jar 1654213423405 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Fri Jun  3 01:13:43 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-c32e9295-abd0-48de-921f-a0d524ca4db2.jar 1654218823466 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Fri Jun  3 05:33:31 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-4f88e716-a620-4897-bc80-89e3bfa2282c.jar 1654234411000 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Fri Jun  3 08:43:31 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-deb4795a-1983-46ea-a6a3-00457d44d523.jar 1654245811327 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa]
Fri Jun  3 10:23:00 2022 [main] INFO o.a.s.c.Blobstore - dep-apeframework-3.11.3-e887952c-2403-484c-ab53-22ff75a26b9a.jar 1654251780168 [o::r--, o::rwa, u:class org.apache.storm.security.auth.NimbusPrincipal:rwa] </pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Antoine Tran" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=antoine.tran">antoine.tran</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3871" target="_blank">Storm blobstore leak space</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=antoine.tran">antoine.tran</a>:</i>
<p>Workaround:</p>
<blockquote><p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
#!/bin/bash
declare -i nowminus30m=<span class="code-quote">"$(date -d <span class="code-quote">'30 minutes ago'</span> +%s)000"</span>
/space/StormApp/current/bin/storm blobstore list 2>&1| grep <span class="code-quote">'o.a.s.c.Blobstore'</span>>blobstore
sort -k7 blobstore>sortedblobstore
<span class="code-keyword">while</span> IFS= read -r line
<span class="code-keyword">do</span>
  declare -i d=$(echo $line | awk <span class="code-quote">'{ print $7}'</span>)
  name=$(echo $line | awk <span class="code-quote">'{ print $6}'</span> )
  echo <span class="code-quote">"$d ? $nowminus30m"</span>
  <span class="code-keyword">if</span> [ $d -lt $nowminus30m ]; then
    echo <span class="code-quote">" delete $name $line "</span>
    /space/StormApp/current/bin/storm blobstore delete $name
  <span class="code-keyword">else</span>
    echo <span class="code-quote">"keep $name $line"</span>
  fi
done < <span class="code-quote">"sortedblobstore"</span>
rm -f blobstore sortedblobstore
</pre>
</div></div>
<p> </p></blockquote>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Does this happen in Storm 2.5.0 or 2.6.0-SNAPSHOT?</p>

**Comment by amobdlp** [comment]
Hi, we have not move yet to Storm 2.6.x, we foressen to do it in the next few weeks in link with the Operation System update.

**Comment by Mikhail-Aoun** [comment]
We tested the fix. Most of the time, our topology dependencies are cleaned up correctly, but sometimes they still remain in the blobstore.

The following suspicious log pattern can be observed in the Nimbus logs when a dependency is not cleaned up:

1. Nimbus log: `"[INFO] Removing dependency blobs of..."`, which indicates the start of the cleanup implemented by the fix.
2. `StormClusterStateImpl` log: `"[INFO] set-path: /blobstore/..."` for the same dependency that was previously removed.

For example, in one of my recent executions:

```text
nimbus.log:2026-09-10 05:14:09.061 o.a.s.c.StormClusterStateImpl [INFO] set-path: /blobstore/dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar/spc-scientificprocessingcluster-sni-stormnimbus-1.storm-nimbus.val.svc.cluster.local:6627:0-2
nimbus.log:2026-09-10 05:14:09.625 o.a.s.d.n.Nimbus [INFO] Created download session 40814946-e3bd-4240-b022-1565057c2fb1 for dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar
nimbus.log:2026-09-10 05:14:09.655 o.a.s.d.n.Nimbus [INFO] Created download session dd541b11-04e0-4f33-9848-5674820445fb for dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar
nimbus.log:2026-09-10 05:14:20.292 o.a.s.d.n.Nimbus [INFO] Created download session 2338a9c0-6fa8-4fca-bb52-60be4ce9e9fb for dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar
nimbus.log:2026-09-10 05:19:38.715 o.a.s.d.n.Nimbus [INFO] Removing dependency blobs of val-ipc-fci-nrt_Clmcla-RCFD_2017100_0096-2354-1789017251 - [dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar]
nimbus.log:2026-09-10 05:20:10.235 o.a.s.c.StormClusterStateImpl [INFO] set-path: /blobstore/dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar/spc-scientificprocessingcluster-sni-stormnimbus-1.storm-nimbus.val.svc.cluster.local:6627:0-0
nimbus.log:2026-09-10 05:20:11.466 o.a.s.c.StormClusterStateImpl [INFO] set-path: /blobstore/dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar/spc-scientificprocessingcluster-sni-stormnimbus-1.storm-nimbus.val.svc.cluster.local:6627:0-1
```

When the dependency is correctly removed, we do not observe the last two `StormClusterStateImpl` log entries:

```text
nimbus.log:2026-09-10 08:35:04.722 o.a.s.c.StormClusterStateImpl [INFO] set-path: /blobstore/dep-apeframework-0.0.11710-SNAPSHOT-8135d1cd-0fd1-4b67-9350-3909723c4078.jar/spc-scientificprocessingcluster-sni-stormnimbus-1.storm-nimbus.val.svc.cluster.local:6627:0-2
nimbus.log:2026-09-10 08:35:04.974 o.a.s.d.n.Nimbus [INFO] Created download session c5c8c393-f6d0-416b-b92d-1eb5bd7f8f46 for dep-apeframework-0.0.11710-SNAPSHOT-8135d1cd-0fd1-4b67-9350-3909723c4078.jar
nimbus.log:2026-09-10 08:35:04.997 o.a.s.d.n.Nimbus [INFO] Created download session 6ec96c26-29fb-446d-acc9-16fd3f6aa63f for dep-apeframework-0.0.11710-SNAPSHOT-8135d1cd-0fd1-4b67-9350-3909723c4078.jar
nimbus.log:2026-09-10 08:35:13.038 o.a.s.d.n.Nimbus [INFO] Created download session f5cae8e4-1a1e-4963-954d-d717e1767bf2 for dep-apeframework-0.0.11710-SNAPSHOT-8135d1cd-0fd1-4b67-9350-3909723c4078.jar
nimbus.log:2026-09-10 08:40:18.801 o.a.s.d.n.Nimbus [INFO] Removing dependency blobs of val-ipc-fci-nrt_Fir-RCFD_2017100_0116-2553-1789029304 - [dep-apeframework-0.0.11710-SNAPSHOT-8135d1cd-0fd1-4b67-9350-3909723c4078.jar]
```

Please do not hesitate to ask if you need more details or additional logs.

**Comment by rzo1** [comment]
Thanks for testing and for the detailed logs. Reopening, since the blob can still leak.

The cleanup does run and deletes the blob. The two `set-path` lines afterwards (`…:0-0`, then `…:0-1`) suggest that the leader recreates it about 30 seconds later: a supervisor's blob update check (default every 30s) calls `getBlobMeta` on the leader, `checkForBlobOrDownload` finds the key registered in ZooKeeper by another Nimbus, and the leader downloads the blob again from that Nimbus. The version numbers `0` and then `1` only fit if another Nimbus had registered the key again (at version `1`) after the leader deleted it. After that, nothing deletes the dependency blob, because the topology is already gone.

To confirm this and find out which step re-registers the key, could you please provide:

1. How many Nimbus instances you run (is there a `stormnimbus-0` besides `stormnimbus-1`?), and which one was the leader at that time.
2. The full `nimbus.log` of **all** Nimbus instances for a failing case, covering the upload through a few minutes after `Removing dependency blobs of …`. Please don't filter by the key: some relevant lines don't contain it (e.g. `Exception` errors logged by `KeySequenceNumber`).
3. If you can, the `supervisor.log` of a supervisor that ran a worker of that topology, for the same time window.

For your excerpt above, that would be roughly 05:13–05:25 for `dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar`.

**Comment by Mikhail-Aoun** [comment]
Thanks for your analysis.

1. We have 3 Nimbus instances: `spc-scientificprocessingcluster-sni-stormnimbus-0` to `spc-scientificprocessingcluster-sni-stormnimbus-2`.

According to the latest relevant `gained leadership` log entry, `stormnimbus-1` was the leader at that time:

```text
logs/nimbus.log.1.gz:2026-09-08 13:04:06.193 o.a.s.z.LeaderListenerCallbackFactory [INFO] spc-scientificprocessingcluster-sni-stormnimbus-1.storm-nimbus.val.svc.cluster.local gained leadership.
```

2. and 3. Please find attached the Nimbus logs and the supervisor log corresponding to the topology execution.

[spc-scientificprocessingcluster-sni-stormnimbus-0.log](https://github.com/user-attachments/files/32055235/spc-scientificprocessingcluster-sni-stormnimbus-0.log)
[spc-scientificprocessingcluster-sni-stormnimbus-1.log](https://github.com/user-attachments/files/32055234/spc-scientificprocessingcluster-sni-stormnimbus-1.log)
[spc-scientificprocessingcluster-sni-stormnimbus-2.log](https://github.com/user-attachments/files/32055236/spc-scientificprocessingcluster-sni-stormnimbus-2.log)
[spc-scientificprocessingcluster-ssu-stormsupervisor-2.log](https://github.com/user-attachments/files/32055233/spc-scientificprocessingcluster-ssu-stormsupervisor-2.log)

**Comment by rzo1** [comment]
Thanks a lot, the logs show what happens. Timeline for `dep-apeframework-0.0.11710-SNAPSHOT-f2d87a33-a8ad-4a95-a567-71e96a2b8695.jar`:

| Time | Instance | What happens |
|---|---|---|
| 05:19:38.715 | nimbus-1 (leader) | `Removing dependency blobs of …Clmcla…`: deletes the blob and its ZooKeeper nodes |
| 05:19:38.823 | nimbus-0 | `Created download session`: nimbus-2 downloads the blob from nimbus-0 |
| 05:19:40.640 | nimbus-2 | `set-path …stormnimbus-2…-1`: registers the key again, from scratch at version 1 |
| 05:19:40.870, 05:19:42.269 | nimbus-0 | downloads it back from nimbus-2, `set-path …-0`, then `…-1` |
| 05:20:09.977 | supervisor-2 | localizer cleanup asks the leader whether the blob still exists |
| 05:20:10.235, 05:20:11.466 | nimbus-1 (leader) | downloads it back from nimbus-2 (download session on nimbus-2 at 05:20:10.233), `set-path …-0`, then `…-1` |

The leader deletes `/blobstore/<key>` child by child, so the delete is not atomic. nimbus-2's blob sync ran in between: its own entry was already gone while nimbus-0's was still there, so it downloaded the blob from nimbus-0 as if it had been updated. By the time it called `createStateInZookeeper`, the key node was gone, and it registered the key again as new. The other instances then copied it back from nimbus-2, including the leader. This also explains why supervisor-2 deletes the topology's jar/code/conf at 05:20:10 but keeps the dependency blob.

The `Could not remove the dependency blobs of …Oca…` warning at 05:21:08 is harmless: the cleanup pass at 05:20:58 had already removed that topology's dependency blob, and the second pass only found the code blob gone.

https://github.com/apache/storm/pull/9082 does two things:
- It stops a non-leader Nimbus from registering a key that was deleted from ZooKeeper.
- It adds a sweep that removes dependency blobs no topology has referred to for `nimbus.inbox.jar.expiration.secs`, which also cleans up blobs that already leaked.

**Comment by rzo1** [comment]
@Mikhail-Aoun the fix is in https://github.com/apache/storm/pull/9082. It stops a non-leader Nimbus from registering a blob again after it was deleted, and it removes dependency blobs that no topology has referred to for `nimbus.inbox.jar.expiration.secs`, so blobs that already leaked get cleaned up too. It would be great if you could try it on your cluster once it is merged, or backport both commits to your build.

**Comment by Mikhail-Aoun** [comment]
Thanks again for digging into this. I built an internal version including the two fixes from #9082 and kicked off a 3-day test. I’ll verify the blobstore at the end of the run and share the results on Monday.

**Comment by reiabreu** [comment]
@Mikhail-Aoun in the interest of including this in the on going 3.1.0 release, I'm going to close the issue. 
Please give us some feedback around your tests. We can always re-open it if needed. 
Thank you

**Comment by Mikhail-Aoun** [comment]
The test completed successfully with those fixes backported to our Storm 2.8.9 version. We no longer have those unexpected `dep-apeframework*` JARs in the blobstore.

For your information, according to the logs from my execution, it seems that the `dep-apeframework*` JAR download attempt is now successfully caught by this exception:

```text
2026-09-13 18:14:37.179 o.a.s.d.n.Nimbus [INFO] Removing dependency blobs of val-ipc-fci-nrt_Fir-RCFD_2017100_0143-4215-1789322971 - [dep-apeframework-0.0.11710-SNAPSHOT-03c571ab-94dd-4925-b1d3-0cc73b3c9a77.jar]
2026-09-13 18:14:37.211 o.a.s.d.n.Nimbus [WARN] begin blob download exception.
KeyNotFoundException(msg:dep-apeframework-0.0.11710-SNAPSHOT-03c571ab-94dd-4925-b1d3-0cc73b3c9a77.jar)
        at org.apache.storm.blobstore.LocalFsBlobStore.getStoredBlobMeta(LocalFsBlobStore.java:273)
        at org.apache.storm.blobstore.LocalFsBlobStore.getBlob(LocalFsBlobStore.java:406)
        at org.apache.storm.daemon.nimbus.Nimbus.beginBlobDownload(Nimbus.java:4124)
        at org.apache.storm.generated.Nimbus$Processor$beginBlobDownload.getResult(Nimbus.java:4753)
        at org.apache.storm.generated.Nimbus$Processor$beginBlobDownload.getResult(Nimbus.java:4724)
        at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:40)
        at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:41)
        at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:171)
```

I’ll get back to you if the problem happens again, but I think this fix has solved it. Thanks again for the update!
