### ISSUE TITLE
[STORM-3915] Fix test failure in JDK 8 and 11 for storm-cassandra

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7697]
<p>Github action for JDK8 fails with message:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (<span class="code-keyword">default</span>-test) on project storm-cassandra: There are test failures.
7150Error:  
7151Error:  Please refer to /home/runner/work/storm/storm/external/storm-cassandra/target/surefire-reports <span class="code-keyword">for</span> the individual test results.
7152Error:  Please refer to dump files (<span class="code-keyword">if</span> any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
7153Error:  ExecutionException The forked VM terminated without properly saying goodbye. VM crash or <span class="code-object">System</span>.exit called?
7154Error:  Command was /bin/sh -c cd /home/runner/work/storm/storm/external/storm-cassandra && /usr/lib/jvm/temurin-8-jdk-amd64/jre/bin/java -Xmx3g -XX:+HeapDumpOnOutOfMemoryError -jar /home/runner/work/storm/storm/external/storm-cassandra/target/surefire/surefirebooter1740914470713932382.jar /home/runner/work/storm/storm/external/storm-cassandra/target/surefire 2023-04-28T18-24-45_882-jvmRun2 surefire38252873504194138tmp surefire_303399085227568856114tmp
7155Error:  Error occurred in starting fork, check output in log
7156Error:  <span class="code-object">Process</span> Exit Code: 1
7157Error:  Crashed tests:
7158Error:  org.apache.storm.cassandra.trident.MapStateTest
7159Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or <span class="code-object">System</span>.exit called?
7160Error:  Command was /bin/sh -c cd /home/runner/work/storm/storm/external/storm-cassandra && /usr/lib/jvm/temurin-8-jdk-amd64/jre/bin/java -Xmx3g -XX:+HeapDumpOnOutOfMemoryError -jar /home/runner/work/storm/storm/external/storm-cassandra/target/surefire/surefirebooter1740914470713932382.jar /home/runner/work/storm/storm/external/storm-cassandra/target/surefire 2023-04-28T18-24-45_882-jvmRun2 surefire38252873504194138tmp surefire_303399085227568856114tmp
7161Error:  Error occurred in starting fork, check output in log
7162Error:  <span class="code-object">Process</span> Exit Code: 1
7163Error:  Crashed tests:
7164Error:  org.apache.storm.cassandra.trident.MapStateTest
7165Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:532)
7166Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:405)
7167Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:321)
7168Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:266)
7169Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
7170Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
7171Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
7172Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
7173Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
7174Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
7175Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
7176Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
7177Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
7178Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
7179Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
7180Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
7181Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
7182Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
7183Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
7184Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
7185Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
7186Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
7187Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
7188Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
7189Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
7190Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
7191Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
7192Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
7193Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
7194Error:  Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or <span class="code-object">System</span>.exit called?
7195Error:  Command was /bin/sh -c cd /home/runner/work/storm/storm/external/storm-cassandra && /usr/lib/jvm/temurin-8-jdk-amd64/jre/bin/java -Xmx3g -XX:+HeapDumpOnOutOfMemoryError -jar /home/runner/work/storm/storm/external/storm-cassandra/target/surefire/surefirebooter1740914470713932382.jar /home/runner/work/storm/storm/external/storm-cassandra/target/surefire 2023-04-28T18-24-45_882-jvmRun2 surefire38252873504194138tmp surefire_303399085227568856114tmp
7196Error:  Error occurred in starting fork, check output in log
7197Error:  <span class="code-object">Process</span> Exit Code: 1
7198Error:  Crashed tests:
7199Error:  org.apache.storm.cassandra.trident.MapStateTest
7200Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
7201Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$700(ForkStarter.java:121)
7202Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:393)
7203Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:370)
7204Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
7205Error:  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
7206Error:  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
7207Error:  	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:750)
7208Error:  -> [Help 1]
7209Error:  
7210Error:  To see the full stack trace of the errors, re-run Maven with the -e <span class="code-keyword">switch</span>.
7211Error:  Re-run Maven using the -X <span class="code-keyword">switch</span> to enable full debug logging.
7212Error:  
7213Error:  For more information about the errors and possible solutions, please read the following articles:
7214Error:  [Help 1] http:<span class="code-comment">//cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
</span>7215Error:  
7216Error:  After correcting the problems, you can resume the build with the command
7217Error:    mvn <args> -rf :storm-cassandra </pre>
</div></div>
<p>JDK11 test fails gives a warning:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by org.github.jamm.MemoryMeter (file:/Users/bprasad/.m2/repository/com/github/jbellis/jamm/0.3.0/jamm-0.3.0.jar) to field java.math.BigInteger.mag
[ERROR] WARNING: Please consider reporting <span class="code-keyword">this</span> to the maintainers of org.github.jamm.MemoryMeter
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a <span class="code-keyword">future</span> release
[INFO] Running org.apache.storm.cassandra.trident.MapStateTest </pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Bipin Prasad" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bipinprasad">bipinprasad</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3915" target="_blank">Fix test failure in JDK 8 and 11 for storm-cassandra</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Bipin Prasad" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bipinprasad">bipinprasad</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2023-08-15T08:28:59+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of upgrading to Cassandra 4 in <a href="https://github.com/apache/storm/pull/3525" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/3525</a></p>

<p>Build switched from 8 to 11 as baseline, so this issue isn't up2date anymore.</p>
