### ISSUE TITLE
[STORM-4000] Processing late tuples from BaseWindowedBolt results in serialization exception

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7782]
<p>I am developing an Apache Storm (v2.5.0) topology that reads events from a spout (<em>BaseRichSpout</em>), counts the number of events in tumbling windows (<em>BaseWindowedBolt</em>), and prints the count (<em>BaseRichBolt</em>). The topology works fine, but there are some out-of-order events in my dataset. The <em>BaseWindowedBolt</em> provides <em>withLateTupleStream</em> method to route late events to a separate stream. However, when I try to process late events, I get a serialization exception:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: <span class="code-object">Class</span> is not registered: org.apache.storm.shade.com.google.common.collect.SingletonImmutableBiMap
Note: To register <span class="code-keyword">this</span> <span class="code-keyword">class </span>use: kryo.register(org.apache.storm.shade.com.google.common.collect.SingletonImmutableBiMap.class);
Serialization trace:
defaultResources (org.apache.storm.task.WorkerTopologyContext)
context (org.apache.storm.tuple.TupleImpl)
    at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101) ~[kryo-4.0.2.jar:?]
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508) ~[kryo-4.0.2.jar:?]
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-4.0.2.jar:?]
    at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79) ~[kryo-4.0.2.jar:?]
    at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508) ~[kryo-4.0.2.jar:?]
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.2.jar:?]
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:100) ~[kryo-4.0.2.jar:?]
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40) ~[kryo-4.0.2.jar:?]
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:557) ~[kryo-4.0.2.jar:?]
    at org.apache.storm.serialization.KryoValuesSerializer.serializeInto(KryoValuesSerializer.java:38) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.serialization.KryoTupleSerializer.serialize(KryoTupleSerializer.java:40) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.daemon.worker.WorkerState.checkSerialize(WorkerState.java:613) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.executor.ExecutorTransfer.tryTransferLocal(ExecutorTransfer.java:101) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.executor.ExecutorTransfer.tryTransfer(ExecutorTransfer.java:66) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.executor.LocalExecutor$1.tryTransfer(LocalExecutor.java:36) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.executor.bolt.BoltOutputCollectorImpl.boltEmit(BoltOutputCollectorImpl.java:112) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.executor.bolt.BoltOutputCollectorImpl.emit(BoltOutputCollectorImpl.java:65) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:93) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:93) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.task.OutputCollector.emit(OutputCollector.java:42) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.topology.WindowedBoltExecutor.execute(WindowedBoltExecutor.java:313) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.executor.bolt.BoltExecutor.tupleActionFn(BoltExecutor.java:212) ~[storm-client-2.5.0.jar:2.5.0]
    at org.apache.storm.executor.Executor.accept(Executor.java:294) ~[storm-client-2.5.0.jar:2.5.0]
    ... 6 more</pre>
</div></div>
<p>I have defined my topology as below:<br/>
 <br/>
 </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> <span class="code-keyword">class </span>TestTopology {
    <span class="code-keyword">public</span> <span class="code-keyword">static</span> void main (<span class="code-object">String</span>[] args) <span class="code-keyword">throws</span> Exception {
Config config = <span class="code-keyword">new</span> Config();
config.put(Config.TOPOLOGY_TESTING_ALWAYS_TRY_SERIALIZE, <span class="code-keyword">true</span>);
config.registerSerialization(TupleImpl.class);
config.registerSerialization(WorkerTopologyContext.class);
config.registerSerialization(Fields.class);
LocalCluster cluster = <span class="code-keyword">new</span> LocalCluster();

<span class="code-keyword">try</span> (LocalCluster.LocalTopology topology = cluster.submitTopology(<span class="code-quote">"testTopology"</span>, config, getTopology().createTopology())) {
    <span class="code-object">Thread</span>.sleep(50000);}
cluster.shutdown();
    }

    <span class="code-keyword">static</span> TopologyBuilder getTopology(){
TopologyBuilder builder = <span class="code-keyword">new</span> TopologyBuilder();
builder.setSpout(<span class="code-quote">"eventSpout"</span>, <span class="code-keyword">new</span> LateEventSpout());
builder.setBolt(<span class="code-quote">"windowBolt"</span>, <span class="code-keyword">new</span> WindowBolt().withTumblingWindow(BaseWindowedBolt.Duration.seconds(10)).
withTimestampField(<span class="code-quote">"time"</span>).
withLateTupleStream(<span class="code-quote">"lateEvents"</span>)).
shuffleGrouping(<span class="code-quote">"eventSpout"</span>);
builder.setBolt(<span class="code-quote">"latePrintBolt"</span>, <span class="code-keyword">new</span> LatePrintBolt()).
shuffleGrouping(<span class="code-quote">"windowBolt"</span>, <span class="code-quote">"lateEvents"</span>);
builder.setBolt(<span class="code-quote">"printBolt"</span>, <span class="code-keyword">new</span> PrintBolt()).shuffleGrouping(<span class="code-quote">"windowBolt"</span>);
<span class="code-keyword">return</span> builder;
    }
}</pre>
</div></div>
<p>Where `LateEventSpout` is</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> <span class="code-keyword">class </span>LateEventSpout <span class="code-keyword">extends</span> BaseRichSpout {

    <span class="code-keyword">private</span> SpoutOutputCollector collector;
    <span class="code-keyword">private</span> List<<span class="code-object">Long</span>> eventTimes;
    <span class="code-keyword">private</span> <span class="code-object">int</span> currentTime = 0;
    <span class="code-keyword">private</span> <span class="code-object">int</span> id = 1;

    <span class="code-keyword">public</span> LateEventSpout () {
eventTimes = <span class="code-keyword">new</span> ArrayList<>();
<span class="code-keyword">for</span> (<span class="code-object">int</span> i = 1; i<= 61; i++) {
    eventTimes.add(Instant.EPOCH.plusSeconds(i).toEpochMilli());
} <span class="code-comment">// eventTimes = [epoch+1, epoch+2, .., epoch+61]
</span>    }

    @Override
    <span class="code-keyword">public</span> void open(Map<<span class="code-object">String</span>, <span class="code-object">Object</span>> conf, TopologyContext context, SpoutOutputCollector collector) {
<span class="code-keyword">this</span>.collector = collector;
    }

    @Override
    <span class="code-keyword">public</span> void nextTuple() {
<span class="code-object">int</span> eventId = id++;
<span class="code-object">Long</span> eventTime = eventTimes.get(currentTime++);
<span class="code-keyword">if</span> (currentTime == eventTimes.size()){
    currentTime = 0;
}
collector.emit(<span class="code-keyword">new</span> Values(eventId, eventTime));
    }
    @Override
    <span class="code-keyword">public</span> void declareOutputFields(OutputFieldsDeclarer declarer) {
declarer.declare(<span class="code-keyword">new</span> Fields(<span class="code-quote">"id"</span>, <span class="code-quote">"time"</span>));
    }
} </pre>
</div></div>
<p>And `WindowBolt` is:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> <span class="code-keyword">class </span>WindowBolt <span class="code-keyword">extends</span> BaseWindowedBolt {

    OutputCollector collector;

    @Override
    <span class="code-keyword">public</span> void prepare(Map<<span class="code-object">String</span>, <span class="code-object">Object</span>> topoConf, TopologyContext context, OutputCollector collector){
<span class="code-keyword">this</span>.collector = collector;
    }

    @Override
    <span class="code-keyword">public</span> void execute(TupleWindow inputWindow) {
<span class="code-object">int</span> sum = 0;
<span class="code-keyword">for</span> (Tuple event : inputWindow.get()){
    sum++;
}
collector.emit(<span class="code-keyword">new</span> Values(inputWindow.getStartTimestamp(), inputWindow.getEndTimestamp(), sum));
    }

    @Override
    <span class="code-keyword">public</span> void declareOutputFields(OutputFieldsDeclarer declarer) {
declarer.declare(<span class="code-keyword">new</span> Fields(<span class="code-quote">"start"</span>, <span class="code-quote">"end"</span>, <span class="code-quote">"sum"</span>));
    }
} </pre>
</div></div>
<p> <br/>
And `PrintBolt` just prints the `windowBolt` output. (`LatePrintBolt` is similar)<br/>
If I don't set the `LatePrintBolt` in `TopologyBuilder`, I get the correct results<br/>
 </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> <span class="code-keyword">class </span>PrintBolt <span class="code-keyword">extends</span> BaseRichBolt {
    @Override
    <span class="code-keyword">public</span> void prepare(Map<<span class="code-object">String</span>, <span class="code-object">Object</span>> topoConf, TopologyContext context, OutputCollector collector) {
    }
    
    @Override
    <span class="code-keyword">public</span> void execute(Tuple input) {
<span class="code-object">System</span>.out.println(<span class="code-object">String</span>.format(<span class="code-quote">"Start: %d, End: %d, Sum:%d"</span>, input.getLongByField(<span class="code-quote">"start"</span>), input.getLongByField(<span class="code-quote">"end"</span>), input.getIntegerByField(<span class="code-quote">"sum"</span>)));
    }
    
    @Override
    <span class="code-keyword">public</span> void declareOutputFields(OutputFieldsDeclarer declarer) {
    }
} </pre>
</div></div>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Start: 0, End: 10000, Sum:10
Start: 10000, End: 20000, Sum:10
Start: 20000, End: 30000, Sum:10
Start: 30000, End: 40000, Sum:10
Start: 40000, End: 50000, Sum:10
Start: 50000, End: 60000, Sum:10 </pre>
</div></div>
<p> <br/>
However, when I try to print lateEvents stream, I get the same output but on the first late event, I get the above-mentioned exception.<br/>
 <br/>
I have debugged the issue. When <a href="https://github.com/apache/storm/blob/18341682ce90976c173ecf9ac68582b1626bda8a/storm-client/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java#L313" class="external-link" target="_blank" rel="nofollow noopener">WindowedBoltExecutor</a> receives a late tuple, it emits the late tuple but <a href="https://github.com/apache/storm/blob/18341682ce90976c173ecf9ac68582b1626bda8a/storm-client/src/jvm/org/apache/storm/executor/bolt/BoltOutputCollectorImpl.java#L110" class="external-link" target="_blank" rel="nofollow noopener">BoltOutputCollectorImpl</a>  rewraps it in a new Tuple. Now, this new tuple contains <em>WorkerTopologyContext,</em> which is not serializable, hence the error.</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Jawad Tahir" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jawadtahir">jawadtahir</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-4000" target="_blank">Processing late tuples from BaseWindowedBolt results in serialization exception</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Does it also happen with 2.6.0 ? We updated Kyro.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER302864">JIRAUSER302864</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1" class="user-hover" rel="rzo1">rzo1</a> ,</p>

<p>Thank you for your response and sorry for the late response, I have been away from my machine.  </p>

<p>I just checked it, and the new version does not solve the problem.</p>

<p> </p>

<p>As far as I understood, the problem is not with serialization but with the wrong implementation of the late tuple management. The input in <a href="https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java#L313" class="external-link" target="_blank" rel="nofollow noopener">WindowBoltExecutor</a> is already a Tuple. The tuple contains WorkerTopologyContext, which is not serializable (some volatile attributes). Hence, the error. In my opinion, we should change the line to </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
windowedOutputCollector.emit(lateTupleStream, input, input.getValues()); </pre>
</div></div>
<p>instead of </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
windowedOutputCollector.emit(lateTupleStream, input, <span class="code-keyword">new</span> Values(input)); </pre>
</div></div>
<p> </p>

<p>What are your thoughts on it?</p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Sounds valid. Do you want to submit a PR with an accompying test for it?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER302864">JIRAUSER302864</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1" class="user-hover" rel="rzo1">rzo1</a> ,</p>

<p> </p>

<p>I have been trying to fix this bug for the past two days. Upon closer inspection, I found that it is a much bigger problem than just changing the parameters of the emit function.</p>

<p>We cannot change it to input.getValues() as we define only one <a href="https://github.com/apache/storm/blob/9a238c448d7849b908b77d929b682e74926c01ac/storm-client/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java#L342" class="external-link" target="_blank" rel="nofollow noopener">output</a> field. By design, it expects a tuple. However, a tuple can never be serialized due to some volatile attributes. Hence, lateTupleStream will only work when there is no serialization.</p>

<p>I think we need the input of original authors <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kosii" class="user-hover" rel="kosii">kosii</a> and <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arunm" class="user-hover" rel="arunm">arunm</a> on how to solve this bug.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Given the late community health and the discussion of moving to the attic earlier this year, I doubt, that there will be much traction from the original authors. If you can think of a good solution, feel free to provide a PR or send a mail to the dev@ list to discuss a proposal in more depth.</p>
