### ISSUE TITLE
[STORM-4003] storm-kafka-monitor fails with Java 17 runtime, missing jakarta.xml.bind dependency

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7785]
No Description

---
<details><summary><i>Originally reported by <a title="Alexandre Vermeerbergen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-4003" target="_blank">storm-kafka-monitor fails with Java 17 runtime, missing jakarta.xml.bind dependency</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Alexandre Vermeerbergen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2023-11-15T15:28:33+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=avermeerbergen">avermeerbergen</a>:</i>
<p>Without this fix, when running Storm UI with Java 17 runtime, we have this kind of exceptions in ui.log whenever there is a topology consuming Kafka topics:</p>

<p> </p>

<p>2023-11-15 10:54:27.473 o.e.j.s.AbstractConnector main <span class="error">&#91;INFO&#93;</span> Started<br/>
ServerConnector@e3c9c02f{HTTP/1.1, (http/1.1)}</p>
{[0.0.0.0:8070|http://0.0.0.0:8070/]}
<p>2023-11-15 10:54:27.474 o.e.j.s.Server main <span class="error">&#91;INFO&#93;</span> Started @4256ms<br/>
2023-11-15 10:55:02.781 o.a.s.u.NimbusClient qtp-1075191296-25 <span class="error">&#91;INFO&#93;</span><br/>
Found leader nimbus :<br/>
<a href="http://ec23-1-251-0-65.eu-west-1.compute.amazonaws.com:6627/" class="external-link" target="_blank" rel="nofollow noopener">ec23-1-251-0-65.eu-west-1.compute.amazonaws.com:6627</a><br/>
2023-11-15 10:59:31.128 o.a.s.u.ShellUtils qtp-1075191296-24 <span class="error">&#91;INFO&#93;</span><br/>
Failed running command<br/>
[/usr/local/Storm/storm-stable/bin/storm-kafka-monitor, -t, audit, -g,<br/>
StormAuditPublisherTopology_SbxRealTimeSupervisionAVEEEZZeuw1, -b,<br/>
<a href="http://ec23-1-251-0-66.eu-west-1.compute.amazonaws.com/" class="external-link" target="_blank" rel="nofollow noopener">ec23-1-251-0-66.eu-west-1.compute.amazonaws.com</a>,[ec23-1-251-0-65.eu-west-1.compute.amazonaws.com|http://ec23-1-251-0-65.eu-west-1.compute.amazonaws.com/],ec2-52-18-172-77,<br/>
-s, SASL_SSL, -c, /tmp/kafka-consumer-extra6421423768198678110props]<br/>
org.apache.storm.utils.ShellUtils$ExitCodeException: SLF4J: Failed to<br/>
load class "org.slf4j.impl.StaticLoggerBinder".<br/>
SLF4J: Defaulting to no-operation (NOP) logger implementation<br/>
SLF4J: See <a href="http://www.slf4j.org/codes.html#StaticLoggerBinder" class="external-link" target="_blank" rel="nofollow noopener">http://www.slf4j.org/codes.html#StaticLoggerBinder</a> for<br/>
further details.<br/>
Exception in thread "main" java.lang.NoClassDefFoundError:<br/>
javax.xml.bind.DatatypeConverter<br/>
 at org.apache.kafka.common.security.scram.ScramMessages$ServerFirstMessage.<init>(ScramMessages.java:143)<br/>
 at org.apache.kafka.common.security.scram.ScramSaslClient.evaluateChallenge(ScramSaslClient.java:112)<br/>
 at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator$2.run(SaslClientAuthenticator.java:280)<br/>
 at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator$2.run(SaslClientAuthenticator.java:278)<br/>
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)<br/>
 at java.base/javax.security.auth.Subject.doAs(Subject.java:439)<br/>
 at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:278)<br/>
 at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslToken(SaslClientAuthenticator.java:215)<br/>
 at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:189)<br/>
 at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:76)<br/>
 at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:385)<br/>
 at org.apache.kafka.common.network.Selector.poll(Selector.java:334)<br/>
 at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:433)<br/>
 at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)<br/>
 at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:208)<br/>
 at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:184)<br/>
 at org.apache.kafka.clients.consumer.internals.Fetcher.getTopicMetadata(Fetcher.java:314)<br/>
 at org.apache.kafka.clients.consumer.KafkaConsumer.partitionsFor(KafkaConsumer.java:1386)<br/>
 at org.apache.storm.kafka.monitor.KafkaOffsetLagUtil.getOffsetLags(KafkaOffsetLagUtil.java:165)<br/>
 at org.apache.storm.kafka.monitor.KafkaOffsetLagUtil.main(KafkaOffsetLagUtil.java:74)<br/>
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter<br/>
 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:827)<br/>
 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)<br/>
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1095)<br/>
 ... 20 more</p>

<p>Plan to fix consists in making a change so that jakarta.xml.bind-api<version>.jar will be available in lib-tools/storm-kafka-monitor/ of the runtime-view.</p>

<p> </p>

<p> </p>
