### ISSUE TITLE
[STORM-4023] Background periodic Kerberos re-login should use same JAAS configuration as initial login

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7804]
<p>In the <a href="https://github.com/apache/storm/blob/v2.6.0/storm-client/src/jvm/org/apache/storm/messaging/netty/Login.java" class="external-link" target="_blank" rel="nofollow noopener">Login</a> class, a background thread is started that periodically performs a re-login to the Kerberos Ticket Granting Server.</p>

<p>For the initial login, a custom Configuration instance is <a href="https://github.com/apache/storm/blob/v2.6.0/storm-client/src/jvm/org/apache/storm/messaging/netty/Login.java#L257" class="external-link" target="_blank" rel="nofollow noopener">created</a> and <a href="https://github.com/apache/storm/blob/v2.6.0/storm-client/src/jvm/org/apache/storm/messaging/netty/Login.java#L300" class="external-link" target="_blank" rel="nofollow noopener">supplied to the LoginContext constructor</a> potentially using a custom JAAS file location.</p>

<p>However, the background refresh thread does not then subsequently provide the JAAS file location or Configuration to the <a href="https://github.com/apache/storm/blob/v2.6.0/storm-client/src/jvm/org/apache/storm/messaging/netty/Login.java#L222" class="external-link" target="_blank" rel="nofollow noopener">reLogin method</a>, so it tries to construct a LoginContext with <a href="https://github.com/apache/storm/blob/v2.6.0/storm-client/src/jvm/org/apache/storm/messaging/netty/Login.java#L409" class="external-link" target="_blank" rel="nofollow noopener">just a context name and subject</a> but no Configuration parameter, which means that the underlying <tt>Configuration.getConfiguration()</tt> call has to load one from <a href="https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/jdk-11%2B28/src/java.base/share/classes/javax/security/auth/login/LoginContext.java#L242" class="external-link" target="_blank" rel="nofollow noopener">system defaults</a>, which could possibly specify a different file or none at all.</p>

<p>In our application where this issue was found, we had set the <tt>java.security.auth.login.config</tt> value to a valid JAAS file location as a Storm client property along with other standard connectivity properties, since the <a href="https://github.com/apache/storm/blob/v2.6.0/storm-client/src/jvm/org/apache/storm/messaging/netty/KerberosSaslNettyClient.java#L61" class="external-link" target="_blank" rel="nofollow noopener">Netty client framework</a> loads it <a href="https://github.com/apache/storm/blob/v2.6.0/storm-client/src/jvm/org/apache/storm/security/auth/ClientAuthUtils.java#L64" class="external-link" target="_blank" rel="nofollow noopener">from the topology configuration</a>. It looks like the Netty server framework <a href="https://github.com/apache/storm/blob/v2.6.0/storm-client/src/jvm/org/apache/storm/messaging/netty/KerberosSaslNettyServer.java#L55" class="external-link" target="_blank" rel="nofollow noopener">does the same</a> as well. The initial login succeeded and the following Storm Nimbus interactions were successful, but a while later it lost the ability to communicate with Storm with this error being logged,</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>ERROR [Refresh-TGT] org.apache.storm.messaging.netty.Login Could not refresh TGT for principal: <REDACTED>
javax.security.auth.login.LoginException: No LoginModules configured for StormClient
   at java.base/javax.security.auth.login.LoginContext.init(LoginContext.java:267)
   at java.base/javax.security.auth.login.LoginContext.<init>(LoginContext.java:385)
   at org.apache.storm.messaging.netty.Login.reLogin(Login.java:409)
   at org.apache.storm.messaging.netty.Login$1.run(Login.java:222)
   at java.base/java.lang.Thread.run(Thread.java:829)
</pre>
</div></div>
<p>It appears that a viable workaround for this issue is to also set the system property,</p>

<p><tt>-Djava.security.auth.login.config=/some/path/jaas.conf</tt></p>

<p>for the application, referencing the same JAAS file location as was set in the Storm configuration. After doing so the background refresh thread was able to correctly function in our situation.</p>

<p>To address this, we can update the <tt>reLogin</tt> method to use the same JAAS configuration. Furthermore it should use the same callback handler instance that was originally provided also, instead of creating a new default one.</p>

---
<details><summary><i>Originally reported by <a title="Andrew Olson" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=noslowerdna">noslowerdna</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-4023" target="_blank">Background periodic Kerberos re-login should use same JAAS configuration as initial login</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2024-01-25T10:22:45+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=noslowerdna">noslowerdna</a>:</i>
<p>I'm currently working on a patch for this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=noslowerdna">noslowerdna</a>:</i>
<p>Pull request: <a href="https://github.com/apache/storm/pull/3619" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/3619</a></p>
