### ISSUE TITLE
[STORM-4036] Apache Storm 2.5.0 not able to start with Kafka 3.6.1 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7817]
<p>Hi Team,</p>

<p>We are trying to use Apache Storm to pump in data using Kafka to another component. But as soon as we add the Kafka.properties to the storm conf folder, NMStormTopology and other processes fails with following error</p>

<p>Exception in thread "main" java.lang.NoClassDefFoundError: org.apache.kafka.clients.producer.Producer<br/>
at com.ibm.csi.nm.storm.app.NMStormTopology.validateKafkaConnection(NMStormTopology.java:126)<br/>
at com.ibm.csi.nm.storm.app.NMStormTopology.main(NMStormTopology.java:170)<br/>
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.Producer<br/>
at java.net.URLClassLoader.findClass(URLClassLoader.java:610)<br/>
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:948)<br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:893)<br/>
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:353)<br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:876)</p>

<p>We first start Kafka 3.6.1 server and then start storm 2.5.0.</p>

<p>We are trying to understand which version of Kafka is compatible Storm 2.5.0? or this is a bug in storm which is not able to integrate with Kafka 3.6.1?</p>

<p>with earlier version we didn't this issue but with this version we are seeing this. Help us to understand how to resolve this issue.</p>

---
<details><summary><i>Originally reported by <a title="Adarsh Shukla" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adisang">adisang</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-4036" target="_blank">Apache Storm 2.5.0 not able to start with Kafka 3.6.1 </a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Can you test with Storm 2.6.1 ? We updated the Kafka version, cf. <a href="https://storm.apache.org/2024/02/02/storm261-released.html" class="external-link" target="_blank" rel="nofollow noopener">https://storm.apache.org/2024/02/02/storm261-released.html</a></p>
