### ISSUE TITLE
[STORM-4055] ConcurrentModificationException on KafkaConsumer when running topology with Metrics Reporters

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7836]
<p>After a recent upgrade to storm-kafka-client on storm server 2.6.1, we are seeing ConcurrentModificationException in our topology at runtime. I believe this is due to the re-use of a KafkaConsumer instance between the KafkaSpout and the <br/>
KafkaOffsetPartitionMetrics which were added some time between 2.4.0 and 2.6.1.<br/>
 </p>
<h3><a name="StepstoReproduce%3A"></a>Steps to Reproduce:</h3>

<p>Configure a topology with a basic KafkaSpout. Configure the topology with one of the metrics loggers. We used our own custom one, but reproduced it with ConsoleStormReporter as well. The JMXReporter did not reproduce the issue for us, but we did not dig into why.</p>

<p><b>reporter config:</b></p>

<p><tt>topology.metrics.reporters: [</tt><br/>
<tt>  {</tt><br/>
<tt>    "filter": {</tt><br/>
<tt>      "expression": ".*",</tt><br/>
<tt>      "class": "org.apache.storm.metrics2.filters.RegexFilter"</tt><br/>
<tt>    },</tt><br/>
<tt>    "report.period": 15,</tt><br/>
<tt>    "report.period.units": "SECONDS",</tt><br/>
<tt>    "class": "org.apache.storm.metrics2.reporters.ConsoleStormReporter"</tt></p>

<p>    }<br/>
<tt>]</tt></p>
<h3><a name="Stacktrace%3A"></a>Stacktrace:</h3>
<blockquote><p><span class="error">&#91;ERROR&#93;</span> Exception thrown from NewRelicReporter#report. Exception was suppressed.<br/>
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access. currentThread(name: metrics-newRelicReporter-1-thread-1, id: 24) otherThread(id: 40)<br/>
    at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2484) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2465) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at org.apache.kafka.clients.consumer.KafkaConsumer.beginningOffsets(KafkaConsumer.java:2144) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at org.apache.kafka.clients.consumer.KafkaConsumer.beginningOffsets(KafkaConsumer.java:2123) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at org.apache.storm.kafka.spout.metrics2.KafkaOffsetPartitionMetrics.getBeginningOffsets(KafkaOffsetPartitionMetrics.java:181) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at org.apache.storm.kafka.spout.metrics2.KafkaOffsetPartitionMetrics$2.getValue(KafkaOffsetPartitionMetrics.java:93) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at org.apache.storm.kafka.spout.metrics2.KafkaOffsetPartitionMetrics$2.getValue(KafkaOffsetPartitionMetrics.java:90) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at com.codahale.metrics.newrelic.transformer.GaugeTransformer.transform(GaugeTransformer.java:60) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at com.codahale.metrics.newrelic.NewRelicReporter.lambda$transform$0(NewRelicReporter.java:154) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.TreeMap$EntrySpliterator.forEachRemaining(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~<span class="error">&#91;?:?&#93;</span><br/>
    at com.codahale.metrics.newrelic.NewRelicReporter.report(NewRelicReporter.java:138) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
    at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:243) ~<span class="error">&#91;metrics-core-3.2.6.jar:3.2.6&#93;</span><br/>
    at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:182) <span class="error">&#91;metrics-core-3.2.6.jar:3.2.6&#93;</span><br/>
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) <span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) <span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) <span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) <span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) <span class="error">&#91;?:?&#93;</span><br/>
    at java.base/java.lang.Thread.run(Unknown Source) <span class="error">&#91;?:?&#93;</span></p></blockquote>
<h3><a name="Workaround"></a>Workaround</h3>

<p>Configure the with RegexFilter or similar that excludes the KafkaOffsetPartitionMetrics.</p>
<h3><a name="Impact"></a>Impact</h3>

<p>I am concerned that depending on the timing of the access to the spout that the offending metric could fast forward or rewind the spout. I did not do any further testing to see if the lock could be mis-managed in such a way that the spout is directly impacted, but it is feasible. Impact may need to be adjusted if it is confirmed that a simple metric reporter could result in skipping events or re-processing them.</p>
<h3><a name="PotentialCodeIssues%3A"></a>Potential Code Issues:</h3>

<p><b>KafkaSpout.java</b></p>

<p><tt>private transient Consumer<K, V> consumer;</tt><br/>
<tt>...</tt></p>

<p><tt>public void open(Map<String, Object> conf, TopologyContext context, SpoutOutputCollector collector) {</tt><br/>
<tt>        ...</tt><br/>
<tt>        //this consumer will be used by the spout everywhere</tt><br/>
<tt>        consumer = kafkaConsumerFactory.createConsumer(kafkaSpoutConfig.getKafkaProps());</tt><br/>
<tt>        tupleListener.open(conf, context);</tt><br/>
<tt>        this.kafkaOffsetMetricManager</tt><br/>
<tt>            = new KafkaOffsetMetricManager<>(() -> Collections.unmodifiableMap(offsetManagers), () -> consumer, context);</tt></p>

<p>() -> consumer does not appear to be a safe provider.  It re-uses the same instance of the KafkaConsumer as the KafkaSpout in another thread and KafkaConsumer is not thread safe.</p>

<p><b>KafkaOffsetPartitionMetrics.java: getBeginningOffsets, getEndOffsets</b>{<tt>}</tt></p>

<p> </p>

<p> </p>

<p><tt>private Map<TopicPartition, Long> getBeginningOffsets(Set<TopicPartition> topicPartitions) {</tt><br/>
<tt>    Consumer<K, V> consumer = consumerSupplier.get();</tt><br/>
<tt>    ...</tt><br/>
<tt>    try {</tt><br/>
<tt>        // This will actually try to modify the KafkaSpout instance of the consumer which could negatively impact the spout</tt><br/>
<tt>        beginningOffsets = consumer.beginningOffsets(topicPartitions);</tt></p>

<p>{<br class="atl-forced-newline" /></p>
{    }
<p>}}<br/>
<tt>    ...</tt><br/>
<tt>}</tt><tt>private Map<TopicPartition, Long> getEndOffsets(Set<TopicPartition> topicPartitions) {</tt><br/>
<tt>    Consumer<K, V> consumer = consumerSupplier.get();</tt><br/>
<tt>    ...</tt><br/>
<tt>    try {</tt><br/>
<tt>        // This will actually try to modify the KafkaSpout instance of the consumer which could negatively impact the spout</tt><br/>
<tt>        endOffsets = consumer.endOffsets(topicPartitions);</tt></p>
{\{    }

<p>}}<br/>
<tt>    ...</tt><br/>
<tt>}</tt></p>

---
<details><summary><i>Originally reported by <a title="Anthony Castrati" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=castratia">castratia</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-4055" target="_blank">ConcurrentModificationException on KafkaConsumer when running topology with Metrics Reporters</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2024-11-18T18:41:53+00:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Thanks for the report. Since you have already dived into the code, would you be willing to provide a PR to fix ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER305281">JIRAUSER305281</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1" class="user-hover" rel="rzo1">Richard Zowalla</a>  I would be happy to provide a PR for fix. It would be my first contribution to this code base, so I will want to take some time with it to ensure no other regressions. At the moment it is just difficult to find the time to pick this up now that we have a workaround. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rabreu">rabreu</a>:</i>
<p>Fixed by: <a href="https://github.com/apache/storm/pull/3691" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/3691</a></p>
